import type { StrengthenedLesson } from "../strengthenedLessonSchema";

export type DistributionInferenceChallenge = {
  prompt: string;
  expected: string;
  hint: string;
  kind: "numeric" | "keywords" | "interaction";
  factoryId: string;
};

type FormulaSeed = {
  label: string;
  expression: string;
  variables: Array<{ symbol: string; meaning: string }>;
  restrictions?: string[];
  exactness?: "exact" | "approximation" | "definition" | "theorem" | "identity";
};

type Seed = {
  id: number;
  title: string;
  slug: string;
  topic: "Probability and Distributions" | "Inferential Statistics";
  lessonType: StrengthenedLesson["lessonType"];
  definition: string;
  action: string;
  reason: string;
  representation: "table" | "distribution_plot" | "probability_simulation" | "sampling_animation";
  misconception: [string, string, string];
  examples: [string, string][];
  challenge: DistributionInferenceChallenge;
  formula?: FormulaSeed;
};

const data: Record<number, Seed> = {
  523: item(523, "Hypergeometric Distribution", "hypergeometric-distribution", "Probability and Distributions", "concept", "The hypergeometric distribution counts successes in draws without replacement from a finite group.", "Check population size, success count, draw count, and no replacement before calculating.", "Probabilities change after each draw because items are not replaced.", "distribution_plot", ["USED_BINOMIAL", "Using binomial when draws are without replacement.", "Use hypergeometric when the population is finite and draws are without replacement."], [["Cards", "Drawing aces without replacement changes later chances."], ["Quality checks", "Inspecting items from a small batch changes what remains."], ["Committee selection", "Selecting people without replacement is hypergeometric."]], "Hypergeometric draws are with or without replacement?", "without"),
  524: item(524, "Poisson Distribution", "poisson-distribution", "Probability and Distributions", "concept", "The Poisson distribution models counts of events in a fixed time, area, or space when events occur at an average rate.", "Identify the average rate, choose the interval, and count events in that interval.", "It works when events are rare, independent enough, and the rate is roughly constant.", "distribution_plot", ["NO_INTERVAL", "Naming a rate without saying the interval.", "Always connect the rate to a fixed interval."], [["Calls per hour", "A help desk can model call counts."], ["Typos per page", "A page has a count of errors."], ["Cars per minute", "Traffic counts can use a rate."]], "Poisson models counts in a fixed what?", "interval", { label: "Poisson probability", expression: "P(X=k)=e^(-lambda)lambda^k/k!", variables: [{ symbol: "lambda", meaning: "mean count in the interval" }, { symbol: "k", meaning: "event count" }], restrictions: ["lambda > 0; k is a non-negative integer."], exactness: "definition" }),
  525: item(525, "Geometric Distribution", "geometric-distribution", "Probability and Distributions", "concept", "The geometric distribution models the trial number of the first success in repeated independent Bernoulli trials.", "Check independent trials with the same success probability, then count until the first success.", "Each failed trial resets the same chance for the next trial.", "distribution_plot", ["COUNT_FAILURES_ONLY", "Confusing trial number with number of failures before success.", "State which convention the question uses before calculating."], [["Free throws", "Count shots until the first make."], ["Coin tosses", "Count tosses until first head."], ["Quality testing", "Count items until first defective item."]], "Geometric distribution waits for the first what?", "success", { label: "Geometric probability", expression: "P(X=k)=(1-p)^(k-1)p", variables: [{ symbol: "p", meaning: "success probability" }, { symbol: "k", meaning: "trial number of first success" }], restrictions: ["0 < p <= 1; k is a positive integer."], exactness: "definition" }),
  526: item(526, "Negative Binomial Distribution", "negative-binomial-distribution", "Probability and Distributions", "concept", "The negative binomial distribution models the trial number or failure count needed to reach a fixed number of successes.", "Check independent trials, same success probability, and a fixed target number of successes.", "It extends the geometric distribution from one success to several successes.", "distribution_plot", ["NO_TARGET", "Forgetting the target number of successes.", "Negative binomial needs a fixed success target."], [["Sales calls", "Count calls until 5 sales."], ["Free throws", "Count attempts until 10 makes."], ["Testing", "Count failures before 3 successes."]], "Negative binomial needs a fixed target number of what?", "successes"),
  527: item(527, "Uniform Distribution", "uniform-distribution", "Probability and Distributions", "concept", "A uniform distribution gives equal probability to all allowed outcomes or equal density across an interval.", "Identify the allowed outcomes or interval, then spread probability evenly.", "No outcome is favoured over another within the allowed range.", "distribution_plot", ["OUTSIDE_RANGE", "Giving probability to values outside the allowed range.", "Uniform probability only covers the stated range."], [["Fair die", "Each face has equal probability."], ["Random time from 0 to 10 minutes", "Every equal-length interval is equally likely."], ["Spinner with equal sectors", "Each sector has the same chance."]], "In a uniform distribution, allowed outcomes are equally what?", "likely"),
  528: item(528, "Normal Distribution", "normal-distribution", "Probability and Distributions", "concept", "The normal distribution is a symmetric bell-shaped distribution described by its mean and standard deviation.", "Locate the mean, use standard deviation for spread, and use areas for probabilities.", "Many sums and averages become approximately normal under suitable conditions.", "distribution_plot", ["ALL_BELL_NORMAL", "Assuming every bell-shaped graph is exactly normal.", "Check context, symmetry, and distribution assumptions."], [["Heights", "Adult heights are often roughly normal in one group."], ["Measurement error", "Small random errors can be roughly normal."], ["Sample means", "Large-sample means often become normal."]], "The normal distribution is symmetric around its what?", "mean"),
  529: item(529, "Student t Distribution", "student-t-distribution", "Probability and Distributions", "concept", "The Student t distribution is a bell-shaped distribution with heavier tails than the normal distribution.", "Use it for mean inference when population standard deviation is unknown and conditions are suitable.", "Heavier tails account for extra uncertainty from estimating standard deviation with sample data.", "distribution_plot", ["USE_Z_ALWAYS", "Using z methods when the population standard deviation is unknown.", "Use t methods for mean inference with unknown population standard deviation."], [["Small sample mean", "A t interval estimates a mean."], ["Lab measurements", "Unknown spread calls for t methods."], ["Before-after data", "Mean difference can use t."]], "The t distribution has heavier what than the normal?", "tails"),
  530: item(530, "Chi-Square Distribution", "chi-square-distribution", "Probability and Distributions", "concept", "The chi-square distribution is a right-skewed distribution used with sums of squared standard normal values.", "Use degrees of freedom and read right-tail areas for common tests.", "Squaring makes values non-negative, so the distribution starts at zero.", "distribution_plot", ["NEGATIVE_CHI", "Expecting chi-square values to be negative.", "Chi-square values are never negative."], [["Goodness-of-fit", "It compares observed and expected counts."], ["Independence test", "It checks category association."], ["Variance inference", "It can test a population variance."]], "Can a chi-square statistic be negative?", "no"),
  531: item(531, "F Distribution", "f-distribution", "Probability and Distributions", "concept", "The F distribution is a right-skewed distribution used for ratios of variance estimates.", "Use numerator and denominator degrees of freedom before reading probabilities.", "Variance ratios are non-negative, so F values cannot be negative.", "distribution_plot", ["ONE_DF", "Using only one degrees-of-freedom value.", "F distributions need numerator and denominator degrees of freedom."], [["ANOVA", "F compares between-group and within-group variation."], ["Variance tests", "F can compare two variances."], ["Regression", "F can test overall model fit."]], "F distributions need how many degrees-of-freedom values?", "two"),
  532: item(532, "Exponential Distribution", "exponential-distribution", "Probability and Distributions", "concept", "The exponential distribution models waiting time until the next event in a Poisson process.", "Identify the event rate, then calculate probabilities for waiting times.", "It is memoryless, meaning past waiting does not change the remaining waiting-time distribution.", "distribution_plot", ["COUNT_NOT_TIME", "Using exponential distribution for counts instead of waiting times.", "Use Poisson for counts and exponential for waiting time."], [["Bus arrivals", "Waiting time can be exponential if arrivals follow a Poisson process."], ["Machine failure", "Time until failure can be modelled."], ["Radioactive decay", "Waiting time to decay can use this model."]], "Exponential distribution models count or waiting time?", "waiting time"),
  533: item(533, "Gamma Distribution", "gamma-distribution", "Probability and Distributions", "concept", "The gamma distribution models waiting time until several events occur in a Poisson process.", "Set the shape for the target number of events and the rate or scale parameter.", "It generalises the exponential distribution from one event to several events.", "distribution_plot", ["ONE_EVENT_ONLY", "Using gamma but thinking it only waits for one event.", "Exponential is the one-event case of gamma."], [["Call centre", "Time until 5 calls can be gamma."], ["Reliability", "Time until several failures may be modelled."], ["Rain events", "Time until a target number of storms can use gamma."]], "Gamma generalises exponential to several what?", "events"),
  534: item(534, "Weibull Distribution", "weibull-distribution", "Probability and Distributions", "concept", "The Weibull distribution models lifetimes where failure risk can increase, decrease, or stay constant.", "Choose shape and scale parameters, then interpret the failure-rate pattern.", "The shape parameter controls how risk changes over time.", "distribution_plot", ["ALWAYS_CONSTANT_RISK", "Assuming failure risk must stay constant.", "Weibull can model increasing, decreasing, or constant risk."], [["Machine parts", "Wear-out failures often increase with time."], ["Light bulbs", "Lifetime can follow a Weibull shape."], ["Medical survival", "Time-to-event data can use Weibull models."]], "Which parameter controls Weibull risk shape?", "shape"),
  535: item(535, "Standardisation", "standardisation", "Probability and Distributions", "procedure", "Standardisation changes a value into a z-score by measuring distance from the mean in standard deviations.", "Subtract the mean, then divide by the standard deviation.", "It lets values from different scales be compared on one standard scale.", "distribution_plot", ["SKIP_DIVIDE", "Subtracting the mean but not dividing by standard deviation.", "A z-score needs both centering and scaling."], [["Test scores", "Compare scores from different exams."], ["Heights", "See how unusual a height is."], ["Manufacturing", "Check how far a part is from target."]], "Standardisation subtracts the mean and divides by what?", "standard deviation", { label: "Z-score", expression: "z=(x-mu)/sigma", variables: [{ symbol: "x", meaning: "value" }, { symbol: "mu", meaning: "mean" }, { symbol: "sigma", meaning: "standard deviation" }], restrictions: ["sigma must be greater than 0."], exactness: "definition" }),
  536: item(536, "Distribution Simulation", "distribution-simulation", "Probability and Distributions", "tool", "Distribution simulation generates random values from a chosen probability distribution.", "Choose the model, set valid parameters, generate samples, and compare the simulated shape with theory.", "Simulation shows how random samples vary around the theoretical distribution.", "probability_simulation", ["SIM_EQUALS_EXACT", "Thinking one simulation is the exact distribution.", "A simulation is random evidence; the theoretical distribution is the model."], [["Dice simulation", "Many rolls approach the die distribution."], ["Normal samples", "Simulated values form a bell shape."], ["Queue model", "Random waiting times estimate service behaviour."]], "Is one simulation exactly the same as the theoretical model?", "no"),
  537: item(537, "Sampling Distributions", "sampling-distributions", "Inferential Statistics", "concept", "A sampling distribution is the distribution of a statistic over many possible samples.", "Take many equal-size samples, compute the statistic each time, and study the statistic values.", "Statistics vary from sample to sample, and their pattern tells us uncertainty.", "sampling_animation", ["DATA_DISTRIBUTION_CONFUSED", "Confusing the raw data distribution with the sampling distribution.", "A sampling distribution is about statistics from samples, not individual data values."], [["Sample means", "Many sample means form a sampling distribution."], ["Poll proportions", "Many sample proportions vary around the true proportion."], ["Quality samples", "Sample defect rates vary by sample."]], "Sampling distributions describe sample statistics or raw values?", "statistics"),
  538: item(538, "Central Limit Theorem", "central-limit-theorem", "Inferential Statistics", "concept", "The central limit theorem says sample means tend to be approximately normal for large samples under suitable conditions.", "Take large independent samples, compute their means, and compare the mean distribution with a normal shape.", "Averages smooth random variation, so their distribution becomes more regular.", "sampling_animation", ["RAW_DATA_NORMAL", "Thinking the raw data must be normal.", "The theorem is about sample means, not always the raw data."], [["Average delivery time", "Means from many samples become more normal."], ["Poll averages", "Large-sample averages are often nearly normal."], ["Factory measurements", "Sample means vary less than individual parts."]], "The central limit theorem is mainly about sample what?", "means"),
  539: item(539, "Confidence Interval for Mean", "confidence-interval-for-mean", "Inferential Statistics", "procedure", "A confidence interval for a mean estimates a population mean with a margin of error.", "Compute sample mean, standard error, critical value, and margin of error.", "Repeated correct intervals capture the true mean at the stated long-run rate.", "sampling_animation", ["PROB_TRUE_MEAN_MOVES", "Saying there is a fixed probability the true mean is inside after data are observed.", "The method has long-run capture rate; the fixed interval either contains the mean or not."], [["Average height", "Estimate the population mean height."], ["Mean battery life", "Estimate average battery life."], ["Average commute", "Estimate a city mean commute time."]], "A confidence interval estimates a population what?", "mean"),
  540: item(540, "Confidence Interval for Proportion", "confidence-interval-for-proportion", "Inferential Statistics", "procedure", "A confidence interval for a proportion estimates a population fraction or percent.", "Compute sample proportion, standard error, critical value, and margin of error.", "Sample proportions vary, so the interval shows plausible population proportions.", "sampling_animation", ["COUNT_AS_PROPORTION", "Using the success count without dividing by sample size.", "Use p-hat = successes divided by sample size."], [["Voter support", "Estimate the proportion supporting a choice."], ["Defective items", "Estimate defect rate."], ["Survey preference", "Estimate percent choosing an option."]], "p-hat equals successes divided by what?", "sample size"),
  541: item(541, "Difference of Means Interval", "difference-of-means-interval", "Inferential Statistics", "procedure", "A difference of means interval estimates the difference between two population means.", "Compute the two sample means, subtract them, and add a margin of error for the difference.", "Two samples have uncertainty, so both contribute to the interval width.", "sampling_animation", ["PAIRED_AS_INDEPENDENT", "Using a two-sample interval for naturally paired data.", "Use a paired method when observations are matched."], [["Two teaching methods", "Estimate difference in mean scores."], ["Two machines", "Compare average output."], ["Two routes", "Estimate mean travel-time difference."]], "This interval estimates a difference between two population what?", "means"),
  542: item(542, "Difference of Proportions Interval", "difference-of-proportions-interval", "Inferential Statistics", "procedure", "A difference of proportions interval estimates the difference between two population proportions.", "Compute two sample proportions, subtract them, and use a standard error for the difference.", "Each sample proportion varies, so the difference has its own uncertainty.", "sampling_animation", ["POOL_FOR_INTERVAL", "Pooling proportions for a confidence interval without reason.", "For ordinary intervals, use separate sample proportions in the standard error."], [["Two brands", "Compare defect proportions."], ["Two cities", "Compare support rates."], ["Two treatments", "Compare success proportions."]], "This interval compares two population what?", "proportions"),
  543: item(543, "One-Sample z-Test", "one-sample-z-test", "Inferential Statistics", "procedure", "A one-sample z-test tests a population mean or proportion using a standard normal reference when z conditions are met.", "State hypotheses, compute the z statistic, find the p-value, and compare with alpha.", "Standardising the statistic shows how unusual it is if the null hypothesis is true.", "distribution_plot", ["NO_CONDITIONS", "Using a z-test without checking conditions.", "Check independence, sample size, and known standard deviation or proportion conditions."], [["Known sigma mean test", "Test a mean when population standard deviation is known."], ["Proportion test", "Test one population proportion."], ["Manufacturing target", "Test whether a process mean changed."]], "A z-test compares the statistic with which standard distribution?", "normal"),
  544: item(544, "One-Sample t-Test", "one-sample-t-test", "Inferential Statistics", "procedure", "A one-sample t-test tests a population mean when population standard deviation is unknown.", "State hypotheses, compute t from sample mean and sample standard deviation, then find the p-value.", "The t distribution accounts for estimating spread from the sample.", "distribution_plot", ["USE_POP_SIGMA", "Pretending population standard deviation is known when it is not.", "Use sample standard deviation and a t distribution."], [["Mean weight", "Test whether average weight equals a label."], ["Exam mean", "Test a class mean against a target."], ["Battery life", "Test mean life with sample standard deviation."]], "A one-sample t-test uses sample standard what?", "deviation"),
  545: item(545, "Two-Sample t-Test", "two-sample-t-test", "Inferential Statistics", "procedure", "A two-sample t-test compares two population means using two independent samples.", "State hypotheses, compare sample means, compute a t statistic, and read the p-value.", "The method measures whether the observed mean difference is large relative to sampling variation.", "distribution_plot", ["MATCHED_DATA", "Using a two-sample t-test for matched before-and-after data.", "Use a paired t-test for matched pairs."], [["Two classes", "Compare average marks."], ["Two machines", "Compare mean output."], ["Two medicines", "Compare mean response in independent groups."]], "Two-sample t-tests need independent samples or paired samples?", "independent"),
  546: item(546, "Paired t-Test", "paired-t-test", "Inferential Statistics", "procedure", "A paired t-test tests the mean of differences from matched pairs.", "Subtract within each pair, then run a one-sample t-test on the differences.", "Pairing removes person-to-person or item-to-item variation before testing.", "distribution_plot", ["TEST_TWO_COLUMNS_DIRECTLY", "Testing two paired columns as if they are independent.", "First compute the within-pair differences."], [["Before and after", "Each person's change is one difference."], ["Left and right", "Matched body measurements form pairs."], ["Twin study", "Each twin pair gives a difference."]], "A paired t-test first computes within-pair what?", "differences"),
  547: item(547, "One-Proportion Test", "one-proportion-test", "Inferential Statistics", "procedure", "A one-proportion test checks a claim about one population proportion.", "State the null proportion, compute p-hat, standardise with the null value, and find the p-value.", "It tests whether the observed success rate is unusual if the claim is true.", "distribution_plot", ["USE_PHAT_SE", "Using p-hat instead of the null proportion in the test standard error.", "For the test statistic, use the null proportion in the standard error."], [["Coin fairness", "Test whether heads probability is 0.5."], ["Defect rate", "Test whether defects exceed a target."], ["Survey support", "Test whether support differs from 60 percent."]], "A one-proportion test checks one population what?", "proportion"),
  548: item(548, "Two-Proportion Test", "two-proportion-test", "Inferential Statistics", "procedure", "A two-proportion test checks whether two population proportions differ.", "Compute two sample proportions, pool under the null when testing equality, then find the z statistic.", "Pooling represents the common proportion assumed by the null hypothesis.", "distribution_plot", ["NO_POOL_TEST", "Not pooling proportions for an equality test.", "Use pooled proportion for the standard error when the null says proportions are equal."], [["Two ads", "Compare click proportions."], ["Two factories", "Compare defect rates."], ["Two groups", "Compare support percentages."]], "For an equality test, two-proportion z-tests use a pooled what?", "proportion"),
  549: item(549, "Chi-Square Goodness-of-Fit", "chi-square-goodness-of-fit", "Inferential Statistics", "procedure", "A chi-square goodness-of-fit test checks whether observed category counts match expected counts.", "Compute expected counts, sum squared differences divided by expected counts, and read the chi-square p-value.", "Large differences between observed and expected counts make the statistic large.", "distribution_plot", ["USE_PERCENT_ONLY", "Using percentages without expected counts.", "The test is based on observed and expected counts."], [["Die fairness", "Check whether six faces occur equally often."], ["Genetics", "Compare observed ratios with expected ratios."], ["Customer choices", "Test whether choices follow a claimed distribution."]], "Goodness-of-fit compares observed and expected what?", "counts"),
  550: item(550, "Chi-Square Independence", "chi-square-independence", "Inferential Statistics", "procedure", "A chi-square independence test checks whether two categorical variables are associated.", "Use a two-way table, compute expected counts from margins, then compare observed and expected counts.", "If variables are independent, observed counts should be close to expected counts from row and column totals.", "table", ["CAUSE_FROM_ASSOCIATION", "Treating association as proof of cause.", "A chi-square test can show association, not prove cause by itself."], [["Sport and grade", "Check whether sport choice is associated with grade."], ["Device and preference", "Test categorical association."], ["Treatment and outcome", "Check relationship in count data."]], "Chi-square independence uses a two-way what?", "table"),
  551: item(551, "Variance Tests", "variance-tests", "Inferential Statistics", "procedure", "Variance tests check claims about population variance or compare variances between groups.", "Choose the correct chi-square or F test, check assumptions, compute the statistic, and read the p-value.", "Squared deviations make variance tests sensitive to spread and outliers.", "distribution_plot", ["IGNORE_NORMALITY", "Using variance tests without checking strong assumptions.", "Classical variance tests often need normality and are sensitive to outliers."], [["Machine consistency", "Test whether variation changed."], ["Two suppliers", "Compare variability."], ["Lab precision", "Check if measurement variance meets a standard."]], "Variance tests are sensitive to spread and what?", "outliers"),
  552: item(552, "ANOVA", "anova", "Inferential Statistics", "procedure", "ANOVA tests whether several population means are equal by comparing between-group and within-group variation.", "State group mean hypotheses, compute an F statistic, and use the F distribution for the p-value.", "If group means differ more than expected from within-group variation, the F statistic becomes large.", "distribution_plot", ["PAIRWISE_ONLY", "Doing many pairwise tests instead of one overall ANOVA first.", "Use ANOVA for an overall comparison of several means."], [["Three teaching methods", "Compare mean scores across groups."], ["Fertiliser types", "Compare average plant growth."], ["Machine settings", "Compare mean output across settings."]], "ANOVA compares several population what?", "means"),
};

export function distributionInferenceSeed(id: number) {
  return data[id];
}

export type DistributionInferenceSeed = Seed;

export function distributionInferenceLesson(seed: Seed): StrengthenedLesson {
  const code = seed.misconception[0];
  return {
    id: seed.id,
    title: seed.title,
    route: `/lessons/data-and-probability/${seed.id}-${seed.slug}`,
    category: "Data and Probability",
    topic: seed.topic,
    lessonType: seed.lessonType,
    learningObjectives: [`Define ${seed.title} accurately.`, seed.action, `Avoid this mistake: ${seed.misconception[1]}`],
    prerequisites: ["Probability from 0 to 1", "Mean and standard deviation", "Reading distribution graphs"],
    keyVocabulary: [{ term: seed.title, meaning: seed.definition }, { term: seed.topic.includes("Inference") ? "p-value" : "parameter", meaning: seed.topic.includes("Inference") ? "The probability of results at least this unusual if the null hypothesis is true." : "A number that sets the shape or location of a distribution." }],
    introduction: `${seed.title} helps us describe chance or make decisions from sample data. It matters because real data has uncertainty. We use it in science, surveys, quality checks, health, and planning.`,
    basicIdea: `${seed.definition} The basic idea is to match the model or test to its assumptions before using it. ${seed.reason} A common mistake is ${seed.misconception[1]}`,
    howItWorks: `${seed.action} Then check assumptions, units, and whether the answer is a probability, estimate, statistic, or decision.`,
    whyItWorks: seed.topic.includes("Inference") ? "Inferential statistics uses sampling variation to judge whether data are typical or unusual under a stated claim." : "Probability distributions work by assigning probability according to a rule that matches the random process.",
    definitions: [{ id: `${seed.slug}-definition`, statement: seed.definition }],
    facts: [{ id: `${seed.slug}-fact`, statement: seed.reason }],
    formulas: seed.formula ? [{ id: `${seed.slug}-formula`, ...seed.formula }] : [],
    conditionsAndRestrictions: ["Check independence or sampling assumptions.", "Use valid parameters for the chosen model.", "Do not confuse probability, statistic, and conclusion."],
    representations: [{ id: `${seed.slug}-representation`, type: seed.representation, learningPurpose: `Show the structure of ${seed.title}.` }],
    workedExamples: [{ id: `${seed.slug}-worked-1`, prompt: seed.challenge.prompt, steps: ["Identify the model or inference method.", seed.action, "Check the conclusion against the context."], answer: seed.challenge.expected }],
    realLifeExamples: seed.examples.map(([context, connection], index) => ({ id: `${seed.slug}-real-${index + 1}`, context, connection })),
    misconceptions: [{ code, mistake: seed.misconception[1], correction: seed.misconception[2] }],
    interaction: { id: `${seed.slug}-interaction`, learningPurpose: `Explore ${seed.title} with a distribution, simulation, interval, or hypothesis-test display.`, parameters: [{ id: "sampleSize", label: "Sample size", validRange: [10, 100] }], initialState: `Start with a small example for ${seed.title}.`, dynamicFeedback: "Changing parameters updates the probability display, simulated samples, confidence intervals, or test statistic.", successCriteria: ["Choose the correct model or test", "Read the linked output", "Explain the common mistake"], accessibilityAlternative: "Provide the distribution values, interval bounds, test statistic, and decision as text." },
    guidedExploration: [{ id: "predict", prompt: "Predict how the graph or decision changes when the sample size changes." }, { id: "test", prompt: "Change one parameter and read the new output." }, { id: "explain", prompt: "Explain the result using the lesson definition." }],
    practice: [practice(`${seed.slug}-recognition`, `What is ${seed.title}?`, seed.definition, code, "recognition"), practice(`${seed.slug}-direct`, seed.challenge.prompt, seed.challenge.expected, code, "direct"), practice(`${seed.slug}-multi`, `How do you use ${seed.title}?`, seed.action, code, "multi_step"), practice(`${seed.slug}-error`, `What is wrong with this mistake: ${seed.misconception[1]}`, seed.misconception[2], code, "error_diagnosis"), practice(`${seed.slug}-transfer`, `Give one daily use of ${seed.title}.`, seed.examples[0][0], code, "transfer")],
    challenge: { id: `${seed.slug}-challenge`, prompt: seed.challenge.prompt, successCriteria: ["Uses the correct model or test", "Checks assumptions", "Avoids the named mistake"], hints: [seed.challenge.hint, seed.misconception[2]] },
    exitCheck: [{ id: `${seed.slug}-exit`, prompt: `State one rule for ${seed.title}.`, answer: seed.misconception[2], criterion: "Answer names a valid condition or interpretation." }],
    accessibilityNotes: ["Announce probability, interval, and p-value text.", "Do not rely only on colour for reject or capture states."],
    expertReviewRequired: false,
  };
}

export function distributionInferenceChallenge(seed: Seed) {
  return seed.challenge;
}

function item(id: number, title: string, slug: string, topic: Seed["topic"], lessonType: Seed["lessonType"], definition: string, action: string, reason: string, representation: Seed["representation"], misconception: Seed["misconception"], examples: Seed["examples"], prompt: string, expected: string, formula?: FormulaSeed): Seed {
  return { id, title, slug, topic, lessonType, definition, action, reason, representation, misconception, examples, formula, challenge: { prompt, expected, hint: `Use the ${title} rule and check assumptions.`, kind: Number.isFinite(Number(expected)) ? "numeric" : "keywords", factoryId: `distributionInference.${slug}` } };
}

function practice(id: string, prompt: string, answer: string, misconceptionTag: string, difficulty: StrengthenedLesson["practice"][number]["difficulty"]): StrengthenedLesson["practice"][number] {
  return { id, prompt, answer, hints: ["Check the assumptions.", "Identify the parameter or statistic.", "Read the distribution or interval carefully."], workedSolution: ["Identify the model or test.", "Apply the correct rule.", "Interpret the result in context."], misconceptionTag, difficulty, parameterConstraints: ["Use valid samples, counts, probabilities, and distribution parameters."] };
}
