import { OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Camera, Check, CircleHelp, RotateCcw, Share2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { BoxGeometry, BufferGeometry, DoubleSide, Float32BufferAttribute } from "three";
import type { LessonAdapterProps } from "../../types";
import "./CoordinateSystemTargetLesson378.css";
import "./ImplicitSurfacesTargetLesson414.css";
import "./ImplicitSurfacesTargetLesson414.layout.css";

type Preset = "sphere" | "ellipsoid" | "hyperboloid" | "torus" | "gyroid";
type Axis = "xy" | "xz" | "yz";
type Bounds = { xMin: number; xMax: number; yMin: number; yMax: number; zMin: number; zMax: number };
type Point = { x: number; y: number; z: number };
const initialBounds: Bounds = { xMin: -5, xMax: 5, yMin: -5, yMax: 5, zMin: -5, zMax: 5 };
const presetLabels: Record<Preset, string> = { sphere: "Sphere", ellipsoid: "Ellipsoid", hyperboloid: "Hyperboloid 1 sheet", torus: "Torus", gyroid: "Gyroid" };

export default function ImplicitSurfacesTargetLesson414({ resetToken, onInteraction }: LessonAdapterProps) {
  const [preset, setPreset] = useState<Preset>("sphere");
  const [iso, setIso] = useState(9);
  const [resolution, setResolution] = useState(120);
  const [bounds, setBounds] = useState(initialBounds);
  const [planes, setPlanes] = useState<Record<Axis, { enabled: boolean; value: number }>>({ xy: { enabled: true, value: 0 }, xz: { enabled: true, value: 0 }, yz: { enabled: true, value: 0 } });
  const [clipping, setClipping] = useState(true);
  const [plot, setPlot] = useState(true);
  const [point, setPoint] = useState<Point>({ x: 1.5, y: 1.5, z: 2.45 });
  const [challenge, setChallenge] = useState(false);
  const [shared, setShared] = useState(false);
  const [actions, setActions] = useState(0);
  const [viewKey, setViewKey] = useState(0);
  const act = (fn: () => void) => { fn(); setActions((v) => v + 1); onInteraction(); };
  const reset = () => { setPreset("sphere"); setIso(9); setResolution(120); setBounds(initialBounds); setPlanes({ xy: { enabled: true, value: 0 }, xz: { enabled: true, value: 0 }, yz: { enabled: true, value: 0 } }); setClipping(true); setPlot(true); setPoint({ x: 1.5, y: 1.5, z: 2.45 }); setChallenge(false); setShared(false); setActions(0); setViewKey((value) => value + 1); };
  useEffect(reset, [resetToken]);
  const f = evaluate(preset, point), difference = f - iso, classification = Math.abs(difference) < 0.05 ? "surface" : difference < 0 ? "inside" : "outside";
  const equation = equationFor(preset);
  const choose = (next: Preset) => act(() => { setPreset(next); setIso(next === "torus" ? 1 : next === "gyroid" ? 0 : 9); setChallenge(next === "hyperboloid"); });
  const updatePlane = (axis: Axis, patch: Partial<{ enabled: boolean; value: number }>) => act(() => setPlanes((current) => ({ ...current, [axis]: { ...current[axis], ...patch } })));
  const updateBound = (key: keyof Bounds, value: number) => act(() => setBounds((current) => ({ ...current, [key]: value })));
  return <section className="cs378-page is414-page" data-testid="geometry3d-mockup-0599" data-lesson-title="Implicit Surfaces" data-object-model="threejs-dedicated-implicit-level-set-presets-iso-value-slice-planes-domain-point-classification-hyperboloid-challenge" data-direct-interaction="true" data-preset={preset} data-iso={iso} data-f-value={round(f)} data-difference={round(difference)} data-classification={classification} data-challenge={challenge} data-actions={actions}>
    <header className="is414-hero"><small>3D MATHEMATICS</small><small>3D FUNCTIONS AND SURFACES</small><h1>Implicit Surfaces</h1><p>Explore level sets F(x,y,z) = c. Points on the surface satisfy the equation.</p><div><span>Advanced</span><span>3D Analysis Lab</span><span>3D Graphing / CAS</span><span>6-10 min</span><select aria-label="Language"><option>English (English)</option></select><button onClick={reset}><RotateCcw/>Reset</button><button onClick={() => act(() => { setShared(true); void navigator.clipboard?.writeText(`${equation} = ${iso}`); })}><Share2/>{shared ? "Shared" : "Share"}</button></div></header>
    <nav className="is414-tabs">{["Level set", "Slice planes", "Cross-sections", "Domain", "Explain", "Examples", "Challenge", "Formulas", "Know more"].map((label, i) => <button key={label} className={i === 0 ? "active" : ""}>{label}</button>)}</nav>
    <section className="is414-main">
      <aside><h2>Define the implicit surface</h2><label>Equation F(x, y, z) = c<output>{equation} = c</output></label><h3>Presets</h3><div className="is414-presets">{(Object.keys(presetLabels) as Preset[]).map((item) => <button key={item} className={preset === item ? "active" : ""} onClick={() => choose(item)}><PresetIcon preset={item}/><span>{presetLabels[item]}</span></button>)}</div><Range label="Iso-value c" value={iso} min={-10} max={10} step={0.25} onChange={(v) => act(() => setIso(v))}/><p className="is414-example"><b>Example: {equation} = {fmt(iso)}</b><span>{describe(preset, iso)}</span><span>All points (x,y,z) satisfying F = c lie on this level set.</span></p><Range label="Resolution" value={resolution} min={20} max={250} step={1} onChange={(v) => act(() => setResolution(v))}/><Toggle label="Plot implicit surface" checked={plot} onChange={(v) => act(() => setPlot(v))}/><Toggle label="Clipping box" checked={clipping} onChange={(v) => act(() => setClipping(v))}/><h3>Domain bounds</h3><div className="is414-bounds">{(["xMin", "xMax", "yMin", "yMax", "zMin", "zMax"] as (keyof Bounds)[]).map((key) => <label key={key}>{key.replace("Min", " min").replace("Max", " max")}<input aria-label={key} type="number" value={bounds[key]} onChange={(e) => updateBound(key, Number(e.target.value))}/></label>)}</div><button className="is414-reset-bounds" onClick={() => act(() => setBounds(initialBounds))}><RotateCcw/>Reset bounds</button></aside>
      <article className="is414-view"><div className="is414-tools"><button aria-label="Select">↖</button><button aria-label="Orbit">⟳</button><button aria-label="Fullscreen">⛶</button><button aria-label="Snapshot"><Camera/></button><button aria-label="Settings">⚙</button><button aria-label="Help"><CircleHelp/></button></div><div className="is414-stage">{plot && <ImplicitCanvas key={viewKey} preset={preset} iso={iso} planes={planes} clipping={clipping} bounds={bounds} onPoint={(p) => { setPoint(p); onInteraction(); }}/>}<output className={`is414-point ${classification}`}><b>Point ({fmt(point.x)}, {fmt(point.y)}, {fmt(point.z)})</b><span>F(x,y,z) = {fmt(f)}</span><span>c = {fmt(iso)}</span><span>F - c = <strong>{difference > 0 ? "+" : ""}{fmt(difference)}</strong></span><em>{classification === "surface" ? "On surface" : classification === "inside" ? "Inside" : "Outside"}</em></output><div className="is414-legend"><span><i className="red"/>xy slice (z = {fmt(planes.xy.value)})</span><span><i className="green"/>xz slice (y = {fmt(planes.xz.value)})</span><span><i className="blue"/>yz slice (x = {fmt(planes.yz.value)})</span><span><i className="cyan"/>Surface F = c</span></div></div><small>Drag surface to rotate • Scroll to zoom • Right-click + drag to pan</small></article>
      <section className="is414-slices"><header><h2>Slice planes</h2><p>Planes cut the surface to show contour intersections.</p></header>{(["xy", "xz", "yz"] as Axis[]).map((axis) => <article key={axis}><Toggle label={`${axis.toUpperCase()} plane`} checked={planes[axis].enabled} onChange={(v) => updatePlane(axis, { enabled: v })}/><Range label={`k (${axis === "xy" ? "z" : axis === "xz" ? "y" : "x"})`} value={planes[axis].value} min={-5} max={5} step={0.1} onChange={(v) => updatePlane(axis, { value: v })}/><label>Contour <input aria-label={`${axis} contour color`} type="color" value={axis === "xy" ? "#ef4444" : axis === "xz" ? "#16a34a" : "#315bd8"} readOnly/></label></article>)}</section>
    </section>
    <section className="is414-bottom"><article><h2>Why level sets?</h2><p>Implicit surfaces generalize explicit graphs.</p><div className="is414-compare"><span><b>Explicit surface</b><i>z = f(x, y)</i><small>One output for each (x,y). May fail for vertical surfaces or closed shapes.</small></span><span><b>Implicit surface (level set)</b><i>F(x, y, z) = c</i><small>All points satisfying the equation. Handles closed surfaces, voids, and multiple sheets.</small></span></div><p>Points <b>on the surface</b> satisfy F(x,y,z) = c exactly.</p></article><article><h2>Inside / Outside</h2><p>The sign of F(x,y,z) - c tells on which side a point lies.</p><ul><li><i/>F - c &lt; 0 <b>Inside</b></li><li><i/>F - c &gt; 0 <b>Outside</b></li><li><i/>F - c = 0 <b>On surface</b></li></ul></article><article><h2>Challenge</h2><p>Turn the level set into two sheets.</p><b>Try: x² + y² - z² = c</b><p>Adjust c &gt; 0 to see a hyperboloid of two sheets.</p><button onClick={() => choose("hyperboloid")}>{challenge && <Check/>} Try it</button><small>or explore other presets like torus or gyroid.</small></article></section>
    <nav className="is414-adjacent"><button><small>PREVIOUS</small><b>← Surface z = f(x,y)</b></button><button><small>NEXT</small><b>Parametric Surfaces →</b></button></nav>
    <footer className="is414-footer"><b>Math Universe</b><p>Interactive math labs, visual proofs, NCERT explorations, graphing, CAS-style tools, and classroom-ready activities.</p><nav><button>Sitemap</button><button>Docs</button><button>About</button></nav><hr/><small>© 2026 INDIAN SERVERS PRIVATE LIMITED. NO RIGHT TO REPRODUCE IT.</small></footer>
  </section>;
}

function ImplicitCanvas({ preset, iso, planes, clipping, bounds, onPoint }: { preset: Preset; iso: number; planes: Record<Axis, { enabled: boolean; value: number }>; clipping: boolean; bounds: Bounds; onPoint: (p: Point) => void }) {
  const box = useMemo(() => new BoxGeometry(bounds.xMax - bounds.xMin, bounds.yMax - bounds.yMin, bounds.zMax - bounds.zMin), [bounds]);
  return <Canvas camera={{ position: [8.5, 7.2, 10], fov: 40 }}><color attach="background" args={["#ffffff"]}/><ambientLight intensity={1.6}/><directionalLight position={[5, 8, 6]} intensity={1.8}/><group onPointerDown={(e) => { e.stopPropagation(); onPoint({ x: e.point.x, y: e.point.y, z: e.point.z }); }}><PresetMesh preset={preset} iso={iso}/>{planes.xy.enabled && <mesh position={[0, 0, planes.xy.value]} rotation={[Math.PI / 2, 0, 0]}><planeGeometry args={[10,10]}/><meshBasicMaterial color="#ef4444" transparent opacity={0.12} depthWrite={false} side={DoubleSide}/></mesh>}{planes.xz.enabled && <mesh position={[0, planes.xz.value, 0]}><planeGeometry args={[10,10]}/><meshBasicMaterial color="#22a559" transparent opacity={0.12} depthWrite={false} side={DoubleSide}/></mesh>}{planes.yz.enabled && <mesh position={[planes.yz.value, 0, 0]} rotation={[0, Math.PI / 2, 0]}><planeGeometry args={[10,10]}/><meshBasicMaterial color="#315bd8" transparent opacity={0.12} depthWrite={false} side={DoubleSide}/></mesh>}</group><gridHelper args={[10,10,"#9fb1c4","#d9e2ec"]}/>{clipping && <lineSegments><edgesGeometry args={[box]}/><lineBasicMaterial color="#8795a6" transparent opacity={0.55}/></lineSegments>}<axesHelper args={[5.5]}/><OrbitControls onStart={() => onPoint({ x: 1.5, y: 1.5, z: 2.45 })}/></Canvas>;
}

function PresetMesh({ preset, iso }: { preset: Preset; iso: number }) {
  const r = Math.max(.45, Math.sqrt(Math.abs(iso)));
  const geometry = useMemo(() => preset === "gyroid" ? gyroidGeometry() : null, [preset]);
  const material = <meshStandardMaterial color="#1db6d3" transparent opacity={0.68} roughness={0.34} metalness={0.05} side={DoubleSide}/>;
  if (preset === "sphere") return <mesh scale={[r,r,r]}><sphereGeometry args={[1,48,32]}/>{material}</mesh>;
  if (preset === "ellipsoid") return <mesh scale={[r, r * .72, r * .5]}><sphereGeometry args={[1,48,32]}/>{material}</mesh>;
  if (preset === "torus") return <mesh rotation={[Math.PI / 2,0,0]}><torusGeometry args={[2.5, Math.max(.3, Math.sqrt(Math.abs(iso)) * .45), 28, 80]}/>{material}</mesh>;
  if (preset === "hyperboloid") return <mesh geometry={hyperboloidGeometry(iso)}>{material}</mesh>;
  return <mesh geometry={geometry!}>{material}</mesh>;
}

function hyperboloidGeometry(iso: number) { const pos:number[]=[]; const idx:number[]=[]; const n=38,m=28; const c=iso >= 0 ? 1 : -1; for(let j=0;j<=m;j++){const z=-3+6*j/m; const radius=Math.sqrt(Math.max(.12,Math.abs(c+z*z))); for(let i=0;i<=n;i++){const a=Math.PI*2*i/n; pos.push(radius*Math.cos(a),radius*Math.sin(a),z);}} for(let j=0;j<m;j++)for(let i=0;i<n;i++){const p=j*(n+1)+i;idx.push(p,p+1,p+n+1,p+1,p+n+2,p+n+1);} const g=new BufferGeometry();g.setAttribute("position",new Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g; }
function gyroidGeometry(){ const pos:number[]=[]; const idx:number[]=[]; const n=44; for(let j=0;j<=n;j++)for(let i=0;i<=n;i++){const x=-Math.PI+2*Math.PI*i/n,y=-Math.PI+2*Math.PI*j/n,z=Math.sin(x)*Math.cos(y)+Math.sin(y)*Math.cos(x);pos.push(x,y,z*1.2);}for(let j=0;j<n;j++)for(let i=0;i<n;i++){const p=j*(n+1)+i;idx.push(p,p+1,p+n+1,p+1,p+n+2,p+n+1);}const g=new BufferGeometry();g.setAttribute("position",new Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g;}
function Range({ label, value, min, max, step, onChange }: { label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void }) { return <label className="is414-range"><b>{label}</b><span><small>{min}</small><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={(e)=>onChange(Number(e.target.value))}/><small>{max}</small><input aria-label={`${label} value`} type="number" value={value} min={min} max={max} step={step} onChange={(e)=>onChange(Number(e.target.value))}/></span></label>; }
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="is414-toggle"><span><b>{label}</b>{label.includes("Plot") && <small>Render the 3D level set F(x,y,z) = c.</small>}{label === "Clipping box" && <small>Clip the plot to the domain box.</small>}</span><input aria-label={label} type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/></label>}
function PresetIcon({preset}:{preset:Preset}){return <svg viewBox="0 0 44 35"><ellipse cx="22" cy="18" rx={preset==="ellipsoid"?10:12} ry={preset==="torus"?5:12} fill="none" stroke="currentColor"/><path d={preset==="hyperboloid"?"M11 3Q22 15 33 3M11 32Q22 20 33 32":preset==="gyroid"?"M4 25C12 3 18 32 25 10S35 28 41 8":"M10 18h24M22 5v26"} fill="none" stroke="currentColor"/></svg>}
function equationFor(p:Preset){return p==="sphere"?"x² + y² + z²":p==="ellipsoid"?"x²/9 + y²/4 + z²":p==="hyperboloid"?"x² + y² - z²":p==="torus"?"(√(x²+y²)-3)² + z²":"sin x cos y + sin y cos z + sin z cos x"}
function evaluate(p:Preset,q:Point){if(p==="sphere")return q.x*q.x+q.y*q.y+q.z*q.z;if(p==="ellipsoid")return q.x*q.x/9+q.y*q.y/4+q.z*q.z;if(p==="hyperboloid")return q.x*q.x+q.y*q.y-q.z*q.z;if(p==="torus")return (Math.hypot(q.x,q.y)-3)**2+q.z*q.z;return Math.sin(q.x)*Math.cos(q.y)+Math.sin(q.y)*Math.cos(q.z)+Math.sin(q.z)*Math.cos(q.x)}
function describe(p:Preset,c:number){return p==="sphere"?`This is a sphere of radius ${fmt(Math.sqrt(Math.max(0,c)))}.`:p==="ellipsoid"?"This is a stretched ellipsoid.":p==="hyperboloid"?"The sign of c controls the sheets.":p==="torus"?"This level set forms a torus.":"This periodic level set forms a gyroid."}
function fmt(v:number){return Number.isInteger(v)?String(v):v.toFixed(2)} function round(v:number){return Number(v.toFixed(4))}
