import{ArrowLeft,Link,MoreVertical,RotateCcw,X}from"lucide-react";import{useState}from"react";import{useNavigate}from"react-router-dom";import"./slope-triangles-mobile.css";
export default function SlopeTrianglesMobileProof(){const nav=useNavigate(),[slope,setSlope]=useState(.5),[locked,setLocked]=useState(true),[menu,setMenu]=useState(false),ox=195,oy=270,unit=38;const Y=(x:number)=>oy-slope*(x-ox);
const reset=()=>{setSlope(.5);setLocked(true);setMenu(false)};const triangles=[{x:-3,run:2,c:"#0aa9c0"},{x:0,run:4,c:"#ef8500"},{x:3,run:locked?8:6,c:"#594acc"}];
return <main className="slope-mobile"><header><button onClick={()=>nav(-1)} aria-label="Back to visual proofs"><ArrowLeft/></button><div><h1>Slope Triangles</h1><p>28 / 69</p></div><button onClick={()=>setMenu(v=>!v)} aria-label="Lesson options"><MoreVertical/></button></header>
<section className="slope-stage"><svg viewBox="0 0 390 520" aria-label={`Line slope ${slope.toFixed(2)}; all rise over run ratios ${locked?"locked equal":"can differ"}`}>
{Array.from({length:11},(_,i)=>i-5).map(n=><g key={n}><line className="grid" x1={ox+n*unit} y1="25" x2={ox+n*unit} y2="490"/><line className="grid" x1="15" y1={oy-n*unit} x2="375" y2={oy-n*unit}/></g>)}<line className="axis" x1="15" y1={oy} x2="375" y2={oy}/><line className="axis" x1={ox} y1="490" x2={ox} y2="25"/><line className="main-line" x1="15" y1={Y(15)} x2="375" y2={Y(375)}/>
{triangles.map((t,i)=>{const x1=ox+t.x*unit,x2=x1+t.run*unit*.55,y1=Y(x1),y2=Y(x2);return <g key={i}><polygon points={`${x1},${y1} ${x2},${y1} ${x2},${y2}`} fill={t.c+"22"} stroke={t.c}/><circle cx={x1} cy={y1} r="7" fill={t.c}/><circle cx={x2} cy={y2} r="7" fill={t.c}/><text x={(x1+x2)/2} y={y1+20} fill={t.c}>run {t.run}</text><text x={x2+26} y={(y1+y2)/2} fill={t.c}>rise {(t.run*slope).toFixed(1)}</text></g>})}
<g className="formula" transform="translate(195 465)"><rect x="-160" y="-38" width="320" height="76" rx="13"/><text x="0" y="8">m = rise / run = {slope.toFixed(2)}</text></g>
</svg></section><section className="slope-cards">{[2,4,8].map((run,i)=><div key={run} style={{color:triangles[i].c}}><span>rise</span><b>{(run*slope).toFixed(1)}</b><hr/><span>run</span><b>{run}</b></div>)}<button className={locked?"active":""} onClick={()=>setLocked(v=>!v)} aria-label="Lock similar slope triangles" aria-pressed={locked}><Link/></button></section>
<nav className="slope-controls"><button onClick={reset} aria-label="Reset slope triangles"><RotateCcw/></button><label><span>slope {slope.toFixed(2)}</span><input aria-label="Line slope" type="range" min="-1" max="1.5" step=".05" value={slope} onChange={e=>setSlope(Number(e.target.value))}/></label></nav>
{menu?<aside role="dialog"><button onClick={()=>setMenu(false)} aria-label="Close lesson options"><X/></button><h2>Same line, same ratio</h2><p>Every right triangle drawn along one line is similar. Scaling rise and run together leaves rise/run unchanged, so the slope is constant.</p></aside>:null}</main>}
