import{ArrowLeft,ChevronLeft,ChevronRight,MousePointer2,MoreVertical,RotateCcw,X}from"lucide-react";import{useState}from"react";import{useNavigate}from"react-router-dom";import"./difference-squares-mobile.css";
const coral="#fb6551",cyan="#3db5c9",gold="#ffb331";
function Grid({n,mode,x,y,size=17}:{n:number;mode:"whole"|"border";x:number;y:number;size?:number}){return <g transform={`translate(${x} ${y})`}>{Array.from({length:n},(_,r)=>Array.from({length:n},(__,c)=>{const border=r===n-1||c===n-1;return <rect key={`${r}-${c}`} x={c*size} y={r*size} width={size-1} height={size-1} rx="1.5" fill={mode==="whole"?coral:border?gold:cyan}/> }))}</g>}
export default function DifferenceSquaresMobileProof(){const nav=useNavigate(),[n,setN]=useState(6),[spread,setSpread]=useState(true),[menu,setMenu]=useState(false),size=17,total=2*n-1,stripSize=Math.min(18,310/total);const reset=()=>{setN(6);setSpread(true);setMenu(false)};
return <main className="dcs"><header><button style={{marginLeft:"10px"}} onClick={()=>nav(-1)} aria-label="Back to visual proofs"><ArrowLeft/></button><div><h1 style={{fontSize:"16px"}}>Difference of Consecutive Squares</h1><p>33 / 69</p></div><button onClick={()=>setMenu(v=>!v)} aria-label="Lesson options"><MoreVertical/></button></header>
<section className="dcs-stage"><svg viewBox="0 0 390 690" role="img" aria-label={`${n} squared minus ${n-1} squared equals ${total}`}>
<text className="math" x="83" y="34">n²</text><Grid n={n} mode="whole" x={32} y={48} size={size}/><path className="dim" d={`M27 48h-7v${n*size}h7M20 48v${n*size}M32 ${55+n*size}v7h${n*size}v-7`}/><text className="math small" x="12" y={102}>n</text><text className="math small" x={83} y={176}>n</text>
<text className="math" x="285" y="34">(n−1)²</text><Grid n={n} mode="border" x={232} y={48} size={size}/><rect className="dash-box" x="225" y="41" width={n*size+14} height={n*size+14}/>
<path className="curve" d="M354 83c28 38 28 76 0 110"/><path className="arrow" d="m350 88 1-14 12 8"/>
<g className="tap" role="button" tabIndex={0} aria-label="Rearrange L border" aria-pressed={spread} onClick={()=>setSpread(v=>!v)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setSpread(v=>!v)}} transform="translate(318 151)"><rect x="-26" y="-22" width="55" height="55" rx="6"/><MousePointer2/></g>
<path className="down" d="m183 210 12 13 12-13"/>
<g className={spread?"dcs-demo spread":"dcs-demo"}><Grid n={n} mode="border" x={48} y={245} size={size}/><path className="curve" d="M200 308c50 2 71 32 82 69"/><path className="arrow" d="m275 369 9 11 3-14"/></g>
<path className="down" d="m183 414 12 13 12-13"/>
<g transform={`translate(${195-total*stripSize/2} 462)`}>{Array.from({length:total},(_,i)=><rect key={i} x={i*stripSize} width={stripSize-1} height={stripSize-1} rx="2" fill={i<n?gold:cyan}/>)}</g><path className="dim" d={`M${195-total*stripSize/2} 490v7h${total*stripSize}v-7`}/><text className="math" x="195" y="532">2n − 1</text>
<g className="formula" transform="translate(195 590)"><rect x="-166" y="-37" width="332" height="74" rx="12"/><text x="0" y="10"><tspan className="coral">n²</tspan><tspan> − </tspan><tspan className="cyan">(n − 1)²</tspan><tspan> = </tspan><tspan className="violet">2n − 1</tspan></text></g>
</svg></section><nav className="dcs-controls"><button onClick={()=>setN(v=>Math.max(2,v-1))} aria-label="Previous square size"><ChevronLeft/></button><strong>n = {n}</strong><button onClick={()=>setN(v=>Math.min(9,v+1))} aria-label="Next square size"><ChevronRight/></button><button onClick={reset} aria-label="Reset square difference"><RotateCcw/></button></nav>
{menu?<aside role="dialog"><button onClick={()=>setMenu(false)} aria-label="Close lesson options"><X/></button><h2>The odd border</h2><p>Removing the (n−1) by (n−1) square leaves one row of n tiles and one column of n−1 tiles: n+(n−1)=2n−1.</p></aside>:null}</main>}
