import{ArrowLeft,ChevronDown,ChevronUp,MoreVertical,RotateCcw,X}from"lucide-react";import{useState}from"react";import{useNavigate}from"react-router-dom";import"./odd-square-pattern-mobile.css";
const colors=["#303640","#ed6855","#f2a52e","#28b5bd","#465cbd","#7953c7"];
export default function OddSquarePatternMobileProof(){const nav=useNavigate(),[n,setN]=useState(5),[menu,setMenu]=useState(false),cell=45,origin=195,rowGap=Math.min(38,175/n);const reset=()=>{setN(5);setMenu(false)};
return <main className="osp"><header><button onClick={()=>nav(-1)} aria-label="Back to visual proofs"><ArrowLeft/></button><div><h1>Odd Numbers Build Squares</h1><p>31 / 69</p></div><button onClick={()=>setMenu(v=>!v)} aria-label="Lesson options"><MoreVertical/></button></header>
<section className="osp-stage"><svg viewBox="0 0 390 555" aria-label={`Nested odd layers through ${2*n-1} form ${n} squared`}>
<g transform={`translate(${origin-n*cell/2} 42)`}>{Array.from({length:n},(_,row)=>Array.from({length:n},(__,col)=>{const layer=Math.max(row,col),active=layer<n;return <rect key={`${row}-${col}`} x={col*cell} y={row*cell} width={cell-2} height={cell-2} rx="3" fill={active?colors[layer]:"#eee"}/> }))}</g>
{Array.from({length:n},(_,i)=><g key={i} transform={`translate(38 ${330+i*rowGap})`}><circle cx="0" r="12" fill={colors[i]}/><text x="32" y="6">{2*i+1}</text><text x="180" y="6">n = {i+1}</text><text x="275" y="6">{i+1}² = {(i+1)**2}</text></g>)}
<g className="formula" transform="translate(195 525)"><rect x="-170" y="-27" width="340" height="54" rx="12"/><text x="0" y="8">1 + 3 + ··· + (2n − 1) = n² = {n*n}</text></g>
</svg></section><nav className="osp-controls"><button onClick={()=>setN(v=>Math.min(6,v+1))} aria-label="Add next odd layer"><ChevronUp/></button><span>n = {n}<small>new border: {2*n-1} tiles</small></span><button onClick={()=>setN(v=>Math.max(1,v-1))} aria-label="Remove outer odd layer"><ChevronDown/></button><button onClick={reset} aria-label="Reset odd layer pattern"><RotateCcw/></button></nav>
{menu?<aside role="dialog"><button onClick={()=>setMenu(false)} aria-label="Close lesson options"><X/></button><h2>Why the next number is odd</h2><p>The new bottom row contributes n tiles and the new side contributes n−1 more. Together the border has 2n−1 tiles.</p></aside>:null}</main>}
