export type StudioLearningCopy = {
  observe: string;
  understand: string;
  why: string;
  try: string;
  challenge: string;
};

export type StudioMockupPage = {
  id: string;
  label: string;
  route: string;
  title: string;
  subtitle: string;
  description: string;
  modes: string[];
  challenge: { prompt: string; expected: number; hint: string };
  learning: StudioLearningCopy;
};

export type StudioMockupDefinition = {
  id: string;
  name: string;
  mark: string;
  homeTitle: string;
  homeSubtitle: string;
  searchPlaceholder: string;
  basePath: string;
  continueLabel: string;
  continueRoute: string;
  pages: StudioMockupPage[];
};

const loop = (observe: string, understand: string, why: string, tryText: string, challenge: string): StudioLearningCopy => ({
  observe, understand, why, try: tryText, challenge,
});

function page(
  id: string,
  label: string,
  base: string,
  title: string,
  subtitle: string,
  description: string,
  modes: string[],
  challenge: StudioMockupPage["challenge"],
  learning: StudioLearningCopy,
): StudioMockupPage {
  return { id, label, route: id === "home" ? base : `${base}/${id}`, title, subtitle, description, modes, challenge, learning };
}

export const studioMockups: Record<string, StudioMockupDefinition> = {
  geometry: {
    id: "geometry", name: "Geometry Studio", mark: "G", homeTitle: "Geometry Studio",
    homeSubtitle: "Construct, measure, transform, and prove with interactive figures.",
    searchPlaceholder: "Search constructions, theorems, or shapes...",
    basePath: "/geometry", continueLabel: "Triangles & Congruence", continueRoute: "/geometry/triangles",
    pages: [
      page("home", "Studio Home", "/geometry", "Geometry Studio", "Explore shape, measure, and proof.", "Launch a geometry lab.", [], { prompt: "0", expected: 0, hint: "" }, loop("Pick a lab and watch one figure respond when you drag a point.", "Read the live measures and name what stays constant.", "A construction, a measure, and a theorem are the same relationship.", "Start with Triangles Explorer, then open Circles.", "Prove one claim in Theorems & Proofs after you can measure it.")),
      page("construction", "Construction", "/geometry", "Construction Workspace", "Build figures with dependent objects.", "Point, line, circle, and polygon tools that stay linked as you drag.", ["Live Object Tree", "Measurements", "Dependencies", "Proof Explanation"], { prompt: "How many degrees in a straight angle?", expected: 180, hint: "A straight line is a half turn." }, loop("Watch objects appear.", "Read the object tree.", "Dependencies keep the figure consistent.", "Add a circle through two points.", "Reconstruct a perpendicular bisector.")),
      page("triangles", "Triangles", "/geometry", "Triangles Lab", "Explore triangle geometry through dynamic constructions, measurements and proofs.", "Drag vertices to classify triangles and test congruence, similarity, centers, and inequalities.", ["Triangle Explorer", "Congruence", "Similarity", "Centers", "Inequalities"], { prompt: "Angle sum of a triangle (degrees)?", expected: 180, hint: "Interior angles of a Euclidean triangle." }, loop("Drag vertices to explore how side lengths and angles change.", "Notice if parts remain constant under different movements.", "Why does SSS guarantee triangle congruence?", "Use transformations to move one triangle onto the other.", "Create two non-congruent triangles that look similar.")),
      page("circles", "Circles", "/geometry", "Circles Lab", "Explore circle geometry through constructions, measurements and dynamic relationships.", "Chord, tangent, and inscribed-angle theorems in motion.", ["Chords", "Tangents", "Angles", "Power of a Point", "Arcs & Sectors"], { prompt: "Angle in a semicircle (degrees)?", expected: 90, hint: "Thales' theorem." }, loop("Move the inscribed point.", "Read the intercepted arc.", "Inscribed angle is half the center.", "Drag a tangent.", "Find an angle from an arc.")),
      page("polygons", "Polygons", "/geometry", "Polygons Lab", "Explore polygon structure, angles, tessellations, area and diagonals through interactive constructions.", "Regular n-gons with interior sum, tessellation, area, and diagonals.", ["Regular Polygon", "Interior Angles", "Tessellation", "Area", "Diagonals"], { prompt: "Interior angle of a regular hexagon?", expected: 120, hint: "((n-2)×180)/n." }, loop("Change n and watch the regular n-gon rebuild.", "Interior sum is (n−2)×180°; exteriors always close 360°.", "Only triangles, squares, and hexagons tessellate regularly.", "Decompose area into triangles or use the shoelace formula.", "Count n(n−3)/2 diagonals of an octagon.")),
      page("transformations", "Transformations", "/geometry", "Transformations Lab", "Translate, rotate, reflect, dilate, and compose maps.", "See the image of a shape under each isometry and dilation.", ["Translate", "Rotate", "Reflect", "Dilate", "Compose"], { prompt: "Rotation of 180° around origin sends (1,0) to x=?", expected: -1, hint: "Halfway around the origin." }, loop("Move the pre-image.", "Read the image coordinates.", "Isometries preserve distance.", "Compose reflect then rotate.", "Map a triangle onto another.")),
      page("coordinate", "Coordinate Geometry", "/geometry", "Coordinate Geometry Lab", "Explore analytic geometry with points, lines, equations, or loci.", "Distance, midpoint, slope, and loci on a live coordinate plane.", ["Distance", "Midpoint", "Slope", "Section Formula", "Locus"], { prompt: "Distance from (0,0) to (3,4)?", expected: 5, hint: "3-4-5 triangle." }, loop("Drag points A, B & C or lines to see relationships update in real time.", "Explore slopes, equations, distances, and intersections.", "See how algebraic forms connect to geometric ideas.", "Create your own lines, loci, and solve challenges.", "Find the locus of points equidistant from A and B.")),
      page("measurement", "Measurement", "/geometry", "Measurement Lab", "Measure length, angle, area, perimeter, scale, and uncertainty.", "Live length, angle, area, and perimeter with units and scale.", ["Length", "Angle", "Area", "Perimeter", "Scale", "Error"], { prompt: "Area of a 6 by 4 rectangle?", expected: 24, hint: "length × width." }, loop("The shape is composite and can be decomposed into 4 rectangles for easy measurement.", "Area is the sum of parts. Perimeter is the total around the outer boundary.", "Decomposition simplifies complex shapes. Additive properties ensure accurate total measurements.", "Drag orange points to modify the shape. Switch to other modes to measure angles and more.", "Create a shape with the same area but different perimeter. Can you minimize the perimeter?")),
      page("proofs", "Theorems & Proofs", "/geometry", "Theorem & Visual Proof", "See why classic theorems hold.", "Visual proofs for Pythagoras, angle sum, circles, and similarity.", ["Pythagoras", "Angle Sum", "Circle Theorems", "Similarity", "Area Proofs"], { prompt: "In a 3-4-5 triangle, hypotenuse is?", expected: 5, hint: "3²+4²=c²." }, loop("Watch the rearrangement.", "Read each proof step.", "Area is conserved under dissection.", "Rearrange the squares.", "Write a two-column proof.")),
      { ...page("solids", "Shapes Explorer", "/geometry", "2D & 3D Shapes Explorer", "Measure 2D shapes and 3D solids with live formulas.", "Cylinders, cones, spheres, nets, and cross-sections in the Shapes Explorer.", ["Cylinders", "Cones", "Spheres", "Nets", "Cross-sections"], { prompt: "Volume of a cube of side 3?", expected: 27, hint: "s³." }, loop("Rotate the solid.", "Read surface area and volume.", "Nets fold without overlap.", "Unfold a cylinder.", "Sketch a cross-section.")), route: "/shapes" },
      page("ar", "Geometry AR", "/geometry", "Geometry AR Lab", "Overlay constructions on the camera plane.", "Camera overlay for points, lines, polygons, and 3D solids.", ["Select", "Point", "Line", "Circle", "Polygon", "3D Solid", "Plane", "Measure"], { prompt: "A full turn in degrees?", expected: 360, hint: "One complete rotation." }, loop("Place a point in AR.", "Measure a live length.", "Camera pose maps world to screen.", "Measure a room corner.", "Capture a triangle overlay.")),
    ],
  },
  trigonometry: {
    id: "trigonometry", name: "Trigonometry Studio", mark: "θ", homeTitle: "Trigonometry Studio",
    homeSubtitle: "Explore angles, triangles, circles and waves.",
    searchPlaceholder: "Search angles, identities, or waves...",
    basePath: "/trigonometry", continueLabel: "Unit Circle", continueRoute: "/trigonometry/unit-circle",
    pages: [
      page("home", "Studio Home", "/trigonometry", "Trigonometry Studio", "Explore angles, triangles, circles and waves.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("Watch the circle.", "Read sine and cosine.", "Projection explains the graphs.", "Change the angle.", "Solve a triangle.")),
      page("unit-circle", "Unit Circle", "/trigonometry", "Unit Circle & Angle Studio", "Explore angles, unit circle relationships, and exact trig values.", "Drag the terminal ray.", ["Angles", "Unit Circle", "Quadrants", "Exact Values", "Reference Angles"], { prompt: "sin(90°) = ?", expected: 1, hint: "The point is (0,1)." }, loop("See how the point moves on the unit circle as θ changes.", "Understand projections, signs, and exact values.", "Discover the meaning behind the relationships.", "Practice with angles and check your understanding.", "Solve problems and apply trig concepts.")),
      page("right-triangle", "Right Triangle", "/trigonometry", "Right Triangle Studio", "Solve, explore, and master right triangles.", "SOH-CAH-TOA in motion.", ["Solve Triangle", "Ratios", "Pythagoras", "Similarity", "Special Triangles"], { prompt: "In a 30-60-90 triangle, short leg if hypotenuse is 2?", expected: 1, hint: "Short leg is half the hypotenuse." }, loop("Move points and see how sides and angles change in real time.", "Explore ratios, the Pythagorean theorem, and right triangle facts.", "Discover the relationships behind the calculations.", "Change inputs or drag vertices to create your own problems.", "Solve triangle puzzles and beat your best time.")),
      page("graphs", "Functions & Graphs", "/trigonometry", "Trigonometric Functions & Graphs Studio", "Explore how transformations shape sine, cosine, and tangent graphs.", "Amplitude, period, phase.", ["Sine", "Cosine", "Tangent", "Transformations", "Comparison"], { prompt: "Period of sin(2x) in π units? Enter 1 for π.", expected: 1, hint: "Period is 2π/|b|." }, loop("Drag a point on the unit circle or the graph to see them synchronize.", "Amplitude controls height. B controls period. C shifts left/right. D moves up/down.", "Transformations come from stretching and shifting the parent function.", "Change B to 2 and C to −π/2. What happens to the graph?", "Can you make the graph pass through (0, 1.5) with a period of π?")),
      page("identities", "Identities", "/trigonometry", "Identities & Visual Proofs Studio", "Explore and prove trigonometric identities with interactive visuals.", "Prove with the circle.", ["Pythagorean", "Angle Sum", "Double Angle", "Half Angle", "Product-Sum"], { prompt: "sin²θ + cos²θ = ?", expected: 1, hint: "Unit circle radius." }, loop("Move θ.", "See the identity hold.", "The radius is identically 1.", "Expand sin(2θ).", "Verify a double-angle value.")),
      page("inverse", "Inverse Trig", "/trigonometry", "Inverse Trigonometry Studio", "Explore inverse trig functions, their restrictions, and geometric interpretations.", "Arcsin, arccos, arctan.", ["Arcsin", "Arccos", "Arctan", "Principal Values", "Compositions"], { prompt: "arcsin(1) in degrees?", expected: 90, hint: "Sine of 90° is 1." }, loop("Restrict the range.", "Read the principal value.", "Inverse undoes on the principal branch.", "Compose sin(arcsin x).", "Find arctan(1).")),
      page("oblique", "Sine & Cosine Laws", "/trigonometry", "Oblique Triangle Studio", "Explore and solve non-right triangles using the Sine Law and Cosine Law.", "Sine and cosine laws.", ["Sine Law", "Cosine Law", "Area", "SSA Ambiguous Case", "Solve Triangle"], { prompt: "Area of SAS triangle a=2, b=2, included 90°?", expected: 2, hint: "(1/2)ab sin C." }, loop("Manipulate the triangle and watch how sides and angles respond together.", "See how the Sine Law and Cosine Law connect sides and angles.", "Explore why the laws hold true for any triangle.", "Change the known values and solve new triangles.", "Test yourself with real-world problems and puzzles.")),
      page("waves", "Waves & Harmonics", "/trigonometry", "Waves & Harmonics Studio", "Explore, combine, and analyze periodic motion and harmonic phenomena.", "Build a wave.", ["Simple Wave", "Superposition", "Harmonics", "Beats", "Phase"], { prompt: "Beat frequency for 10 Hz and 12 Hz?", expected: 2, hint: "|f1 − f2|." }, loop("Watch how changing frequency or phase alters the pattern.", "Learn how superposition creates interference and beats.", "Explore the connection between waves and circular motion.", "Adjust parameters to matching a target waveform.", "Build a waveform using specific harmonic coefficients.")),
      page("applications", "Applications", "/trigonometry", "Trigonometry Applications Studio", "Solve real-world measurement problems using right triangles and trigonometric relationships.", "Real-world triangles.", ["Heights & Distances", "Bearings", "Navigation", "Surveying", "Periodic Models"], { prompt: "Height if tan(45°)=h/10 with adjacent 10?", expected: 10, hint: "tan 45° = 1." }, loop("Change the angle of elevation.", "Read the height.", "Tangent is opposite over adjacent.", "Work a bearing problem.", "Model a tide.")),
      page("ar", "AR Lab", "/trigonometry", "Trigonometry AR Lab", "Measure height and project waves in AR.", "Camera overlays.", ["Height Measurement", "Distance", "Angle", "Triangle Overlay", "Unit Circle", "Wave Projection"], { prompt: "If angle of elevation is 45° and distance is 8, height is?", expected: 8, hint: "tan 45° = 1." }, loop("Point the camera.", "Read live angle.", "The overlay is a similar triangle.", "Measure a building.", "Project a unit circle.")),
    ],
  },
  "linear-algebra": {
    id: "linear-algebra", name: "Linear Algebra Studio", mark: "A", homeTitle: "Linear Algebra Studio",
    homeSubtitle: "Explore vectors, matrices, transformations, and the geometry of linear systems.",
    searchPlaceholder: "Search topics, tools, or examples...",
    basePath: "/linear-algebra", continueLabel: "Eigenvectors", continueRoute: "/linear-algebra/eigenvectors",
    pages: [
      page("home", "Studio Home", "/linear-algebra", "Linear Algebra Studio", "See linear maps in 2D and 3D.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("See patterns and visual structures.", "Connect ideas with concepts.", "Uncover the reasoning behind the math.", "Experiment and test your understanding.", "Push your skills and solve advanced problems.")),
      page("vectors", "Vectors", "/linear-algebra", "Vectors Lab", "Explore vectors in 3D: components, operations, dot & cross products, projections.", "2D and 3D vector ops.", ["Dot", "Cross", "Projections", "Add", "Subtract", "Scale"], { prompt: "Dot product of (1,0) and (0,1)?", expected: 0, hint: "Orthogonal vectors." }, loop("Drag vector endpoints to explore operations and see values update in real time.", "Study relationships between vectors, angles, and how projections work geometrically.", "Dot product measures alignment. Cross product gives a perpendicular vector and area.", "Change vectors, compute projections, or test a × (b + c) = a × b + a × c.", "Can you make a · b = 0? What maximizes |a × b|?")),
      page("matrices", "Matrices", "/linear-algebra", "Matrices & Operations Lab", "Explore matrix arithmetic, properties, and geometric transformations.", "Live matrix algebra.", ["Multiply", "Add", "Inverse", "Transpose", "Block"], { prompt: "det([[1,0],[0,1]])?", expected: 1, hint: "Identity." }, loop("See how A transforms the unit square, then B applies another transformation.", "Track how rows of A combine with columns of B to form the result.", "Determinants multiply: det(A × B) = det(A) · det(B).", "Edit entries, switch operations, or try non-square matrices.", "Find matrices A, B where A × B = I (but A and B are not square).")),
      page("row-reduction", "Row Reduction", "/linear-algebra", "Systems & Row Reduction Lab", "Solve Ax = b by row reducing the augmented matrix and visualize the solution set.", "3D / 2D / pivot map.", ["3D View", "2D View", "Pivot Map"], { prompt: "Rank of identity 2×2?", expected: 2, hint: "Two pivots." }, loop("Watch how row operations preserve the solution set.", "See pivots form a staircase and free variables emerge.", "Row operations are elementary matrices — they don't change Ax = b.", "Modify the matrix or add a free variable. What happens?", "Create a system with infinitely many solutions.")),
      page("linear-transforms", "Linear Transforms", "/linear-algebra", "Linear Transformations Lab", "Explore how linear transformations map vectors, shapes, and bases.", "Presets and 2D/3D.", ["Identity", "R90", "Scale X", "Shear", "2D", "3D"], { prompt: "Rotation by 90° sends (1,0) to y=?", expected: 1, hint: "(0,1)." }, loop("Adjust A, the basis, or move the interpolation slider to see the transformation in action.", "Linear transformations preserve lines and the origin, but change lengths, angles, and areas.", "Matrix multiplication encodes how basis vectors move—everything else follows.", "Create your own matrix, compose transforms, and predict the result before seeing it.", "Find a matrix that reflects across the line y = x and then stretches by 2 in the y-direction.")),
      page("determinants", "Determinants", "/linear-algebra", "Determinants Lab", "Explore area, volume, orientation, and singularity through determinants.", "Signed scale of maps.", ["2D Area", "3D Volume", "Cofactor", "Orientation", "Singularity"], { prompt: "det of a 90° rotation?", expected: 1, hint: "Rotation preserves area and orientation." }, loop("Drag v1 and v2 to create different parallelograms. Watch the area change.", "The determinant tells how A scales area and whether it flips orientation.", "det(A) is the signed area factor: det(AB) = det(A) det(B).", "Create a matrix with det(A) = −2. What happens to area & orientation?", "Find a matrix with det(A) = −1 that swaps the axes.")),
      page("vector-spaces", "Vector Spaces", "/linear-algebra", "Vector Spaces & Basis Lab", "Explore spans, independence, bases, subspaces, and coordinates in R³.", "Live spanning set.", ["Span", "Independence", "Basis", "Subspaces", "Coordinates"], { prompt: "Dimension of R²?", expected: 2, hint: "Two independent directions." }, loop("Toggle vectors and see how the span changes. Notice the plane they form.", "Rank tells you the dimension of the span. A basis is a minimal independent set.", "Dependence means one vector is a combination of others.", "Add or remove vectors to find a basis for the plane or for all of R³.", "Can you find a basis that includes v3 instead of v1 or v2?")),
      page("eigenvectors", "Eigenvectors", "/linear-algebra", "Eigenvalues & Eigenvectors Lab", "Transform a field of arrows and unit circle/ellipse; eigenvectors remain on invariant directions.", "2D, 3D, phase portrait.", ["2D View", "3D View", "Phase Portrait"], { prompt: "Eigenvalue of I₂ (either)?", expected: 1, hint: "Identity scales by 1." }, loop("Watch how the circle transforms and eigenvectors remain fixed.", "See how eigenvalues scale along eigen directions.", "Learn why eigenvectors don't change direction under A.", "Adjust the matrix and explore different behaviors.", "Find a matrix with complex eigenvalues.")),
      page("orthogonality", "Orthogonality", "/linear-algebra", "Orthogonality & Projections Lab", "Project vectors onto lines and planes, build orthonormal bases with Gram-Schmidt.", "3D and 2D views.", ["3D View", "Vector Decomp", "2D Projections"], { prompt: "Length of a unit vector?", expected: 1, hint: "Normalized." }, loop("v projects onto line span(u) at a right angle. The residual is orthogonal to u.", "Orthogonal projections minimize distance. They decompose v into independent parts.", "Orthogonality simplifies computations: dot products decouple components.", "Change vectors, switch steps, or try random examples.", "Can you build an ON basis from these vectors in a different order?")),
      page("least-squares", "Least Squares", "/linear-algebra", "Least Squares Lab", "Fit a line to data using least squares. Minimize the sum of squared residuals.", "Fit a line to data.", ["Fit", "Residuals", "Column Space"], { prompt: "Slope of least squares for points (0,0) and (1,2)?", expected: 2, hint: "The line through the origin and (1,2)." }, loop("Drag points to see how the best-fit line and residuals update.", "See how projections onto the column space minimize error.", "Least squares solves min_x ||Ax − b||². Normal equations give x = (AᵀA)⁻¹ Aᵀb.", "Change the data or add noise to test the robustness.", "Add outliers or try a quadratic model. Can you do better?")),
      page("playground", "Transform Playground", "/linear-algebra", "2D & 3D Transformation Playground", "Explore linear transformations. Edit the matrix, drag the object, and see geometry come alive.", "Presets and a stack.", ["2D Canvas", "3D Canvas", "Compose"], { prompt: "Identity composed n times still has det?", expected: 1, hint: "det I = 1." }, loop("What happens to lengths, angles, areas, and volumes?", "How does the matrix create this transformation?", "Why does det(A) control area/volume scale?", "Experiment with different matrices and objects.", "Can you build a transformation with a specific effect?")),
    ],
  },
  "complex-numbers": {
    id: "complex-numbers", name: "Complex Numbers Studio", mark: "i", homeTitle: "Welcome to Complex Numbers Studio",
    homeSubtitle: "Explore, visualize, and master complex numbers through interactive experiments.",
    searchPlaceholder: "Search topics, e.g. z = a + bi, roots, Euler formula...",
    basePath: "/complex-numbers", continueLabel: "Argand Plane", continueRoute: "/complex-numbers/argand-plane",
    pages: [
      page("home", "Studio Home", "/complex-numbers", "Complex Numbers Studio", "Plot, rotate, and transform z.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("Watch z move.", "Read modulus and argument.", "Geometry is algebra.", "Rotate by i.", "Find cube roots of −1.")),
      page("argand-plane", "Argand Plane", "/complex-numbers", "Argand Plane Lab", "Plot z, conjugate, modulus, argument, locus.", "Drag the blue point.", ["Plot", "Modulus", "Argument", "Conjugate", "Distance", "Locus"], { prompt: "|3+4i| = ?", expected: 5, hint: "3-4-5." }, loop("Drag z.", "Read r and θ.", "Modulus is distance from origin.", "Show the conjugate.", "Open locus |z|=2.")),
      page("arithmetic", "Arithmetic", "/complex-numbers", "Complex Arithmetic & Geometry Lab", "Operate on complex numbers as vectors in the Argand plane.", "Parallelogram addition.", ["Add", "Subtract", "Multiply", "Divide", "Conjugate"], { prompt: "Re((2+i)+(1+2i))?", expected: 3, hint: "Add real parts." }, loop("Drag points P and Q. Watch the sum update in real time.", "Vector addition uses the parallelogram rule in ℂ.", "Complex arithmetic — geometry in the Argand plane.", "Switch operations and explore products, quotients, and more.", "Can you make z₁ × z₂ purely imaginary?")),
      page("polar-forms", "Polar Forms", "/complex-numbers", "Polar & Exponential Forms Lab", "Convert between rectangular, polar, and exponential forms on the Argand plane.", "Linked sliders.", ["Rectangular", "Polar", "Exponential"], { prompt: "Argument of i in degrees?", expected: 90, hint: "Positive imaginary axis." }, loop("Watch how forms stay in sync as you move sliders.", "See the geometry of modulus and argument clearly.", "Euler connects rotation on the unit circle to exponentials.", "Pick a point, change branch, see what happens.", "Convert tricky numbers and explore multiple branches.")),
      page("rotation", "Rotation", "/complex-numbers", "Multiplication as Rotation Lab", "Visualize z × w as a rotation and scaling in the complex plane.", "Spiral of powers.", ["Rotate", "Scale", "Sequence"], { prompt: "arg(i) in degrees?", expected: 90, hint: "Multiplying by i is +90°." }, loop("Multiplication rotates by arg(w) and scales by |w|.", "Complex multiplication is similarity transform in the plane.", "Because r e^{iθ} = r (cos θ + i sin θ) represents rotation and scaling.", "Change θ to −60° and see rotation in the opposite direction.", "Find w such that wz = −z for any nonzero z.")),
      page("roots", "Roots", "/complex-numbers", "Roots of Complex Numbers Lab", "Explore nth roots, roots of unity, and polynomial roots on the Argand plane.", "De Moivre in action.", ["Square Roots", "nth Roots", "Roots of Unity", "Polynomial Roots"], { prompt: "How many 6th roots does a nonzero z have?", expected: 6, hint: "n distinct nth roots." }, loop("The n roots lie on a circle of radius r^{1/n}, equally spaced by 360°/n.", "Roots are symmetric: angles differ by 360°/n. The polygon connects roots in order of increasing k.", "De Moivre's theorem links powers and roots via polar form, turning multiplication into angle addition.", "Change n, drag the angle θ, or try random z. Explore patterns and special cases.", "Find z such that one of its cube roots is purely imaginary. What about fourth roots?")),
      page("euler", "Euler Formula", "/complex-numbers", "Euler's Formula Lab", "Explore e^{iθ} = cos θ + i sin θ, its series, and the beautiful identity e^{iπ} + 1 = 0.", "Four linked views.", ["Unit Circle", "Helix", "Projections", "Taylor"], { prompt: "e^{iπ} + 1 = ?", expected: 0, hint: "Euler's identity." }, loop("Watch e^{iθ} move on the unit circle and trace the helix in 3D.", "e^{iθ} has constant magnitude 1 and encodes pure rotation by θ.", "Taylor series of e^x extends to x=iθ, linking exponentials and trig.", "Change θ, terms, and trace length. Predict where e^{iθ} goes next.", "Prove e^{iπ} + 1 = 0 and explore e^{i2π} = 1. Can you generalize?")),
      page("loci", "Loci & Transforms", "/complex-numbers", "Loci & Transformations Lab", "Explore loci and how transformations reshape the complex plane.", "Before and after planes.", ["Circle Loci", "Line Loci", "Möbius", "Inversion", "Affine Map"], { prompt: "Möbius maps send generalized circles to circles. How many fixed points can a non-identity Möbius have at most?", expected: 2, hint: "Quadratic equation." }, loop("See how the locus and grid transform in real time.", "Explore invariants, fixed points, and domain behavior.", "Möbius maps preserve cross-ratios and map generalized circles.", "Change the transformation, drag points, and experiment.", "Can you map this circle to a line? Find parameters to try.")),
      page("fractals", "Fractals", "/complex-numbers", "Mandelbrot & Julia Sets Lab", "Explore complex dynamics and fractal beauty.", "Linked Mandelbrot and Julia.", ["Mandelbrot Set", "Julia Set"], { prompt: "For c=0, is 0 in the Mandelbrot set? Enter 1 for yes.", expected: 1, hint: "Orbit stays at 0." }, loop("See how varying c changes the Julia set.", "Points inside the set stay bounded; outside escape.", "Iterating z² + c reveals deep structure and chaos.", "Drag c, change iterations and palette.", "Find a c where the Julia set is disconnected.")),
      page("waves-circuits", "Waves & Circuits", "/complex-numbers", "Applications to Waves & Circuits Lab", "Unify phasors, AC circuits, and complex numbers. Visualize steady-state behavior.", "RLC in the complex plane.", ["Phasors", "AC Circuits", "Signal Rotation", "Impedance"], { prompt: "Power factor if φ=0°?", expected: 1, hint: "cos 0° = 1." }, loop("Explore phasors, waves, and circuit response in real time.", "See how complex impedance controls magnitude and phase.", "Impedance encodes opposition and phase shift in AC circuits.", "Adjust components, frequency, and observe the effects.", "Match a target power factor and minimize current.")),
    ],
  },
  modelling: {
    id: "modelling", name: "Modelling Studio", mark: "M", homeTitle: "Mathematical Modelling Studio",
    homeSubtitle: "Explore • Simulate • Compare • Understand",
    searchPlaceholder: "Search datasets, scenarios or models...",
    basePath: "/mathematical-modelling", continueLabel: "Epidemic Spread", continueRoute: "/mathematical-modelling/epidemics",
    pages: [
      page("home", "Studio Home", "/mathematical-modelling", "Mathematical Modelling Studio", "Build, fit, and compare models.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("Explore real-world patterns and data.", "Build models that explain what's happening.", "Interpret results and uncover the reasoning.", "Experiment with assumptions and parameters.", "Test your thinking with real modelling tasks.")),
      page("motion", "Motion", "/mathematical-modelling", "Motion Modelling Lab", "Simulate motion, compare models, and assess prediction error.", "Compare models to data.", ["Projectile", "Vehicle", "Pursuit", "Drag"], { prompt: "Time of flight scale: if g doubles, hang time of a vertical toss falls by about what factor? Enter 0.71 for 1/√2.", expected: 0.71, hint: "t ~ 1/√g." }, loop("Explore the motion and compare models to data.", "See how parameters and forces affect the motion.", "Learn the physics behind projectile motion.", "Adjust parameters and test your own scenarios.", "Can you minimize the error with the best model?")),
      page("population", "Population", "/mathematical-modelling", "Population Growth Lab", "Explore, compare, and simulate population models under different scenarios.", "Carrying capacity in view.", ["Exponential", "Logistic", "Harvesting", "Age Structured"], { prompt: "Logistic equilibrium is at K. If K=5000, equilibrium P=?", expected: 5000, hint: "dP/dt=0 at K." }, loop("What patterns do you see in the data and model curves?", "How do r and K affect long-term population size?", "Why does the logistic model level off while exponential does not?", "Test different scenarios and see how sensitive the outcomes are.", "Can you keep the population near K using harvesting?")),
      page("epidemics", "Epidemics", "/mathematical-modelling", "Epidemic Modelling Lab", "Explore, simulate, and compare epidemic models.", "Compartment flow.", ["SIR", "SEIR", "Vaccination", "Interventions"], { prompt: "If R0 < 1, outbreak dies out. Enter 1 if that statement is true.", expected: 1, hint: "Each case produces fewer than one new case." }, loop("Explore the live dynamics and compare scenarios.", "Learn how parameters and interventions shape outcomes.", "Discover the mechanisms behind epidemic behavior.", "Test your own scenarios and see the impact.", "Can you keep Rₑ < 1 and stay within hospital capacity?")),
      page("finance", "Finance", "/mathematical-modelling", "Finance & Compound Interest Lab", "Model savings, loans, investments, inflation, and annuities.", "Nominal vs real value.", ["Savings", "Loans", "Investments", "Inflation", "Annuities"], { prompt: "If interest is 0%, $100 after 5 years is?", expected: 100, hint: "No growth." }, loop("What patterns do you see in the growth curves?", "Why does compounding create exponential growth?", "How does inflation affect the real value?", "What if you increase contributions or the interest rate?", "Can you reach $2M in real value within 30 years?")),
      page("optimization", "Optimization", "/mathematical-modelling", "Optimization Modelling Lab", "Find the best decision under constraints. Compare models, evaluate trade-offs, and understand resources.", "Feasible region.", ["Production Planning", "Transport", "Design", "Allocation", "Scheduling"], { prompt: "If Max Z=50x+40y and (x,y)=(0,0), Z=?", expected: 0, hint: "Origin." }, loop("Explore the feasible region, constraints and objective line.", "Identify binding constraints and shadow values.", "See how resources impact profit and solutions.", "Adjust resources, move objective line, and test scenarios.", "Can you increase profit with the same resources?")),
      page("networks", "Networks & Routing", "/mathematical-modelling", "Networks & Routing Lab", "Find optimal routes on networks using shortest path algorithms and traffic conditions.", "Live route search.", ["Dijkstra", "A*"], { prompt: "Shortest path in a graph of equal weights uses fewest hops. Enter 1 if true.", expected: 1, hint: "BFS/Dijkstra on unit weights." }, loop("See how algorithms explore the network and find routes.", "Why some paths are better under current traffic and costs.", "How do heuristics reduce search time while preserving optimality?", "Change traffic, close roads, or switch algorithms and compare.", "Can you find a faster route with different assumptions?")),
      page("regression", "Regression", "/mathematical-modelling", "Regression & Prediction Lab", "Explore relationships, fit models, assess error, and make predictions.", "Train/validation split.", ["Scatter & Fit", "Residuals", "Diagnostics", "Prediction"], { prompt: "A perfect linear fit has R² = ?", expected: 1, hint: "All variance explained." }, loop("Scatter shows a curved relationship with a peak around 28–30 °C.", "Polynomial model explains more variance with lower error.", "Linear misses the curvature; polynomial captures it.", "Adjust degree, handle outliers, or transform variables.", "Can you improve predictions and reduce extrapolation risk?")),
      page("periodic", "Periodic Models", "/mathematical-modelling", "Periodic Phenomena Lab", "Explore, model and predict repeating patterns in the real world.", "Harmonic comparison.", ["Tides", "Seasons", "Daylight", "Sound", "Cycles"], { prompt: "A sine with period 12 hours has frequency 1/12. Enter 12 for the period.", expected: 12, hint: "Period is on the slider." }, loop("What patterns do you see? Zoom, inspect and measure.", "What drives these patterns? Explore parameters and theory.", "Why do the models differ? Link assumptions to fit quality.", "Test new models or change assumptions.", "Can you improve the model or predict further ahead?")),
      page("numerical", "Numerical Experiments", "/mathematical-modelling", "Numerical Experiments Lab", "Explore stochastic and deterministic computation through simulation and approximation.", "Estimate π.", ["Monte Carlo", "Iteration", "Random Walk", "Differential Approx.", "Sensitivity"], { prompt: "Monte Carlo π uses 4×(inside/total). If half the points are inside, estimate?", expected: 2, hint: "4×0.5." }, loop("Watch random points fall and see the estimate emerge.", "Why does this work? Connect area, probability, and limits.", "What affects accuracy and convergence speed?", "Change N, seeds, and settings. Run batches and compare.", "Can you reach 6-digit accuracy for π? Optimize the experiment.")),
      page("comparison", "Model Comparison", "/mathematical-modelling", "Model Comparison & Error Lab", "Compare candidate models, evaluate error, and choose the best explanatory model.", "Pick the best model.", ["Compare", "Residuals", "Selection"], { prompt: "Lower RMSE is better. Enter 1 if true.", expected: 1, hint: "Error metric." }, loop("Which model follows the data best? Check the fit and residuals.", "Why does one model outperform others? Explore assumptions.", "What causes underfit or overfit? Compare complexity and error.", "Adjust models, parameters, and see how performance changes.", "Can you build a better model with justified assumptions?")),
    ],
  },
  discrete: {
    id: "discrete", name: "Number & Discrete Studio", mark: "#", homeTitle: "Number & Discrete Mathematics Studio",
    homeSubtitle: "Explore the language of numbers, structures, and logic.",
    searchPlaceholder: "Search topics, tools, or problems...",
    basePath: "/discrete-world", continueLabel: "Modular Arithmetic", continueRoute: "/discrete-world/modular-arithmetic",
    pages: [
      page("home", "Studio Home", "/discrete-world", "Number & Discrete Mathematics Studio", "Numbers, logic, graphs, algorithms, crypto.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("Spot structure.", "Connect ideas.", "Prove a small claim.", "Run a tool.", "Solve the daily puzzle.")),
      page("number-sense", "Number Sense", "/discrete-world", "Number Sense & Number Lines Lab", "Compare and measure numbers on one line.", "Drag values on a line.", ["Integers", "Fractions", "Decimals", "Ratios", "Powers", "Scales"], { prompt: "Which is greater, −7 or −2? Enter the greater number.", expected: -2, hint: "Farther left is smaller." }, loop("Watch unit ticks and hops.", "Order is position, not digit size.", "Distance is |a−b|.", "Drag a point or add a hop.", "Which is greater, −7 or −2?")),
      page("primes", "Primes & Factors", "/discrete-world", "Factors, Primes & Divisibility Lab", "Sieve, factor trees, GCD and LCM.", "Visual proofs of uniqueness.", ["Sieve of Eratosthenes", "Factor Tree", "GCD & LCM", "Divisibility Rules", "Prime Patterns"], { prompt: "gcd(84,60)?", expected: 12, hint: "Common primes with min powers." }, loop("Run the sieve.", "See primes remain.", "Unique factorization.", "Change the range.", "Find a number with 18 divisors.")),
      page("modular-arithmetic", "Modular Arithmetic", "/discrete-world", "Modular Arithmetic Lab", "Clock arithmetic, inverses, linear congruences.", "Hops on a circle.", ["Clock Arithmetic", "Congruence", "Inverses", "Linear Congruences", "Cycles"], { prompt: "5×2 mod 12?", expected: 10, hint: "10 < 12." }, loop("Animate hops.", "See the cycle length.", "Inverses exist when gcd(a,n)=1.", "Solve 5x≡10 (mod 12).", "Prove a congruence.")),
      page("number-patterns", "Number Patterns", "/discrete-world", "Number Patterns Lab", "Explore beautiful patterns in numbers — figurate numbers, recurrences, Pascal's triangle and fractals.", "Grow a pattern.", ["Figurate", "Recursive", "Pascal Triangle", "Fractals"], { prompt: "6th triangular number?", expected: 21, hint: "n(n+1)/2." }, loop("See how each new row adds one more point.", "The nth triangular number is the total of the first n positive integers.", "Two copies of the triangle form an n × (n+1) rectangle.", "Change n and animate the construction.", "Find T20 without counting every dot.")),
      page("combinatorics", "Combinatorics", "/discrete-world", "Combinatorics Lab", "Arrangements, selections, inclusion-exclusion.", "Generating tree.", ["Arrangements", "Selections", "Pigeonhole", "Inclusion-Exclusion", "Generating Tree"], { prompt: "4 distinct items, all orders: 4! = ?", expected: 24, hint: "4×3×2×1." }, loop("Toggle order.", "Watch the count.", "Order matters for permutations.", "Allow repeats.", "Count with no adjacent repeats.")),
      page("logic", "Logic", "/discrete-world", "Mathematical Logic Lab", "Gates, truth tables, satisfiability.", "Build a circuit.", ["Circuit", "Truth Table", "Equivalence", "CNF/DNF", "SAT"], { prompt: "True AND False is 0. Enter 0.", expected: 0, hint: "AND needs both true." }, loop("Flip an input.", "See the table highlight.", "Gates compose formulas.", "Build XOR.", "Find a counterexample.")),
      page("sets", "Sets & Relations", "/discrete-world", "Sets & Relations Lab", "Venn, operations, relations, functions, equivalence.", "Drag elements.", ["Venn Diagram", "Operations", "Cartesian Products", "Relations", "Functions", "Equivalence"], { prompt: "|{1,2,3} ∪ {3,4}|?", expected: 4, hint: "1,2,3,4." }, loop("Drag into a region.", "Read union and intersection.", "Functions pair each input once.", "Test symmetry.", "Make R an equivalence.")),
      page("graphs", "Graph Networks", "/discrete-world", "Graph Theory & Networks Lab", "Paths, coloring, spanning trees, flows.", "Run Dijkstra.", ["Paths", "Connectivity", "Coloring", "Spanning Trees", "Flows"], { prompt: "A tree with 5 vertices has how many edges?", expected: 4, hint: "n−1." }, loop("Run the path.", "Read the cost.", "Dijkstra is optimal on nonnegative weights.", "Color the graph.", "Find a spanning tree.")),
      page("algorithms", "Algorithms", "/discrete-world", "Algorithms Lab", "Sorting, searching, Euclid, complexity.", "Step through Merge Sort.", ["Sorting", "Searching", "Euclid", "Graph Traversal", "Complexity"], { prompt: "Comparisons grow like n log n for merge sort. Enter 1 if true.", expected: 1, hint: "Divide and conquer." }, loop("Step the sort.", "Read the pseudocode.", "Divide and conquer is O(n log n).", "Switch to bubble sort.", "Compare complexity curves.")),
      page("cryptography", "Cryptography", "/discrete-world", "Cryptography Playground", "Classic ciphers and RSA as number theory.", "Educational keys only.", ["Caesar", "Affine", "Vigenère", "RSA Concept", "Diffie-Hellman", "Hashing"], { prompt: "Caesar shift 0 leaves A as A. Enter 0.", expected: 0, hint: "Identity shift." }, loop("Generate p and q.", "Watch modular exponentiation.", "RSA security is factoring n.", "Encrypt a letter.", "Decrypt with d.")),
    ],
  },
  statistics: {
    id: "statistics", name: "Statistics Studio", mark: "σ", homeTitle: "Statistics & Probability Studio",
    homeSubtitle: "Explore data. Model uncertainty. Draw conclusions.",
    searchPlaceholder: "Search datasets...",
    basePath: "/probability-statistics", continueLabel: "Distributions", continueRoute: "/probability-statistics/interactive-distributions",
    pages: [
      page("home", "Studio Home", "/probability-statistics", "Statistics & Probability Studio", "From data to decisions.", "", [], { prompt: "0", expected: 0, hint: "" }, loop("Explore a dataset.", "Summarize center and spread.", "See why CLT works.", "Run a test.", "Open a challenge.")),
      page("data-explorer", "Data Explorer", "/probability-statistics", "Data Explorer", "Import, filter, brush, and visualize.", "Histograms, scatter, box plots.", ["Overview", "Pairwise"], { prompt: "Median of 1,2,3?", expected: 2, hint: "Middle value." }, loop("Brush a region.", "Read the selected summary.", "Association appears in the scatter.", "Filter a category.", "Name a pattern.")),
      page("descriptive", "Descriptive Stats", "/probability-statistics", "Descriptive Statistics Lab", "Center, spread, shape, outliers.", "Dot, box, histogram, Q-Q.", ["Center", "Spread", "Shape", "Outliers", "Grouped"], { prompt: "IQR if Q1=2 and Q3=6?", expected: 4, hint: "Q3−Q1." }, loop("Drag an outlier.", "Watch the mean move.", "The median is resistant.", "Show ±2σ bands.", "Build a skewed set.")),
      page("interactive-distributions", "Distributions", "/probability-statistics", "Interactive Distributions Lab", "Normal, binomial, Poisson, t, chi-square.", "Shade probability.", ["Normal", "Binomial", "Poisson", "Exponential", "t", "Chi-square"], { prompt: "P(−1<Z<1) for standard normal is about 0.68. Enter 0.68.", expected: 0.68, hint: "68-95-99.7." }, loop("Shade between a and b.", "Read the live probability.", "σ stretches the bell.", "Switch to binomial.", "Match a scenario.")),
      page("experiments", "Probability Experiments", "/probability-statistics", "Probability Experiments Lab", "Coins, dice, cards, Bayes.", "Empirical vs theoretical.", ["Coins", "Dice", "Cards", "Spinner", "Conditional", "Bayes"], { prompt: "P(sum=7) with two fair dice = 6/36. Enter 0.167.", expected: 0.167, hint: "Six outcomes out of 36." }, loop("Run many trials.", "See the histogram fill.", "Relative frequency settles.", "Build an event.", "Estimate a rare event.")),
      page("counting", "Combinatorics", "/probability-statistics", "Combinatorics Lab", "Permutations, combinations, Pascal.", "Counting tree.", ["Permutations", "Combinations", "Arrangements", "Multisets", "Counting Tree", "Binomial Coefficients"], { prompt: "P(5,4) = 5!/(5-4)! = ?", expected: 120, hint: "5×4×3×2." }, loop("Toggle order.", "Watch nPr vs nCr.", "Order matters for permutations.", "Read Pascal's row.", "Count with restrictions.")),
      page("clt", "Sampling & CLT", "/probability-statistics", "Sampling & Central Limit Theorem Lab", "Sampling distributions of the mean.", "Repeated samples.", ["Population", "Sampling", "CLT"], { prompt: "SE = σ/√n. If σ=10 and n=25, SE=?", expected: 2, hint: "10/5." }, loop("Draw samples.", "Watch the mean-dot strip.", "Averages become normal.", "Increase n.", "Get an almost-normal sampling distribution.")),
      page("confidence-intervals", "Confidence Intervals", "/probability-statistics", "Confidence Intervals Lab", "Capture rate of repeated intervals.", "Mean, proportion, bootstrap.", ["Mean", "Proportion", "Two-sample", "Bootstrap"], { prompt: "A 95% CI aims to capture μ in 95 of 100 samples. Enter 95.", expected: 95, hint: "Confidence level." }, loop("Run simulations.", "Count blue vs red intervals.", "Width grows with confidence.", "Change n.", "Get margin of error under 2.")),
      page("hypothesis", "Hypothesis Testing", "/probability-statistics", "Hypothesis Testing Lab", "p-values, power, Type I/II.", "One and two samples.", ["One Sample Mean", "Two Sample Mean", "Proportion", "Chi-Square", "Permutation Test"], { prompt: "If p=0.02 and α=0.05, reject H0? Enter 1 for yes.", expected: 1, hint: "p < α." }, loop("Shift the null.", "See p-value change.", "Small p is evidence against H0.", "Change n.", "Inspect Type I / II.")),
      page("correlation", "Regression", "/probability-statistics", "Correlation & Regression Lab", "Fit, residuals, influential points.", "Drag points on the plot.", ["Linear Fit", "Residuals", "Prediction"], { prompt: "If all points are on a line with positive slope, r is 1. Enter 1.", expected: 1, hint: "Perfect correlation." }, loop("Drag a point.", "Watch r and R².", "Residuals diagnose the fit.", "Show the confidence band.", "Predict at a new x.")),
      page("anova", "ANOVA & Design", "/probability-statistics", "ANOVA & Experimental Design Lab", "Group means, variation, CRD.", "Between vs within.", ["Group Comparison", "Variation Decomposition", "Design Canvas", "Diagnostics"], { prompt: "If all group means are equal, F is near 1. Enter 1.", expected: 1, hint: "MSB ≈ MSW." }, loop("Randomize treatments.", "Watch between vs within.", "F compares those mean squares.", "Add a group.", "Run post-hoc.")),
    ],
  },
};

export function studioPagesWithoutHome(def: StudioMockupDefinition) {
  return def.pages.filter((item) => item.id !== "home");
}

/** AR and Discrete Sets/Graphs stay as routes/windows, not studio-home tiles. */
export function studioNavPages(def: StudioMockupDefinition) {
  return studioPagesWithoutHome(def).filter((item) => {
    if (item.id === "ar") return false;
    if (def.id === "discrete" && (item.id === "sets" || item.id === "graphs")) return false;
    return true;
  });
}

export function studioSidebarPages(def: StudioMockupDefinition) {
  return def.pages.filter((item) => item.id !== "ar");
}

export function matchStudioPage(def: StudioMockupDefinition, pathname: string, modeParam?: string | null): StudioMockupPage {
  const labs = studioPagesWithoutHome(def);
  const slug = pathname.replace(def.basePath, "").replace(/^\//, "");
  if (slug) {
    const found = def.pages.find((item) => item.id === slug || item.route === pathname);
    if (found) return found;
  }
  if (modeParam) {
    const byId = labs.find((item) => item.id === modeParam);
    if (byId) return byId;
  }
  return def.pages[0];
}

export const studioRouteTable = Object.values(studioMockups).flatMap((studio) =>
  studio.pages.map((item) => ({ studio: studio.id, path: item.route.replace(/^\//, ""), pageId: item.id })),
);
