import {describe,expect,it} from "vitest";import * as geo from "./geometryEnhancementEngine";
const triangle:[geo.Point,geo.Point,geo.Point]=[{x:0,y:0},{x:4,y:0},{x:0,y:3}];
describe("Geometry enhancement engine",()=>{
 it("constructs, constrains, and generates loci",()=>{expect(geo.constructionSteps("angle-bisector",triangle).valid).toBe(true);expect(geo.constrainToCircle({x:6,y:0},{x:0,y:0},3)).toEqual({x:3,y:0});expect(geo.locusCircle({x:0,y:0},2)).toHaveLength(36);});
 it("checks congruence, similarity, centres, Euler line, and nine-point circle",()=>{expect(geo.congruenceSSS([3,4,5],[5,3,4]).congruent).toBe(true);expect(geo.similarityScale([3,4,5],[6,8,10])).toMatchObject({similar:true,scale:2});expect(geo.triangleCentres(triangle).centroid).toEqual({x:4/3,y:1});expect(geo.eulerLine(triangle)?.ratioOGtoGH).toBeCloseTo(.5);expect(geo.ninePointCircle(triangle)?.radius).toBeCloseTo(1.25);});
 it("covers transformations, coordinate proof, polygons, and tessellation",()=>{expect(geo.transformPoint({x:1,y:0},{rotate:Math.PI/2}).y).toBeCloseTo(1);expect(geo.coordinateProof([{x:0,y:0},{x:1,y:1},{x:2,y:0},{x:3,y:1}]).parallel).toBe(true);expect(geo.polygonAngles(5).interiorSum).toBe(540);expect(geo.regularPolygon(6,2)).toHaveLength(6);expect(geo.regularTessellation(6,3).tessellates).toBe(true);});
 it("covers circles, conics, proofs, sections, and nets",()=>{expect(geo.circleTheorems({centralAngle:80,intersectingChord:[2,6,3]})).toEqual({inscribedAngle:40,missingChordSegment:4});expect(geo.powerOfPoint(5,3).tangentLength).toBe(4);expect(geo.conicPoint("ellipse",5,0)).toEqual({x:5,y:0});expect(geo.proofStepHighlight(1,[["A"],["B"]]).complete).toBe(true);expect(geo.theoremCounterexample({parallel:false},true).counterexamplePossible).toBe(true);expect(geo.cuboidSection([4,5,6],"xy",0).area).toBe(20);expect(geo.validateCubeNet([[0,0],[1,0],[2,0],[3,0],[1,1],[1,-1]]).plausibleNet).toBe(true);});
 it("covers dissections, topology, curved geometry, uncertainty, and exchange",()=>{expect(geo.prismDissection(12,5).pyramidVolume).toBe(20);expect(geo.eulerCharacteristic(8,12,6).convexPolyhedron).toBe(true);expect(geo.curvedGeometryAngleSum("spherical",.1,2).radians).toBeGreaterThan(Math.PI);expect(geo.measurementInterval(10,.1)).toMatchObject({minimum:9.9,maximum:10.1});expect(geo.serializeConstruction([{id:"A",type:"point",dependencies:[],data:{x:0,y:0}}]).objectCount).toBe(1);});
});
