import { useState } from "react";
import type { StudioSolid } from "./solidStudioModel";

export default function SolidStudioNet({ solid, size, height }: { solid: StudioSolid; size: number; height: number }) {
  const [selected, setSelected] = useState(0);
  const s = size, w = solid === "cuboid" ? size * 0.72 : size, h = solid === "cube" ? size : height;
  const faces: Array<{ name: string; points: string; area: number }> = [];
  const rectangle = (name: string, x: number, y: number, a: number, b: number) => faces.push({ name, points: `${x},${y} ${x + a},${y} ${x + a},${y + b} ${x},${y + b}`, area: a * b });
  if (solid === "cube" || solid === "cuboid") { rectangle("Base", s, s, s, w); rectangle("Top", s, s + w + h, s, w); rectangle("Front", s, s + w, s, h); rectangle("Back", s, s - h, s, h); rectangle("Left", s - h, s, h, w); rectangle("Right", 2 * s, s, h, w); }
  if (solid === "prism") { const t = Math.sqrt(3) * s / 2; for (let i = 0; i < 3; i++) rectangle(`Side ${i + 1}`, i * s, 0, s, h); faces.push({ name: "Base", points: `0,0 ${s},0 ${s / 2},${-t}`, area: s * t / 2 }, { name: "Top", points: `0,${h} ${s},${h} ${s / 2},${h + t}`, area: s * t / 2 }); }
  if (solid === "pyramid") { const t = Math.hypot(s / 2, h); rectangle("Base", 0, 0, s, s); [`0,0 ${s},0 ${s / 2},${-t}`, `0,${s} ${s},${s} ${s / 2},${s + t}`, `0,0 0,${s} ${-t},${s / 2}`, `${s},0 ${s},${s} ${s + t},${s / 2}`].forEach((points, i) => faces.push({ name: `Triangle ${i + 1}`, points, area: s * t / 2 })); }
  if (solid === "tetrahedron") { const t = Math.sqrt(3) * s / 2; [`0,0 ${s},0 ${s / 2},${t}`, `0,0 ${s},0 ${s / 2},${-t}`, `0,0 ${s / 2},${t} ${-s / 2},${t}`, `${s},0 ${s / 2},${t} ${1.5 * s},${t}`].forEach((points, i) => faces.push({ name: `Face ${i + 1}`, points, area: s * t / 2 })); }
  const vertices = faces.flatMap((face) => face.points.split(" ").map((p) => p.split(",").map(Number)));
  const minX = Math.min(0, ...vertices.map((p) => p[0])) - 1, minY = Math.min(0, ...vertices.map((p) => p[1])) - 1, maxX = Math.max(1, ...vertices.map((p) => p[0])) + 1, maxY = Math.max(1, ...vertices.map((p) => p[1])) + 1;
  if (solid === "sphere") return <p>A sphere cannot be flattened into an exact planar net without stretching or cuts. Surface area = {(Math.PI * size ** 2).toFixed(3)}.</p>;
  if (solid === "cylinder" || solid === "cone") { const radius = size / 2, slant = Math.hypot(radius, height), theta = 2 * Math.PI * radius / slant, R = 80; return <div><svg viewBox="0 0 300 280" role="img" aria-label={`${solid} net`} style={{ width: "100%" }}>{solid === "cylinder" ? <><rect x="20" y="90" width="260" height="100" fill="#06b6d433" stroke="#0891b2" /><circle cx="80" cy="55" r="35" fill="#8b5cf633" stroke="#8b5cf6" /><circle cx="80" cy="225" r="35" fill="#8b5cf633" stroke="#8b5cf6" /></> : <><path d={`M150 100L${150 + R} 100A${R} ${R} 0 ${theta > Math.PI ? 1 : 0} 1 ${150 + R * Math.cos(theta)} ${100 + R * Math.sin(theta)}Z`} fill="#06b6d433" stroke="#0891b2" /><circle cx="150" cy="230" r="35" fill="#8b5cf633" stroke="#8b5cf6" /></>}</svg><p>{solid === "cylinder" ? `Rectangle: ${(2 * Math.PI * radius).toFixed(3)} × ${height}; two circles of radius ${radius}. Diagram shown schematically.` : `Sector radius ${slant.toFixed(3)}, angle ${(theta * 180 / Math.PI).toFixed(3)}°; base circle radius ${radius}. Base shown separately.`}</p></div>; }
  return <div><svg viewBox={`${minX} ${minY} ${maxX - minX} ${maxY - minY}`} role="img" aria-label={`${solid} net`} style={{ width: "100%", minHeight: 180 }}>{faces.map((face, i) => <polygon key={face.name} points={face.points} fill={selected === i ? "#8b5cf666" : "#06b6d433"} stroke="#0891b2" strokeWidth=".06" />)}</svg><div className="gu-filter-row">{faces.map((face, i) => <button type="button" key={face.name} aria-pressed={i === selected} onClick={() => setSelected(i)}>{face.name}</button>)}</div><output>{faces[selected]?.name}: area {faces[selected]?.area.toFixed(3)} square units</output></div>;
}
