from pathlib import Path

BASE = Path(r"C:\Indian Servers\Interactive Biology App\Image text Prompts")

PHASE2_CATEGORIES = {
    "10_Evolution_and_Biodiversity",
    "11_Biochemistry_and_Metabolism",
    "12_Developmental_and_Reproductive_Biology",
    "13_Animal_Physiology_and_Homeostasis",
    "14_Biotechnology_and_Lab_Techniques",
    "15_Cancers_and_Oncology",
    "16_Animals_and_Zoology",
    "17_Drug_Discovery_and_Pharmacology",
}


def category_asset_focus(category: str) -> str:
    if category.startswith("10"):
        return """* Use evolutionary biology assets that show real evidence: branching phylogenetic trees, fossil layers, anatomical comparisons, DNA alignments, maps, allele-frequency graphs and population timelines.
* Use branching diagrams instead of ladder-of-progress imagery.
* Include at least one data-style panel such as a trait matrix, frequency graph, fossil timeline, range map or molecular comparison.
* Avoid generic silhouettes, progress marches, inaccurate ancestor-descendant chains or teleological visuals."""
    if category.startswith("11"):
        return """* Use biochemistry assets that look like premium molecular pathway plates: compartment-specific pathway maps, enzyme active-site insets, metabolite structures, membrane complexes, cofactors and regulation nodes.
* Include cellular compartment labels such as cytosol, mitochondrion, ER, nucleus, lysosome or membrane when relevant.
* Use clear stoichiometric arrows and energy/electron carriers where appropriate.
* Avoid random decorative molecules, impossible pathway loops, vague energy glows or unsupported supplement-style visuals."""
    if category.startswith("12"):
        return """* Use developmental biology assets with respectful, stage-accurate embryos, germ-layer maps, tissue patterning diagrams, hormone axes, timelines and microanatomy insets.
* Show developmental stages as proportional scientific diagrams, not miniature adults.
* Include timing, lineage, tissue-origin or signalling cues where relevant.
* Avoid sensational pregnancy imagery, inaccurate fetal staging or moralized visual framing."""
    if category.startswith("13"):
        return """* Use animal physiology assets with comparative anatomy, organ-system cutaways, feedback loops, blood/fluid/gas pathways, behavioural or adaptation panels and organism-specific examples.
* Include normal-versus-adapted or normal-versus-dysregulated comparisons when useful.
* Show homeostasis with clear sensors, control centres and effectors.
* Avoid anthropomorphic anatomy, vague body icons or arrows that do not map to physiological flow."""
    if category.startswith("14"):
        return """* Use laboratory and biotechnology assets: real instrument-style diagrams, workflow plates, microplates, gels, sequencing reads, cell-culture vessels, cytometry plots and control panels.
* Include positive controls, negative controls, standards, scale bars or readout graphs when relevant.
* Show sample-to-result workflows with contamination and quality-control checkpoints.
* Avoid magic black-box lab imagery, fictional instruments, unlabeled graphs or overconfident diagnostic claims."""
    if category.startswith("15"):
        return """* Use oncology assets specific to each cancer: organ anatomy, tumour origin tissue, histology/pathology inset, invasion route, lymphatic or blood spread, screening/diagnostic panel and treatment-category map.
* Include normal tissue versus premalignant or malignant change where appropriate.
* Show receptor, mutation, staging or grading panels only when biologically relevant to that cancer.
* Avoid frightening imagery, gore, generic red lumps, guaranteed-cure symbolism or one-size-fits-all cancer diagrams."""
    if category.startswith("16"):
        return """* Use zoology assets with accurate organism morphology, body plans, life cycles, comparative anatomy, habitat context and evolutionary relationships.
* Include labelled organism-specific structures rather than generic animal cartoons.
* Show scale, habitat layer, life stage, feeding route, movement or reproductive strategy where relevant.
* Avoid ranking animals as higher/lower, anthropomorphic expressions or mixing unrelated species in false ecological relationships."""
    if category.startswith("17"):
        return """* Use pharmaceutical R&D assets: target proteins, binding pockets, assay plates, robotic screening, molecular optimization panels, PK curves, trial diagrams, safety dashboards and regulatory workflow graphics.
* Include uncertainty, attrition, controls and validation steps visually.
* Show molecules interacting with specific targets rather than generic pill icons.
* Avoid miracle-drug imagery, guaranteed approval pathways, hidden safety concerns or direct medical advice."""
    return "* Use topic-specific scientific assets, not generic decorative biology imagery."


def universal_block(category: str) -> str:
    return f"""

# PREMIUM NON-GENERIC IMAGE ASSET REQUIREMENTS
{category_asset_focus(category)}
* Every major visual element must teach a specific structure, mechanism, pathway, disease step, ecological relationship, evolutionary relationship, experimental result or development stage.
* Use custom scientific illustration assets rather than stock-photo-style compositions.
* Make labels biologically anchored: every label line must point to a visible structure, cell, molecule, organism, graph feature, tissue, device or process step.
* Add a scale, orientation, timeline, specimen, compartment, life-stage, tissue-origin, assay-control or context cue where useful.
* Maintain consistent lighting, perspective and colour logic across all panels.
* Keep the central hero illustration visually dominant, but reserve enough negative space for readable labels.

# ADVANCED SCIENTIFIC ACCURACY AND LABEL QA
* Before final rendering, verify every label against the visible drawing.
* Do not invent structures, pathways, organisms, symptoms, treatments, statistics, trial outcomes or disease claims.
* Do not use oversimplified myths unless they appear in a clearly marked MYTHS AND FACTS panel.
* Keep arrows directional and biologically meaningful; do not use decorative arrows that imply false flow, ancestry, causality or treatment success.
* Use cautious language for medical, ecological, evolutionary, developmental and biotechnology claims.
* When uncertainty or variability matters, show it explicitly with wording such as varies by species, varies by person, depends on context, approximate, model-based or requires professional evaluation.
* Check spelling of all anatomical, medical, botanical, zoological, pharmacological and molecular terms.
* Ensure text does not overlap tissue structures, pathways, legends, graphs, organisms or icon panels.

# NEGATIVE PROMPT
No generic stock illustration, no random decorative DNA, no fake anatomy, no fictional organs, no incorrect arrows, no unreadable pathway labels, no unlabeled blobs, no progress-ladder evolution, no miniature-adult embryo, no sensational cancer imagery, no miracle-drug claims, no pseudo-scientific wellness language, no misleading statistics, no overconfident clinical claims, no watermarks, no logos, no cropped-off diagrams.
"""


TEMPLATE_QUALITY = """# OUTPUT QUALITY
* Ultra-HD 8K resolution
* Exact canvas size: 7680 x 4320 px
* Landscape orientation
* Premium, non-generic scientific infographic
* Extremely sharp anatomical, molecular, zoological, developmental, oncology or pharmaceutical illustration
* Crisp labels, precise leader lines and readable legends
* Professional medical-college, biology-classroom, pharmacy, biotechnology and science-museum quality
* No blurry text, no watermarks, no logos, no stock-image appearance"""


def make_prompt(title, subtitle, central, panels, process, accuracy, category):
    return f"""Act as a senior medical infographic designer, biology illustrator, anatomy editor and scientific-visualization specialist.

Create exactly ONE premium, highly detailed educational infographic about {title}.

# INFOGRAPHIC TITLE
{title}

# MAIN SUBTITLE
{subtitle}

{TEMPLATE_QUALITY}

# VISUAL STYLE
Use a premium, high-end scientific visualization style with a realistic central hero illustration, transparent cutaways, clean vector panels, microscopic or molecular insets, graph/data panels, glass-like information panels, precise labels and a strict colour legend.

# CENTRAL HERO ILLUSTRATION
Show and clearly label:
{central}

# REQUIRED EDUCATIONAL PANELS
Include:
{panels}

# PROCESS OR PATHWAY DIAGRAM
Show this sequence clearly:
{process}

# COMPOSITION
Top title and subtitle. Centre large hero illustration. Left side normal structure, evidence or baseline mechanism. Right side functional pathway, comparison, workflow, disease progression or application. Bottom strip key facts, warning signs, controls, myths or misconceptions.

# SCIENTIFIC ACCURACY REQUIREMENTS
{accuracy}

{universal_block(category)}

# FINAL RENDERING REQUIREMENTS
Produce one premium, accurate, readable 8K infographic suitable for medical education, school biology, college biology, pharmacy, biotechnology, digital learning and large-format printing.
"""


MISSING_PROMPTS = [
    ("10_Evolution_and_Biodiversity", "11_Coevolution_and_Arms_Races.txt", "COEVOLUTION AND EVOLUTIONARY ARMS RACES", "An illustrated guide to reciprocal evolution, predator-prey dynamics, host-parasite interactions, pollination, mimicry and adaptation tradeoffs", "* Predator and prey pair\n* Host and parasite\n* Flower and pollinator\n* Mimic and model species\n* Trait-matching diagram\n* Fitness graph\n* Phylogenetic tree\n* Time-series panels", "* Coevolution definition\n* Reciprocal selection\n* Red Queen dynamics\n* Pollination syndromes\n* Brood parasitism concept\n* Host-parasite resistance\n* Mimicry systems\n* Tradeoffs and constraints", "* Species A trait affects species B fitness\n* Species B evolves response traits\n* New trait changes selection on species A\n* Reciprocal changes accumulate over generations\n* Ecological context alters the strength of interaction", "* Coevolution is not cooperation by intention\n* Not every interacting pair is tightly coevolving\n* Avoid implying traits evolve because organisms need them\n* Show evidence through comparative data or trait matching"),
    ("10_Evolution_and_Biodiversity", "12_Sexual_Selection.txt", "SEXUAL SELECTION", "An illustrated guide to mate choice, competition, ornaments, signals, dimorphism, fitness tradeoffs and evolutionary outcomes", "* Male and female phenotype examples\n* Courtship display\n* Antlers or horns\n* Bird plumage\n* Signal honesty panel\n* Mate-choice graph\n* Sexual dimorphism comparison\n* Fitness tradeoff scale", "* Intrasexual competition\n* Intersexual choice\n* Ornaments and weapons\n* Honest signals\n* Sexual dimorphism\n* Runaway selection concept\n* Handicap principle concept\n* Natural selection tradeoffs\n* Parental investment", "* Heritable mating trait varies\n* Trait influences mating success\n* Individuals with trait leave more offspring\n* Trait frequency changes\n* Survival costs can balance mating benefits", "* Sexual selection is about reproductive success, not conscious beauty\n* Avoid human stereotypes\n* Not all species have strong sexual dimorphism\n* Mate choice and competition vary widely"),
    ("10_Evolution_and_Biodiversity", "13_Island_Biogeography.txt", "ISLAND BIOGEOGRAPHY", "An illustrated guide to island size, distance, colonization, extinction, endemism, adaptive radiation and conservation corridors", "* Mainland source pool\n* Near island\n* Far island\n* Large island\n* Small island\n* Colonization arrows\n* Extinction graph\n* Endemic species icons\n* Habitat fragments", "* Species-area relationship\n* Distance effect\n* Colonization rate\n* Extinction rate\n* Equilibrium model\n* Endemism\n* Adaptive radiation\n* Habitat islands\n* Conservation reserve design", "* Species disperse from source area\n* Colonization is higher on nearer islands\n* Extinction is lower on larger islands\n* Species richness approaches dynamic equilibrium\n* Isolation can promote endemism and radiation", "* Island biogeography is a model, not a perfect prediction\n* Habitat fragments can act like islands\n* Do not imply equilibrium means no change\n* Real islands differ in age, habitat and disturbance"),
    ("10_Evolution_and_Biodiversity", "14_Mass_Radiations_and_Cambrian_Explosion.txt", "MASS RADIATIONS AND THE CAMBRIAN EXPLOSION", "An illustrated guide to rapid diversification, fossil evidence, body-plan evolution, ecological opportunity and evolutionary innovation", "* Cambrian seafloor\n* Trilobite\n* Anomalocaris concept\n* Burgess Shale fossil panel\n* Body-plan silhouettes\n* Branching diversification tree\n* Oxygen/environment graph\n* Predator-prey icons", "* Adaptive radiation\n* Cambrian fossil record\n* Body-plan diversification\n* Ecological opportunity\n* Predation and armour\n* Developmental gene networks concept\n* Fossil preservation bias\n* Later radiations", "* Environmental and ecological changes create new opportunities\n* Lineages diversify into available niches\n* Innovations alter interactions\n* Fossils preserve snapshots of diversification\n* Later extinction and radiation reshape diversity", "* Do not imply evolution happened overnight\n* Cambrian explosion spans millions of years\n* Fossil record is incomplete\n* Avoid progress-ladder imagery"),
    ("10_Evolution_and_Biodiversity", "15_Molecular_Clock_and_Evolutionary_Time.txt", "MOLECULAR CLOCKS AND EVOLUTIONARY TIME", "An illustrated guide to mutation rates, sequence divergence, calibration fossils, phylogenies and estimating divergence dates", "* DNA sequence alignment\n* Mutation marks\n* Phylogenetic tree\n* Clock icon\n* Fossil calibration point\n* Confidence interval bar\n* Divergence timeline\n* Rate variation panel", "* Molecular clock concept\n* Sequence divergence\n* Mutation rates\n* Fossil calibration\n* Relaxed clocks\n* Confidence intervals\n* Sources of uncertainty\n* Applications in viruses and species evolution", "* DNA sequences accumulate changes\n* Researchers compare homologous sequences\n* Fossils or known dates calibrate rates\n* Models estimate divergence times\n* Uncertainty ranges are reported", "* Molecular clocks are estimates, not exact dates\n* Mutation rates vary across lineages and genes\n* Calibration quality matters\n* Confidence intervals must be shown"),
    ("11_Biochemistry_and_Metabolism", "21_Pentose_Phosphate_Pathway.txt", "PENTOSE PHOSPHATE PATHWAY", "An illustrated guide to NADPH production, ribose-5-phosphate, oxidative stress defence, nucleotide synthesis and red blood cell relevance", "* Cytosol\n* Glucose-6-phosphate\n* NADP+\n* NADPH\n* Ribose-5-phosphate\n* Glutathione\n* Red blood cell\n* Reactive oxygen species\n* Nucleotide synthesis icon", "* Oxidative phase\n* Non-oxidative phase\n* NADPH function\n* Ribose sugar production\n* Glutathione reduction\n* Fatty acid synthesis support\n* G6PD deficiency concept\n* Red blood cell vulnerability", "* Glucose-6-phosphate enters pathway\n* Oxidative phase produces NADPH\n* Ribose-5-phosphate supports nucleotide synthesis\n* Carbon skeletons interconvert with glycolysis intermediates\n* NADPH helps maintain reduced glutathione", "* Pathway is cytosolic\n* Do not confuse NADPH with NADH roles\n* G6PD deficiency increases oxidative stress risk in red blood cells\n* Avoid treatment advice"),
    ("11_Biochemistry_and_Metabolism", "22_Gluconeogenesis_and_Fasting_Metabolism.txt", "GLUCONEOGENESIS AND FASTING METABOLISM", "An illustrated guide to liver glucose production, lactate, glycerol, amino acids, hormones, glycogen and fasting adaptation", "* Liver\n* Kidney cortex\n* Lactate\n* Glycerol\n* Amino acids\n* Glucose\n* Glucagon\n* Insulin\n* Glycogen\n* Brain energy panel", "* Glycogenolysis\n* Gluconeogenesis substrates\n* Cori cycle\n* Alanine cycle\n* Hormonal regulation\n* Fasting timeline\n* Ketone body relationship\n* Energy costs\n* Clinical hypoglycaemia context", "* Blood glucose falls\n* Glucagon rises and insulin falls\n* Liver breaks down glycogen\n* Lactate, glycerol and amino acids feed gluconeogenesis\n* Liver releases glucose\n* Longer fasting increases fat oxidation and ketone production", "* Gluconeogenesis is not simply reverse glycolysis\n* Liver is main source, kidney contributes in prolonged fasting\n* Brain can use ketones during prolonged fasting but still needs some glucose\n* Avoid fasting advice"),
    ("11_Biochemistry_and_Metabolism", "23_Ketone_Bodies_and_Ketosis.txt", "KETONE BODIES AND KETOSIS", "An illustrated guide to ketogenesis, ketolysis, fasting, diabetes ketoacidosis, liver-mitochondria and brain fuel use", "* Liver mitochondrion\n* Fatty acids\n* Acetyl-CoA\n* Acetoacetate\n* Beta-hydroxybutyrate\n* Acetone\n* Brain\n* Muscle\n* Blood pH warning panel", "* Ketogenesis\n* Ketolysis\n* Fasting ketosis\n* Diabetic ketoacidosis distinction\n* Fat oxidation\n* Hormonal regulation\n* Brain fuel adaptation\n* Acid-base risk\n* Diabetes warning signs", "* Fatty acids enter liver mitochondria\n* Beta-oxidation produces acetyl-CoA\n* Excess acetyl-CoA forms ketone bodies\n* Ketones travel in blood\n* Extrahepatic tissues convert ketones to acetyl-CoA\n* In uncontrolled diabetes, excessive ketones can cause acidosis", "* Nutritional ketosis and diabetic ketoacidosis are different\n* Liver makes ketones but does not use them significantly\n* Do not glamorize or recommend diets\n* Ketoacidosis is a medical emergency"),
    ("11_Biochemistry_and_Metabolism", "24_Heme_Metabolism_and_Jaundice.txt", "HEME METABOLISM AND JAUNDICE", "An illustrated guide to red cell breakdown, bilirubin transport, liver conjugation, bile excretion and jaundice types", "* Old red blood cell\n* Macrophage\n* Heme\n* Biliverdin\n* Unconjugated bilirubin\n* Albumin\n* Liver hepatocyte\n* Conjugated bilirubin\n* Bile duct\n* Intestine", "* Haemoglobin breakdown\n* Bilirubin transport\n* Hepatic conjugation\n* Bile excretion\n* Urobilinogen\n* Pre-hepatic, hepatic and post-hepatic jaundice\n* Newborn jaundice overview\n* Lab markers concept", "* Macrophages break down old red cells\n* Heme becomes bilirubin\n* Unconjugated bilirubin travels bound to albumin\n* Liver conjugates bilirubin\n* Bile carries bilirubin into intestine\n* Metabolites leave in stool and urine", "* Do not show unconjugated bilirubin freely dissolved in blood\n* Jaundice is a sign with many causes\n* Bile obstruction and liver disease differ\n* Newborn jaundice needs clinical context"),
    ("11_Biochemistry_and_Metabolism", "25_Metabolic_Integration_Fed_and_Fasting_State.txt", "METABOLIC INTEGRATION: FED AND FASTING STATES", "An illustrated guide to liver, muscle, adipose, brain, insulin, glucagon and fuel switching after meals and fasting", "* Fed-state body map\n* Fasting-state body map\n* Liver\n* Muscle\n* Adipose tissue\n* Brain\n* Insulin\n* Glucagon\n* Glucose\n* Fatty acids\n* Ketones", "* Fed state\n* Post-absorptive state\n* Fasting state\n* Insulin actions\n* Glucagon actions\n* Glycogen storage\n* Lipogenesis\n* Lipolysis\n* Gluconeogenesis\n* Ketogenesis", "* Meal raises nutrients and insulin\n* Tissues store glucose and fat\n* Between meals insulin falls and glucagon rises\n* Liver releases glucose\n* Adipose releases fatty acids\n* Prolonged fasting increases ketone production", "* Metabolism is coordinated across organs\n* Hormonal states are gradients, not switches\n* Avoid diet prescriptions\n* Diabetes and starvation physiology require medical context"),
    ("12_Developmental_and_Reproductive_Biology", "11_Organogenesis_Overview.txt", "ORGANOGENESIS OVERVIEW", "An illustrated guide to how germ layers form organs, body patterning, tissue folding, heart tube, limb buds and early organ systems", "* Ectoderm\n* Mesoderm\n* Endoderm\n* Neural tube\n* Heart tube\n* Somites\n* Limb buds\n* Gut tube\n* Pharyngeal arches\n* Embryonic folding", "* Germ-layer derivatives\n* Neural development\n* Heart formation overview\n* Gut tube formation\n* Limb bud outgrowth\n* Somite differentiation\n* Inductive signalling\n* Critical periods\n* Congenital anomaly relevance", "* Germ layers form during gastrulation\n* Tissue sheets fold and interact\n* Signalling centres pattern organs\n* Organ primordia form\n* Cells differentiate and remodel\n* Organ systems mature through fetal development", "* Organ primordia are not miniature adult organs\n* Developmental timing varies by species\n* Avoid over-detailed human gestational claims unless labelled approximate\n* Use respectful medical language"),
    ("12_Developmental_and_Reproductive_Biology", "12_Limb_Development.txt", "LIMB DEVELOPMENT", "An illustrated guide to limb buds, apical ectodermal ridge, zone of polarizing activity, digit formation and patterning signals", "* Limb bud\n* Apical ectodermal ridge\n* Zone of polarizing activity\n* Progress zone\n* Cartilage template\n* Developing digits\n* Apoptosis between digits\n* Hox gene pattern map", "* Proximal-distal patterning\n* Anterior-posterior patterning\n* Dorsal-ventral patterning\n* FGF signalling\n* Sonic hedgehog gradient\n* Hox genes\n* Cartilage model\n* Digit separation\n* Congenital limb differences", "* Limb bud emerges\n* AER maintains outgrowth\n* ZPA patterns thumb-to-little-finger axis\n* Mesenchyme condenses into skeletal elements\n* Digits form and separate through apoptosis\n* Muscles, nerves and vessels integrate", "* Do not show digits appearing fully formed immediately\n* Patterning signals are gradients, not simple on/off labels\n* Limb differences require respectful language\n* Avoid deterministic single-gene simplification"),
    ("12_Developmental_and_Reproductive_Biology", "13_Sex_Determination_and_Differentiation.txt", "SEX DETERMINATION AND DIFFERENTIATION", "An illustrated guide to chromosomes, gonads, hormones, ducts, genital development, variation and respectful biology education", "* Chromosome panel\n* Bipotential gonad\n* SRY gene concept\n* Testis pathway\n* Ovary pathway\n* Wolffian ducts\n* Mullerian ducts\n* Hormone icons\n* External genital development timeline", "* Chromosomal sex\n* Gonadal differentiation\n* Hormonal signalling\n* Internal duct development\n* External genital development\n* Pubertal maturation\n* Differences of sex development\n* Respectful terminology\n* Medical evaluation context", "* Early embryo has bipotential structures\n* Genetic signals influence gonad development\n* Gonads produce hormones\n* Duct systems develop or regress depending on signals\n* External anatomy differentiates over time\n* Puberty adds further maturation", "* Biological sex development is multi-level and can vary\n* Avoid reducing sex to one chromosome marker\n* Use respectful non-stigmatizing language\n* Do not conflate biology education with social stereotypes"),
    ("12_Developmental_and_Reproductive_Biology", "14_Assisted_Reproductive_Technology_IVF.txt", "ASSISTED REPRODUCTIVE TECHNOLOGY AND IVF", "An illustrated guide to ovarian stimulation, egg retrieval, fertilization, embryo culture, transfer, cryopreservation and ethical care", "* Ovary with follicles\n* Ultrasound-guided retrieval\n* Egg cell\n* Sperm cell\n* IVF dish\n* ICSI pipette\n* Embryo culture\n* Blastocyst\n* Embryo transfer catheter\n* Cryostorage tank", "* IVF steps\n* Ovarian stimulation\n* Egg retrieval\n* Sperm preparation\n* Conventional IVF versus ICSI\n* Embryo culture\n* Embryo grading concept\n* Transfer\n* Cryopreservation\n* Success-rate caution", "* Medications stimulate follicles\n* Eggs are retrieved\n* Sperm is prepared\n* Fertilization occurs in lab\n* Embryos are cultured\n* Selected embryo is transferred or frozen\n* Pregnancy testing and follow-up occur", "* IVF success varies by age, diagnosis and clinic\n* Avoid guarantee language\n* Respect privacy and emotional complexity\n* Medical decisions require fertility specialists"),
    ("12_Developmental_and_Reproductive_Biology", "15_Contraception_Methods_Biology.txt", "CONTRACEPTION METHODS AND BIOLOGY", "An illustrated guide to barrier, hormonal, intrauterine, emergency and permanent contraception mechanisms", "* Sperm pathway\n* Ovulation icon\n* Cervical mucus\n* Uterus\n* IUD\n* Condom\n* Hormone pills/patch/ring\n* Implant\n* Emergency contraception icon\n* Vas deferens/fallopian tube icons", "* Barrier methods\n* Hormonal suppression of ovulation\n* Cervical mucus changes\n* IUD mechanisms\n* Emergency contraception\n* Sterilization\n* Effectiveness concepts\n* STI protection distinction\n* Shared decision-making", "* Method blocks sperm, suppresses ovulation, alters cervical mucus, affects uterine environment or prevents gamete transport depending on type\n* Correct use and user context influence effectiveness\n* Some methods protect against STIs and others do not", "* Do not imply all contraception works after fertilization\n* Condoms reduce STI risk; many methods do not\n* Avoid personal medical recommendations\n* Respect individual choice and medical eligibility"),
    ("13_Animal_Physiology_and_Homeostasis", "11_Endocrine_Feedback_in_Animals.txt", "ENDOCRINE FEEDBACK IN ANIMALS", "An illustrated guide to hormone feedback loops, hypothalamus, pituitary, thyroid, adrenal and reproductive axes across animals", "* Hypothalamus\n* Pituitary\n* Thyroid gland\n* Adrenal gland\n* Gonads\n* Hormone arrows\n* Negative feedback loop\n* Target tissue\n* Comparative animal icons", "* Endocrine glands\n* Negative feedback\n* Positive feedback examples\n* HPA axis\n* HPT axis\n* HPG axis\n* Hormone receptors\n* Homeostasis\n* Comparative physiology", "* Control centre releases hormone\n* Target gland responds\n* Target hormone affects tissues\n* Rising hormone feeds back to reduce upstream signals\n* Stress or reproduction can modify loop dynamics", "* Feedback loops are not simple one-way chains\n* Hormones act on cells with receptors\n* Animal endocrine systems vary by lineage\n* Avoid human-only assumptions"),
    ("13_Animal_Physiology_and_Homeostasis", "12_Animal_Nervous_Systems_Comparison.txt", "COMPARATIVE ANIMAL NERVOUS SYSTEMS", "An illustrated guide to nerve nets, ganglia, brains, spinal cords, sensory systems and behavioural control", "* Nerve net\n* Ganglion\n* Ventral nerve cord\n* Brain\n* Spinal cord\n* Sensory organ\n* Motor neuron\n* Synapse\n* Reflex circuit\n* Cephalization gradient", "* Nervous system diversity\n* Nerve nets in cnidarians\n* Ganglia in worms and arthropods\n* Vertebrate CNS\n* Cephalization\n* Reflexes\n* Sensory processing\n* Motor control\n* Evolutionary context", "* Sensory cells detect stimuli\n* Neural circuits process information\n* Motor neurons activate muscles\n* More centralized systems integrate complex behaviours\n* Evolution modifies circuits for different body plans", "* Do not rank nervous systems as higher or lower\n* Avoid implying all animals have brains\n* Nervous-system complexity varies with ecology and body plan\n* Keep dorsal/ventral nerve cord distinctions clear"),
    ("13_Animal_Physiology_and_Homeostasis", "13_Animal_Digestion_Strategies.txt", "ANIMAL DIGESTION STRATEGIES", "An illustrated guide to herbivore, carnivore, omnivore, ruminant, hindgut fermentation and digestive tract adaptation", "* Simple stomach\n* Ruminant stomach chambers\n* Cecum\n* Intestine length comparison\n* Teeth types\n* Microbial fermentation vat\n* Carnivore gut\n* Herbivore gut", "* Feeding strategies\n* Mechanical digestion\n* Chemical digestion\n* Foregut fermentation\n* Hindgut fermentation\n* Ruminants\n* Dentition\n* Microbiome role\n* Energy extraction tradeoffs", "* Food enters digestive tract\n* Mechanical processing increases surface area\n* Enzymes digest macromolecules\n* Microbes ferment plant fibre in specialized chambers\n* Nutrients are absorbed\n* Waste is eliminated", "* Do not imply herbivores digest cellulose without microbes\n* Digestive anatomy matches diet but has evolutionary constraints\n* Avoid simplistic carnivore/herbivore stereotypes\n* Fermentation location matters"),
    ("13_Animal_Physiology_and_Homeostasis", "14_Animal_Immune_Systems.txt", "ANIMAL IMMUNE SYSTEMS", "An illustrated guide to innate immunity, adaptive immunity in vertebrates, barriers, phagocytes, antibodies and immune diversity", "* Skin/exoskeleton barrier\n* Mucus\n* Phagocyte\n* Complement-like proteins\n* Lymphocyte\n* Antibody\n* Fish/amphibian/bird/mammal icons\n* Inflammation panel", "* Innate immunity across animals\n* Barriers\n* Phagocytosis\n* Antimicrobial peptides\n* Vertebrate adaptive immunity\n* Antibodies\n* Immune memory\n* Invertebrate immune strategies\n* Tradeoffs", "* Barrier prevents entry\n* Innate cells detect invaders\n* Phagocytes engulf pathogens\n* Signalling recruits defence\n* Vertebrate lymphocytes create specific responses and memory", "* Do not imply all animals have antibodies\n* Adaptive immunity is characteristic of vertebrates\n* Invertebrates still have effective immune defences\n* Avoid portraying all microbes as harmful"),
    ("13_Animal_Physiology_and_Homeostasis", "15_Animal_Sensory_Systems.txt", "ANIMAL SENSORY SYSTEMS", "An illustrated guide to vision, hearing, smell, electroreception, mechanoreception, echolocation and sensory adaptation", "* Compound eye\n* Camera eye\n* Antenna chemoreceptors\n* Lateral line\n* Bat echolocation\n* Shark electroreceptors\n* Owl ear asymmetry\n* Sensory neuron", "* Sensory receptor types\n* Visual systems\n* Chemical senses\n* Mechanoreception\n* Electroreception\n* Echolocation\n* Sensory ecology\n* Signal processing\n* Adaptation to habitat", "* Environmental energy reaches receptor\n* Receptor transduces signal\n* Neural pathway carries information\n* Brain or ganglia process patterns\n* Behaviour changes based on sensory input", "* Do not assume human senses are the standard\n* Sensory worlds differ by species\n* Avoid fictional superpowers\n* Show receptor anatomy accurately"),
    ("14_Biotechnology_and_Lab_Techniques", "11_Immunohistochemistry_and_Tissue_Staining.txt", "IMMUNOHISTOCHEMISTRY AND TISSUE STAINING", "An illustrated guide to tissue sections, antibodies, chromogenic or fluorescent detection, controls and pathology interpretation", "* Tissue block\n* Microtome section\n* Slide\n* Antigen\n* Primary antibody\n* Secondary antibody\n* Chromogen stain\n* Fluorescent label\n* Positive control\n* Negative control\n* Microscope field", "* Tissue fixation\n* Sectioning\n* Antigen retrieval\n* Blocking\n* Primary antibody binding\n* Detection systems\n* Counterstaining\n* Controls\n* Pathology use\n* Interpretation limits", "* Tissue is fixed and embedded\n* Thin sections are cut\n* Antigen retrieval exposes targets\n* Antibodies bind specific proteins\n* Detection reveals location\n* Controls validate staining\n* Pathologist interprets pattern", "* Staining pattern requires expert interpretation\n* Antibodies can be nonspecific\n* Controls are essential\n* IHC shows protein location, not always function"),
    ("14_Biotechnology_and_Lab_Techniques", "12_Mass_Spectrometry_Proteomics.txt", "MASS SPECTROMETRY AND PROTEOMICS", "An illustrated guide to protein digestion, peptide separation, ionization, mass analysis, spectra and protein identification", "* Protein sample\n* Trypsin enzyme\n* Peptides\n* Liquid chromatography column\n* Ion source\n* Mass analyzer\n* Detector\n* Mass spectrum\n* Database search panel\n* Protein coverage map", "* Proteomics workflow\n* Sample preparation\n* Enzymatic digestion\n* LC-MS/MS\n* Mass-to-charge ratio\n* Fragment spectra\n* Database matching\n* Quantitative proteomics\n* Controls and false discovery rate", "* Proteins are extracted\n* Enzymes digest proteins into peptides\n* Peptides separate by chromatography\n* Ionized peptides enter mass spectrometer\n* Spectra are recorded\n* Software matches spectra to sequences\n* Protein abundance and modifications are inferred", "* Proteomics depends on database quality\n* Missing detection is not proof of absence\n* Quantification requires controls\n* Avoid black-box certainty"),
    ("14_Biotechnology_and_Lab_Techniques", "13_RNA_Seq_and_Transcriptomics.txt", "RNA-SEQ AND TRANSCRIPTOMICS", "An illustrated guide to RNA extraction, library preparation, sequencing, expression analysis and gene regulation discovery", "* Cell sample\n* RNA molecules\n* mRNA enrichment\n* cDNA synthesis\n* Sequencing reads\n* Genome alignment\n* Expression heatmap\n* Volcano plot\n* Pathway enrichment panel", "* Transcriptome concept\n* RNA quality\n* Library preparation\n* Sequencing depth\n* Read alignment\n* Differential expression\n* Splicing analysis\n* Batch effects\n* Validation by qPCR\n* Biological interpretation", "* RNA is extracted\n* RNA is converted to cDNA library\n* Sequencer generates reads\n* Reads align to genome or transcriptome\n* Counts are normalized\n* Differential expression is tested\n* Pathways are interpreted and validated", "* RNA levels are not always protein levels\n* Sample quality and batch effects matter\n* Statistical correction is required\n* Correlation does not prove causation"),
    ("14_Biotechnology_and_Lab_Techniques", "14_Organs_on_Chips.txt", "ORGANS-ON-CHIPS", "An illustrated guide to microfluidic tissue models, flow, cell layers, mechanical forces, sensors and drug testing", "* Microfluidic chip\n* Cell-lined channel\n* Endothelial layer\n* Epithelial layer\n* Perfusion flow\n* Flexible membrane\n* Mechanical stretch\n* Sensor electrodes\n* Drug molecule\n* Readout graph", "* Microfluidics\n* Tissue-tissue interfaces\n* Fluid flow\n* Mechanical cues\n* Lung-on-chip concept\n* Gut-on-chip concept\n* Drug testing\n* Disease modelling\n* Limitations\n* Validation against real biology", "* Cells are cultured in microchannels\n* Media flows through channels\n* Mechanical forces mimic organ environment\n* Sensors capture responses\n* Drugs or toxins are introduced\n* Results are compared with known biology", "* Organ chips model selected features, not entire organs\n* Validation is essential\n* Results may not translate perfectly\n* Avoid replacing all animal/human studies claims"),
    ("14_Biotechnology_and_Lab_Techniques", "15_Gene_Therapy_Delivery_Systems.txt", "GENE THERAPY DELIVERY SYSTEMS", "An illustrated guide to viral vectors, nonviral delivery, target cells, gene expression, safety, immune response and clinical translation", "* AAV vector\n* Lentiviral vector\n* Lipid nanoparticle\n* Therapeutic gene\n* Target cell\n* Nucleus\n* Immune response icon\n* Off-target tissue\n* Manufacturing vial\n* Safety monitoring panel", "* In vivo gene therapy\n* Ex vivo gene therapy\n* Viral vectors\n* Nonviral delivery\n* Tissue targeting\n* Expression duration\n* Immune response\n* Insertional mutagenesis concept\n* Manufacturing\n* Clinical monitoring", "* Therapeutic genetic payload is designed\n* Delivery vehicle is selected\n* Vector reaches target cells\n* Payload enters cell\n* Gene is expressed or edited\n* Safety and efficacy are monitored", "* Gene therapy is not simple gene replacement in every case\n* Delivery and safety are major challenges\n* Avoid cure guarantees\n* Germline editing is not routine clinical care"),
    ("15_Cancers_and_Oncology", "11_Ovarian_Cancer.txt", "OVARIAN CANCER", "An illustrated guide to ovarian and fallopian tube origins, symptoms, spread, diagnosis, staging and treatment concepts", "* Ovary\n* Fallopian tube fimbriae\n* Pelvic cavity\n* Tumour nodule\n* Peritoneal spread\n* Ascites\n* CA-125 blood test icon\n* Ultrasound/CT panel\n* Pathology inset", "* Epithelial ovarian cancer\n* Fallopian tube origin concept\n* Peritoneal spread\n* Bloating and pelvic symptoms\n* Genetic risk BRCA concept\n* Imaging and surgery\n* Chemotherapy and targeted therapy categories\n* Screening limitations", "* Abnormal epithelial cells develop\n* Tumour may involve ovary or tube\n* Cells can spread across peritoneal surfaces\n* Fluid and symptoms may accumulate\n* Surgery and pathology define stage", "* Symptoms are nonspecific\n* No universal screening test for average risk\n* Genetic risk evaluation may matter\n* Avoid implying all ovarian cysts are cancer"),
    ("15_Cancers_and_Oncology", "12_Endometrial_Cancer.txt", "ENDOMETRIAL CANCER", "An illustrated guide to uterine lining cancer, hormone exposure, abnormal bleeding, biopsy, staging and treatment concepts", "* Uterus\n* Endometrium\n* Myometrium\n* Cervix\n* Endometrial hyperplasia\n* Tumour invasion depth\n* Biopsy pipelle\n* Ultrasound panel\n* Lymph node map", "* Endometrium anatomy\n* Hyperplasia\n* Risk factors\n* Abnormal uterine bleeding\n* Biopsy diagnosis\n* Grade and stage\n* Surgery concept\n* Radiation/systemic therapy categories\n* Prevention and early evaluation", "* Endometrial cells proliferate abnormally\n* Hyperplasia may develop\n* Cancer can invade myometrium\n* Abnormal bleeding prompts evaluation\n* Biopsy confirms diagnosis\n* Stage guides care", "* Postmenopausal bleeding needs evaluation\n* Not all abnormal bleeding is cancer\n* Avoid treatment guarantees\n* Hormonal risks require clinical context"),
    ("15_Cancers_and_Oncology", "13_Bladder_Cancer.txt", "BLADDER CANCER", "An illustrated guide to urothelial cancer, haematuria, cystoscopy, staging, smoking risk and treatment concepts", "* Bladder wall layers\n* Urothelium\n* Papillary tumour\n* Muscle layer\n* Blood in urine icon\n* Cystoscope\n* Urine cytology panel\n* Lymph node map\n* Intravesical therapy concept", "* Urothelial carcinoma\n* Non-muscle-invasive versus muscle-invasive disease\n* Haematuria\n* Cystoscopy\n* TURBT concept\n* Staging\n* Smoking and chemical exposure risk\n* Intravesical and systemic therapy categories", "* Urothelial cells acquire mutations\n* Papillary or flat lesions form\n* Tumour may remain superficial or invade muscle\n* Blood may appear in urine\n* Cystoscopy and pathology define stage", "* Blood in urine requires evaluation\n* Smoking is a major risk factor\n* Not all urinary symptoms are cancer\n* Avoid diagnostic certainty from symptoms alone"),
    ("15_Cancers_and_Oncology", "14_Kidney_Cancer_Renal_Cell_Carcinoma.txt", "KIDNEY CANCER: RENAL CELL CARCINOMA", "An illustrated guide to renal tumour anatomy, blood supply, symptoms, imaging, staging and treatment concepts", "* Kidney cortex\n* Renal mass\n* Renal artery\n* Renal vein\n* Collecting system\n* Tumour thrombus concept\n* CT scan panel\n* Biopsy/surgery icons\n* Metastasis map", "* Renal cell carcinoma\n* Incidental imaging detection\n* Blood in urine\n* Flank pain and mass classic triad caution\n* Staging\n* Surgery/ablation concepts\n* Targeted therapy\n* Immunotherapy categories\n* Risk factors", "* Kidney cell clone grows into mass\n* Tumour may alter blood vessels\n* Imaging detects lesion\n* Stage assesses local and distant spread\n* Treatment depends on size, stage and health context", "* Many kidney masses are found incidentally\n* Symptoms may be absent early\n* Imaging characterization is specialist work\n* Avoid implying every cyst is cancer"),
    ("15_Cancers_and_Oncology", "15_Thyroid_Cancer.txt", "THYROID CANCER", "An illustrated guide to thyroid nodules, follicular cells, ultrasound, biopsy, spread patterns and treatment concepts", "* Thyroid lobes\n* Isthmus\n* Follicular cells\n* Nodule\n* Calcification icon\n* Ultrasound probe\n* Fine-needle aspiration\n* Lymph nodes\n* Radioiodine concept", "* Thyroid nodules\n* Papillary and follicular thyroid cancer overview\n* Medullary/anaplastic caution panel\n* Ultrasound features\n* FNA biopsy\n* Lymph node spread\n* Surgery and radioiodine concepts\n* Prognosis variability", "* Thyroid nodule is detected\n* Ultrasound assesses features\n* Fine-needle biopsy samples cells\n* Pathology classifies cancer type\n* Stage and risk guide management", "* Most thyroid nodules are benign\n* Cancer types vary greatly\n* Do not imply all thyroid cancer is harmless\n* Specialist evaluation is required"),
    ("16_Animals_and_Zoology", "11_Primate_Evolution_and_Behavior.txt", "PRIMATE EVOLUTION AND BEHAVIOUR", "An illustrated guide to primate traits, hands, vision, social groups, cognition, locomotion and conservation", "* Primate skull\n* Forward-facing eyes\n* Grasping hand\n* Opposable thumb\n* Lemur\n* Monkey\n* Ape\n* Social group\n* Locomotion comparison\n* Forest habitat", "* Primate traits\n* Strepsirrhines and haplorhines\n* New World and Old World monkeys\n* Apes\n* Social behaviour\n* Tool use\n* Communication\n* Locomotor diversity\n* Conservation threats", "* Arboreal ancestry shapes grasping and vision\n* Lineages diversify into different habitats\n* Social systems evolve in ecological context\n* Behaviour affects survival and reproduction", "* Humans are primates but not descended from modern apes\n* Avoid ranking primates by intelligence\n* Behaviour varies by species\n* Conservation threats are human-driven"),
    ("16_Animals_and_Zoology", "12_Marine_Mammals.txt", "MARINE MAMMALS", "An illustrated guide to whales, dolphins, seals, manatees, diving physiology, echolocation and ocean conservation", "* Whale body\n* Dolphin echolocation beam\n* Seal flipper\n* Manatee\n* Blubber layer\n* Lung\n* Myoglobin-rich muscle\n* Dive profile graph\n* Ocean food web", "* Marine mammal groups\n* Adaptations to water\n* Diving reflex\n* Oxygen storage\n* Blubber\n* Echolocation\n* Thermoregulation\n* Feeding strategies\n* Conservation threats", "* Animal dives\n* Heart rate adjusts\n* Oxygen is stored in blood and muscle\n* Blood flow prioritizes vital organs\n* Animal resurfaces to breathe air\n* Echolocation or senses guide feeding", "* Marine mammals breathe air\n* Do not show gills\n* Diving adaptations vary by species\n* Avoid portraying all ocean threats as identical"),
    ("16_Animals_and_Zoology", "13_Pollinators_and_Flower_Interactions.txt", "POLLINATORS AND FLOWER INTERACTIONS", "An illustrated guide to bees, butterflies, birds, bats, flower signals, pollen transfer and ecosystem services", "* Bee\n* Butterfly\n* Hummingbird\n* Bat\n* Flower anther\n* Stigma\n* Pollen grains\n* Nectar guide\n* UV pattern panel\n* Fruit/seed icon", "* Pollination mechanism\n* Flower signals\n* Nectar rewards\n* Pollen transfer\n* Specialist and generalist interactions\n* Coevolution\n* Crop pollination\n* Pollinator decline\n* Habitat support", "* Pollinator visits flower\n* Pollen attaches to body\n* Pollinator moves to another flower\n* Pollen reaches stigma\n* Fertilization leads to seed and fruit development", "* Not all pollination is by bees\n* Some plants use wind or water\n* Pollination is not intentional help by animals\n* Avoid cartoon flower-animal relationships"),
    ("16_Animals_and_Zoology", "14_Venomous_Animals_and_Toxins.txt", "VENOMOUS ANIMALS AND TOXINS", "An illustrated guide to venom delivery, toxin types, snakes, spiders, scorpions, cone snails and medical relevance", "* Snake fang\n* Spider chelicerae\n* Scorpion stinger\n* Cone snail harpoon\n* Venom gland\n* Neurotoxin icon\n* Hemotoxin icon\n* Antivenom vial\n* Bite-site warning panel", "* Venom versus poison\n* Delivery structures\n* Neurotoxins\n* Hemotoxins\n* Cytotoxins\n* Defensive and predatory uses\n* Antivenom concept\n* Drug discovery from toxins\n* First-aid warning", "* Venom is produced in gland\n* Delivery structure injects venom\n* Toxins bind physiological targets\n* Prey or threat is affected\n* Medical care may use antivenom for specific cases", "* Venomous does not mean aggressive\n* Do not recommend harmful first-aid myths\n* Antivenom is specific and medically supervised\n* Toxins can inspire medicines"),
    ("16_Animals_and_Zoology", "15_Animal_Migration_and_Navigation.txt", "ANIMAL MIGRATION AND NAVIGATION", "An illustrated guide to seasonal migration, magnetic sensing, star cues, landmarks, energy costs and conservation barriers", "* Migrating birds\n* Monarch butterfly\n* Salmon\n* Whale\n* Magnetic field lines\n* Star compass\n* Sun compass\n* Migration route map\n* Stopover habitat\n* Barrier icons", "* Migration triggers\n* Navigation cues\n* Magnetic sense\n* Celestial cues\n* Olfaction in salmon\n* Energetic costs\n* Stopover ecology\n* Climate change\n* Human barriers\n* Conservation corridors", "* Environmental cues shift\n* Animals accumulate energy stores\n* Navigation systems guide movement\n* Individuals travel between habitats\n* Stopovers support recovery\n* Successful migration supports reproduction or survival", "* Migration varies by species\n* Not all individuals migrate\n* Navigation is multi-cue\n* Avoid implying animals follow a simple map like humans"),
    ("17_Drug_Discovery_and_Pharmacology", "11_Drug_Resistance_Mechanisms.txt", "DRUG RESISTANCE MECHANISMS", "An illustrated guide to resistance in bacteria, viruses, cancer and parasites through target changes, efflux, metabolism and selection", "* Drug molecule\n* Target protein mutation\n* Efflux pump\n* Drug-metabolizing enzyme\n* Resistant cell clone\n* Sensitive cell clone\n* Selection pressure graph\n* Combination therapy concept", "* Target alteration\n* Drug inactivation\n* Efflux pumps\n* Reduced uptake\n* Bypass pathways\n* Cancer resistance\n* Antiviral resistance\n* Combination therapy rationale\n* Stewardship", "* Drug exposure kills sensitive cells\n* Rare resistant variants survive\n* Resistant cells multiply\n* Resistance mechanisms reduce drug effect\n* Monitoring and combination strategies may slow resistance", "* Resistance evolves under selection\n* Human bodies do not become antibiotic-resistant; microbes do\n* Cancer resistance differs from bacterial resistance\n* Avoid blaming patients simplistically"),
    ("17_Drug_Discovery_and_Pharmacology", "12_Biomarkers_and_Companion_Diagnostics.txt", "BIOMARKERS AND COMPANION DIAGNOSTICS", "An illustrated guide to predictive, prognostic and pharmacodynamic biomarkers, patient selection and precision medicine", "* Patient sample\n* Tumour biopsy\n* Blood tube\n* DNA mutation marker\n* Protein biomarker\n* Diagnostic test cartridge\n* Treatment selection panel\n* Response graph", "* Biomarker types\n* Predictive biomarkers\n* Prognostic biomarkers\n* Pharmacodynamic biomarkers\n* Companion diagnostics\n* Sensitivity and specificity\n* Patient stratification\n* Validation\n* Regulatory context", "* Sample is collected\n* Biomarker assay is performed\n* Result is interpreted with clinical context\n* Patients are stratified\n* Therapy or trial eligibility may be selected\n* Outcomes validate biomarker utility", "* Biomarkers guide but do not guarantee response\n* Test accuracy and sample quality matter\n* Privacy and equity matter\n* Avoid overpromising precision medicine"),
    ("17_Drug_Discovery_and_Pharmacology", "13_Monoclonal_Antibodies.txt", "MONOCLONAL ANTIBODIES", "An illustrated guide to antibody structure, target binding, immune effector functions, manufacturing and therapeutic uses", "* Y-shaped antibody\n* Heavy chain\n* Light chain\n* Antigen-binding site\n* Fc region\n* Target receptor\n* Immune cell Fc receptor\n* Bioreactor\n* Infusion vial", "* Antibody structure\n* Specific target binding\n* Neutralization\n* Receptor blockade\n* ADCC concept\n* Humanized antibodies\n* Manufacturing in cells\n* Biosimilars\n* Side effects and monitoring", "* Target antigen is selected\n* Antibody is engineered\n* Cells manufacture antibody\n* Antibody is purified\n* Antibody binds target in patient\n* Biological effect depends on mechanism", "* Antibodies are proteins, not small-molecule pills\n* Target specificity is high but side effects can occur\n* Manufacturing quality matters\n* Avoid cure guarantees"),
    ("17_Drug_Discovery_and_Pharmacology", "14_RNA_Therapeutics.txt", "RNA THERAPEUTICS", "An illustrated guide to mRNA, siRNA, antisense oligonucleotides, delivery, gene silencing and protein production", "* mRNA strand\n* siRNA duplex\n* Antisense oligonucleotide\n* Lipid nanoparticle\n* Ribosome\n* RISC complex\n* Target mRNA\n* Liver cell\n* Immune sensor icon", "* mRNA medicines\n* siRNA silencing\n* Antisense mechanisms\n* RNA delivery\n* Chemical modification\n* Tissue targeting\n* Duration of effect\n* Safety and immune activation\n* Manufacturing", "* RNA therapeutic is designed\n* Delivery vehicle protects RNA\n* RNA enters target cell\n* mRNA is translated or siRNA/ASO binds target RNA\n* Protein production changes\n* RNA is degraded over time", "* RNA does not permanently rewrite DNA in normal mRNA therapy\n* Delivery is a major challenge\n* Effects depend on platform and target\n* Avoid platform hype"),
    ("17_Drug_Discovery_and_Pharmacology", "15_Pharmacogenomics.txt", "PHARMACOGENOMICS", "An illustrated guide to genetic variation, drug metabolism, transporters, receptors, dosing risk and personalized prescribing", "* DNA variant\n* CYP enzyme\n* Liver cell\n* Drug molecule\n* Active metabolite\n* Transporter\n* Receptor\n* Response curve\n* Adverse reaction warning\n* Test report", "* Genetic variants\n* CYP2D6/CYP2C19 concepts\n* Poor and rapid metabolizers\n* Transporter variants\n* HLA risk markers\n* Drug response variation\n* Test interpretation\n* Clinical decision support\n* Equity and access", "* Patient has genetic variation\n* Variant changes enzyme, transporter or immune recognition\n* Drug exposure or response changes\n* Test result informs risk category\n* Clinician integrates genetics with age, organ function and other medicines", "* Genes are one factor among many\n* Do not adjust medications without clinician guidance\n* Test panels vary\n* Avoid deterministic claims"),
]


def add_block_if_missing(path: Path, category: str):
    text = path.read_text(encoding="utf-8")
    if "# PREMIUM NON-GENERIC IMAGE ASSET REQUIREMENTS" in text:
        return False
    marker = "# FINAL RENDERING REQUIREMENTS"
    block = universal_block(category)
    if marker in text:
        text = text.replace(marker, block + "\n" + marker, 1)
    else:
        text = text.rstrip() + block + "\n"
    path.write_text(text, encoding="utf-8")
    return True


def main():
    enhanced = 0
    for category in PHASE2_CATEGORIES:
        folder = BASE / category
        if not folder.exists():
            continue
        for path in folder.glob("*.txt"):
            if add_block_if_missing(path, category):
                enhanced += 1

    created = 0
    for category, filename, title, subtitle, central, panels, process, accuracy in MISSING_PROMPTS:
        folder = BASE / category
        folder.mkdir(parents=True, exist_ok=True)
        path = folder / filename
        if not path.exists():
            path.write_text(make_prompt(title, subtitle, central, panels, process, accuracy, category), encoding="utf-8")
            created += 1

    print(f"Enhanced existing phase-2 files: {enhanced}")
    print(f"Created missing concept files: {created}")
    print(f"Total text files now: {len(list(BASE.rglob('*.txt')))}")


if __name__ == "__main__":
    main()
