from pathlib import Path

BASE = Path(r"C:\Indian Servers\Interactive Biology App\Image text Prompts")

COMMON_QUALITY = """# OUTPUT QUALITY
* Ultra-HD 8K resolution
* Exact canvas size: 7680 x 4320 px
* Landscape orientation
* Extremely sharp medical and biological illustration
* Print-quality scientific graphics
* Crisp, correctly spelled labels
* Professional biology-classroom, medical-college, public-health and science-museum quality
* No blurry or distorted text
* No scientific errors
* No fear-based or sensational imagery
* No watermarks
* No logos
* No stock-image appearance
* No unnecessary visual clutter"""

COMMON_FINAL = """# FINAL RENDERING REQUIREMENTS
Produce one visually rich, scientifically accurate and professionally composed 8K infographic suitable for school biology, college biology, microbiology, medical and nursing education, public-health displays, science museums, digital learning applications and large-format printing.

Prioritise biological accuracy, clear visual storytelling, sharp labelling, readable typography, balanced composition and premium 8K presentation."""


def build_prompt(spec):
    return f"""Act as a senior medical infographic designer, microbiology illustrator, anatomy editor and scientific-visualization specialist.

Create exactly ONE premium, highly detailed educational infographic about {spec['about']}.

# INFOGRAPHIC TITLE
{spec['title']}

# MAIN SUBTITLE
{spec['subtitle']}

{COMMON_QUALITY}

# VISUAL STYLE
Use a premium modern scientific-infographic style combining realistic three-dimensional biological structures, clean vector-style educational diagrams, transparent cutaways, microscopic scenes, colour-coded pathways, molecular detail panels, glass-like information panels, precise annotation lines, subtle gradients, balanced spacing and strong visual hierarchy.

Use consistent colour coding:
{spec['colors']}

# BACKGROUND
Create a sophisticated white-to-light-blue clinical/scientific gradient background with subtle grid lines, faint molecular or microscopic patterns, soft glows related to the topic and generous negative space.

# CENTRAL HERO ILLUSTRATION
Place a large, scientifically accurate central illustration.

Show and clearly label:
{spec['central']}

# REQUIRED EDUCATIONAL PANELS
Create well-organized supporting panels covering:
{spec['panels']}

# PROCESS OR PATHWAY DIAGRAM
Include a clear step-by-step pathway or sequence:
{spec['process']}

# KEY FACTS PANEL
Create a clean statistics and key-facts panel with icons. Include concise, evidence-based facts only. Avoid exaggerated claims, unsupported numbers and misleading simplifications.

# COMMON CONDITIONS, APPLICATIONS OR PUBLIC-HEALTH CONTEXT
Include a neutral educational panel covering:
{spec['conditions']}

Use careful wording. Medical and infectious-disease topics must include that symptoms, causes, prevention and treatments vary, and professional medical evaluation is required for diagnosis or treatment decisions.

# COMPOSITION
Use a premium, structured layout:
* Top: title, subtitle and short introduction
* Centre: large hero illustration
* Upper left: main structure, anatomy or organism labels
* Upper right: key functions, mechanisms or life cycle
* Lower left: microscopic or molecular detail
* Lower right: disease, diagnosis, treatment, prevention or application panel
* Bottom strip: key facts, safety notes, myths and common misconceptions

Specific composition guidance:
{spec['composition']}

# TYPOGRAPHY
* Bold modern sans-serif font
* Large, highly legible main title
* Clear uppercase section headings
* Large readable body text
* Consistent label size
* Correct scientific and medical terminology
* No spelling mistakes
* No text overlapping diagrams
* Use short captions rather than dense paragraphs
* Preserve scientific symbols, units and punctuation correctly

# SCIENTIFIC ACCURACY REQUIREMENTS
{spec['accuracy']}

{COMMON_FINAL}
"""


SPECS = [
    # 04 Microbiology
    ("04_Microbiology", "01_Bacterial_Cell_Structure.txt", "BACTERIAL CELL STRUCTURE", "BACTERIAL CELL STRUCTURE", "An illustrated guide to prokaryotic anatomy, cell walls, capsules, flagella, plasmids, ribosomes and bacterial survival", "* Cell wall teal\n* Plasma membrane blue\n* Capsule pale gold\n* Cytoplasm light green\n* Nucleoid purple\n* Plasmids pink\n* Ribosomes black\n* Flagella orange\n* Pili yellow", "* Capsule\n* Cell wall\n* Plasma membrane\n* Cytoplasm\n* Nucleoid DNA\n* Plasmids\n* 70S ribosomes\n* Pili\n* Flagellum\n* Inclusion bodies\n* Biofilm matrix", "* Prokaryote versus eukaryote comparison\n* Gram-positive and Gram-negative cell envelopes\n* Peptidoglycan\n* Capsule functions\n* Pili and conjugation\n* Flagellar movement\n* Plasmids and antibiotic resistance genes\n* Binary fission overview\n* Biofilm formation\n* Beneficial and harmful bacteria", "* Nutrients enter cell\n* DNA replicates\n* Cell elongates\n* Septum forms\n* Binary fission produces two daughter cells\n* Some bacteria exchange plasmids by conjugation\n* Biofilms protect bacterial communities", "* Normal microbiota\n* Food fermentation\n* Pathogenic bacteria\n* Antibiotic resistance\n* Sterilization and disinfection\n* Vaccination against some bacterial diseases\n* Medical diagnosis using culture, microscopy and molecular tests", "Use one large bacterial cutaway in the centre, Gram-positive/Gram-negative comparison on the left and binary fission/biofilm panels on the right.", "* Do not show bacteria with a nucleus or mitochondria\n* Do not portray all bacteria as harmful\n* Distinguish plasmids from chromosomal DNA\n* Show Gram-negative bacteria with outer membrane and thin peptidoglycan\n* Show Gram-positive bacteria with thick peptidoglycan"),
    ("04_Microbiology", "02_Bacterial_Growth_and_Reproduction.txt", "BACTERIAL GROWTH AND REPRODUCTION", "BACTERIAL GROWTH AND REPRODUCTION", "An illustrated guide to binary fission, growth curves, colony formation, environmental factors, spores and microbial control", "* Individual bacteria green\n* DNA purple\n* Septum gold\n* Colonies cream\n* Lag phase blue\n* Log phase orange\n* Stationary phase violet\n* Death phase red\n* Endospores brown", "* Parent bacterial cell\n* Replicated chromosome\n* Septum\n* Daughter cells\n* Petri dish colonies\n* Growth curve axes\n* Nutrient agar\n* Endospore\n* Vegetative cell\n* Environmental gradients", "* Binary fission stages\n* Bacterial growth curve\n* Lag, log, stationary and death phases\n* Colony-forming units\n* Temperature, pH, oxygen and nutrient effects\n* Aerobes, anaerobes and facultative anaerobes\n* Endospore formation\n* Sterilization, pasteurization and refrigeration\n* Biosecurity and aseptic technique", "* Bacteria adapt to medium\n* Cells divide exponentially during log phase\n* Nutrients become limited\n* Waste accumulates\n* Population reaches stationary phase\n* Cells die or persist\n* Some species form resistant endospores under stress", "* Food spoilage\n* Food safety\n* Culture-based diagnosis\n* Industrial fermentation\n* Hospital infection control\n* Antibiotic susceptibility testing\n* Limits of growth control methods", "Place a binary-fission sequence across the centre with a growth curve above and Petri dish/colony panels below.", "* Binary fission is asexual reproduction\n* Do not imply all bacteria form endospores\n* Distinguish sterilization from disinfection\n* Growth curves describe populations, not a single cell\n* Avoid implying cold always kills bacteria"),
    ("04_Microbiology", "03_Gram_Staining_and_Bacterial_Classification.txt", "GRAM STAINING AND BACTERIAL CLASSIFICATION", "GRAM STAINING AND BACTERIAL CLASSIFICATION", "An illustrated guide to Gram-positive and Gram-negative bacteria, staining steps, cell-wall differences, shapes and diagnostic interpretation", "* Gram-positive purple\n* Gram-negative pink-red\n* Crystal violet violet\n* Iodine amber\n* Alcohol decolorizer pale blue\n* Safranin red\n* Peptidoglycan teal\n* Outer membrane orange", "* Gram-positive coccus\n* Gram-negative rod\n* Thick peptidoglycan\n* Thin peptidoglycan\n* Outer membrane\n* Periplasm\n* Lipopolysaccharide\n* Microscope slide\n* Staining reagents\n* Bacterial shapes", "* Gram stain steps\n* Crystal violet, iodine, decolorization and counterstain\n* Cell-wall structural differences\n* Cocci, bacilli, spirilla, vibrios and spirochetes\n* Arrangements such as chains, clusters and pairs\n* Aerobic/anaerobic classification\n* Clinical relevance\n* Limitations of Gram staining\n* Culture and molecular confirmation", "* Prepare smear\n* Heat-fix sample\n* Apply crystal violet\n* Add iodine mordant\n* Decolorize carefully\n* Apply safranin\n* View under oil immersion\n* Interpret colour, shape and arrangement", "* Rapid preliminary diagnosis\n* Antibiotic selection guidance\n* Gram-variable organisms\n* Acid-fast bacteria requiring different stains\n* Contamination and sample-quality issues\n* Laboratory safety", "Use a split central comparison of Gram-positive and Gram-negative envelopes, with staining workflow as a numbered strip.", "* Gram stain is not definitive species identification\n* Do not show Gram-negative bacteria retaining purple after correct decolorization\n* Acid-fast organisms are not classified well by Gram stain\n* Correctly show thick peptidoglycan in Gram-positive cells\n* Avoid implying shape alone identifies species"),
    ("04_Microbiology", "04_Antibiotics_and_Antibiotic_Resistance.txt", "ANTIBIOTICS AND ANTIBIOTIC RESISTANCE", "ANTIBIOTICS AND ANTIBIOTIC RESISTANCE", "An illustrated guide to antibiotic targets, resistance mechanisms, stewardship, susceptibility testing and global health impact", "* Antibiotics teal\n* Bacteria green\n* Resistant bacteria red\n* Cell wall target orange\n* Ribosome target purple\n* DNA target blue\n* Efflux pump yellow\n* Resistance gene magenta\n* Stewardship panel navy", "* Bacterial cell wall\n* Ribosome\n* DNA gyrase target\n* Cell membrane\n* Efflux pump\n* Beta-lactamase enzyme\n* Plasmid\n* Resistance gene\n* Antibiotic gradient plate\n* Zone of inhibition", "* Antibiotic classes by target\n* Cell-wall synthesis inhibitors\n* Protein synthesis inhibitors\n* DNA/RNA synthesis inhibitors\n* Membrane disruptors\n* Resistance through enzyme inactivation, target modification, reduced permeability and efflux\n* Horizontal gene transfer\n* Susceptibility testing\n* Antibiotic stewardship\n* Infection prevention", "* Antibiotic exposure creates selection pressure\n* Susceptible bacteria die or stop growing\n* Resistant variants survive\n* Resistant bacteria multiply\n* Resistance genes spread by plasmids\n* Inappropriate use accelerates resistance\n* Stewardship slows selection pressure", "* MRSA concept\n* Multidrug-resistant tuberculosis concept\n* Hospital-acquired infections\n* Agricultural and community antibiotic use\n* Vaccination and hygiene reducing antibiotic demand\n* Importance of completing prescribed therapy as directed by clinicians", "Put bacterial target diagram centrally, resistance mechanisms around it and stewardship/susceptibility testing as strong bottom panels.", "* Antibiotics do not treat viral infections\n* Resistance develops in bacterial populations, not because the human body becomes resistant\n* Do not imply all resistance is caused by patient misuse alone\n* Show stewardship as public-health and clinical teamwork\n* Avoid recommending specific drugs"),
    ("04_Microbiology", "05_Human_Microbiome.txt", "THE HUMAN MICROBIOME", "THE HUMAN MICROBIOME", "An illustrated guide to beneficial microbes, body-site ecosystems, digestion, immunity, dysbiosis and microbiome research", "* Gut microbes green\n* Skin microbes orange\n* Oral microbes blue\n* Vaginal microbes pink\n* Immune links purple\n* Short-chain fatty acids gold\n* Pathobionts red\n* Fibre brown", "* Skin microbiome\n* Oral microbiome\n* Gut microbiome\n* Respiratory microbiome\n* Urogenital microbiome\n* Bacteria\n* Fungi\n* Archaea\n* Viruses/phages\n* Mucus layer\n* Intestinal epithelium\n* Immune cells", "* Body-site diversity\n* Symbiosis and commensalism\n* Gut barrier\n* Fibre fermentation\n* Short-chain fatty acids\n* Microbiome and immune education\n* Dysbiosis concept\n* Antibiotic effects\n* Probiotics and prebiotics with cautious wording\n* Research methods such as sequencing", "* Dietary fibre reaches colon\n* Microbes ferment fibre\n* Metabolites such as short-chain fatty acids form\n* Gut barrier and immune cells interact with microbes\n* Balanced communities help resist pathogen overgrowth\n* Disruption can contribute to dysbiosis", "* Antibiotic-associated diarrhoea\n* Clostridioides difficile concept\n* Inflammatory bowel disease research links\n* Metabolic disease research links\n* Skin and oral health\n* Fecal microbiota transplantation as supervised medical therapy for specific indications", "Use a full-body body-site map in the centre, gut cross-section as the largest detail panel and research/health panels at the bottom.", "* Do not portray all microbes as germs\n* Avoid claiming probiotics cure all diseases\n* Correlation does not prove causation in microbiome research\n* Body-site microbiomes differ greatly\n* Keep claims evidence-based and cautious"),
    ("04_Microbiology", "06_Fungi_and_Mycology.txt", "FUNGI AND MYCOLOGY", "FUNGI AND MYCOLOGY", "An illustrated guide to fungal cells, yeasts, moulds, hyphae, spores, decomposition, symbiosis and fungal disease", "* Fungal cell wall brown\n* Chitin gold\n* Yeast cells cream\n* Hyphae green\n* Spores purple\n* Mycelium teal\n* Pathogenic fungi red\n* Antifungal targets blue", "* Yeast cell\n* Budding scar\n* Mould hyphae\n* Mycelium\n* Septa\n* Spores\n* Fruiting body\n* Fungal cell wall\n* Nucleus\n* Mitochondria\n* Vacuole\n* Ergosterol membrane", "* Fungi as eukaryotes\n* Yeasts versus moulds\n* Hyphae and mycelium\n* Spore production\n* Decomposition\n* Mycorrhizae\n* Lichens\n* Fermentation uses\n* Antifungal targets\n* Superficial and invasive fungal infections", "* Spore lands on suitable surface\n* Germ tube forms\n* Hypha grows\n* Mycelium expands\n* Nutrients are absorbed externally\n* Reproductive structures form\n* Spores disperse to new environments", "* Athlete's foot\n* Ringworm\n* Candidiasis\n* Aspergillosis\n* Cryptococcosis\n* Food spoilage\n* Antibiotic production and fermentation\n* Immunocompromised-host risk", "Make yeast and mould comparison central, with fungal cell anatomy and life-cycle panels on either side.", "* Fungi are eukaryotes, not bacteria\n* Antibiotics for bacteria usually do not treat fungal infections\n* Do not show fungi photosynthesizing\n* Distinguish superficial from invasive fungal disease\n* Do not imply all fungi are harmful"),
    ("04_Microbiology", "07_Protozoa_and_Protists.txt", "PROTOZOA AND PROTISTS", "PROTOZOA AND PROTISTS", "An illustrated guide to diverse single-celled eukaryotes, movement, feeding, reproduction, ecology and parasitic disease", "* Amoeba green\n* Flagellates blue\n* Ciliates purple\n* Apicomplexans red\n* Nucleus violet\n* Food vacuoles orange\n* Contractile vacuole cyan\n* Parasite stages gold", "* Amoeba\n* Ciliate\n* Flagellate\n* Apicomplexan parasite\n* Nucleus\n* Mitochondria\n* Food vacuole\n* Contractile vacuole\n* Cilia\n* Flagellum\n* Pseudopodia\n* Cyst stage", "* Protists as diverse eukaryotes\n* Movement by cilia, flagella and pseudopodia\n* Feeding strategies\n* Asexual and sexual reproduction examples\n* Cyst formation\n* Freshwater osmoregulation\n* Ecological roles in aquatic food webs\n* Symbiosis\n* Parasitic protozoa\n* Diagnostic microscopy", "* Protist encounters food\n* Movement structures guide cell\n* Food is engulfed or absorbed\n* Vacuoles process nutrients\n* Waste exits cell\n* Under stress some form cysts\n* Parasite forms may move between hosts or tissues", "* Malaria parasite concept\n* Amoebiasis\n* Giardiasis\n* Toxoplasmosis\n* Sleeping sickness\n* Water sanitation\n* Vector control\n* Microscopy and antigen/molecular testing", "Use a four-organism comparison as the central visual, with movement mechanisms and parasite life-cycle caution panels around it.", "* Protists are not one simple organism type\n* Do not classify protozoa as bacteria\n* Do not imply all protists are parasites\n* Life cycles vary widely\n* Avoid inaccurate host or vector pathways"),
    ("04_Microbiology", "08_Algae_and_Aquatic_Microbes.txt", "ALGAE AND AQUATIC MICROBES", "ALGAE AND AQUATIC MICROBES", "An illustrated guide to photosynthetic microbes, aquatic ecosystems, oxygen production, blooms, toxins and climate relevance", "* Green algae emerald\n* Diatoms gold-brown\n* Cyanobacteria blue-green\n* Chloroplasts green\n* Sunlight yellow\n* Oxygen red\n* Carbon dioxide grey\n* Harmful bloom red-orange", "* Green alga\n* Diatom silica shell\n* Cyanobacterium\n* Chloroplast\n* Thylakoids\n* Gas vesicles\n* Flagella where present\n* Aquatic food web\n* Phytoplankton bloom\n* Zooplankton grazer", "* Algae versus cyanobacteria\n* Photosynthesis\n* Phytoplankton food webs\n* Oxygen production\n* Diatoms and silica shells\n* Nitrogen fixation in some cyanobacteria\n* Harmful algal blooms\n* Eutrophication\n* Toxins and hypoxia\n* Climate and carbon cycling", "* Sunlight and nutrients support growth\n* Photosynthetic microbes fix carbon dioxide\n* Oxygen is released\n* Zooplankton consume phytoplankton\n* Excess nutrients can trigger blooms\n* Bloom decay can lower dissolved oxygen\n* Some species produce toxins", "* Harmful algal blooms\n* Water quality monitoring\n* Fisheries impact\n* Drinking-water safety\n* Climate research\n* Biofuel research\n* Aquaculture relevance", "Make a bright aquatic microscopic scene central, with food web and bloom sequence panels along the bottom.", "* Cyanobacteria are bacteria, not algae in the strict cellular sense\n* Do not imply every bloom is toxic\n* Oxygen production varies by ecosystem\n* Do not show algae as plants with roots and leaves\n* Keep eutrophication sequence accurate"),
    ("04_Microbiology", "09_Microbial_Ecology_and_Nutrient_Cycles.txt", "MICROBIAL ECOLOGY AND NUTRIENT CYCLES", "MICROBIAL ECOLOGY AND NUTRIENT CYCLES", "An illustrated guide to microbes in soil, oceans, decomposition, nitrogen cycling, carbon cycling, symbiosis and ecosystem health", "* Soil microbes brown\n* Ocean microbes blue\n* Carbon cycle grey-green\n* Nitrogen cycle violet\n* Decomposers orange\n* Symbiosis teal\n* Methanogens purple\n* Plant roots green", "* Soil particles\n* Plant roots\n* Rhizosphere\n* Bacteria\n* Fungi\n* Archaea\n* Decomposing leaf litter\n* Nitrogen-fixing nodules\n* Ocean plankton\n* Biofilm\n* Sediment layers", "* Decomposition\n* Carbon cycle\n* Nitrogen fixation\n* Nitrification\n* Denitrification\n* Methanogenesis\n* Symbiosis with plants and animals\n* Rhizosphere interactions\n* Ocean microbial loop\n* Biofilms in nature\n* Microbes and climate feedbacks", "* Dead organic matter enters soil\n* Decomposers break polymers into smaller molecules\n* Carbon returns as carbon dioxide or biomass\n* Nitrogen is fixed, transformed and returned to atmosphere\n* Plants absorb nutrients\n* Microbes exchange nutrients in food webs", "* Soil fertility\n* Composting\n* Wastewater treatment\n* Bioremediation\n* Climate change research\n* Agricultural nitrogen management\n* Harmful nutrient runoff", "Use an ecosystem cross-section from soil to water as the centre, with nitrogen and carbon cycles as two large looping diagrams.", "* Do not show nutrient cycles as linear one-way arrows\n* Distinguish bacteria, fungi and archaea where relevant\n* Avoid implying microbes only cause disease\n* Keep nitrogen-cycle terms correctly placed\n* Show decomposition as ecological recycling"),
    ("04_Microbiology", "10_Laboratory_Culture_and_Aseptic_Technique.txt", "LABORATORY CULTURE AND ASEPTIC TECHNIQUE", "LABORATORY CULTURE AND ASEPTIC TECHNIQUE", "An illustrated guide to culturing microbes safely, sterile technique, media, incubation, colony isolation and contamination control", "* Sterile field blue\n* Agar medium amber\n* Colonies cream\n* Inoculating loop silver\n* Flame orange\n* Contamination red\n* PPE teal\n* Incubator purple", "* Petri dish\n* Agar medium\n* Bacterial colonies\n* Inoculating loop\n* Bunsen burner or sterilizer\n* Pipette\n* Test tube\n* Incubator\n* Biosafety cabinet\n* Gloves\n* Lab coat\n* Waste container", "* Aseptic technique\n* Sterile media\n* Streak plate method\n* Spread plate concept\n* Pour plate concept\n* Colony isolation\n* Incubation conditions\n* Contamination sources\n* Biosafety levels overview\n* Disposal and disinfection\n* Lab records and labelling", "* Label plate\n* Sterilize loop\n* Collect sample safely\n* Streak first sector\n* Re-sterilize loop\n* Drag cells into new sectors\n* Incubate under appropriate conditions\n* Observe isolated colonies\n* Dispose safely", "* Clinical culture concept\n* Food and water testing\n* Research microbiology\n* Antibiotic susceptibility testing\n* Contamination troubleshooting\n* Biosafety and PPE\n* Never culture unknown hazardous samples outside appropriate lab settings", "Use a clean lab-bench scene centrally, with streak-plate sequence across the middle and biosafety rules along the bottom.", "* Do not encourage unsafe home culturing of unknown microbes\n* Distinguish sterile from clean\n* Incubation conditions depend on organism\n* Colony appearance alone usually cannot identify species\n* Show PPE and disposal correctly"),
]

SPECS += [
    # 05 Viruses and infectious disease
    ("05_Viruses_and_Infectious_Disease", "01_Virus_Structure_and_Life_Cycle.txt", "VIRUS STRUCTURE AND LIFE CYCLE", "VIRUS STRUCTURE AND LIFE CYCLE", "An illustrated guide to viral particles, genomes, capsids, envelopes, host-cell entry, replication, assembly and release", "* Capsid purple\n* Viral genome yellow\n* Envelope teal\n* Spike proteins red\n* Host cell blue\n* Replication complex green\n* New virions orange\n* Immune response pink", "* Capsid\n* Nucleic acid genome\n* Envelope\n* Spike glycoproteins\n* Matrix proteins\n* Viral enzymes\n* Host-cell receptor\n* Endosome\n* Replication site\n* Assembled virions", "* Virus versus cell comparison\n* DNA and RNA viruses\n* Enveloped and non-enveloped viruses\n* Host specificity\n* Attachment and entry\n* Uncoating\n* Genome replication\n* Protein synthesis\n* Assembly\n* Release by budding or lysis\n* Immune recognition", "* Virus attaches to receptor\n* Enters host cell\n* Uncoats genome\n* Hijacks host machinery\n* Replicates genome\n* Produces viral proteins\n* Assembles new particles\n* Releases virions\n* Infection spreads to nearby cells", "* Vaccines\n* Antiviral drugs\n* Diagnostic PCR and antigen tests\n* Infection control\n* Zoonotic spillover concept\n* Viral mutation and variants\n* Public-health prevention", "Use a large virion cutaway central, life cycle around it as a circular sequence, and host-cell entry as an enlarged inset.", "* Viruses are not cells\n* Viruses do not reproduce independently without host cells\n* Do not show all viruses with envelopes\n* Avoid implying antibiotics treat viral infections\n* Keep receptor specificity accurate"),
    ("05_Viruses_and_Infectious_Disease", "02_HIV_and_AIDS.txt", "HIV AND AIDS", "HIV AND AIDS", "An illustrated guide to HIV structure, CD4 cell infection, reverse transcription, immune decline, treatment and prevention", "* HIV envelope teal\n* gp120 spikes red\n* RNA genome yellow\n* Reverse transcriptase purple\n* CD4 T cell blue\n* Integrated provirus orange\n* Antiretroviral therapy green\n* Prevention gold", "* HIV envelope\n* gp120/gp41 proteins\n* Capsid\n* RNA genome\n* Reverse transcriptase\n* Integrase\n* Protease\n* CD4 receptor\n* Co-receptors CCR5/CXCR4\n* CD4 T cell\n* Proviral DNA", "* HIV as a retrovirus\n* CD4 T-cell targeting\n* Reverse transcription\n* Integration into host DNA\n* Viral assembly and budding\n* Difference between HIV infection and AIDS\n* Antiretroviral therapy targets\n* Viral load and CD4 count\n* Prevention methods\n* Stigma-free public-health language", "* HIV binds CD4 and co-receptor\n* Viral envelope fuses with cell membrane\n* RNA is reverse-transcribed into DNA\n* Viral DNA integrates into host genome\n* Host cell produces viral RNA and proteins\n* New virions assemble and bud\n* Protease maturation creates infectious particles", "* AIDS as advanced immune deficiency\n* Opportunistic infections\n* Testing and counselling\n* ART suppressing viral replication\n* PrEP, PEP, condoms, sterile needles and prevention of parent-to-child transmission\n* U=U concept stated carefully: sustained undetectable viral load prevents sexual transmission", "Use HIV virion and CD4 cell interaction centrally, life cycle around it, ART target points as precise callouts.", "* Use respectful non-stigmatizing language\n* Do not imply casual contact transmits HIV\n* Do not say HIV and AIDS are the same thing\n* Do not claim ART removes all integrated virus\n* Avoid cure claims"),
    ("05_Viruses_and_Infectious_Disease", "03_Influenza_Virus.txt", "INFLUENZA VIRUS", "INFLUENZA VIRUS", "An illustrated guide to flu virus structure, respiratory infection, antigenic drift, seasonal vaccines, symptoms and prevention", "* Viral envelope blue\n* Hemagglutinin red\n* Neuraminidase purple\n* RNA segments yellow\n* Respiratory epithelium teal\n* Mucus amber\n* Immune response pink\n* Vaccine green", "* Influenza virion\n* Hemagglutinin\n* Neuraminidase\n* Matrix protein\n* Segmented RNA genome\n* Respiratory epithelial cell\n* Cilia\n* Mucus\n* Infected airway\n* Immune cells", "* Influenza A and B overview\n* HA and NA functions\n* Segmented genome\n* Respiratory droplet spread\n* Airway infection\n* Antigenic drift\n* Antigenic shift concept\n* Seasonal vaccination\n* Antiviral timing concept\n* Complications and prevention", "* Virus enters respiratory tract\n* HA binds host receptors\n* Virus enters epithelial cell\n* Genome segments replicate\n* New virions assemble\n* NA helps release virions\n* Immune response causes many symptoms\n* Transmission occurs through respiratory particles", "* Seasonal flu\n* Pneumonia complications\n* High-risk groups\n* Vaccination\n* Hand hygiene, ventilation and staying home when sick\n* Difference between cold and flu\n* Medical care for severe symptoms", "Place influenza virion central with HA/NA enlarged. Use respiratory airway panel and antigenic drift diagram as side panels.", "* Do not confuse influenza with common cold\n* Do not imply flu vaccine causes influenza infection\n* Antigenic shift is most associated with influenza A\n* Avoid specific treatment instructions\n* Show segmented RNA genome"),
    ("05_Viruses_and_Infectious_Disease", "04_Coronavirus_and_COVID19.txt", "CORONAVIRUS AND COVID-19", "CORONAVIRUS AND COVID-19", "An illustrated guide to coronavirus structure, spike entry, respiratory infection, immune response, variants, vaccines and prevention", "* Spike protein red\n* Viral envelope teal\n* RNA genome yellow\n* Nucleocapsid purple\n* ACE2 receptor blue\n* Airway cells green\n* Immune response pink\n* Vaccine gold", "* Coronavirus virion\n* Spike proteins\n* Envelope\n* Membrane protein\n* Nucleocapsid\n* RNA genome\n* ACE2 receptor\n* Respiratory epithelial cell\n* Alveolus\n* Immune cells", "* Coronavirus family overview\n* SARS-CoV-2 structure\n* Spike-ACE2 binding\n* Respiratory and systemic effects overview\n* Replication of positive-sense RNA virus\n* Variants and mutations\n* Vaccines and immune memory\n* Testing methods\n* Prevention and ventilation\n* Long COVID as a medical research and care topic", "* Virus reaches airway\n* Spike binds receptor\n* Virus enters cell\n* RNA genome is released\n* Viral proteins and RNA are produced\n* New particles assemble\n* Virions exit cell\n* Immune response and inflammation develop\n* Transmission can occur through respiratory particles", "* COVID-19 symptoms and severity range\n* Severe disease risk factors\n* Vaccination and boosters as public-health tools\n* Testing and isolation guidance as locally variable\n* Ventilation and masks in high-risk settings\n* Long COVID\n* Medical evaluation for severe breathing difficulty or chest pain", "Use SARS-CoV-2 virion and airway-cell entry centrally, with testing/vaccine/prevention panels clearly separated.", "* Use up-to-date neutral wording without political framing\n* Do not claim all infections are mild or all are severe\n* Do not imply variants are intentionally created\n* Avoid giving location-specific public-health rules\n* Keep vaccine claims evidence-based"),
    ("05_Viruses_and_Infectious_Disease", "05_Bacteriophages.txt", "BACTERIOPHAGES", "BACTERIOPHAGES", "An illustrated guide to viruses that infect bacteria, phage structure, lytic cycle, lysogeny, bacterial evolution and phage therapy research", "* Phage head purple\n* Tail sheath teal\n* Tail fibres orange\n* DNA genome yellow\n* Bacterial cell green\n* Lytic cycle red\n* Lysogenic cycle blue\n* Prophage gold", "* Icosahedral head\n* DNA genome\n* Tail sheath\n* Baseplate\n* Tail fibres\n* Bacterial receptor\n* Bacterial cell wall\n* Injected genome\n* Prophage\n* Released phages", "* Phage anatomy\n* Host specificity\n* Lytic cycle\n* Lysogenic cycle\n* Prophage integration\n* Transduction\n* CRISPR bacterial defence\n* Phage ecology\n* Phage therapy research\n* Biotechnology applications", "* Phage attaches to bacterium\n* Genome is injected\n* Lytic path produces phage parts\n* Bacterium lyses and releases phages\n* Lysogenic path integrates prophage\n* Prophage may later enter lytic cycle\n* Genes can sometimes move between bacteria", "* Bacterial population control\n* Phage therapy research\n* Food safety applications\n* Molecular biology tools\n* Antibiotic-resistance context\n* Environmental abundance of phages", "Use a dramatic phage-on-bacterium central scene, with lytic and lysogenic cycles as two parallel pathways.", "* Bacteriophages infect bacteria, not human cells directly as their host\n* Do not imply all phages are lytic\n* Phage therapy is not a universal replacement for antibiotics\n* Show genome injection, not whole phage entering bacterial cell\n* Keep transduction concept accurate"),
    ("05_Viruses_and_Infectious_Disease", "06_Vaccines_and_Immunization.txt", "VACCINES AND IMMUNIZATION", "VACCINES AND IMMUNIZATION", "An illustrated guide to vaccine types, immune priming, antibodies, T cells, memory cells, boosters, herd protection and safety monitoring", "* Vaccine antigen teal\n* Antibodies gold\n* B cells blue\n* T cells purple\n* Memory cells green\n* Pathogen red\n* Booster orange\n* Community protection navy", "* Vaccine antigen\n* Antigen-presenting cell\n* Helper T cell\n* B cell\n* Plasma cell\n* Antibody\n* Cytotoxic T cell\n* Memory B cell\n* Memory T cell\n* Syringe icon\n* Community protection network", "* Vaccine types: live attenuated, inactivated, subunit, toxoid, viral vector and mRNA\n* Innate immune activation\n* Antigen presentation\n* Antibody production\n* T-cell responses\n* Immune memory\n* Boosters\n* Herd protection concept\n* Safety monitoring\n* Contraindication and medical advice note", "* Vaccine introduces antigen or antigen instructions\n* Immune system detects antigen\n* Antigen-presenting cells activate lymphocytes\n* B cells produce antibodies\n* T cells support and kill infected cells where relevant\n* Memory cells persist\n* Future exposure triggers faster response", "* Childhood immunization\n* Seasonal vaccines\n* Outbreak prevention\n* Protection of vulnerable people\n* Vaccine side effects versus serious adverse events\n* Public-health surveillance\n* Importance of clinician guidance", "Use immune priming sequence centrally, vaccine-type comparison left and community protection network right.", "* Do not claim vaccines provide instant or perfect protection\n* Do not imply vaccines treat active infections in general\n* Avoid dismissive language about concerns\n* Distinguish common mild side effects from rare serious events\n* Keep herd protection as population-level concept"),
    ("05_Viruses_and_Infectious_Disease", "07_Malaria_Parasite_Life_Cycle.txt", "MALARIA PARASITE LIFE CYCLE", "MALARIA PARASITE LIFE CYCLE", "An illustrated guide to Plasmodium infection, mosquito transmission, liver stage, blood stage, symptoms, diagnosis, treatment and prevention", "* Mosquito orange\n* Sporozoites yellow\n* Liver cells green\n* Red blood cells red\n* Merozoites purple\n* Gametocytes blue\n* Fever cycle pink\n* Prevention teal", "* Anopheles mosquito\n* Sporozoites\n* Liver cell\n* Schizont\n* Merozoites\n* Red blood cells\n* Ring stage\n* Trophozoite\n* Gametocytes\n* Mosquito gut\n* Salivary glands", "* Plasmodium species overview\n* Mosquito vector\n* Liver stage\n* Blood stage\n* Red-blood-cell rupture\n* Gametocytes\n* Fever cycles\n* Diagnosis by microscopy and rapid tests\n* Antimalarial treatment concept\n* Bed nets, vector control and prophylaxis", "* Infected mosquito bites human\n* Sporozoites enter bloodstream\n* Parasites infect liver cells\n* Merozoites enter blood\n* Red blood cells are infected and rupture\n* Some parasites become gametocytes\n* Mosquito ingests gametocytes\n* Parasite develops in mosquito and reaches salivary glands", "* Malaria symptoms\n* Severe malaria warning signs\n* Pregnancy and childhood risk\n* Travel medicine\n* Insecticide-treated bed nets\n* Mosquito control\n* Drug resistance concerns\n* Medical diagnosis and treatment urgency", "Use a human-mosquito circular life cycle as the main visual, with liver and red-cell stages enlarged.", "* Malaria is caused by Plasmodium parasites, not a virus or bacterium\n* Anopheles mosquitoes transmit malaria\n* Do not omit liver stage\n* Do not imply all mosquito bites transmit malaria\n* Avoid treatment recommendations beyond medical-care guidance"),
    ("05_Viruses_and_Infectious_Disease", "08_Tuberculosis.txt", "TUBERCULOSIS", "TUBERCULOSIS", "An illustrated guide to Mycobacterium tuberculosis, lung infection, granulomas, latent and active TB, transmission, diagnosis, treatment and prevention", "* TB bacteria red-pink\n* Lung tissue blue\n* Macrophages green\n* Granuloma gold\n* Airborne droplets cyan\n* Acid-fast stain magenta\n* Treatment panel teal\n* Prevention navy", "* Mycobacterium tuberculosis\n* Waxy cell wall\n* Lung alveolus\n* Macrophage\n* Granuloma\n* Caseous centre\n* Airway droplets\n* Chest X-ray panel\n* Sputum sample\n* Acid-fast bacilli", "* TB transmission\n* Inhaled airborne particles\n* Macrophage infection\n* Granuloma formation\n* Latent TB infection\n* Active TB disease\n* Pulmonary and extrapulmonary TB\n* Diagnosis: sputum tests, culture, molecular tests and imaging\n* Multi-drug treatment concept\n* BCG vaccine and prevention context", "* Infectious person releases airborne particles\n* Another person inhales droplets\n* Bacteria reach alveoli\n* Macrophages engulf bacteria\n* Granuloma may contain infection\n* Latent infection may persist\n* Reactivation can cause active disease\n* Treatment requires supervised multi-drug regimens", "* Cough lasting weeks\n* Fever, night sweats and weight loss\n* Drug-resistant TB\n* HIV and TB interaction\n* Contact tracing\n* Ventilation and respiratory protection\n* Importance of completing treatment under medical supervision", "Use a lung granuloma as the central image, with transmission pathway left and latent-versus-active comparison right.", "* TB is bacterial, not viral\n* Latent TB is not the same as active contagious TB\n* Do not imply all exposed people become ill\n* Treatment is long and must be medically supervised\n* Show acid-fast bacteria accurately"),
    ("05_Viruses_and_Infectious_Disease", "09_Zoonotic_Diseases_and_Spillover.txt", "ZOONOTIC DISEASES AND SPILLOVER", "ZOONOTIC DISEASES AND SPILLOVER", "An illustrated guide to pathogens moving between animals and humans, reservoirs, vectors, spillover risk, surveillance and One Health prevention", "* Reservoir animals brown\n* Humans blue\n* Vectors orange\n* Pathogens red\n* Environment green\n* Surveillance purple\n* Barriers teal\n* One Health gold", "* Reservoir host\n* Intermediate host\n* Vector\n* Human host\n* Pathogen particles\n* Habitat interface\n* Farm setting\n* Wildlife setting\n* Market setting\n* Surveillance network\n* Barrier interventions", "* Zoonosis definition\n* Reservoir hosts\n* Intermediate hosts\n* Vector-borne spread\n* Direct contact, foodborne and airborne routes\n* Spillover risk factors\n* Land use and climate links\n* One Health approach\n* Surveillance and early warning\n* Prevention at human-animal-environment interface", "* Pathogen circulates in reservoir\n* Human activities increase contact\n* Pathogen reaches intermediate host or vector\n* Exposure occurs\n* Some pathogens adapt to human infection\n* Limited or sustained transmission may occur\n* Surveillance detects clusters\n* Prevention reduces contact and spread", "* Rabies\n* Ebola virus disease concept\n* Avian influenza\n* Lyme disease\n* Nipah virus concept\n* Food safety\n* Wildlife conservation\n* Veterinary public health\n* Outbreak investigation", "Use a One Health triangle as the central composition linking humans, animals and environment with route arrows.", "* Do not blame animals simplistically\n* Spillover does not guarantee a pandemic\n* Avoid sensational imagery\n* Distinguish reservoir, vector and intermediate host\n* Keep prevention focused on systems and surveillance"),
    ("05_Viruses_and_Infectious_Disease", "10_Epidemiology_and_Outbreak_Control.txt", "EPIDEMIOLOGY AND OUTBREAK CONTROL", "EPIDEMIOLOGY AND OUTBREAK CONTROL", "An illustrated guide to transmission chains, R number, incidence, prevalence, contact tracing, vaccination, isolation and public-health response", "* Cases red\n* Susceptible people blue\n* Recovered people green\n* Transmission arrows orange\n* Vaccination gold\n* Contact tracing purple\n* Isolation teal\n* Public-health dashboard navy", "* Index case\n* Transmission chain\n* Cluster\n* Contact network\n* Epidemic curve\n* R number icon\n* Incidence graph\n* Prevalence panel\n* Vaccination shield\n* Testing station\n* Isolation symbol", "* Epidemiology basics\n* Incidence versus prevalence\n* R0 and effective R\n* Epidemic curves\n* Case definition\n* Testing and surveillance\n* Contact tracing\n* Isolation and quarantine distinction\n* Vaccination campaigns\n* Risk communication\n* Layered prevention", "* Case is detected\n* Public health defines case criteria\n* Contacts are identified\n* Testing and monitoring occur\n* Infectious people isolate\n* Exposed contacts may quarantine depending on guidance\n* Vaccination and prevention reduce transmission\n* Data update response strategy", "* Outbreak investigation\n* School and workplace outbreaks\n* Foodborne outbreaks\n* Respiratory disease spread\n* Vector-borne surveillance\n* Ethical communication\n* Data uncertainty and changing recommendations", "Use a dashboard-style central outbreak map and contact network, with epidemic curve and intervention layers as side panels.", "* R0 is not fixed for all settings\n* Incidence and prevalence are different\n* Isolation and quarantine are different concepts\n* Public-health guidance varies by disease and location\n* Avoid implying models are perfect predictions"),
]

SPECS += [
    # 06 Human disease and public health
    ("06_Human_Disease_and_Public_Health", "01_Diabetes_Mellitus.txt", "DIABETES MELLITUS", "DIABETES MELLITUS", "An illustrated guide to insulin, blood glucose regulation, type 1 diabetes, type 2 diabetes, complications, monitoring and prevention", "* Glucose gold\n* Insulin blue\n* Pancreas yellow\n* Beta cells green\n* Blood vessels red\n* Muscle cells purple\n* Fat cells orange\n* Complications red-pink\n* Healthy habits teal", "* Pancreas\n* Islets of Langerhans\n* Beta cells\n* Insulin\n* Glucagon\n* Blood glucose\n* Glucose transporter\n* Muscle cell\n* Liver cell\n* Adipose tissue\n* Blood vessel\n* Kidney, eye, nerve and heart icons", "* Normal glucose regulation\n* Type 1 diabetes autoimmune beta-cell loss\n* Type 2 diabetes insulin resistance\n* Gestational diabetes overview\n* Hyperglycaemia and hypoglycaemia\n* HbA1c\n* Glucose monitoring\n* Lifestyle prevention for type 2 risk\n* Medications and insulin as clinician-guided treatment concepts\n* Complications and screening", "* Food raises blood glucose\n* Pancreas senses glucose\n* Insulin release helps cells take up glucose\n* Liver stores glucose as glycogen\n* In diabetes, insulin lack or resistance disrupts regulation\n* Long-term high glucose damages vessels and nerves", "* Heart disease\n* Kidney disease\n* Retinopathy\n* Neuropathy\n* Foot ulcers\n* Diabetic ketoacidosis warning concept\n* Severe hypoglycaemia warning signs\n* Medical care and regular monitoring", "Use pancreas-glucose-cell pathway centrally, type 1/type 2 comparison left and complication prevention panels right.", "* Do not imply diabetes is caused only by sugar intake\n* Distinguish type 1 and type 2 mechanisms\n* Avoid treatment dosing advice\n* Show hypoglycaemia as possible during treatment\n* Use non-stigmatizing language"),
    ("06_Human_Disease_and_Public_Health", "02_Cancer_Overview.txt", "CANCER OVERVIEW", "CANCER OVERVIEW", "An illustrated guide to tumour formation, risk factors, screening, diagnosis, staging, treatment types and prevention", "* Normal cells blue\n* Cancer cells red-purple\n* DNA damage yellow\n* Blood vessels red-blue\n* Immune cells green\n* Screening teal\n* Treatment gold\n* Prevention navy", "* Normal tissue\n* Abnormal cells\n* Benign tumour\n* Malignant tumour\n* Invasion\n* Blood vessel growth\n* Lymph node\n* Metastatic site\n* Biopsy needle\n* Pathology slide\n* Imaging panel", "* What cancer is\n* Benign versus malignant\n* DNA mutations and cell-cycle control\n* Risk factors\n* Screening\n* Biopsy and pathology\n* Staging and grading\n* Treatment categories\n* Survivorship\n* Prevention and early detection", "* Normal cell accumulates mutations\n* Growth-control pathways fail\n* Cell clone expands\n* Tumour forms\n* Some cells invade tissue\n* Diagnosis uses imaging and biopsy\n* Stage guides treatment planning\n* Follow-up monitors response", "* Surgery\n* Radiation therapy\n* Chemotherapy\n* Targeted therapy\n* Immunotherapy\n* Hormone therapy\n* Palliative care\n* Warning signs such as unexplained weight loss, persistent lumps, abnormal bleeding and non-healing sores", "Use tumour progression centrally, with screening/diagnosis on left and treatment/prevention on right.", "* Cancer is not one single disease\n* Not all tumours are malignant\n* Avoid guaranteed cure claims\n* Screening recommendations vary by age, risk and country\n* Use compassionate, non-blaming language"),
    ("06_Human_Disease_and_Public_Health", "03_Hypertension_and_Blood_Pressure.txt", "HYPERTENSION AND BLOOD PRESSURE", "HYPERTENSION AND BLOOD PRESSURE", "An illustrated guide to arteries, systolic and diastolic pressure, vascular resistance, organ damage, measurement and prevention", "* Arteries red\n* Veins blue\n* Pressure wave gold\n* Heart crimson\n* Kidney purple\n* Brain teal\n* Blood-pressure cuff navy\n* Lifestyle panel green", "* Heart\n* Aorta\n* Artery wall\n* Smooth muscle\n* Endothelium\n* Blood-pressure cuff\n* Systolic pressure\n* Diastolic pressure\n* Kidney\n* Brain\n* Eye\n* Blood vessel damage", "* Blood pressure definition\n* Systolic versus diastolic\n* Cardiac output and vascular resistance\n* Arterial stiffness\n* Kidney salt-water regulation\n* RAAS overview\n* Proper measurement technique\n* Silent nature of hypertension\n* Organ damage\n* Prevention and clinician-guided treatment", "* Heart ejects blood during systole\n* Arteries stretch under pressure\n* Pressure falls during diastole\n* Narrower or stiffer arteries raise resistance\n* Kidneys influence fluid volume\n* Persistent high pressure damages vessels and organs", "* Stroke\n* Heart attack\n* Heart failure\n* Kidney disease\n* Retinopathy\n* Aneurysm risk\n* Lifestyle measures such as sodium reduction, exercise, healthy diet and limiting harmful alcohol\n* Medication categories without dosing advice", "Use artery pressure cross-section and cuff measurement centrally, with organ-damage map along the bottom.", "* Do not call hypertension harmless because it may be silent\n* Avoid specific medication advice\n* Use accurate systolic/diastolic explanation\n* Do not imply stress alone causes all hypertension\n* Diagnosis requires repeated appropriate measurements"),
    ("06_Human_Disease_and_Public_Health", "04_Asthma_and_Allergy.txt", "ASTHMA AND ALLERGY", "ASTHMA AND ALLERGY", "An illustrated guide to airway inflammation, bronchoconstriction, allergens, IgE, mast cells, triggers, inhalers and emergency warning signs", "* Normal airway blue\n* Inflamed airway red-pink\n* Mucus amber\n* Smooth muscle purple\n* Allergens orange\n* IgE gold\n* Mast cells green\n* Rescue care teal", "* Normal bronchiole\n* Asthmatic bronchiole\n* Airway smooth muscle\n* Mucus plug\n* Inflamed lining\n* Allergen particle\n* IgE antibody\n* Mast cell\n* Histamine granules\n* Inhaler\n* Peak flow meter", "* Asthma basics\n* Airway inflammation\n* Bronchoconstriction\n* Mucus production\n* Allergic sensitization\n* IgE and mast cells\n* Triggers such as pollen, dust mites, smoke, exercise, cold air and infections\n* Controller versus reliever inhaler concept\n* Action plans\n* Anaphylaxis distinction", "* Allergen or trigger reaches airway\n* Immune and airway cells activate\n* Smooth muscle tightens\n* Mucus increases\n* Airway narrows\n* Breathing becomes difficult\n* Reliever medication can relax airway muscle\n* Long-term control reduces inflammation", "* Wheezing\n* Shortness of breath\n* Chest tightness\n* Cough\n* Severe attack warning signs\n* Allergy testing concept\n* Avoidance strategies\n* Emergency care for severe breathing difficulty or anaphylaxis", "Use normal-versus-asthmatic airway comparison centrally, immune allergy pathway left and inhaler/action-plan panel right.", "* Do not show asthma as only psychological\n* Do not recommend medication doses\n* Distinguish asthma attack from anaphylaxis\n* Not all asthma is allergic\n* Emergency symptoms require urgent care"),
    ("06_Human_Disease_and_Public_Health", "05_Stroke_and_Brain_Attack.txt", "STROKE: BRAIN ATTACK", "STROKE: BRAIN ATTACK", "An illustrated guide to ischemic and hemorrhagic stroke, brain blood supply, FAST warning signs, emergency care and rehabilitation", "* Healthy artery red\n* Blocked artery dark red\n* Bleeding vessel purple-red\n* Brain tissue blue\n* Ischemic zone grey\n* FAST warning panel orange\n* Emergency care teal\n* Rehabilitation green", "* Brain\n* Circle of Willis\n* Cerebral artery\n* Blood clot\n* Ischemic core\n* Penumbra\n* Hemorrhage\n* Neuron injury\n* Face droop icon\n* Arm weakness icon\n* Speech difficulty icon\n* Emergency clock", "* Ischemic stroke\n* Hemorrhagic stroke\n* Transient ischemic attack\n* Brain oxygen and glucose needs\n* FAST warning signs\n* Other sudden symptoms\n* Emergency imaging\n* Clot treatment concepts\n* Blood-pressure and bleeding management concepts\n* Rehabilitation and prevention", "* Blood vessel blocks or ruptures\n* Brain region loses normal blood supply\n* Neurons lack oxygen and glucose\n* Symptoms appear suddenly\n* Emergency services are contacted\n* Imaging identifies stroke type\n* Time-sensitive treatment decisions are made\n* Rehabilitation supports recovery", "* FAST: face drooping, arm weakness, speech difficulty, time to call emergency services\n* Sudden confusion\n* Vision changes\n* Severe headache\n* Dizziness or loss of balance\n* Numbness or weakness on one side\n* Risk reduction: blood pressure, diabetes, smoking, atrial fibrillation and cholesterol management", "Use a split ischemic-versus-hemorrhagic brain diagram centrally, FAST signs as a high-contrast emergency strip.", "* Do not suggest waiting to see if stroke symptoms pass\n* Distinguish ischemic and hemorrhagic stroke\n* Do not recommend aspirin before stroke type is known\n* Use urgent emergency language\n* Keep anatomy and vascular territories plausible"),
    ("06_Human_Disease_and_Public_Health", "06_Heart_Attack_Myocardial_Infarction.txt", "HEART ATTACK: MYOCARDIAL INFARCTION", "HEART ATTACK: MYOCARDIAL INFARCTION", "An illustrated guide to coronary artery blockage, plaque rupture, heart-muscle injury, symptoms, emergency response and prevention", "* Coronary arteries red\n* Plaque yellow\n* Blood clot dark red\n* Ischemic myocardium grey\n* Oxygen red\n* ECG green\n* Emergency warning orange\n* Prevention teal", "* Heart\n* Coronary artery\n* Atherosclerotic plaque\n* Plaque rupture\n* Thrombus\n* Blocked artery\n* Ischemic myocardium\n* Damaged heart muscle\n* ECG trace\n* Cardiac enzyme blood test icon", "* Coronary artery disease\n* Plaque buildup\n* Plaque rupture and clot\n* Reduced oxygen delivery\n* Myocardial injury\n* Symptoms and atypical presentations\n* ECG and blood tests\n* Emergency reperfusion concepts\n* Cardiac rehabilitation\n* Risk-factor prevention", "* Plaque narrows coronary artery\n* Plaque ruptures\n* Platelets form clot\n* Blood flow drops or stops\n* Heart muscle lacks oxygen\n* Cells become injured\n* Emergency treatment restores flow when possible\n* Recovery and prevention reduce future risk", "* Chest pain or pressure\n* Shortness of breath\n* Sweating\n* Nausea\n* Pain radiating to arm, jaw or back\n* Symptoms may differ by person\n* Call emergency services for suspected heart attack\n* Risk reduction through clinician-guided care", "Use coronary artery blockage as the central hero with heart-muscle injury and ECG panels alongside.", "* Do not imply all heart attacks feel the same\n* Do not provide self-treatment instructions\n* Distinguish cardiac arrest from heart attack\n* Emergency evaluation is required\n* Show coronary arteries supplying myocardium accurately"),
    ("06_Human_Disease_and_Public_Health", "07_Alzheimers_Disease_and_Dementia.txt", "ALZHEIMER'S DISEASE AND DEMENTIA", "ALZHEIMER'S DISEASE AND DEMENTIA", "An illustrated guide to memory networks, amyloid plaques, tau tangles, neurodegeneration, symptoms, diagnosis, care and brain health", "* Brain regions blue\n* Hippocampus gold\n* Amyloid plaques red-orange\n* Tau tangles purple\n* Neurons green\n* Synapses yellow\n* Care support teal\n* Healthy habits navy", "* Brain\n* Hippocampus\n* Cerebral cortex\n* Neuron\n* Synapse\n* Amyloid plaque\n* Tau tangle\n* Atrophied brain region\n* Memory pathway\n* Caregiver support icon", "* Dementia definition\n* Alzheimer's disease as one cause\n* Memory and cognition networks\n* Amyloid and tau pathology concepts\n* Synapse loss\n* Neurodegeneration\n* Symptoms progression\n* Diagnosis and cognitive testing\n* Care planning\n* Risk reduction and brain health", "* Protein changes accumulate\n* Synapses become impaired\n* Neurons are damaged\n* Brain networks lose efficiency\n* Memory and thinking symptoms appear\n* Functional independence may decline\n* Diagnosis uses history, exams and tests\n* Supportive care and treatments are planned", "* Memory loss affecting daily life\n* Confusion\n* Language difficulty\n* Behaviour changes\n* Safety concerns\n* Caregiver support\n* Treatable causes of cognitive symptoms\n* Medical evaluation for new or worsening confusion", "Use hippocampus/cortex network centrally, microscopic plaque/tangle panel lower left and care/diagnosis panel lower right.", "* Dementia is a syndrome, not normal ageing\n* Alzheimer's is not the only cause of dementia\n* Do not claim plaques alone fully explain all symptoms\n* Avoid cure claims\n* Use respectful person-centred language"),
    ("06_Human_Disease_and_Public_Health", "08_Autoimmune_Diseases.txt", "AUTOIMMUNE DISEASES", "AUTOIMMUNE DISEASES", "An illustrated guide to immune tolerance, autoantibodies, T-cell attack, inflammation, organ-specific and systemic autoimmune conditions", "* Self cells blue\n* Immune cells purple\n* Autoantibodies gold\n* Inflammation red-pink\n* Tolerance green\n* Target organs teal\n* Treatment concept orange\n* Flares violet", "* Antigen-presenting cell\n* T cell\n* B cell\n* Autoantibody\n* Self antigen\n* Inflamed tissue\n* Joint\n* Thyroid\n* Pancreatic beta cell\n* Myelin sheath\n* Skin\n* Kidney", "* Immune tolerance\n* Central and peripheral tolerance concepts\n* Autoantibodies\n* Autoreactive T cells\n* Inflammation\n* Organ-specific autoimmunity\n* Systemic autoimmunity\n* Flares and remission\n* Diagnosis using symptoms, exams and lab markers\n* Treatment categories as immune modulation", "* Genetic and environmental factors contribute\n* Immune tolerance fails\n* Autoreactive cells activate\n* Autoantibodies or T cells target tissues\n* Inflammation damages organs\n* Symptoms fluctuate\n* Diagnosis combines clinical and laboratory evidence\n* Treatment aims to control inflammation and preserve function", "* Type 1 diabetes\n* Rheumatoid arthritis\n* Lupus\n* Multiple sclerosis\n* Hashimoto thyroiditis\n* Graves disease\n* Celiac disease\n* Warning signs vary widely by organ system", "Use immune tolerance failure as the central concept, with organ-specific examples around a body silhouette.", "* Do not imply autoimmune disease is simply a weak immune system\n* Avoid claiming diet or lifestyle alone cures autoimmune disease\n* Distinguish allergy, immunodeficiency and autoimmunity\n* Use neutral language about chronic illness\n* No medication advice"),
    ("06_Human_Disease_and_Public_Health", "09_Nutrition_Metabolism_and_Deficiency.txt", "NUTRITION, METABOLISM AND DEFICIENCY", "NUTRITION, METABOLISM AND DEFICIENCY", "An illustrated guide to macronutrients, micronutrients, digestion, energy balance, metabolism, deficiency diseases and healthy eating patterns", "* Carbohydrates gold\n* Proteins purple\n* Fats orange\n* Vitamins green\n* Minerals blue\n* Metabolism red\n* Deficiency warning pink\n* Balanced plate teal", "* Digestive tract\n* Glucose\n* Amino acids\n* Fatty acids\n* Vitamins\n* Minerals\n* Liver\n* Muscle\n* Adipose tissue\n* Mitochondrion\n* Balanced plate\n* Deficiency icons", "* Macronutrients\n* Micronutrients\n* Digestion and absorption\n* Energy balance\n* Basal metabolic rate concept\n* Glycogen and fat storage\n* Protein turnover\n* Vitamins A, B, C, D, E and K overview\n* Minerals iron, calcium, iodine, zinc and sodium/potassium\n* Deficiency and excess risks", "* Food is digested\n* Nutrients are absorbed\n* Blood carries nutrients to liver and tissues\n* Cells use nutrients for ATP, building blocks and regulation\n* Excess energy may be stored\n* Deficiency impairs specific biological functions\n* Balanced patterns support health over time", "* Iron deficiency anaemia\n* Vitamin D deficiency\n* Iodine deficiency\n* Scurvy\n* Rickets\n* Overnutrition and metabolic disease\n* Food insecurity\n* Eating disorders requiring professional care", "Use a balanced plate connected to digestive/metabolic organs centrally, with macro/micro panels and deficiency examples around it.", "* Avoid fad diet claims\n* Do not classify all fats or carbohydrates as bad\n* Deficiency and excess can both be harmful\n* Nutrition needs vary by age, pregnancy, disease and activity\n* Avoid personalized medical diet advice"),
    ("06_Human_Disease_and_Public_Health", "10_Mental_Health_Neurobiology.txt", "MENTAL HEALTH AND NEUROBIOLOGY", "MENTAL HEALTH AND NEUROBIOLOGY", "An illustrated guide to brain networks, neurotransmitters, stress biology, depression, anxiety, treatment support and crisis awareness", "* Brain networks blue\n* Serotonin teal\n* Dopamine purple\n* Norepinephrine orange\n* Stress hormones red\n* Support systems green\n* Therapy gold\n* Crisis warning magenta", "* Prefrontal cortex\n* Amygdala\n* Hippocampus\n* Reward pathway\n* Synapse\n* Neurotransmitters\n* HPA axis\n* Cortisol\n* Sleep-wake rhythm\n* Social support network\n* Care pathway", "* Mental health as brain-body-social interaction\n* Neurotransmitter signalling\n* Stress response and HPA axis\n* Emotion regulation networks\n* Depression overview\n* Anxiety overview\n* Trauma and stress concepts\n* Sleep, exercise and social connection\n* Psychotherapy and medication as treatment categories\n* Crisis warning signs and help-seeking", "* Stressor is perceived\n* Brain networks evaluate threat and context\n* HPA axis releases stress hormones\n* Body prepares response\n* Chronic stress can affect sleep, mood and attention\n* Support, therapy and medical care can help recovery\n* Crisis symptoms require urgent support", "* Depression symptoms\n* Anxiety symptoms\n* Panic attacks\n* Substance use interaction\n* Self-harm warning signs\n* Suicidal thoughts as emergency support need\n* Stigma reduction\n* Professional evaluation and crisis resources", "Use interconnected brain network and synapse as central visual, with stress axis left and support/treatment pathway right.", "* Do not reduce mental illness to a simple chemical imbalance only\n* Use non-stigmatizing language\n* Do not imply willpower alone fixes mental illness\n* Avoid treatment recommendations or medication claims\n* Include urgent help-seeking for self-harm or suicidal thoughts"),
]


def main():
    for category, filename, about, title, subtitle, colors, central, panels, process, conditions, composition, accuracy in SPECS:
        folder = BASE / category
        folder.mkdir(parents=True, exist_ok=True)
        text = build_prompt(
            {
                "about": about,
                "title": title,
                "subtitle": subtitle,
                "colors": colors,
                "central": central,
                "panels": panels,
                "process": process,
                "conditions": conditions,
                "composition": composition,
                "accuracy": accuracy,
            }
        )
        (folder / filename).write_text(text, encoding="utf-8")

    print(f"Created {len(SPECS)} phase 2 prompt files in {BASE}")
    for category in sorted({row[0] for row in SPECS}):
        print(f"{category}: {len(list((BASE / category).glob('*.txt')))} text files")


if __name__ == "__main__":
    main()
