import {afterEach,describe,it,expect,vi} from 'vitest';
import {downloadBytes} from './downloadBytes';
import {modelLoads,startModelLoad} from './modelLoadStore';
afterEach(()=>{vi.unstubAllGlobals();vi.useRealTimers();modelLoads.getSnapshot().forEach(load=>modelLoads.dismiss(load.id));});
function response(headers:Record<string,string>={}){return new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array(20));controller.enqueue(new Uint8Array(30));controller.enqueue(new Uint8Array(50));controller.close();}}),{headers});}
describe('model download progress',()=>{
 it('reports measured intermediate percentages and returns every byte',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>response({'content-length':'100'})));const progress:number[]=[];const {bytes}=await downloadBytes('/model.bin',value=>{if(value.percent!==undefined)progress.push(value.percent);});expect(progress).toEqual([0,20,50,99,100]);expect(bytes.byteLength).toBe(100);});
 it('does not invent a percentage when size is unknown or compressed',async()=>{for(const headers of [{},{'content-length':'10','content-encoding':'gzip'}] as Array<Record<string,string>>){vi.stubGlobal('fetch',vi.fn(async()=>response(headers)));const updates:Array<number|undefined>=[];await downloadBytes('/model.bin',p=>updates.push(p.percent));expect(updates.slice(0,-1).every(p=>p===undefined)).toBe(true);expect(updates.at(-1)).toBe(100);}});
 it('rejects a missing model rather than treating an error page as weights',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('missing',{status:404})));await expect(downloadBytes('/weights.bin',()=>{})).rejects.toThrow('404');});
 it('propagates interrupted streams instead of reporting completion',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(new ReadableStream({pull(controller){controller.error(new Error('Connection lost'));}}))));const events:unknown[]=[];await expect(downloadBytes('/weights.bin',p=>events.push(p.percent))).rejects.toThrow('Connection lost');expect(events).not.toContain(100);});
 it('keeps initialization separate from a finished model and cleans up',()=>{vi.useFakeTimers();const task=startModelLoad('Hands');task.progress({asset:'hand.task',loaded:10,total:20,percent:50});expect(modelLoads.getSnapshot()[0].progress?.percent).toBe(50);task.initializing();expect(modelLoads.getSnapshot()[0].phase).toBe('initializing');task.finish();expect(modelLoads.getSnapshot()[0].phase).toBe('ready');vi.advanceTimersByTime(1500);expect(modelLoads.getSnapshot()).toHaveLength(0);});
 it('supports simultaneous loads and dismisses failed or cancelled sessions',()=>{const a=startModelLoad('Hands'),b=startModelLoad('Ruhi');a.fail(new Error('Offline'));expect(modelLoads.getSnapshot()[0]).toMatchObject({phase:'error',error:'Offline'});b.cancel();expect(modelLoads.getSnapshot()).toHaveLength(1);modelLoads.dismiss(a.id);expect(modelLoads.getSnapshot()).toHaveLength(0);});
});
