import { Check, Download, RotateCcw, X } from "lucide-react";
import { useMemo, useState, type PointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import { chiSquareAnalysis, chiSquareCdf, chiSquareDensity, chiSquareGoodnessOfFit, chiSquareQuantile } from "./chiSquareLessonModel";
import "./ChiSquareDistributionLesson530.css";

const alphaOptions = [0.1, 0.05, 0.025, 0.01, 0.001];

export default function ChiSquareDistributionLesson530({ resetToken, onInteraction }: LessonAdapterProps) {
  return <ChiSquareActivity key={resetToken} onInteraction={onInteraction} />;
}

function ChiSquareActivity({ onInteraction }: Pick<LessonAdapterProps, "onInteraction">) {
  const [df, setDf] = useState(6), [alpha, setAlpha] = useState(0.05), [view, setView] = useState<"pdf" | "cdf">("pdf");
  const [observed, setObserved] = useState([21, 15, 18, 26, 22, 18]);
  const [answers, setAnswers] = useState([1, 1, 2]), [checked, setChecked] = useState([true, true, true]);
  const result = useMemo(() => chiSquareAnalysis(df, alpha), [alpha, df]);
  const expectedValue = observed.reduce((sum, value) => sum + value, 0) / observed.length;
  const fit = useMemo(() => chiSquareGoodnessOfFit(observed, observed.map(() => expectedValue)), [expectedValue, observed]);
  const domainMax = Math.max(30, result.critical * 1.8), samples = Array.from({ length: 151 }, (_, index) => { const x = domainMax * index / 150; return { x, pdf: chiSquareDensity(x, df), cdf: chiSquareCdf(x, df) }; });
  const maxPdf = Math.max(...samples.map((point) => point.pdf), 0.001), px = (value: number) => 5 + value / domainMax * 90, py = (value: number) => 88 - value * 70;
  const line = samples.map((point) => `${px(point.x)},${py(view === "pdf" ? point.pdf / maxPdf : point.cdf)}`).join(" ");
  const fromPointer = (event: PointerEvent<SVGSVGElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return Math.max(0.01, ((event.clientX - rect.left) / rect.width - 0.05) / 0.9 * domainMax); };
  const drag = (event: PointerEvent<SVGSVGElement>) => { setAlpha(Math.max(0.001, Math.min(0.25, 1 - chiSquareCdf(fromPointer(event), df)))); onInteraction(); };
  const reset = () => { setDf(6); setAlpha(0.05); setView("pdf"); setObserved([21, 15, 18, 26, 22, 18]); setAnswers([1, 1, 2]); setChecked([true, true, true]); onInteraction(); };
  const exportTable = () => { const rows = ["df," + alphaOptions.join(","), ...Array.from({ length: 5 }, (_, index) => { const rowDf = Math.max(1, df - 2 + index); return [rowDf, ...alphaOptions.map((value) => chiSquareQuantile(1-value,rowDf).toFixed(3))].join(","); })]; const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "chi-square-critical-values.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const tableDfs = Array.from({ length: 5 }, (_, index) => Math.max(1, df - 2 + index));
  const questions = [{ text: "If X is chi-square with df=6, what is P(X>12.592)?", options: [0.1,0.05,0.025,0.01], correct: 1 }, { text: "For chi-square with df=8, what are E[X] and Var(X)?", options: ["8, 8","8, 16","16, 8","16, 16"], correct: 1 }, { text: "The chi-square distribution is defined for:", options: ["All real numbers","x<0","x>=0","0<x<1"], correct: 2 }];

  return <div className="cs530" data-testid="probability-mockup-0493" data-target-family="probability-and-distributions">
    <header className="cs530-hero"><span>DATA AND PROBABILITY &nbsp; PROBABILITY AND DISTRIBUTIONS</span><h2>Chi-Square Distribution</h2><p>Support categorical data analysis and variance inference.</p><button type="button" onClick={reset}><RotateCcw size={14} />Reset</button></header>
    <nav><b>Interaction + visualization</b><span>Explain</span><span>Examples</span><span>Formulas</span><span>Know more</span></nav>
    <section className="cs530-overview"><article><h3>Objective</h3><p>Understand the Chi-Square Distribution, explore how degrees of freedom shape its curve, use critical values from the table, and interpret goodness-of-fit results.</p></article><article><p>Notation <b>X ~ chi-square(df)</b></p><p>Support <b>x &gt;= 0</b></p><p>Mean <b>{result.mean}</b></p><p>Variance <b>{result.variance}</b></p><p>Skewness <b>{result.skewness.toFixed(3)}</b></p></article><article><h3>Key insight</h3><p>As degrees of freedom increase, the distribution becomes more symmetric and approaches a normal distribution.</p></article></section>
    <section className="cs530-lab"><h3>Interactive Lab</h3><h4>Explore the Chi-Square Distribution</h4><div className="cs530-controls"><label>Degrees of freedom (k)<input type="range" min="1" max="30" value={df} onChange={(event) => { setDf(Number(event.target.value)); onInteraction(); }} /><output>{df}</output></label><label>Right-tail significance level (alpha)<input type="range" min=".001" max=".2" step=".001" value={alpha} onChange={(event) => { setAlpha(Number(event.target.value)); onInteraction(); }} /><output>{alpha.toFixed(3)}</output></label><fieldset><legend>View</legend><button type="button" className={view === "pdf" ? "active" : ""} onClick={() => setView("pdf")}>PDF</button><button type="button" className={view === "cdf" ? "active" : ""} onClick={() => setView("cdf")}>CDF</button></fieldset></div>
      <div className="cs530-graph"><article><h3>{view === "pdf" ? "Probability density function" : "Cumulative distribution function"} (df={df})</h3><svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); drag(event); }} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) drag(event); }}><line className="axis" x1="3" y1="88" x2="97" y2="88" />{view === "pdf" && samples.filter((point) => point.x >= result.critical).map((point) => <line className="tail" key={point.x} x1={px(point.x)} y1="88" x2={px(point.x)} y2={py(point.pdf/maxPdf)} />)}<polyline points={line} /><line className="critical" x1={px(result.critical)} y1="18" x2={px(result.critical)} y2="90" /><circle cx={px(result.critical)} cy="88" r="1.8" /></svg><p>Critical value: chi-square = {result.critical.toFixed(3)}</p></article><aside><h3>Distribution summary</h3><p>Degrees of freedom <b>{df}</b></p><p>Mean <b>{result.mean}</b></p><p>Variance <b>{result.variance}</b></p><p>Std. deviation <b>{result.std.toFixed(3)}</b></p><p>Mode <b>{result.mode}</b></p><p>Skewness <b>{result.skewness.toFixed(3)}</b></p><h3>Interactive tools</h3><p>Drag the purple handle to change the critical value. The shaded area equals P(X&gt;c).</p><button type="button" onClick={() => setAlpha(0.05)}>Reset handle</button></aside></div>
      <section className="cs530-table"><header><h3>Chi-Square Table (Right-tail critical values)</h3><button type="button" onClick={exportTable}><Download size={13} />Export table</button></header><table><thead><tr><th>df</th>{alphaOptions.map((value) => <th key={value}>alpha={value}</th>)}</tr></thead><tbody>{tableDfs.map((rowDf) => <tr key={rowDf} className={rowDf === df ? "selected" : ""}><th>{rowDf}</th>{alphaOptions.map((value) => <td key={value}><button type="button" className={rowDf===df&&value===alpha?"active":""} onClick={() => { setDf(rowDf); setAlpha(value); onInteraction(); }}>{chiSquareQuantile(1-value,rowDf).toFixed(3)}</button></td>)}</tr>)}</tbody></table><p>Selected: chi-square({alpha.toFixed(3)},{df}) = {result.critical.toFixed(3)}</p></section>
      <section className="cs530-fit"><h3>Apply Chi-Square Test for Goodness of Fit</h3><p>A die is rolled {fit.totalObserved} times. Test whether outcomes follow a uniform distribution.</p><div><article><h3>Observed frequencies</h3><table><thead><tr><th>Face</th><th>Observed</th><th>Expected</th><th>Contribution</th></tr></thead><tbody>{observed.map((value,index) => <tr key={index}><td>{index+1}</td><td><input aria-label={`Observed face ${index+1}`} type="number" min="0" value={value} onChange={(event) => { const next=[...observed]; next[index]=Math.max(0,Number(event.target.value)); setObserved(next); onInteraction(); }} /></td><td>{expectedValue.toFixed(2)}</td><td>{fit.contributions[index].toFixed(4)}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th>{fit.totalObserved}</th><th>{fit.totalExpected.toFixed(0)}</th><th>{fit.statistic.toFixed(3)}</th></tr></tfoot></table></article><article><h3>Test results</h3><p>Test statistic <b>{fit.statistic.toFixed(3)}</b></p><p>Degrees of freedom <b>{fit.df}</b></p><p>Critical value <b>{chiSquareQuantile(.95,fit.df).toFixed(3)}</b></p><p>p-value <b>{fit.pValue.toFixed(3)}</b></p><strong><Check size={15} />{fit.pValue>.05?"Fail to reject H0: consistent with a uniform distribution.":"Reject H0: evidence against a uniform distribution."}</strong></article></div></section>
    </section>
    <section className="cs530-insights"><article><h3>What it measures</h3><p>Chi-square measures discrepancy between observed and expected frequencies: sum (O-E)^2/E.</p></article><article><h3>Common misconception</h3><p>Chi-square cannot be negative because every contribution is nonnegative.</p></article><article><h3>Assumptions &amp; cautions</h3><p>Observations are independent, expected counts are sufficiently large, and categories are exclusive.</p></article><article><h3>When not to use</h3><p>Avoid it when expected counts are too small or observations are not categorical.</p></article></section>
    <section className="cs530-quiz"><h3>Check your understanding</h3>{questions.map((question,index) => <article key={question.text}><div><b>{index+1}. {question.text}</b>{question.options.map((option,optionIndex) => <label key={String(option)} className={answers[index]===optionIndex?"selected":""}><input type="radio" checked={answers[index]===optionIndex} onChange={() => { const next=[...answers]; next[index]=optionIndex; setAnswers(next); const nextChecked=[...checked]; nextChecked[index]=false; setChecked(nextChecked); onInteraction(); }} />{String.fromCharCode(65+optionIndex)}. {option}</label>)}</div><aside className={checked[index]&&answers[index]===question.correct?"correct":"incorrect"}>{checked[index]&&answers[index]===question.correct?<Check size={15}/>:<X size={15}/>} {checked[index]?answers[index]===question.correct?"Correct!":"Try again":"Choose an answer"}<button type="button" onClick={() => { const next=[...checked]; next[index]=true; setChecked(next); }}>Check</button></aside></article>)}</section>
    <footer><button type="button" onClick={reset}><RotateCcw size={14} />Reset lesson</button><span>Previous: Student t Distribution &nbsp; Next: F Distribution</span></footer>
  </div>;
}
