import { ArrowLeft, ArrowRight, Check, Eye, Hand, Languages, Lightbulb, Minus, RotateCcw, Share2, Target, TriangleAlert, Plus } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./CosineGraphTargetLesson262.css";

type Parameters = { a:number; b:number; c:number; d:number };
type Choice = "a"|"b"|"c"|"d";
const DEFAULTS:Parameters={a:1,b:1,c:0,d:0};
const TAU=Math.PI*2;

export default function CosineGraphTargetLesson262({resetToken,onInteraction}:LessonAdapterProps){
  const[theta,setTheta]=useState(Math.PI/3),[parameters,setParameters]=useState<Parameters>(DEFAULTS),[choice,setChoice]=useState<Choice>("c"),[result,setResult]=useState<"idle"|"correct"|"incorrect">("correct");
  const model=useMemo(()=>cosineModel(parameters),[parameters]),current=model.value(theta);
  useEffect(()=>{setTheta(Math.PI/3);setParameters(DEFAULTS);setChoice("c");setResult("correct");},[resetToken]);
  const updateTheta=(value:number)=>{setTheta(clamp(value,-TAU,TAU));onInteraction();};
  const updateParameter=(key:keyof Parameters,value:number)=>{setParameters((state)=>({...state,[key]:clampParameter(key,value)}));onInteraction();};
  const reset=(notify=true)=>{setTheta(Math.PI/3);setParameters(DEFAULTS);setChoice("c");setResult("correct");if(notify)onInteraction();};
  const choose=(value:Choice)=>{setChoice(value);setResult("idle");onInteraction();};
  const grade=()=>{setResult(choice==="c"?"correct":"incorrect");onInteraction();};
  return <section className="target-cosine-page" data-testid="trigonometry-mockup-0319" data-dedicated-lesson="262" data-object-model="horizontal-unit-circle-projection-transformable-cosine-function-model" data-theta={theta.toFixed(6)} data-current-x={Math.cos(theta).toFixed(6)} data-current-y={current.toFixed(6)} data-amplitude={model.amplitude.toFixed(3)} data-period={model.period.toFixed(6)} data-phase-shift={parameters.c.toFixed(6)} data-vertical-shift={parameters.d.toFixed(3)} data-practice-choice={choice} data-practice-result={result}>
    <header className="target-cosine-header"><div><span>Trigonometry</span><h1>Cosine Graph</h1><p>Explore phase-shifted periodic shape.</p><section><b>♙ Intermediate-Advanced</b><b>ϟ Visual Lab</b><b>▣ Trig Graphing / Geometry</b><b>◷ 6-10 min</b></section></div><footer><label><Languages/><select aria-label="Lesson language" defaultValue="en" onChange={onInteraction}><option value="en">English (English)</option><option value="hi">हिन्दी (Hindi)</option></select></label><button type="button" onClick={()=>reset()}><RotateCcw/>Reset</button><button type="button" onClick={()=>{void navigator.clipboard?.writeText(model.equation);onInteraction();}}><Share2/>Share</button><button type="button" onClick={()=>{document.querySelector(".target-cosine-workspace")?.scrollIntoView({behavior:"smooth"});onInteraction();}}>↗ Workspace⌄</button></footer></header>

    <section className="target-cosine-steps">{[[Eye,"Observe","See how cos x is formed from the unit circle."],[Hand,"Manipulate","Move the angle and change amplitude, period, phase."],[Lightbulb,"Notice","Watch the radius rotate and the cosine value trace the graph."],[Target,"Understand","Cosine is the horizontal projection of the rotating radius."]].map(([Icon,title,text],index)=><article key={String(title)}><h2><Icon/>{String(title)}</h2><p>{String(text)}</p>{index===0?<MiniCircle/>:index===1?<MiniControls/>:index===2?<MiniCosine/>:<strong>y = cos x</strong>}</article>)}</section>

    <section className="target-cosine-workspace"><article><h2>UNIT CIRCLE (ROTATING RADIUS)</h2><CosineCircle theta={theta} onTheta={updateTheta}/></article><article><h2>COSINE GRAPH &nbsp; <b>y = cos x</b></h2><CosinePlot parameters={DEFAULTS} theta={theta} onTheta={updateTheta} testId="cosine-main-graph-handle"/><section><h3>Key facts</h3><div><span>✓ Domain: (−∞, ∞)</span><span>✓ Amplitude: 1</span><span>✓ cos 0 = 1</span><span>✓ cos π = −1</span><span>✓ Range: [−1, 1]</span><span>✓ Period: 2π</span></div></section></article></section>

    <section className="target-cosine-controls"><article><h2>ANGLE CONTROL</h2><label>x (radians)<output><b>{formatRadians(theta)}</b> ({Math.abs(theta).toFixed(3)})</output><input aria-label="Cosine angle" type="range" min={-TAU} max={TAU} step={Math.PI/180} value={theta} onChange={(event)=>updateTheta(Number(event.target.value))}/><small><span>−2π</span><span>−π</span><span>0</span><span>π</span><span>2π</span></small></label><footer>cos x = <strong>{Math.cos(theta).toFixed(4)}</strong></footer></article><article><header><h2>TRANSFORMATIONS</h2><b>y = A cos(Bx − C) + D</b></header><div>{([['a','Amplitude (A)',.1,3,.1],['b','Period factor (B)',.25,4,.25],['c','Phase shift (C)',-TAU,TAU,Math.PI/12],['d','Vertical shift (D)',-3,3,.25]] as const).map(([key,name,min,max,step])=><CosineControl key={key} name={name} value={parameters[key]} min={min} max={max} step={step} onDecrease={()=>updateParameter(key,parameters[key]-step)} onIncrease={()=>updateParameter(key,parameters[key]+step)} onChange={(value)=>updateParameter(key,value)} footer={key==='a'?"Stretches vertically":key==='b'?`Period = ${formatRadians(model.period)}`:key==='c'?`Shift right by ${formatRadians(parameters.c/parameters.b)}`:"Moves up/down"}/>)}</div></article><article><h2>WAVE INFO</h2><strong>{model.equation}</strong><footer><span>Amplitude<b>{formatNumber(model.amplitude)}</b></span><span>Period<b>{formatRadians(model.period)}</b></span></footer></article></section>

    <section className="target-cosine-lessons"><article><h2>THE RULE (COSINE GRAPH)</h2><p>The general cosine function is</p><strong>y = A cos(Bx − C) + D</strong><ul><li><i>A</i><b>Amplitude</b>Vertical stretch by |A|.</li><li><i>B</i><b>Period factor</b>Period = 2π/B.</li><li><i>C</i><b>Phase shift</b>Shift right by C/B.</li><li><i>D</i><b>Vertical shift</b>Shift up by D.</li></ul><footer><h3>SIGN OF COS x</h3><SignPlot/></footer></article><article><h2>WORKED EXAMPLE</h2><h3>Graph y = 2 cos (½x − π/3) + 1.</h3><ol><li><b>Amplitude A = 2</b> Vertical stretch by 2.</li><li><b>Period factor B = ½</b> Period = 4π.</li><li><b>Phase shift C = π/3</b> Shift right by 2π/3.</li><li><b>Vertical shift D = 1</b> Shift up by 1.</li></ol><CosinePlot parameters={{a:2,b:.5,c:Math.PI/3,d:1}} compact/><footer>Max = 3, &nbsp; Midline = 1, &nbsp; Min = −1, &nbsp; Period = 4π</footer></article><article><h2><TriangleAlert/>COMMON MISCONCEPTION</h2><h3>Cosine is NOT sine.</h3><p>cos 0 = 1 (starts at the maximum),<br/>sin 0 = 0 (starts at zero).</p><Comparison/><footer>Make sure you understand the horizontal projection from the unit circle—cosine measures the x-coordinate.</footer></article></section>

    <section className="target-cosine-practice"><article><h2><Target/>PRACTICE CHALLENGE</h2><p>Which equation matches the graph?</p><div>{[["a","A. y = cos x − 1"],["b","B. y = cos(x − π/2)"],["c","C. y = 2 cos(x + π/2)"],["d","D. y = −cos x + 1"]].map(([value,label])=><label key={value} className={choice===value?"selected":""}><input type="radio" name="cosine-choice" value={value} checked={choice===value} onChange={()=>choose(value as Choice)}/>{label}</label>)}</div><button type="button" onClick={grade}>Check</button>{result==="incorrect"?<p role="status">Compare amplitude, period, and the value at x = −π/2.</p>:null}</article><CosinePlot parameters={{a:2,b:1,c:-Math.PI/2,d:0}} compact/><aside className={result==="correct"?"correct":""}><h3><Check/>{result==="correct"?"Correct!":"Check the selected equation"}</h3><p>Amplitude = 2, Period = 2π.</p><p>It starts at −2 when x = −π/2,<br/>so equation C fits.</p></aside></section>
    <nav className="target-cosine-nav"><a href="/lessons/trigonometry/261-sine-graph"><ArrowLeft/><span><b>Previous</b>Sine Graph</span></a><a href="/lessons/trigonometry/263-tangent-graph"><span><b>Next</b>Tangent Graph</span><ArrowRight/></a></nav>
  </section>;
}

function CosineCircle({theta,onTheta}:{theta:number;onTheta:(value:number)=>void}){const svg=useRef<SVGSVGElement>(null),normalized=((theta%TAU)+TAU)%TAU,center={x:135,y:135},point={x:135+102*Math.cos(normalized),y:135-102*Math.sin(normalized)};const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(event.type==="pointermove"&&event.buttons!==1)return;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());let angle=Math.atan2(center.y-p.y,p.x-center.x);if(angle<0)angle+=TAU;onTheta(angle);};return <svg ref={svg} viewBox="0 0 280 280" role="img" aria-label="Draggable rotating radius with horizontal cosine projection" onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);move(event);}} onPointerMove={move}><line x1="8" x2="270" y1="135" y2="135"/><line x1="135" x2="135" y1="5" y2="273"/><circle cx="135" cy="135" r="102"/><path d={`M135 135L${point.x} ${point.y}`} stroke="#08a9d6" strokeWidth="2.5"/><line x1={point.x} x2={point.x} y1={point.y} y2="135" stroke="#fb7b19" strokeDasharray="4 3"/><line x1="135" x2={point.x} y1="135" y2="135" stroke="#fb7b19" strokeWidth="3"/><circle data-testid="cosine-unit-circle-handle" cx={point.x} cy={point.y} r="6" fill="#0879bd"/><text x={point.x+6} y={point.y-6}>(cos x, sin x)</text><text x={(135+point.x)/2-10} y="151" fill="#f97316">cos x</text><text x="120" y="152">O</text><text x="140" y="20">y</text><text x="268" y="130">x</text><text x="20" y="130">−1</text><text x="247" y="130">1</text><text x="122" y="265">−1</text><text x="122" y="42">1</text></svg>;}
function CosinePlot({parameters,theta,onTheta,compact=false,testId}:{parameters:Parameters;theta?:number;onTheta?:(value:number)=>void;compact?:boolean;testId?:string}){const svg=useRef<SVGSVGElement>(null),w=compact?300:470,h=compact?180:230,pad=compact?20:25,mid=h/2,scale=compact?35:63,path=cosPath(parameters,w,h,pad,scale),px=theta===undefined?null:pad+(theta+TAU)/(TAU*2)*(w-pad*2),py=theta===undefined?null:mid-(parameters.a*Math.cos(parameters.b*(theta-parameters.c))+parameters.d)*scale;const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!onTheta||(event.type==="pointermove"&&event.buttons!==1))return;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());onTheta((p.x-pad)/(w-pad*2)*TAU*2-TAU);};return <svg ref={svg} className={compact?"compact":""} viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Interactive transformed cosine graph" onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);move(event);}} onPointerMove={move}><Grid w={w} h={h} pad={pad}/><line x1={pad} x2={w-8} y1={mid} y2={mid}/><line x1={w/2} x2={w/2} y1="8" y2={h-8}/><path d={path} fill="none" stroke={compact?"#8b5cf6":"#079ced"} strokeWidth="2.4"/>{px!==null&&py!==null?<><line x1={px} x2={px} y1={py} y2={mid} stroke="#f97316" strokeDasharray="4 3"/><circle data-testid={testId} cx={px} cy={py} r="5" fill="#f97316"/></>:null}<text x="3" y={mid+13}>−2π</text><text x={w/2-8} y={mid+13}>0</text><text x={w-40} y={mid+13}>2π</text><text x={w-8} y={mid-5}>x</text><text x={w/2+5} y="12">y</text></svg>;}
function Grid({w,h,pad}:{w:number;h:number;pad:number}){return <g stroke="#d9e3ef" strokeDasharray="4 4">{Array.from({length:9},(_,i)=><line key={`v${i}`} x1={pad+i*(w-pad*2)/8} x2={pad+i*(w-pad*2)/8} y1="15" y2={h-15}/>)}{Array.from({length:5},(_,i)=><line key={`h${i}`} x1={pad} x2={w-pad} y1={25+i*(h-50)/4} y2={25+i*(h-50)/4}/>)}</g>;}
function CosineControl({name,value,min,max,step,onDecrease,onIncrease,onChange,footer}:{name:string;value:number;min:number;max:number;step:number;onDecrease:()=>void;onIncrease:()=>void;onChange:(value:number)=>void;footer:string}){return <label><b>{name}</b><section><button type="button" aria-label={`Decrease ${name}`} onClick={onDecrease}><Minus/></button><output>{formatRadiansOrNumber(value)}</output><button type="button" aria-label={`Increase ${name}`} onClick={onIncrease}><Plus/></button></section><input aria-label={name} type="range" min={min} max={max} step={step} value={value} onChange={(event)=>onChange(Number(event.target.value))}/><small><span>{formatRadiansOrNumber(min)}</span><span>{formatRadiansOrNumber(max)}</span></small><footer>{footer}</footer></label>;}
function MiniCircle(){return <svg viewBox="0 0 100 70"><circle cx="45" cy="35" r="28" fill="none" stroke="#64748b"/><line x1="15" x2="76" y1="35" y2="35" stroke="#64748b"/><line x1="45" x2="72" y1="35" y2="22" stroke="#08a9d6"/><line x1="45" x2="72" y1="35" y2="35" stroke="#f97316"/><circle cx="72" cy="22" r="4" fill="#08a9d6"/></svg>;}
function MiniControls(){return <svg viewBox="0 0 100 70">{[12,35,58].map((y,i)=><g key={y}><line x1="10" x2="90" y1={y} y2={y} stroke="#cbd5e1" strokeWidth="5"/><circle cx={20+i*20} cy={y} r="6" fill={i===0?"#06b6d4":i===1?"#3b82f6":"#8b5cf6"}/></g>)}</svg>;}
function MiniCosine(){return <svg viewBox="0 0 120 70"><path d={cosPath(DEFAULTS,120,70,5,18)} fill="none" stroke="#06a8cf" strokeWidth="2"/><line x1="65" x2="65" y1="18" y2="52" stroke="#f97316" strokeDasharray="3 2"/></svg>;}
function SignPlot(){return <svg viewBox="0 0 210 85"><line x1="10" x2="200" y1="43" y2="43" stroke="#64748b"/>{[10,57,105,152,200].map((x)=><line key={x} x1={x} x2={x} y1="37" y2="49" stroke="#64748b"/>)}<text x="8" y="66">−2π</text><text x="50" y="66">−π</text><text x="102" y="66">0</text><text x="149" y="66">π</text><text x="192" y="66">2π</text><text x="48" y="27" fill="#079447">+</text><text x="96" y="27" fill="#e11d48">−</text><text x="146" y="27" fill="#079447">+</text></svg>;}
function Comparison(){return <svg viewBox="0 0 260 170"><text x="165" y="14" fill="#0879bd">y = cos x</text><path d={cosPath(DEFAULTS,260,70,5,22)} fill="none" stroke="#06a8cf" strokeWidth="2"/><g transform="translate(0 90)"><text x="165" y="-3" fill="#7c3aed">y = sin x</text><path d={sinPath(260,70,5,22)} fill="none" stroke="#8b5cf6" strokeWidth="2"/></g></svg>;}
function cosineModel(p:Parameters){return{amplitude:Math.abs(p.a),period:TAU/Math.abs(p.b),min:p.d-Math.abs(p.a),max:p.d+Math.abs(p.a),equation:cosineEquation(p),value:(x:number)=>p.a*Math.cos(p.b*x-p.c)+p.d};}
function cosPath(p:Parameters,w:number,h:number,pad:number,scale:number){const parts=[];for(let i=0;i<=180;i++){const x=-TAU+i/180*TAU*2,y=p.a*Math.cos(p.b*x-p.c)+p.d,px=pad+i/180*(w-pad*2),py=h/2-y*scale;parts.push(`${i?"L":"M"}${px.toFixed(2)} ${py.toFixed(2)}`);}return parts.join(" ");}
function sinPath(w:number,h:number,pad:number,scale:number){const parts=[];for(let i=0;i<=180;i++){const x=-TAU+i/180*TAU*2,px=pad+i/180*(w-pad*2),py=h/2-Math.sin(x)*scale;parts.push(`${i?"L":"M"}${px.toFixed(2)} ${py.toFixed(2)}`);}return parts.join(" ");}
function formatRadians(value:number){const r=value/Math.PI,values:Array<[number,string]>=[[-2,"−2π"],[-1,"−π"],[-.5,"−π/2"],[-1/3,"−π/3"],[0,"0"],[1/3,"π/3"],[.5,"π/2"],[1,"π"],[2,"2π"],[4,"4π"]];return values.find(([v])=>Math.abs(v-r)<.01)?.[1]??`${r.toFixed(2)}π`;}
function formatRadiansOrNumber(value:number){return Math.abs(value)>=Math.PI-.01?formatRadians(value):formatNumber(value);}
function cosineEquation(p:Parameters){const coefficient=Math.abs(p.a-1)<1e-8?"":Math.abs(p.a+1)<1e-8?"−":`${formatNumber(p.a)} `,frequency=Math.abs(p.b-1)<1e-8?"x":`${formatNumber(p.b)}x`,phase=Math.abs(p.c)<1e-8?"":` − ${formatRadians(p.c)}`,shift=Math.abs(p.d)<1e-8?"":p.d>0?` + ${formatNumber(p.d)}`:` − ${formatNumber(Math.abs(p.d))}`;return`y = ${coefficient}cos(${frequency}${phase})${shift}`.replace("cos(x)","cos x");}
function clampParameter(key:keyof Parameters,value:number){const bounds:Record<keyof Parameters,[number,number]>={a:[.1,3],b:[.25,4],c:[-TAU,TAU],d:[-3,3]};return clamp(value,...bounds[key]);}
function formatNumber(value:number){return Number(value.toFixed(2)).toString();}function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
