import { ArrowLeft, ArrowRight, Check, ExternalLink, Languages, RotateCcw, Share2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./DilationPointTargetLesson241.css";

type Point={x:number;y:number}; type VertexKey="A"|"B"|"D"; type Vertices=Record<VertexKey,Point>; type Drag=VertexKey|"centre"|null;
const INITIAL_CENTRE={x:0,y:0}; const INITIAL_VERTICES:Vertices={A:{x:2,y:1},B:{x:4,y:2},D:{x:2,y:0}}; const STAGES=[["Observe","See the effect"],["Manipulate","Change scale and centre"],["Notice","Look for patterns"],["Understand","Learn the rule"],["Try it","Practice"]];

export default function DilationPointTargetLesson241({resetToken,onInteraction}:LessonAdapterProps){
  const [centre,setCentre]=useState<Point>(INITIAL_CENTRE),[vertices,setVertices]=useState<Vertices>(INITIAL_VERTICES),[magnitude,setMagnitude]=useState(2),[sign,setSign]=useState<1|-1>(1),[rays,setRays]=useState(true),[imageVisible,setImageVisible]=useState(true),[stage,setStage]=useState(0),[language,setLanguage]=useState("English (English)"),[feedback,setFeedback]=useState(""),[score,setScore]=useState<number|null>(null);
  const k=magnitude*sign, model=useMemo(()=>dilate(centre,vertices,k),[centre,vertices,k]);
  const reset=()=>{setCentre(INITIAL_CENTRE);setVertices(INITIAL_VERTICES);setMagnitude(2);setSign(1);setRays(true);setImageVisible(true);setStage(0);setFeedback("");setScore(null);onInteraction();};
  useEffect(()=>{setCentre(INITIAL_CENTRE);setVertices(INITIAL_VERTICES);setMagnitude(2);setSign(1);setRays(true);setImageVisible(true);setStage(0);setLanguage("English (English)");setFeedback("");setScore(null);},[resetToken]);
  const setScale=(value:number)=>{setMagnitude(clamp(Math.abs(value),.5,4));onInteraction();};
  const share=async()=>{try{await navigator.clipboard?.writeText(`Dilation about C${fp(centre)} with k=${k}: A'${fp(model.image.A)}, B'${fp(model.image.B)}, D'${fp(model.image.D)}`);}catch{/* Clipboard can be unavailable in test contexts. */}onInteraction();};
  const check=()=>{const exact=Math.abs(centre.x)<.01&&Math.abs(centre.y)<.01&&Math.abs(k-1.5)<.01;setScore(exact?10:6);setFeedback(exact?"Correct construction: every image vertex is 1.5 times as far from C.":"Construction is valid, but set C=(0,0) and k=1.5 for this task.");onInteraction();};
  return <section className="target-dilation-page" data-testid="dynamic-geometry-mockup-0298" data-dedicated-lesson="241" data-object-model="centre-scale-triangle-dilation" data-scale={k.toFixed(2)} data-perimeter-ratio={model.perimeterRatio.toFixed(4)} data-area-ratio={model.areaRatio.toFixed(4)}>
    <header className="target-dilation-header"><h1>Dilation from Point</h1><p>Understand similarity and scale.</p><div><b>♙ Intermediate–Advanced</b><b>ϟ Investigation Lab</b><b>▣ Transformation / Locus Tools</b><b>◷ 6–10 min</b></div><footer><label><Languages/><select aria-label="Lesson language" value={language} onChange={e=>{setLanguage(e.target.value);onInteraction();}}><option>English (English)</option><option>हिन्दी (Hindi)</option></select></label><button type="button" onClick={reset}><RotateCcw/>Reset</button><button type="button" onClick={()=>void share()}><Share2/>Share</button><button type="button" onClick={()=>{document.getElementById("dilation-workspace")?.scrollIntoView();onInteraction();}}><ExternalLink/>Workspace</button></footer></header>
    <nav className="target-dilation-stages">{STAGES.map(([name,copy],i)=><button type="button" key={name} className={stage===i?"is-active":""} onClick={()=>{setStage(i);onInteraction();}}><i>{i+1}</i><span><b>{name}</b><small>{copy}</small></span></button>)}</nav>
    <section className="target-dilation-workspace" id="dilation-workspace"><article><h2>Explore the dilation</h2><p>Drag the centre <i>C</i> or any point of the figure. Use the scale factor <i>k</i>.</p><header><span>Mode:</span><button type="button" className={sign===1?"is-active":""} onClick={()=>{setSign(1);onInteraction();}}>◎ Positive k</button><button type="button" className={sign===-1?"is-active":""} onClick={()=>{setSign(-1);onInteraction();}}>◎ Negative k</button><label><input type="checkbox" checked={rays} onChange={e=>{setRays(e.target.checked);onInteraction();}}/>Show rays</label><button type="button" onClick={()=>{setImageVisible(false);onInteraction();}}>⌫ Clear</button></header><DilationGraph centre={centre} vertices={vertices} model={model} rays={rays} imageVisible={imageVisible} onCentre={p=>{setCentre(p);setImageVisible(true);onInteraction();}} onVertex={(key,p)=>{setVertices(v=>({...v,[key]:p}));setImageVisible(true);onInteraction();}}/><div className="target-dilation-scale"><b>Scale factor <i>k</i></b><button type="button" aria-label="Decrease scale factor" onClick={()=>setScale(magnitude-.5)}>−</button><input aria-label="Scale factor" type="range" min=".5" max="4" step=".5" value={magnitude} onChange={e=>setScale(Number(e.target.value))}/><strong>{f(k)}</strong><button type="button" aria-label="Increase scale factor" onClick={()=>setScale(magnitude+.5)}>+</button><b>Centre <i>C</i></b><Coordinate name="Dilation centre C" point={centre} onValue={(axis,value)=>{setCentre(c=>({...c,[axis]:clamp(value,-5,5)}));onInteraction();}}/></div></article><aside><section><h2>What happens?</h2><strong>Image = k × Original <small>(from centre C)</small></strong><h3>Lengths (distance from C)</h3><Metric name="CA" original={model.distances.A} image={model.imageDistances.A} ratio={Math.abs(k)}/><Metric name="CB" original={model.distances.B} image={model.imageDistances.B} ratio={Math.abs(k)}/><h3>Perimeter</h3><Metric name="P" original={model.perimeter} image={model.imagePerimeter} ratio={model.perimeterRatio}/><h3>Area</h3><Metric name="A" original={model.area} image={model.imageArea} ratio={model.areaRatio} square/></section><section><h2>Try negative scale</h2><p>Turn on Negative <i>k</i> mode and move the slider. The image appears on the opposite side of <i>C</i>.</p><div><i>A'</i><span/><b>C</b><span/><i>A</i></div><strong>k &lt; 0 &nbsp; (opposite ray)</strong></section></aside></section>
    <section className="target-dilation-learning"><article><h2>Construction steps</h2><ol><li>Choose centre <i>C</i> and scale factor <i>k</i>.</li><li>Join <i>C</i> to each vertex of the figure.</li><li>Mark each image point on the same ray: <i>CP' = k × CP</i>.</li></ol><aside>Tip: Use rays for accurate construction.</aside></article><article><h2>Insight</h2><p>For any point <i>P</i> and its image <i>P'</i> about centre <i>C</i> with scale factor <i>k</i>:</p><strong>CP⃗' = k CP⃗</strong><ul><li>k &gt; 0: image on the same ray.</li><li>k &lt; 0: image on the opposite ray.</li><li>|k| &gt; 1: enlargement; 0 &lt; |k| &lt; 1: reduction.</li><li>Area scale factor = k².</li></ul></article><article><h2>Quick example</h2><p>Given: C(1, −1), A(3, 2), k = −2</p><ol><li>CA⃗ = (2, 3)</li><li>CA⃗' = −2(2, 3) = (−4, −6)</li><li>A' = C + CA⃗' = (−3, −7)</li></ol><strong>Answer: A'(−3, −7)</strong></article></section>
    <section className="target-dilation-practice"><article><h2>Your turn</h2><p>Dilate triangle ABD about C with the given scale factor k.</p><strong>A(2,1), &nbsp; B(4,2), &nbsp; D(2,0), &nbsp; k=1.5</strong><button type="button" onClick={()=>{setMagnitude(1.5);setSign(1);setCentre(INITIAL_CENTRE);setScore(null);setFeedback("");onInteraction();}}><RotateCcw/> New question</button></article><article><h2>Task</h2><ol><li>Plot triangle ABD.</li><li>Set the centre to C(0,0) and k=1.5.</li><li>Construct the image A'B'D'.</li><li>Write the coordinates of A', B', and D'.</li></ol><button type="button" onClick={check}><Check/>Check my construction</button></article><aside><h3>Your score</h3><strong>{score===null?"−":score} / 10</strong><h3>Accuracy</h3><strong>{score===null?"−":score*10}%</strong></aside>{feedback&&<p role="status">{feedback}</p>}</section>
    <nav className="target-dilation-nav"><a href="/lessons/geometry/240-rotation-around-point"><ArrowLeft/><span><b>Previous</b>Rotation Around Point</span></a><a href="/lessons/geometry/242-matrix-transformation"><span><b>Next</b>Matrix Transformation</span><ArrowRight/></a></nav>
  </section>;
}

function DilationGraph({centre,vertices,model,rays,imageVisible,onCentre,onVertex}:{centre:Point;vertices:Vertices;model:ReturnType<typeof dilate>;rays:boolean;imageVisible:boolean;onCentre:(p:Point)=>void;onVertex:(k:VertexKey,p:Point)=>void}){const ref=useRef<SVGSVGElement>(null),drag=useRef<Drag>(null),origin={x:155,y:202},scale=32,s=(p:Point)=>({x:origin.x+p.x*scale,y:origin.y-p.y*scale});const world=(e:ReactPointerEvent<SVGSVGElement>)=>{const m=ref.current?.getScreenCTM();if(!m)return null;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return{x:(p.x-origin.x)/scale,y:(origin.y-p.y)/scale}},begin=(d:Exclude<Drag,null>)=>(e:ReactPointerEvent<SVGCircleElement>)=>{drag.current=d;e.currentTarget.setPointerCapture(e.pointerId)};const o=s(centre),points=mapPoints(vertices,s),images=mapPoints(model.image,s);return <svg ref={ref} className="target-dilation-graph" viewBox="0 0 540 420" role="img" aria-label="Interactive triangle dilation with draggable centre and vertices" onPointerMove={e=>{if(!drag.current)return;const p=world(e);if(!p)return;const next={x:clamp(roundHalf(p.x),-5,9),y:clamp(roundHalf(p.y),-6,7)};if(drag.current==="centre")onCentre(next);else onVertex(drag.current,next)}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><rect width="540" height="420" fill="#fff"/><Grid/>{rays&&imageVisible&&Object.keys(vertices).map(key=>{const k=key as VertexKey;return <line key={k} x1={o.x} y1={o.y} x2={images[k].x} y2={images[k].y} stroke="#8b5cf6" strokeDasharray="5 4"/>})}<polygon points={poly(points)} fill="#60a5fa44" stroke="#1685f8" strokeWidth="2"/>{imageVisible&&<polygon data-testid="dilation-image-polygon" points={poly(images)} fill="#a855f733" stroke="#7c3aed" strokeWidth="2"/>}<circle data-testid="dilation-centre" data-x={centre.x} data-y={centre.y} cx={o.x} cy={o.y} r="7" fill="#111827" onPointerDown={begin("centre")}/>{(Object.keys(vertices) as VertexKey[]).map(k=><g key={k}><circle data-testid={`dilation-source-${k.toLowerCase()}`} data-x={vertices[k].x} data-y={vertices[k].y} cx={points[k].x} cy={points[k].y} r="7" fill="#1685f8" onPointerDown={begin(k)}/><text x={points[k].x+8} y={points[k].y-8} fontSize="13" fill="#163b74">{k} {fp(vertices[k])}</text>{imageVisible&&<><circle data-testid={`dilation-image-${k.toLowerCase()}`} data-x={model.image[k].x.toFixed(4)} data-y={model.image[k].y.toFixed(4)} cx={images[k].x} cy={images[k].y} r="6" fill="#7c3aed"/><text x={images[k].x+7} y={images[k].y-7} fontSize="13" fill="#6d28d9">{k}' {fp(model.image[k])}</text></>}</g>)}<text x={o.x+10} y={o.y+25} fill="#172554" fontSize="13">C {fp(centre)}</text></svg>}
function Grid(){return <g><g stroke="#e5edf5">{Array.from({length:18},(_,i)=><line key={`v${i}`} x1={i*32} x2={i*32} y1="0" y2="420"/>)}{Array.from({length:14},(_,i)=><line key={`h${i}`} x1="0" x2="540" y1={i*32} y2={i*32}/>)}</g><g stroke="#475569"><line x1="0" x2="540" y1="202" y2="202"/><line x1="155" x2="155" y1="0" y2="420"/></g></g>}
function Coordinate({name,point,onValue}:{name:string;point:Point;onValue:(a:"x"|"y",v:number)=>void}){return <div className="target-dilation-coordinate"><label>x<input aria-label={`${name} x coordinate`} type="number" value={point.x} onChange={e=>onValue("x",Number(e.target.value))}/></label><label>y<input aria-label={`${name} y coordinate`} type="number" value={point.y} onChange={e=>onValue("y",Number(e.target.value))}/></label></div>}
function Metric({name,original,image,ratio,square=false}:{name:string;original:number;image:number;ratio:number;square?:boolean}){return <div className="target-dilation-metric"><i>{name} = {f2(original)}</i><i>{name}' = {f2(image)}</i><span>Ratio</span><b>{f2(ratio)}{square&&" (= k²)"}</b></div>}
function dilate(c:Point,v:Vertices,k:number){const image=Object.fromEntries(Object.entries(v).map(([key,p])=>[key,{x:c.x+k*(p.x-c.x),y:c.y+k*(p.y-c.y)}])) as Vertices,distances=mapValues(v,p=>Math.hypot(p.x-c.x,p.y-c.y)),imageDistances=mapValues(image,p=>Math.hypot(p.x-c.x,p.y-c.y)),perimeter=perim(v),imagePerimeter=perim(image),area=triArea(v),imageArea=triArea(image);return{image,distances,imageDistances,perimeter,imagePerimeter,area,imageArea,perimeterRatio:perimeter?imagePerimeter/perimeter:0,areaRatio:area?imageArea/area:0}}
function perim(v:Vertices){return dist(v.A,v.B)+dist(v.B,v.D)+dist(v.D,v.A)}function triArea(v:Vertices){return Math.abs((v.A.x*(v.B.y-v.D.y)+v.B.x*(v.D.y-v.A.y)+v.D.x*(v.A.y-v.B.y))/2)}function dist(a:Point,b:Point){return Math.hypot(a.x-b.x,a.y-b.y)}function mapValues<T>(v:Vertices,fn:(p:Point)=>T){return Object.fromEntries(Object.entries(v).map(([k,p])=>[k,fn(p)])) as Record<VertexKey,T>}function mapPoints(v:Vertices,fn:(p:Point)=>Point){return mapValues(v,fn)}function poly(v:Vertices){return `${v.A.x},${v.A.y} ${v.B.x},${v.B.y} ${v.D.x},${v.D.y}`}function fp(p:Point){return `(${f(p.x)}, ${f(p.y)})`}function f(n:number){return Number(n.toFixed(2)).toString()}function f2(n:number){return n.toFixed(2)}function roundHalf(n:number){return Math.round(n*2)/2}function clamp(n:number,min:number,max:number){return Math.min(max,Math.max(min,Number.isFinite(n)?n:min))}
