import { ArrowLeft, ArrowRight, Minus, Plus, RotateCcw, Search, Shuffle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { KeyboardEvent, PointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./DistanceBetweenPointsTargetLesson169.css";
import "./DistanceBetweenPointsTargetLesson169.icons.css";

type Point = { x: number; y: number };
const clamp = (value: number) => Math.max(-8, Math.min(8, value));
const delta = (a: Point, b: Point) => ({ dx: Math.abs(b.x - a.x), dy: Math.abs(b.y - a.y) });
const distance = (a: Point, b: Point) => Math.hypot(b.x - a.x, b.y - a.y);

function DistanceGrid({ a, b, grid, snap, zoom, onPoint }: { a: Point; b: Point; grid: boolean; snap: boolean; zoom: number; onPoint: (which: "a" | "b", point: Point) => void }) {
  const ref = useRef<SVGSVGElement>(null), width = 480, height = 460, originX = 240, originY = 230, unit = 26 * zoom;
  const fromClient = (clientX: number, clientY: number) => { const box = ref.current?.getBoundingClientRect(); if (!box) return { x: 0, y: 0 }; const x = (((clientX - box.left) / box.width) * width - originX) / unit, y = (originY - ((clientY - box.top) / box.height) * height) / unit; return { x: clamp(snap ? Math.round(x) : Math.round(x * 2) / 2), y: clamp(snap ? Math.round(y) : Math.round(y * 2) / 2) }; };
  const move = (event: PointerEvent<SVGCircleElement>, which: "a" | "b") => onPoint(which, fromClient(event.clientX, event.clientY));
  const keyMove = (event: KeyboardEvent<SVGCircleElement>, which: "a" | "b", point: Point) => { const step = snap ? 1 : .5, next = { ...point }; if (event.key === "ArrowLeft") next.x = clamp(point.x - step); if (event.key === "ArrowRight") next.x = clamp(point.x + step); if (event.key === "ArrowUp") next.y = clamp(point.y + step); if (event.key === "ArrowDown") next.y = clamp(point.y - step); if (next.x !== point.x || next.y !== point.y) { event.preventDefault(); onPoint(which, next); } };
  const { dx, dy } = delta(a, b), d = distance(a, b), ax = originX + a.x * unit, ay = originY - a.y * unit, bx = originX + b.x * unit, by = originY - b.y * unit;
  return <svg ref={ref} viewBox={`0 0 ${width} ${height}`} className="dbp169-grid" role="img" aria-label="Distance right triangle graph"><defs><pattern id="dbp169-grid" width={unit} height={unit} patternUnits="userSpaceOnUse"><path d={`M${unit} 0H0V${unit}`} fill="none" stroke="#dfe8ef" /></pattern><marker id="dbp169-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#17213a" /></marker></defs><rect width={width} height={height} fill={grid ? "url(#dbp169-grid)" : "#fff"} /><line x1="5" x2={width - 5} y1={originY} y2={originY} className="axis" markerEnd="url(#dbp169-arrow)" /><line x1={originX} x2={originX} y1={height - 5} y2="5" className="axis" markerEnd="url(#dbp169-arrow)" />{[-8,-6,-4,-2,0,2,4,6,8].map((value) => <g key={value}><text x={originX + value * unit + (value === 0 ? 10 : 0)} y={originY + 18}>{value}</text>{value !== 0 ? <text x={originX - 11} y={originY - value * unit + 4}>{value}</text> : null}</g>)}<text x={width - 10} y={originY - 9}>x</text><text x={originX + 9} y="14">y</text><path className="triangle" d={`M${ax} ${ay}H${bx}V${by}Z`} /><line className="distance" x1={ax} y1={ay} x2={bx} y2={by} /><path className="right" d={`M${bx - 8} ${ay}V${ay + (by > ay ? 8 : -8)}H${bx}`} /><g className="measure dx" transform={`translate(${(ax + bx) / 2 - 40} ${ay - 31})`}><rect width="99" height="25" rx="4" /><text x="49" y="16">Δx = |{b.x} − {a.x}| = {dx}</text></g><g className="measure dy" transform={`translate(${bx + 8} ${(ay + by) / 2 - 12})`}><rect width="104" height="25" rx="4" /><text x="52" y="16">Δy = |{b.y} − {a.y}| = {dy}</text></g><g className="measure d" transform={`translate(${(ax + bx) / 2 - 37} ${(ay + by) / 2 + 8})`}><rect width="75" height="25" rx="4" /><text x="37" y="16">d = {d.toFixed(4)}</text></g>{[["a",a,ax,ay,"A","#176de5"],["b",b,bx,by,"B","#176de5"]].map(([which,point,x,y,label,color]) => { const p = point as Point; return <g key={which as string}><circle data-testid={`distance-point-${which}`} role="slider" tabIndex={0} aria-label={`Drag point ${label}`} cx={x as number} cy={y as number} r="7" fill={color as string} stroke="#fff" strokeWidth="2" onPointerDown={(event) => { event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); move(event, which as "a" | "b"); }} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) move(event, which as "a" | "b"); }} onKeyDown={(event) => keyMove(event, which as "a" | "b", p)} /><text className="point-label" x={(x as number) + (which === "a" ? -22 : -22)} y={(y as number) + (which === "a" ? -14 : 31)}>{label} ({p.x}, {p.y})</text></g>; })}</svg>;
}

function PointControls({ label, point, onChange, onReset }: { label: "A" | "B"; point: Point; onChange: (point: Point) => void; onReset: () => void }) {
  return <section className="dbp169-point"><header><i /> <b>{label} (x<sub>{label === "A" ? "1" : "2"}</sub>, y<sub>{label === "A" ? "1" : "2"}</sub>)</b><span>⌄</span></header><div><label>x<sub>{label === "A" ? "1" : "2"}</sub><input aria-label={`${label} x coordinate`} type="number" min="-8" max="8" value={point.x} onChange={(event) => onChange({ ...point, x: clamp(Number(event.target.value)) })} /></label><label>y<sub>{label === "A" ? "1" : "2"}</sub><input aria-label={`${label} y coordinate`} type="number" min="-8" max="8" value={point.y} onChange={(event) => onChange({ ...point, y: clamp(Number(event.target.value)) })} /></label><button aria-label={`Reset point ${label}`} onClick={onReset}><RotateCcw /></button></div></section>;
}

export default function DistanceBetweenPointsTargetLesson169({ resetToken, onInteraction }: LessonAdapterProps) {
  const [a, setAState] = useState<Point>({ x: 2, y: 3 }), [b, setBState] = useState<Point>({ x: 6, y: -1 }), [grid, setGrid] = useState(true), [snap, setSnap] = useState(true), [zoom, setZoom] = useState(1), [tab, setTab] = useState(0), [pa, setPa] = useState<Point>({ x: 1, y: 2 }), [pb, setPb] = useState<Point>({ x: 6, y: -3 });
  const setA = (point: Point) => { setAState(point); onInteraction(); }, setB = (point: Point) => { setBState(point); onInteraction(); };
  const reset = () => { setAState({ x: 2, y: 3 }); setBState({ x: 6, y: -1 }); setGrid(true); setSnap(true); setZoom(1); onInteraction(); };
  useEffect(() => { setAState({ x: 2, y: 3 }); setBState({ x: 6, y: -1 }); setGrid(true); setSnap(true); setZoom(1); setTab(0); setPa({ x: 1, y: 2 }); setPb({ x: 6, y: -3 }); }, [resetToken]);
  const diff = delta(a, b), d = distance(a, b), pd = distance(pa, pb), target = 7, within = Math.abs(pd - target) <= .1;
  return <main className="dbp169-page" data-testid="geometry-mockup-0226" data-dedicated-lesson="169" data-object-model="two-independent-editable-pointer-keyboard-draggable-points-generated-right-triangle-deltas-distance-grid-snap-zoom-and-independent-target-distance-practice" data-a={`${a.x}:${a.y}`} data-b={`${b.x}:${b.y}`} data-distance={d.toFixed(4)} data-grid={grid} data-snap={snap} data-zoom={zoom} data-tab={tab} data-practice={`${pa.x}:${pa.y},${pb.x}:${pb.y}`} data-practice-distance={pd.toFixed(4)} data-within={within}>
    <header className="dbp169-header"><span>COORDINATE GEOMETRY</span><h1>Distance between Points</h1><p>Discover the distance formula using right triangles.</p><aside><b>♙ <span>Level<small>Intermediate</small></span></b><b>▣ <span>Module<small>Coordinate Geometry</small></span></b><b>◷ <span>Time<small>6–10 min</small></span></b></aside></header>
    <nav className="dbp169-tabs">{[["⌘","Explore"],["▥","Patterns"],["∿","Formula"],["⌁","Practice"]].map(([icon,label],index) => <button key={label} className={tab === index ? "active" : ""} onClick={() => { setTab(index); onInteraction(); }}>{icon} {label}</button>)}</nav>
    <section className="dbp169-model"><article><header><div><h2>Interactive Model</h2><p>Drag the blue points to explore. A right triangle shows the horizontal and vertical differences.</p></div><button onClick={reset}><RotateCcw /> Reset</button></header><div className="dbp169-plot-tools"><label>Grid <input type="checkbox" checked={grid} onChange={(event) => { setGrid(event.target.checked); onInteraction(); }} /></label><label>Snap <input type="checkbox" checked={snap} onChange={(event) => { setSnap(event.target.checked); onInteraction(); }} /></label><span><Search /><button aria-label="Zoom out" onClick={() => { setZoom((value) => Math.max(.75, value - .25)); onInteraction(); }}><Minus /></button><button aria-label="Zoom in" onClick={() => { setZoom((value) => Math.min(1.25, value + .25)); onInteraction(); }}><Plus /></button></span></div><DistanceGrid a={a} b={b} grid={grid} snap={snap} zoom={zoom} onPoint={(which, point) => which === "a" ? setA(point) : setB(point)} /></article><aside><h2>Points</h2><PointControls label="A" point={a} onChange={setA} onReset={() => setA({ x: 2, y: 3 })} /><PointControls label="B" point={b} onChange={setB} onReset={() => setB({ x: 6, y: -1 })} /><section className="dbp169-result"><h2>Live result</h2><div><small>Distance d</small><strong>{d.toFixed(4)}</strong></div><h3>ⓘ Breakdown</h3><p><i /> Δx = |x₂ − x₁| = |{b.x} − {a.x}| = {diff.dx}</p><p><i /> Δy = |y₂ − y₁| = |{b.y} − {a.y}| = {diff.dy}</p><p><i /> d = √(Δx² + Δy²) = √{diff.dx}² + {diff.dy}² = {d.toFixed(4)}</p></section></aside></section>
    <section className="dbp169-how"><div><h2>How it works</h2><p><i>1</i><b>Horizontal difference</b><span>Move from A horizontally to align with B. This forms Δx.</span></p><p><i>2</i><b>Vertical difference</b><span>Move vertically to B. This forms Δy.</span></p><p><i>3</i><b>Right triangle</b><span>The distance d is the hypotenuse of the right triangle.</span></p></div><svg viewBox="0 0 220 100"><path d="M25 15H175V80Z" /><path className="hyp" d="M25 15L175 80" /><path className="right" d="M25 70H35V80" /><text x="88" y="12">Δx</text><text x="4" y="52">Δy</text><text x="100" y="52">d</text><circle cx="25" cy="15" r="3" /><circle cx="175" cy="80" r="3" /></svg></section>
    <section className="dbp169-learn"><article><h2>The Rule</h2><b>Distance formula</b><strong>d = √((x₂ − x₁)² + (y₂ − y₁)²)</strong><small>Where:</small><ul><li>(x₁, y₁), (x₂, y₂) are the coordinates of the points.</li><li>d is the distance between the points.</li><li>The result is always non-negative.</li></ul></article><article><h2>Worked example</h2><b>Find the distance between C(−3, 4) and D(5, −2).</b><p><i /> Δx = |5 − (−3)| = |8| = 8</p><p><i /> Δy = |−2 − 4| = |−6| = 6</p><p><i /> d = √(8² + 6²) = √100 = 10</p><strong>✓ &nbsp; Distance = 10 units</strong></article></section>
    <section className="dbp169-practice"><header><h2>Try it yourself</h2><p>Drag the points or enter coordinates to match the target distance.</p><button onClick={() => { setPa({ x: 1, y: 2 }); setPb({ x: 6, y: -3 }); onInteraction(); }}><RotateCcw /> Reset</button></header><article><small>Target distance</small><strong>7.0000 &nbsp; ⓘ</strong><b className={within ? "ok" : ""}>{within ? "Within tolerance ✓" : "Keep adjusting"}</b></article><PointControls label="A" point={pa} onChange={(point) => { setPa(point); onInteraction(); }} onReset={() => setPa({ x: 1, y: 2 })} /><button className="swap" aria-label="Swap practice points" onClick={() => { setPa(pb); setPb(pa); onInteraction(); }}><Shuffle /></button><PointControls label="B" point={pb} onChange={(point) => { setPb(point); onInteraction(); }} onReset={() => setPb({ x: 6, y: -3 })} /><aside><small>Check your distance</small><p>d = √(({pb.x} − {pa.x})² + ({pb.y} − {pa.y})²)</p><p>= {pd.toFixed(4)}</p><b>Difference from target: {Math.abs(pd - target).toFixed(4)}</b></aside></section>
    <nav className="dbp169-nav"><a href="/lessons/geometry/168-plotting-points"><ArrowLeft /><span><small>Previous</small><b>Plotting Points</b></span></a><div><small>Lesson progress</small><span><i className="active" /><i /><i /><i /><i /></span><b>2 of 5</b></div><a href="/lessons/geometry/170-midpoint"><span><small>Next</small><b>Midpoint</b></span><ArrowRight /></a></nav>
    <footer className="dbp169-footer"><div><b>◉ &nbsp; Math Universe</b><p>Interactive math labs, visual proofs, NCERT explorations,<br />graphing, and classroom-ready activities.</p></div><a href="#sitemap">▥ &nbsp; Sitemap</a><a href="#docs">♧ &nbsp; Docs</a><a href="#about">✉ &nbsp; About</a><small>© 2026 INDIAN SERVERS PRIVATE LIMITED. NO RIGHT TO REPRODUCE IT.<br />www.IndianServers.com &nbsp; info@IndianServers.com</small></footer>
  </main>;
}
