import { useEffect, useRef, useState, type PointerEvent } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Expand, Info, Languages, LocateFixed, RotateCcw, Share2, Sparkles, TriangleAlert } from "lucide-react";
import type { LessonAdapterProps } from "../types";
import "./DomainRangeTargetLesson130.css";
import "./DomainRangeTargetLesson130Tuning.css";

const clean = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(2).replace(/0+$/, "").replace(/\.$/, "");
const signedInside = (shift: number) => shift < 0 ? `− ${clean(Math.abs(shift))}` : `+ ${clean(shift)}`;
const signedOutside = (shift: number) => shift < 0 ? `− ${clean(Math.abs(shift))}` : shift > 0 ? `+ ${clean(shift)}` : "";
const formula = (domainShift: number, rangeShift: number, name = "f") => `${name}(x) = √(x ${signedInside(domainShift)}) ${signedOutside(rangeShift)}`.trim();
const resultText = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(3);

function ProjectorGraph({ domainShift, rangeShift, grid, onStartMove }: { domainShift: number; rangeShift: number; grid: boolean; onStartMove: (domainShift: number, rangeShift: number) => void }) {
  const svg = useRef<SVGSVGElement>(null);
  const [dragging, setDragging] = useState(false);
  const px = (x: number) => 219 + x * 53.5;
  const py = (y: number) => 287 - y * 49;
  const startX = -domainShift;
  const pointer = (event: PointerEvent<SVGSVGElement>) => {
    const box = svg.current?.getBoundingClientRect(); if (!box) return;
    const x = Math.max(-4, Math.min(4, Math.round(((((event.clientX - box.left) / box.width) * 560) - 219) / 53.5)));
    const y = Math.max(-3, Math.min(3, Math.round((287 - (((event.clientY - box.top) / box.height) * 580)) / 49)));
    onStartMove(-x, y);
  };
  const path = Array.from({ length: 90 }, (_, index) => { const x = startX + index * ((6 - startX) / 89); return `${index ? "L" : "M"}${px(x)},${py(Math.sqrt(Math.max(0, x + domainShift)) + rangeShift)}`; }).join(" ");
  return <svg ref={svg} className="dom130-graph" viewBox="0 0 560 580" role="img" aria-label="Domain and range projection graph" onPointerMove={(event) => dragging && pointer(event)} onPointerUp={() => setDragging(false)} onPointerLeave={() => setDragging(false)}>
    <defs><pattern id="dom130-grid" width="47" height="49" patternUnits="userSpaceOnUse"><path d="M47 0H0V49" fill="none" stroke="#dbe5e9" strokeWidth="1" strokeDasharray="3 3" /></pattern><marker id="dom130-arrow-teal" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#079c9d" /></marker><marker id="dom130-arrow-blue" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#2563dd" /></marker></defs>
    <rect x="15" y="15" width="530" height="550" fill={grid ? "url(#dom130-grid)" : "#fff"} />
    <line x1="15" x2="542" y1={py(0)} y2={py(0)} className="axis" /><line x1={px(0)} x2={px(0)} y1="560" y2="16" className="axis" />
    {[-4,-3,-2,-1,0,1,2,3,4,5,6].map((x)=><text key={`x${x}`} x={px(x)} y={py(0)+20}>{x}</text>)}{[-5,-4,-3,-2,-1,1,2,3,4,5].map((y)=><text key={`y${y}`} x={px(0)-13} y={py(y)+4}>{y}</text>)}<text x="532" y={py(0)-10} className="xy">x</text><text x={px(0)+15} y="25" className="xy">y</text>
    <path d={path} className="curve" /><text x={px(3.5)} y={py(Math.sqrt(3.5+domainShift)+rangeShift)-22} className="curve-label">{formula(domainShift, rangeShift)}</text>
    <line x1={px(startX)} x2={px(startX)} y1={py(rangeShift)} y2="558" className="start-guide" />
    <line x1={px(startX)} x2="538" y1={py(rangeShift)+55} y2={py(rangeShift)+55} className="domain-ray" markerEnd="url(#dom130-arrow-teal)" /><circle cx={px(startX)} cy={py(rangeShift)+55} r="6" className="domain-dot" /><circle cx={px(0)-14} cy={py(rangeShift)+55} r="7" className="domain-dot" />
    <line x1={px(0)} x2={px(0)} y1="558" y2={py(rangeShift)+55} className="range-ray" markerEnd="url(#dom130-arrow-blue)" /><circle cx={px(0)} cy="558" r="7" className="range-dot" />
    <circle cx={px(startX)} cy={py(rangeShift)} r="8" className="start" role="slider" tabIndex={0} aria-label="Drag square root start point" aria-valuetext={`start ${startX}, ${rangeShift}`} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); setDragging(true); }} onKeyDown={(event) => { if (event.key === "ArrowLeft") onStartMove(Math.min(4,domainShift+1),rangeShift); if (event.key === "ArrowRight") onStartMove(Math.max(-4,domainShift-1),rangeShift); if (event.key === "ArrowUp") onStartMove(domainShift,Math.min(3,rangeShift+1)); if (event.key === "ArrowDown") onStartMove(domainShift,Math.max(-3,rangeShift-1)); }} />
    <g className="domain-label"><text x={px(.8)} y={py(rangeShift)+92}>Domain: x ≥ {clean(startX)}</text><text x={px(.8)} y={py(rangeShift)+115}>Interval: [{clean(startX)}, ∞)</text></g><g className="range-label"><text x={px(0)+26} y={py(-3.7)}>Range: y ≥ {clean(rangeShift)}</text><text x={px(0)+26} y={py(-4.15)}>Interval: [{clean(rangeShift)}, ∞)</text></g>
  </svg>;
}

export default function DomainRangeTargetLesson130({ resetToken, onInteraction }: LessonAdapterProps) {
  const [domainShift,setDomainShift]=useState(2), [rangeShift,setRangeShift]=useState(0), [grid,setGrid]=useState(true), [tab,setTab]=useState("Interaction + Visualization"), [language,setLanguage]=useState("English (English)"), [actions,setActions]=useState(0), [shared,setShared]=useState(false), [workspace,setWorkspace]=useState(false), [fullscreen,setFullscreen]=useState(false), [answer,setAnswer]=useState(false);
  const act=()=>{setActions((value)=>value+1);onInteraction();}; const startX=-domainShift; const domain=`[${clean(startX)}, ∞)`; const range=`[${clean(rangeShift)}, ∞)`;
  const reset=()=>{setDomainShift(2);setRangeShift(0);setGrid(true);setTab("Interaction + Visualization");setLanguage("English (English)");setActions(0);setShared(false);setWorkspace(false);setFullscreen(false);setAnswer(false);onInteraction();}; useEffect(()=>reset(),[resetToken]); // eslint-disable-line react-hooks/exhaustive-deps
  const updateStart=(d:number,r:number)=>{setDomainShift(d);setRangeShift(r);act();}; const evaluate=(x:number)=>x<startX?null:Math.sqrt(x+domainShift)+rangeShift;
  const examples=[startX,Math.max(startX,0),Math.max(startX,2)];
  return <div className={`dom130-page ${fullscreen?"fullscreen":""}`} data-testid="graph-mockup-0187" data-dedicated-lesson="130" data-object-model="editable-shifted-square-root-domain-range-projector-pointer-keyboard-draggable-closed-start-point-linked-axis-projections-generated-interval-notation-sample-evaluations-grid-practice-model" data-domain-shift={domainShift} data-range-shift={rangeShift} data-start={`${startX},${rangeShift}`} data-domain={domain} data-range={range} data-grid={grid} data-answer={answer} data-actions={actions} data-direct-interaction="true">
    <nav className="dom130-breadcrumb"><a href="/">⌂</a><a href="/">Home</a><span>&gt;</span><a href="/lessons">Lessons</a><span>&gt;</span><a href="/lessons/graphs-and-functions">Graphs And Functions</a><span>&gt;</span><b>130 Domain And Range</b></nav>
    <header className="dom130-intro"><small><b>GRAPHS AND FUNCTIONS</b><b>FUNCTIONS</b></small><h1>Domain and Range</h1><p>Identify permitted inputs and outputs.</p><nav><b>♙ Intermediate-Advanced</b><b>ϟ Graph Explorer</b><b>▣ Graphing Projector</b><b>◷ 6-10 min</b></nav><div><label><Languages/><select aria-label="Domain and range language" value={language} onChange={(event)=>{setLanguage(event.target.value);act();}}><option>English (English)</option><option>Hindi (हिन्दी)</option></select><ChevronDown/></label><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>{setShared(true);act();}}><Share2/>{shared?"Link ready":"Share"}</button><button onClick={()=>{setWorkspace((value)=>!value);act();}}>↗ {workspace?"Close workspace":"Workspace"}</button></div></header>
    <nav className="dom130-tabs">{["Interaction + Visualization","Explain","Examples","Formulas","Know More"].map((name)=><button key={name} className={tab===name?"active":""} onClick={()=>{setTab(name);if(name==="Examples"){setDomainShift(-3);setRangeShift(1);}act();}}>{name}</button>)}</nav>
    <section className="dom130-lab"><header><div><small>INTERACTION · PROJECTOR</small><h2>Domain–Range Projector</h2><p>Project f(x) onto the axes to read domain and range.</p></div><nav><label>Grid<input aria-label="Toggle projector grid" type="checkbox" checked={grid} onChange={(event)=>{setGrid(event.target.checked);act();}}/></label><button aria-label="Expand domain range projector" onClick={()=>{setFullscreen((value)=>!value);act();}}><Expand/></button></nav></header><div className="dom130-layout"><main><article className="dom130-rule"><span><b>Function</b><strong>{formula(domainShift,rangeShift)}</strong></span><span><b>Rule</b><strong>√(x {signedInside(domainShift)}) {signedOutside(rangeShift)}</strong></span></article><ProjectorGraph domainShift={domainShift} rangeShift={rangeShift} grid={grid} onStartMove={updateStart}/><article className="dom130-samples"><h3>Sample evaluations</h3><div>{examples.map((x,index)=><span key={`${x}-${index}`}><strong>f({clean(x)}) = √({clean(x)} {signedInside(domainShift)}) {signedOutside(rangeShift)}</strong><b>= {evaluate(x)===null?"undefined":resultText(evaluate(x)!)}</b></span>)}</div></article><footer><i/>The graph starts at ({clean(startX)}, {clean(rangeShift)}) and extends to the right. The closed endpoint is included.</footer></main>
      <aside className="dom130-rail"><section className="controls"><h3>Controls</h3><label>Domain shift <Info/><input aria-label="Domain shift" type="range" min="-5" max="5" step="1" value={domainShift} onChange={(event)=>{setDomainShift(Number(event.target.value));act();}}/><output>{domainShift}</output></label><label>Range shift <Info/><input aria-label="Range shift" type="range" min="-5" max="5" step="1" value={rangeShift} onChange={(event)=>{setRangeShift(Number(event.target.value));act();}}/><output>{rangeShift}</output></label><label>Rule <Info/><strong>{formula(domainShift,rangeShift)}</strong></label></section><section className="reasoning"><h3>Reasoning</h3>{[[LocateFixed,"Locate graph start",`Set x ${signedInside(domainShift)} = 0 → x = ${clean(startX)}. Start point is (${clean(startX)}, ${clean(rangeShift)}) (closed).`],[ArrowRight,"Read allowed x-values",`From the projection on the x-axis. Domain: x ≥ ${clean(startX)}.`],[ArrowRight,"Read possible y-values",`From the projection on the y-axis. Range: y ≥ ${clean(rangeShift)}.`],[Check,"Use closed endpoint",`The starting point (${clean(startX)}, ${clean(rangeShift)}) is included in the graph.`]].map(([Icon,title,text])=><p key={String(title)}><Icon/><span><b>{String(title)}</b><small>{String(text)}</small></span></p>)}</section><section className="warning"><TriangleAlert/><div><b>Check your understanding</b><h3>DOMAIN_RANGE_SWAPPED</h3><p>Remember: Domain is x-values (inputs) and Range is y-values (outputs).</p></div></section><section className="practice"><h3>Try another</h3><p>Consider g(x) = √(x − 3) + 1.</p><p>What are its domain and range?</p><button onClick={()=>{setAnswer((value)=>!value);act();}}>{answer?"Hide derivation":"Show answer"}</button><article><b>Domain: x ≥ 3<br/>Interval: [3, ∞)</b><strong>Range: y ≥ 1<br/>Interval: [1, ∞)</strong>{answer&&<small>Set x − 3 = 0. The closed start is (3, 1).</small>}</article></section></aside></div></section>
    <nav className="dom130-adjacent"><a href="/lessons/graphs-and-functions/129-function-concept"><ArrowLeft/><span><small>PREVIOUS</small>Function Concept</span></a><a href="/lessons/graphs-and-functions/131-function-notation"><span><small>NEXT</small>Function Notation</span><ArrowRight/></a></nav><footer className="dom130-footer"><b><Sparkles/>Math Universe</b><span>Interactive math labs, visual proofs, NCERT explorations, graphing, CAS-style tools, and classroom-ready activities.</span><nav><button>Sitemap</button><button>Docs</button><button>About</button></nav><hr/><small>© 2026 INDIAN SERVERS PRIVATE LIMITED. NO RIGHT TO REPRODUCE IT.</small><small>www.IndianServers.com info@IndianServers.com</small></footer>
  </div>;
}
