import { useMemo, useState } from "react";
import { BarChart3, CheckCircle2, Eraser, RotateCcw, Shuffle, SortAsc, Trophy } from "lucide-react";
import type { LessonAdapterProps } from "../types";
import { challengeData, defaultFrequencyData, frequencyRows, meanOf, medianOf, modeOf, rangeOf, relativeTotal, repairedChallenge, type FrequencyRow } from "./frequencyTablesModel";
import "./FrequencyTablesLesson468.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

export default function FrequencyTablesLesson468({ resetToken, onInteraction }: LessonAdapterProps) {
  return <FrequencyTablesActivity key={resetToken} onInteraction={onInteraction} />;
}
function fmt(value: number | null, digits = 2) { return value === null ? "-" : Number.isInteger(value) ? String(value) : value.toFixed(digits); }
function tally(value: number) { return value ? "|||||".repeat(Math.floor(value / 5)) + "|".repeat(value % 5) : ""; }
function MiniBarChart({ rows }: { rows: FrequencyRow[] }) {
  const max = Math.max(1, ...rows.map(row => row.frequency));
  return <svg className="ft468-chart" viewBox="0 0 480 250" role="img" aria-label="Frequency bar chart">
    <path d="M44 18V210H462" fill="none" stroke="#70839a" strokeWidth="2" />
    {rows.map((row, index) => { const height = row.frequency / max * 160; return <g key={row.value}><rect x={60 + index * (390 / Math.max(1, rows.length))} y={210 - height} width={Math.max(12, 260 / Math.max(1, rows.length))} height={height} fill={row.frequency === max ? "#08a7cf" : "#a5d9e7"} /><text x={69 + index * (390 / Math.max(1, rows.length))} y={202 - height} textAnchor="middle" className="ft468-bar-label">{row.frequency}</text><text x={69 + index * (390 / Math.max(1, rows.length))} y="230" textAnchor="middle" className="ft468-axis-label">{row.value}</text></g>; })}
    <text x="14" y="125" transform="rotate(-90 14 125)" className="ft468-axis-label">Frequency (f)</text><text x="250" y="248" textAnchor="middle" className="ft468-axis-label">Value (x)</text>
  </svg>;
}
function FrequencyTable({ rows, total, editable = false, values, onChange }: { rows: FrequencyRow[]; total: number; editable?: boolean; values?: Record<number, number>; onChange?: (value: number, count: number) => void }) {
  return <table className="ft468-table"><thead><tr><th>Value (x)</th><th>Tally</th><th>Frequency (f)</th><th>Relative freq. (f/n)</th></tr></thead><tbody>{rows.map(row => <tr key={row.value}><td>{row.value}</td><td className="ft468-tally">{editable ? <input aria-label={`Tally for ${row.value}`} value={values?.[row.value] ?? ""} onChange={event => onChange?.(row.value, Number(event.target.value) || 0)} inputMode="numeric" /> : row.tally}</td><td>{editable ? <input aria-label={`Frequency for ${row.value}`} value={values?.[row.value] ?? ""} onChange={event => onChange?.(row.value, Number(event.target.value) || 0)} inputMode="numeric" /> : row.frequency}</td><td>{total ? `${row.frequency}/${total} = ${row.relative.toFixed(3)}` : "0.000"}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th className="ft468-tally">{tally(total)}</th><th>{total}</th><th>{total ? "1.000" : "0.000"}</th></tr></tfoot></table>;
}
function FrequencyTablesActivity({ onInteraction }: Pick<LessonAdapterProps, "onInteraction">) {
  const [data, setData] = useState(defaultFrequencyData);
  const [challenge, setChallenge] = useState<Record<number, number>>({});
  const [challengeChecked, setChallengeChecked] = useState(false);
  const rows = useMemo(() => frequencyRows(data), [data]);
  const challengeRows = useMemo(() => frequencyRows(challengeData), []);
  const updateValue = (index: number, value: string) => { const next = [...data]; if (value === "") next.splice(index, 1); else next[index] = Math.max(0, Math.min(99, Number(value) || 0)); setData(next); onInteraction(); };
  function sortData(order: "value" | "frequency") { setData([...data].sort((a, b) => order === "value" ? a - b : (rows.find(row => row.value === b)?.frequency ?? 0) - (rows.find(row => row.value === a)?.frequency ?? 0))); onInteraction(); }
  return <div className="ft468" data-testid="statistics-mockup-0431" data-target-family="statistics-and-regression">
    <section className="ft468-interact"><header className="ft468-heading"><div><span className="ft468-eyebrow">Interact</span><h2>Your data, your counts</h2><p>Edit the dataset below. Counts, relative frequencies and the chart update automatically.</p></div><span className="ft468-total"><CheckCircle2 size={16} /> Total (n) = {data.length}</span></header>
      <div className="ft468-main"><section className="ft468-data"><h3>Editable dataset</h3><div className="ft468-values">{data.map((value, index) => <input key={`${index}-${value}`} aria-label={`Data value ${index + 1}`} value={value} onChange={event => updateValue(index, event.target.value)} inputMode="numeric" />)}</div><FrequencyTable rows={rows} total={data.length} /><div className="ft468-actions"><button type="button" onClick={() => sortData("value")}><SortAsc size={14} /> Sort A-Z</button><button type="button" onClick={() => sortData("frequency")}><BarChart3 size={14} /> Sort by freq.</button><button type="button" onClick={() => { setData([]); onInteraction(); }}><Eraser size={14} /> Clear data</button><button type="button" onClick={() => { setData([...defaultFrequencyData].sort(() => Math.random() - .5)); onInteraction(); }}><Shuffle size={14} /> Randomise</button></div><p className="ft468-tip">Tip: Edit any number above. Tally, frequencies and the chart update automatically.</p></section>
        <section className="ft468-visual"><h3>Frequency (bar chart)</h3><MiniBarChart rows={rows} /><div className="ft468-stats"><strong>Quick stats</strong><div><span>Mode<b>{fmt(modeOf(rows), 0)}</b></span><span>Median<b>{fmt(medianOf(data))}</b></span><span>Range<b>{fmt(rangeOf(data), 0)}</b></span><span>Mean<b>{fmt(meanOf(data))}</b></span></div></div><div className="ft468-legend"><i className="ft468-most" /> Most frequent (mode) <i className="ft468-least" /> Least frequent</div></section></div>
      <p className="ft468-integrity"><CheckCircle2 size={15} /> Totals check out <b>Σf = {data.length}</b> <b>Σ(f/n) = {data.length ? relativeTotal(rows).toFixed(2) : "0.00"}</b></p>
    </section>
    <div className="ft468-study"><section><span className="ft468-eyebrow">Learn</span><h3>Definition</h3><p>A frequency table summarises how often each value or category appears in a dataset.</p><h4>Key terms</h4><p><b>Frequency (f):</b> number of times a value occurs.</p><p><b>Relative frequency (f/n):</b> proportion of the total.</p></section><section><span className="ft468-eyebrow ft468-warning">Misconception guard</span><h3>Relative frequency is not the same as frequency.</h3><p>If n = 20, then f = 4 does not mean f/n = 4. It is f/n = 4/20 = 0.20.</p></section><section><span className="ft468-eyebrow">Why this matters</span><h3>Read patterns quickly</h3><p>Frequency tables help you compare groups and summarise data for decisions.</p></section></div>
    <section className="ft468-example"><div><span className="ft468-eyebrow">Worked example</span><h3>A survey of 15 students</h3><p>How many hours of sleep did the students report?</p><p className="ft468-chip">5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 11, 11</p><p>Which sleep duration is most common?</p></div><FrequencyTable rows={frequencyRows([5, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10, 11])} total={15} /><aside><CheckCircle2 size={16} /><b>Answer</b><p>Most common (mode):<br /><strong>8 hours</strong></p><p>Σf = 15 ✓<br />Σ(f/15) = 1.000 ✓</p></aside></section>
    <section className="ft468-challenge"><header><div><span className="ft468-eyebrow ft468-warning">Challenge: Spot and repair the miscount</span><h3>The table below contains mistakes. Find and fix them so that totals are correct.</h3><p className="ft468-chip">2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 6, 7</p><p>(n = 15)</p></div><button type="button" className="ft468-check" onClick={() => { setChallengeChecked(true); onInteraction(); }}><Trophy size={16} /> Check my fix</button></header><div className="ft468-repair"><div><h4>Incorrect table</h4><FrequencyTable rows={challengeRows} total={15} /></div><div><h4>Repair the frequencies</h4><FrequencyTable rows={challengeRows} total={Object.values(challenge).reduce((sum, value) => sum + value, 0)} editable values={challenge} onChange={(value, count) => { setChallenge(state => ({ ...state, [value]: count })); setChallengeChecked(false); onInteraction(); }} /></div></div><div className={challengeChecked && repairedChallenge(challengeData, challenge) ? "ft468-repair-success" : "ft468-repair-status"}>{challengeChecked ? repairedChallenge(challengeData, challenge) ? "All tallies correct. Σf = 15 and Σ(f/n) = 1.000." : "Review the counts: each frequency must match the raw observations." : "Enter every frequency, then check your fix."}</div></section>
    <div className="ft468-bottom"><button type="button" onClick={() => { setData(defaultFrequencyData); setChallenge({}); setChallengeChecked(false); onInteraction(); }}><RotateCcw size={15} /> Reset lesson</button><span>Next: Grouped Frequency Tables →</span></div>
      <LessonTopicStudyBoard lessonId={468} alwaysVisible onInteraction={onInteraction} />

  </div>;
}
