import { useEffect, useRef, useState, type PointerEvent } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Expand, Info, Languages, Minus, Plus, RotateCcw, Share2, Sparkles, TriangleAlert } from "lucide-react";
import type { LessonAdapterProps } from "../types";
import "./FunctionNotationTargetLesson131.css";
import "./FunctionNotationTargetLesson131Tuning.css";

const clean=(value:number)=>Number.isInteger(value)?String(value):value.toFixed(2).replace(/0+$/,"").replace(/\.$/,"");
const signed=(value:number)=>value<0?`− ${clean(Math.abs(value))}`:`+ ${clean(value)}`;
const rule=(a:number,k:number,name="f")=>`${name}(x) = ${a===1?"":a===-1?"−":clean(a)}x² ${signed(k)}`;

function NotationGraph({a,k,input,onInput}:{a:number;k:number;input:number;onInput:(value:number)=>void}){
  const svg=useRef<SVGSVGElement>(null);const [dragging,setDragging]=useState(false);const px=(x:number)=>200+x*42,py=(y:number)=>318-y*32;
  const move=(event:PointerEvent<SVGSVGElement>)=>{const box=svg.current?.getBoundingClientRect();if(!box)return;const x=Math.max(-4,Math.min(4,Math.round(((((event.clientX-box.left)/box.width)*400)-200)/42)));onInput(x);};
  const path=Array.from({length:121},(_,index)=>{const x=-3+index*.05;return`${index?"L":"M"}${px(x)},${py(a*x*x+k)}`;}).join(" "),output=a*input*input+k;
  return <svg ref={svg} className="note131-graph" viewBox="0 0 400 430" preserveAspectRatio="none" role="img" aria-label="Function notation parabola" onPointerMove={(event)=>dragging&&move(event)} onPointerUp={()=>setDragging(false)} onPointerLeave={()=>setDragging(false)}><defs><pattern id="note131-grid" width="42" height="32" patternUnits="userSpaceOnUse"><path d="M42 0H0V32" fill="none" stroke="#e1e9ee" strokeWidth="1"/></pattern><clipPath id="note131-plot-clip"><rect x="12" y="16" width="376" height="390"/></clipPath></defs><rect x="12" y="16" width="376" height="390" fill="url(#note131-grid)"/><line x1="12" x2="388" y1={py(0)} y2={py(0)} className="axis"/><line x1={px(0)} x2={px(0)} y1="405" y2="16" className="axis"/>{[-4,-3,-2,-1,0,1,2,3,4].map(x=><text key={`x${x}`} x={px(x)} y={py(0)+20}>{x}</text>)}{[-1,1,2,3,4,5,6,7].map(y=><text key={`y${y}`} x={px(0)-13} y={py(y)+4}>{y}</text>)}<text x="383" y={py(0)-9} className="xy">x</text><text x={px(0)+13} y="25" className="xy">y</text><path d={path} className="curve" clipPath="url(#note131-plot-clip)"/><circle cx={px(input)} cy={py(output)} r="8" className="chosen" role="slider" tabIndex={0} aria-label="Drag chosen function input" aria-valuemin={-4} aria-valuemax={4} aria-valuenow={input} onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);setDragging(true);}} onKeyDown={(event)=>{if(event.key==="ArrowLeft")onInput(Math.max(-4,input-1));if(event.key==="ArrowRight")onInput(Math.min(4,input+1));}}/><g className="point-label"><rect x={px(input)+12} y={py(output)-22} width="65" height="38" rx="8"/><text x={px(input)+44} y={py(output)+2}>({input}, {clean(output)})</text></g><g className="legend"><rect x="24" y="365" width="134" height="36" rx="7"/><line x1="38" x2="67" y1="383" y2="383" className="curve"/><text x="76" y="387">{rule(a,k)}</text></g></svg>;
}

export default function FunctionNotationTargetLesson131({resetToken,onInteraction}:LessonAdapterProps){
  const [a,setA]=useState(1),[k,setK]=useState(1),[input,setInput]=useState(2),[tab,setTab]=useState("Interaction + visualization"),[language,setLanguage]=useState("English (English)"),[actions,setActions]=useState(0),[shared,setShared]=useState(false),[workspace,setWorkspace]=useState(false),[fullscreen,setFullscreen]=useState(false),[learn,setLearn]=useState(false),[practiceInput,setPracticeInput]=useState(5),[practiceChecked,setPracticeChecked]=useState(true);const output=a*input*input+k,practiceOutput=3*practiceInput-4;
  const act=()=>{setActions(value=>value+1);onInteraction();};const reset=()=>{setA(1);setK(1);setInput(2);setTab("Interaction + visualization");setLanguage("English (English)");setActions(0);setShared(false);setWorkspace(false);setFullscreen(false);setLearn(false);setPracticeInput(5);setPracticeChecked(true);onInteraction();};useEffect(()=>reset(),[resetToken]); // eslint-disable-line react-hooks/exhaustive-deps
  const changeInput=(value:number)=>{setInput(value);act();};const sampleInputs=Array.from(new Set([-2,0,input]));
  return <div className={`note131-page ${fullscreen?"fullscreen":""}`} data-testid="graph-mockup-0188" data-dedicated-lesson="131" data-object-model="editable-quadratic-function-notation-decoder-coefficient-shift-pointer-keyboard-draggable-chosen-input-linked-substitution-output-parabola-sample-table-ordered-pair-not-multiplication-practice-model" data-a={a} data-k={k} data-input={input} data-output={output} data-point={`${input},${output}`} data-practice={`${practiceInput},${practiceOutput},${practiceChecked}`} data-actions={actions} data-direct-interaction="true">
    <nav className="note131-breadcrumb"><a href="/">←</a><a href="/">Home</a><span>&gt;</span><a href="/lessons">Lessons</a><span>&gt;</span><a href="/lessons/graphs-and-functions">Graphs And Functions</a><span>&gt;</span><b>131 Function Notation</b></nav><header className="note131-intro"><small><b>GRAPHS AND FUNCTIONS</b><b>FUNCTIONS</b></small><h1>Function Notation</h1><p>Interpret f(x).</p><nav><b>♙ Intermediate-Advanced</b><b>ϟ Graph Explorer</b><b>▣ Graphing Calculator</b><b>◷ 6-10 min</b></nav><div><label><Languages/><select aria-label="Function notation language" value={language} onChange={(event)=>{setLanguage(event.target.value);act();}}><option>English (English)</option><option>Hindi (हिन्दी)</option></select><ChevronDown/></label><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>{setShared(true);act();}}><Share2/>{shared?"Link ready":"Share"}</button><button onClick={()=>{setWorkspace(value=>!value);act();}}>↗ {workspace?"Close workspace":"Workspace"}</button></div></header>
    <nav className="note131-tabs">{["Interaction + visualization","Explain","Examples","Formulas","Know more"].map(name=><button key={name} className={tab===name?"active":""} onClick={()=>{setTab(name);if(name==="Examples"){setA(2);setK(-1);setInput(3);}act();}}>{name}</button>)}</nav>
    <section className="note131-lab"><header><div><small>INTERACTION + VISUALIZATION</small><h2>Notation decoder for <i>{rule(a,k)}</i></h2></div><nav><b>Interactive</b><span>{actions} actions</span><button aria-label="Expand notation decoder" onClick={()=>{setFullscreen(value=>!value);act();}}><Expand/></button></nav></header><section className="note131-decoder"><article><h3><i>1</i>Notation</h3><strong>f({input})</strong><p>means use input <em>x = {input}</em><br/>in the rule <em>{rule(a,k)}</em>.</p></article><b>→</b><article><h3><i>2</i>Substitute into the rule</h3><strong>f({input}) = {clean(a)}({input})² {signed(k)}<br/>= {clean(a*input*input)} {signed(k)}<br/>= <em>{clean(output)}</em></strong></article><b>→</b><article><h3><i>3</i>Output</h3><strong>f({input}) = <em>{clean(output)}</em></strong><p>So the output is <em>{clean(output)}</em>.<br/>Point on graph: <em>({input}, {clean(output)})</em></p></article></section>
      <div className="note131-middle"><section className="note131-visual"><article className="note131-plot"><h3>Graph of <i>{rule(a,k)}</i></h3><NotationGraph a={a} k={k} input={input} onInput={changeInput}/></article><article className="note131-table"><h3>Some sample values</h3><table><thead><tr><th>x</th><th>{rule(a,k)}</th><th>Ordered pair<br/>(x, f(x))</th></tr></thead><tbody>{sampleInputs.map(x=>{const y=a*x*x+k;return <tr key={x} className={x===input?"active":""}><td>{x}</td><td>{clean(y)}</td><td>({x}, {clean(y)})</td></tr>;})}</tbody></table></article></section><aside className="note131-rail"><section><h3>Graph parameters <Info/></h3><label>coefficient (a)<input aria-label="Function notation coefficient" type="range" min="-5" max="5" step="1" value={a} onChange={(event)=>{setA(Number(event.target.value));act();}}/><output>{a}</output></label><label>vertical shift (k)<input aria-label="Function notation vertical shift" type="range" min="-5" max="5" step="1" value={k} onChange={(event)=>{setK(Number(event.target.value));act();}}/><output>{k}</output></label><label>chosen input (x)<span><button aria-label="Decrease chosen input" onClick={()=>changeInput(Math.max(-4,input-1))}><Minus/></button><output>{input}</output><button aria-label="Increase chosen input" onClick={()=>changeInput(Math.min(4,input+1))}><Plus/></button></span><b>x = {input}</b></label></section><section><h3>Quick reasoning</h3>{[["Name the rule",rule(a,k)],["Choose the input",`x = ${input}`],["Substitute x",`f(${input}) = ${clean(a)}(${input})² ${signed(k)}`],["Read the output",`f(${input}) = ${clean(output)}`]].map((item,index)=><p key={item[0]}><i>{index+1}</i><b>{item[0]}</b><span>{item[1]}</span></p>)}</section></aside></div>
      <div className="note131-lower"><article className="warning"><TriangleAlert/><div><h3>NOT_MULTIPLICATION</h3><p>f({input}) does <b>not</b> mean f times {input}.<br/>It means the function value at x = {input}.<br/>Always substitute the input into the rule.</p><button onClick={()=>{setLearn(value=>!value);act();}}>{learn?"Hide note":"Learn more"}</button>{learn&&<small>Parentheses hold the input supplied to the function.</small>}</div></article><article className="practice"><Check/><div><h3>Try another: Practice check</h3><p>Let g(x) = 3x − 4.<br/>Find g(<input aria-label="Function notation practice input" type="number" min="-9" max="9" value={practiceInput} onChange={(event)=>{setPracticeInput(Number(event.target.value));setPracticeChecked(false);act();}}/>).</p><strong>g({practiceInput}) = 3({practiceInput}) − 4<br/>= {3*practiceInput} − 4<br/>= {practiceOutput}</strong></div><aside><b>Answer</b><button onClick={()=>{setPracticeChecked(true);act();}}>g({practiceInput}) = {practiceOutput} {practiceChecked&&<Check/>}</button><p>Point on graph would be ({practiceInput}, {practiceOutput}).</p></aside></article></div></section>
    <nav className="note131-adjacent"><a href="/lessons/graphs-and-functions/130-domain-and-range"><ArrowLeft/><span><small>PREVIOUS</small>Domain and Range</span></a><a href="/lessons/graphs-and-functions/132-vertical-line-test"><span><small>NEXT</small>Vertical-Line Test</span><ArrowRight/></a></nav><footer className="note131-footer"><b><Sparkles/>Math Universe</b><span>Interactive math labs, visual proofs, NCERT explorations, graphing, CAS-style tools, and classroom-ready activities.</span><nav><button>Sitemap</button><button>Docs</button><button>About</button></nav><hr/><small>© 2026 INDIAN SERVERS PRIVATE LIMITED. NO RIGHT TO REPRODUCE IT.</small><small>www.IndianServers.com info@IndianServers.com</small></footer>
  </div>;
}
