import { useEffect, useMemo, useState } from "react";
import SliderControl, { SliderGroup } from "../../../components/ui/SliderControl";
import { oneProportionZTest, simulateConfidenceIntervals, simulateSamplingDistribution } from "../../../utils/mathEngine/probabilityUtils";
import AdapterFrame from "../components/AdapterFrame";
import type { LessonAdapterProps } from "../types";

export default function InferenceLessonAdapter({ lesson, resetToken, onInteraction }: LessonAdapterProps) {
  const seed = lesson.id * 65537 + 31; const [sampleSize, setSampleSize] = useState(30); const [successes, setSuccesses] = useState(18); const [confidence, setConfidence] = useState(95);
  useEffect(() => { setSampleSize(30); setSuccesses(18); setConfidence(95); }, [resetToken]);
  const intervals = useMemo(() => simulateConfidenceIntervals(30, sampleSize, confidence / 100, seed), [confidence, sampleSize, seed]);
  const sampling = useMemo(() => simulateSamplingDistribution(300, sampleSize, seed), [sampleSize, seed]);
  const test = useMemo(() => oneProportionZTest(Math.min(successes, sampleSize), sampleSize, .5), [sampleSize, successes]);
  const isTest = /test|null|p-value|error|power|significance/i.test(lesson.title);
  const maxBin = Math.max(...sampling.histogram.map((bin) => bin.count), 1);
  const update = (setter: (value: number) => void) => (value: number) => { setter(value); onInteraction(); };
  return <AdapterFrame title={`${lesson.title} · inference lab`} value={isTest ? `p = ${test.pValue.toFixed(4)}` : `capture ${(intervals.captureRate * 100).toFixed(1)}%`} footer={`All repeated samples use deterministic seed ${seed}; sample size controls both standard error and interval width.`}>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_290px]"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900">{isTest ? <TestView z={test.z} reject={test.reject} /> : <IntervalView intervals={intervals.intervals} />}<div className="mt-3 flex h-28 items-end gap-1" aria-label="Sampling distribution">{sampling.histogram.map((bin) => <div key={bin.label} className="flex-1 rounded-t bg-cyan-500" style={{ height: `${Math.max(4, bin.count / maxBin * 105)}px` }} title={`${bin.label}: ${bin.count}`} />)}</div></div><div className="space-y-3"><SliderGroup title="Study design"><SliderControl density="compact" label="Sample size" value={sampleSize} min={10} max={100} step={5} onChange={(value) => { setSampleSize(value); setSuccesses((current) => Math.min(current, value)); onInteraction(); }} /><SliderControl density="compact" label="Successes" value={successes} min={0} max={sampleSize} step={1} onChange={update(setSuccesses)} /><SliderControl density="compact" label="Confidence" value={confidence} min={90} max={99} step={1} unit="%" onChange={update(setConfidence)} /></SliderGroup><div className="grid grid-cols-2 gap-2"><Metric label="Mean of means" value={sampling.meanOfMeans.toFixed(3)} /><Metric label="Std. error" value={sampling.standardError.toFixed(3)} /><Metric label="z statistic" value={test.z.toFixed(3)} /><Metric label="Decision" value={test.reject ? "Reject H₀" : "Keep H₀"} /></div></div></div>
  </AdapterFrame>;
}

function IntervalView({ intervals }: { intervals: Array<{ index: number; mean: number; lower: number; upper: number; captures: boolean }> }) { const sx = (value: number) => 40 + (value - 2) / 3 * 560; return <svg viewBox="0 0 640 260" className="h-[230px] w-full" role="img" aria-label="Confidence interval capture simulation"><line x1={sx(3.5)} x2={sx(3.5)} y1="10" y2="245" stroke="#f59e0b" strokeWidth="3" />{intervals.slice(0, 20).map((item, index) => <g key={item.index}><line x1={sx(item.lower)} x2={sx(item.upper)} y1={18 + index * 11} y2={18 + index * 11} stroke={item.captures ? "#0891b2" : "#ef4444"} strokeWidth="3" /><circle cx={sx(item.mean)} cy={18 + index * 11} r="3" fill={item.captures ? "#0891b2" : "#ef4444"} /></g>)}</svg>; }
function TestView({ z, reject }: { z: number; reject: boolean }) { const x = 320 + Math.max(-3, Math.min(3, z)) / 3 * 270; return <svg viewBox="0 0 640 260" className="h-[230px] w-full" role="img" aria-label="Hypothesis test rejection region"><path d="M40 220 C160 220 190 45 320 45 C450 45 480 220 600 220" fill="none" stroke="#06b6d4" strokeWidth="4" /><rect x="40" y="210" width="105" height="20" fill="#ef4444" opacity=".25" /><rect x="495" y="210" width="105" height="20" fill="#ef4444" opacity=".25" /><line x1={x} x2={x} y1="35" y2="225" stroke={reject ? "#ef4444" : "#f59e0b"} strokeWidth="4" /><text x={x} y="28" textAnchor="middle" fontWeight="800" fill="#334155">z={z.toFixed(2)}</text></svg>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-100 p-2 text-center dark:bg-white/10"><span className="block text-[10px] font-bold text-slate-500">{label}</span><strong className="text-xs">{value}</strong></div>; }
