import { ArrowLeft, ArrowRight, Check, ChevronLeft, RotateCcw, Trophy } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type React from "react";
import type { LessonAdapterProps } from "../types";
import "./ParentFunctionLibraryTargetLesson165.css";

type FamilyId = "linear" | "quadratic" | "absolute" | "root" | "cubic" | "reciprocal";
type Family = { id: FamilyId; name: string; formula: string; color: string; domain: string; range: string; description: string; patterns: string[]; rule: string; evaluate: (x:number)=>number|null };
const families: Family[] = [
  {id:"linear",name:"Linear",formula:"f(x) = x",color:"#1677ff",domain:"(-∞, ∞)",range:"(-∞, ∞)",description:"Linear functions form straight lines.",patterns:["Constant rate of change (slope).","No turning points.","Extends infinitely in both directions."],rule:"g(x) = mx + b",evaluate:x=>x},
  {id:"quadratic",name:"Quadratic",formula:"f(x) = x²",color:"#8b45ef",domain:"(-∞, ∞)",range:"[0, ∞)",description:"Quadratic functions form parabolas.",patterns:["One turning point called the vertex.","Symmetric about the y-axis.","Outputs are never negative."],rule:"g(x) = a(x - h)² + k",evaluate:x=>x*x},
  {id:"absolute",name:"Absolute Value",formula:"f(x) = |x|",color:"#ff4775",domain:"(-∞, ∞)",range:"[0, ∞)",description:"Absolute-value functions form V-shapes.",patterns:["Two linear rays meet at a vertex.","Symmetric about the y-axis.","Distance from zero controls output."],rule:"g(x) = a|x - h| + k",evaluate:x=>Math.abs(x)},
  {id:"root",name:"Square Root",formula:"f(x) = √x",color:"#ff8a00",domain:"[0, ∞)",range:"[0, ∞)",description:"Square-root functions begin at an endpoint.",patterns:["Starts at the origin.","Increases while flattening.","Only nonnegative inputs are allowed."],rule:"g(x) = a√(x - h) + k",evaluate:x=>x<0?null:Math.sqrt(x)},
  {id:"cubic",name:"Cubic",formula:"f(x) = x³",color:"#20af55",domain:"(-∞, ∞)",range:"(-∞, ∞)",description:"Cubic functions form smooth S-curves.",patterns:["Passes through the origin.","Has rotational symmetry.","Extends infinitely in both directions."],rule:"g(x) = a(x - h)³ + k",evaluate:x=>x*x*x},
  {id:"reciprocal",name:"Reciprocal",formula:"f(x) = 1/x",color:"#2e71ff",domain:"(-∞, 0) ∪ (0, ∞)",range:"(-∞, 0) ∪ (0, ∞)",description:"Reciprocal functions form two branches.",patterns:["Undefined at x = 0.","Approaches both axes asymptotically.","Opposite-sign inputs give opposite outputs."],rule:"g(x) = a/[b(x-h)] + k",evaluate:x=>Math.abs(x)<1e-8?null:1/x},
];
const initial={a:1,b:1,k:0,h:0}; const clamp=(n:number,min:number,max:number)=>Math.min(max,Math.max(min,n)); const snap=(n:number)=>Math.round(n*2)/2; const fmt=(n:number)=>Number.isInteger(n)?String(n):n.toFixed(1);

function MiniIcon({family}:{family:Family}){return <svg viewBox="0 0 45 34" aria-hidden="true"><path d={family.id==="linear"?"M3 31L41 3":family.id==="quadratic"?"M3 3Q22 61 41 3":family.id==="absolute"?"M3 3L22 31L41 3":family.id==="root"?"M3 31Q4 7 41 3":family.id==="cubic"?"M5 31C17 31 15 3 27 3S31 1 40 0":"M3 3Q21 4 21 17M24 18Q24 31 42 31"} fill="none" stroke={family.color} strokeWidth="2"/></svg>}

function LibraryGraph({family,model,onShift}:{family:Family;model:typeof initial;onShift:(h:number,k:number)=>void}){
  const ref=useRef<SVGSVGElement>(null),W=380,H=380,ox=190,oy=190,u=29;
  const transformed=(x:number)=>{const value=family.evaluate(model.b*(x-model.h));return value===null?null:model.a*value+model.k};
  const makePath=(fn:(x:number)=>number|null)=>{let pen=false;return Array.from({length:321},(_,i)=>-6.4+i*12.8/320).map(x=>{const y=fn(x),visible=y!==null&&Number.isFinite(y)&&Math.abs(y)<8;if(!visible){pen=false;return ""}const cmd=pen?"L":"M";pen=true;return `${cmd}${(ox+x*u).toFixed(1)} ${(oy-y!*u).toFixed(1)}`}).join(" ")};
  const move=(e:React.PointerEvent<SVGCircleElement>)=>{const box=ref.current?.getBoundingClientRect();if(!box)return;onShift(snap(clamp(((e.clientX-box.left)/box.width*W-ox)/u,-5,5)),snap(clamp((oy-(e.clientY-box.top)/box.height*H)/u,-5,5)))};
  return <svg ref={ref} viewBox={`0 0 ${W} ${H}`} className="pfl165-graph" role="img" aria-label={`${family.name} parent and transformed graph`}><defs><pattern id="pfl165-grid" width={u} height={u} patternUnits="userSpaceOnUse"><path d={`M${u} 0H0V${u}`} fill="none" stroke="#dce5ed"/></pattern><marker id="pfl165-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#17233f"/></marker></defs><rect width={W} height={H} fill="url(#pfl165-grid)"/><line x1="3" x2={W-4} y1={oy} y2={oy} className="axis" markerEnd="url(#pfl165-arrow)"/><line x1={ox} x2={ox} y1={H-3} y2="4" className="axis" markerEnd="url(#pfl165-arrow)"/>{[-6,-5,-4,-3,-2,-1,1,2,3,4,5,6].map(n=><text key={`x${n}`} x={ox+n*u} y={oy+17}>{n}</text>)}{[-6,-5,-4,-3,-2,-1,1,2,3,4,5,6].map(n=><text key={`y${n}`} x={ox-8} y={oy-n*u+3} textAnchor="end">{n}</text>)}<text x={W-7} y={oy-8}>x</text><text x={ox+8} y="12">y</text><path d={makePath(family.evaluate)} className="parent" style={{stroke:family.color}}/><path d={makePath(transformed)} className="transformed"/>{[-4,-3,-2,-1,0,1,2,3,4].map(x=>{const y=transformed(x);return y!==null&&Math.abs(y)<=6?<circle key={x} cx={ox+x*u} cy={oy-y*u} r="3.5" className="sample"/>:null})}<circle data-testid="parent-library-anchor" role="slider" tabIndex={0} aria-label="Drag transformed family anchor" aria-valuetext={`(${fmt(model.h)}, ${fmt(model.k)})`} cx={ox+model.h*u} cy={oy-model.k*u} r="13" className="handle" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))move(e)}} onKeyDown={e=>{const d=e.shiftKey?1:.5;if(e.key==="ArrowLeft")onShift(clamp(model.h-d,-5,5),model.k);if(e.key==="ArrowRight")onShift(clamp(model.h+d,-5,5),model.k);if(e.key==="ArrowUp")onShift(model.h,clamp(model.k+d,-5,5));if(e.key==="ArrowDown")onShift(model.h,clamp(model.k-d,-5,5));}}/></svg>
}

function Control({symbol,label,min,max,value,onChange}:{symbol:string;label:string;min:number;max:number;value:number;onChange:(n:number)=>void}){return <label><span>{label}: <b>{symbol}</b></span><div><input aria-label={`${label} ${symbol}`} type="range" min={min} max={max} step="0.5" value={value} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={`${symbol} value`} type="number" min={min} max={max} step="0.5" value={value} onChange={e=>onChange(clamp(Number(e.target.value),min,max))}/></div></label>}

export default function ParentFunctionLibraryTargetLesson165({resetToken,onInteraction}:LessonAdapterProps){
  const [familyId,setFamilyId]=useState<FamilyId>("linear"),[model,setModelState]=useState(initial),[tab,setTab]=useState("Explore"),[gallery,setGallery]=useState(true),[question,setQuestion]=useState(0),[answer,setAnswer]=useState<FamilyId|null>(null),[status,setStatus]=useState("");
  const family=families.find(item=>item.id===familyId)!; const practiceIds:FamilyId[]=["quadratic","absolute","reciprocal"]; const practiceFamily=families.find(item=>item.id===practiceIds[question])!;
  const setModel=(next:typeof initial)=>{setModelState(next);onInteraction()}; const selectFamily=(id:FamilyId)=>{setFamilyId(id);setModelState(initial);onInteraction()};
  useEffect(()=>{setFamilyId("linear");setModelState(initial);setTab("Explore");setGallery(true);setQuestion(0);setAnswer(null);setStatus("")},[resetToken]);
  const keyXs=family.id==="root"?[0,1,4,9,16]:family.id==="reciprocal"?[-2,-1,-.5,.5,1]:[-2,-1,0,1,2];
  const equation=useMemo(()=>`g(x) = ${fmt(model.a)} · f(${fmt(model.b)}(x ${model.h>=0?"-":"+"} ${fmt(Math.abs(model.h))})) ${model.k>=0?"+":"-"} ${fmt(Math.abs(model.k))}`,[model]);
  return <main className="pfl165-page" data-testid="graph-mockup-0222" data-dedicated-lesson="165" data-object-model="six-explicit-parent-function-definitions-selectable-generated-domain-range-pattern-rules-key-points-transform-controls-pointer-keyboard-draggable-anchor-and-graded-practice" data-family={family.id} data-a={model.a} data-b={model.b} data-h={model.h} data-k={model.k} data-equation={equation} data-tab={tab} data-gallery={gallery} data-question={question+1} data-answer={answer??""}>
    <header className="pfl165-header"><section><span>TRANSFORMATIONS</span><h1>Parent-Function Library</h1><p>Explore the building blocks of functions.</p><div><b>♙ Level: Intermediate</b><b>ϟ Skills: Functions & Graphs</b><b>◷ Time: ~ 10 min</b><b>⌘ Goal: Recognize & use 6 parent families</b></div></section><aside><b>LEARNING FLOW</b>{["Observe","Manipulate","Notice the pattern","Understand the rule","Try independently"].map((x,i)=><span key={x}><i>{i+1}</i><em>{i+1}</em>{x}</span>)}</aside></header>
    <nav className="pfl165-tabs">{["Explore","Compare Families","Key Points","Rules","Practice"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);onInteraction()}}>{x}</button>)}</nav>
    <section className={`pfl165-main ${gallery?"":"gallery-hidden"}`}><aside className="pfl165-gallery"><h2><i>1</i> Choose a parent function</h2>{gallery?families.map(item=><button key={item.id} className={item.id===family.id?"active":""} onClick={()=>selectFamily(item.id)}><MiniIcon family={item}/><span><b>{item.name}</b><small>{item.formula}</small></span></button>):null}<button className="hide" onClick={()=>setGallery(v=>!v)}><ChevronLeft/>{gallery?"Hide gallery":"Show gallery"}</button></aside><article className="pfl165-plot"><header><strong>{family.formula}</strong><button onClick={()=>setModel(initial)}><RotateCcw/> Reset graph</button></header><LibraryGraph family={family} model={model} onShift={(h,k)=>setModel({...model,h,k})}/></article><aside className="pfl165-rail"><section><h2><i>2</i> Manipulate (Transform)</h2><Control symbol="a" label="Vertical stretch" min={-3} max={3} value={model.a} onChange={a=>setModel({...model,a:a===0?.5:a})}/><Control symbol="b" label="Horizontal stretch" min={-3} max={3} value={model.b} onChange={b=>setModel({...model,b:b===0?.5:b})}/><Control symbol="k" label="Vertical shift" min={-5} max={5} value={model.k} onChange={k=>setModel({...model,k})}/><Control symbol="h" label="Horizontal shift" min={-5} max={5} value={model.h} onChange={h=>setModel({...model,h})}/><div className="trace"><b>g(x) = a · f(b(x - h)) + k</b><span>= {fmt(model.a)} · f({fmt(model.b)}(x - {fmt(model.h)})) {model.k>=0?"+":"-"} {fmt(Math.abs(model.k))}</span><span>= transformed {family.name.toLowerCase()}</span></div></section><article><h2>At a glance</h2><div><span>Domain<b>{family.domain}</b></span><span>Range<b>{family.range}</b></span></div></article></aside></section>
    <section className="pfl165-insight"><article><h2><i>3</i> Notice the pattern</h2><p>{family.description}</p>{family.patterns.map(x=><span key={x}><Check/>{x}</span>)}</article><article><h2>Key points</h2><table><thead><tr><th>x</th>{keyXs.map(x=><th key={x}>{fmt(x)}</th>)}</tr></thead><tbody><tr><th>{family.formula}</th>{keyXs.map(x=><td key={x}>{family.evaluate(x)===null?"undefined":fmt(family.evaluate(x)!)}</td>)}</tr></tbody></table><p><b>Selected family:</b> {family.name} &nbsp; • &nbsp; <b>Anchor:</b> ({fmt(model.h)}, {fmt(model.k)})</p></article><aside><h2><i>4</i> Understand the rule</h2><p>{family.name} parent function:</p><b>{family.formula}</b><p>General {family.name.toLowerCase()} family:</p><strong>{family.rule}</strong></aside></section>
    <section className="pfl165-practice"><header><h2><i>5</i> Try independently</h2><p>Match the graph to the parent function.</p>{[0,1,2].map(i=><button key={i} className={question===i?"active":""} onClick={()=>{setQuestion(i);setAnswer(null);setStatus("")}}>Question {i+1}</button>)}</header><article><MiniIcon family={practiceFamily}/><svg viewBox="0 0 170 150"><line x1="5" x2="165" y1="75" y2="75"/><line x1="85" x2="85" y1="5" y2="145"/><path d={practiceFamily.id==="quadratic"?"M28 5Q85 145 142 5":practiceFamily.id==="absolute"?"M20 10L85 75L150 10":"M6 15Q75 18 78 68M92 82Q96 137 164 140"}/></svg></article><fieldset><legend>Select the parent function</legend>{families.map(item=><label key={item.id}><input type="radio" name="parent-family-answer" checked={answer===item.id} onChange={()=>{setAnswer(item.id);setStatus("")}}/>{item.name}: <i>{item.formula}</i></label>)}</fieldset><aside className={status.startsWith("Correct")?"correct":""}><Trophy/><p>{status||"Make a selection to see feedback."}</p><button disabled={!answer} onClick={()=>setStatus(answer===practiceFamily.id?`Correct - this is the ${practiceFamily.name} parent.`:`Try again - inspect the defining shape.`)}>Check answer</button></aside></section>
    <nav className="pfl165-nav"><a href="/lessons/graphs-and-functions/164-parameter-explorer"><ArrowLeft/><span><small>Previous</small><b>Parameter Explorer</b></span></a><div><small>Lesson Progress</small>{[1,2,3,4,5].map(i=><i key={i} className={i===1?"active":""}>{i}</i>)}</div><a href="/lessons/graphs-and-functions/166-graph-matching"><span><small>Next</small><b>Graph Matching</b></span><ArrowRight/></a></nav>
  </main>
}
