import { ArrowLeft, ArrowRight, Check, Eye, Grid3X3, Info, Lightbulb, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./ReflectionCircleTargetLesson239.css";

type Point = { x: number; y: number };
type Drag = "point" | "centre" | "radius" | null;
const INITIAL_POINT = { x: 3, y: 4 };
const INITIAL_CENTRE = { x: 0, y: 0 };
const STAGES = [["Observe", "See the pattern"], ["Manipulate", "Drag and explore"], ["Notice", "What stays constant?"], ["Understand", "The rule OP · OP' = r²"], ["Try", "Practice task"]];

export default function ReflectionCircleTargetLesson239({ resetToken, onInteraction }: LessonAdapterProps) {
  const [point, setPoint] = useState<Point>(INITIAL_POINT);
  const [centre, setCentre] = useState<Point>(INITIAL_CENTRE);
  const [radius, setRadius] = useState(3);
  const [mode, setMode] = useState<"point" | "radius">("point");
  const [grid, setGrid] = useState(true);
  const [axes, setAxes] = useState(true);
  const [stage, setStage] = useState(0);
  const [answer, setAnswer] = useState(["", ""]);
  const [feedback, setFeedback] = useState("");
  const [showSolution, setShowSolution] = useState(false);
  const model = useMemo(() => circleReflection(centre, point, radius), [centre, point, radius]);
  useEffect(() => { setPoint(INITIAL_POINT); setCentre(INITIAL_CENTRE); setRadius(3); setMode("point"); setGrid(true); setAxes(true); setStage(0); setAnswer(["", ""]); setFeedback(""); setShowSolution(false); }, [resetToken]);
  const updatePoint = (axis: "x" | "y", value: number) => { setPoint((current) => ({ ...current, [axis]: clamp(value, -6, 6) })); onInteraction(); };
  const updateCentre = (axis: "x" | "y", value: number) => { setCentre((current) => ({ ...current, [axis]: clamp(value, -4, 4) })); onInteraction(); };
  const updateRadius = (value: number) => { setRadius(clamp(value, 1, 5)); onInteraction(); };
  const check = () => { const expected = circleReflection({x:0,y:0}, {x:-2,y:1}, 5).image; const valid = answer.every(Boolean) && Math.abs(Number(answer[0])-expected.x)<.011 && Math.abs(Number(answer[1])-expected.y)<.011; setFeedback(valid ? "Correct: P' = (10, -5)." : "Not yet. Use the opposite ray and multiply P by -r²/OP²."); onInteraction(); };

  return <section className="target-circle-reflection-page" data-testid="dynamic-geometry-mockup-0296" data-dedicated-lesson="239" data-object-model="opposite-ray-circle-inversion" data-radius={radius.toFixed(4)} data-product={model.product.toFixed(4)}>
    <header className="target-circle-reflection-header"><span>Coordinate Geometry</span><h1>Reflection in Circle</h1><p>Reflect a point across a circle. Explore the relationship <i>OP · OP' = r².</i></p><footer><b>Event<br/><strong>Reflection</strong></b><b>Focus<br/><strong>Point and inverse</strong></b><b>Tools<br/><strong>Drag • Measure • Construct</strong></b><b>Time<br/><strong>6–10 min</strong></b></footer></header>
    <nav className="target-circle-reflection-stages" aria-label="Circle reflection lesson stages">{STAGES.map(([name,copy],index)=><button type="button" key={name} className={stage===index?"is-active":""} onClick={()=>{setStage(index);onInteraction();}}><i>{index+1}</i><span><b>{name}</b><small>{copy}</small></span></button>)}</nav>
    <section className="target-circle-reflection-workspace"><article className="target-circle-reflection-plot"><header><div><button type="button" className={mode==="point"?"is-active":""} onClick={()=>setMode("point")}>Point mode</button><button type="button" className={mode==="radius"?"is-active":""} onClick={()=>setMode("radius")}>Radius mode</button></div><div><label><input type="checkbox" checked={grid} onChange={e=>{setGrid(e.target.checked);onInteraction();}}/><Grid3X3/> Grid</label><label><input type="checkbox" checked={axes} onChange={e=>{setAxes(e.target.checked);onInteraction();}}/>Axes</label></div></header><CircleReflectionGraph centre={centre} point={point} radius={radius} model={model} mode={mode} grid={grid} axes={axes} onCentre={setCentre} onPoint={setPoint} onRadius={setRadius} onInteraction={onInteraction}/><aside><b><i>O</i> Center</b><b><i>P</i> Point</b><b><i>P'</i> Inverse point</b><hr/><span>Circle: (x − h)² + (y − k)² = r²<br/>r = {format(radius)}</span></aside></article>
      <aside className="target-circle-reflection-controls"><section><h2>Point <i>P</i></h2><CoordinateInputs name="Point P" point={point} onValue={updatePoint}/><label>Drag <i>P</i><input aria-label="Drag P horizontally" type="range" min="-6" max="6" step=".1" value={point.x} onChange={e=>updatePoint("x",Number(e.target.value))}/></label></section><section><h2>◉ Circle <small>(center O)</small></h2><CoordinateInputs name="Circle center O" point={centre} onValue={updateCentre}/><label>Radius <i>r</i><span><input aria-label="Circle radius exact value" type="number" min="1" max="5" step=".1" value={radius} onChange={e=>updateRadius(Number(e.target.value))}/><input aria-label="Circle radius" type="range" min="1" max="5" step=".1" value={radius} onChange={e=>updateRadius(Number(e.target.value))}/></span></label></section><section className="target-circle-reflection-observation"><h2>◌ Observation</h2><dl><div><dt><i>OP</i> (distance)</dt><dd>{format3(model.distance)}</dd></div><div><dt><i>OP'</i> (distance)</dt><dd>{model.defined?format3(model.imageDistance):"undefined"}</dd></div><div><dt>Product <i>OP · OP'</i></dt><dd>{model.defined?format3(model.product):"undefined"}</dd></div><div><dt><i>r²</i></dt><dd>{format3(radius*radius)}</dd></div></dl><footer><b>OP · OP' = r²</b><strong><Check/> {model.holds?"Holds":"Undefined at O"}</strong></footer></section></aside>
    </section>
    <div className="target-circle-reflection-tip"><Info/> Drag point <i>P</i> anywhere (inside or outside the circle). Point <i>P'</i> updates automatically on the same line through <i>O</i>.</div>
    <section className="target-circle-reflection-learning"><article><h2>Worked Example</h2><p>Given <i>P(3, 4)</i> and circle <i>x² + y² = 9</i> (<i>r = 3</i>).</p><ol><li><b>Distance OP</b><br/><i>OP = √(3² + 4²) = 5</i></li><li><b>Inverse distance</b><br/><i>OP' = r² / OP = 9 / 5 = 1.8</i></li><li><b>Inverse point</b><br/><i>P' = −r²/OP² P<br/>= −9/25 (3, 4)<br/>= (−1.08, −1.44)</i></li></ol></article><article><h2>Construction</h2><ol><li>Draw circle with center <i>O</i> and radius <i>r</i>.</li><li>Place point <i>P</i> anywhere.</li><li>Join <i>OP</i>.</li><li>Locate <i>P'</i> on the opposite ray so that</li></ol><strong>OP · OP' = r²</strong><p>Equivalently,</p><b>P' = O − r²/OP² (P−O)</b></article><article><h2><Lightbulb/> Key Insight</h2><p>For any point <i>P ≠ O</i>, its reflected point <i>P'</i> with respect to circle</p><strong>(x−h)² + (y−k)² = r²</strong><p>lies on line <i>OP</i> (opposite side) and satisfies</p><b>OP · OP' = r²</b><p>If <i>P</i> lies inside the circle, then <i>P'</i> lies outside. If <i>P</i> lies outside, then <i>P'</i> lies inside.</p></article></section>
    <section className="target-circle-reflection-practice"><h2>Try It Yourself</h2><p>Find the inverse point <i>P'</i>.</p><div><b>1</b><span>Circle<br/><i>x² + y² = 25 &nbsp; (r = 5)</i></span><span>Given point P<br/><i>P(−2, 1)</i></span><span>Your answer P' <small>(rounded to 2 d.p.)</small><label>x' = <input aria-label="Practice inverse x coordinate" value={answer[0]} onChange={e=>setAnswer([e.target.value,answer[1]])} placeholder="e.g., 4.62"/></label><label>y' = <input aria-label="Practice inverse y coordinate" value={answer[1]} onChange={e=>setAnswer([answer[0],e.target.value])} placeholder="e.g., −2.31"/></label><button type="button" onClick={check}>Check</button></span><aside>Hint<br/><i>P' = O − r²/OP²(P−O)</i></aside></div><footer><button type="button" onClick={()=>{setAnswer(["",""]);setFeedback("");onInteraction();}}><RotateCcw/> Reset</button><button type="button" onClick={()=>{setShowSolution(v=>!v);onInteraction();}}><Eye/> {showSolution?"Hide solution":"Show solution"}</button></footer>{(feedback||showSolution)&&<p role="status">{showSolution?"OP² = 5, so P' = −5(−2,1) = (10,−5).":feedback}</p>}</section>
    <nav className="target-circle-reflection-nav" aria-label="Adjacent lessons"><a href="/lessons/geometry/238-reflection-in-point"><ArrowLeft/><span><b>Previous</b>Reflection in Point</span></a><span>Lesson 239 of Coordinate Geometry<i/></span><a href="/lessons/geometry/240-rotation-around-point"><span><b>Next</b>Rotation Around Point</span><ArrowRight/></a></nav>
  </section>;
}

function CircleReflectionGraph({centre,point,radius,model,mode,grid,axes,onCentre,onPoint,onRadius,onInteraction}:{centre:Point;point:Point;radius:number;model:ReturnType<typeof circleReflection>;mode:"point"|"radius";grid:boolean;axes:boolean;onCentre:(p:Point)=>void;onPoint:(p:Point)=>void;onRadius:(r:number)=>void;onInteraction:()=>void}) { const ref=useRef<SVGSVGElement>(null),drag=useRef<Drag>(null),origin={x:252,y:205},scale=35; const s=(p:Point)=>({x:origin.x+p.x*scale,y:origin.y-p.y*scale}); const w=(e:ReactPointerEvent<SVGSVGElement>)=>{const m=ref.current?.getScreenCTM();if(!m)return null;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return{x:(p.x-origin.x)/scale,y:(origin.y-p.y)/scale};}; const o=s(centre),p=s(point),q=s(model.image),rh=s({x:centre.x+radius,y:centre.y}); const begin=(d:Exclude<Drag,null>)=>(e:ReactPointerEvent<SVGCircleElement>)=>{drag.current=d;e.currentTarget.setPointerCapture(e.pointerId);}; return <svg ref={ref} className="target-circle-reflection-graph" viewBox="0 0 505 410" role="img" aria-label="Interactive reflection in circle graph with draggable O, P, and radius" onPointerMove={e=>{if(!drag.current)return;const n=w(e);if(!n)return;if(drag.current==="point")onPoint({x:clamp(round(n.x),-6,6),y:clamp(round(n.y),-6,6)});else if(drag.current==="centre")onCentre({x:clamp(round(n.x),-4,4),y:clamp(round(n.y),-4,4)});else onRadius(clamp(Math.hypot(n.x-centre.x,n.y-centre.y),1,5));onInteraction();}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><rect width="505" height="410" fill="#fff"/>{grid&&<Grid/>}{axes&&<g stroke="#64748b"><line x1="8" x2="497" y1={origin.y} y2={origin.y}/><line x1={origin.x} x2={origin.x} y1="5" y2="405"/></g>}<line x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="#a855f7" strokeWidth="1.5"/><circle cx={o.x} cy={o.y} r={radius*scale} fill="none" stroke="#168ddd" strokeWidth="1.5"/><circle data-testid="circle-reflection-centre" cx={o.x} cy={o.y} r="5" fill="#168ddd" onPointerDown={begin("centre")}/><circle data-testid="circle-reflection-radius-handle" cx={rh.x} cy={rh.y} r={mode==="radius"?7:4} fill="#22c55e" onPointerDown={begin("radius")}/><circle data-testid="circle-reflection-source" data-x={point.x} data-y={point.y} cx={p.x} cy={p.y} r="7" fill="#1378db" onPointerDown={begin("point")}/>{model.defined&&<circle data-testid="circle-reflection-image" data-x={model.image.x.toFixed(4)} data-y={model.image.y.toFixed(4)} cx={q.x} cy={q.y} r="7" fill="#7c3aed"/>}<g fontFamily="Georgia,serif" fontSize="14"><text x={o.x+9} y={o.y+18} fill="#64748b">O {formatPoint(centre)}</text><text x={p.x+8} y={p.y-10} fill="#1378db">P {formatPoint(point)}</text>{model.defined&&<text x={q.x-82} y={q.y+20} fill="#7c3aed">P' {formatPoint(model.image)}</text>}</g></svg>; }
function Grid(){return <g stroke="#e5edf5">{Array.from({length:15},(_,i)=><line key={`v${i}`} x1={7+i*35} x2={7+i*35} y1="0" y2="410"/>)}{Array.from({length:13},(_,i)=><line key={`h${i}`} x1="0" x2="505" y1={i*35} y2={i*35}/>)}</g>;}
function CoordinateInputs({name,point,onValue}:{name:string;point:Point;onValue:(axis:"x"|"y",value:number)=>void}){return <div className="target-circle-reflection-coordinates"><label>x<input aria-label={`${name} x coordinate`} type="number" value={point.x} onChange={e=>onValue("x",Number(e.target.value))}/></label><label>y<input aria-label={`${name} y coordinate`} type="number" value={point.y} onChange={e=>onValue("y",Number(e.target.value))}/></label></div>;}
function circleReflection(centre:Point,point:Point,radius:number){const dx=point.x-centre.x,dy=point.y-centre.y,distance=Math.hypot(dx,dy),defined=distance>1e-8,factor=defined?radius*radius/(distance*distance):0,image=defined?{x:centre.x-factor*dx,y:centre.y-factor*dy}:{...centre},imageDistance=defined?Math.hypot(image.x-centre.x,image.y-centre.y):0,product=distance*imageDistance;return{image,distance,imageDistance,product,defined,holds:defined&&Math.abs(product-radius*radius)<1e-7};}
function format(n:number){return Number(n.toFixed(2)).toString();} function format3(n:number){return n.toFixed(3);} function formatPoint(p:Point){return `(${format(p.x)}, ${format(p.y)})`;} function round(n:number){return Math.round(n*10)/10;} function clamp(n:number,min:number,max:number){return Math.min(max,Math.max(min,Number.isFinite(n)?n:min));}
