import { ArrowLeft, ArrowRight, Check, Maximize2, RotateCcw, Share2, Sparkles } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./RotationPointTargetLesson240.css";

type Point={x:number;y:number}; type Drag="centre"|"point"|"angle"|null;
const INITIAL_CENTRE={x:0,y:0}, INITIAL_POINT={x:4,y:2};
const TABS=["Observe","Manipulate","Pattern","Rule","Try it"];

export default function RotationPointTargetLesson240({resetToken,onInteraction}:LessonAdapterProps){
  const [centre,setCentre]=useState<Point>(INITIAL_CENTRE),[point,setPoint]=useState<Point>(INITIAL_POINT),[angle,setAngle]=useState(90),[direction,setDirection]=useState<1|-1>(1),[tab,setTab]=useState(0);
  const [showImage,setShowImage]=useState(true),[showArc,setShowArc]=useState(true),[showLabels,setShowLabels]=useState(false),[answer,setAnswer]=useState(["",""]),[feedback,setFeedback]=useState(""),[solution,setSolution]=useState(false),[status,setStatus]=useState("");
  const signedAngle=angle*direction, model=useMemo(()=>rotate(centre,point,signedAngle),[centre,point,signedAngle]), practice=useMemo(()=>rotate({x:0,y:0},{x:-2,y:5},120),[]);
  const reset=()=>{setCentre(INITIAL_CENTRE);setPoint(INITIAL_POINT);setAngle(90);setDirection(1);setTab(0);setShowImage(true);setShowArc(true);setShowLabels(false);setStatus("Rotation reset.");onInteraction();};
  useEffect(()=>{setCentre(INITIAL_CENTRE);setPoint(INITIAL_POINT);setAngle(90);setDirection(1);setTab(0);setShowImage(true);setShowArc(true);setShowLabels(false);setAnswer(["",""]);setFeedback("");setSolution(false);setStatus("");},[resetToken]);
  const updateCentre=(axis:"x"|"y",value:number)=>{setCentre(c=>({...c,[axis]:clamp(value,-6,6)}));onInteraction();}, updatePoint=(axis:"x"|"y",value:number)=>{setPoint(p=>({...p,[axis]:clamp(value,-7,7)}));onInteraction();};
  const updateAngle=(value:number)=>{setAngle(clamp(Math.round(value),0,360));onInteraction();};
  const share=async()=>{const summary=`Rotate P${fp(point)} about O${fp(centre)} by ${signedAngle}° to P'${fp(model.image)}.`;try{await navigator.clipboard?.writeText(summary);setStatus("Rotation summary copied.");}catch{setStatus("Rotation summary prepared.");}onInteraction();};
  const check=()=>{const ok=answer.every(Boolean)&&Math.abs(Number(answer[0])-practice.image.x)<.011&&Math.abs(Number(answer[1])-practice.image.y)<.011;setFeedback(ok?`Correct: P' = (${f2(practice.image.x)}, ${f2(practice.image.y)}).`:"Not yet. Apply the counterclockwise rotation matrix to both coordinates.");onInteraction();};
  return <section className="target-rotation-page" data-testid="dynamic-geometry-mockup-0297" data-dedicated-lesson="240" data-object-model="fixed-centre-signed-angle-rotation" data-radius={model.radius.toFixed(4)} data-image-x={model.image.x.toFixed(4)} data-image-y={model.image.y.toFixed(4)}>
    <header className="target-rotation-header"><h1>Rotation around Point</h1><p>Rotate a point about a fixed centre by a given angle.</p><footer><b>⚲ Coordinate Geometry</b><b>ϟ Intermediate–Advanced</b><b>▣ Investigation Lab</b><b>▤ Reusable 2D Engine</b><b>◷ 6–10 min</b></footer></header>
    <section className="target-rotation-lab"><header><nav>{TABS.map((name,i)=><button type="button" key={name} className={tab===i?"is-active":""} onClick={()=>{setTab(i);onInteraction();}}>{name}</button>)}</nav><aside><button type="button" onClick={reset}><RotateCcw/> Reset all</button><button type="button" onClick={()=>void share()}><Share2/> Share</button><button type="button" aria-label="Full screen rotation lab" onClick={()=>{document.documentElement.requestFullscreen?.();onInteraction();}}><Maximize2/></button></aside></header>
      <div className="target-rotation-body"><article className="target-rotation-left"><div className="target-rotation-graph-wrap"><aside><label><input type="checkbox" checked={showImage} onChange={e=>{setShowImage(e.target.checked);onInteraction();}}/>Show image (rotated)</label><label><input type="checkbox" checked={showArc} onChange={e=>{setShowArc(e.target.checked);onInteraction();}}/>Show path (arc)</label><label><input type="checkbox" checked={showLabels} onChange={e=>{setShowLabels(e.target.checked);onInteraction();}}/>Show axes labels</label></aside><RotationGraph centre={centre} point={point} model={model} angle={signedAngle} showImage={showImage} showArc={showArc} showLabels={showLabels} onCentre={setCentre} onPoint={setPoint} onAngle={updateAngle} onInteraction={onInteraction}/><nav><button type="button">+</button><button type="button">−</button><button type="button">⌾</button></nav></div><section className="target-rotation-controls"><article><h2>Centre (fixed)</h2><p><i>O (h, k)</i></p><Coordinate name="Centre O" value={centre} onValue={updateCentre}/></article><article><h2>Angle θ</h2><AngleDial angle={angle} onAngle={updateAngle}/><div>{[[-90,"−90°"],[90,"90°"],[180,"180°"],[270,"270°"]].map(([value,label])=><button type="button" key={value} onClick={()=>{setAngle(Math.abs(value as number));setDirection((value as number)<0?-1:1);onInteraction();}}>{label}</button>)}</div><h3>Direction</h3><footer><button type="button" aria-label="Counterclockwise direction" className={direction===1?"is-active":""} onClick={()=>{setDirection(1);onInteraction();}}>↶</button><button type="button" aria-label="Clockwise direction" className={direction===-1?"is-active":""} onClick={()=>{setDirection(-1);onInteraction();}}>↷</button></footer></article><article><h2>Point to rotate</h2><p><i>P (x, y)</i></p><Coordinate name="Point P" value={point} onValue={updatePoint}/></article></section>
        <section className="target-rotation-summary"><div><b>● Original point P</b><strong>(x, y) = {fp(point)}</strong><span>Distance r = {f2(model.radius)}</span><span>Angle from O = {f2(model.startAngle)}°</span></div><div><b>● Centre O</b><strong>(h, k) = {fp(centre)}</strong></div><div><b>● Image P'</b><strong>(x', y') = {fp(model.image)}</strong><span>Distance r' = {f2(model.imageRadius)}</span><span>Angle from O = {f2(model.endAngle)}°</span></div></section><div className="target-rotation-tip"><Sparkles/><b>Pro tip</b><span>Use the angle dial or preset buttons to explore multiples of 90°. Drag the centre to see how rotation changes.</span></div>
      </article><aside className="target-rotation-right"><section><h2>Observations</h2>{["The distance from O to P and P' remains the same.","The path is a circular arc with centre O.","Rotating by +θ is counterclockwise.","Coordinates update instantly as you change θ or the centre."].map(t=><p key={t}><Check/>{t}</p>)}</section><section><h2>Rule (about origin)</h2><p>If <i>P (x, y)</i> is rotated counterclockwise about the origin <i>O (0, 0)</i> by angle <i>θ</i>,</p><strong>P'(x', y') = (x cos θ − y sin θ, &nbsp; x sin θ + y cos θ)</strong><p>For rotation about <i>O (h, k)</i>:</p><strong>P'(x',y') = (h+(x−h)cosθ−(y−k)sinθ, k+(x−h)sinθ+(y−k)cosθ)</strong></section><section><h2>Worked example</h2><p>Rotate <i>P (3, −1)</i> about <i>O (1, 2)</i> by <i>θ = 90°</i> counterclockwise.</p><p>• Here, x−h = 2 and y−k = −3</p><p>• So, P' = (1 + 0 − (−3), 2 + 2 + 0) = (4, 4)</p></section><section className="target-rotation-practice"><h2>Try it</h2><p>Rotate the given point about the origin by the stated angle.</p><strong>P (−2, 5), θ = 120° (counterclockwise)</strong><div><label>x' = <input aria-label="Practice rotated x coordinate" value={answer[0]} onChange={e=>setAnswer([e.target.value,answer[1]])}/></label><label>y' = <input aria-label="Practice rotated y coordinate" value={answer[1]} onChange={e=>setAnswer([answer[0],e.target.value])}/></label></div><footer><button type="button" onClick={check}>Check answer</button><button type="button" onClick={()=>{setSolution(v=>!v);onInteraction();}}>{solution?"Hide solution":"Show solution"}</button></footer>{(feedback||solution)&&<p role="status">{solution?`P' = (${f2(practice.image.x)}, ${f2(practice.image.y)})`:feedback}</p>}</section></aside></div>
    </section><nav className="target-rotation-nav"><a href="/lessons/geometry/239-reflection-in-circle"><ArrowLeft/><span><b>Previous</b>Reflection in Circle</span></a><span><b>Lesson progress</b><i/><strong>4 / 5 &nbsp; 🏆</strong></span><a href="/lessons/geometry/241-dilation-from-point"><span><b>Next</b>Dilation from Point</span><ArrowRight/></a></nav><span className="sr-only" role="status">{status}</span>
  </section>;
}

function RotationGraph({centre,point,model,angle,showImage,showArc,showLabels,onCentre,onPoint,onAngle,onInteraction}:{centre:Point;point:Point;model:ReturnType<typeof rotate>;angle:number;showImage:boolean;showArc:boolean;showLabels:boolean;onCentre:(p:Point)=>void;onPoint:(p:Point)=>void;onAngle:(n:number)=>void;onInteraction:()=>void}){const ref=useRef<SVGSVGElement>(null),drag=useRef<Drag>(null),origin={x:285,y:260},scale=29,s=(p:Point)=>({x:origin.x+p.x*scale,y:origin.y-p.y*scale}),o=s(centre),p=s(point),q=s(model.image);const world=(e:ReactPointerEvent<SVGSVGElement>)=>{const m=ref.current?.getScreenCTM();if(!m)return null;const z=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return{x:(z.x-origin.x)/scale,y:(origin.y-z.y)/scale};},begin=(d:Exclude<Drag,null>)=>(e:ReactPointerEvent<SVGCircleElement>)=>{drag.current=d;e.currentTarget.setPointerCapture(e.pointerId);};const r=model.radius*scale,large=Math.abs(angle)>180?1:0,sweep=angle>=0?0:1,arc=`M ${p.x} ${p.y} A ${r} ${r} 0 ${large} ${sweep} ${q.x} ${q.y}`;return <svg ref={ref} className="target-rotation-graph" viewBox="0 0 570 490" role="img" aria-label="Interactive graph rotating P around draggable centre O" onPointerMove={e=>{if(!drag.current)return;const n=world(e);if(!n)return;if(drag.current==="point")onPoint({x:clamp(roundHalf(n.x),-8,8),y:clamp(roundHalf(n.y),-8,8)});else if(drag.current==="centre")onCentre({x:clamp(roundHalf(n.x),-6,6),y:clamp(roundHalf(n.y),-6,6)});else{const a=Math.atan2(n.y-centre.y,n.x-centre.x)*180/Math.PI-model.startAngle;onAngle((a+360)%360);}onInteraction();}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><rect width="570" height="490" fill="#fff"/><Grid origin={origin} scale={scale}/><line x1={o.x} y1={o.y} x2={p.x} y2={p.y} stroke="#1685f8" strokeWidth="2"/><line x1={o.x} y1={o.y} x2={q.x} y2={q.y} stroke="#8b5cf6" strokeWidth="2"/>{showArc&&<path data-testid="rotation-arc" d={arc} fill="none" stroke="#a78bfa" strokeWidth="1.5" strokeDasharray="5 4"/>}<circle data-testid="rotation-centre" data-x={centre.x} data-y={centre.y} cx={o.x} cy={o.y} r="7" fill="#f59e0b" onPointerDown={begin("centre")}/><circle data-testid="rotation-source" data-x={point.x} data-y={point.y} cx={p.x} cy={p.y} r="7" fill="#1685f8" onPointerDown={begin("point")}/>{showImage&&<circle data-testid="rotation-image" data-x={model.image.x.toFixed(4)} data-y={model.image.y.toFixed(4)} cx={q.x} cy={q.y} r="7" fill="#7c3aed" onPointerDown={begin("angle")}/>}<g fontSize="14" fontFamily="Georgia,serif"><text x={o.x-21} y={o.y+25} fill="#f97316">O {fp(centre)}</text><text x={p.x+10} y={p.y-10} fill="#1685f8">P {fp(point)}</text>{showImage&&<text x={q.x-65} y={q.y-12} fill="#7c3aed">P' {fp(model.image)}</text>}<text x={o.x+56} y={o.y-34} fill="#16a34a">θ = {angle}°</text></g>{showLabels&&<text x="535" y="250" fontSize="11">x-axis</text>}</svg>}
function Grid({origin,scale}:{origin:Point;scale:number}){return <g><g stroke="#e5edf5">{Array.from({length:20},(_,i)=><line key={`v${i}`} x1={i*scale} x2={i*scale} y1="0" y2="490"/>)}{Array.from({length:18},(_,i)=><line key={`h${i}`} x1="0" x2="570" y1={i*scale} y2={i*scale}/>)}</g><g stroke="#475569"><line x1="0" x2="570" y1={origin.y} y2={origin.y}/><line x1={origin.x} x2={origin.x} y1="0" y2="490"/></g></g>}
function Coordinate({name,value,onValue}:{name:string;value:Point;onValue:(a:"x"|"y",v:number)=>void}){return <div className="target-rotation-coordinate"><label>x<input aria-label={`${name} x coordinate`} type="number" value={value.x} onChange={e=>onValue("x",Number(e.target.value))}/></label><label>y<input aria-label={`${name} y coordinate`} type="number" value={value.y} onChange={e=>onValue("y",Number(e.target.value))}/></label></div>}
function AngleDial({angle,onAngle}:{angle:number;onAngle:(n:number)=>void}){return <label className="target-rotation-dial"><input aria-label="Rotation angle" type="range" min="0" max="360" value={angle} onChange={e=>onAngle(Number(e.target.value))}/><i style={{transform:`rotate(${angle}deg)`}}/><b>{angle}°</b></label>}
function rotate(c:Point,p:Point,degrees:number){const t=degrees*Math.PI/180,dx=p.x-c.x,dy=p.y-c.y,image={x:c.x+dx*Math.cos(t)-dy*Math.sin(t),y:c.y+dx*Math.sin(t)+dy*Math.cos(t)},radius=Math.hypot(dx,dy),imageRadius=Math.hypot(image.x-c.x,image.y-c.y),startAngle=(Math.atan2(dy,dx)*180/Math.PI+360)%360,endAngle=(Math.atan2(image.y-c.y,image.x-c.x)*180/Math.PI+360)%360;return{image,radius,imageRadius,startAngle,endAngle}}
function f2(n:number){return n.toFixed(2)}function f(n:number){return Number(n.toFixed(2)).toString()}function fp(p:Point){return `(${f(p.x)}, ${f(p.y)})`}function roundHalf(n:number){return Math.round(n*2)/2}function clamp(n:number,min:number,max:number){return Math.min(max,Math.max(min,Number.isFinite(n)?n:min))}
