import { ArrowLeft, ArrowRight, Check, ChevronDown, Compass, Expand, Lightbulb, Maximize2, Move, RotateCcw, Share2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { PointerEvent, ReactNode } from "react";
import type { LessonAdapterProps } from "../types";
import "./SegmentGivenLengthTargetLesson205.css";

type Point={x:number;y:number}; type Drag="A"|"B"|"pan"|null;
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n)), round=(n:number)=>Math.round(n*100)/100;
const endpoint=(a:Point,d:number,angle:number)=>{const r=angle*Math.PI/180;return{x:a.x+d*Math.cos(r),y:a.y+d*Math.sin(r)}};
function Field({label,value,onChange,min=-8,max=8}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){return <label>{label}<input aria-label={label} type="number" step="0.5" min={min} max={max} value={value} onChange={e=>onChange(clamp(Number(e.target.value),min,max))}/></label>}
function ModelGraph({a,d,angle,grid,pan,zoom,onA,onAngle,onPan}:{a:Point;d:number;angle:number;grid:boolean;pan:Point;zoom:number;onA:(p:Point)=>void;onAngle:(n:number)=>void;onPan:(p:Point)=>void}){
  const ref=useRef<SVGSVGElement>(null),drag=useRef<Drag>(null),last=useRef({x:0,y:0}),ox=320+pan.x,oy=250+pan.y,s=29*zoom,b=endpoint(a,d,angle),screen=(p:Point)=>({x:ox+p.x*s,y:oy-p.y*s}),as=screen(a),bs=screen(b);
  const from=(e:PointerEvent<SVGSVGElement>)=>{const r=ref.current!.getBoundingClientRect();return{x:round((((e.clientX-r.left)/r.width)*640-ox)/s),y:round((oy-((e.clientY-r.top)/r.height)*500)/s)}};
  const move=(e:PointerEvent<SVGSVGElement>)=>{if(!drag.current)return;if(drag.current==="pan"){onPan({x:pan.x+e.clientX-last.current.x,y:pan.y+e.clientY-last.current.y});last.current={x:e.clientX,y:e.clientY};return}const p=from(e);if(drag.current==="A")onA({x:clamp(p.x,-6,6),y:clamp(p.y,-6,6)});else onAngle(Math.round((Math.atan2(a.y-p.y,p.x-a.x)*180/Math.PI+360)%360));};
  const start=(e:PointerEvent<SVGGElement>,name:Exclude<Drag,"pan"|null>)=>{e.stopPropagation();drag.current=name;e.currentTarget.setPointerCapture(e.pointerId)};
  const ray={x:as.x+(bs.x-as.x)*1.75,y:as.y+(bs.y-as.y)*1.75};
  return <svg ref={ref} className="gl205-canvas" viewBox="0 0 640 500" role="img" aria-label="Fixed-length segment from draggable start A to draggable direction handle B" onPointerDown={e=>{drag.current="pan";last.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><defs><pattern id="gl205-grid" width={s} height={s} patternUnits="userSpaceOnUse" x={ox} y={oy}><path d={`M${s} 0H0V${s}`} fill="none" stroke="#dce5ed" strokeDasharray="2 2"/></pattern></defs><rect width="640" height="500" fill="#fff"/>{grid&&<rect width="640" height="500" fill="url(#gl205-grid)"/>}<line x1="8" y1={oy} x2="632" y2={oy} className="axis"/><line x1={ox} y1="492" x2={ox} y2="8" className="axis"/>{[-8,-6,-4,-2,0,2,4,6,8].map(n=><g key={n}><text x={ox+n*s} y={oy+20} textAnchor="middle">{n}</text>{n!==0&&<text x={ox-10} y={oy-n*s+4} textAnchor="end">{n}</text>}</g>)}<line x1={as.x} y1={as.y} x2={ray.x} y2={ray.y} className="ray"/><line x1={as.x} y1={as.y} x2={bs.x} y2={bs.y} className="segment"/><g data-testid="given-start" onPointerDown={e=>start(e,"A")}><circle cx={as.x} cy={as.y} r="7" className="a"/><text x={as.x+10} y={as.y-8}>A ({a.x}, {a.y})</text></g><g data-testid="given-handle" onPointerDown={e=>start(e,"B")}><circle cx={bs.x} cy={bs.y} r="15" className="handle"/><path d={`M${bs.x-6} ${bs.y+3}L${bs.x+6} ${bs.y-9}M${bs.x} ${bs.y-9}H${bs.x+6}V${bs.y-3}`}/></g></svg>
}
function Dial({angle,onAngle}:{angle:number;onAngle:(n:number)=>void}){const r=angle*Math.PI/180,x=55+Math.cos(r)*39,y=55-Math.sin(r)*39;return <svg className="gl205-dial" viewBox="0 0 110 110" role="slider" aria-label="Direction angle dial" aria-valuenow={angle} onPointerDown={e=>{const b=e.currentTarget.getBoundingClientRect(),px=(e.clientX-b.left)/b.width*110,py=(e.clientY-b.top)/b.height*110;onAngle(Math.round((Math.atan2(55-py,px-55)*180/Math.PI+360)%360))}}><circle cx="55" cy="55" r="40"/><line x1="55" y1="55" x2={x} y2={y}/><circle cx={x} cy={y} r="4"/><text x="55" y="83" textAnchor="middle">{angle} deg</text></svg>}
function Card({title,tone,children}:{title:string;tone:string;children:ReactNode}){return <article className={`gl205-card ${tone}`}><h2>{title}</h2><div>{children}</div></article>}
function StepArt({step}:{step:number}){return <svg viewBox="0 0 130 55"><line x1="15" y1="42" x2="112" y2={step===1?42:15} className={step===3?"solid":"dash"}/><circle cx="15" cy="42" r="3"/><circle cx="112" cy={step===1?42:15} r="3"/>{step===1&&<path d="M44 45L65 8L86 45"/>}</svg>}

export default function SegmentGivenLengthTargetLesson205({lesson,resetToken,onInteraction}:LessonAdapterProps){
  const [a,setA]=useState<Point>({x:0,y:0}),[d,setD]=useState(5),[angle,setAngle]=useState(45),[grid,setGrid]=useState(true),[pan,setPan]=useState({x:0,y:0}),[zoom,setZoom]=useState(1),[stage,setStage]=useState("Observe"),[language,setLanguage]=useState("English (English)"),[shared,setShared]=useState(false),[task,setTask]=useState({ax:-2,ay:1,d:7,angle:30}),[result,setResult]=useState<"idle"|"correct"|"incorrect">("idle"),[taskNo,setTaskNo]=useState(0);const b=endpoint(a,d,angle);
  const reset=()=>{setA({x:0,y:0});setD(5);setAngle(45);setGrid(true);setPan({x:0,y:0});setZoom(1);onInteraction()};useEffect(()=>{setA({x:0,y:0});setD(5);setAngle(45);setGrid(true);setPan({x:0,y:0});setZoom(1);setStage("Observe");setShared(false);setTask({ax:-2,ay:1,d:7,angle:30});setResult("idle");setTaskNo(0)},[resetToken]);
  const setAngleReal=(n:number)=>{setAngle((n+360)%360);onInteraction()}, setStart=(p:Point)=>{setA(p);onInteraction()};
  const stages=[["Observe","See the model"],["Manipulate","Change inputs"],["Notice","Pattern emerges"],["Understand","The rule"],["Try it","Practice"]];
  return <section className="gl205-page" data-testid="dynamic-geometry-mockup-0262" data-model="start-length-angle-derived-endpoint-compass-invariant" data-a={`${a.x}:${a.y}`} data-b={`${round(b.x)}:${round(b.y)}`} data-length={d} data-angle={angle} data-grid={grid} data-pan={`${round(pan.x)}:${round(pan.y)}`} data-zoom={zoom} data-stage={stage} data-shared={shared} data-task={taskNo}>
    <header className="gl205-header"><i><Compass/></i><div><h1>{lesson.title}</h1><p>Construct a segment of a specified length from a chosen start point.</p></div><label><select aria-label="Lesson language" value={language} onChange={e=>{setLanguage(e.target.value);onInteraction()}}><option>English (English)</option><option>Hindi (Hindi)</option></select><ChevronDown/></label><aside><b>Dynamic Geometry Constructions</b><b>Geometry Tools</b><b>6-10 min</b></aside><nav><button type="button" onClick={reset}><RotateCcw/>Reset</button><button type="button" onClick={async()=>{setShared(true);await globalThis.navigator?.clipboard?.writeText(globalThis.location?.href??"").catch(()=>{});onInteraction()}}><Share2/>{shared?"Shared":"Share"}</button></nav></header>
    <nav className="gl205-stages" aria-label="Given length lesson stages">{stages.map(([name,sub],i)=><button type="button" key={name} className={stage===name?"active":""} onClick={()=>{setStage(name);onInteraction()}}><i>{i+1}</i><span><b>{name}</b><small>{sub}</small></span></button>)}</nav>
    <section className="gl205-model"><main><header><h2>Interactive Model</h2><nav><button type="button" aria-pressed={grid} onClick={()=>{setGrid(v=>!v);onInteraction()}}>Grid<i className={grid?"on":""}/></button><button type="button" aria-label="Center view" onClick={()=>setPan({x:0,y:0})}><Move/></button><button type="button" aria-label="Zoom model" onClick={()=>setZoom(z=>z===1?1.2:1)}><Expand/></button><button type="button" aria-label="Fit model" onClick={()=>{setPan({x:0,y:0});setZoom(1)}}><Maximize2/></button></nav></header><p className="hint">Drag the handle to set direction.</p><ModelGraph a={a} d={d} angle={angle} grid={grid} pan={pan} zoom={zoom} onA={setStart} onAngle={setAngleReal} onPan={setPan}/><footer><b>Start point A</b><b>Constructed segment</b><b>Direction ray</b></footer></main><aside><h2>Construction Controls</h2><section><h3>Start point A</h3><div><Field label="A x coordinate" value={a.x} onChange={n=>setStart({...a,x:n})}/><Field label="A y coordinate" value={a.y} onChange={n=>setStart({...a,y:n})}/></div><h3>Length</h3><Field label="Length AB" value={d} min={1} max={9} onChange={n=>{setD(n);onInteraction()}}/><h3>Direction</h3><Field label="Angle theta" value={angle} min={0} max={359} onChange={setAngleReal}/><Dial angle={angle} onAngle={setAngleReal}/></section><section className="verify"><header><b>Live Verification</b><span>Verified</span></header><h3>Constructed point B</h3><p>B ({b.x.toFixed(3)}, {b.y.toFixed(3)})</p><p>Distance AB <b>{d.toFixed(3)} units</b></p><p>Angle theta <b>{angle.toFixed(1)} deg</b></p><strong><Check/>Great! AB = {d} units.</strong></section></aside></section>
    <div className="gl205-cards"><Card title="Worked Example" tone="blue"><p>Construct segment AB of length 5 units from A (0, 0) at angle 45 deg.</p><ol>{["Set start point A (0, 0).","Set length AB = 5 units.","Set direction angle theta = 45 deg.","Draw ray from A at 45 deg.","Mark point B on the ray so that AB = 5 units.","Read coordinates of B and verify."].map((text,i)=><li key={text}><i>{i+1}</i>{text}</li>)}</ol><strong>Result: B ({b.x.toFixed(3)}, {b.y.toFixed(3)})</strong></Card><Card title="Key Insight" tone="violet"><p>Point B is determined by the start point A, the length d, and the direction angle theta.</p><h3>Coordinate Rule</h3><strong>xB = xA + d cos(theta)<br/>yB = yA + d sin(theta)</strong><p>Angle theta is measured counterclockwise from the positive x-axis.</p></Card><Card title="Your Turn" tone="cyan"><button className="new" type="button" onClick={()=>{const next=taskNo?{ax:-2,ay:1,d:7,angle:30}:{ax:1,ay:-2,d:6,angle:120};setTaskNo(n=>1-n);setTask(next);setResult("idle");onInteraction()}}>New</button><p>Construct segment AB of length {taskNo?6:7} units from A ({taskNo?"1, -2":"-2, 1"}) at angle {taskNo?120:30} deg.</p><div><Field label="Task A x" value={task.ax} onChange={n=>setTask(t=>({...t,ax:n}))}/><Field label="Task A y" value={task.ay} onChange={n=>setTask(t=>({...t,ay:n}))}/></div><Field label="Task length" value={task.d} min={1} max={9} onChange={n=>setTask(t=>({...t,d:n}))}/><Field label="Task angle" value={task.angle} min={0} max={359} onChange={n=>setTask(t=>({...t,angle:n}))}/><button className="check" type="button" onClick={()=>{const expected=taskNo?{ax:1,ay:-2,d:6,angle:120}:{ax:-2,ay:1,d:7,angle:30};setResult(Object.keys(expected).every(k=>task[k as keyof typeof task]===expected[k as keyof typeof expected])?"correct":"incorrect");onInteraction()}}>Check My Construction</button>{result!=="idle"&&<b role="status" className={result}>{result==="correct"?"Correct construction inputs.":"Use the requested start, length and angle."}</b>}<small><Lightbulb/>Tip: Use the handle or angle dial to set direction.</small></Card></div>
    <section className="gl205-steps"><h2>Construction Steps (Compass & Straightedge)</h2><div>{[["Draw Ray","Draw a ray from A in the desired direction."],["Set Compass","Set compass radius to the given length d."],["Mark Point B","With A as center, draw an arc to meet the ray at B."],["Segment AB","Segment AB is the required length d."]].map(([title,body],i)=><article key={title}><h3><i>{i+1}</i>{title}</h3><p>{body}</p><StepArt step={i}/></article>)}</div></section>
    <nav className="gl205-nav" aria-label="Adjacent lessons"><a href="/lessons/geometry/204-segment"><ArrowLeft/><span><small>Previous</small>Segment</span></a><a href="/lessons/geometry/206-ray"><span><small>Next</small>Ray</span><ArrowRight/></a></nav><footer className="gl205-footer"><b>Math Universe</b><span>Interactive math labs, visual proofs, NCERT explorations, graphing, CAS-style tools, and classroom-ready activities.</span><small>© 2026 INDIAN SERVERS PRIVATE LIMITED. NO RIGHT TO REPRODUCE IT.</small><nav><a href="/">Sitemap</a><a href="/docs">Docs</a><a href="/about">About</a></nav></footer>
  </section>
}
