import { ArrowLeft, ArrowRight, Eye, Hand, Languages, Lightbulb, RotateCcw, Share2, Target, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./TangentGraphTargetLesson263.css";

type Tab="interaction"|"explain"|"examples"|"formulas"|"more";
type PracticeRow={answer:string;sign:string;quadrant:string};
const TAU=Math.PI*2,INITIAL_ROWS:PracticeRow[]=[{answer:"√3/3",sign:"+",quadrant:"I"},{answer:"−√3",sign:"−",quadrant:"II"},{answer:"1",sign:"+",quadrant:"III"},{answer:"√3/3",sign:"+",quadrant:"III"}];
const EXPECTED=[{answer:"sqrt3/3",sign:"+",quadrant:"I"},{answer:"-sqrt3",sign:"-",quadrant:"II"},{answer:"1",sign:"+",quadrant:"III"},{answer:"sqrt3/3",sign:"+",quadrant:"III"}];

export default function TangentGraphTargetLesson263({resetToken,onInteraction}:LessonAdapterProps){
 const[theta,setTheta]=useState(Math.PI/3),[tab,setTab]=useState<Tab>("interaction"),[rows,setRows]=useState<PracticeRow[]>(INITIAL_ROWS),[practiceResult,setPracticeResult]=useState<"idle"|"correct"|"incorrect">("correct");
 const model=useMemo(()=>tangentModel(theta),[theta]);
 useEffect(()=>{setTheta(Math.PI/3);setTab("interaction");setRows(INITIAL_ROWS);setPracticeResult("correct");},[resetToken]);
 const updateTheta=(value:number)=>{setTheta(clamp(value,-TAU,TAU));onInteraction();};
 const reset=(notify=true)=>{setTheta(Math.PI/3);setTab("interaction");setRows(INITIAL_ROWS);setPracticeResult("correct");if(notify)onInteraction();};
 const updateRow=(index:number,key:keyof PracticeRow,value:string)=>{setRows((state)=>state.map((row,rowIndex)=>rowIndex===index?{...row,[key]:value}:row));setPracticeResult("idle");onInteraction();};
 const grade=()=>{const correct=EXPECTED.every((expected,index)=>normalize(rows[index].answer)===expected.answer&&normalize(rows[index].sign)===expected.sign&&rows[index].quadrant===expected.quadrant);setPracticeResult(correct?"correct":"incorrect");onInteraction();};
 return <section className="target-tangent-page" data-testid="trigonometry-mockup-0320" data-dedicated-lesson="263" data-object-model="unit-circle-tangent-line-discontinuous-branch-asymptote-model" data-theta={theta.toFixed(6)} data-sin={model.sin.toFixed(6)} data-cos={model.cos.toFixed(6)} data-tan={model.tan===null?"undefined":model.tan.toFixed(6)} data-defined={model.tan!==null} data-quadrant={model.quadrant} data-active-tab={tab} data-practice-result={practiceResult}>
  <header className="target-tangent-header"><div><span>Trigonometry</span><h1>Tangent Graph</h1><p>Understand period and asymptotes.</p><section><b>♙ Intermediate-Advanced</b><b>ϟ Visual Lab</b><b>▣ Trig Graphing / Geometry</b><b>◷ 6-10 min</b></section></div><footer><label><Languages/><select aria-label="Lesson language" defaultValue="en" onChange={onInteraction}><option value="en">English (English)</option><option value="hi">हिन्दी (Hindi)</option></select></label><button type="button" onClick={()=>reset()}><RotateCcw/>Reset</button><button type="button" onClick={()=>{void navigator.clipboard?.writeText(`tan(${degrees(theta)}°) = ${model.tan===null?"undefined":model.tan.toFixed(4)}`);onInteraction();}}><Share2/>Share</button><button type="button" onClick={()=>{document.querySelector(".target-tangent-workspace")?.scrollIntoView({behavior:"smooth"});onInteraction();}}>↗ Workspace</button></footer><nav>{[["interaction","◉ Interaction + visualization"],["explain","▤ Explain"],["examples","♧ Examples"],["formulas","∑ Formulas"],["more","⌁ Know more"]].map(([value,label])=><button key={value} type="button" className={tab===value?"active":""} onClick={()=>{setTab(value as Tab);onInteraction();}}>{label}</button>)}</nav></header>

  <section className="target-tangent-steps">{[[Eye,"Observe","See how tangent is measured on the unit circle and how it creates the graph."],[Hand,"Manipulate","Drag the angle or point on the circle. Watch the tangent length and graph update."],[Lightbulb,"Notice","Note where tangent is positive, negative, zero, and undefined (asymptotes)."],[Target,"Understand","Tangent is the ratio sine/cosine. Vertical asymptotes occur where cos θ = 0."]].map(([Icon,title,text],index)=><article key={String(title)}><Icon/><div><h2>{String(title)}</h2><p>{String(text)}</p></div>{index<3?<span>→</span>:null}</article>)}</section>

  <section className="target-tangent-workspace"><article><h2>UNIT CIRCLE TANGENT CONSTRUCTION</h2><TangentCircle theta={theta} model={model} onTheta={updateTheta}/><section><h3>Drag the point P on the unit circle</h3><div><b>θ = {degrees(theta)}°</b><input aria-label="Tangent angle" type="range" min={-360} max={360} step="1" value={degrees(theta)} onChange={(event)=>updateTheta(Number(event.target.value)*Math.PI/180)}/><input aria-label="Tangent angle degrees" type="number" min={-360} max={360} value={degrees(theta)} onChange={(event)=>updateTheta(Number(event.target.value)*Math.PI/180)}/></div></section><footer><span>cos θ = {model.cos.toFixed(4)}</span><span>sin θ = {model.sin.toFixed(4)}</span><span>tan θ = {model.tan===null?"undefined":model.tan.toFixed(4)}</span><b>{model.quadrant}</b><strong>{model.tan===null?"cos θ = 0":model.tan>0?"tan θ > 0":"tan θ < 0"}</strong></footer></article><div className="target-tangent-link">↔</div><article><h2>TANGENT GRAPH &nbsp; <b>y = tan x</b></h2><TangentPlot theta={theta} onTheta={updateTheta}/><footer><div><b>Domain:</b> x ≠ (2k + 1)π/2, &nbsp; k ∈ Z</div><div><b>Range:</b> R</div><span>━ &nbsp; y = tan x</span><span>┈ &nbsp; Asymptotes &nbsp; x = (2k + 1)π/2</span></footer></article></section>

  <section className="target-tangent-facts">{[["↔","The tangent length is the vertical distance from (1,0) to T on the tangent line."],["zero","tan x = 0 at x = kπ (where the radius lies on the x-axis)."],["∞","The graph is undefined where cos x = 0 → x = (2k + 1)π/2."],["↻","Tangent has period π: tan(x + π) = tan x."]].map(([icon,text])=><article key={text}><i>{icon}</i><p>{text}</p></article>)}</section>

  <section className="target-tangent-notes"><article><h2>FORMULA / RULE</h2><p>Tangent is the ratio of sine to cosine.</p><strong>tan x = <Fraction top="sin x" bottom="cos x" />, &nbsp; cos x ≠ 0</strong><footer><h3>Undefined when cos x = 0</h3><p>→ x = (2k + 1)π/2, &nbsp; k ∈ Z</p></footer></article><article><h2>WORKED EXAMPLE</h2><h3>Example: Find tan(π/3) and plot the point.</h3><p><b>Step 1</b> Evaluate using the ratio.</p><div>tan(π/3) = <Fraction top="sin(π/3)" bottom="cos(π/3)" /> = <Fraction top="√3/2" bottom="1/2" /> = √3 ≈ 1.732</div><p><b>Step 2</b> Plot the point on y = tan x.</p><section><span>x = π/3 ≈ 60° → y = √3<br/><br/><b>Point on graph:</b> (π/3, √3) ≈ (1.047, 1.732)<br/><br/>This matches the interactive graph.</span><WorkedPlot/></section></article><article><h2><TriangleAlert/>MISCONCEPTION WARNING</h2><h3>Common mistake</h3><p>Thinking tangent is always positive.</p><h3>Why it’s wrong</h3><p>tan x is negative in Quadrants II and IV. Check the sign of sin x and cos x.</p><h3>Remember</h3><p>Use tan x = sin x / cos x and quadrant signs.</p><QuadrantSigns/></article></section>

  <section className="target-tangent-practice"><header><div><h2>YOUR TURN: PRACTICE CHALLENGE</h2><p>Use the interactive above to find the exact value, sign, and quadrant for each angle.</p></div><button type="button" onClick={grade}>Check Answers</button></header><table><thead><tr><th>Angle x</th><th>Find tan x (exact)</th><th>Sign</th><th>Quadrant</th><th>Your Answer</th><th>Feedback</th></tr></thead><tbody>{[["π/6","30°"],["2π/3","120°"],["5π/4","225°"],["7π/6","210°"]].map(([angle,label],index)=><tr key={angle}><td>{index+1}. &nbsp; <b>{angle}</b> &nbsp; ({label})</td><td>{INITIAL_ROWS[index].answer}</td><td>{EXPECTED[index].sign}</td><td>{EXPECTED[index].quadrant}</td><td><input aria-label={`Tangent answer ${index+1}`} value={rows[index].answer} onChange={(event)=>updateRow(index,"answer",event.target.value)}/><select aria-label={`Tangent sign ${index+1}`} value={rows[index].sign} onChange={(event)=>updateRow(index,"sign",event.target.value)}><option>+</option><option>−</option></select><select aria-label={`Tangent quadrant ${index+1}`} value={rows[index].quadrant} onChange={(event)=>updateRow(index,"quadrant",event.target.value)}>{["I","II","III","IV"].map((value)=><option key={value}>{value}</option>)}</select></td><td><span className={practiceResult==="correct"?"correct":""}>{practiceResult==="correct"?"Correct! ✓":practiceResult==="incorrect"?"Check row":"Ready"}</span></td></tr>)}</tbody></table></section>
  <nav className="target-tangent-nav"><a href="/lessons/trigonometry/262-cosine-graph"><ArrowLeft/><span><b>Previous</b>Cosine Graph</span></a><a href="/lessons/trigonometry/264-reciprocal-trig-functions"><span><b>Next</b>Reciprocal Trig Functions</span><ArrowRight/></a></nav>
 </section>;
}

function TangentCircle({theta,model,onTheta}:{theta:number;model:ReturnType<typeof tangentModel>;onTheta:(value:number)=>void}){
 const svg=useRef<SVGSVGElement>(null),n=((theta%TAU)+TAU)%TAU,c={x:125,y:164},r=92,p={x:125+r*Math.cos(n),y:164-r*Math.sin(n)},tY=164-r*(model.tan===null?Math.sign(model.sin)*1.5:clamp(model.tan,-1.5,1.5));
 const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(event.type==="pointermove"&&event.buttons!==1)return;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const q=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());let angle=Math.atan2(c.y-q.y,q.x-c.x);if(angle<0)angle+=TAU;onTheta(angle);};
 return <svg ref={svg} viewBox="0 0 320 300" role="img" aria-label="Draggable unit-circle tangent-line construction" onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);move(event);}} onPointerMove={move}><line x1="12" x2="305" y1="164" y2="164"/><line x1="125" x2="125" y1="35" y2="294"/><circle cx="125" cy="164" r="92"/><line x1="217" x2="217" y1="38" y2="294" stroke="#8b5cf6" strokeWidth="2"/><path d={`M125 164L${p.x} ${p.y}`} stroke="#08a9d6" strokeWidth="2.5"/><line x1={p.x} x2="217" y1={p.y} y2={tY} stroke="#64748b" strokeDasharray="4 3"/><line x1="217" x2="217" y1="164" y2={tY} stroke="#8b5cf6" strokeWidth="4"/><circle data-testid="tangent-unit-circle-handle" cx={p.x} cy={p.y} r="6" fill="#078cb4"/><circle cx="217" cy={tY} r="5" fill="#8b5cf6"/><text x={p.x-20} y={p.y-10}>P (cos θ, sin θ)</text><text x="222" y={tY-7}>T (1, tan θ)</text><text x="225" y={(164+tY)/2} fill="#7c3aed">tan θ</text><text x="82" y="177">O (0, 0)</text><text x="219" y="183">(1, 0)</text><text x="300" y="159">x</text><text x="118" y="38">y</text></svg>;
}
function TangentPlot({theta,onTheta}:{theta:number;onTheta:(value:number)=>void}){const svg=useRef<SVGSVGElement>(null),w=390,h=300,pad=25,mid=h/2,scaleY=38,paths=tangentPaths(w,h,pad,scaleY),px=pad+(theta+TAU)/(TAU*2)*(w-pad*2),tan=Math.tan(theta),py=mid-clamp(tan,-4.8,4.8)*scaleY;const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(event.type==="pointermove"&&event.buttons!==1)return;const matrix=svg.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());onTheta((p.x-pad)/(w-pad*2)*TAU*2-TAU);};return <svg ref={svg} viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Draggable tangent graph with vertical asymptotes" onPointerDown={(event)=>{event.currentTarget.setPointerCapture(event.pointerId);move(event);}} onPointerMove={move}><line x1={pad} x2={w-7} y1={mid} y2={mid}/><line x1={w/2} x2={w/2} y1="12" y2={h-12}/>{[-1.5,-.5,.5,1.5].map((multiple)=><line key={multiple} x1={pad+(multiple*Math.PI+TAU)/(TAU*2)*(w-pad*2)} x2={pad+(multiple*Math.PI+TAU)/(TAU*2)*(w-pad*2)} y1="14" y2={h-14} stroke="#a855f7" strokeDasharray="5 4"/>)}{paths.map((path,index)=><path key={index} d={path} fill="none" stroke="#08a9d6" strokeWidth="2"/>)}{Math.abs(Math.cos(theta))>.04?<><line x1={px} x2={px} y1={py} y2={mid} stroke="#f97316" strokeDasharray="4 3"/><circle data-testid="tangent-graph-handle" cx={px} cy={py} r="5" fill="#f97316"/></>:null}<text x="2" y={mid+13}>−2π</text><text x={w/2-5} y={mid+13}>0</text><text x={w-38} y={mid+13}>2π</text><text x={w-7} y={mid-5}>x</text><text x={w/2+5} y="15">y</text></svg>;}
function tangentPaths(w:number,h:number,pad:number,scaleY:number){const paths:string[]=[];let current:string[]=[];for(let i=0;i<=500;i++){const x=-TAU+i/500*TAU*2,y=Math.tan(x);if(Math.abs(Math.cos(x))<.045||Math.abs(y)>3.1){if(current.length>1)paths.push(current.join(" "));current=[];continue;}const px=pad+i/500*(w-pad*2),py=h/2-y*scaleY;current.push(`${current.length?"L":"M"}${px.toFixed(2)} ${py.toFixed(2)}`);}if(current.length>1)paths.push(current.join(" "));return paths;}
function WorkedPlot(){return <svg viewBox="0 0 100 145"><line x1="10" x2="93" y1="110" y2="110" stroke="#64748b"/><line x1="20" x2="20" y1="10" y2="130" stroke="#64748b"/><path d="M20 110 C45 105 55 70 65 18" fill="none" stroke="#08a9d6" strokeWidth="2"/><line x1="65" x2="65" y1="18" y2="110" stroke="#f97316" strokeDasharray="4 3"/><circle cx="65" cy="57" r="5" fill="#f97316"/><text x="47" y="50" fill="#f97316">√3</text><text x="60" y="126">π/3</text></svg>;}
function QuadrantSigns(){return <svg viewBox="0 0 150 120"><circle cx="75" cy="60" r="45" fill="#fff1f2" stroke="#fda4af"/><line x1="20" x2="130" y1="60" y2="60" stroke="#64748b"/><line x1="75" x2="75" y1="10" y2="112" stroke="#64748b"/><text x="48" y="40" fill="#e11d48">−</text><text x="96" y="40" fill="#e11d48">+</text><text x="48" y="88" fill="#e11d48">+</text><text x="96" y="88" fill="#e11d48">−</text></svg>;}
function Fraction({top,bottom}:{top:string;bottom:string}){return <span className="target-tangent-fraction"><span>{top}</span><span>{bottom}</span></span>;}
function tangentModel(theta:number){const sin=Math.sin(theta),cos=Math.cos(theta),tan=Math.abs(cos)<1e-7?null:sin/cos,n=((theta%TAU)+TAU)%TAU,quadrant=n<Math.PI/2?"In quadrant I":n<Math.PI?"In quadrant II":n<Math.PI*1.5?"In quadrant III":"In quadrant IV";return{sin,cos,tan,quadrant};}
function normalize(value:string){return value.toLowerCase().replaceAll(" ","").replaceAll("√","sqrt").replaceAll("−","-");}function degrees(value:number){return Math.round(value*180/Math.PI);}function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
