import { ArrowLeft, ArrowRight, Lightbulb, RotateCcw, Share2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { PointerEvent } from "react";
import type { LessonAdapterProps } from "../types";
import "./VectorLineTargetLesson194.css";

type Point={x:number;y:number};
const A0={x:1,y:2},V0={x:3,y:1},clamp=(n:number,min=-5,max=5)=>Math.max(min,Math.min(max,Math.round(n*2)/2)),at=(a:Point,v:Point,t:number)=>({x:a.x+t*v.x,y:a.y+t*v.y}),fmt=(n:number)=>Number.isInteger(n)?String(n):n.toFixed(1);

function LineGraph({a,v,t,trail,steps,onT}:{a:Point;v:Point;t:number;trail:boolean;steps:boolean;onT:(n:number)=>void}){
 const ref=useRef<SVGSVGElement>(null),drag=useRef(false),unit=34,sx=(x:number)=>205+x*unit,sy=(y:number)=>260-y*unit,r=at(a,v,t),p0=at(a,v,-5),p1=at(a,v,5),move=(e:PointerEvent<SVGSVGElement>)=>{if(!drag.current)return;const b=ref.current!.getBoundingClientRect(),p={x:(((e.clientX-b.left)/b.width)*520-205)/unit,y:(260-((e.clientY-b.top)/b.height)*360)/unit},d=v.x*v.x+v.y*v.y;onT(clamp(((p.x-a.x)*v.x+(p.y-a.y)*v.y)/d,-3,3))};
 return <svg ref={ref} className="vl194-graph" viewBox="0 0 520 360" preserveAspectRatio="none" aria-label="Parametric vector line graph" onPointerMove={move} onPointerUp={()=>{drag.current=false}} onPointerLeave={()=>{drag.current=false}}><defs><pattern id="vl194-grid" width={unit} height={unit} patternUnits="userSpaceOnUse"><path d={`M${unit} 0H0V${unit}`} fill="none" stroke="#dfe7ee"/></pattern><marker id="vl194-arrow" markerWidth="9" markerHeight="9" refX="8" refY="4.5" orient="auto"><path d="M0 0L9 4.5L0 9Z" fill="#0799bb"/></marker></defs><rect width="520" height="360" fill="url(#vl194-grid)"/><line x1="0" x2="520" y1={sy(0)} y2={sy(0)} className="axis"/><line x1={sx(0)} x2={sx(0)} y1="0" y2="360" className="axis"/><line x1={sx(p0.x)} y1={sy(p0.y)} x2={sx(p1.x)} y2={sy(p1.y)} className="line"/>{trail&&<line x1={sx(a.x)} y1={sy(a.y)} x2={sx(r.x)} y2={sy(r.y)} className="trail"/>}{steps&&[-1,0,1,2].map(n=>{const p=at(a,v,n);return <g key={n}><circle cx={sx(p.x)} cy={sy(p.y)} r="5" className={n===0?"base":"step"}/><text x={sx(p.x)-8} y={sy(p.y)+24}>t = {n}</text></g>})}<line x1={sx(a.x)} y1={sy(a.y)} x2={sx(a.x+v.x)} y2={sy(a.y+v.y)} className="direction" markerEnd="url(#vl194-arrow)"/><circle data-testid="line-r-tip" role="slider" aria-label="Point R on line" tabIndex={0} cx={sx(r.x)} cy={sy(r.y)} r="9" className="moving" onPointerDown={e=>{drag.current=true;e.currentTarget.setPointerCapture(e.pointerId)}}/><text x={sx(r.x)-8} y={sy(r.y)-22} className="moving-label">R(t)</text><text x={sx(r.x)-16} y={sy(r.y)-8} className="moving-label">t = {fmt(t)}</text><text x={sx(a.x+v.x)-25} y={sy(a.y+v.y)+25} className="direction-label">v = ({fmt(v.x)}, {fmt(v.y)})</text></svg>
}

function Stepper({label,value,onValue}:{label:string;value:number;onValue:(n:number)=>void}){return <label><span>{label}</span><button aria-label={`Decrease ${label}`} onClick={()=>onValue(clamp(value-1))}>−</button><input aria-label={`${label} value`} type="number" value={value} onChange={e=>onValue(clamp(+e.target.value))}/><button aria-label={`Increase ${label}`} onClick={()=>onValue(clamp(value+1))}>+</button></label>}

export default function VectorLineTargetLesson194({resetToken,onInteraction}:LessonAdapterProps){
 const [a,setA]=useState(A0),[v,setV]=useState(V0),[t,setT]=useState(1.5),[trail,setTrail]=useState(true),[steps,setSteps]=useState(true),[table,setTable]=useState(true),[tab,setTab]=useState(0),[language,setLanguage]=useState("English (English)"),[shared,setShared]=useState(false),[challenge,setChallenge]=useState(false);const r=at(a,v,t),slope=v.x===0?"undefined":fmt(v.y/v.x),interact=()=>onInteraction();
 useEffect(()=>{setA(A0);setV(V0);setT(1.5);setTrail(true);setSteps(true);setTable(true);setTab(0);setLanguage("English (English)");setShared(false);setChallenge(false)},[resetToken]);
 const reset=()=>{setA(A0);setV(V0);setT(1.5);setTrail(true);setSteps(true);setTable(true);setChallenge(false);interact()};
 return <main className="vl194-page" data-testid="vector-mockup-0251" data-dedicated-lesson="194" data-object-model="parametric-vector-line-point-direction-parameter-trail-table-challenge" data-a={`${a.x}:${a.y}`} data-v={`${v.x}:${v.y}`} data-t={t} data-r={`${r.x}:${r.y}`} data-trail={trail} data-steps={steps} data-table={table} data-tab={tab} data-language={language} data-shared={shared} data-challenge={challenge}>
  <header className="vl194-header"><section><span>GEOMETRY</span><span>VECTORS</span><h1>Vector Equation of a Line</h1><p>Represent lines parametrically.</p><aside><b>♙ Intermediate-Advanced</b><b>ϟ Applied Lab</b><b>▣ Vector Tools</b><b>◷ 6-10 min</b></aside></section><nav><select aria-label="Lesson language" value={language} onChange={e=>{setLanguage(e.target.value);interact()}}><option>English (English)</option><option>हिन्दी (Hindi)</option></select><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>{setShared(true);navigator.clipboard?.writeText(location.href).catch(()=>undefined);interact()}}><Share2/>{shared?"Shared":"Share"}</button><a href="/workspace/geometry">Workspace</a></nav></header>
  <nav className="vl194-tabs">{["Interact","Learn","Examples","Formula","Practice"].map((name,index)=><button key={name} className={tab===index?"active":""} onClick={()=>{setTab(index);interact()}}>{name}</button>)}</nav>
  <section className="vl194-main"><article className="vl194-work"><h2>PARAMETRIC LINE WORKBENCH</h2><header><b>↗ <span>Direction v<br/>({fmt(v.x)}, {fmt(v.y)})</span></b><b>● <span>Point R(t)<br/>r({fmt(t)}) = ({fmt(r.x)}, {fmt(r.y)})</span></b><b>– – <span>t trail<br/>-3 to 3</span></b></header><LineGraph a={a} v={v} t={t} trail={trail} steps={steps} onT={n=>{setT(n);interact()}}/></article><aside className="vl194-controls"><h2>CONTROLS</h2><label className="parameter"><b>Parameter t</b><span>-3</span><input aria-label="Line parameter t" type="range" min="-3" max="3" step=".5" value={t} onChange={e=>{setT(+e.target.value);interact()}}/><span>3</span><input aria-label="Exact line parameter t" type="number" min="-3" max="3" step=".5" value={t} onChange={e=>{setT(clamp(+e.target.value,-3,3));interact()}}/></label><section><h3>Point a (fixed on line)</h3><Stepper label="a x" value={a.x} onValue={n=>{setA({...a,x:n});interact()}}/><Stepper label="a y" value={a.y} onValue={n=>{setA({...a,y:n});interact()}}/><output>a = ({fmt(a.x)}, {fmt(a.y)})</output></section><section><h3>Direction vector v</h3><Stepper label="v x" value={v.x} onValue={n=>{setV({...v,x:n});interact()}}/><Stepper label="v y" value={v.y} onValue={n=>{setV({...v,y:n});interact()}}/><output>v = ({fmt(v.x)}, {fmt(v.y)})</output></section><section className="vl194-toggles"><h3>Display options</h3>{[["Show t trail",trail,setTrail],["Show direction steps",steps,setSteps],["Show point table",table,setTable]].map(([name,value,setter])=><label key={String(name)}>{name}<input aria-label={String(name)} type="checkbox" checked={value as boolean} onChange={()=>{(setter as (fn:(x:boolean)=>boolean)=>void)(x=>!x);interact()}}/></label>)}</section></aside></section>
  <section className="vl194-lower"><article className={!table?"hidden":""}><h2>POINTS ON THE LINE r = a + t v</h2><table><thead><tr><th>t</th><th>r(t) = a + t v</th><th>Coordinates</th></tr></thead><tbody>{[-1,0,1,t,2].map((n,index)=>{const p=at(a,v,n);return <tr key={`${n}-${index}`} className={n===t?"active":""}><td>{fmt(n)}</td><td>({fmt(a.x)}, {fmt(a.y)}) + ({fmt(n)})({fmt(v.x)}, {fmt(v.y)})</td><td>({fmt(p.x)}, {fmt(p.y)})</td></tr>})}</tbody></table></article><article><h2>CURRENT RESULT</h2><main><output>r = a + t v</output><p>a = ({fmt(a.x)}, {fmt(a.y)})<br/>v = ({fmt(v.x)}, {fmt(v.y)})<br/>t = {fmt(t)}</p><hr/><output>r({fmt(t)}) = ({fmt(a.x)}, {fmt(a.y)}) + {fmt(t)}({fmt(v.x)}, {fmt(v.y)})<br/>= ({fmt(r.x)}, {fmt(r.y)})</output></main><aside><b>Direction ratio<br/>dy/dx = {fmt(v.y)}/{fmt(v.x)}</b><b>Slope of line<br/>m = {slope}</b></aside></article></section>
  <section className="vl194-tip"><Lightbulb/><span><b>Move t to travel along the same line</b><small>Changing t moves point R(t) along the line in the direction of v.</small></span><button onClick={()=>{setT(2);setChallenge(true);interact()}}>Try: find t when r = (7, 4) <ArrowRight/></button></section>
  <nav className="vl194-nav"><a href="/lessons/geometry/193-linear-combinations"><ArrowLeft/><span>PREVIOUS<b>Linear Combinations</b></span></a><a href="/lessons/geometry/195-vector-equation-of-a-plane"><span>NEXT<b>Vector Equation of a Plane</b></span><ArrowRight/></a></nav>
  <footer className="vl194-footer"><b>Math Universe</b><span>Interactive math labs, visual proofs, NCERT explorations, graphing, CAS-style tools, and classroom-ready activities.</span><small>© 2026 INDIAN SERVERS PRIVATE LIMITED.</small><nav><a href="/sitemap">Sitemap</a><a href="/docs">Docs</a><a href="/about">About</a></nav></footer>
 </main>
}
