import { Check, RotateCcw } from "lucide-react";
import { useMemo, useState, type DragEvent } from "react";
import type { LessonAdapterProps } from "../types";
import { expectedPlacements, shadeIncludes, universe, vennSummary, type VennPlacements, type VennRegion, type VennShade } from "./vennDiagramsLessonModel";
import "./VennDiagramsLesson510.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

const labels: Record<VennRegion,string> = { aOnly:"A-only", intersection:"A ∩ B", bOnly:"B-only", outside:"Outside" };

export default function VennDiagramsLesson510({resetToken,onInteraction}:LessonAdapterProps){return <VennActivity key={resetToken} onInteraction={onInteraction}/>}

function VennActivity({onInteraction}:Pick<LessonAdapterProps,"onInteraction">){
  const [placements,setPlacements]=useState<VennPlacements>(expectedPlacements);
  const [shade,setShade]=useState<VennShade>("none");
  const [checked,setChecked]=useState(false);
  const [practice,setPractice]=useState({only:[3,9],intersection:"0.25",union:"0.85",complement:"true"});
  const summary=useMemo(()=>vennSummary(placements),[placements]);
  const move=(value:number,region:VennRegion)=>{setPlacements(current=>({...current,[value]:region}));setChecked(false);onInteraction();};
  const drop=(event:DragEvent,region:VennRegion)=>{event.preventDefault();const value=Number(event.dataTransfer.getData("outcome"));if(universe.includes(value))move(value,region);};
  const reset=()=>{setPlacements(expectedPlacements);setShade("none");setChecked(false);onInteraction();};
  const setText=(values:number[])=>`{${values.join(",")}}`;
  return <div className="vd510" data-testid="probability-mockup-0473" data-target-family="probability-and-distributions">
    <header className="vd510-hero"><span>DATA AND PROBABILITY</span><h2>Venn Diagrams</h2><p>Understand, build and solve with Venn diagrams.</p><button type="button" onClick={reset}><RotateCcw size={14}/>Reset</button></header>
    <nav aria-label="Lesson sections"><b>Interact</b><span>Learn</span><span>Example</span><span>Formula</span><span>Practice</span></nav>
    <section className="vd510-classify"><header><div><h3>Classify outcomes</h3><p>Drag each outcome to the correct region of the Venn diagram.</p></div><article><span>Total outcomes<b>20</b></span><span>Placed<b>20 / 20</b></span><span>Correct<b>{summary.correct}</b></span><button type="button" onClick={()=>{setChecked(true);onInteraction();}}><Check size={14}/>Check</button></article></header><div className="vd510-workspace">
      <aside className="vd510-outcomes"><h3>Outcomes to classify</h3><p>Drag each item to A-only, A ∩ B, B-only, or Outside.</p><div>{universe.map(value=><button type="button" draggable key={value} onDragStart={event=>event.dataTransfer.setData("outcome",String(value))} onClick={()=>move(value,placements[value]==="aOnly"?"intersection":placements[value]==="intersection"?"bOnly":placements[value]==="bOnly"?"outside":"aOnly")}>{value}</button>)}</div></aside>
      <article className={`vd510-diagram shade-${shade}`}><h3>Sample Space U (20 outcomes)</h3><div className="vd510-board"><DropRegion region="aOnly" values={summary.aOnly} shade={shade} onDrop={drop}/><DropRegion region="intersection" values={summary.intersection} shade={shade} onDrop={drop}/><DropRegion region="bOnly" values={summary.bOnly} shade={shade} onDrop={drop}/><DropRegion region="outside" values={summary.outside} shade={shade} onDrop={drop}/><i className="circle-a">A</i><i className="circle-b">B</i></div></article>
      <aside className="vd510-regions"><h3>Regions</h3><p>Counts & probabilities</p>{(["aOnly","intersection","bOnly","outside"] as VennRegion[]).map(region=>{const values=summary[region];return <article key={region}><span>{labels[region]}<b>{values.length}</b></span><strong>P = {values.length}/20 = {(values.length/20).toFixed(3)}</strong></article>})}</aside>
    </div><div className="vd510-tools"><article><h3>Quick shading</h3>{[["Shade A","a"],["Shade B","b"],["Shade A ∪ B","union"],["Shade A ∩ B","intersection"],["Clear","none"]].map(([label,value])=><button type="button" className={shade===value?"active":""} key={value} onClick={()=>{setShade(value as VennShade);onInteraction();}}>{label}</button>)}</article><article><h3>Set notation (live)</h3><p>A = {setText(summary.a)}</p><p>B = {setText(summary.b)}</p><p>U = {setText(universe)}</p></article><article><h3>Live results</h3><p>n(A) = {summary.a.length}</p><p>n(B) = {summary.b.length}</p><p>n(A ∩ B) = {summary.intersection.length}</p><p>n(A ∪ B) = {summary.union.length}</p><p>n(Aᶜ) = {summary.notA.length}</p><p>n(Bᶜ) = {summary.notB.length}</p></article></div></section>
    <section className="vd510-details"><article><h3>Experiment setup</h3><p>A bag contains 20 numbered balls (1–20). A ball is drawn at random.</p><hr/><b>Events</b><p>A: The number is in {setText(summary.a)}<br/>B: The number is in {setText(summary.b)}</p><hr/><b>Assumption</b><p>All outcomes are equally likely.</p></article><div><article><h3>Sample Space</h3><p>U = {setText(universe)}<br/>|U| = 20</p></article><article><h3>Calculations</h3><p>P(A) = {summary.a.length}/20 = {(summary.a.length/20).toFixed(3)}</p><p>P(B) = {summary.b.length}/20 = {(summary.b.length/20).toFixed(3)}</p><p>P(A ∩ B) = {summary.intersection.length}/20 = {(summary.intersection.length/20).toFixed(3)}</p><p>P(A ∪ B) = {summary.union.length}/20 = {(summary.union.length/20).toFixed(3)}</p></article></div><article><h3>Result summary</h3>{[["P(A)",summary.a.length],["P(B)",summary.b.length],["P(A ∩ B)",summary.intersection.length],["P(A ∪ B)",summary.union.length],["P(Aᶜ)",summary.notA.length],["P(Bᶜ)",summary.notB.length]].map(([label,count])=><p key={String(label)}>{label}<b>{(Number(count)/20).toFixed(3)}</b><Check size={13}/></p>)}<strong>All probabilities are derived from 20 equally likely outcomes.</strong></article></section>
    <section className="vd510-rules"><article><h3>Correct Rule</h3><b>Inclusion–Exclusion Principle</b><p>P(A ∪ B) = P(A) + P(B) − P(A ∩ B)</p></article><article><h3>Worked check</h3><p>{(summary.a.length/20).toFixed(3)} + {(summary.b.length/20).toFixed(3)} − {(summary.intersection.length/20).toFixed(3)} = {(summary.union.length/20).toFixed(3)}</p></article><article><h3>Misconception Guard</h3><p>Do not add P(A) and P(B) directly. The overlap would be counted twice.</p></article></section>
    <section className="vd510-practice"><h3>Practice – Check your understanding</h3><div><article><b>1. Which outcomes are in A-only?</b>{[3,9,10,15].map(value=><label key={value}><input type="checkbox" checked={practice.only.includes(value)} onChange={event=>setPractice(current=>({...current,only:event.target.checked?[...current.only,value]:current.only.filter(item=>item!==value)}))}/>{value}</label>)}</article><PracticeRadio title="2. What is P(A ∩ B)?" value={practice.intersection} options={["0.15","0.20","0.25","0.30"]} onChange={value=>setPractice(current=>({...current,intersection:value}))}/><PracticeRadio title="3. What is P(A ∪ B)?" value={practice.union} options={["0.65","0.70","0.85","0.90"]} onChange={value=>setPractice(current=>({...current,union:value}))}/><PracticeRadio title="4. True or False? P(Aᶜ) = 1 − P(A)" value={practice.complement} options={["true","false"]} onChange={value=>setPractice(current=>({...current,complement:value}))}/></div>{checked&&<p className="vd510-feedback">{summary.correct===20?"All 20 outcomes are correctly classified.":`${summary.correct} of 20 outcomes are correct. Keep adjusting the regions.`}</p>}</section>
    <footer><button type="button" onClick={reset}><RotateCcw size={14}/>Reset lesson</button><span>Previous: Tree Diagrams &nbsp; Next: Two-Way Tables →</span></footer>
      <LessonTopicStudyBoard lessonId={510} alwaysVisible onInteraction={onInteraction} />

  </div>;
}

function DropRegion({region,values,shade,onDrop}:{region:VennRegion;values:number[];shade:VennShade;onDrop:(event:DragEvent,region:VennRegion)=>void}){return <div className={`drop-${region} ${shadeIncludes(region,shade)?"shaded":""}`} onDragOver={event=>event.preventDefault()} onDrop={event=>onDrop(event,region)}>{values.map(value=><button type="button" draggable key={value} onDragStart={event=>event.dataTransfer.setData("outcome",String(value))}>{value}</button>)}</div>}
function PracticeRadio({title,value,options,onChange}:{title:string;value:string;options:string[];onChange:(value:string)=>void}){return <article><b>{title}</b>{options.map(option=><label key={option}><input type="radio" checked={value===option} onChange={()=>onChange(option)}/>{option}</label>)}</article>}
