import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`equation input retains solution model and plot at ${width}`,async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(45000);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
 await page.goto('/lessons/core-workspaces/30-equation-input',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="30"]');await lesson.waitFor({timeout:45000});const input=lesson.getByRole('textbox',{name:'Equation input'}),check=lesson.getByRole('button',{name:'Check Equation',exact:true}),graph=lesson.locator('.graph-card [data-lesson-graph-workspace]'),frame=graph.locator('[data-graph-family]');
 const verify=async(x:number,y:number)=>{await expect(lesson).toHaveAttribute('data-solution',Number.isInteger(x)?String(x):x.toFixed(2));await expect(lesson).toHaveAttribute('data-solved-y',Number.isInteger(y)?String(y):y.toFixed(2));
 const p=await graph.locator('circle[role="button"]').evaluate(e=>{const svg=(e as SVGCircleElement).ownerSVGElement!,v=svg.viewBox.baseVal,f=svg.closest('[data-graph-family]')!,xmin=Number(f.getAttribute('data-x-min')),xmax=Number(f.getAttribute('data-x-max')),ymin=Number(f.getAttribute('data-y-min')),ymax=Number(f.getAttribute('data-y-max'));return {x:xmin+(Number(e.getAttribute('cx'))-48)/(v.width-72)*(xmax-xmin),y:ymax-(Number(e.getAttribute('cy'))-24)/(v.height-64)*(ymax-ymin)};});expect(p.x).toBeCloseTo(x,5);expect(p.y).toBeCloseTo(y,5);
 };
 await expect(input).toHaveValue('2x + 3 = 11');await expect(lesson).toHaveAttribute('data-checks','1');await verify(4,11);await expect(lesson.locator('[data-graph-family="balance"]')).toHaveAttribute('aria-label','2x + 3 equals 11');
 for(const [example,x,y] of [['3x - 2 = 7',3,7],['x + 5 = 2x - 1',6,11],['4y = y + 12',4,16]] as const){await lesson.getByRole('button',{name:example,exact:true}).click();await expect(lesson).toHaveAttribute('data-checked','false');await expect(lesson.locator('.summary-panel')).toContainText('x = ?');await verify(x,y);await check.click();await expect(lesson.locator('.solution-checker em')).toHaveText('TRUE');}
 await input.fill('0.5*x + 0.25 = 1');await verify(1.5,1);await check.click();await expect(lesson.locator('.summary-panel')).toContainText('x = 1.50');await expect(lesson.locator('[data-graph-family="balance"]')).toHaveAttribute('aria-label','0.50x + 0.25 equals 1');
 for(const invalid of ['x=x','x=x+1','x^2=4','x@2=4','2x=','x=2=3']){await input.fill(invalid);await expect(lesson).toHaveAttribute('data-valid','false');await expect(check).toBeDisabled();await expect(graph).toContainText('Reference example: 2x + 3 = 11');}
 await lesson.getByRole('button',{name:'Clear',exact:true}).click();await expect(input).toHaveValue('');await input.fill('2x + 3 = 11');await check.click();await verify(4,11);
 const original=await frame.getAttribute('data-x-min');await graph.getByRole('button',{name:'Zoom graph in',exact:true}).click();await expect(frame).not.toHaveAttribute('data-x-min',original!);await verify(4,11);await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await graph.locator('svg').focus();await page.keyboard.press('ArrowRight');await expect(frame).not.toHaveAttribute('data-x-min',original!);await graph.getByRole('button',{name:'Reset graph view',exact:true}).click();await expect(frame).toHaveAttribute('data-x-min',original!);
 for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);for(const button of await lesson.locator('.equation-entry button').all()){const box=await button.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual(width);}await page.screenshot({path:`test-evidence/shared-lesson-graphs/30/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}
 expect(errors).toEqual([]);
});
