import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`Function Plotter traces exact rules at ${width}`,async({page,context})=>{
 test.setTimeout(90000);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('/lessons/graphs-and-functions/40-function-plotter',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="40"]');await lesson.waitFor({timeout:45000});const graph=lesson.locator('[data-lesson-graph-workspace]'),frame=graph.locator('[data-graph-family]'),svg=graph.locator('svg');const rules=[(x:number)=>x*x-2,(x:number)=>.8*x+1,(x:number)=>Math.sin(x)];
 const verify=async(x:number)=>{await expect(lesson).toHaveAttribute('data-trace',String(x));for(let i=0;i<3;i++){const id='fgh'[i],y=rules[i](x),point=graph.getByTestId(`function-${id}-trace-40`);const f=await frame.evaluate(e=>Object.fromEntries(['x-min','x-max','y-min','y-max','plot-left','plot-top','plot-width','plot-height'].map(k=>[k,Number(e.getAttribute('data-'+k))])));if(y<f['y-min']||y>f['y-max']){await expect(point).toHaveCount(0);continue;}expect(await point.getAttribute('aria-label')).toContain(`${id}(${x}) = ${y.toFixed(3)}: (${x}, `);const p=await point.evaluate(e=>({x:Number(e.getAttribute('cx')),y:Number(e.getAttribute('cy'))}));expect(p.x).toBeCloseTo(f['plot-left']+(x-f['x-min'])/(f['x-max']-f['x-min'])*f['plot-width'],4);expect(p.y).toBeCloseTo(f['plot-top']+(f['y-max']-y)/(f['y-max']-f['y-min'])*f['plot-height'],4);}await expect(lesson.locator('main').getByText(rules[0](x).toFixed(3),{exact:true})).toBeVisible();};
 await verify(1.5);for(let i=0;i<3;i++){const points=await graph.locator(`[data-series-id="${'fgh'[i]}"] polyline`).evaluate(e=>{const f=e.closest('[data-graph-family]')!,a=(k:string)=>Number(f.getAttribute('data-'+k));return e.getAttribute('points')!.split(' ').map(pair=>{const [px,py]=pair.split(',').map(Number);return {x:a('x-min')+(px-a('plot-left'))/a('plot-width')*(a('x-max')-a('x-min')),y:a('y-max')-(py-a('plot-top'))/a('plot-height')*(a('y-max')-a('y-min'))};});});expect(points).toHaveLength(601);for(const p of points)expect(p.y).toBeCloseTo(rules[i](p.x),9);}const trace=lesson.getByRole('slider',{name:'Trace x',exact:true});await expect(trace).toHaveAttribute('min','-5');await expect(trace).toHaveAttribute('max','5');await expect(trace).toHaveAttribute('step','0.5');await trace.focus();await page.keyboard.press('Home');for(let x=-5;x<=5;x+=.5){await verify(x);if(x<5)await page.keyboard.press('ArrowRight');}await expect(lesson.getByRole('button',{name:'Increase Trace x',exact:true})).toBeDisabled();await verify(5);await lesson.getByRole('button',{name:'Decrease Trace x',exact:true}).click();await verify(4.5);
 for(const id of ['f','g']){const toggle=lesson.getByRole('checkbox',{name:`Show ${id}(x)`,exact:true});await expect(toggle).toBeChecked();await toggle.uncheck();await expect(graph.locator(`[data-series-id="${id}"]`)).toHaveCount(0);await expect(lesson.getByRole('cell',{name:'hidden',exact:true})).toHaveCount(1);await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toBeChecked();await expect(graph.locator(`[data-series-id="${id}"]`)).toHaveCount(1);await verify(4.5);}
 await lesson.getByRole('checkbox',{name:'Show f(x)',exact:true}).uncheck();await lesson.getByRole('checkbox',{name:'Show g(x)',exact:true}).uncheck();await expect(graph.locator('[data-series-id="h"]')).toHaveCount(1);await lesson.getByRole('button',{name:'Toggle guides'}).click();await lesson.getByRole('button',{name:'Inspector',exact:true}).click();await expect(lesson).toHaveAttribute('data-guides','true');await expect(graph.getByTestId('function-h-trace-40')).toBeFocused();
 await lesson.getByRole('button',{name:'Reset view',exact:true}).click();await verify(1.5);await expect(lesson.getByRole('checkbox',{name:'Show f(x)',exact:true})).toBeChecked();await expect(lesson.getByRole('checkbox',{name:'Show g(x)',exact:true})).toBeChecked();await lesson.getByRole('button',{name:'Inspector',exact:true}).click();await expect(graph.getByTestId('function-f-trace-40')).toBeFocused();await page.keyboard.press('ArrowRight');await verify(2);
 const screen=async(x:number,y:number)=>{await svg.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));return svg.evaluate((e,p)=>{const s=e as SVGSVGElement,r=s.getBoundingClientRect(),v=s.viewBox.baseVal,f=s.closest('[data-graph-family]')!;const a=(k:string)=>Number(f.getAttribute('data-'+k));return {x:r.x+(a('plot-left')+(p.x-a('x-min'))/(a('x-max')-a('x-min'))*a('plot-width'))*r.width/v.width,y:r.y+(a('plot-top')+(a('y-max')-p.y)/(a('y-max')-a('y-min'))*a('plot-height'))*r.height/v.height};},{x,y});};
 let p=await screen(2,2),q=await screen(-1,1);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:4});await page.mouse.up();await verify(-1);p=await screen(-1,-1);q=await screen(1,1);const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[q]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await verify(1);
 await lesson.getByRole('button',{name:'Toggle guides'}).click();await expect(graph.locator('circle')).toHaveCount(0);await expect(graph.locator('.lesson-cartesian-ticks text')).toHaveCount(2);await lesson.getByRole('button',{name:'Toggle guides'}).click();await verify(1);await lesson.getByRole('button',{name:'Move graph',exact:true}).click();await expect(svg).toBeFocused();await page.keyboard.press('ArrowRight');await expect(frame).not.toHaveAttribute('data-x-min','-6');await graph.getByRole('button',{name:'Zoom graph in',exact:true}).click();await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await lesson.getByRole('button',{name:'Fit',exact:true}).click();await expect(frame).toHaveAttribute('data-x-min','-6');await verify(1.5);await lesson.getByRole('button',{name:'Share',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('f(1.5) = 0.250; g(1.5) = 2.200; h(1.5) = 0.997');await graph.getByRole('button',{name:'Reset graph view',exact:true}).click();
 await expect(lesson).toContainText('f & g: (-1.378, -0.102); (2.178, 2.742)');await expect(lesson).toContainText('f & h: (-1.062, -0.873); (1.728, 0.988)');await expect(lesson).toContainText('g & h: (-2.235, -0.788)');
 for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-evidence/shared-lesson-graphs/40/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}expect(errors).toEqual([]);
});



