import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`Inequality Grapher clips the feasible region at ${width}`,async({page,context})=>{
 test.setTimeout(90000);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('/lessons/graphs-and-functions/42-inequality-grapher',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="42"]');await lesson.waitFor({timeout:45000});const graph=lesson.locator('[data-lesson-graph-workspace]'),frame=graph.locator('[data-graph-family]'),svg=graph.locator('svg');
 const world=async(selector:string)=>graph.locator(selector).evaluate(e=>{const f=e.closest('[data-graph-family]')!,a=(k:string)=>Number(f.getAttribute('data-'+k));const pixels=e.tagName==='circle'?[[Number(e.getAttribute('cx')),Number(e.getAttribute('cy'))]]:e.getAttribute('points')!.split(' ').map(p=>p.split(',').map(Number));return pixels.map(([px,py])=>({x:a('x-min')+(px-a('plot-left'))/a('plot-width')*(a('x-max')-a('x-min')),y:a('y-max')-(py-a('plot-top'))/a('plot-height')*(a('y-max')-a('y-min'))}));});
 const verify=async(x:number)=>{await expect(lesson).toHaveAttribute('data-trace',String(x));const [upper]=await world('[data-testid="inequality-upper-42"]'),[lower]=await world('[data-testid="inequality-lower-42"]');expect(upper.x).toBeCloseTo(x,10);expect(lower.x).toBeCloseTo(x,10);expect(upper.y).toBeCloseTo(.8*x+1,10);expect(lower.y).toBeCloseTo(-.5*x+2,10);await expect(graph.getByTestId('inequality-upper-42')).toHaveAttribute('data-included','true');await expect(graph.getByTestId('inequality-lower-42')).toHaveAttribute('data-included','false');await expect(graph.locator('[data-series-id="trace-solution"]')).toHaveCount(x>10/13?1:0);await expect(graph.locator('.lesson-graph-observation')).toContainText(x>10/13?`${(-.5*x+2).toFixed(3)} < y ≤ ${(.8*x+1).toFixed(3)}`:'No overlap');};
 const verifyRegions=async()=>{for(const id of ['region-a','region-b','overlap']){const points=await world(`[data-series-id="${id}"] polygon`);expect(points.length).toBeGreaterThanOrEqual(3);for(const p of points){if(id!=='region-b')expect(p.y-.8*p.x-1).toBeLessThan(1e-9);if(id!=='region-a')expect(-.5*p.x+2-p.y).toBeLessThan(1e-9);}if(id==='overlap')expect(Math.min(...points.map(p=>p.x))).toBeCloseTo(10/13,9);}};
 await verify(1.5);await verifyRegions();await expect(frame).toHaveAttribute('data-x-min','-6');await expect(graph.locator('[data-series-id="boundary-b"] polyline')).toHaveAttribute('stroke-dasharray','10 8');await expect(graph.locator('[data-series-id="boundary-a"] polyline')).not.toHaveAttribute('stroke-dasharray');await expect(lesson.locator('main').getByText('false',{exact:true})).toBeVisible();
 const trace=lesson.getByRole('slider',{name:'Trace x',exact:true});await expect(trace).toHaveAttribute('min','-5');await expect(trace).toHaveAttribute('max','5');await expect(trace).toHaveAttribute('step','0.5');await trace.focus();await page.keyboard.press('Home');for(let x=-5;x<=5;x+=.5){await verify(x);if(x<5)await page.keyboard.press('ArrowRight');}await expect(lesson.getByRole('button',{name:'Increase Trace x',exact:true})).toBeDisabled();await verify(5);await lesson.getByRole('button',{name:'Decrease Trace x',exact:true}).click();await verify(4.5);
 const beforeOverlap=await world('[data-series-id="overlap"] polygon');for(const id of ['A','B']){const toggle=lesson.getByRole('checkbox',{name:`Show Boundary ${id}`,exact:true}),lower=id.toLowerCase();await expect(toggle).toBeChecked();await toggle.uncheck();await expect(graph.locator(`[data-series-id="boundary-${lower}"]`)).toHaveCount(0);await expect(graph.locator(`[data-series-id="region-${lower}"]`)).toHaveCount(0);await expect(graph.getByTestId(id==='A'?'inequality-upper-42':'inequality-lower-42')).toHaveCount(0);expect(await world('[data-series-id="overlap"] polygon')).toEqual(beforeOverlap);await expect(graph.locator('.lesson-graph-observation')).toContainText('overlap still uses both inequalities');await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toBeChecked();await verify(4.5);await verifyRegions();}
 await lesson.getByRole('checkbox',{name:'Show Boundary A',exact:true}).uncheck();await lesson.getByRole('checkbox',{name:'Show Boundary B',exact:true}).uncheck();await expect(graph.locator('[data-series-id^="boundary-"]')).toHaveCount(0);await expect(graph.locator('[data-series-id="overlap"]')).toHaveCount(1);await lesson.getByRole('button',{name:'Toggle guides'}).click();await lesson.getByRole('button',{name:'Inspector',exact:true}).click();await expect(lesson).toHaveAttribute('data-guides','true');await expect(graph.getByTestId('inequality-sample-42')).toBeFocused();
 await lesson.getByRole('button',{name:'Reset view',exact:true}).click();await verify(1.5);await expect(lesson.getByRole('checkbox',{name:'Show Boundary A',exact:true})).toBeChecked();await expect(lesson.getByRole('checkbox',{name:'Show Boundary B',exact:true})).toBeChecked();await graph.getByTestId('inequality-lower-42').focus();await page.keyboard.press('ArrowRight');await verify(2);
 const screen=async(x:number,y:number)=>{await svg.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));return svg.evaluate((e,p)=>{const s=e as SVGSVGElement,r=s.getBoundingClientRect(),v=s.viewBox.baseVal,f=s.closest('[data-graph-family]')!;const a=(k:string)=>Number(f.getAttribute('data-'+k));return {x:r.x+(a('plot-left')+(p.x-a('x-min'))/(a('x-max')-a('x-min'))*a('plot-width'))*r.width/v.width,y:r.y+(a('plot-top')+(a('y-max')-p.y)/(a('y-max')-a('y-min'))*a('plot-height'))*r.height/v.height};},{x,y});};
 let p=await screen(2,1),q=await screen(-2,1);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:4});await page.mouse.up();await verify(-2);p=await screen(-2,3);q=await screen(1,1);const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[q]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await verify(1);
 await lesson.getByRole('button',{name:'Toggle guides'}).click();await expect(graph.getByTestId('inequality-upper-42')).toHaveCount(0);await expect(graph.getByTestId('inequality-sample-42')).toHaveCount(1);await lesson.getByRole('button',{name:'Toggle guides'}).click();await verify(1);await lesson.getByRole('button',{name:'Inspector',exact:true}).click();await expect(graph.getByTestId('inequality-sample-42')).toBeFocused();await lesson.getByRole('button',{name:'Move graph',exact:true}).click();await expect(svg).toBeFocused();await page.keyboard.press('ArrowRight');await expect(frame).not.toHaveAttribute('data-x-min','-6');await verifyRegions();await graph.getByRole('button',{name:'Zoom graph in',exact:true}).click();await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await verifyRegions();await lesson.getByRole('button',{name:'Fit',exact:true}).click();await expect(frame).toHaveAttribute('data-x-min','-6');await verify(1.5);await lesson.getByRole('button',{name:'Share',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('y ≤ 0.8x + 1 and y > −0.5x + 2; at x = 1.5: 1.250 < y ≤ 2.200');await graph.getByRole('button',{name:'Reset graph view',exact:true}).click();await expect(lesson.getByRole('cell',{name:'No overlap',exact:true})).toHaveCount(4);
 const boxes=await graph.locator('.lesson-cartesian-annotation').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true);}for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-evidence/shared-lesson-graphs/42/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}expect(errors).toEqual([]);
});
