import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`list charts preserve ordered values and transformations at ${width}`,async({page})=>{
 test.setTimeout(90000);page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(45000);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('/lessons/core-workspaces/32-lists',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="32"]');await lesson.waitFor({timeout:45000});const graph=lesson.locator('[data-lesson-graph-workspace]');
 const verify=async()=>{const raw=await lesson.getAttribute('data-list'),values=raw?raw.split(',').map(Number):[],sum=values.reduce((a,b)=>a+b,0);await expect(lesson).toHaveAttribute('data-length',String(values.length));await expect(lesson).toHaveAttribute('data-sum',String(sum));await expect(lesson).toHaveAttribute('data-mean',String(values.length?sum/values.length:0));let mapped=[...values,10];const firstFour=mapped.indexOf(4);if(firstFour>=0)mapped.splice(firstFour,1);mapped.sort((a,b)=>a-b);if(await lesson.getAttribute('data-descending')==='true')mapped.reverse();mapped=mapped.map(x=>x*2);await expect(lesson).toHaveAttribute('data-final-list',mapped.join(','));await expect(lesson).toHaveAttribute('data-final-sum',String(mapped.reduce((a,b)=>a+b,0)));await expect(graph.locator('.lesson-bar')).toHaveCount(values.length);const max=Math.max(1,...values.map(Math.abs));for(let i=0;i<values.length;i++){const bar=graph.locator('.lesson-bar').nth(i);await expect(bar).toHaveAttribute('data-value',String(values[i]));expect(Number(await bar.getAttribute('data-fraction'))).toBeCloseTo(Math.abs(values[i])/max*85/111);await expect(bar).toHaveAttribute('data-highlighted',String(String(i)===await lesson.getAttribute('data-selected-index')));}};
 await expect(lesson).toHaveAttribute('data-list','2,4,6,8');await verify();await lesson.getByRole('spinbutton',{name:'List value 1',exact:true}).fill('-2.5');await verify();
 await lesson.getByRole('button').filter({hasText:'Dot plot'}).click();await expect(lesson).toHaveAttribute('data-view','dot');await expect(graph.locator('[data-graph-family]')).toHaveAttribute('data-graph-family','categorical-dots');await verify();await graph.getByRole('button',{name:'Index 1 = -2.5',exact:true}).click();await expect(graph.locator('output')).toHaveText('Index 1 = -2.5');
 await lesson.getByRole('button',{name:'Bar chart',exact:true}).click();await expect(lesson).toHaveAttribute('data-view','bar');
 for(let i=0;i<5;i++)await lesson.getByRole('button',{name:'Append next list value'}).click();await verify();await expect(lesson).toHaveAttribute('data-length','9');const last=graph.locator('.lesson-bar').last();await last.focus();await expect(last).toBeFocused();await last.click();await expect(graph.locator('output')).toHaveText('Index 9 = 18');
 await lesson.locator('.list-operations button').filter({hasText:'Remove'}).click();await verify();await expect(lesson).toHaveAttribute('data-length','8');await lesson.locator('.list-operations button').filter({hasText:'Map'}).click();await verify();await expect(lesson).toHaveAttribute('data-list','-5,8,12,16,20,24,28,32');
 for(let i=0;i<2;i++){await lesson.locator('.list-operations button').filter({hasText:'Sort'}).click();await verify();}
 await lesson.getByRole('button',{name:'Reset list',exact:true}).click();await verify();const items=lesson.locator('.list-item');await items.first().dragTo(items.nth(2));await expect(lesson).toHaveAttribute('data-list','4,6,2,8');await verify();
 await lesson.getByRole('button').filter({hasText:'Start over'}).click();await verify();await expect(lesson).toHaveAttribute('data-length','0');for(const text of ['Remove','Map','Sort'])await expect(lesson.locator('.list-operations button').filter({hasText:text})).toBeDisabled();await lesson.locator('.list-operations button').filter({hasText:'Append'}).click();await expect(lesson).toHaveAttribute('data-list','2');await verify();
 await lesson.getByRole('button',{name:'Reset list',exact:true}).click();for(const name of ['Sum','Mean','Min','Max']){const actions=Number(await lesson.getAttribute('data-actions'));await lesson.locator('.lists-concepts').getByRole('button',{name,exact:true}).evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await lesson.locator('.lists-concepts').getByRole('button',{name,exact:true}).click();await expect(lesson).toHaveAttribute('data-actions',String(actions+1));}
 for(const name of ['＋','−','ƒx','⇄']){await lesson.locator('.lists-concepts').getByRole('button',{name,exact:true}).evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await lesson.locator('.lists-concepts').getByRole('button',{name,exact:true}).click();await verify();}await lesson.getByRole('button',{name:'Reset list',exact:true}).click();await verify();
 for(const button of await lesson.locator('.lists-tabs button').all()){const n=Number(await lesson.getAttribute('data-actions'));await button.click();await expect(lesson).toHaveAttribute('data-actions',String(n+1));const tab=page.getByRole('tab',{name:'Interaction + visualization',exact:true});if(await tab.count())await tab.click();}
 for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-evidence/shared-lesson-graphs/32/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}
 expect(errors).toEqual([]);
});



