import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`piecewise probe follows branches and endpoints at ${width}`,async({page,context})=>{
 test.setTimeout(90000);page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(45000);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('/lessons/core-workspaces/35-piecewise-definitions',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="35"]');await lesson.waitFor({timeout:45000});const slider=lesson.getByRole('slider',{name:'Piecewise x value'}),graph=lesson.locator('[data-lesson-graph-workspace]'),frame=graph.locator('[data-graph-family]'),svg=graph.locator('svg');
 const verify=async(x:number)=>{const y=x<0?x+3:2*x;await expect(lesson).toHaveAttribute('data-x',String(x));await expect(lesson).toHaveAttribute('data-value',String(y));await expect(lesson).toHaveAttribute('data-branch',x<0?'left':'right');await expect(slider).toHaveValue(String(x));await expect(graph.locator('circle[data-included="false"]')).toHaveCount(1);await expect(graph.locator('circle[data-included="true"]')).toHaveCount(1);const visible=y>=Number(await frame.getAttribute('data-y-min'))&&y<=Number(await frame.getAttribute('data-y-max'));await expect(graph.getByTestId('piecewise-probe')).toHaveCount(visible?1:0);};
 const screen=async(x:number,y:number)=>{await svg.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));return svg.evaluate((e,p)=>{const svg=e as SVGSVGElement,r=svg.getBoundingClientRect(),v=svg.viewBox.baseVal,f=svg.closest('[data-graph-family]')!,xmin=Number(f.getAttribute('data-x-min')),xmax=Number(f.getAttribute('data-x-max')),ymin=Number(f.getAttribute('data-y-min')),ymax=Number(f.getAttribute('data-y-max'));return {x:r.x+(Number(f.getAttribute('data-plot-left'))+(p.x-xmin)/(xmax-xmin)*Number(f.getAttribute('data-plot-width')))*r.width/v.width,y:r.y+(Number(f.getAttribute('data-plot-top'))+(ymax-p.y)/(ymax-ymin)*Number(f.getAttribute('data-plot-height')))*r.height/v.height};},{x,y});};
 await verify(1);await expect(slider).toHaveAttribute('min','-5');await expect(slider).toHaveAttribute('max','5');await expect(slider).toHaveAttribute('step','1');await slider.focus();await page.keyboard.press('Home');for(let x=-5;x<=5;x++){await verify(x);if(x<5)await page.keyboard.press('ArrowRight');}await lesson.getByRole('button',{name:'Increase x',exact:true}).click();await verify(5);await slider.focus();await page.keyboard.press('Home');await lesson.getByRole('button',{name:'Decrease x',exact:true}).click();await verify(-5);
 await lesson.locator('.select-branch button').first().click();await verify(-1);await lesson.locator('.select-branch button').last().click();await verify(1);await expect(lesson.locator('.boundary-card article').nth(1)).toContainText('2(0) = 0');
 let p=await screen(-2,4);await page.mouse.click(p.x,p.y);await verify(-2);const original=await frame.getAttribute('data-x-min');let q=await screen(2,4);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:5});await page.mouse.up();await verify(2);await expect(frame).toHaveAttribute('data-x-min',original!);
 p=await screen(-1,4);q=await screen(1,4);const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[q]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await verify(1);
 await graph.getByTestId('piecewise-probe').focus();await page.keyboard.press('ArrowLeft');await verify(0);await page.keyboard.press('ArrowLeft');await verify(-1);
 await svg.focus();await page.keyboard.press('ArrowRight');await expect(frame).not.toHaveAttribute('data-x-min',original!);p=await screen(1,4);await page.mouse.click(p.x,p.y);await verify(1);await graph.getByRole('button',{name:'Reset graph view',exact:true}).click();await expect(frame).toHaveAttribute('data-x-min',original!);
 await graph.getByRole('button',{name:'Zoom graph in',exact:true}).click();await verify(1);await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await slider.focus();await page.keyboard.press('End');await verify(5);await expect(graph.getByTestId('piecewise-probe')).toHaveCount(1);
 await lesson.getByRole('button',{name:'Lesson language'}).click();await expect(lesson.getByRole('button',{name:'Lesson language'})).toContainText('Hindi');await lesson.getByRole('button',{name:'Workspace',exact:true}).click();await expect(lesson).toHaveAttribute('data-workspace','true');await lesson.getByRole('button',{name:'Share',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('f(5) = 10');await lesson.getByRole('button',{name:'Reset',exact:true}).click();await verify(1);await expect(frame).toHaveAttribute('data-x-min',original!);await expect(lesson).toHaveAttribute('data-workspace','false');await expect(lesson.getByRole('button',{name:'Lesson language'})).toContainText('English');
 for(const text of ['Sitemap','Docs','About']){const n=Number(await lesson.getAttribute('data-actions'));await lesson.locator('.piecewise-footer button').filter({hasText:text}).click();await expect(lesson).toHaveAttribute('data-actions',String(n+1));}
 for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-evidence/shared-lesson-graphs/35/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}expect(errors).toEqual([]);
});
