import {test,expect} from '@playwright/test';
for(const [width,height] of [[1440,900],[768,1024],[390,844]])test(`Point Plotter exact coordinates and controls at ${width}`,async({page,context})=>{
 test.setTimeout(90000);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('/lessons/graphs-and-functions/45-point-plotter',{waitUntil:'domcontentloaded'});const lesson=page.locator('[data-dedicated-lesson="45"]');await lesson.waitFor({timeout:45000});const graph=lesson.locator('[data-lesson-graph-workspace]'),frame=graph.locator('[data-graph-family]'),svg=graph.locator('svg'),point=lesson.getByTestId('point-c-45');
 const verify=async(x:number,y:number)=>{await expect(lesson).toHaveAttribute('data-primary',String(x));await expect(lesson).toHaveAttribute('data-secondary',String(y));await expect(point).toHaveAttribute('aria-label',`C(${x}, ${y}): (${x}, ${y})`);const p=await point.evaluate(e=>({x:Number(e.getAttribute('cx')),y:Number(e.getAttribute('cy'))}));const f=await frame.evaluate(e=>Object.fromEntries(['x-min','x-max','y-min','y-max','plot-left','plot-top','plot-width','plot-height'].map(k=>[k,Number(e.getAttribute('data-'+k))])));expect(p.x).toBeCloseTo(f['plot-left']+(x-f['x-min'])/(f['x-max']-f['x-min'])*f['plot-width'],4);expect(p.y).toBeCloseTo(f['plot-top']+(f['y-max']-y)/(f['y-max']-f['y-min'])*f['plot-height'],4);expect(f['plot-width']/(f['x-max']-f['x-min'])).toBeCloseTo(f['plot-height']/(f['y-max']-f['y-min']),4);await expect(lesson.locator('tr').filter({has:page.locator('th').filter({hasText:/^C$/})}).locator('td').first()).toHaveText('('+x+', '+y+')');};
 const verifyFixed=async()=>{for(const [id,x,y] of [['point-a-45',-2,1],['point-b-45',-1,3]] as const){const p=graph.getByTestId(id);const values=await p.evaluate(e=>{const f=e.closest('[data-graph-family]')!,a=(k:string)=>Number(f.getAttribute('data-'+k));return {x:a('x-min')+(Number(e.getAttribute('cx'))-a('plot-left'))/a('plot-width')*(a('x-max')-a('x-min')),y:a('y-max')-(Number(e.getAttribute('cy'))-a('plot-top'))/a('plot-height')*(a('y-max')-a('y-min'))};});expect(values.x).toBeCloseTo(x,10);expect(values.y).toBeCloseTo(y,10);}};
 await verifyFixed();await verify(2,3);await expect(frame).toHaveAttribute('data-x-min','-6');const names=['x','y','Trace x'];
 for(let i=0;i<3;i++){const s=lesson.getByRole('slider',{name:names[i],exact:true});await expect(s).toHaveAttribute('min','-5');await expect(s).toHaveAttribute('max','5');await expect(s).toHaveAttribute('step','0.5');await s.focus();await page.keyboard.press('Home');for(let n=-5;n<=5;n+=.5){await expect(s).toHaveValue(String(n));if(i===0)await verify(n,3);if(i===1)await verify(5,n);if(i===2){await expect(lesson).toHaveAttribute('data-trace',String(n));await expect(graph.getByTestId('point-trace-45')).toHaveAttribute('aria-label',`Trace (${n}, 5): (${n}, 5)`);}if(n<5)await page.keyboard.press('ArrowRight');}await expect(lesson.getByRole('button',{name:`Increase ${names[i]}`,exact:true})).toBeDisabled();await expect(s).toHaveValue('5');await lesson.getByRole('button',{name:`Decrease ${names[i]}`,exact:true}).click();await expect(s).toHaveValue('4.5');await s.focus();await page.keyboard.press('End');}
 await expect(lesson.getByRole('cell',{name:'(-3, 5)',exact:true})).toBeVisible();await lesson.getByRole('button',{name:'Reset view',exact:true}).click();await verify(2,3);
 await point.focus();await page.keyboard.press('ArrowLeft');await verify(1.5,3);await page.keyboard.press('ArrowDown');await verify(1.5,2.5);
 const screen=async(x:number,y:number)=>{await svg.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));return svg.evaluate((e,p)=>{const s=e as SVGSVGElement,r=s.getBoundingClientRect(),v=s.viewBox.baseVal,f=s.closest('[data-graph-family]')!;const a=(k:string)=>Number(f.getAttribute('data-'+k));return {x:r.x+(a('plot-left')+(p.x-a('x-min'))/(a('x-max')-a('x-min'))*a('plot-width'))*r.width/v.width,y:r.y+(a('plot-top')+(a('y-max')-p.y)/(a('y-max')-a('y-min'))*a('plot-height'))*r.height/v.height};},{x,y});};
 let p=await screen(1.5,2.5),q=await screen(-2,-1);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:4});await page.mouse.up();await verify(-2,-1);p=await screen(-2,-1);q=await screen(3,-2);const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[q]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await verify(3,-2);await verifyFixed();
 await lesson.getByRole('button',{name:'Toggle guides'}).click();await expect(lesson).toHaveAttribute('data-guides','false');await expect(graph.getByTestId('point-trace-45')).toHaveCount(0);await expect(point).toBeVisible();await expect(graph.locator('.lesson-cartesian-ticks text')).toHaveCount(2);await lesson.getByRole('button',{name:'Toggle guides'}).click();await expect(lesson).toHaveAttribute('data-guides','true');
 await lesson.getByRole('button',{name:'Move graph',exact:true}).click();await expect(svg).toBeFocused();await page.keyboard.press('ArrowRight');await expect(frame).not.toHaveAttribute('data-x-min','-6');await lesson.getByRole('button',{name:'Inspector',exact:true}).click();await expect(point).toBeFocused();await graph.getByRole('button',{name:'Zoom graph in',exact:true}).click();await graph.getByRole('button',{name:'Zoom graph out',exact:true}).click();await lesson.getByRole('button',{name:'Fit',exact:true}).click();await expect(frame).toHaveAttribute('data-x-min','-6');await expect(lesson).toHaveAttribute('data-trace','1.5');await verify(3,-2);await verifyFixed();
 await lesson.getByRole('button',{name:'Share',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('C = (3, -2); A = (-2, 1); B = (-1, 3); trace = (1.5, -2)');await lesson.getByRole('button',{name:'Reset view',exact:true}).click();await verify(2,3);await graph.getByRole('button',{name:'Reset graph view',exact:true}).click();
 const boxes=await graph.locator('.lesson-cartesian-annotation').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true);}for(const dark of [false,true]){await page.evaluate(value=>document.documentElement.classList.toggle('dark',value),dark);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`test-evidence/shared-lesson-graphs/45/tested-${width}-${dark?'dark':'light'}.png`,fullPage:true});}expect(errors).toEqual([]);
});


