import { ArrowLeft, Hand, Minus, MoreVertical, Pause, Play, Plus, RotateCcw, X as Close } from "lucide-react";
import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { useNavigate } from "react-router-dom";
import "./derivative-slope-mobile.css";

const f=(x:number)=>.055*x*x*x-.18*x*x+.9*x+1.15;
const fp=(x:number)=>.165*x*x-.36*x+.9;
const X=(x:number)=>52+(x+2)*43;
const Y=(y:number)=>384-(y+1)*43;

export default function DerivativeSlopeMobileProof(){
 const navigate=useNavigate();const [x,setX]=useState(.5);const [h,setH]=useState(3);const [playing,setPlaying]=useState(false);const [dragging,setDragging]=useState(false);const [menu,setMenu]=useState(false);const svg=useRef<SVGSVGElement>(null);const last=useRef<number|null>(null);
 useEffect(()=>{if(!playing)return;let frame=0;const tick=(time:number)=>{if(last.current===null)last.current=time;const dt=time-last.current;last.current=time;setH(v=>{const next=v-dt/1800;if(next<=.08){setPlaying(false);return .08}return next});frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);last.current=null}},[playing]);
 const qx=x+h,y1=f(x),y2=f(qx),m=(y2-y1)/h,tangent=fp(x),p1={x:X(x),y:Y(y1)},p2={x:X(qx),y:Y(y2)};
 const move=(e:ReactPointerEvent<SVGSVGElement>)=>{if(!dragging||!svg.current)return;const matrix=svg.current.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());setX(Math.max(-1.2,Math.min(2.8,(p.x-52)/43-2)));setPlaying(false)};
 const reset=()=>{setX(.5);setH(3);setPlaying(false);setMenu(false)};const curve=Array.from({length:100},(_,i)=>{const xx=-2+i*7/99;return `${i?"L":"M"}${X(xx)} ${Y(f(xx))}`}).join(" ");
 return <main className="derivative-mobile" aria-label="Derivative as Slope interactive lesson"><header className="derivative-header"><button onClick={()=>navigate(-1)} aria-label="Back to visual proofs"><ArrowLeft/></button><div><h1>Derivative as Slope</h1><p>11 / 69</p></div><button onClick={()=>setMenu(v=>!v)} aria-label="Lesson options"><MoreVertical/></button></header>
 <section className="derivative-stage"><svg ref={svg} viewBox="0 0 390 690" onPointerMove={move} onPointerUp={()=>setDragging(false)} onPointerCancel={()=>setDragging(false)} role="img" aria-label={`Secant slope ${m.toFixed(2)} approaches tangent slope ${tangent.toFixed(2)} as h approaches zero`}>
  <defs><filter id="cyan-glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d="M50 400H370m-318 15V45" stroke="#26333d" strokeWidth="1.2"/><path d="M370 400l-9-5v10zM52 45l-5 9h10z" fill="#26333d"/><path d={curve} fill="none" stroke="#2c3540" strokeWidth="2.4"/>
  {[.25,.5,.75,1].map(k=>{const hk=Math.max(.08,h*k),q={x:X(x+hk),y:Y(f(x+hk))};return <line key={k} x1={p1.x} y1={p1.y} x2={q.x} y2={q.y} stroke="#ff6a55" opacity={.12+.16*k}/>})}
  <line x1={p1.x-90} y1={p1.y+90*tangent} x2={p1.x+180} y2={p1.y-180*tangent} stroke="#1ebad0" strokeWidth="2" filter="url(#cyan-glow)"/><line x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} stroke="#ff654f" strokeWidth="2.3"/><line x1={p1.x} y1={p1.y} x2={p2.x} y2={p1.y} stroke="#29343d" strokeDasharray="4 4"/><line x1={p2.x} y1={p1.y} x2={p2.x} y2={p2.y} stroke="#29343d" strokeDasharray="4 4"/>
  <g className="derivative-delta"><text x={(p1.x+p2.x)/2} y={p1.y+28}>Δx = {h.toFixed(2)}</text><text x={p2.x+24} y={(p1.y+p2.y)/2}>Δy</text></g><g className="derivative-point"><circle cx={p2.x} cy={p2.y} r="7"/><circle className="base" cx={p1.x} cy={p1.y} r="7"/><circle cx={p1.x} cy={p1.y} r="20" fill="transparent" role="slider" tabIndex={0} aria-label="Base point x" aria-valuenow={Number(x.toFixed(2))} onPointerDown={e=>{setDragging(true);e.currentTarget.setPointerCapture(e.pointerId)}} onKeyDown={e=>{if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();setX(v=>Math.max(-1.2,Math.min(2.8,v+(e.key==="ArrowRight"?.1:-.1))));setPlaying(false)}}}/></g>
  <g transform="translate(20 455)"><InfoCard x={0} color="#f2634e" label="Δy / Δx" value={m.toFixed(2)}/><InfoCard x={126} color="#19afc4" label="h → 0" value={h.toFixed(2)}/><InfoCard x={252} color="#5a4bc0" label="f′(x)" value={tangent.toFixed(2)}/></g>
  <foreignObject x="22" y="558" width="346" height="76"><div className="derivative-h"><p>h → 0</p><button onClick={()=>{setH(v=>Math.max(.08,v-.2));setPlaying(false)}} aria-label="Decrease h"><Minus/></button><input type="range" min="0.08" max="3" step="0.02" value={h} onChange={e=>{setH(Number(e.target.value));setPlaying(false)}} aria-label="Distance h"/><button onClick={()=>{setH(v=>Math.min(3,v+.2));setPlaying(false)}} aria-label="Increase h"><Plus/></button></div></foreignObject>
 </svg></section><section className="derivative-controls"><button className={dragging?"active":""} onClick={()=>setDragging(v=>!v)} aria-pressed={dragging} aria-label="Toggle point dragging"><Hand/></button><button onClick={reset} aria-label="Reset derivative proof"><RotateCcw/></button><button onClick={()=>setPlaying(v=>!v)} aria-label={playing?"Pause secant animation":"Play secant animation"}>{playing?<Pause/>:<Play/>}</button></section>{menu?<aside role="dialog"><button onClick={()=>setMenu(false)} aria-label="Close lesson options"><Close/></button><h2>Secant becomes tangent</h2><p>The secant slope is Δy/Δx. As h shrinks toward zero, the moving point approaches x and the secant line approaches the tangent.</p><p>The limiting slope is f′(x) = {tangent.toFixed(2)}.</p></aside>:null}</main>
}
function InfoCard({x,color,label,value}:{x:number;color:string;label:string;value:string}){return <g transform={`translate(${x} 0)`}><rect width="116" height="75" rx="9" fill="#fff" stroke={color} strokeOpacity=".28"/><text x="58" y="28" fill={color}>{label}</text><text x="58" y="56" fill={color}>{value}</text></g>}
