export type Complex={re:number;im:number};const C=(re:number,im=0):Complex=>({re,im});export function add(a:Complex,b:Complex){return C(a.re+b.re,a.im+b.im)}export function multiply(a:Complex,b:Complex){return C(a.re*b.re-a.im*b.im,a.re*b.im+a.im*b.re)}export function divide(a:Complex,b:Complex){const d=b.re*b.re+b.im*b.im;return C((a.re*b.re+a.im*b.im)/d,(a.im*b.re-a.re*b.im)/d)}export function abs(z:Complex){return Math.hypot(z.re,z.im)}export function expComplex(z:Complex){const r=Math.exp(z.re);return C(r*Math.cos(z.im),r*Math.sin(z.im))}
export function draggableArithmetic(a:Complex,b:Complex){return{sum:add(a,b),difference:add(a,C(-b.re,-b.im)),product:multiply(a,b)}}
export function synchronizeForms(z:Complex){const modulus=abs(z),argument=Math.atan2(z.im,z.re);return{rectangular:z,polar:{modulus,argument},exponential:`${modulus}e^(i${argument})`}}
export function locus(kind:"circle"|"vertical"|"apollonius",parameter:number,samples=36){if(kind==="vertical")return Array.from({length:samples},(_,i)=>C(parameter,-5+10*i/(samples-1)));if(kind==="circle")return Array.from({length:samples},(_,i)=>C(parameter*Math.cos(2*Math.PI*i/samples),parameter*Math.sin(2*Math.PI*i/samples)));return Array.from({length:samples},(_,i)=>{const t=2*Math.PI*i/samples;return C(parameter+Math.cos(t),Math.sin(t))})}
export function deMoivre(z:Complex,power:number){const{modulus,argument}=synchronizeForms(z).polar;return C(modulus**power*Math.cos(power*argument),modulus**power*Math.sin(power*argument))}
export function nthRoots(z:Complex,n:number){const r=abs(z)**(1/n),theta=Math.atan2(z.im,z.re);return Array.from({length:n},(_,k)=>C(r*Math.cos((theta+2*Math.PI*k)/n),r*Math.sin((theta+2*Math.PI*k)/n)))}
export function rootsOfUnity(n:number){return nthRoots(C(1),n)}
export function mobius(z:Complex,a:Complex,b:Complex,c:Complex,d:Complex){return divide(add(multiply(a,z),b),add(multiply(c,z),d))}
export function mappedGrid(fn:(z:Complex)=>Complex,extent=2,lines=5){const coordinates=Array.from({length:lines},(_,i)=>-extent+2*extent*i/(lines-1));return{horizontal:coordinates.map(y=>coordinates.map(x=>fn(C(x,y)))),vertical:coordinates.map(x=>coordinates.map(y=>fn(C(x,y))))}}
export function cauchyRiemann(fn:(z:Complex)=>Complex,z:Complex,h=1e-5){const fx1=fn(C(z.re+h,z.im)),fx0=fn(C(z.re-h,z.im)),fy1=fn(C(z.re,z.im+h)),fy0=fn(C(z.re,z.im-h)),ux=(fx1.re-fx0.re)/(2*h),vx=(fx1.im-fx0.im)/(2*h),uy=(fy1.re-fy0.re)/(2*h),vy=(fy1.im-fy0.im)/(2*h),residual=Math.hypot(ux-vy,uy+vx);return{ux,uy,vx,vy,residual,analyticCandidate:residual<1e-5}}
export function complexDerivative(fn:(z:Complex)=>Complex,z:Complex,h=1e-6){const real=divide(add(fn(C(z.re+h,z.im)),C(-fn(z).re,-fn(z).im)),C(h)),imaginary=divide(add(fn(C(z.re,z.im+h)),C(-fn(z).re,-fn(z).im)),C(0,h));return{realDirection:real,imaginaryDirection:imaginary,residual:abs(add(real,C(-imaginary.re,-imaginary.im)))}}
export function contourIntegral(fn:(z:Complex)=>Complex,path:(t:number)=>Complex,steps=1000){let sum=C(0);for(let i=0;i<steps;i++){const t0=i/steps,t1=(i+1)/steps,z0=path(t0),z1=path(t1),mid=path((t0+t1)/2),dz=add(z1,C(-z0.re,-z0.im));sum=add(sum,multiply(fn(mid),dz))}return sum}
export function simpleResidue(numerator:(z:Complex)=>Complex,denominatorDerivative:(z:Complex)=>Complex,pole:Complex){return divide(numerator(pole),denominatorDerivative(pole))}
export function zeroPoleMap(zeros:Array<{z:Complex;multiplicity:number}>,poles:Array<{z:Complex;multiplicity:number}>){return{zeros,poles,totalZeroOrder:zeros.reduce((s,x)=>s+x.multiplicity,0),totalPoleOrder:poles.reduce((s,x)=>s+x.multiplicity,0)}}
export function principalLog(z:Complex){const argument=Math.atan2(z.im,z.re);return{value:C(Math.log(abs(z)),argument),onBranchCut:z.im===0&&z.re<=0,branch:"−π < Arg(z) ≤ π"}}
export function stereographicProjection(z:Complex){const d=abs(z)**2+1;return{x:2*z.re/d,y:2*z.im/d,z:(abs(z)**2-1)/d}}
export function mandelbrot(c:Complex,maxIterations=100){let z=C(0),iteration=0;while(iteration<maxIterations&&abs(z)<=2){z=add(multiply(z,z),c);iteration++}return{escaped:iteration<maxIterations,iterations:iteration,z}}
export function julia(z0:Complex,c:Complex,maxIterations=100){let z=z0,iteration=0;const orbit=[z];while(iteration<maxIterations&&abs(z)<=2){z=add(multiply(z,z),c);orbit.push(z);iteration++}return{escaped:iteration<maxIterations,iterations:iteration,orbit}}
export function eulerPhasor(magnitude:number,phase:number){const value=C(magnitude*Math.cos(phase),magnitude*Math.sin(phase));return{value,cosine:value.re,sine:value.im}}
export function polynomialRoots(coefficients:Complex[],iterations=120){const degree=coefficients.length-1;if(degree<1)return[];let roots=Array.from({length:degree},(_,k)=>eulerPhasor(1,2*Math.PI*k/degree+.2).value);const evaluate=(z:Complex)=>coefficients.reduce((sum,coef)=>add(multiply(sum,z),coef),C(0));for(let n=0;n<iterations;n++)roots=roots.map((root,i)=>{let denom=C(1);roots.forEach((other,j)=>{if(i!==j)denom=multiply(denom,add(root,C(-other.re,-other.im)))});return add(root,multiply(C(-1),divide(evaluate(root),denom)))});return roots}
export function discreteFourier(signal:number[]){return signal.map((_,k)=>signal.reduce((sum,value,n)=>add(sum,eulerPhasor(value,-2*Math.PI*k*n/signal.length).value),C(0)))}
export function seriesImpedance(resistance:number,inductance:number,capacitance:number,omega:number){const reactance=omega*inductance-1/(omega*capacitance),z=C(resistance,reactance);return{z,magnitude:abs(z),phase:Math.atan2(z.im,z.re),resonant:Math.abs(reactance)<1e-8}}
export function quantumInterference(amplitudes:Complex[]){const total=amplitudes.reduce(add,C(0));return{total,probability:abs(total)**2,individualProbability:amplitudes.reduce((s,z)=>s+abs(z)**2,0)}}
export function conformalRegion(fn:(z:Complex)=>Complex,corners:Complex[]){const mapped=corners.map(fn);const orientedArea=mapped.reduce((s,p,i)=>s+p.re*mapped[(i+1)%mapped.length].im-p.im*mapped[(i+1)%mapped.length].re,0)/2;return{mapped,orientedArea,orientation:Math.sign(orientedArea)}}
export function rootSensitivity(root:Complex,perturbation:Complex){const moved=add(root,perturbation);return{root,moved,absoluteChange:abs(perturbation),relativeChange:abs(root)===0?Infinity:abs(perturbation)/abs(root)}}
export function quaternionRotation(axis:[number,number,number],angle:number){const length=Math.hypot(...axis)||1,s=Math.sin(angle/2)/length;return{w:Math.cos(angle/2),x:axis[0]*s,y:axis[1]*s,z:axis[2]*s,norm:1}}
