export function setOperations<T>(a:T[],b:T[]){const A=new Set(a),B=new Set(b);return{union:[...new Set([...a,...b])],intersection:a.filter(x=>B.has(x)),difference:a.filter(x=>!B.has(x)),symmetricDifference:[...a.filter(x=>!B.has(x)),...b.filter(x=>!A.has(x))]}}
export function truthTable2(evaluate:(p:boolean,q:boolean)=>boolean){return[false,true].flatMap(p=>[false,true].map(q=>({p,q,result:evaluate(p,q)})))}
export function karnaugh2(minterms:number[]){const set=new Set(minterms);if(set.size===4)return"1";if(!set.size)return"0";const terms:string[]=[];if(set.has(2)&&set.has(3))terms.push("p");if(set.has(0)&&set.has(1))terms.push("¬p");if(set.has(1)&&set.has(3))terms.push("q");if(set.has(0)&&set.has(2))terms.push("¬q");for(const m of set)if(![[2,3],[0,1],[1,3],[0,2]].some(pair=>pair.includes(m)&&pair.every(x=>set.has(x))))terms.push(`${m&2?"p":"¬p"}∧${m&1?"q":"¬q"}`);return[...new Set(terms)].join(" ∨ ")}
export function quantify<T>(domain:T[],predicate:(x:T)=>boolean){const witnesses=domain.filter(predicate);return{forall:witnesses.length===domain.length,exists:witnesses.length>0,witnesses,counterexamples:domain.filter(x=>!predicate(x))}}
export function modusPonens(p:boolean,pImpliesQ:boolean){return{valid:p&&pImpliesQ,conclusion:p&&pImpliesQ,rule:"modus ponens"}}
export function relationClosures<T>(domain:T[],pairs:Array<[T,T]>){const key=(a:T,b:T)=>JSON.stringify([a,b]),closure=new Map(pairs.map(p=>[key(...p),p]));domain.forEach(x=>closure.set(key(x,x),[x,x]));let changed=true;while(changed){changed=false;for(const[a,b]of[...closure.values()])for(const[c,d]of[...closure.values()])if(Object.is(b,c)&&!closure.has(key(a,d))){closure.set(key(a,d),[a,d]);changed=true}}return{reflexiveTransitive:[...closure.values()]}}
export function functionProperties(domain:string[],codomain:string[],mapping:Record<string,string>){const outputs=domain.map(x=>mapping[x]),injective=new Set(outputs).size===outputs.length,surjective=codomain.every(y=>outputs.includes(y));return{injective,surjective,bijective:injective&&surjective}}
export function countingTree(groups:number[]){const total=groups.reduce((a,b)=>a*b,1);return{levels:groups.map((choices,i)=>({level:i+1,choices,partial:groups.slice(0,i+1).reduce((a,b)=>a*b,1)})),total}}
export function generatingFunctionCoins(coins:number[],maximum:number){const coefficients=Array(maximum+1).fill(0)as number[];coefficients[0]=1;for(const coin of coins)for(let sum=coin;sum<=maximum;sum++)coefficients[sum]+=coefficients[sum-coin];return{coefficients,interpretation:"coefficient of x^n counts unordered selections"}}
export function linearRecurrence(coefficients:number[],initial:number[],count:number){const terms=[...initial];while(terms.length<count){const n=terms.length;terms.push(coefficients.reduce((s,c,i)=>s+c*terms[n-1-i],0))}return terms.slice(0,count)}
export function congruenceClass(value:number,modulus:number){const residue=((value%modulus)+modulus)%modulus;return{residue,representatives:Array.from({length:7},(_,i)=>residue+(i-3)*modulus)}}
export function chineseRemainder(remainders:number[],moduli:number[]){const product=moduli.reduce((a,b)=>a*b,1);let x=0;for(let i=0;i<moduli.length;i++){const partial=product/moduli[i],inverse=modInverse(partial,moduli[i]);if(inverse===null)return null;x+=remainders[i]*partial*inverse}return{solution:((x%product)+product)%product,modulus:product}}
export function extendedEuclid(a:number,b:number){let[oldR,r]=[a,b],[oldS,s]=[1,0],[oldT,t]=[0,1];const steps=[];while(r!==0){const q=Math.trunc(oldR/r);steps.push({q,r:oldR});[oldR,r]=[r,oldR-q*r];[oldS,s]=[s,oldS-q*s];[oldT,t]=[t,oldT-q*t]}return{gcd:Math.abs(oldR),x:oldS,y:oldT,steps}}
export function primeFactorization(n:number){let value=Math.abs(Math.trunc(n)),factor=2;const factors:number[]=[];while(factor*factor<=value){while(value%factor===0){factors.push(factor);value/=factor}factor++}if(value>1)factors.push(value);return{prime:factors.length===1&&factors[0]===Math.abs(n),factors}}
export function rsaDemo(p:number,q:number,message:number){const n=p*q,phi=(p-1)*(q-1),e=[3,5,17,257].find(v=>gcd(v,phi)===1)??3,d=modInverse(e,phi);if(d===null)return null;const encrypted=modPow(message,e,n),decrypted=modPow(encrypted,d,n);return{publicKey:[e,n],privateKey:[d,n],encrypted,decrypted}}
export function validateGraph(nodes:string[],edges:Array<[string,string]>,directed=false){const valid=edges.every(([a,b])=>nodes.includes(a)&&nodes.includes(b));const adjacency=Object.fromEntries(nodes.map(n=>[n,[]as string[]]));edges.forEach(([a,b])=>{adjacency[a].push(b);if(!directed)adjacency[b].push(a)});return{valid,adjacency}}
export function bfs(adjacency:Record<string,string[]>,start:string){const queue=[start],visited=new Set([start]),order:string[]=[];while(queue.length){const node=queue.shift()!;order.push(node);for(const next of adjacency[node]??[])if(!visited.has(next)){visited.add(next);queue.push(next)}}return order}
export function greedyColoring(adjacency:Record<string,string[]>){const colors:Record<string,number>={};for(const node of Object.keys(adjacency)){const used=new Set((adjacency[node]??[]).map(n=>colors[n]).filter(Boolean));let color=1;while(used.has(color))color++;colors[node]=color}return{colors,chromaticUpperBound:Math.max(0,...Object.values(colors))}}
export function maxFlow(capacity:number[][],source:number,sink:number){const residual=capacity.map(r=>[...r]);let flow=0;while(true){const parent=Array(capacity.length).fill(-1),q=[source];parent[source]=source;while(q.length&&parent[sink]<0){const u=q.shift()!;for(let v=0;v<capacity.length;v++)if(parent[v]<0&&residual[u][v]>0){parent[v]=u;q.push(v)}}if(parent[sink]<0)break;let add=Infinity;for(let v=sink;v!==source;v=parent[v])add=Math.min(add,residual[parent[v]][v]);for(let v=sink;v!==source;v=parent[v]){residual[parent[v]][v]-=add;residual[v][parent[v]]+=add}flow+=add}return{flow,residual}}
export function planarityBound(vertices:number,edges:number,bipartite=false){const bound=vertices<3?Infinity:(bipartite?2:3)*vertices-(bipartite?4:6);return{necessaryBound:bound,violates:edges>bound,note:"Euler bound is necessary, not sufficient"}}
export function huffmanCodes(frequencies:Record<string,number>){let nodes=Object.entries(frequencies).map(([symbol,weight])=>({symbols:[symbol],weight,codes:{[symbol]:""}}));while(nodes.length>1){nodes.sort((a,b)=>a.weight-b.weight);const a=nodes.shift()!,b=nodes.shift()!,codes:Record<string,string>={};for(const[s,c]of Object.entries(a.codes))codes[s]="0"+c;for(const[s,c]of Object.entries(b.codes))codes[s]="1"+c;nodes.push({symbols:[...a.symbols,...b.symbols],weight:a.weight+b.weight,codes})}return nodes[0]?.codes??{}}
export function simulateDfa(input:string,transition:Record<string,Record<string,string>>,start:string,accepting:string[]){let state=start;const trace=[state];for(const symbol of input){state=transition[state]?.[symbol]??"∅";trace.push(state)}return{state,accepted:accepting.includes(state),trace}}
export function regexEquivalentBounded(first:RegExp,second:RegExp,alphabet:string[],maxLength:number){const strings=[""];for(let length=1;length<=maxLength;length++){const previous=strings.filter(s=>s.length===length-1);strings.push(...previous.flatMap(s=>alphabet.map(c=>s+c)))}const counterexample=strings.find(s=>new RegExp(`^(?:${first.source})$`).test(s)!==new RegExp(`^(?:${second.source})$`).test(s));return{equivalentOnBound:counterexample===undefined,counterexample,checked:strings.length}}
export function parenthesesPda(input:string){let depth=0;const trace=[];for(const symbol of input){depth+=symbol==="("?1:symbol===")"?-1:0;trace.push({symbol,depth});if(depth<0)return{accepted:false,trace}}return{accepted:depth===0,trace}}
export function cfgAndTuring(input:string){const cfgAccepted=/^a*b*$/.test(input)&&!input.includes("ba");let head=0,tape=input.split("");const trace=[];while(head<tape.length){trace.push({head,symbol:tape[head]});tape[head]=tape[head]==="a"?"A":tape[head];head++}return{cfgAccepted,turing:{halted:true,tape:tape.join(""),trace}}}
function gcd(a:number,b:number):number{return b?gcd(b,a%b):Math.abs(a)}function modInverse(a:number,m:number){const r=extendedEuclid(a,m);return r.gcd===1?((r.x%m)+m)%m:null}function modPow(base:number,exponent:number,modulus:number){let result=1,b=((base%modulus)+modulus)%modulus,e=exponent;while(e>0){if(e%2)result=result*b%modulus;b=b*b%modulus;e=Math.floor(e/2)}return result}
