import {useEffect,useRef,useState} from 'react';
import * as tf from '@tensorflow/tfjs';
import {assertTrainingAllowed} from './intelligence/buildPolicy';
import {buildContextDataset} from './intelligence/contextDataset';
import type {ContextRow} from './intelligence/ruhiContextNet';
const CANDIDATE='indexeddb://ruhi-context-v1-candidate';
export default function ContextTrainingPanel(){
 const [rows,setRows]=useState<ContextRow[]>([]),[status,setStatus]=useState('Context training is separate from the unchanged v4 action model.'),[busy,setBusy]=useState(false),[metrics,setMetrics]=useState<{rows:number;intentAccuracy:number;contextAccuracy:number;jointAccuracy:number}>();
 const worker=useRef<Worker>(),candidate=useRef<tf.LayersModel>();
 useEffect(()=>()=>{worker.current?.terminate();candidate.current?.dispose();},[]);
 function train(){try{assertTrainingAllowed();setBusy(true);const next=new Worker(new URL('./intelligence/contextTraining.worker.ts',import.meta.url),{type:'module'});worker.current=next;next.onmessage=async({data})=>{if(data.type==='progress')setStatus(`Epoch ${data.epoch}: loss ${Number(data.loss).toFixed(4)}`);else if(data.type==='error'){setStatus(data.message);setBusy(false);next.terminate();}else if(data.type==='complete'){next.terminate();candidate.current?.dispose();candidate.current=await tf.loadLayersModel(tf.io.fromMemory(data.artifact));await candidate.current.save(CANDIDATE);setMetrics(data.metrics);setBusy(false);setStatus('Candidate saved separately. Student inference still uses the distributed version.');}};next.onerror=e=>{setStatus(e.message);setBusy(false);next.terminate();};next.postMessage({rows,hidden:64,epochs:40});}catch(e){setStatus(String(e));setBusy(false);}}
 async function exportModel(){try{assertTrainingAllowed();if(!candidate.current||!metrics||metrics.jointAccuracy<.95)throw new Error('Distribution export requires a reviewed candidate with at least 95% held-out joint accuracy.');await candidate.current.save('downloads://ruhi-context-v1-reviewed');setStatus('Exported model for administrator-reviewed distribution. Replace bundled version only after execution/security checks.');}catch(e){setStatus(String(e));}}
 return <><h2>RuhiContextNet · page and dialogue intelligence</h2><p>Offline worker training; template-group splits; separately calibrated intent and meaning heads. Browser-only build separation is not account authentication against an owner of the browser.</p><button disabled={busy} onClick={()=>{assertTrainingAllowed();setRows(buildContextDataset());}}>Load discovered-page contextual dataset</button><label>Import context JSONL<input type="file" accept=".jsonl,.ndjson" disabled={busy} onChange={async e=>{try{assertTrainingAllowed();const file=e.target.files?.[0];if(!file)return;if(file.size>100*1024*1024)throw new Error('Maximum 100 MB.');const parsed=(await file.text()).split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));if(parsed.length>100000)throw new Error('Maximum 100,000 rows.');setRows(parsed);setMetrics(undefined);}catch(error){setStatus(String(error));}}}/></label><p>{rows.length} rows; model v1. Public inference caches bundled weights across navigation.</p><button disabled={busy||!rows.length} onClick={train}>Train context candidate</button><button disabled={busy||!candidate.current} onClick={()=>void exportModel()}>Export reviewed distribution model</button><button disabled={busy} onClick={async()=>{assertTrainingAllowed();candidate.current?.dispose();candidate.current=undefined;await tf.io.removeModel(CANDIDATE).catch(()=>{});setMetrics(undefined);setStatus('Candidate removed. Rolled back to the immutable bundled context model; v4 preserved.');}}>Roll back context candidate</button><p role="status">{status}</p>{metrics&&<pre>{JSON.stringify(metrics,null,2)}</pre>}</>;
}
