import {useMemo,useState} from 'react';
import {CorrectionQueue} from './intelligence/correctionCandidates';
import {datasetQuality} from './intelligence/datasetQuality';
import {publicationBlocks,type ExecutionAssessment} from './intelligence/candidateAssessment';
import type {SemanticRow} from './intelligence/types';
import type {V4Report} from './intelligence/hierarchicalModel';
export function IntelligenceReviewPanels({tab,rows,report,baseline,assessment,hasCandidate,busy,runRegression,compare,approveExport}:{tab:string;rows:SemanticRow[];report?:V4Report;baseline?:V4Report;assessment?:ExecutionAssessment;hasCandidate:boolean;busy:boolean;runRegression:()=>void;compare:()=>void;approveExport:()=>void}){
 const queue=useMemo(()=>new CorrectionQueue(window.localStorage),[]),[corrections,setCorrections]=useState(()=>queue.list()),[cell,setCell]=useState<{head:string;expected:string;predicted:string}>();
 const quality=useMemo(()=>datasetQuality(rows),[rows]),blocks=publicationBlocks(report,assessment,hasCandidate);
 if(tab==='Overview')return <><h2>Ruhi Intelligence Engine v5</h2><p>Deterministic geometry execution with a local neural intent model. Training is available only in development or a privately distributed training build. A public training build is not an authentication system.</p><p>Known-good v4 assets remain the baseline. Training saves a separate candidate; explicit approval exports a verified candidate for deployment.</p><pre>{JSON.stringify(quality,null,2)}</pre></>;
 if(tab==='Corrections')return <><h2>Correction review queue</h2><p>Approval marks reviewed examples for dataset export. It does not alter live mappings or weights.</p><button onClick={()=>{const blob=new Blob([corrections.filter(c=>c.approved).flatMap(c=>c.commands.map(command=>JSON.stringify({phrase:c.originalText,action:command.action,subAction:command.subAction,mode:c.mode,parameters:command.parameters,target:command.target,targets:command.targets,group:`correction-${c.id}`,source:'admin-reviewed'}))).join('\n')],{type:'application/x-ndjson'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reviewed-corrections.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export approved rows</button>{corrections.map(c=><article key={c.id}><p>{c.originalText} → {c.correctedAction}:{c.correctedSubaction} ({c.mode})</p><button disabled={c.approved} onClick={()=>{queue.approve(c.id);setCorrections(queue.list());}}>{c.approved?'Reviewed':'Approve example'}</button></article>)}</>;
 if(tab==='Confusion Matrix')return <><h2>Measured action and subaction confusion</h2>{report&&(['action','subaction'] as const).map(head=>{const labels=head==='action'?report.metrics.actionLabels:report.metrics.subActionLabels??[],matrix=head==='action'?report.metrics.confusionMatrix:report.metrics.subActionConfusionMatrix??[];return <details key={head} open><summary>{head} matrix</summary><div className="mt-table-wrap"><table><thead><tr><th>Expected / predicted</th>{labels.map(l=><th key={l}>{l}</th>)}</tr></thead><tbody>{matrix.map((row,i)=><tr key={i}><th>{labels[i]}</th>{row.map((n,j)=><td key={j}><button onClick={()=>setCell({head,expected:labels[i],predicted:labels[j]})}>{n}</button></td>)}</tr>)}</tbody></table></div></details>;})}{cell&&<><h3>{cell.expected} → {cell.predicted}</h3>{report?.metrics.examples?.filter(e=>cell.head==='action'?e.expectedAction===cell.expected&&e.predictedAction===cell.predicted:e.expectedSubAction===cell.expected&&e.predictedSubAction===cell.predicted).slice(0,100).map((e,i)=><p key={i}>{e.phrase} · confidence {((cell.head==='subaction'?e.subActionConfidence??e.confidence:e.confidence)*100).toFixed(1)}% · {e.mode}</p>)}</>}</>;
 if(tab==='Regression'||tab==='Adversarial Tests')return <><h2>Execution and safety regression</h2><p>Held-out executable rows, context references, query-state invariants, and 2,000 intent-negative checks across four workspaces. The negative corpus has 50 authored intent families with grouped speech and formatting perturbations.</p><button disabled={busy||!rows.length} onClick={runRegression}>Run regression and adversarial checks</button>{assessment&&<pre>{JSON.stringify(assessment,null,2)}</pre>}</>;
 if(tab==='Model Compare')return <><h2>Baseline and candidate on the same held-out rows</h2><button disabled={busy||!hasCandidate||!rows.length} onClick={compare}>Compare baseline and candidate</button><table><thead><tr><th>Metric</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>{(['actionAccuracy','subActionAccuracy','macroF1','subActionMacroF1','semanticExactMatch'] as const).map(key=><tr key={key}><th>{key}</th><td>{baseline?.metrics[key]?.toFixed(4)??'Not measured'}</td><td>{hasCandidate?report?.metrics[key]?.toFixed(4)??'Not measured':'No candidate'}</td></tr>)}</tbody></table></>;
 if(tab==='Publish')return <><h2>Approve candidate export</h2><p>Approval exports model JSON, weights, labels and metadata. Deployment remains an explicit separate action. The installed baseline is preserved.</p>{blocks.length?<ul>{blocks.map(b=><li key={b}>{b}</li>)}</ul>:<p>All measured publication gates pass.</p>}<button disabled={busy||blocks.length>0} onClick={approveExport}>Approve and export candidate</button></>;
 return null;
}
