import {useState} from 'react';
import snapshot from './ruhi2dPilotSummary.json';
const percentage=(value:number|null)=>value===null?'Not asserted':`${(value*100).toFixed(2)}%`;
export default function Ruhi2dAuditPanel(){
 const [report,setReport]=useState(snapshot),[error,setError]=useState('');
 const evaluation=report.evaluation;
 return <article aria-label="Ruhi 2D NLP audit"><h2>2D NLP test–train–retest audit</h2><p>Recorded native workspace evaluations · {report.generatedAt}. Administrator distribution only. Training access is controlled at the build and host boundary; this panel grants no shared model publication access.</p>
 <label>Load a newer audit summary<input type="file" accept=".json" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('Summary exceeds 2 MB.');const next=JSON.parse(await file.text());if(next.schemaVersion!==1||!next.evaluation?.metrics||!Array.isArray(next.cycles)||!next.training?.history)throw new Error('Use the generated dashboard-summary.json.');setReport(next);setError('');}catch(reason){setError(String(reason));}}}/></label>{error&&<p role="alert">{error}</p>}
 <div className="mt-stats"><div><strong>{report.dataset.total}</strong><span>Records · {report.dataset.valid} structurally valid · {report.dataset.ambiguous} ambiguous</span></div><div><strong>{report.dataset.train} / {report.dataset.validation} / {report.dataset.heldOut}</strong><span>Development / validation / held-out</span></div><div><strong>{report.cycle}</strong><span>Source repair cycle</span></div><div><strong>{evaluation.passed} / {evaluation.total}</strong><span>{evaluation.phase} end-to-end · {percentage(evaluation.endToEndAccuracy)}</span></div></div>
 <p>{report.modelVersion}. Best checkpoint: <code>{report.checkpoint}</code>. Promoted: {report.promoted?'yes':'no'}. Stop: {report.stoppingCondition}.</p>
 <table><thead><tr><th>Measured dimension</th><th>Pass / eligible</th><th>Accuracy</th></tr></thead><tbody>{Object.entries(evaluation.metrics).map(([name,value])=><tr key={name}><td>{name}</td><td>{value.passed} / {value.total}</td><td>{percentage(value.accuracy)}</td></tr>)}</tbody></table><p>Eligibility varies by record; unasserted dimensions are not credited. Dataset variants are regression coverage and do not establish unrestricted language generalization.</p>
 <h3>Cycle history</h3><table><thead><tr><th>Cycle</th><th>Scope</th><th>Pass / total</th><th>Accuracy</th></tr></thead><tbody>{report.cycles.map((cycle:{phase:string;subset:string;passed:number;total:number;endToEndAccuracy:number})=><tr key={cycle.phase}><td>{cycle.phase}</td><td>{cycle.subset}</td><td>{cycle.passed} / {cycle.total}</td><td>{percentage(cycle.endToEndAccuracy)}</td></tr>)}</tbody></table>
 <h3>Classifier training, separate from execution</h3><p>{report.training.train} compatible training rows / {report.training.validation} validation rows. Best epoch {report.training.bestEpoch}; {report.training.stoppingCondition}.</p><table><thead><tr><th>Epoch</th><th>Loss</th><th>Primary label accuracy</th><th>Prior guard</th><th>Accepted</th></tr></thead><tbody>{report.training.history.map(epoch=><tr key={epoch.epoch}><td>{epoch.epoch}</td><td>{epoch.loss.toFixed(4)}</td><td>{percentage(epoch.primaryAccuracy)}</td><td>{percentage(epoch.priorAccuracy)}</td><td>{epoch.accepted?'yes':'no'}</td></tr>)}</tbody></table>
 <h3>Training curves</h3><svg viewBox="0 0 400 110" role="img" aria-label="Measured training loss curve" style={{maxWidth:600,width:'100%'}}><path d="M 30 10 V 90 H 390" fill="none" stroke="currentColor"/><polyline points={report.training.history.map((e,i)=>`${40+i*320/Math.max(1,report.training.history.length-1)},${90-e.loss*70/Math.max(1,...report.training.history.map(e=>e.loss))}`).join(' ')} fill="none" stroke="#3b82f6" strokeWidth="2"/><polyline points={report.training.history.map((e,i)=>`${40+i*320/Math.max(1,report.training.history.length-1)},${90-e.primaryAccuracy*70}`).join(' ')} fill="none" stroke="#22c55e" strokeWidth="2"/><text x="35" y="107" fill="currentColor">Epoch → · blue: loss, green: validation accuracy</text></svg>
 <h3>Unresolved records</h3>{report.failures.length?report.failures.map((failure:{id:string;command:string;rootCause:string;reason:string})=><details key={failure.id}><summary>{failure.id}: {failure.command}</summary><p>{failure.rootCause}: {failure.reason}</p></details>):<p>No unresolved records in this evaluated scope.</p>}
 <p>Reproduce with the local CLI: <code>node scripts/ruhi-2d-nlp-run.mjs final-regression all</code>. Source repair runs in the developer environment; neural training runs locally and saves a separate checkpoint.</p></article>;
}
