import {describe,it,expect} from 'vitest';
import {SemanticEngine} from './semanticEngine';
import {readFileSync} from 'node:fs';
const modes=['geometry2d','geometry3d','graph2d','graph3d'] as const;
const run=(engine:SemanticEngine,text:string)=>engine.execute(text,async()=>undefined);
describe('Ruhi conversational continuations',()=>{
  it('understands the standalone same continuation',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a circle radius 5');await run(engine,'Move it 3 units right');expect((await run(engine,'same')).status).toBe('success');expect(engine.snapshot().objects[0].position[0]).toBe(6);});
  it('keeps object labels unique after deletion and duplication',async()=>{const engine=new SemanticEngine('geometry2d');for(let i=0;i<3;i++)await run(engine,'Draw a circle radius 5');await run(engine,'Delete C2');await run(engine,'Select C1');await run(engine,'Create another one');expect(engine.snapshot().objects).toHaveLength(3);expect(new Set(engine.snapshot().objects.map(o=>o.label)).size).toBe(3);});
  it('ordinal references retain creation order after modifying an earlier object',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');await run(engine,'Move C1 4 units right');await run(engine,'Move the first circle 2 units left');expect(engine.snapshot().objects.find(o=>o.label==='C1')?.position[0]).toBe(2);expect(engine.snapshot().objects.find(o=>o.label==='C2')?.position[0]).toBe(0);});
  it('repairs the target of a previous move without leaving its old target moved',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw line (0,0) to (4,0)');await run(engine,'Draw line (0,2) to (4,2)');await run(engine,'Move it 3 units right');expect((await run(engine,'No, the other line')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.label==='L1')?.vertices?.[0][0]).toBe(3);expect(engine.snapshot().objects.find(o=>o.label==='L2')?.vertices?.[0][0]).toBe(0);});
  it('confirms an inscribed circle before drawing',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a square side 6');expect((await run(engine,'Put a circle inside it')).status).toBe('ambiguous');expect(engine.snapshot().objects).toHaveLength(1);expect((await run(engine,'yes')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='circle')?.radius).toBe(3);});
  it('no cancels an inscribed circle proposal',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a square side 6');await run(engine,'Put a circle inside it');await run(engine,'no');expect(engine.snapshot().objects).toHaveLength(1);});
  it('chooses a rectangle diagonal explicitly',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a rectangle 4 by 6');expect((await run(engine,'Draw the diagonal')).status).toBe('ambiguous');expect((await run(engine,'2')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='line')?.vertices).toHaveLength(2);});
  it('retains the queried center while asking line direction',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a rectangle 4 by 6');await run(engine,'Find its center');expect((await run(engine,'Draw a line through it')).status).toBe('ambiguous');const vertical=await run(engine,'vertical');expect(vertical.status,vertical.message).toBe('success');const line=engine.snapshot().objects.find(o=>o.type==='line');expect(line?.vertices?.map(p=>p[0])).toEqual([0,0]);});
  it('constructs a parallel through the left edge and measures actual distance',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a rectangle 4 by 6');await run(engine,'Find its center');await run(engine,'Draw a line through it');await run(engine,'vertical');const result=await run(engine,'Make another parallel to that one through the left edge');expect(result.status).toBe('success');expect(engine.snapshot().objects.filter(o=>o.type==='line')).toHaveLength(2);const measured=await run(engine,'How far apart are they?');expect(measured.status).toBe('success');expect(measured.value,JSON.stringify({result,objects:engine.snapshot().objects})).toBe(2);expect((await run(engine,'why')).message).toMatch(/perpendicular distance/);});
  it('asks and retains the reference line for perpendicular editing',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw line (0,0) to (4,0)');await run(engine,'Draw line (0,2) to (4,2)');expect((await run(engine,'Make it perpendicular')).status).toBe('ambiguous');expect((await run(engine,'L1')).status).toBe('success');expect((await run(engine,'Are these two lines perpendicular?')).value).toBe(true);});
  it('retains a reference while asking through-point coordinates',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw line (0,0) to (4,0)');expect((await run(engine,'Draw a perpendicular line')).status).toBe('ambiguous');expect((await run(engine,'(2,3)')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(2);});
  it('preserves a named line across the endpoint follow-up',async()=>{const engine=new SemanticEngine('geometry2d');expect((await run(engine,'Draw line AB')).status).toBe('ambiguous');expect((await run(engine,'(0,0) and (4,0)')).status).toBe('success');expect(engine.snapshot().objects[0].label).toBe('AB');expect((await run(engine,'Find the midpoint of AB')).value).toEqual([2,0]);});
  it('an inscribed-circle proposal is invalidated when its square is deleted',async()=>{const engine=new SemanticEngine('geometry2d');await run(engine,'Draw a square side 6');await run(engine,'Put a circle inside it');engine.sync([]);expect(engine.workingMemory().pending).toBeUndefined();expect((await run(engine,'yes')).effects).toEqual([]);expect(engine.snapshot().objects).toEqual([]);});
  const replays=JSON.parse(readFileSync('public/datasets/math-robo-conversations.json','utf8')) as {name:string;mode:typeof modes[number];turns:string[];expected:{count:number;position?:number[];radius?:number}}[];
  for(const replay of replays)it(`Authored replay: ${replay.name}`,async()=>{const engine=new SemanticEngine(replay.mode);for(const text of replay.turns)await run(engine,text);const objects=engine.snapshot().objects;expect(objects).toHaveLength(replay.expected.count);if(replay.expected.position)expect(objects[0].position).toEqual(replay.expected.position);if(replay.expected.radius!==undefined)expect(objects[0].radius).toBe(replay.expected.radius);});
  for(const mode of modes){
    it(`${mode}: corrections revise the pending direction before any movement`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 5');await run(engine,'Move it right');expect((await run(engine,'No, left')).status).toBe('ambiguous');expect(engine.snapshot().objects[0].position[0]).toBe(0);expect((await run(engine,'3 units')).status).toBe('success');expect(engine.snapshot().objects[0].position[0]).toBe(-3);});
    it(`${mode}: incomplete destinations keep the original moving object`,async()=>{const engine=new SemanticEngine(mode),three=mode.endsWith('3d');await run(engine,'Draw a circle radius 5');const id=engine.snapshot().objects[0].id;expect((await run(engine,'Move it to point 4')).status).toBe('ambiguous');expect(engine.workingMemory().pending?.slot).toBe('destination');expect((await run(engine,three?'4,2,1':'4,2')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(1);expect(engine.snapshot().objects[0].id).toBe(id);expect(engine.snapshot().objects[0].position).toEqual(three?[4,2,1]:[4,2]);});
    it(`${mode}: reflection asks for an axis or plane appropriate to the workspace`,async()=>{const engine=new SemanticEngine(mode),three=mode.endsWith('3d');await run(engine,three?'Draw point (2,3,4)':'Draw point (2,3)');expect((await run(engine,'Reflect it')).status).toBe('ambiguous');expect(engine.workingMemory().pending?.slot).toBe(three?'plane':'axis');expect((await run(engine,three?'xy plane':'y-axis')).status).toBe('success');expect(engine.snapshot().objects[0].position).toEqual(three?[2,3,-4]:[-2,3]);});
    it(`${mode}: duplicates preserve radius with a distinct object label`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 5');expect((await run(engine,'Create another one')).status).toBe('success');expect(engine.snapshot().objects.map(o=>o.radius)).toEqual([5,5]);expect(new Set(engine.snapshot().objects.map(o=>o.label)).size).toBe(2);});
    it(`${mode}: other object references avoid the active one`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');expect((await run(engine,'Move the other one 3 units right')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.label==='C1')?.position[0]).toBe(3);expect(engine.snapshot().objects.find(o=>o.label==='C2')?.position[0]).toBe(0);});
    it(`${mode}: both answers a target clarification`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');await run(engine,'Move the circle right');await run(engine,'both');expect(engine.workingMemory().pending?.slot).toBe('distance');expect((await run(engine,'3 units')).status).toBe('success');expect(engine.snapshot().objects.every(o=>o.position[0]===3)).toBe(true);});
    it(`${mode}: clockwise answer keeps waiting for the angle`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a square side 4');await run(engine,'Rotate it');await run(engine,'clockwise');expect(engine.workingMemory().pending?.slot).toBe('angle');expect((await run(engine,'30 degrees')).status).toBe('success');expect(engine.snapshot().objects[0].command.rotation?.[2]).toBe(-30);});
    it(`${mode}: rotation target label does not supply an angle`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');expect((await run(engine,'Rotate C2')).status).toBe('ambiguous');expect(engine.workingMemory().pending?.slot).toBe('angle');});
    it(`${mode}: dimensional units must match the pending slot`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');expect((await run(engine,'3 degrees')).effects).toEqual([]);expect(engine.workingMemory().pending?.slot).toBe('distance');expect((await run(engine,'3 units')).status).toBe('success');});
    it(`${mode}: invalid numeric answers retain the question`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');for(const text of ['1/0 units','-3 units','1000000 units'])expect((await run(engine,text)).effects).toEqual([]);expect(engine.workingMemory().pending?.slot).toBe('distance');expect((await run(engine,'3 units')).status).toBe('success');});
    it(`${mode}: named triangle edges resolve to query results`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw triangle ABC');const before=engine.snapshot().objects.length;expect((await run(engine,'Find the midpoint of AB')).status).toBe('success');const value=engine.snapshot().previousResult;expect((await run(engine,'Mark it')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(before+1);expect(engine.snapshot().objects.at(-1)?.position).toEqual(value);});
    it(`${mode}: missing scale factor resumes`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');expect((await run(engine,'Scale it')).status).toBe('ambiguous');expect((await run(engine,'2')).status).toBe('success');expect(engine.snapshot().objects[0].command.scale).toBe(2);});
    it(`${mode}: same action applies to named second object`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it 3 units right');await run(engine,'Draw a circle radius 5');await run(engine,'Select C1');await run(engine,'Move it 2 units right');expect((await run(engine,'Do the same with C2')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.label==='C2')?.position[0]).toBe(2);});
    it(`${mode}: radius correction updates rather than creates`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');expect((await run(engine,'No make it 5')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(1);expect(engine.snapshot().objects[0].radius).toBe(5);});
    it(`${mode}: rotation correction changes the total angle`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a square side 4');await run(engine,'Rotate it 90 degrees');expect((await run(engine,'Actually rotate 45 degrees')).status).toBe('success');expect(engine.snapshot().objects[0].command.rotation?.[2]).toBe(45);});
    it(`${mode}: context shift cancels old pending command`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw triangle ABC');await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');expect((await run(engine,"Now let's work with triangle ABC")).status).toBe('success');expect(engine.workingMemory().pending).toBeUndefined();expect((await run(engine,'Move it 2 units left')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='circle')?.position[0]).toBe(0);});
    it(`${mode}: plural circles request radius once`,async()=>{const engine=new SemanticEngine(mode);expect((await run(engine,'Draw two circles')).status).toBe('ambiguous');expect((await run(engine,'5')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(2);expect(engine.snapshot().objects.every(o=>o.radius===5)).toBe(true);});
    it(`${mode}: no unsafe interpretation of pending numeric answers`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');for(const text of ['maybe delete it','Do not move it 3 units','the weather is 30 degrees','-Infinity','1000000000 units']){const result=await run(engine,text);expect(result.effects).toEqual([]);expect(engine.snapshot().objects[0].position[0]).toBe(0);}});
    it(`${mode}: numeric query does not become a move target`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a rectangle 4 by 6');expect((await run(engine,'Find its area')).value).toBe(24);await run(engine,'Move it right');await run(engine,'4 units');expect(engine.snapshot().objects[0].position[0]).toBe(4);expect(engine.workingMemory().lastMathResult?.value).toBe(24);expect((await run(engine,'why')).effects).toEqual([]);});
    it(`${mode}: stable numbered choices`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');expect((await run(engine,'Move the circle right')).status).toBe('ambiguous');expect(engine.workingMemory().pending?.options).toHaveLength(2);await run(engine,'second one');expect(engine.workingMemory().pending?.slot).toBe('distance');await run(engine,'3 units');expect(engine.snapshot().objects.map(o=>o.position[0])).toEqual([0,3]);});
    it(`${mode}: deleted pending target cannot be reused`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');engine.sync([]);const result=await run(engine,'3 units');expect(result.effects).toEqual([]);expect(engine.snapshot().objects).toEqual([]);expect(engine.workingMemory().pending).toBeUndefined();});
    it(`${mode}: selected object overrides previous active object`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Draw a circle radius 5');const scene=engine.snapshot();engine.sync(scene.objects,[scene.objects[0].id]);await run(engine,'Move it right');await run(engine,'2 units');expect(engine.snapshot().objects.find(o=>o.id===scene.objects[0].id)?.position[0]).toBe(2);expect(engine.snapshot().objects.find(o=>o.id===scene.objects[1].id)?.position[0]).toBe(0);});
    it(`${mode}: multi-step plan waits for final slot before mutating`,async()=>{const engine=new SemanticEngine(mode);const result=await run(engine,'Draw a circle radius 5 then move it right');expect(result.effects).toEqual([]);expect(engine.snapshot().objects).toEqual([]);expect((await run(engine,'3 units')).status).toBe('success');expect(engine.snapshot().objects).toHaveLength(1);expect(engine.snapshot().objects[0].position[0]).toBe(3);});
    it(`${mode}: history restores object after completed follow-up`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');await run(engine,'3 units');await run(engine,'undo');expect(engine.snapshot().objects[0].position[0]).toBe(0);await run(engine,'redo');expect(engine.snapshot().objects[0].position[0]).toBe(3);});
    it(`${mode}: direction and distance asked separately`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it');expect(engine.workingMemory().pending?.slot).toBe('direction');await run(engine,'right');expect(engine.workingMemory().pending?.slot).toBe('distance');await run(engine,'three units');expect(engine.snapshot().objects[0].position[0]).toBe(3);});
    it(`${mode}: cancellation does not move the subject`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');await run(engine,'Move it right');await run(engine,'no');expect(engine.snapshot().objects[0].position[0]).toBe(0);expect(engine.workingMemory().pending).toBeUndefined();});
    it(`${mode}: math definition never changes geometry`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');const before=engine.snapshot().objects;expect((await run(engine,'What is a tangent?')).message).toMatch(/perpendicular/);expect(engine.snapshot().objects).toEqual(before);});
    it(`${mode}: keeps only 25 conversation turns`,async()=>{const engine=new SemanticEngine(mode);await run(engine,'Draw a circle radius 3');for(let i=0;i<30;i++)await run(engine,'Find its area');expect(engine.workingMemory().turns).toHaveLength(25);expect(engine.workingMemory().recentCommands.length).toBeLessThanOrEqual(25);});
  }
  for(const mode of modes)for(let value=1;value<=20;value++){
    it(`${mode}: retains target and right direction for distance ${value}`,async()=>{
      const engine=new SemanticEngine(mode);expect((await run(engine,'Create a circle radius 5')).status).toBe('success');
      const id=engine.snapshot().objects[0].id,position=engine.snapshot().objects[0].position;
      expect((await run(engine,'Move it right')).status).toBe('ambiguous');expect(engine.snapshot().objects[0].position).toEqual(position);
      expect((await run(engine,`${value} units`)).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.id===id)?.position[0]).toBe(position[0]+value);
      expect(engine.workingMemory().pending).toBeUndefined();
    });
    it(`${mode}: missing rotation angle ${value}`,async()=>{
      const engine=new SemanticEngine(mode);await run(engine,'Create a rectangle 4 by 6');
      const result=await run(engine,'Now rotate it');expect(result.status).toBe('ambiguous');
      expect((await run(engine,`${value} degrees`)).status).toBe('success');expect(engine.snapshot().objects[0].command.rotation).toBeDefined();
    });
    it(`${mode}: reset cancels pending distance ${value} without removing geometry`,async()=>{
      const engine=new SemanticEngine(mode);await run(engine,`Create a circle radius ${value}`);await run(engine,'Move it left');
      await run(engine,'clear context');expect(engine.workingMemory().pending).toBeUndefined();expect(engine.snapshot().objects).toHaveLength(1);expect(engine.snapshot().objects[0].radius).toBe(value);
      await run(engine,'3 units');expect(engine.snapshot().objects[0].position[0]).toBe(0);
    });
    it(`${mode}: new complete action replaces pending distance ${value}`,async()=>{
      const engine=new SemanticEngine(mode);await run(engine,'Create a circle radius 5');await run(engine,'Move it right');
      expect((await run(engine,`Move it ${value} units left`)).status).toBe('success');expect(engine.snapshot().objects[0].position[0]).toBe(-value);expect(engine.workingMemory().pending).toBeUndefined();
    });
  }
});
