import {describe,it,expect} from 'vitest';
import {writeFileSync} from 'node:fs';
import {SemanticEngine} from './semanticEngine';
import {EngineRouter} from './engineRouter';
import {describeObject} from './sceneContext';
import {geometryState} from './resultVerifier';
import {measurement} from './geometryQueries';
import {engineCapabilities,executeCapability,validateEngineRegistry} from './engineRegistry';
import type {VisualCommand} from '../../offline-intelligence/commands';
function workspace(mode:'graph2d'|'geometry2d'|'graph3d'|'geometry3d'='graph2d'){
  const engine=new SemanticEngine(mode),committed=new Map<string,VisualCommand>();
  const run=(text:string)=>engine.execute(text,async command=>{if(command.roboControl==='delete')committed.delete(command.objectId!);else if(!command.roboControl)committed.set(command.objectId!,structuredClone(command));},undefined,()=>({objects:[...committed.values()].map(c=>describeObject(c,mode))}));
  return {engine,run};
}
describe('Central engine orchestration',()=>{
  it('routes specialist results and explains the actual preceding algebra steps',async()=>{const {engine,run}=workspace();const result=await run('Solve 2x + 5 = 17');expect(result.status,result.message).toBe('success');expect(result.message).toMatch(/6/);expect(result.engineExecution?.engineId).toBe('problem-solver');expect((await run('Show me the steps')).message).toMatch(/Move the constant term|Divide both sides/i);expect((await run('Why did you subtract 5?')).message).toMatch(/both sides/i);expect(geometryState(engine.snapshot())).toBe('[]');});
  it('keeps the required medial triangle connected to its original',async()=>{const {engine,run}=workspace();for(const prompt of ['Draw a triangle at (0,0), (6,0), (3,4).','What is its area?','Mark all three midpoints.','Join them.','What kind of triangle did we just make inside?','Make the original triangle twice as large.','Does that inner triangle still have the same relationship?','Explain why.']){const result=await run(prompt);expect(result.status,`${prompt}: ${result.message}`).toBe('success');}
    const triangles=engine.snapshot().objects.filter(o=>o.type==='triangle');expect(triangles).toHaveLength(2);expect(measurement(triangles[0],'AREA')).toBeCloseTo(48);expect(measurement(triangles[1],'AREA')).toBeCloseTo(12);expect(triangles[1].command.roboDependency?.parents).toHaveLength(3);});
  it('resolves top edge, perpendicular, width and rotation without losing the rectangle',async()=>{const {engine,run}=workspace();for(const prompt of ['Draw a rectangle 4 by 6.','Find its area.','Mark the midpoint of the top edge.','Draw a perpendicular line through that point.','Make the rectangle twice as wide.','Now rotate it 30 degrees.','What is the new area?']){const result=await run(prompt);expect(result.status,`${prompt}: ${result.message}`).toBe('success');}
    const rectangle=engine.snapshot().objects.find(o=>o.type==='rectangle')!;expect(measurement(rectangle,'AREA')).toBeCloseTo(48);expect(engine.snapshot().objects.find(o=>o.type==='point')?.command.roboDependency?.kind).toBe('midpoint');});
  it('derives discovery from callable registered capabilities and fails unknown capabilities',async()=>{const {run}=workspace();expect((await run('What can you do with matrices?')).message).toMatch(/inverse/i);expect(engineCapabilities().length).toBeGreaterThan(30);expect((await executeCapability('training.replaceWeights',{})).success).toBe(false);expect(engineCapabilities().every(e=>e.modules.every(m=>!m.includes('training')))).toBe(true);});
  it('executes multi-command construction through the existing dependency graph',async()=>{const {engine,run}=workspace();const r=await run('Create a triangle with points (0,0), (4,0), (2,3), mark the midpoint of every side and connect them.');expect(r.status,r.message).toBe('success');expect(engine.snapshot().objects.filter(o=>o.type==='triangle')).toHaveLength(2);expect(engine.snapshot().objects.filter(o=>o.command.roboDependency?.kind==='midpoint')).toHaveLength(3);});
  it('updates the tangent and marked intersection with their parents',async()=>{const {engine,run}=workspace();const tangent=await run('Draw a circle radius 5 at the origin and put a tangent at (5,0).');expect(tangent.status,tangent.message).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='line')?.command.roboDependency?.kind).toBe('tangent');expect((await run('Move the circle 2 units right.')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='line')?.vertices?.[0][0]).toBeCloseTo(7);});
  it('keeps CAS notebook assignments and bounded variable context',async()=>{const {run,engine}=workspace();expect((await run('Let a = 3')).status).toBe('success');expect((await run('Calculate a + 2')).message).toMatch(/5/);expect((await run('CAS simplify a:=4')).status).toBe('success');expect((await run('CAS simplify a+2')).message).toMatch(/6/);expect(engine.engineRouter.notebook).toHaveLength(2);});
  it('returns an input error for missing matrix arguments and a finite inverse result',async()=>{expect((await executeCapability('matrices.inverse',{args:[]})).success).toBe(false);const inverse=await executeCapability('matrices.inverse',{args:[[[1,2],[3,4]]]});expect(inverse.success).toBe(true);expect(inverse.value).toEqual([[-2,1],[1.5,-0.5]]);});

  it('verifies every registered native export exists',async()=>{const checks=await validateEngineRegistry();expect(checks.filter(c=>!c.available)).toEqual([]);expect(checks.length).toBeGreaterThan(90);writeFileSync('artifacts/math-robo-orchestration/capabilities.json',JSON.stringify({engines:engineCapabilities(),exports:checks},null,2));},30000);

  it('asks for missing data and reuses the supplied dataset for follow-ups',async()=>{const {run}=workspace();expect((await run('Find the mean')).status).toBe('ambiguous');expect((await run('2,4,6')).engineExecution?.value).toBe(4);expect((await run('And median?')).engineExecution?.value).toBe(4);expect((await run('What about half of it?')).message).toMatch(/2/);});

  it('uses foundation exact fractions and existing adaptive sampling',async()=>{expect((await executeCapability('foundation.evaluate',{text:'1/3+1/6'})).answer).toBe('1/2');const graph=await executeCapability('graph.sample',{text:'sin(x)',args:['sin(x)']});expect(graph.success).toBe(true);expect(graph.approximate).toBe(true);});
  it('grades the generated practice question through the assessment engine',async()=>{const {run,engine}=workspace();expect((await run('Quiz me')).status).toBe('success');const question=engine.engineRouter.quiz!;expect(question.validation.valid).toBe(true);expect((await run(`My answer is ${question.answer}`)).message).toMatch(/CORRECT/);});

  it('keeps a named midpoint dependent on two separately created points',async()=>{const {engine,run}=workspace();for(const text of ['Draw point A at (0,0).','Draw point B at (6,4).','Create midpoint M.','Move point A 2 units right.']){const r=await run(text);expect(r.status,r.message).toBe('success');}expect(engine.snapshot().objects.find(o=>o.command.roboDependency?.kind==='midpoint')?.position).toEqual([4,2]);});

  it('recomputes a 3D midpoint using existing vector operations',async()=>{const {engine,run}=workspace('geometry3d');for(const text of ['Draw point A at (0,0,0).','Draw point B at (6,4,2).','Create midpoint M.','Move point A 2 units right.']){const result=await run(text);expect(result.status,result.message).toBe('success');}expect(engine.snapshot().objects.find(o=>o.label==='M')?.position).toEqual([4,2,1]);});
  it('refreshes a dependency after an external workspace edit',async()=>{const {engine,run}=workspace();await run('Draw line AB from (0,0) to (6,4).');await run('Mark its midpoint.');const objects=structuredClone(engine.snapshot().objects),line=objects.find(o=>o.type==='line')!;Object.assign(line,describeObject({...line.command,points:[[2,0],[8,4]]},'graph2d'));engine.sync(objects);const effects:VisualCommand[]=[];await engine.refreshDependencies(async command=>{effects.push(command);});expect(effects).toHaveLength(1);expect(engine.snapshot().objects.find(o=>o.type==='point')?.position).toEqual([5,2]);});

  it('verifies a standalone dynamic tangent at its contact point',async()=>{const {run,engine}=workspace();await run('Draw a circle radius 5.');const result=await run('Draw a tangent at (5,0).');expect(result.status,result.message).toBe('success');expect(result.verification?.checks).toContain('Verified radius and tangent orthogonality');await run('Move the circle 2 units right.');const [a,b]=engine.snapshot().objects.find(o=>o.type==='line')!.vertices!;expect((a[0]+b[0])/2).toBeCloseTo(7);});

  it('routes an explicit new teaching problem rather than replaying the previous answer',async()=>{const {run}=workspace();await run('Solve 2x+5=17');expect((await run('Teach me how to solve 3x=12')).message).toMatch(/4/);});

  it('reuses the existing percentage scaling interpreter',async()=>{const {run,engine}=workspace();await run('Draw a circle radius 5');expect((await run('Scale it to 50%')).status).toBe('success');expect(measurement(engine.snapshot().objects[0],'RADIUS')).toBeCloseTo(2.5);expect((await run('Make it 20% larger')).status).toBe('success');expect(measurement(engine.snapshot().objects[0],'RADIUS')).toBeCloseTo(3);});

  it('converts units through the native engine and respects its rejection contract',async()=>{const {run}=workspace();expect((await run('Convert 5 cm to m')).engineExecution?.value).toBe(.05);const mismatch=await run('Convert 5 cm to kg');expect(mismatch.status).toBe('invalid');expect(mismatch.message).toMatch(/Dimension mismatch/);});

  it('resolves and tracks a named tangent point and rejects off-circle contact',async()=>{const {run,engine}=workspace();await run('Draw circle C1 radius 5.');await run('Draw point A at (0,5).');const tangent=await run('Draw a tangent to circle C1 at point A.');expect(tangent.status,tangent.message).toBe('success');const line=engine.snapshot().objects.find(o=>o.type==='line')!;expect(line.command.roboDependency?.parents).toHaveLength(2);expect(line.vertices![0][1]).toBeCloseTo(5);await run('Move point A 1 unit up.');expect(engine.snapshot().objects.find(o=>o.type==='line')!.command.roboVisible).toBe(false);});

  it('chains the existing derivative result into the native graph planner',async()=>{const {run,engine}=workspace();expect((await run('Differentiate x^2')).status).toBe('success');expect((await run('Plot it.')).status).toBe('success');expect(engine.snapshot().objects.find(o=>o.type==='plot')?.command.expression).toMatch(/2\s*\*?\s*x/);});

  it('normalizes fractional percentages through the shared number parser',async()=>{const {run,engine}=workspace();await run('Draw a circle radius 5');expect((await run('Scale it to 1/2%')).status).toBe('success');expect(measurement(engine.snapshot().objects[0],'RADIUS')).toBeCloseTo(.025);});

  it('does not consume a new drawing command as a pending numeric dataset',async()=>{const {run,engine}=workspace();await run('Find the mean');expect((await run('Draw a circle radius 5')).status).toBe('success');expect(engine.snapshot().objects[0].type).toBe('circle');expect(engine.engineRouter.pending).toBeUndefined();});

  it('shares mathematical memory across studios while keeping workspace objects separate',async()=>{const session=new EngineRouter(),cas=new SemanticEngine('normal',undefined,session),graph=new SemanticEngine('graph2d',undefined,session);await cas.execute('Solve x^2-5x+6=0',async()=>{});expect((await graph.execute('Plot it.',async()=>{})).status).toBe('success');expect(graph.snapshot().objects[0].command.expression).toContain('x^2');expect(cas.snapshot().objects).toHaveLength(0);});

});
