import fs from 'node:fs';
import {test,expect} from 'vitest';
import {SemanticEngine} from './semanticEngine';
import {describeObject} from './sceneContext';
import {vertices} from './geometryQueries';
import {deserializeRoboScene} from './mathIRAdapter';
import type {RoboMode} from './types';
import type {VisualCommand} from '../../offline-intelligence/commands';
function fixture(mode:RoboMode){const engine=new SemanticEngine(mode),native=new Map<string,VisualCommand>();const apply=async(c:VisualCommand)=>{if(c.roboClearAll)native.clear();else if(c.roboControl==='delete')native.delete(c.objectId!);else if(!c.roboControl)native.set(c.objectId!,structuredClone(c));};const read=()=>({objects:[...native.values()].map(c=>describeObject(c,mode))});const ask=(text:string)=>engine.execute(text,apply,undefined,read);return {engine,native,apply,read,ask};}
for(const mode of ['geometry2d','graph2d','geometry3d','graph3d'] as RoboMode[]){
 test(mode+' anchored side mutation preserves IDs and styles, certificates and undo/redo',async()=>{const f=fixture(mode);await f.ask('Draw triangle ABC');await f.ask('Color it blue');const original=f.engine.snapshot().objects[0],a=vertices(original);const answer=await f.ask('Change side AB to 8, keep A and C fixed and B on ray AB');expect(answer.status,answer.message).toBe('success');expect(answer.execution?.evidence.level).toBe('numerical_consistency');const edited=f.engine.snapshot().objects[0];expect(edited.id).toBe(original.id);expect(edited.style).toEqual(original.style);expect(Math.hypot(...vertices(edited)[0].map((n,i)=>n-vertices(edited)[1][i]))).toBeCloseTo(8);expect(vertices(edited)[2]).toEqual(a[2]);await f.ask('Undo');expect(vertices(f.engine.snapshot().objects[0])).toEqual(a);await f.ask('Redo');expect(vertices(f.engine.snapshot().objects[0])).toEqual(vertices(edited));});
 test(mode+' missing side constraints and failed edits cannot mutate state',async()=>{const f=fixture(mode);await f.ask('Draw triangle ABC');const before=f.engine.snapshot();const missing=await f.ask('Change side AB');expect(missing.status).toBe('ambiguous');expect(missing.clarification?.slots).toContain('triangleLength');expect(f.engine.snapshot()).toEqual(before);await f.ask('8');expect(f.engine.conversation.pending?.slot).toBe('trianglePolicy');await f.ask('Undo');await f.ask('Draw triangle ABC');const stable=f.engine.snapshot();const bad=await f.ask('Change side AB to 10000, preserve AC and BC, fix A and the AB direction, keep C on the same side');expect(bad.status).toBe('invalid');expect(f.engine.snapshot()).toEqual(stable);});
 test(mode+' versioned persistence round trips aliases/styles/history and rejects duplicate identities atomically',async()=>{const f=fixture(mode);await f.ask('Draw a rectangle');await f.ask('Make it 8 units wide');await f.ask('Make its height half its width');await f.ask('Rotate it by 30 degrees');const saved=f.engine.exportState(),fresh=fixture(mode);await fresh.engine.importState(saved,fresh.apply,fresh.read);expect(fresh.engine.canonicalGraph()).toEqual(f.engine.canonicalGraph());await fresh.ask('Undo');expect(fresh.engine.snapshot().objects[0].command.rotation).not.toEqual(f.engine.snapshot().objects[0].command.rotation);const broken=JSON.parse(saved);broken.scene.objects.push(broken.scene.objects[0]);const stable=fresh.engine.snapshot();await expect(fresh.engine.importState(JSON.stringify(broken),fresh.apply,fresh.read)).rejects.toThrow('duplicate');expect(fresh.engine.snapshot()).toEqual(stable);const future=JSON.parse(saved);future.version=2;expect(()=>deserializeRoboScene(JSON.stringify(future),mode)).toThrow('schema');});
}
test('2D circumcircle follows constrained triangle and missing-constraint question retains intent',async()=>{const f=fixture('geometry2d');await f.ask('Draw triangle ABC');await f.ask('Construct its circumcircle');const missing=await f.ask('Change side AB');expect(missing.status).toBe('ambiguous');expect((await f.ask('Does the circumcircle update?')).message).toContain('recomputed');expect(f.engine.conversation.pending?.slot).toBe('triangleLength');await f.ask('8');const answer=await f.ask('keep A and C fixed and B on ray AB');expect(answer.status,answer.message).toBe('success');expect(answer.execution?.evidence.passed).toBe(true);expect(f.engine.snapshot().objects[1].command.roboDependency?.parents[0].objectId).toBe(f.engine.snapshot().objects[0].id);});
test('queued native cancellation rolls back before a later request, without committing history',async()=>{const f=fixture('geometry2d');await f.ask('Draw circle radius 5');const original=f.engine.snapshot(),controller=new AbortController();let release!:()=>void;const waiting=new Promise<void>(resolve=>{release=resolve;});let entered!:()=>void;const started=new Promise<void>(resolve=>{entered=resolve;});const pending=f.engine.execute('Move it right by 3',async c=>{await f.apply(c);entered();await waiting;},undefined,f.read,{signal:controller.signal});await started;controller.abort();const later=f.ask('What is its radius?');release();expect((await pending).execution?.status).toBe('cancelled');expect((await later).status).toBe('success');expect(vertices(f.engine.snapshot().objects[0])).toEqual(vertices(original.objects[0]));});
test('exact five frozen transcripts run in four modes with ambiguity recorded honestly',async()=>{const source=JSON.parse(fs.readFileSync('reports/ruhi-v5.3/focused-conversations.json','utf8')),results=[];for(const mode of ['geometry2d','graph2d','geometry3d','graph3d'] as RoboMode[])for(const transcript of source.results){const f=fixture(mode),turns=[];for(const turn of transcript.turns){if(turn.text==='SAVE_RELOAD'){const saved=f.engine.exportState();await f.engine.importState(saved,f.apply,f.read);turns.push({text:turn.text,status:'success'});continue;}const r=await f.ask(turn.text);turns.push({text:turn.text,status:r.status,execution:r.execution,clarification:r.clarification,message:r.message});expect(r.execution).toBeDefined();}if(transcript===source.results[0]){expect(f.engine.snapshot().objects[0].command.radius*(f.engine.snapshot().objects[0].command.scale??1)).toBe(5);}results.push({mode,conversation:transcript.conversation,turns});}fs.mkdirSync('tmp/ruhi-test-reports',{recursive:true});fs.writeFileSync('tmp/ruhi-test-reports/five-transcripts-matrix.json',JSON.stringify({source:'reports/ruhi-v5.3/focused-conversations.json',results},null,2));});

test('supplied endpoints complete the blocked line/intersection/circle/color transcript',async()=>{const f=fixture('graph2d');expect((await f.ask('Create two intersecting lines')).status).toBe('ambiguous');expect((await f.ask('(0,0), (4,4), (0,4), (4,0)')).status).toBe('success');expect(f.engine.snapshot().objects.filter(o=>o.type==='line')).toHaveLength(2);expect((await f.ask('Find their intersection')).status).toBe('success');expect((await f.ask('Draw a circle centered there')).status).toBe('ambiguous');const created=await f.ask('Make its radius 4');expect(created.status,created.message).toBe('success');const circle=f.engine.snapshot().objects.find(o=>o.type==='circle')!;expect(circle.position).toEqual([2,2]);expect(circle.command.radius).toBe(4);const lines=f.engine.snapshot().objects.filter(o=>o.type==='line');await f.ask('Color only the circle blue');await f.ask('Undo only the color change');expect(f.engine.snapshot().objects.filter(o=>o.type==='line')).toEqual(lines);});
test('a uniquely retained triangle-side property supports increase by 2 and undo that change',async()=>{const f=fixture('geometry2d');await f.ask('Draw triangle ABC');await f.ask('Change side AB to 8, keep A and C fixed and B on ray AB');const result=await f.ask('Increase it by 2');expect(result.status,result.message).toBe('success');let v=vertices(f.engine.snapshot().objects[0]);expect(Math.hypot(...v[0].map((n,i)=>n-v[1][i]))).toBeCloseTo(10);await f.ask('Undo that change');v=vertices(f.engine.snapshot().objects[0]);expect(Math.hypot(...v[0].map((n,i)=>n-v[1][i]))).toBeCloseTo(8);});

test('cyclic dependencies and native commit exceptions reject proposed scene atomically',async()=>{const f=fixture('geometry2d');await f.ask('Draw triangle ABC');const before=f.engine.snapshot(),raw=JSON.parse(f.engine.exportState());raw.scene.objects[0].command.roboDependency={kind:'triangle',parents:[{objectId:raw.scene.objects[0].id,vertex:0}]};await expect(f.engine.importState(JSON.stringify(raw),f.apply,f.read)).rejects.toThrow('cycle');expect(f.engine.snapshot()).toEqual(before);let fail=true;const result=await f.engine.execute('Move it right by 3',async c=>{await f.apply(c);if(fail){fail=false;return 'Injected native commit failure';}},undefined,f.read);expect(result.status).toBe('invalid');expect(f.engine.snapshot()).toEqual(before);expect(f.read().objects.map(o=>vertices(o))).toEqual(before.objects.map(o=>vertices(o)));});
for(const mode of ['geometry2d','graph2d','geometry3d','graph3d'] as RoboMode[])test(mode+' a supplied vector and angle preserve magnitude under rotation',async()=>{const f=fixture(mode),points=mode.endsWith('3d')?'(0,0,0) to (3,4,0)':'(0,0) to (3,4)';await f.ask('Create a vector '+points);const original=vertices(f.engine.snapshot().objects[0]);expect((await f.ask('Rotate it')).clarification?.slots).toContain('angle');expect((await f.ask('90 degrees')).status).toBe('success');const current=vertices(f.engine.snapshot().objects[0]);const norm=(v:number[][])=>Math.hypot(...v[1].map((n,i)=>n-v[0][i]));expect(norm(original)).toBeCloseTo(5);expect(norm(current)).toBeCloseTo(5);});

test('partial side constraints remain underdetermined and never select a hidden anchoring policy',async()=>{const f=fixture('geometry2d');await f.ask('Draw triangle ABC');const before=f.engine.snapshot();const first=await f.ask('Change side AB to 8, preserve AC and BC');expect(first.status).toBe('ambiguous');expect(first.clarification?.slots).toContain('trianglePolicy');expect((await f.ask('keep A and C fixed')).status).toBe('ambiguous');expect(f.engine.snapshot()).toEqual(before);});
