import { Play, RotateCcw, Share2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import type { LessonAdapterProps } from "../../types";
import "./DeterminantTargetLesson353.css";
type Matrix=[[number,number],[number,number]];const initial:Matrix=[[3,1],[2,4]],tabs=["Interact","Learn","Examples","Formula","Practice"];
const determinant=(m:Matrix)=>m[0][0]*m[1][1]-m[0][1]*m[1][0],clean=(n:number)=>Number(n.toFixed(2));
export default function DeterminantTargetLesson353({resetToken,onInteraction}:LessonAdapterProps){
 const[matrix,setMatrix]=useState<Matrix>(initial),[challenge,setChallenge]=useState<Matrix>(initial),[challengeResult,setChallengeResult]=useState<""|"correct"|"incorrect">(""),[view,setView]=useState<"parallelogram"|"unit">("parallelogram"),[animating,setAnimating]=useState(false),[progress,setProgress]=useState(1),[tab,setTab]=useState(tabs[0]),[actions,setActions]=useState(0);const drag=useRef<0|1|null>(null),det=determinant(matrix),ad=matrix[0][0]*matrix[1][1],bc=matrix[0][1]*matrix[1][0],orientation=det>0?"Positive (counterclockwise)":det<0?"Negative (clockwise)":"Zero (collinear)",singular=det===0,challengeDet=determinant(challenge);
 const act=(fn:()=>void)=>{fn();setActions(v=>v+1);onInteraction()},reset=()=>{setMatrix(initial);setChallenge(initial);setChallengeResult("");setView("parallelogram");setAnimating(false);setProgress(1);setTab(tabs[0]);setActions(0)};useEffect(reset,[resetToken]);
 useEffect(()=>{if(!animating)return;const id=window.setInterval(()=>setProgress(p=>p>=1?0:Math.min(1,p+.08)),90);return()=>clearInterval(id)},[animating]);
 const edit=(target:"matrix"|"challenge",r:number,c:number,v:number)=>act(()=>(target==="matrix"?setMatrix:setChallenge)(m=>m.map((row,i)=>row.map((x,j)=>i===r&&j===c?v:x)) as Matrix));
 const dragMove=(e:ReactPointerEvent<SVGSVGElement>)=>{if(drag.current===null||e.buttons!==1)return;const rect=e.currentTarget.getBoundingClientRect(),x=Math.round((((e.clientX-rect.left)/rect.width)*520-260)/42),y=Math.round((190-((e.clientY-rect.top)/rect.height)*380)/42),col=drag.current;setMatrix(m=>{const n=m.map(row=>[...row]) as Matrix;n[0][col]=Math.max(-5,Math.min(5,x));n[1][col]=Math.max(-4,Math.min(5,y));return n})};
 return <section className="mat353-page" data-testid="matrix-mockup-0538" data-object-model="editable-two-by-two-matrix-determinant-products-draggable-column-vectors-signed-area-orientation-singularity-view-animation-independent-zero-challenge" data-matrix={matrix.flat().join(",")} data-ad={ad} data-bc={bc} data-det={det} data-orientation={orientation} data-singular={singular} data-view={view} data-animating={animating} data-progress={clean(progress)} data-challenge={challenge.flat().join(",")} data-challenge-det={challengeDet} data-challenge-result={challengeResult} data-tab={tab} data-actions={actions}>
  <header className="mat353-hero"><div><h1>Determinant</h1><p>Area scale and orientation</p><span><b>ADVANCED MATHEMATICS</b><b>MATRICES AND LINEAR ALGEBRA</b></span><section><b>2x2 Matrix</b><b>Signed Area</b><b>6-10 min</b></section></div><nav><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>act(()=>{})}><Share2/>Share</button></nav></header>
  <nav className="mat353-tabs">{tabs.map(name=><button className={tab===name?"active":""} key={name} onClick={()=>act(()=>setTab(name))}>{name}</button>)}</nav>
  <section className="mat353-main"><aside><h3>2x2 MATRIX &nbsp; A = [a b; c d]</h3><MatrixInputs matrix={matrix} onEdit={(r,c,v)=>edit("matrix",r,c,v)}/><div className="mat353-products"><span><b>ad (cyan)</b><code>a x d = {ad}</code></span><span><b>bc (violet)</b><code>b x c = {bc}</code></span></div><div className="mat353-formula"><code>det(A) = ad - bc<br/>= {ad} - {bc} = <b>{det}</b></code></div><h4>Orientation</h4><strong>{orientation}</strong><h4>Status</h4><strong>{singular?"Singular (det(A) = 0)":"Non-singular (det(A) != 0)"}</strong></aside>
   <article className="mat353-graph"><h3>GEOMETRIC VIEW - SIGNED AREA</h3><DeterminantGraph matrix={matrix} progress={progress} view={view} onStart={col=>drag.current=col} onMove={dragMove} onEnd={()=>{if(drag.current!==null){drag.current=null;setActions(v=>v+1);onInteraction()}}}/><div className="mat353-legend"><p><i/>a = ({matrix[0][0]}, {matrix[1][0]})<br/>1st column</p><p><i/>b = ({matrix[0][1]}, {matrix[1][1]})<br/>2nd column</p><strong>Signed area = <b>{det}</b><small>Area scale x |det(A)|<br/>Orientation from sign</small></strong></div><footer><button className={view==="parallelogram"?"active":""} onClick={()=>act(()=>setView("parallelogram"))}>Parallelogram view</button><button className={view==="unit"?"active":""} onClick={()=>act(()=>setView("unit"))}>Unit square view</button><button onClick={()=>act(()=>setAnimating(v=>!v))}><Play/>{animating?"Pause":"Animate"}</button></footer></article>
  </section>
  <section className="mat353-bottom"><article><h3>✓ WORKED EXAMPLE</h3><p>Compute det(A) for A = [{matrix[0].join(" ")}; {matrix[1].join(" ")}]</p><code>ad = {matrix[0][0]} x {matrix[1][1]} = {ad}</code><code>bc = {matrix[0][1]} x {matrix[1][0]} = {bc}</code><code>det(A) = ad - bc = {ad} - {bc} = {det}</code><strong>det(A) = {det}</strong></article><article><h3>☆ CHALLENGE</h3><h2>Make det(A) = 0</h2><p>Adjust the entries to make the determinant zero (the two vectors should be collinear).</p><div><MatrixInputs matrix={challenge} onEdit={(r,c,v)=>edit("challenge",r,c,v)}/><aside><code>det(A) = ad - bc<br/>= {challenge[0][0]*challenge[1][1]} - {challenge[0][1]*challenge[1][0]} = {challengeDet}</code><button onClick={()=>act(()=>setChallengeResult(challengeDet===0?"correct":"incorrect"))}>Check</button><output>{challengeResult==="correct"?"Correct: the columns are linearly dependent.":challengeResult==="incorrect"?"Not zero yet. Make one column a scalar multiple of the other.":""}</output></aside></div></article></section>
  <p className="mat353-tip">Tip: det(A) measures signed area scale and orientation of the linear map. Positive preserves orientation; negative flips orientation.</p>
 </section>
}
function MatrixInputs({matrix,onEdit}:{matrix:Matrix;onEdit:(r:number,c:number,v:number)=>void}){return <div className="mat353-inputs"><span/><b>Column 1</b><b>Column 2</b>{matrix.flatMap((row,r)=>[<b key={`r${r}`}>Row {r+1}</b>,...row.map((v,c)=><label key={`${r}-${c}`}><i>{["a","b","c","d"][r*2+c]}</i><input aria-label={`Determinant matrix row ${r+1} column ${c+1}`} type="number" value={v} onChange={e=>onEdit(r,c,Number(e.target.value))}/></label>)])}</div>}
function DeterminantGraph({matrix,progress,view,onStart,onMove,onEnd}:{matrix:Matrix;progress:number;view:string;onStart:(c:0|1)=>void;onMove:(e:ReactPointerEvent<SVGSVGElement>)=>void;onEnd:()=>void}){const origin={x:260,y:190},point=(c:number)=>({x:origin.x+matrix[0][c]*42*progress,y:origin.y-matrix[1][c]*42*progress}),a=point(0),b=point(1),sum={x:a.x+b.x-origin.x,y:a.y+b.y-origin.y};return <svg viewBox="0 0 520 380" role="img" aria-label="Draggable determinant signed-area view" onPointerMove={onMove} onPointerUp={onEnd}>{Array.from({length:11},(_,i)=><g key={i}><line x1={50+i*42} y1="20" x2={50+i*42} y2="360" className="grid"/><line x1="40" y1={22+i*34} x2="500" y2={22+i*34} className="grid"/></g>)}<line x1="30" y1={origin.y} x2="505" y2={origin.y} className="axis"/><line x1={origin.x} y1="15" x2={origin.x} y2="365" className="axis"/>{view==="parallelogram"?<polygon points={`${origin.x},${origin.y} ${a.x},${a.y} ${sum.x},${sum.y} ${b.x},${b.y}`} className="area"/>:<rect x={origin.x} y={origin.y-42} width="42" height="42" className="unit"/>}<line x1={origin.x} y1={origin.y} x2={a.x} y2={a.y} className="a"/><line x1={origin.x} y1={origin.y} x2={b.x} y2={b.y} className="b"/><circle data-drag="determinant-column-1" cx={a.x} cy={a.y} r="8" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);onStart(0)}}/><circle data-drag="determinant-column-2" cx={b.x} cy={b.y} r="8" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);onStart(1)}}/></svg>}
