import { RotateCcw, Share2 } from "lucide-react";
import { useEffect, useState } from "react";
import type { LessonAdapterProps } from "../../types";
import "./MatrixAdditionTargetLesson348.css";
type Matrix = number[][];
type Operation = "add" | "subtract";
const startA: Matrix = [[1, -2, 3], [4, 0, 2]], startB: Matrix = [[3, 5, -1], [-2, 1, 4]];
const tabs = ["Interaction + visualization", "Explain", "Examples", "Formulas", "Know more"];
const combine = (a: Matrix, b: Matrix, operation: Operation) => a.map((row, r) => row.map((v, c) => operation === "add" ? v + b[r][c] : v - b[r][c]));
const flat = (a: Matrix) => a.flat().join(",");
export default function MatrixAdditionTargetLesson348({ resetToken, onInteraction }: LessonAdapterProps) {
  const [a, setA] = useState(startA), [b, setB] = useState(startB), [operation, setOperation] = useState<Operation>("add"),
    [animation, setAnimation] = useState(true), [step, setStep] = useState(false), [tab, setTab] = useState(tabs[0]),
    [quick, setQuick] = useState<"" | "correct" | "incorrect">("correct"), [actions, setActions] = useState(0), [notice, setNotice] = useState("");
  const result = combine(a, b, operation), symbol = operation === "add" ? "+" : "-", compatible = a.length === b.length && a[0].length === b[0].length;
  const act = (fn: () => void) => { fn(); setActions((v) => v + 1); onInteraction(); };
  const reset = () => { setA(startA); setB(startB); setOperation("add"); setAnimation(true); setStep(false); setTab(tabs[0]); setQuick("correct"); setActions(0); setNotice(""); };
  useEffect(reset, [resetToken]);
  const update = (which: "a" | "b", r: number, c: number, value: number) => act(() => (which === "a" ? setA : setB)((m) => m.map((row, ri) => row.map((v, ci) => ri === r && ci === c ? value : v))));
  return <section className="mat348-page" data-testid="matrix-mockup-0533" data-object-model="two-editable-compatible-matrices-elementwise-addition-subtraction-derived-result-cell-trace-vector-geometry-vectorization-animation-assessment"
    data-a={flat(a)} data-b={flat(b)} data-result={flat(result)} data-operation={operation} data-compatible={compatible} data-animation={animation} data-step={step} data-tab={tab} data-quick={quick} data-actions={actions}>
    <header className="mat348-hero"><span><b>ADVANCED MATHEMATICS</b><b>MATRICES AND LINEAR ALGEBRA</b></span><h1>Matrix Addition and Subtraction</h1><p>Perform element-wise operations.</p><div><b>Advanced</b><b>Linear Algebra Lab</b><b>Matrix Commands / CAS</b><b>6-10 min</b></div><nav><select aria-label="Language"><option>English (English)</option></select><button onClick={reset}><RotateCcw/>Reset</button><button onClick={() => act(() => setNotice("Share link ready."))}><Share2/>Share</button><button onClick={() => act(() => setNotice("Opened in matrix workspace."))}>Workspace</button></nav></header>
    <nav className="mat348-tabs">{tabs.map((name) => <button className={tab === name ? "active" : ""} key={name} onClick={() => act(() => setTab(name))}>{name}</button>)}</nav>
    <section className="mat348-overview"><article><h3>Learning objective</h3><p>Add or subtract matrices of the same order using element-wise operations and interpret the result.</p></article><article><h3>Operations</h3><p><i className="cyan"/> Addition (A + B)</p><p><i/> Subtraction (A - B)</p></article><article><h3>Notation</h3><p>If A, B in M<sub>m x n</sub>, then A +/- B is in M<sub>m x n</sub>.</p></article><article><h3>Compatibility</h3><p>Matrices must have the <b>same dimensions</b> (m x n).</p></article></section>
    <section className="mat348-lab"><header><span><b>INTERACTIVE LAB</b><h2>Compute A +/- B</h2><p>Edit the entries. See the element-wise operation, result, and geometric interpretation.</p></span><label>Animation <input aria-label="Animation" type="checkbox" checked={animation} onChange={() => act(() => setAnimation((v) => !v))}/></label><label>Step by step <input aria-label="Step by step" type="checkbox" checked={step} onChange={() => act(() => setStep((v) => !v))}/></label></header>
      <div className="mat348-compute"><MatrixEditor label="Matrix A" tone="cyan" matrix={a} onChange={(r,c,v) => update("a",r,c,v)}/><span className="mat348-symbol">{symbol}</span><MatrixEditor label="Matrix B" tone="violet" matrix={b} onChange={(r,c,v) => update("b",r,c,v)}/><div className="mat348-ops"><button className={operation === "add" ? "active" : ""} onClick={() => act(() => setOperation("add"))}>A + B</button><b>⇄</b><button className={operation === "subtract" ? "active" : ""} onClick={() => act(() => setOperation("subtract"))}>A - B</button></div><b className="mat348-arrow">→</b><MatrixDisplay label="Result" matrix={result}/></div>
      <h3>Cell-by-cell computation</h3><div className="mat348-cells">{result.flatMap((row,r) => row.map((v,c) => <code key={`${r}-${c}`}>{a[r][c]} {symbol} {b[r][c]} = <b>{v}</b></code>))}</div>
      <div className="mat348-analysis"><article><h3>Geometric interpretation (row vectors)</h3><p>View each row as a vector in R<sup>3</sup>. {operation === "add" ? "Addition is head-to-tail." : "Subtraction adds the opposite vector."}</p><VectorDiagram a={a} b={b} result={result}/></article><article><h3>Dimension check</h3><p>Both matrices must have the same order.</p><dl><dt>A order:</dt><dd>2 x 3 ✓</dd><dt>B order:</dt><dd>2 x 3 ✓</dd><dt>Compatible:</dt><dd>{compatible ? "Yes" : "No"}</dd></dl><h4>Vectorized view</h4><p>vec(A) {symbol} vec(B) = vec(A {symbol} B)</p><div className="mat348-vectors"><code>[{flat(a)}]</code><b>{symbol}</b><code>[{flat(b)}]</code><b>=</b><code>[{flat(result)}]</code></div></article></div>{notice && <output>{notice}</output>}
    </section>
    <section className="mat348-notes"><article><h3>Guided explanation</h3><ol><li>Matrices A and B must have the same dimensions.</li><li>Addition/subtraction are defined element-wise.</li><li>The result has the same order.</li><li>Geometrically, each row vector adds/subtracts as vectors in R<sup>3</sup>.</li></ol></article><article><h3>Key insight</h3><p>Matrix addition/subtraction preserves dimensions and structure, ideal for comparing systems, updating states, and forming linear combinations.</p></article><article><h3>Assumptions & constraints</h3><p>✓ Entries are real numbers.</p><p>✓ Matrices must be finite and rectangular.</p><p>✓ Operations are element-wise.</p></article><article className="misconception"><h3>Common misconception</h3><p>You cannot add/subtract matrices just because they look similar. The orders must match exactly.</p><code>[1 2; 3 4] + [1 2 3; 4 5 6] is not defined.</code></article></section>
    <section className="mat348-check"><header><h3>Quick check</h3><p>Attempt a similar problem. Compute A - B.</p></header><article><p>A = [2 1 0; -1 3 4] &nbsp; B = [-1 2 3; 0 1 -2]</p>{["[3,-1,-3;-1,2,6]","[1,-1,-3;-1,2,6]","[3,3,3;-1,2,2]","[1,-1,-3;1,2,2]"].map((answer,i) => <button className={quick === (i === 0 ? "correct" : "incorrect") ? quick : ""} key={answer} onClick={() => act(() => setQuick(i === 0 ? "correct" : "incorrect"))}>{String.fromCharCode(65+i)}. {answer}</button>)}</article><aside><h3>{quick === "correct" ? "Correct!" : "Try again"}</h3><p>A - B = [3,-1,-3; -1,2,6]</p><p>Well done! You subtracted element-wise.</p><button onClick={() => act(() => setQuick(""))}>Try another</button></aside></section>
  </section>;
}
function MatrixEditor({ label, tone, matrix, onChange }: { label:string; tone:string; matrix:Matrix; onChange:(r:number,c:number,v:number)=>void }) { return <div className={`mat348-matrix ${tone}`}><h3>{label} (2 x 3)</h3><div>{matrix.flatMap((row,r) => row.map((v,c) => <input key={`${r}-${c}`} aria-label={`${label} row ${r+1} column ${c+1}`} type="number" value={v} onChange={(e) => onChange(r,c,Number(e.target.value))}/>))}</div><code>{label.at(-1)} = [ {matrix[0].join("  ")} | {matrix[1].join("  ")} ]</code></div>; }
function MatrixDisplay({ label, matrix }: { label:string; matrix:Matrix }) { return <div className="mat348-matrix result"><h3>{label} (2 x 3)</h3><div>{matrix.flatMap((row,r) => row.map((v,c) => <b key={`${r}-${c}`}>{v}</b>))}</div><code>A +/- B = [ {matrix[0].join("  ")} | {matrix[1].join("  ")} ]</code></div>; }
function VectorDiagram({ a,b,result }: { a:Matrix;b:Matrix;result:Matrix }) { const point=(v:number[], ox:number,oy:number) => ({x:ox+v[1]*12,y:oy-v[0]*18-v[2]*5}); return <svg viewBox="0 0 360 180" role="img" aria-label="Row vector geometric interpretation">{[0,1].map((r) => {const o={x:75,y:55+r*85}, pa=point(a[r],o.x,o.y), pb=point(b[r],pa.x,pa.y), pr=point(result[r],o.x,o.y); return <g key={r}><line x1={o.x} y1={o.y} x2={pa.x} y2={pa.y} className="va"/><line x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y} className="vb" strokeDasharray="5 4"/><line x1={o.x} y1={o.y} x2={pr.x} y2={pr.y} className="vr"/><circle cx={o.x} cy={o.y} r="3"/><text x={pr.x+4} y={pr.y}>a{r+1} {result===a?"":"+ b"}{r+1}</text></g>})}</svg>; }
