import { Play, RotateCcw, Shuffle, TableProperties } from "lucide-react";
import { useEffect, useState } from "react";
import type { LessonAdapterProps } from "../../types";
import "./TransposeTargetLesson352.css";
type Matrix=number[][];
const initial:Matrix=[[1,2,3],[4,5,6]],tabs=["Interaction + visualization","Explain","Examples","Formulas","Know more"];
const transpose=(m:Matrix)=>Array.from({length:m[0].length},(_,c)=>m.map(row=>row[c]));
export default function TransposeTargetLesson352({resetToken,onInteraction}:LessonAdapterProps){
 const[matrix,setMatrix]=useState(initial),[selected,setSelected]=useState<[number,number]>([0,1]),[numeric,setNumeric]=useState(false),[animating,setAnimating]=useState(true),[tab,setTab]=useState(tabs[0]),[actions,setActions]=useState(0);const transposed=transpose(matrix),[r,c]=selected;
 const act=(fn:()=>void)=>{fn();setActions(v=>v+1);onInteraction()},reset=()=>{setMatrix(initial);setSelected([0,1]);setNumeric(false);setAnimating(true);setTab(tabs[0]);setActions(0)};useEffect(reset,[resetToken]);
 useEffect(()=>{if(!animating)return;const id=window.setInterval(()=>setSelected(([ri,ci])=>{const n=ri*3+ci+1;return[Math.floor((n%6)/3),n%3]}),1500);return()=>clearInterval(id)},[animating]);
 const label=(ri:number,ci:number)=>numeric?matrix[ri][ci]:`a${ri+1}${ci+1}`,choose=(ri:number,ci:number)=>act(()=>{setSelected([ri,ci]);setAnimating(false)});
 return <section className="mat352-page" data-testid="matrix-mockup-0537" data-object-model="symbolic-numeric-two-by-three-matrix-derived-transpose-selectable-entry-bidirectional-position-mapping-curved-path-inspector-animation" data-matrix={matrix.flat().join(",")} data-transposed={transposed.flat().join(",")} data-selected={`${r},${c}`} data-selected-value={matrix[r][c]} data-numeric={numeric} data-animating={animating} data-tab={tab} data-actions={actions}>
  <h1>Transpose</h1><nav className="mat352-tabs">{tabs.map(name=><button className={tab===name?"active":""} key={name} onClick={()=>act(()=>setTab(name))}>{name}</button>)}</nav>
  <div className="mat352-layout"><main><header><h2>Swap rows and columns</h2><p>Transpose flips a matrix over its diagonal: rows become columns and columns become rows.</p></header><section className="mat352-map"><div className="mat352-original"><h3>Original matrix A <b>A is 2x3</b></h3><MatrixGrid matrix={matrix} selected={selected} numeric={numeric} transposeView={false} onChoose={choose}/></div><div className="mat352-center"><p>mirror across<br/>diagonal</p><b>row 1 becomes<br/>column 1</b><b>row 2 becomes<br/>column 2</b></div><div className="mat352-transposed"><h3>Transposed matrix A<sup>T</sup> <b>A<sup>T</sup> is 3x2</b></h3><MatrixGrid matrix={transposed} selected={[c,r]} numeric={numeric} transposeView onChoose={(tr,tc)=>choose(tc,tr)}/></div><svg viewBox="0 0 900 300" aria-label="Selected transpose entry mapping"><path className="orange" d={`M ${175+c*82} ${95+r*82} C 430 ${50+r*45}, 520 ${40+c*75}, ${690+r*82} ${95+c*70}`}/><path className="violet" d="M175 177 C400 300,590 270,772 95"/></svg><aside>Diagonal entries stay in place when the matrix is square.</aside></section>
   <section className="mat352-rule"><div><h3>Entry mapping rule</h3><p>Each entry a<sub>ij</sub> in A moves to position (j, i) in A<sup>T</sup>.</p></div><code>(A<sup>T</sup>)<sub>ij</sub> = A<sub>ji</sub></code><span><b>● a<sub>12</sub> moves to a<sub>21</sub></b><b>● a<sub>21</sub> moves to a<sub>12</sub></b></span></section>
   <footer><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>act(()=>{setMatrix(matrix.map(row=>row.map(()=>Math.floor(Math.random()*19)-9)));setNumeric(true)})}><Shuffle/>Randomize</button><button onClick={()=>act(()=>setNumeric(true))}><TableProperties/>Fill with numbers</button><label><Play/>Animate mapping <input aria-label="Animate mapping" type="checkbox" checked={animating} onChange={()=>act(()=>setAnimating(v=>!v))}/></label></footer>
  </main><aside className="mat352-inspector"><article><h3>Inspect entry</h3><strong>{label(r,c)}</strong><h4>Original position in A</h4><p>row {r+1}, column {c+1} ({r+1}, {c+1})</p><h4>Transposed position in A<sup>T</sup></h4><p>row {c+1}, column {r+1} ({c+1}, {r+1})</p><h4>Entry mapping</h4><code>a<sub>{r+1}{c+1}</sub> ↔ a<sub>{c+1}{r+1}</sub></code><h4>Dimensions</h4><code>m x n → n x m<br/>2 x 3 → 3 x 2</code></article><article><h3>Key properties</h3><p>✓ (A<sup>T</sup>)<sup>T</sup> = A</p><p>✓ (A + B)<sup>T</sup> = A<sup>T</sup> + B<sup>T</sup></p></article><article><h3>Why it matters</h3><b>Transpose changes the shape by swapping rows and columns, but preserves the relationships between entries.</b></article></aside></div>
 </section>
}
function MatrixGrid({matrix,selected,numeric,transposeView,onChoose}:{matrix:Matrix;selected:[number,number];numeric:boolean;transposeView:boolean;onChoose:(r:number,c:number)=>void}){return <div className="mat352-grid-wrap"><div className="mat352-col-labels" style={{gridTemplateColumns:`repeat(${matrix[0].length},82px)`}}>{matrix[0].map((_,c)=><b key={c}>col {c+1}</b>)}</div><div className="mat352-grid" style={{gridTemplateColumns:`42px repeat(${matrix[0].length},82px)`}}>{matrix.flatMap((row,r)=>[<b key={`r${r}`}>row {r+1}</b>,...row.map((v,c)=><button className={selected[0]===r&&selected[1]===c?selected[0]===0&&selected[1]===1?"orange":"violet":""} key={`${r}-${c}`} onClick={()=>onChoose(r,c)}>{numeric?v:<em>a<sub>{transposeView?c+1:r+1}{transposeView?r+1:c+1}</sub></em>}</button>)])}</div></div>}
