import type { StrengthenedLesson } from "../strengthenedLessonSchema";

export type RegressionProbabilityChallenge = {
  prompt: string;
  expected: string;
  hint: string;
  kind: "numeric" | "keywords" | "interaction";
  factoryId: string;
};

type FormulaSeed = {
  label: string;
  expression: string;
  variables: Array<{ symbol: string; meaning: string }>;
  restrictions?: string[];
  exactness?: "exact" | "approximation" | "definition" | "theorem" | "identity";
};

type Seed = {
  id: number;
  title: string;
  slug: string;
  topic: "Statistics and Regression" | "Probability and Distributions";
  lessonType: StrengthenedLesson["lessonType"];
  definition: string;
  action: string;
  reason: string;
  representation: "table" | "function_graph" | "coordinate_graph" | "tree_diagram" | "venn_diagram" | "probability_simulation" | "distribution_plot";
  misconception: [string, string, string];
  examples: [string, string][];
  challenge: RegressionProbabilityChallenge;
  formula?: FormulaSeed;
};

const data: Record<number, Seed> = {
  493: item(493, "Logarithmic Regression", "logarithmic-regression", "Statistics and Regression", "modelling", "Logarithmic regression fits data that changes quickly at first and then changes more slowly.", "Plot the data, check for slowing growth, fit a logarithmic model, and inspect residuals.", "A logarithm grows by smaller and smaller amounts as x increases.", "function_graph", ["LOG_WITH_BAD_X", "Using logarithmic regression when x values are zero or negative.", "A real logarithmic model needs positive x values."], [["Sound level", "Decibels use a logarithmic scale."], ["Early learning curve", "Fast gains can slow down later."], ["Plant response", "Some responses rise quickly then level off."]], "What must x-values be for a real logarithmic model?", "positive", { label: "Logarithmic model", expression: "y = a + b ln(x)", variables: [{ symbol: "x", meaning: "positive input value" }, { symbol: "a", meaning: "vertical shift" }, { symbol: "b", meaning: "scale factor" }], restrictions: ["x must be greater than 0."], exactness: "approximation" }),
  494: item(494, "Power Regression", "power-regression", "Statistics and Regression", "modelling", "Power regression fits data where one variable is proportional to a power of another.", "Plot the data, check for a power pattern, fit y = ax^b, and inspect residuals.", "Power models describe scale laws where multiplying x changes y by a predictable factor.", "function_graph", ["POWER_AS_EXPONENTIAL", "Confusing a power model y = ax^b with an exponential model y = ab^x.", "In a power model the variable is the base, not the exponent."], [["Area of a square", "Area follows side length squared."], ["Physics scaling", "Some quantities follow inverse-square rules."], ["Body measurements", "Some relationships follow power laws."]], "In y = ax^b, which symbol is the variable base?", "x", { label: "Power model", expression: "y = ax^b", variables: [{ symbol: "a", meaning: "scale factor" }, { symbol: "b", meaning: "power" }, { symbol: "x", meaning: "positive input value" }], restrictions: ["Use positive x values for standard real power regression."], exactness: "approximation" }),
  495: item(495, "Logistic Regression", "logistic-regression", "Statistics and Regression", "modelling", "Logistic regression for growth fits an S-shaped curve with an upper limit.", "Plot the data, check for a leveling pattern, fit the model, and compare residuals.", "The model grows fast in the middle but slows near a carrying capacity.", "function_graph", ["NO_UPPER_LIMIT", "Using logistic regression when there is no sensible maximum level.", "Use it when the context has a natural upper limit."], [["Population in a limited habitat", "Growth slows near carrying capacity."], ["App adoption", "Users may level off near a market size."], ["Spread of news", "Growth can slow after most people hear it."]], "A logistic growth model has an upper what?", "limit", { label: "Logistic shape", expression: "y = L / (1 + ae^(-kx))", variables: [{ symbol: "L", meaning: "upper limit" }, { symbol: "a", meaning: "positive shape constant" }, { symbol: "k", meaning: "growth rate" }], restrictions: ["L is positive in a standard growth setting."], exactness: "approximation" }),
  496: item(496, "Sinusoidal Regression", "sinusoidal-regression", "Statistics and Regression", "modelling", "Sinusoidal regression fits data that repeats in a wave pattern.", "Plot the data, estimate period and amplitude, fit a sine or cosine model, and inspect residuals.", "Sine and cosine repeat because angles cycle around a circle.", "function_graph", ["NO_PERIOD", "Using a sinusoidal model for data with no repeated cycle.", "Use sinusoidal regression only when a repeating period is sensible."], [["Daily temperature", "Temperature often rises and falls each day."], ["Tides", "Water height repeats in cycles."], ["Seasonal sales", "Some sales repeat yearly."]], "Sinusoidal regression is used for data with a repeated what?", "cycle", { label: "Sinusoidal model", expression: "y = A sin(Bx + C) + D", variables: [{ symbol: "A", meaning: "amplitude" }, { symbol: "B", meaning: "frequency factor" }, { symbol: "D", meaning: "midline" }], restrictions: ["Use when the context supports periodic behaviour."], exactness: "approximation" }),
  497: item(497, "Residual Plot", "residual-plot", "Statistics and Regression", "visual_exploration", "A residual plot shows prediction errors from a fitted model.", "Find each residual as observed minus predicted, plot residuals, and look for patterns.", "A good model often leaves residuals with no clear shape around zero.", "coordinate_graph", ["IGNORE_PATTERN", "Ignoring a clear curve or pattern in residuals.", "A residual pattern means the model may be missing structure."], [["Line fit", "Residuals show whether a line missed a curve."], ["Sales model", "Errors reveal seasonal patterns."], ["Science data", "Residuals check whether the model fits."]], "Residual equals observed minus what?", "predicted", { label: "Residual", expression: "residual = observed - predicted", variables: [{ symbol: "observed", meaning: "actual data value" }, { symbol: "predicted", meaning: "model value" }], exactness: "definition" }),
  498: item(498, "Model Comparison", "model-comparison", "Statistics and Regression", "modelling", "Model comparison decides which model explains data best without adding needless complexity.", "Compare plots, residuals, error size, simplicity, and context.", "A model should fit the pattern and still make scientific or practical sense.", "table", ["FIT_ONLY", "Choosing a model only because it has the smallest error.", "Also check residual patterns, simplicity, and context."], [["Weather model", "A simpler model may predict better."], ["Business sales", "Compare linear and seasonal models."], ["Science experiment", "The chosen model should match the mechanism."]], "Besides error size, what should model comparison check?", "context"),
  499: item(499, "Interpolation and Extrapolation", "interpolation-and-extrapolation", "Statistics and Regression", "concept", "Interpolation predicts inside the data range, while extrapolation predicts outside it.", "Locate the known data range, then decide whether the prediction is inside or outside that range.", "Predictions inside observed data are usually safer than predictions far beyond it.", "function_graph", ["FAR_EXTRAPOLATION", "Trusting far extrapolation as if it were measured data.", "Treat far outside predictions as uncertain unless the context strongly supports them."], [["Temperature between hours", "Estimating noon from 10 and 2 is interpolation."], ["Future population", "Predicting many years ahead is extrapolation."], ["Price table", "Estimating within listed sizes is interpolation."]], "Which is usually safer: interpolation or extrapolation?", "interpolation"),
  500: item(500, "Sample Spaces", "sample-spaces", "Probability and Distributions", "concept", "A sample space is the set of all possible outcomes of a random experiment.", "List every possible outcome once before counting favourable outcomes.", "Probability needs the full set of possible outcomes as its denominator when outcomes are equally likely.", "table", ["MISSING_OUTCOME", "Leaving possible outcomes out of the sample space.", "List all outcomes before calculating probability."], [["Coin toss", "The sample space is H, T."], ["Die roll", "The sample space is 1 through 6."], ["Two children", "Possible birth orders form a sample space."]], "How many outcomes are in one fair die roll?", "6"),
  501: item(501, "Events", "events", "Probability and Distributions", "concept", "An event is a set of outcomes from a sample space.", "Choose the outcomes that match the condition and group them as the event.", "Events let us talk about one question inside a larger random experiment.", "table", ["EVENT_AS_ONE_OUTCOME", "Thinking an event must contain only one outcome.", "An event can contain one, many, or no outcomes."], [["Die roll even", "The event is 2, 4, 6."], ["Card is a heart", "All hearts form one event."], ["Rain tomorrow", "The event contains outcomes where rain happens."]], "For a die, how many outcomes are in the event even?", "3"),
  502: item(502, "Probability Scale", "probability-scale", "Probability and Distributions", "concept", "The probability scale runs from 0 for impossible to 1 for certain.", "Place impossible, unlikely, equally likely, likely, and certain events between 0 and 1.", "Probability measures chance as a fraction of certainty.", "distribution_plot", ["OVER_ONE", "Writing a probability greater than 1.", "A valid probability must be between 0 and 1 inclusive."], [["Sun rising tomorrow", "This is very close to certain in daily language."], ["Rolling a 7 on one die", "This is impossible."], ["Fair coin heads", "This has probability 1/2."]], "Can a probability be 1.2?", "no", { label: "Probability bounds", expression: "0 <= P(A) <= 1", variables: [{ symbol: "P(A)", meaning: "probability of event A" }], exactness: "definition" }),
  503: item(503, "Complement Rule", "complement-rule", "Probability and Distributions", "procedure", "The complement rule says the probability that A does not happen is 1 minus the probability that A happens.", "Find P(A), then subtract it from 1.", "An event and its complement together cover the whole sample space without overlap.", "venn_diagram", ["ADD_COMPLEMENT", "Adding P(A) to find the complement.", "Subtract from 1 because the whole probability is 1."], [["Rain", "Not rain is the complement of rain."], ["Pass test", "Fail test is the complement if there are only pass/fail outcomes."], ["Rolling six", "Not six has probability 5/6."]], "If P(A)=0.3, what is P(not A)?", "0.7", { label: "Complement rule", expression: "P(A') = 1 - P(A)", variables: [{ symbol: "A'", meaning: "not A" }, { symbol: "P(A)", meaning: "probability of A" }], exactness: "theorem" }),
  504: item(504, "Addition Rule", "addition-rule", "Probability and Distributions", "procedure", "The addition rule finds the probability that A or B happens.", "Add P(A) and P(B), then subtract P(A and B) if the events overlap.", "The overlap is subtracted so it is not counted twice.", "venn_diagram", ["DOUBLE_OVERLAP", "Adding overlapping events without subtracting the overlap.", "Subtract the intersection once for overlapping events."], [["Cards", "Heart or king overlaps at king of hearts."], ["Students", "Football or music may overlap."], ["Weather", "Cold or rainy days may overlap."]], "For overlapping events, what must be subtracted?", "overlap", { label: "Addition rule", expression: "P(A or B) = P(A) + P(B) - P(A and B)", variables: [{ symbol: "A", meaning: "first event" }, { symbol: "B", meaning: "second event" }], exactness: "theorem" }),
  505: item(505, "Multiplication Rule", "multiplication-rule", "Probability and Distributions", "procedure", "The multiplication rule finds the probability that A and B both happen.", "Multiply P(A) by P(B after A), or multiply separate probabilities when events are independent.", "Sequential chance shrinks because both conditions must be satisfied.", "tree_diagram", ["ALWAYS_INDEPENDENT", "Multiplying as if events are independent when they are not.", "Use conditional probability when the first event changes the second."], [["Two coin tosses", "Heads then heads has probability 1/4."], ["Cards without replacement", "The second probability changes."], ["Choosing shirts", "Independent choices can multiply."]], "For dependent events, use probability after what?", "A", { label: "Multiplication rule", expression: "P(A and B) = P(A)P(B|A)", variables: [{ symbol: "P(B|A)", meaning: "probability of B given A" }], exactness: "theorem" }),
  506: item(506, "Independent Events", "independent-events", "Probability and Distributions", "concept", "Independent events are events where one happening does not change the probability of the other.", "Compare P(B) with P(B given A); if they are equal, the events are independent.", "Independence means information about one event gives no probability change for the other.", "tree_diagram", ["SAME_AS_DIFFERENT", "Thinking independent means the events cannot happen together.", "Independent events can happen together; they just do not affect each other's probabilities."], [["Coin tosses", "First toss does not affect second toss."], ["Die and coin", "Rolling a die does not affect a coin."], ["Replacement draws", "Replacing keeps probabilities the same."]], "Does one fair coin toss affect the next toss?", "no"),
  507: item(507, "Mutually Exclusive Events", "mutually-exclusive-events", "Probability and Distributions", "concept", "Mutually exclusive events cannot happen at the same time in one trial.", "Check whether the two events share any outcomes.", "If there is no shared outcome, their intersection has probability 0.", "venn_diagram", ["CONFUSE_INDEPENDENT", "Confusing mutually exclusive with independent.", "Mutually exclusive means no overlap; independent means no probability effect."], [["Die roll 2 or 5", "These cannot both happen on one roll."], ["Card heart or spade", "One card cannot be both suits."], ["Rain and no rain", "They cannot both happen at the same time."]], "For mutually exclusive events, P(A and B) equals what?", "0", { label: "No overlap", expression: "P(A and B) = 0", variables: [{ symbol: "A and B", meaning: "intersection of the events" }], exactness: "definition" }),
  508: item(508, "Conditional Probability", "conditional-probability", "Probability and Distributions", "concept", "Conditional probability is the chance of one event when another event is already known.", "Restrict the sample space to the known condition, then count favourable outcomes inside it.", "New information can change the set of possible outcomes.", "tree_diagram", ["OLD_DENOMINATOR", "Using the original denominator after a condition is known.", "Use the reduced sample space after the condition."], [["Cards", "Given a card is red, chance of heart is 1/2."], ["Students", "Given a student plays sport, chance of cricket may change."], ["Weather", "Given clouds, chance of rain changes."]], "Conditional probability uses a reduced sample what?", "space", { label: "Conditional probability", expression: "P(A|B) = P(A and B) / P(B)", variables: [{ symbol: "P(A|B)", meaning: "probability of A given B" }, { symbol: "P(B)", meaning: "probability of B" }], restrictions: ["P(B) must be greater than 0."], exactness: "definition" }),
  509: item(509, "Tree Diagrams", "tree-diagrams", "Probability and Distributions", "visual_exploration", "A tree diagram shows probability paths for multi-step experiments.", "Draw branches for each stage, multiply along a path, and add paths that match the event.", "Branches keep sequential outcomes organised.", "tree_diagram", ["ADD_ALONG_BRANCH", "Adding probabilities along one path.", "Multiply along a path; add separate matching paths."], [["Two coin tosses", "The tree shows HH, HT, TH, TT."], ["Bag draws", "Branches show changed probabilities."], ["Quiz guesses", "Correct and wrong paths can be tracked."]], "In a tree diagram, do you add or multiply along one path?", "multiply"),
  510: item(510, "Venn Diagrams", "venn-diagrams", "Probability and Distributions", "visual_exploration", "A Venn diagram shows events as regions inside a sample space.", "Place overlaps first, then fill only-A, only-B, outside, and totals.", "Regions help prevent double-counting event overlaps.", "venn_diagram", ["OVERLAP_TWICE", "Putting the overlap into both only-regions.", "The overlap belongs in the shared middle region."], [["Sports survey", "Students in both sports go in the overlap."], ["Card events", "Kings and hearts overlap at king of hearts."], ["Food choices", "People choosing both items sit in the intersection."]], "Where do outcomes in both A and B go?", "overlap"),
  511: item(511, "Two-Way Tables", "two-way-tables", "Probability and Distributions", "visual_exploration", "A two-way table organises counts by two categories at once.", "Fill joint counts, row totals, column totals, and the grand total.", "The table shows intersections and totals needed for conditional probabilities.", "table", ["TOTAL_AS_CELL", "Confusing a row total with one joint cell.", "Joint cells are inside the table; totals are margins."], [["Class survey", "Rows are gender and columns are sport choice."], ["Medical test", "Rows are test result and columns are true condition."], ["Transport", "Rows are grade and columns are travel mode."]], "A two-way table has row totals and column what?", "totals"),
  512: item(512, "Bayes' Theorem", "bayes-theorem", "Probability and Distributions", "procedure", "Bayes' theorem updates a probability after new evidence is known.", "Multiply likelihood by prior, then divide by the total probability of the evidence.", "It reverses conditional probability in a mathematically valid way.", "tree_diagram", ["BASE_RATE_IGNORED", "Ignoring the base rate before using test evidence.", "Use the prior probability as well as the evidence accuracy."], [["Medical screening", "A rare disease still needs the base rate."], ["Spam filter", "Words update the chance an email is spam."], ["Weather forecast", "New radar evidence updates rain chance."]], "Bayes' theorem must include the prior or base what?", "rate", { label: "Bayes' theorem", expression: "P(A|B) = P(B|A)P(A) / P(B)", variables: [{ symbol: "P(A)", meaning: "prior probability" }, { symbol: "P(B|A)", meaning: "likelihood" }, { symbol: "P(B)", meaning: "evidence probability" }], restrictions: ["P(B) must be greater than 0."], exactness: "theorem" }),
  513: item(513, "Expected Value", "expected-value", "Probability and Distributions", "concept", "Expected value is the long-run average outcome of a random variable.", "Multiply each outcome by its probability, then add the products.", "Over many repeats, the average tends toward the expected value.", "table", ["MOST_LIKELY", "Thinking expected value must be the most likely single outcome.", "Expected value is a long-run average, not always an actual outcome."], [["Game points", "Expected score predicts long-run average points."], ["Insurance", "Expected cost helps price risk."], ["Prize wheel", "Expected value compares fair games."]], "Expected value is a long-run what?", "average", { label: "Expected value", expression: "E(X) = sum xp(x)", variables: [{ symbol: "x", meaning: "outcome value" }, { symbol: "p(x)", meaning: "probability of that outcome" }], exactness: "definition" }),
  514: item(514, "Simulation", "simulation", "Probability and Distributions", "tool", "A probability simulation imitates random trials to estimate chances.", "Choose a random model, run many trials, count outcomes, and compare with theory.", "More trials usually reduce random noise in the estimate.", "probability_simulation", ["FEW_TRIALS_CERTAIN", "Trusting a very small simulation as exact.", "Use many trials and compare with theoretical probability when possible."], [["Coin toss app", "Many tosses estimate heads probability."], ["Traffic model", "Random arrivals estimate waiting time."], ["Game design", "Simulations test possible scores."]], "Do more trials usually reduce random noise?", "yes"),
  515: item(515, "Law of Large Numbers", "law-of-large-numbers", "Probability and Distributions", "concept", "The law of large numbers says sample results tend to get closer to the true probability as trials increase.", "Repeat the same random experiment many times and watch the relative frequency.", "Random ups and downs balance out better over many trials.", "probability_simulation", ["DUE_TO_BALANCE", "Thinking a tail is due just because many heads happened.", "The law describes long-run frequency, not a guarantee for the next trial."], [["Coin tossing", "Heads proportion tends toward 1/2."], ["Dice rolls", "Each face frequency steadies over many rolls."], ["Quality checks", "Large samples estimate defect rates better."]], "The law of large numbers is about long-run what?", "frequency"),
  516: item(516, "Distribution Calculator", "distribution-calculator", "Probability and Distributions", "tool", "A distribution calculator computes probabilities from a chosen probability model.", "Choose the distribution, enter valid parameters, and select point, interval, or tail probability.", "Different distributions have different parameter rules and shapes.", "distribution_plot", ["WRONG_MODEL", "Using a calculator distribution that does not match the situation.", "Match the random variable and assumptions before entering parameters."], [["Binomial calculator", "Find chance of 3 successes in 10 trials."], ["Normal calculator", "Find probability below a z-score."], ["Poisson calculator", "Estimate counts in a fixed interval."]], "What must you choose before entering parameters?", "distribution"),
  517: item(517, "Probability Plot", "probability-plot", "Probability and Distributions", "visual_exploration", "A probability plot compares data with a theoretical distribution.", "Order the data, plot expected positions, and check whether points follow the reference pattern.", "Close alignment suggests the chosen distribution may be reasonable.", "distribution_plot", ["PERFECT_REQUIRED", "Thinking points must lie perfectly on the line.", "Real sample data has random variation, so look for overall pattern."], [["Normal check", "A near-line plot supports a normal model."], ["Quality data", "The plot checks distribution assumptions."], ["Exam scores", "A plot can reveal skew or outliers."]], "A probability plot checks data against a theoretical what?", "distribution"),
  518: item(518, "Cumulative Distribution", "cumulative-distribution", "Probability and Distributions", "concept", "A cumulative distribution gives the probability that a random variable is at or below a value.", "Add probabilities up to the chosen value or read the CDF curve.", "Cumulative probability builds from left to right until the total reaches 1.", "distribution_plot", ["EXACT_NOT_CUMULATIVE", "Confusing P(X = x) with P(X <= x).", "Cumulative probability includes all values up to x."], [["Test score", "Chance score is at most 70."], ["Delivery time", "Chance parcel arrives within 3 days."], ["Dice sum", "Chance sum is 6 or less."]], "CDF means probability X is less than or equal to what?", "x", { label: "Cumulative distribution", expression: "F(x) = P(X <= x)", variables: [{ symbol: "X", meaning: "random variable" }, { symbol: "x", meaning: "chosen value" }], exactness: "definition" }),
  519: item(519, "Interval / Tail Probability", "interval-tail-probability", "Probability and Distributions", "procedure", "Interval probability is chance inside a range, and tail probability is chance beyond a cutoff.", "Choose lower and upper bounds, then subtract cumulative probabilities or read the shaded area.", "Areas under a probability distribution represent probabilities.", "distribution_plot", ["WRONG_TAIL", "Using the left tail when the question asks for the right tail.", "Check whether the question says below, above, or between."], [["Exam marks", "Chance score is between 60 and 80."], ["Waiting time", "Chance wait is more than 10 minutes."], ["Machine size", "Chance part is below the limit."]], "Tail questions often ask above or below a what?", "cutoff"),
  520: item(520, "Inverse Probability", "inverse-probability", "Probability and Distributions", "procedure", "Inverse probability finds the value that matches a given cumulative probability.", "Choose the target probability, use the inverse distribution, and check the direction.", "It reverses a cumulative distribution calculation.", "distribution_plot", ["PROB_AS_VALUE", "Confusing the target probability with the output value.", "The input is probability; the output is the matching cutoff value."], [["Percentile", "Find the score at the 90th percentile."], ["Manufacturing", "Find the size below which 95 percent fall."], ["Delivery", "Find the time met by 80 percent of deliveries."]], "Inverse probability returns a cutoff what?", "value"),
  521: item(521, "Bernoulli Distribution", "bernoulli-distribution", "Probability and Distributions", "concept", "A Bernoulli distribution models one trial with two outcomes: success or failure.", "Choose success probability p, assign 1 to success and 0 to failure.", "One yes/no trial is the simplest probability distribution.", "distribution_plot", ["MANY_TRIALS", "Using Bernoulli for many trials at once.", "Bernoulli models one trial; binomial models a fixed number of repeated trials."], [["Coin heads", "One toss can be success or failure."], ["Free throw", "One shot is made or missed."], ["Quality check", "One item is defective or not."]], "A Bernoulli distribution has how many trials?", "1", { label: "Bernoulli probabilities", expression: "P(X=1)=p, P(X=0)=1-p", variables: [{ symbol: "p", meaning: "success probability" }], restrictions: ["0 <= p <= 1"], exactness: "definition" }),
  522: item(522, "Binomial Distribution", "binomial-distribution", "Probability and Distributions", "concept", "A binomial distribution models the number of successes in a fixed number of independent Bernoulli trials.", "Check fixed n, same p, independent trials, then count successes.", "The binomial model combines repeated yes/no trials with the same success probability.", "distribution_plot", ["DEPENDENT_TRIALS", "Using binomial when trials are not independent or p changes.", "Check independence and constant success probability."], [["Ten coin tosses", "Count how many heads occur."], ["Free throws", "Count made shots if chance stays the same."], ["Factory checks", "Count defective items in a fixed sample."]], "Binomial trials must be independent and have the same what?", "p", { label: "Binomial probability", expression: "P(X=k)=C(n,k)p^k(1-p)^(n-k)", variables: [{ symbol: "n", meaning: "number of trials" }, { symbol: "k", meaning: "number of successes" }, { symbol: "p", meaning: "success probability" }], restrictions: ["n is a non-negative integer; 0 <= p <= 1; 0 <= k <= n."], exactness: "definition" }),
};

export function regressionProbabilitySeed(id: number) {
  return data[id];
}

export type RegressionProbabilitySeed = Seed;

export function regressionProbabilityLesson(seed: Seed): StrengthenedLesson {
  const code = seed.misconception[0];
  return {
    id: seed.id,
    title: seed.title,
    route: `/lessons/data-and-probability/${seed.id}-${seed.slug}`,
    category: "Data and Probability",
    topic: seed.topic,
    lessonType: seed.lessonType,
    learningObjectives: [`Define ${seed.title} accurately.`, seed.action, `Avoid this mistake: ${seed.misconception[1]}`],
    prerequisites: ["Fractions and decimals", "Reading tables and graphs", "Basic probability or data vocabulary"],
    keyVocabulary: [{ term: seed.title, meaning: seed.definition }, { term: seed.topic.includes("Probability") ? "Outcome" : "Model", meaning: seed.topic.includes("Probability") ? "One possible result of a random experiment." : "A mathematical rule used to describe a data pattern." }],
    introduction: `${seed.title} is a data and probability idea. It helps us make fair predictions from data or chance. We use it in games, weather, science, money, and daily decisions.`,
    basicIdea: `${seed.definition} The basic idea is to match the method to the question before calculating. ${seed.reason} A common mistake is ${seed.misconception[1]}`,
    howItWorks: `${seed.action} Then check the answer against labels, assumptions, and the original context.`,
    whyItWorks: seed.topic.includes("Probability") ? "Probability works by comparing favourable outcomes with possible outcomes, or by using a distribution rule that matches the random process." : "Regression works by comparing observed data with predicted values and choosing a model whose errors are small and pattern-free.",
    definitions: [{ id: `${seed.slug}-definition`, statement: seed.definition }],
    facts: [{ id: `${seed.slug}-fact`, statement: seed.reason }],
    formulas: seed.formula ? [{ id: `${seed.slug}-formula`, ...seed.formula }] : [],
    conditionsAndRestrictions: ["Check assumptions before using a formula.", "Keep probabilities between 0 and 1.", "Do not treat a model prediction as a measured fact."],
    representations: [{ id: `${seed.slug}-representation`, type: seed.representation, learningPurpose: `Show the structure of ${seed.title}.` }],
    workedExamples: [{ id: `${seed.slug}-worked-1`, prompt: seed.challenge.prompt, steps: ["Identify the question type.", seed.action, "Check the answer against the context."], answer: seed.challenge.expected }],
    realLifeExamples: seed.examples.map(([context, connection], index) => ({ id: `${seed.slug}-real-${index + 1}`, context, connection })),
    misconceptions: [{ code, mistake: seed.misconception[1], correction: seed.misconception[2] }],
    interaction: { id: `${seed.slug}-interaction`, learningPurpose: `Explore ${seed.title} with linked graphs, tables, or seeded probability simulation.`, parameters: [{ id: "parameter", label: "Parameter", validRange: [1, 20] }], initialState: `Start with a small example for ${seed.title}.`, dynamicFeedback: "Changing a value updates the graph, probability, residual, or distribution display.", successCriteria: ["Use the correct rule", "Read the linked representation", "Explain the common mistake"], accessibilityAlternative: "Provide the same values, formulas, and interpretation as text." },
    guidedExploration: [{ id: "predict", prompt: "Predict how the output changes when the parameter changes." }, { id: "test", prompt: "Change one value and read the new output." }, { id: "explain", prompt: "Explain the result using the lesson definition." }],
    practice: [practice(`${seed.slug}-recognition`, `What is ${seed.title}?`, seed.definition, code, "recognition"), practice(`${seed.slug}-direct`, seed.challenge.prompt, seed.challenge.expected, code, "direct"), practice(`${seed.slug}-multi`, `How do you use ${seed.title}?`, seed.action, code, "multi_step"), practice(`${seed.slug}-error`, `What is wrong with this mistake: ${seed.misconception[1]}`, seed.misconception[2], code, "error_diagnosis"), practice(`${seed.slug}-transfer`, `Give one daily use of ${seed.title}.`, seed.examples[0][0], code, "transfer")],
    challenge: { id: `${seed.slug}-challenge`, prompt: seed.challenge.prompt, successCriteria: ["Uses the correct definition or formula", "Checks assumptions", "Avoids the named mistake"], hints: [seed.challenge.hint, seed.misconception[2]] },
    exitCheck: [{ id: `${seed.slug}-exit`, prompt: `State one rule for ${seed.title}.`, answer: seed.misconception[2], criterion: "Answer names a correct rule or assumption." }],
    accessibilityNotes: ["Announce chart values and probability values.", "Do not rely only on colour to show success or failure."],
    expertReviewRequired: false,
  };
}

export function regressionProbabilityChallenge(seed: Seed) {
  return seed.challenge;
}

function item(id: number, title: string, slug: string, topic: Seed["topic"], lessonType: Seed["lessonType"], definition: string, action: string, reason: string, representation: Seed["representation"], misconception: Seed["misconception"], examples: Seed["examples"], prompt: string, expected: string, formula?: FormulaSeed): Seed {
  return { id, title, slug, topic, lessonType, definition, action, reason, representation, misconception, examples, formula, challenge: { prompt, expected, hint: `Use the ${title} rule and check assumptions.`, kind: Number.isFinite(Number(expected)) ? "numeric" : "keywords", factoryId: `regressionProbability.${slug}` } };
}

function practice(id: string, prompt: string, answer: string, misconceptionTag: string, difficulty: StrengthenedLesson["practice"][number]["difficulty"]): StrengthenedLesson["practice"][number] {
  return { id, prompt, answer, hints: ["Read the question carefully.", "Check the assumptions.", "Use the matching rule."], workedSolution: ["Identify the situation.", "Apply the correct rule.", "Check whether the answer makes sense."], misconceptionTag, difficulty, parameterConstraints: ["Use valid probabilities, data values, and model parameters."] };
}
