import {
  Atom,
  BarChart3,
  Binary,
  BookOpen,
  BrainCircuit,
  Calculator,
  ChartSpline,
  CircleHelp,
  Cone,
  Cuboid,
  FileText,
  FunctionSquare,
  GitFork,
  Grid3X3,
  Hash,
  Home,
  Info,
  Leaf,
  LineChart,
  Network,
  Presentation,
  Shapes,
  Sigma,
  Sparkles,
  Trophy,
  Workflow,
  Waves,
  Wrench,
} from "lucide-react";

export const iconMap = {
  Atom,
  BarChart3,
  Binary,
  BookOpen,
  BrainCircuit,
  Calculator,
  ChartSpline,
  CircleHelp,
  Cone,
  Cuboid,
  FileText,
  FunctionSquare,
  GitFork,
  Grid3X3,
  Hash,
  Home,
  Info,
  Leaf,
  LineChart,
  Network,
  Presentation,
  Shapes,
  Sigma,
  Sparkles,
  Trophy,
  Workflow,
  Waves,
  Wrench,
};

export type NavItem = {
  title: string;
  route: string;
  icon: keyof typeof iconMap;
  isExternal?: boolean;
  searchTerms?: string[];
  children?: NavItem[];
};

export type NavSection = {
  title: string;
  icon: keyof typeof iconMap;
  items: NavItem[];
};

export const navSections: NavSection[] = [
  {
    title: "Home",
    icon: "Home",
    items: [
      { title: "Math Workspace", route: "/workspace", icon: "Calculator" },
      { title: "Graph & Algebra", route: "/workspace/graph", icon: "FunctionSquare" },
      { title: "Geometry Constructor", route: "/workspace/geometry", icon: "Shapes" },
      { title: "3D Calculator", route: "/workspace/3d", icon: "Cuboid" },
      { title: "CAS, Tables & Data", route: "/workspace/data", icon: "LineChart" },
      { title: "Teacher Studio", route: "/workspace/teach", icon: "Presentation" },
      { title: "Dashboard", route: "/", icon: "Home" },
      { title: "Syllabus", route: "/syllabus", icon: "BookOpen" },
      { title: "Formulas", route: "/formulas", icon: "Sigma" },
      {
        title: "Maths Visual Dictionary",
        route: "/visual-dictionary",
        icon: "BookOpen",
        searchTerms: ["math dictionary", "maths dictionary", "visual dictionary", "math words", "arc tangent sec tan glossary"],
      },
      { title: "Visual Showcase", route: "/visual-showcase", icon: "Sparkles" },
      {
        title: "Magic Maths",
        route: "/magic-maths",
        icon: "Sparkles",
        searchTerms: ["magic math", "magic maths", "magic square", "number tricks", "nature math", "universe math", "patterns"],
        children: [
          { title: "Magic Square Lab", route: "/magic-maths", icon: "Grid3X3", searchTerms: ["lo shu", "magic constant", "odd magic square"] },
          { title: "Magic Math Concepts", route: "/magic-maths", icon: "Sparkles", searchTerms: ["digit roots", "kaprekar", "calendar math", "binary tricks"] },
          { title: "Coupling Universe and Maths", route: "/magic-maths", icon: "Atom", searchTerms: ["orbital resonance", "gravity", "waves", "crystals", "spectra"] },
          { title: "Nature and Maths", route: "/magic-maths", icon: "Leaf", searchTerms: ["fibonacci", "honeycomb", "fractals", "spiral", "reaction diffusion"] },
        ],
      },
      {
        title: "Visual Proofs",
        route: "/visual-proofs",
        icon: "Sparkles",
        searchTerms: ["proof", "visual proof", "circle area", "geometry proof", "mathematics you can see"],
        children: [
          { title: "All Visual Proofs", route: "/visual-proofs", icon: "Sparkles" },
          { title: "Geometry Proofs", route: "/visual-proofs/geometry", icon: "Shapes" },
          { title: "Algebraic Identities", route: "/visual-proofs/algebraic-identities", icon: "Calculator" },
          { title: "Trigonometry Proofs", route: "/visual-proofs/trigonometry", icon: "Waves" },
          { title: "Coordinate Geometry Proofs", route: "/visual-proofs/coordinate-geometry", icon: "Shapes" },
          { title: "Calculus Proofs", route: "/visual-proofs/calculus", icon: "Sigma" },
          { title: "Number Theory Proofs", route: "/visual-proofs/number-theory", icon: "Hash" },
          { title: "Sequences and Series Proofs", route: "/visual-proofs/sequences-and-series", icon: "ChartSpline" },
          { title: "Probability Proofs", route: "/visual-proofs/probability", icon: "CircleHelp" },
          { title: "Statistics Proofs", route: "/visual-proofs/statistics", icon: "BarChart3" },
          { title: "Matrices and Linear Algebra Proofs", route: "/visual-proofs/matrices-linear-algebra", icon: "Grid3X3" },
          { title: "Vectors Proofs", route: "/visual-proofs/vectors", icon: "Workflow" },
          { title: "Complex Number Proofs", route: "/visual-proofs/complex-numbers", icon: "Atom" },
          { title: "Mensuration Proofs", route: "/visual-proofs/mensuration", icon: "Shapes" },
          { title: "Conic Section Proofs", route: "/visual-proofs/conic-sections", icon: "Cone" },
          { title: "Inequalities Proofs", route: "/visual-proofs/inequalities", icon: "Sigma" },
          { title: "Logarithms and Exponents Proofs", route: "/visual-proofs/logarithms-exponents", icon: "FunctionSquare" },
          { title: "Transformations and Symmetry Proofs", route: "/visual-proofs/transformations-symmetry", icon: "Workflow" },
          { title: "Engineering Math Proofs", route: "/visual-proofs/engineering-mathematics", icon: "Sigma" },
        ],
      },
      { title: "Learning Hub", route: "/learn", icon: "BookOpen" },
    ],
  },
  {
    title: "Math Topics",
    icon: "Sigma",
    items: [
      {
        title: "Algebra",
        route: "/algebra",
        icon: "Calculator",
        children: [
          { title: "Overview", route: "/algebra", icon: "Calculator" },
          {
            title: "Formula Visuals",
            route: "/algebra",
            icon: "Calculator",
            children: [
              { title: "Linear Formulas", route: "/algebra", icon: "Calculator" },
              { title: "Quadratic Formulas", route: "/algebra", icon: "Calculator" },
              { title: "Identities", route: "/ncert/class-8-algebraic-identities", icon: "Calculator" },
              { title: "Polynomials", route: "/ncert/class-10-polynomials", icon: "Calculator" },
            ],
          },
          { title: "Algebraic Structures", route: "/algebraic-structures", icon: "GitFork" },
        ],
      },
      {
        title: "Number Systems",
        route: "/number-systems",
        icon: "Hash",
        searchTerms: [
          "number theory",
          "natural numbers",
          "whole numbers",
          "integers",
          "real numbers",
          "prime numbers",
          "factors",
          "multiples",
          "common factors",
          "common multiples",
          "divisibility",
          "hcf",
          "highest common factor",
          "gcd",
          "greatest common divisor",
          "lcm",
          "least common multiple",
          "euclid",
          "euclidean algorithm",
          "prime factorization",
          "factor tree",
        ],
        children: [
          {
            title: "Overview",
            route: "/number-systems",
            icon: "Hash",
            searchTerms: [
              "number theory",
              "factors",
              "multiples",
              "hcf",
              "gcd",
              "lcm",
              "prime factorization",
              "divisibility",
            ],
          },
          {
            title: "Rational Numbers",
            route: "/number-systems",
            icon: "Hash",
            searchTerms: [
              "fractions",
              "p by q",
              "p/q",
              "terminating decimals",
              "repeating decimals",
              "equivalent fractions",
              "negative fractions",
              "rational properties",
            ],
            children: [
              {
                title: "Class 7 Rational Lab",
                route: "/ncert/class-7-rational-numbers",
                icon: "Hash",
                searchTerms: ["fractions", "integers on number line", "rational numbers", "class 7"],
              },
              {
                title: "Class 8 Rational Properties",
                route: "/ncert/class-8-rational-numbers",
                icon: "Hash",
                searchTerms: ["rational properties", "closure", "commutative", "associative", "distributive", "class 8"],
              },
            ],
          },
          {
            title: "Irrational & Real",
            route: "/number-systems",
            icon: "Hash",
            searchTerms: [
              "irrational numbers",
              "real numbers",
              "surds",
              "roots",
              "square root",
              "decimal expansion",
              "fundamental theorem of arithmetic",
              "hcf",
              "gcd",
              "lcm",
              "euclid",
              "prime factorization",
            ],
            children: [
              {
                title: "Class 9 Number Systems",
                route: "/ncert/class-9-number-systems",
                icon: "Hash",
                searchTerms: ["irrational numbers", "real numbers", "decimal expansion", "class 9"],
              },
              {
                title: "Class 10 Real Numbers",
                route: "/ncert/class-10-real-numbers",
                icon: "Hash",
                searchTerms: [
                  "class 10",
                  "real numbers",
                  "hcf",
                  "highest common factor",
                  "gcd",
                  "greatest common divisor",
                  "lcm",
                  "least common multiple",
                  "euclid",
                  "euclidean algorithm",
                  "euclid division lemma",
                  "division lemma",
                  "prime factorization",
                  "prime factors",
                  "factor tree",
                  "common factors",
                  "common multiples",
                  "fundamental theorem of arithmetic",
                  "number theory",
                ],
              },
            ],
          },
        ],
      },
      {
        title: "Geometry",
        route: "/geometry",
        icon: "Shapes",
        children: [
          { title: "Geometry Universe", route: "/geometry", icon: "Shapes" },
          { title: "2D/3D Shapes", route: "/shapes", icon: "Cuboid" },
          { title: "Coordinate Geometry", route: "/geometry/coordinate-geometry", icon: "Shapes" },
        ],
      },
      {
        title: "Trigonometry",
        route: "/trigonometry",
        icon: "Waves",
        children: [
          { title: "Overview", route: "/trigonometry", icon: "Waves" },
          {
            title: "Foundations",
            route: "/trigonometry",
            icon: "Waves",
            children: [
              { title: "All Trig Functions", route: "/trigonometry/trigonometric-functions", icon: "Waves" },
              { title: "Unit Circle", route: "/trigonometry/unit-circle", icon: "Waves" },
              { title: "Right Triangle Ratios", route: "/trigonometry/right-triangle-ratios", icon: "Waves" },
              { title: "Degrees & Radians", route: "/trigonometry/degree-radian", icon: "Waves" },
            ],
          },
          {
            title: "JEE",
            route: "/trigonometry",
            icon: "Waves",
            children: [
              { title: "Half Angle", route: "/trigonometry/half-angle", icon: "Waves" },
              { title: "Product to Sum", route: "/trigonometry/product-to-sum", icon: "Waves" },
              { title: "General Solutions", route: "/trigonometry/general-solutions", icon: "Waves" },
              { title: "Trig Inequalities", route: "/trigonometry/trig-inequalities", icon: "Waves" },
            ],
          },
          {
            title: "Degree & PG",
            route: "/trigonometry",
            icon: "Waves",
            children: [
              { title: "Fourier Trig Series", route: "/trigonometry/fourier-trig-series", icon: "Waves" },
              { title: "Orthogonality", route: "/trigonometry/orthogonality", icon: "Waves" },
              { title: "Spherical Trig", route: "/trigonometry/spherical-trigonometry", icon: "Waves" },
              { title: "Hyperbolic Functions", route: "/trigonometry/hyperbolic-functions", icon: "Waves" },
            ],
          },
        ],
      },
      {
        title: "Calculus",
        route: "/calculus",
        icon: "Sigma",
        children: [
          { title: "Overview + Formula Atlas", route: "/calculus", icon: "Sigma" },
          {
            title: "Core Calculus",
            route: "/calculus",
            icon: "Sigma",
            children: [
              { title: "Limits", route: "/math/limits-continuity", icon: "Sigma" },
              { title: "Derivatives", route: "/math/derivatives", icon: "Sigma" },
              { title: "Integration", route: "/math/integration", icon: "Sigma" },
              { title: "Slope Fields", route: "/math/slope-fields", icon: "Sigma" },
            ],
          },
          {
            title: "Degree & PG",
            route: "/calculus",
            icon: "Sigma",
            children: [
              { title: "Fourier Series", route: "/math/fourier-series", icon: "Sigma" },
              { title: "3D Surface Plotter", route: "/surface-plotter", icon: "Cuboid" },
            ],
          },
        ],
      },
      { title: "Engineering Mathematics", route: "/engineering-math", icon: "Sigma" },
      {
        title: "Magic Maths",
        route: "/magic-maths",
        icon: "Sparkles",
        searchTerms: ["magic square", "math in nature", "universe mathematics", "number patterns", "mathematical magic"],
        children: [
          { title: "Magic Square Lab", route: "/magic-maths", icon: "Grid3X3" },
          { title: "Number Magic Concepts", route: "/magic-maths", icon: "Sparkles" },
          { title: "Universe and Maths", route: "/magic-maths", icon: "Atom" },
          { title: "Nature and Maths", route: "/magic-maths", icon: "Leaf" },
        ],
      },
      { title: "Complex Numbers", route: "/complex-numbers", icon: "Atom" },
      {
        title: "Combinatorics",
        route: "/combinatorics",
        icon: "Grid3X3",
        searchTerms: ["counting", "permutation", "combination", "npr", "ncr", "pascal", "binomial", "inclusion exclusion"],
        children: [
          { title: "Combinatorics Lab", route: "/combinatorics", icon: "Grid3X3" },
          { title: "Permutations and Combinations", route: "/math/permutations-combinations", icon: "Grid3X3" },
          { title: "Counting Trees", route: "/combinatorics", icon: "Workflow" },
          { title: "Pascal and Binomial", route: "/combinatorics", icon: "Sigma" },
          { title: "Inclusion-Exclusion", route: "/combinatorics", icon: "Network" },
        ],
      },
      {
        title: "Set Theory and Relations",
        route: "/set-theory",
        icon: "Network",
        searchTerms: ["set theory", "sets", "venn", "ven", "venn diagram", "union", "intersection", "subset", "relations", "functions", "hasse", "partial order", "cartesian product", "power set"],
        children: [
          { title: "Set Theory Lab", route: "/set-theory", icon: "Network" },
          { title: "Interactive Venn Diagrams", route: "/set-theory", icon: "Network", searchTerms: ["venn", "ven", "drag circles", "union", "intersection", "subset", "overlap", "disjoint"] },
          { title: "Set Builder and Notation", route: "/set-theory", icon: "BookOpen", searchTerms: ["roster", "set notation", "universe", "set a", "set b"] },
          { title: "Cartesian Products", route: "/set-theory", icon: "Grid3X3", searchTerms: ["ordered pairs", "a cross b", "cartesian product"] },
          { title: "Power Sets", route: "/set-theory", icon: "Sparkles", searchTerms: ["subsets", "power set"] },
          { title: "Relations and Matrices", route: "/set-theory", icon: "Grid3X3", searchTerms: ["relation matrix", "reflexive", "symmetric", "transitive", "antisymmetric"] },
          { title: "Hasse Diagram and Partial Orders", route: "/set-theory", icon: "GitFork", searchTerms: ["poset", "partial order", "lattice", "hasse"] },
          { title: "Functions Mapping Studio", route: "/set-theory", icon: "FunctionSquare", searchTerms: ["injective", "surjective", "bijective", "mapping"] },
          { title: "Legacy Venn Builder", route: "/syllabus-lab/venn-diagram-builder", icon: "Network", searchTerms: ["old venn", "syllabus venn"] },
        ],
      },
      {
        title: "Mathematical Logic",
        route: "/mathematical-logic",
        icon: "Binary",
        searchTerms: ["logic", "truth table", "proposition", "predicate", "cnf", "dnf", "inference", "boolean"],
        children: [
          { title: "Logic Lab", route: "/mathematical-logic", icon: "Binary" },
          { title: "Truth Tables", route: "/truth-table", icon: "Binary" },
          { title: "Statements and Connectives", route: "/mathematical-logic", icon: "Binary" },
          { title: "CNF and DNF", route: "/mathematical-logic", icon: "Workflow" },
          { title: "Predicate Models", route: "/mathematical-logic", icon: "Network" },
        ],
      },
      {
        title: "Vectors",
        route: "/linear-algebra",
        icon: "Grid3X3",
        children: [
          { title: "Vector Visualizer", route: "/linear-algebra", icon: "Grid3X3" },
          { title: "3D Vectors", route: "/linear-algebra", icon: "Cuboid" },
          { title: "Vector Algebra", route: "/linear-algebra", icon: "Sigma" },
          { title: "Dot and Cross Product", route: "/linear-algebra", icon: "Workflow" },
          { title: "Vector Projections", route: "/linear-algebra", icon: "ChartSpline" },
        ],
      },
      {
        title: "Linear Algebra",
        route: "/linear-algebra",
        icon: "Grid3X3",
        children: [
          { title: "Linear Algebra Lab", route: "/linear-algebra", icon: "Grid3X3" },
          { title: "Matrix Transformations", route: "/math/matrix-transformations", icon: "Workflow" },
          { title: "Eigenvectors Visualizer", route: "/math/eigenvectors", icon: "Sparkles" },
          { title: "Linear Algebra Math Lab", route: "/math-lab/linear-algebra", icon: "Grid3X3" },
        ],
      },
      {
        title: "Matrices",
        route: "/matrices",
        icon: "Grid3X3",
        searchTerms: ["matrix", "matrices", "determinant", "inverse", "rank", "row operations", "eigenvalues", "eigenvectors", "systems"],
        children: [
          { title: "Matrix Operations", route: "/matrices", icon: "Grid3X3" },
          { title: "Matrix Basics", route: "/matrices/basics", icon: "BookOpen" },
          { title: "Matrix Addition", route: "/matrices/addition", icon: "Grid3X3" },
          { title: "Matrix Multiplication", route: "/matrices/multiplication", icon: "Workflow" },
          { title: "Determinant", route: "/matrices/determinant", icon: "Sigma" },
          { title: "Inverse Matrix", route: "/matrices/inverse", icon: "Workflow" },
          { title: "Rank and Row Operations", route: "/matrices/rank", icon: "Grid3X3" },
          { title: "Linear Equations", route: "/matrices/linear-equations", icon: "Calculator" },
          { title: "Eigenvalues and Eigenvectors", route: "/matrices/eigenvalues-eigenvectors", icon: "Sparkles" },
          { title: "Matrix Transformations", route: "/matrices/transformations", icon: "Workflow" },
          { title: "Matrix Sandbox", route: "/matrix-sandbox", icon: "Grid3X3" },
        ],
      },
      {
        title: "Statistics and Probability",
        route: "/probability-statistics",
        icon: "BarChart3",
        searchTerms: ["statistics", "probability", "mean", "median", "mode", "variance", "standard deviation", "regression", "distribution"],
        children: [
          { title: "Statistics and Probability", route: "/probability-statistics", icon: "BarChart3" },
          { title: "Probability Math Lab", route: "/math-lab/probability", icon: "CircleHelp" },
          { title: "Data Workspace", route: "/workspace/data", icon: "LineChart" },
        ],
      },
      {
        title: "Graph Theory",
        route: "/graph-theory",
        icon: "Network",
        searchTerms: ["graph theory", "bfs", "dfs", "dijkstra", "mst", "tree", "euler", "hamilton", "coloring", "planarity"],
        children: [
          { title: "Graph Theory Lab", route: "/graph-theory", icon: "Network" },
          { title: "Graph Comparison", route: "/graph-comparison", icon: "Waves" },
          { title: "Concept Graph", route: "/concept-graph", icon: "Grid3X3" },
          { title: "Discrete World Graphs", route: "/discrete-world", icon: "Workflow" },
        ],
      },
      {
        title: "Discrete World",
        route: "/discrete-world",
        icon: "Workflow",
        searchTerms: ["discrete math", "automata", "dfa", "nfa", "grammar", "turing machine", "complexity", "logic", "sets", "graphs"],
        children: [
          { title: "Discrete Math and Automata World", route: "/discrete-world", icon: "Workflow" },
          { title: "Automata Lab", route: "/discrete-world", icon: "Workflow", searchTerms: ["dfa", "nfa", "automata"] },
          { title: "Grammar Lab", route: "/discrete-world", icon: "BookOpen", searchTerms: ["grammar", "language", "formal language"] },
          { title: "Turing Machine Lab", route: "/discrete-world", icon: "BrainCircuit", searchTerms: ["turing", "machine", "computation"] },
          { title: "Complexity Lab", route: "/discrete-world", icon: "ChartSpline", searchTerms: ["big o", "complexity", "algorithm"] },
        ],
      },
    ],
  },
  {
    title: "Tools",
    icon: "Wrench",
    items: [
      {
        title: "Math Lab",
        route: "/math-lab",
        icon: "BrainCircuit",
        children: [
          { title: "Graphing Calculator", route: "/math-lab/graphing-calculator", icon: "ChartSpline" },
          { title: "Function Explorer", route: "/math-lab/function-explorer", icon: "Waves" },
          { title: "Trigonometry Lab", route: "/math-lab/trigonometry", icon: "Waves" },
          { title: "Conic Solver", route: "/math-lab/conics", icon: "Cone" },
          { title: "3D Graphing Lab", route: "/math-lab/3d-graphing", icon: "Cuboid" },
          { title: "CAS / Algebra Solver", route: "/problem-solver", icon: "Sigma" },
          { title: "Probability", route: "/math-lab/probability", icon: "CircleHelp" },
          { title: "Smart Query Router", route: "/math-lab/query", icon: "BrainCircuit" },
          { title: "Linear Algebra Lab", route: "/math-lab/linear-algebra", icon: "Grid3X3" },
        ],
      },
      {
        title: "Interactive Visualizers",
        route: "/visual-showcase",
        icon: "Sparkles",
        searchTerms: ["visualizer", "animation", "fourier", "polar", "parametric", "surface", "eigenvector", "matrix transformation"],
        children: [
          { title: "Visual Showcase", route: "/visual-showcase", icon: "Sparkles" },
          { title: "Fourier Animator", route: "/fourier-animator", icon: "Waves", searchTerms: ["fourier", "harmonics", "tails", "wave"] },
          { title: "Fourier Series Visualizer", route: "/math/fourier-series", icon: "Waves" },
          { title: "Parametric Curves", route: "/parametric-curves", icon: "Waves" },
          { title: "Polar Visualizer", route: "/polar-visualizer", icon: "ChartSpline" },
          { title: "3D Surface Plotter", route: "/surface-plotter", icon: "Cuboid" },
          { title: "Matrix Transformations", route: "/math/matrix-transformations", icon: "Workflow" },
          { title: "Eigenvectors", route: "/math/eigenvectors", icon: "Sparkles" },
          { title: "Functions and Graphs", route: "/math/functions-graphs", icon: "FunctionSquare" },
          { title: "Limits and Continuity", route: "/math/limits-continuity", icon: "Sigma" },
          { title: "Derivative Tangents", route: "/math/derivatives", icon: "Sigma" },
          { title: "Integration Area", route: "/math/integration", icon: "Sigma" },
          { title: "Slope Fields", route: "/math/slope-fields", icon: "ChartSpline" },
        ],
      },
      { title: "Formulas", route: "/formulas", icon: "Sigma" },
      { title: "Scientific Calculator", route: "/calculator", icon: "Calculator" },
      { title: "Problem Solver", route: "/problem-solver", icon: "Sigma" },
      { title: "Unit Converter", route: "/unit-converter", icon: "Calculator" },
      { title: "Truth Tables", route: "/truth-table", icon: "Binary" },
      { title: "Statistics", route: "/probability-statistics", icon: "BarChart3" },
    ],
  },
  {
    title: "Practice",
    icon: "BookOpen",
    items: [
      { title: "Olympyard", route: "/olympyard", icon: "Trophy", searchTerms: ["olympiad", "contest", "topic map", "mock test", "visual practice"] },
      { title: "Quiz", route: "/quiz", icon: "CircleHelp" },
      { title: "Daily Challenge", route: "/daily-challenge", icon: "CircleHelp" },
      { title: "Spaced Repetition", route: "/spaced-repetition", icon: "CircleHelp" },
      { title: "Worked Examples", route: "/worked-examples", icon: "BookOpen" },
      { title: "Concept Graph", route: "/concept-graph", icon: "Grid3X3" },
      { title: "AI Applications", route: "/ai-applications", icon: "BrainCircuit" },
      { title: "Documentation", route: "/documentation", icon: "FileText" },
      { title: "About", route: "/about", icon: "Info" },
    ],
  },
];

function flattenNavItems(items: NavItem[]): NavItem[] {
  return items.flatMap((item) => [item, ...flattenNavItems(item.children ?? [])]);
}

export const navItems = navSections.flatMap((section) => flattenNavItems(section.items).map((item) => ({
  ...item,
  icon: iconMap[item.icon],
})));

export const legacyNavItems = [
  { title: "Home", route: "/", icon: Home },
  { title: "Math Lab", route: "/math-lab", icon: BrainCircuit },
  { title: "Visual Showcase", route: "/visual-showcase", icon: Sparkles },
  { title: "Magic Maths", route: "/magic-maths", icon: Sparkles },
  { title: "Visual Proofs", route: "/visual-proofs", icon: Sparkles },
  { title: "Math Workspace", route: "/workspace", icon: Calculator },
  { title: "Algebra", route: "/algebra", icon: Calculator },
  { title: "Algebraic Structures", route: "/algebraic-structures", icon: GitFork },
  { title: "Geometry", route: "/geometry", icon: Shapes },
  { title: "Number Systems", route: "/number-systems", icon: Hash },
  { title: "2D/3D Shapes", route: "/shapes", icon: Cuboid },
  { title: "Trigonometry", route: "/trigonometry", icon: Waves },
  { title: "Calculus", route: "/calculus", icon: Sigma },
  { title: "Engineering Mathematics", route: "/engineering-math", icon: Sigma },
  { title: "Combinatorics", route: "/combinatorics", icon: Grid3X3 },
  { title: "Complex Numbers", route: "/complex-numbers", icon: Atom },
  { title: "Set Theory", route: "/set-theory", icon: Network },
  { title: "Mathematical Logic", route: "/mathematical-logic", icon: Binary },
  { title: "Statistics", route: "/probability-statistics", icon: BarChart3 },
  { title: "Probability Lab", route: "/probability-statistics", icon: BarChart3 },
  { title: "Vectors", route: "/linear-algebra", icon: Grid3X3 },
  { title: "Vector Visualizer", route: "/linear-algebra", icon: Grid3X3 },
  { title: "3D Vectors", route: "/linear-algebra", icon: Cuboid },
  { title: "Vector Algebra", route: "/linear-algebra", icon: Sigma },
  { title: "Linear Algebra", route: "/linear-algebra", icon: Grid3X3 },
  { title: "Matrix Operations", route: "/matrices", icon: Grid3X3 },
  { title: "Matrix Sandbox", route: "/matrix-sandbox", icon: Grid3X3 },
  { title: "AI Applications", route: "/ai-applications", icon: BrainCircuit },
  { title: "Learning Hub", route: "/learn", icon: BookOpen },
  { title: "Olympyard", route: "/olympyard", icon: Trophy },
  { title: "Spaced Repetition", route: "/spaced-repetition", icon: CircleHelp },
  { title: "Problem Solver", route: "/problem-solver", icon: Sigma },
  { title: "Concept Graph", route: "/concept-graph", icon: Grid3X3 },
  { title: "Daily Challenge", route: "/daily-challenge", icon: CircleHelp },
  { title: "Worked Examples", route: "/worked-examples", icon: BookOpen },
  { title: "Syllabus", route: "/syllabus", icon: BookOpen },
  { title: "Formulas", route: "/formulas", icon: Sigma },
  { title: "Maths Visual Dictionary", route: "/visual-dictionary", icon: BookOpen },
  { title: "Scientific Calculator", route: "/calculator", icon: Calculator },
  { title: "Unit Converter", route: "/unit-converter", icon: Calculator },
  { title: "Truth Tables", route: "/truth-table", icon: Sigma },
  { title: "Graph Theory", route: "/graph-theory", icon: Network },
  { title: "Discrete World", route: "/discrete-world", icon: Workflow },
  { title: "Graph Compare", route: "/graph-comparison", icon: Waves },
  { title: "Parametric Curves", route: "/parametric-curves", icon: Waves },
  { title: "3D Surface Plotter", route: "/surface-plotter", icon: Cuboid },
  { title: "Fourier Animator", route: "/fourier-animator", icon: Waves },
  { title: "Polar Visualizer", route: "/polar-visualizer", icon: Waves },
  { title: "Quiz", route: "/quiz", icon: CircleHelp },
  { title: "Documentation", route: "/documentation", icon: FileText },
  { title: "About", route: "/about", icon: Info },
];

export function normalizeNavSearchText(value: string) {
  return value
    .toLowerCase()
    .replace(/\bh[\s._-]*c[\s._-]*f\b/g, "hcf")
    .replace(/\bg[\s._-]*c[\s._-]*d\b/g, "gcd")
    .replace(/\bl[\s._-]*c[\s._-]*m\b/g, "lcm")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function basicNavItemSearchText(item: NavItem, sectionTitle: string) {
  return normalizeNavSearchText([
    sectionTitle,
    item.title,
    item.route,
    ...(item.searchTerms ?? []),
  ].join(" "));
}
