import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleHelp, GitBranch, ListChecks, Play, RotateCcw, TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { runTrials, trialProbabilities, trialTree, type TrialOutcome, type TrialRecord, type TrialSettings } from "./bernoulliTrialsModel";
import "./BernoulliTrialsTargetLesson10219.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

const initial: TrialSettings = { n: 8, p: .7, fatigue: false, depletion: false, third: false };
const names = { S: "Success", F: "Failure", O: "Foul", pending: "Ready" };
function Hoop({ outcome }: { outcome?: TrialOutcome }) {
  return <svg viewBox="0 0 70 95" role="img" aria-label={outcome ? names[outcome] : "Basketball hoop, trial not run"}>
    <path d="M18 35L24 72Q35 80 46 72L52 35 M21 45L44 72 M20 35L48 62 M49 45L27 72 M50 35L23 62 M24 59H47 M22 46H49" stroke="#82909e" fill="none" strokeWidth="1.2" />
    <ellipse cx="35" cy="35" rx="22" ry="7" fill="none" stroke="#ae3325" strokeWidth="2.3" />
    {outcome && <g transform={`translate(${outcome === "S" ? 35 : 15} ${outcome === "S" ? 31 : 76})`}><circle r="9" fill={outcome === "O" ? "#a8a8b7" : "#f89821"} stroke="#963e13" /><path d="M-9 0H9M0-9V9M-6-7Q4 0-6 7M6-7Q-4 0 6 7" fill="none" stroke="#713321" /></g>}
    {outcome === "F" && <text x="31" y="84" fill="#c42832">×</text>}
  </svg>;
}
export default function BernoulliTrialsTargetLesson10219({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [settings, setSettings] = useState(initial), [records, setRecords] = useState<TrialRecord[]>([]);
  const [tab, setTab] = useState("Run"), [answers, setAnswers] = useState<Record<string, boolean>>({});
  const change = (patch: Partial<TrialSettings>) => { setSettings(s => ({ ...s, ...(patch.depletion ? { fatigue: false, third: false } : patch.fatigue || patch.third ? { depletion: false } : {}), ...patch })); setRecords([]); };
  const reset = () => { setSettings(initial); setRecords([]); setAnswers({}); };
  const tree = trialTree(settings), valid = !settings.fatigue && !settings.depletion && !settings.third;
  const base = trialProbabilities(settings, []), successes = records.filter(r => r.outcome === "S").length;
  const modes: { key: "fatigue" | "depletion" | "third"; title: string; description: string; effect: string }[] = [
    { key: "fatigue", title: "Fatigue mode", description: "Success propensity decreases by 0.05 after each trial, stopping at zero.", effect: "Same p is no longer guaranteed across trials." },
    { key: "depletion", title: "No-replacement mode", description: `Draw from 20 balls: ${Math.round(settings.p * 20)} success balls. Each drawn ball is removed.`, effect: "Future probabilities depend on earlier outcomes." },
    { key: "third", title: "Third-outcome mode", description: "A foul occurs with probability 0.10; success and failure share the remaining 0.90.", effect: "Three recorded outcomes replace the binary trial." },
  ];
  const questions = [
    { key: "court", text: "Same player, same court, n = 10 independent free throws with fixed p.", answer: true, why: "Fixed count, binary outcomes, independence and constant p." },
    { key: "coin", text: "Coin flips, but the bias changes after each flip.", answer: false, why: "Success probability is not constant." },
    { key: "die", text: "Roll a fair die independently and record 6 as success, not 6 as failure.", answer: true, why: "The recorded outcome is binary, with constant p = 1/6." },
  ];
  const practice = [
    { key: "batter", text: "A batter faces the same pitcher. Is that alone enough to establish Bernoulli trials?", answer: false, why: "It does not establish independence or constant success probability." },
    { key: "urn", text: "Draw a ball, replace it and mix before each independent draw. Success = red.", answer: true, why: "Replacement preserves p and the recording is binary." },
    { key: "wheel", text: "Record all three wheel outcomes: win, lose, bonus.", answer: false, why: "Three recorded outcomes are not a Bernoulli variable." },
    { key: "shooter", text: "Same shooter, but p increases after each trial.", answer: false, why: "The sequence does not have constant p." },
  ];
  const quiz = (q: typeof questions[number]) => <div key={q.key} className="bt-question"><p>{q.text}</p><div>{[true, false].map(value => <label key={String(value)}><input type="radio" name={`bt-${q.key}`} checked={answers[q.key] === value} onChange={() => setAnswers(a => ({ ...a, [q.key]: value }))} />{value ? "Yes" : "No"}</label>)}</div>{answers[q.key] !== undefined && <p role="status" className={answers[q.key] === q.answer ? "bt-good" : "bt-bad"}>{answers[q.key] === q.answer ? "Correct. " : "Not quite. "}{q.why}</p>}</div>;
  const branchCount = settings.third ? 3 : 2, treeWidth = settings.third ? 1020 : 640;
  const position = (path: TrialOutcome[]) => { const index = path.reduce((sum, item) => sum * branchCount + (item === "S" ? 0 : item === "F" ? 1 : 2), 0); return 20 + (index + .5) * (treeWidth - 40) / branchCount ** path.length; };
  return <main className="bt10219" data-testid="school-mockup-0893">
    <header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · PROBABILITY</small><h1>{lesson.title}</h1><p>A Bernoulli trial has exactly two outcomes. A sequence of Bernoulli trials has a constant probability of success and independent trials.</p><div className="bt-tags">18 min · ADVANCED · CONCEPT · foundations</div></header>
    <nav className="bt-tabs" aria-label="Lesson sections">{[["Run", Play], ["Conditions", CircleHelp], ["Tree", GitBranch], ["Examples", ListChecks], ["Practice", ListChecks]].map(([name, Icon]) => { const title = name as string, Symbol = Icon as typeof Play; return <button key={title} aria-current={tab === title ? "location" : undefined} onClick={() => { setTab(title); document.getElementById(`bt-${title}`)?.scrollIntoView({ behavior: "smooth" }); }}><Symbol size={15} />{title}</button>; })}</nav>
    <section id="bt-Run"><div className="bt-lab-heading"><div><h2>Trial Sequence Laboratory (Basketball Free Throws)</h2><p>Each trial records a success or failure{settings.third ? ", or a foul" : ""}.</p></div><div className="bt-summary"><small>Sequence (observed)</small><strong>{records.length ? records.map(r => r.outcome).join(", ") : "Not run yet"}</strong></div><div className="bt-summary" aria-live="polite"><small>Total successes</small><strong>X = {successes} out of {records.length}</strong></div></div>
      <div className="bt-controls"><label>Number of trials (n) <output>{settings.n}</output><input aria-label="Number of trials" type="range" min="1" max="12" value={settings.n} onChange={e => change({ n: +e.target.value })} /><small>(fixed per sequence)</small></label><label>Success probability (p) <output>{settings.p.toFixed(2)}</output><input aria-label="Success probability" type="range" min="0" max="1" step="0.05" value={settings.p} onChange={e => change({ p: +e.target.value })} /><small>({valid ? "constant" : "initial propensity"})</small></label><button className="bt-primary" onClick={() => setRecords(runTrials(settings))}><Play size={16} />Run sequence</button><button onClick={reset}><RotateCcw size={16} />Reset</button></div>
      <div className="bt-sequence">{Array.from({ length: settings.n }, (_, i) => <article key={i}><b>Trial {i + 1}</b><strong className={records[i]?.outcome === "S" ? "bt-good" : records[i] ? "bt-bad" : ""}>{names[records[i]?.outcome ?? "pending"]}</strong><Hoop outcome={records[i]?.outcome} /></article>)}</div>
      <div className="bt-table-scroll"><table className="bt-probabilities"><tbody>{([['P(success)', 'success'], ['P(failure)', 'failure'], ...(settings.third ? [['P(foul)', 'other']] : [])] as [string, keyof typeof base][]).map(([label, key]) => <tr key={key}><th>{label}</th>{Array.from({ length: settings.n }, (_, i) => <td key={i}>{records[i] ? records[i][key].toFixed(2) : !settings.depletion ? trialProbabilities(settings, Array.from({ length: i }, () => "F"))[key].toFixed(2) : i === 0 ? base[key].toFixed(2) : "—"}</td>)}</tr>)}</tbody></table></div>
      <p className="bt-note">{valid ? "These are individual Bernoulli trials. The binomial count X is the total number of successes in n trials." : "Assumptions changed: the usual binomial model is not generally valid. The tree and run use the modified probabilities."}</p>
    </section>
    <section id="bt-Conditions" className="bt-conditions"><div><h2>Bernoulli Conditions — Live Check</h2><div className="bt-checks">{[["n fixed", true, "The number of trials is determined in advance."], ["two outcomes", !settings.third, "Each trial has success or failure."], ["independent", !settings.depletion, "Earlier outcomes do not change later probabilities."], ["same p", !settings.fatigue && !settings.depletion, "Success probability is constant across trials."]].map(([name, ok, text]) => <article key={String(name)}><b>{name}</b><p>{text}</p><span className={ok ? "bt-good" : "bt-bad"}>{ok ? <CheckCircle2 size={13} /> : <TriangleAlert size={13} />}{ok ? "Status: OK" : "Not guaranteed"}</span></article>)}</div><h3>Deliberately break assumptions</h3>{modes.map(mode => <div key={mode.key} className="bt-mode"><label><input type="checkbox" role="switch" aria-label={mode.title} checked={settings[mode.key]} onChange={e => change({ [mode.key]: e.target.checked })} /><span><b>{mode.title}</b><small>{mode.description}</small></span></label><p className={settings[mode.key] ? "bt-bad" : ""}>{settings[mode.key] ? mode.effect : "Off: baseline condition retained"}</p></div>)}</div><aside><h2>Bernoulli Trial Essentials</h2><p>A binary success indicator Y has two possible values:</p><div className="bt-equation">Y = 1 for success<br />Y = 0 for failure</div><p>q = 1 − p</p><p>E(Y) = p</p><p>Var(Y) = pq</p><hr /><p>Baseline: E(Y) = {settings.p.toFixed(2)}</p><p>Var(Y) = {(settings.p * (1 - settings.p)).toFixed(4)}</p>{!valid && <p className="bt-bad">These baseline values do not describe every modified trial.</p>}{settings.depletion && settings.third && <p>In the combined model, a foul consumes a non-success ball.</p>}</aside></section>
    <section className="bt-explanations"><article id="bt-Tree"><h2>Probability Tree (First {Math.min(3, settings.n)} Trials)</h2><p>Each branch probability is conditional on its preceding outcomes.</p><div className="bt-tree-scroll"><svg className="bt-tree" style={{ minWidth: settings.third ? 1020 : 420 }} viewBox={`0 0 ${treeWidth} 390`} role="group" aria-label="Conditional outcome probability tree">{tree.map(node => { const depth = node.path.length, x = position(node.path), y = 26 + depth * 108; const parent = node.path.slice(0, -1), parentX = position(parent); return <g key={node.path.join("") || "start"}>{depth > 0 && <><path d={`M${parentX} ${y - 96}L${x} ${y - 14}`} fill="none" stroke="#a0b4cf" /><text x={(x + parentX) / 2} y={y - 45} textAnchor="middle">{node.conditional.toFixed(2)}</text></>}<rect x={x - 14} y={y - 12} width="28" height="24" rx="4" fill={node.path.at(-1) === "F" ? "#fff0f0" : "#eff9ef"} stroke="#bad0c4" /><text x={x} y={y + 4} textAnchor="middle">{node.path.at(-1) ?? "Start"}</text><title>{node.path.join(", ") || "Start"}: probability {node.probability.toFixed(5)}</title></g>; })}</svg></div><details><summary>Path probabilities</summary><table><thead><tr><th>Path</th><th>Probability</th></tr></thead><tbody>{tree.filter(node => node.path.length === Math.min(3, settings.n)).map(node => <tr key={node.path.join("")}><td>{node.path.join(", ")}</td><td>{node.probability.toFixed(5)}</td></tr>)}</tbody></table></details></article><div id="bt-Examples"><article className="bt-misconception"><h2><TriangleAlert size={15} />Common Misconception</h2><p>Counting successes (binomial) is not the same as an individual Bernoulli trial.</p><div><p><b>Bernoulli trials</b><br />Examine each binary trial individually.<br />Y ∈ {"{0, 1}"}</p><p><b>Binomial count</b><br />Count total successes.<br />X = ∑Yᵢ<br />X ∼ Binomial(n, p) when all conditions hold.</p></div></article><article><h2>Classify the Scenario</h2>{questions.map(quiz)}</article></div></section>
    <section id="bt-Practice"><h2>Quick Practice</h2><p>Does each scenario establish all four Bernoulli sequence conditions?</p><div className="bt-practice">{practice.map(quiz)}</div></section><nav className="bt-next"><Link to="/lessons/school/class-12/class-12-probability-variance"><ArrowLeft size={14} />Previous: Variance</Link><Link to="/lessons/school/class-12/class-12-probability-binomial-distribution">Next: Binomial Distribution<ArrowRight size={14} /></Link></nav>
      <LessonTopicStudyBoard lessonId={10219} view={tab} />

  </main>;
}
