import { useMemo,useRef,useState } from "react";
import { Link } from "react-router-dom";
import { scaleLinear } from "d3";
import { ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Minus,Plus,RotateCw,TriangleAlert } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { confidenceQuestions,confidenceRun,gradeConfidenceAnswers,intervalForMean,type ConfidenceLevel } from "./confidenceIntervalsLessonModel";
import "./ConfidenceIntervalsTargetLesson2011.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
function NumericControl({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void}) {return <div className="ci-number"><b>{label}</b><div><button aria-label={`Decrease ${label}`} title={`Decrease ${label}`} disabled={value===min} onClick={()=>onChange(value-1)}><Minus size={13}/></button><input aria-label={label} type="number" min={min} max={max} value={value} onChange={e=>{const next=+e.target.value;if(Number.isInteger(next)&&next>=min&&next<=max)onChange(next);}}/><button aria-label={`Increase ${label}`} title={`Increase ${label}`} disabled={value===max} onClick={()=>onChange(value+1)}><Plus size={13}/></button></div><input aria-label={`Drag ${label}`} type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)}/></div>;}
export default function ConfidenceIntervalsTargetLesson2011({lesson}:{lesson:AdvancedConceptLesson}) {
  const [n,setN]=useState(64),[sigma,setSigma]=useState(12),[level,setLevel]=useState<ConfidenceLevel>(95),[count,setCount]=useState<20|100>(20),[seed,setSeed]=useState(1),[selected,setSelected]=useState(0),[tab,setTab]=useState("Repeated Sampling Lab"),[help,setHelp]=useState<string|null>(null),[answers,setAnswers]=useState([-1,-1,-1,-1]),[checked,setChecked]=useState(false);
  const run=useMemo(()=>confidenceRun(n,sigma,level,seed),[n,sigma,level,seed]),intervals=run.intervals.slice(0,count),sample=intervals[selected],covered=intervals.filter(i=>i.contains).length,worked=intervalForMean(50,64,12,95),grades=gradeConfidenceAnswers(answers),dragging=useRef(false);
  const domain=[Math.min(50,...run.intervals.map(i=>i.lower)),Math.max(50,...run.intervals.map(i=>i.upper))],pad=(domain[1]-domain[0])*.08,sx=scaleLinear().domain([domain[0]-pad,domain[1]+pad]).nice().range([46,400]),height=70+count*24;
  const navigate=(name:string)=>{setTab(name);if(name==="Overview")setHelp("How it works");document.getElementById(name==="Overview"?"ci-Repeated Sampling Lab":`ci-${name}`)?.scrollIntoView({behavior:"smooth"});};
  const inspect=(e:React.PointerEvent<SVGSVGElement>)=>{const matrix=e.currentTarget.getScreenCTM();if(!matrix)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());setSelected(Math.max(0,Math.min(count-1,Math.round((point.y-45)/24))));};
  return <main className="ci2011" data-testid="advanced-mockup-0905" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={13}/>Advanced lessons</Link><small>PHASE 1 · STATISTICAL INFERENCE</small><h1>{lesson.title}</h1><p>Interpret intervals as a repeated-sampling method rather than a guarantee about one sample.</p><span>#2011 · 16 min · Advanced · Statistical Inference</span></header><nav className="ci-tabs" aria-label="Lesson sections">{["Overview","Repeated Sampling Lab","Worked Example","Common Pitfall","Practice"].map(name=><button key={name} aria-current={tab===name?"location":undefined} onClick={()=>navigate(name)}>{name}</button>)}</nav>
    <section id="ci-Repeated Sampling Lab" className="ci-lab"><div className="ci-lab-grid"><div className="ci-experiment"><h2><i>1</i>Repeated Sampling Lab</h2><p>Independent samples from a normal population with true mean μ = 50 and known σ = {sigma}.</p><div className="ci-help-buttons">{["How it works","What to look for","Why it matters"].map(name=><button key={name} aria-expanded={help===name} onClick={()=>setHelp(help===name?null:name)}>{name}</button>)}</div>{help&&<aside className="ci-help">{help==="How it works"?`Each interval uses the mean of ${n} generated normal observations and known σ / √n. Confidence-level changes retain the samples; n or σ changes regenerate the cohort using the current seed.`:help==="What to look for"?"The vertical line is fixed at μ = 50. Teal intervals contain μ; red intervals miss it. A higher confidence level widens the intervals for the same samples.":"Coverage is a property of the repeated-sampling method. One computed interval either contains the fixed population mean or does not."}</aside>}
    <p className="ci-chart-caption">Each line is a {level}% confidence interval from one sample of size {n}.</p><div className="ci-chart-scroll"><svg viewBox={`0 0 565 ${height}`} style={{height}} className="ci-chart" role="slider" tabIndex={0} aria-label="Inspect simulated confidence interval" aria-valuemin={1} aria-valuemax={count} aria-valuenow={selected+1} onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);inspect(e);}} onPointerMove={e=>{if(dragging.current)inspect(e);}} onPointerUp={e=>{dragging.current=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{dragging.current=false;}} onLostPointerCapture={()=>{dragging.current=false;}} onKeyDown={e=>{const next=e.key==="Home"?0:e.key==="End"?count-1:e.key==="ArrowDown"?selected+1:e.key==="ArrowUp"?selected-1:null;if(next!==null){e.preventDefault();setSelected(Math.max(0,Math.min(count-1,next)));}}}><text x={sx(50)} y="14" textAnchor="middle" className="ci-mu">μ = 50</text><text x="440" y="20">Interval</text><text x="534" y="20" textAnchor="middle">Covers μ?</text><line x1={sx(50)} x2={sx(50)} y1="25" y2={height-40} stroke="#3485ff" strokeWidth="1.6"/>{sx.ticks(6).map(t=><g key={t}><line x1={sx(t)} x2={sx(t)} y1="25" y2={height-40} stroke="#ebf0f6"/><text x={sx(t)} y={height-17} textAnchor="middle">{t}</text></g>)}{intervals.map((interval,i)=>{const y=45+i*24,color=interval.contains?"#039cb2":"#f05056";return <g key={interval.id}><rect x="2" y={y-10} width="560" height="21" rx="3" fill={i===selected?"#edf5ff":"transparent"} fillOpacity=".6"/><text x="10" y={y+4}>{i+1}</text><path d={`M${sx(interval.lower)} ${y-3}V${y+3}M${sx(interval.lower)} ${y}H${sx(interval.upper)}M${sx(interval.upper)} ${y-3}V${y+3}`} stroke={color} fill="none" strokeWidth={i===selected?2:1.4}/><circle cx={sx(interval.mean)} cy={y} r={i===selected?3.5:2.5} fill={color}/><text x="420" y={y+4}>{interval.lower.toFixed(2)} to {interval.upper.toFixed(2)}</text><text x="534" y={y+4} textAnchor="middle" fill={color}>{interval.contains?"✓":"×"}</text></g>;})}</svg></div><label className="ci-inspector">Current sample<select aria-label="Current sample" value={selected} onChange={e=>setSelected(+e.target.value)}>{intervals.map((interval,i)=><option key={interval.id} value={i}>{interval.id}: {interval.mean.toFixed(2)} ({interval.contains?"covers":"misses"} μ)</option>)}</select></label><div className="ci-coverage" aria-live="polite"><div><small>Coverage in this view</small><strong>{covered} / {count}</strong><b>{(covered/count*100).toFixed(1)}%</b></div><button onClick={()=>{setSeed(old=>old===4294967295?1:old+1);setSelected(0);}}>Run {count} new samples<RotateCw size={14}/></button><div><small>Full 100-sample cohort</small><strong>{run.covered} / 100</strong><b>{run.covered.toFixed(1)}%</b></div></div><small className="ci-seed">Seed {seed}; all coverage counts are computed, not fixed to the nominal level.</small></div>
    <aside className="ci-current"><h2><i>2</i>Current Sample <small>({selected+1} of {count})</small></h2><article><h3>Sample mean x̄</h3><strong>{sample.mean.toFixed(2)}</strong></article><article><h3>Standard error</h3><MathExpression display value={`SE=\\frac{\\sigma}{\\sqrt n}=\\frac{${sigma}}{\\sqrt{${n}}}=${sample.se.toFixed(2)}`}/></article><article><h3>Margin of error ({level}%)</h3><MathExpression display value={`ME=z^*SE\\approx ${sample.z.toFixed(3)}\\times ${sample.se.toFixed(2)}\\approx ${sample.margin.toFixed(2)}`}/></article><article><h3>{level}% Confidence Interval</h3><MathExpression display value={`\\bar x\\pm ME=${sample.mean.toFixed(2)}\\pm ${sample.margin.toFixed(2)}`}/><MathExpression display value={`[${sample.lower.toFixed(2)},\\ ${sample.upper.toFixed(2)}]`}/><p>{sample.contains?"Contains μ = 50":"Misses μ = 50"}</p></article><article className="ci-interpretation"><h3>Interpretation (exact)</h3><p>In repeated sampling, about <b>{level}% of intervals made this way contain μ.</b></p><p>This is <b>not a probability about μ</b> in this specific interval.</p><a href="https://www.itl.nist.gov/div898/handbook/prc/section1/prc14.htm" target="_blank" rel="noreferrer">Learn more</a></article></aside></div>
    <div className="ci-controls"><h2><i>3</i>Simulation Controls</h2><div className="ci-control-grid"><NumericControl label="Sample size n" value={n} min={4} max={400} onChange={setN}/><NumericControl label="Population SD σ" value={sigma} min={1} max={30} onChange={setSigma}/><div><b>Confidence level</b><div className="ci-segments" role="group" aria-label="Confidence level">{([90,95,99] as const).map(value=><button key={value} aria-pressed={level===value} onClick={()=>setLevel(value)}>{value}%</button>)}</div></div><div><b>Number of intervals</b><div className="ci-segments" role="group" aria-label="Number of intervals">{([20,100] as const).map(value=><button key={value} aria-pressed={count===value} onClick={()=>{setCount(value);setSelected(old=>Math.min(old,value-1));}}>{value}</button>)}</div></div></div></div></section>
    <section className="ci-explanations"><article id="ci-Worked Example"><h2><BookOpen size={14}/>Worked Example</h2><p>Given μ = 50, σ = 12, n = 64, 95% confidence.</p><b>Step 1: Compute SE</b><MathExpression display value="SE=\frac{12}{\sqrt{64}}=1.50"/><b>Step 2: Critical value</b><MathExpression display value="z^*\approx1.96"/><b>Step 3: Margin of error</b><MathExpression display value={`ME\\approx1.96\\times1.50\\approx${worked.margin.toFixed(2)}`}/><b>Step 4: Interval form</b><MathExpression display value="\bar{x}\pm ME"/><p>For an illustrative sample mean of 50:</p><MathExpression display value={`[${worked.lower.toFixed(2)},${worked.upper.toFixed(2)}]`}/><p>This example is separate from the selected random sample.</p></article><article id="ci-Common Pitfall"><h2><TriangleAlert size={14}/>Common Pitfall</h2><b>Misconception: “There is a 95% probability that μ lies in this interval.”</b><p>Once an interval is computed, μ either lies in it or does not. The {level}% refers to the method's long-run success rate.</p><svg viewBox="0 0 260 140" className="ci-pitfall-chart" role="img" aria-label="First five generated intervals relative to the population mean">{intervals.slice(0,5).map((interval,i)=><g key={i}><line x1={20+(sx(interval.lower)-46)/354*220} x2={20+(sx(interval.upper)-46)/354*220} y1={25+i*22} y2={25+i*22} stroke={interval.contains?"#039cb2":"#f05056"}/><circle cx={20+(sx(interval.mean)-46)/354*220} cy={25+i*22} r="3" fill={interval.contains?"#039cb2":"#f05056"}/></g>)}<line x1={20+(sx(50)-46)/354*220} x2={20+(sx(50)-46)/354*220} y1="8" y2="130" stroke="#3485ff"/></svg><p>Repeated samples → repeated intervals.</p><b>Nominal coverage is not guaranteed for a batch of 20 or 100.</b></article><article><h2><CheckCircle2 size={14}/>Key Takeaways</h2><p>An interval estimates a population mean using sample data.</p><MathExpression display value="\bar{x}\pm z^*\frac{\sigma}{\sqrt{n}}"/><p>Larger σ, smaller n, or higher confidence makes intervals wider.</p><p>This z interval assumes independent normal observations and known population σ.</p><p>Unknown σ requires a different interval method, typically a t interval under normal sampling.</p></article></section>
    <section id="ci-Practice" className="ci-practice"><h2>Practice</h2><div className="ci-question-grid">{confidenceQuestions.map((q,i)=><fieldset key={q.prompt}><legend>{i+1}. {q.prompt}</legend>{q.options.map((option,j)=><label key={option} className={checked&&answers[i]===j?(grades[i]?"ci-correct":"ci-incorrect"):""}><input type="radio" name={`ci-question-${i}`} checked={answers[i]===j} onChange={()=>{setAnswers(old=>old.map((v,k)=>k===i?j:v));setChecked(false);}}/><span>{String.fromCharCode(65+j)}.</span>{option}</label>)}{checked&&<p className="ci-answer-explanation">{q.explanation}</p>}</fieldset>)}</div><button onClick={()=>setChecked(true)}>Check Answers</button>{checked&&<p role="status">{grades.filter(Boolean).length} / 4 correct. {answers.includes(-1)?"Answer every question.":"Review the explanations above."}</p>}</section><nav className="ci-next"><Link to="/lessons/advanced-concepts/2010-four-color-theorem"><ArrowLeft size={14}/>Four-Color Theorem</Link><Link to="/lessons/advanced-concepts/2012-margin-of-error-sample-size">Margin of Error and Sample Size<ArrowRight size={14}/></Link></nav>
      <LessonTopicStudyBoard lessonId={2011} view={tab} />
</main>;
}
