import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Lightbulb, Minus, Plus, RotateCcw, Salad, Soup, Star, TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { dietCost, dietMix, dietProblem, servingValue } from "./dietProblemModel";
import "./DietProblemTargetLesson10207.css";

const money = (n: number) => n.toFixed(2);
export default function DietProblemTargetLesson10207({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [x, setX] = useState(2.25), [y, setY] = useState(2.25), [whole, setWhole] = useState(false);
  const [protein, setProtein] = useState(9), [calcium, setCalcium] = useState(9);
  const [costLine, setCostLine] = useState(20.25), [tab, setTab] = useState("Interact"), [practice, setPractice] = useState(false), [checked, setChecked] = useState(false);
  const drag = useRef<"mix" | "cost" | null>(null);
  const problem = dietProblem(protein, calcium, whole), mix = dietMix(x, y, protein, calcium, whole);
  const scale = 390 / problem.extent, map = (a: number, b: number) => [48 + a * scale, 430 - b * scale];
  const maxCost = 9 * problem.extent;
  const optimal = mix.feasible && Math.abs(mix.cost - problem.optimum.cost) < 1e-8;
  const changeMix = (a: number, b: number, integer = whole) => {
    const nx = servingValue(a, integer, problem.extent), ny = servingValue(b, integer, problem.extent);
    setX(nx); setY(ny); setCostLine(dietCost(nx, ny)); setChecked(false);
  };
  const reset = () => { setX(2.25); setY(2.25); setWhole(false); setProtein(9); setCalcium(9); setCostLine(20.25); setPractice(false); setChecked(false); };
  const navigate = (name: string) => { setTab(name); document.getElementById(`diet-${name}`)?.scrollIntoView({ behavior: "smooth" }); };
  const stop = (event: React.PointerEvent<SVGSVGElement>) => { drag.current = null; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); };
  const useOptimum = () => changeMix(problem.optimum.x, problem.optimum.y);
  return <main className="diet10207" data-testid="school-mockup-0881">
    <header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · LINEAR PROGRAMMING</small><h1>{lesson.title}</h1><p>Learn how to translate nutrition requirements into a minimum-cost linear program and solve it graphically.</p><div className="diet-tags">18 min · ADVANCED · CONCEPT · graph · optimization</div></header>
    <nav className="diet-tabs" aria-label="Lesson sections">{["Interact", "Build Model", "Graph", "Worked Example", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => navigate(name)}>{name}</button>)}<button onClick={reset}><RotateCcw size={14} />Reset all</button></nav>
    <section id="diet-Interact" className="diet-workspace">
      <aside className="diet-mix"><h2><b>1</b>Build your mix</h2><p>Choose servings of Food A and Food B.</p>
{[{ name: "A", value: x, icon: Salad }, { name: "B", value: y, icon: Soup }].map(({ name, value, icon: Icon }) => <div className={`diet-food diet-food-${name}`} key={name}><Icon size={38} strokeWidth={1.5} aria-hidden="true" /><div><label htmlFor={`diet-food-${name}`}>Food {name} <small>(per serving)</small></label><div className="diet-stepper"><button aria-label={`Decrease Food ${name}`} title={`Decrease Food ${name}`} disabled={value <= 0} onClick={() => name === "A" ? changeMix(x - (whole ? 1 : .25), y) : changeMix(x, y - (whole ? 1 : .25))}><Minus size={14} /></button><input id={`diet-food-${name}`} aria-label={`Food ${name} servings`} type="number" min="0" max={problem.extent} step={whole ? 1 : .25} value={value} onChange={e => { if (Number.isFinite(e.target.valueAsNumber)) { if (name === "A") changeMix(e.target.valueAsNumber, y); else changeMix(x, e.target.valueAsNumber); } }} /><button aria-label={`Increase Food ${name}`} title={`Increase Food ${name}`} disabled={value >= problem.extent} onClick={() => name === "A" ? changeMix(x + (whole ? 1 : .25), y) : changeMix(x, y + (whole ? 1 : .25))}><Plus size={14} /></button></div></div><strong>{value}<small>servings</small></strong></div>)}
        <div className="diet-nutrients"><h3>Nutrient progress <small>Units</small></h3>{[{ name: "Protein", amount: mix.protein, need: protein }, { name: "Calcium", amount: mix.calcium, need: calcium }].map(item => <div key={item.name} className={`diet-meter diet-${item.name}`}><label htmlFor={`diet-${item.name}-meter`}>{item.name} <span>(need ≥ {item.need})</span><strong>{money(item.amount)} / {item.need}</strong></label><progress id={`diet-${item.name}-meter`} max={item.need || 1} value={Math.min(item.amount, item.need || 1)} /><div><span>0</span><span>{item.need / 2}</span><span>{item.need}</span></div></div>)}</div>
        <div className="diet-total" aria-live="polite"><h3>Total cost<strong>₹ {money(mix.cost)}</strong></h3><p>= 4 × {x} + 5 × {y}</p></div>
      </aside>
      <div id="diet-Graph" className="diet-graph-panel"><h2><b>2</b>Feasible region &amp; cost line</h2><div className="diet-legend"><span>3x + y = {protein}</span><span>x + 3y = {calcium}</span><span>Cost line 4x + 5y = {money(costLine)}</span><span>Feasible region</span></div>
        <svg className="diet-graph" viewBox="0 0 478 467" aria-label="Diet feasible region with draggable mix and cost line" onPointerMove={event => {
          if (!drag.current) return;
          const matrix = event.currentTarget.getScreenCTM(); if (!matrix) return;
          const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse());
          const a = (point.x - 48) / scale, b = (430 - point.y) / scale;
          if (drag.current === "mix") changeMix(a, b); else setCostLine(Math.max(0, Math.min(maxCost, Math.round(dietCost(a, b) * 4) / 4)));
        }} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={() => { drag.current = null; }}>
          <defs><pattern id="diet-hatch" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="10" height="10" fill="#f2fbf5" /><line y2="10" stroke="#ccebd7" /></pattern><clipPath id="diet-clip"><rect x="48" y="40" width="390" height="390" /></clipPath></defs>
          <g clipPath="url(#diet-clip)"><polygon points={problem.polygon.map(([a, b]) => map(a, b).join(",")).join(" ")} fill="url(#diet-hatch)" stroke="#b8e6c7" />
            {Array.from({ length: problem.extent + 1 }, (_, n) => <path key={n} d={`M${map(n, 0)[0]} 40V430 M48 ${map(0, n)[1]}H438`} stroke="#e7edf1" strokeWidth=".7" />)}
            <path d={`M${map(0, protein).join(" ")}L${map(protein / 3, 0).join(" ")}`} stroke="#168ce4" strokeWidth="1.5" />
            <path d={`M${map(0, calcium / 3).join(" ")}L${map(calcium, 0).join(" ")}`} stroke="#fa8519" strokeWidth="1.5" />
            {whole && problem.integers.filter(p => p.x <= problem.extent && p.y <= problem.extent).map(p => <circle key={`${p.x}-${p.y}`} cx={map(p.x, p.y)[0]} cy={map(p.x, p.y)[1]} r="2" fill="#56a87b" />)}
            <g onPointerDown={event => { event.preventDefault(); drag.current = "cost"; event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId); }} className="diet-drag-cost"><path d={`M${map(0, costLine / 5).join(" ")}L${map(costLine / 4, 0).join(" ")}`} stroke="transparent" strokeWidth="18" /><path d={`M${map(0, costLine / 5).join(" ")}L${map(costLine / 4, 0).join(" ")}`} stroke="#7d3de8" strokeWidth="2" strokeDasharray="8 5" /></g>
          </g>
          <path d="M48 440V27 M44 34L48 27L52 34 M38 430H451 M444 426L451 430L444 434" fill="none" stroke="#3d4961" />
          {Array.from({ length: Math.floor(problem.extent / 2) + 1 }, (_, i) => i * 2).map(n => <g key={n}><text x={map(n, 0)[0]} y="447" textAnchor="middle">{n}</text><text x="39" y={map(0, n)[1] + 4} textAnchor="end">{n}</text></g>)}
          <text x="55" y="22">y (Food B servings)</text><text x="330" y="462">x (Food A servings)</text>
          {problem.vertices.filter(([a, b]) => a === 0 || b === 0).map(([a, b]) => <g key={`${a}-${b}`}><circle cx={map(a, b)[0]} cy={map(a, b)[1]} r="4" fill="#26374e" /><text x={map(a, b)[0] + 9} y={map(a, b)[1] - 10}>({a}, {b})</text></g>)}
          <g role="button" tabIndex={0} aria-label={`Move food mix, Food A ${x}, Food B ${y}`} className="diet-mix-point" onKeyDown={event => {
            const step = whole ? 1 : .25;
            if (["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) { event.preventDefault(); changeMix(x + (event.key === "ArrowLeft" ? -step : event.key === "ArrowRight" ? step : 0), y + (event.key === "ArrowDown" ? -step : event.key === "ArrowUp" ? step : 0)); }
          }} onPointerDown={event => { event.preventDefault(); drag.current = "mix"; event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId); }}><circle cx={map(x, y)[0]} cy={map(x, y)[1]} r="16" fill="transparent" /><circle cx={map(x, y)[0]} cy={map(x, y)[1]} r="8" fill="#fff" stroke="#b68aef" /><circle cx={map(x, y)[0]} cy={map(x, y)[1]} r="4" fill="#7d3de8" /><text x={Math.min(350, map(x, y)[0] + 10)} y={Math.max(37, map(x, y)[1] - 15)} fill="#7037da">({x}, {y})</text></g>
        </svg>
        <label className="diet-cost-slider">Drag the cost line<input aria-label="Cost line position" type="range" min="0" max={maxCost} step=".25" value={costLine} onChange={e => setCostLine(Number(e.target.value))} /><output>Cost = ₹ {money(costLine)}</output></label>
        <label className="diet-whole"><input type="checkbox" role="switch" checked={whole} onChange={e => { setWhole(e.target.checked); changeMix(x, y, e.target.checked); }} /><span><strong>Whole servings only</strong><small>Restrict to integer servings. See integer-feasible points in the region.</small></span></label>
      </div>
    </section>
<section id="diet-Build Model" className="diet-model"><div><h2>Food &amp; nutrient data</h2><table><thead><tr><th>Nutrient / Cost</th><th>Food A<small>(per serving)</small></th><th>Food B<small>(per serving)</small></th><th>Requirement</th></tr></thead><tbody><tr><th>Protein (units)</th><td>3</td><td>1</td><td>≥ {protein}</td></tr><tr><th>Calcium (units)</th><td>1</td><td>3</td><td>≥ {calcium}</td></tr><tr><th>Cost (₹)</th><td>4</td><td>5</td><td>—</td></tr></tbody></table><p className="diet-variables"><CheckCircle2 size={14} />Variables: x = servings of Food A, y = servings of Food B</p></div><div className="diet-equations"><h2>Your linear program</h2><p>Minimize total cost:</p><p>Minimize C = 4x + 5y</p><p>Subject to nutrient requirements:</p><p>3x + y ≥ {protein} <small>(Protein requirement)</small></p><p>x + 3y ≥ {calcium} <small>(Calcium requirement)</small></p><p>x ≥ 0, y ≥ 0 <small>({whole ? "Whole servings" : "Non-negativity"})</small></p></div><aside className="diet-solution" aria-live="polite"><h2>Current solution</h2><strong className={mix.feasible ? "diet-good" : "diet-bad"}>{mix.feasible ? "Feasible" : "Not feasible"}</strong><p className="diet-math">x = {x}<br />y = {y}</p><p><b>Cost = ₹ {money(mix.cost)}</b><br />Protein = {money(mix.protein)}<br />Calcium = {money(mix.calcium)}</p><div><h3>Optimal ({whole ? "whole servings" : "continuous"})</h3><p>Minimum cost = ₹ {money(problem.optimum.cost)}<br />at ({problem.optimum.x}, {problem.optimum.y})</p><button onClick={useOptimum}>Use optimal mix</button></div></aside></section>
    <section id="diet-Worked Example" className="diet-worked"><article><h2>Translate words to symbols (steps)</h2><ol><li><b>Decision variables:</b> Let x, y be servings of Food A, Food B.</li><li><b>Nutrient requirements:</b> At least {protein} protein units → 3x + y ≥ {protein}. At least {calcium} calcium units → x + 3y ≥ {calcium}.</li><li><b>Non-negativity:</b> Servings cannot be negative → x ≥ 0, y ≥ 0.</li><li><b>Objective:</b> Minimize cost with cost ₹4 per A and ₹5 per B → Minimize C = 4x + 5y.</li><li><b>Solve:</b> {whole ? "Compare feasible integer mixes." : "Find the feasible corner with minimum cost."}</li></ol><p className="diet-rule">{whole ? "An integer optimum need not be the rounded continuous optimum." : "Compare every feasible corner. The lowest cost determines the optimum."}</p></article><div><article><h2>Result breakdown at optimum</h2><table><tbody>{[["Food A servings (x)", problem.optimum.x], ["Food B servings (y)", problem.optimum.y], ["Protein supplied", `3(${problem.optimum.x}) + ${problem.optimum.y} = ${problem.optimum.protein}`], ["Calcium supplied", `${problem.optimum.x} + 3(${problem.optimum.y}) = ${problem.optimum.calcium}`], ["Total cost (₹)", money(problem.optimum.cost)]].map(([label, value]) => <tr key={label}><th>{label}</th><td>{value}</td></tr>)}</tbody></table></article><article className="diet-misconception"><h2><TriangleAlert size={16} />Common misconception</h2><strong>Nutrients are constraints, not the objective.</strong><p>We must satisfy (≥) the nutrient requirements while minimizing cost. Minimizing protein instead of cost answers a different question.</p></article></div></section>
    <section id="diet-Practice" className="diet-practice"><div><h2><Star size={18} />Try it yourself</h2><p>Apply the model to a new requirement.</p><strong>Challenge:</strong><p>Change the requirements to at least 12 protein units and at least 12 calcium units. Find the minimum cost and optimal servings.</p><button onClick={() => { setProtein(12); setCalcium(12); setPractice(true); setChecked(false); navigate("Interact"); }}>Open practice workspace</button></div><div><p><b>Requirements:</b> Protein ≥ 12, Calcium ≥ 12</p><p><b>Goal:</b> Min C = 4x + 5y</p><p><Lightbulb size={16} />The new continuous optimum occurs at the intersection of the lines.</p>{practice && <><button onClick={() => setChecked(true)}>Check current mix</button>{checked && <p role="status">{optimal ? `Correct: the minimum cost is ₹${money(problem.optimum.cost)}.` : mix.feasible ? "Your mix meets the requirements, but a cheaper feasible mix exists." : "Your mix does not meet both nutrient requirements."}</p>}</>}</div></section>
    <nav className="diet-next"><Link to="/lessons/school/class-12/class-12-linear-programming-infeasible-problems"><ArrowLeft size={14} />Infeasible Problems</Link><Link to="/lessons/school/class-12/class-12-linear-programming-production-planning-problem">Production Planning Problem<ArrowRight size={14} /></Link></nav>
  </main>;
}
