import { useMemo,useState } from "react";
import { Link } from "react-router-dom";
import { scaleLinear } from "d3";
import { ArrowLeft,ArrowRight,CheckCircle2,Download,Maximize2,Minimize2,RotateCcw } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { checkErrorPractice,diffusionKernel,errorCurves,errorFunctionState,erfValue } from "./errorFunctionModel";
import "./ErrorFunctionTargetLesson2023.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
type CurveKey="gaussian"|"erf"|"erfc"|"normal";
function ErrorPlot({kind,x,onX,mini=false,tau}:{kind:CurveKey;x:number;onX?:(n:number)=>void;mini?:boolean;tau?:number}) {
  const sx=scaleLinear().domain([-3,3]).range([40,470]),upper=tau!==undefined?Math.max(.6,diffusionKernel(0,tau)*1.15):kind==="erfc"?2.1:1.1,sy=scaleLinear().domain([kind==="erf"?-1.15:0,upper]).range([255,20]),points=errorCurves.map(p=>({x:p.x,y:tau!==undefined?diffusionKernel(p.x,tau):p[kind]})),value=tau!==undefined?diffusionKernel(x,tau):kind==="gaussian"?Math.exp(-x*x):errorFunctionState(x)[kind],curve=points.map((p,i)=>`${i?"L":"M"}${sx(p.x)},${sy(p.y)}`).join(" ");
  const shade=Array.from({length:101},(_,i)=>{const t=x*i/100;return `${i?"L":"M"}${sx(t)},${sy(Math.exp(-t*t))}`;}).join(" ");
  const change=(e:React.PointerEvent<SVGSVGElement>)=>{const m=e.currentTarget.getScreenCTM();if(m)onX?.(sx.invert(new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse()).x));};
  return <svg viewBox="0 0 505 285" role={onX?"group":"img"} aria-label={tau!==undefined?`Diffusion profile at diffusivity times time ${tau}`:`${kind} curve at x ${x}`} className={onX?"ef-draggable":""} onPointerDown={e=>{if(onX){e.currentTarget.setPointerCapture(e.pointerId);change(e);}}} onPointerMove={e=>{if(onX&&e.currentTarget.hasPointerCapture(e.pointerId))change(e);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}>
    {sy.ticks(4).map(t=><g key={t}><path d={`M40 ${sy(t)}H470`} stroke="#eef2f6"/><text x={sx(0)-10} y={sy(t)+4} textAnchor="end">{t}</text></g>)}{kind==="gaussian"&&tau===undefined&&<path d={`${shade}L${sx(x)} ${sy(0)}L${sx(0)} ${sy(0)}Z`} fill={x<0?"#ffd4a1":"#ffcf7b"}/>}{kind==="erf"&&[-1,1].map(t=><path key={t} d={`M40 ${sy(t)}H470`} stroke="#8d9aad" strokeDasharray="5 5"/>)}<path d={`M40 ${sy(0)}H485M${sx(0)} 10V263`} stroke="#526179" fill="none"/>{[-3,-2,-1,0,1,2,3].map(t=><text key={t} x={sx(t)} y="278" textAnchor="middle">{t}</text>)}<path d={curve} stroke={kind==="gaussian"?"#893beb":"#009dca"} strokeWidth="2.4" fill="none"/>{tau===undefined&&!mini&&<><path d={`M${sx(x)} 20V255`} stroke="#7c8697" strokeDasharray="4 4"/><circle cx={sx(x)} cy={sy(value)} r="6" fill={kind==="gaussian"?"#f5a11b":"#009ec2"} stroke="white" strokeWidth="2"/>{kind==="gaussian"&&<circle cx={sx(x)} cy={sy(0)} r="9" fill="#f5a11b" stroke="white" strokeWidth="2"/>}</>}
  </svg>;
}
export default function ErrorFunctionTargetLesson2023({lesson}:{lesson:AdvancedConceptLesson}) {
  const [x,setX]=useState(1),[tau,setTau]=useState(.25),[expanded,setExpanded]=useState(false),[tab,setTab]=useState(2),[zero,setZero]=useState(""),[interpretation,setInterpretation]=useState(""),[one,setOne]=useState(""),[checked,setChecked]=useState(false),[showReference,setShowReference]=useState(true);
  const state=useMemo(()=>errorFunctionState(x),[x]),valid=checkErrorPractice(zero,interpretation,one);
  function move(n:number){setX(Math.max(-3,Math.min(3,Math.round(n*1000)/1000)));}
  function download(){const rows=["x,gaussian,integral_0_x,erf,erfc,normal_cdf",...errorCurves.map(p=>[p.x,p.gaussian,p.area,p.erf,p.erfc,p.normal].join(","))].join("\n"),url=URL.createObjectURL(new Blob([rows],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download="error-function-values.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <main className="ef2023" data-testid="advanced-mockup-0917" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={14}/>Advanced lessons</Link><small>PHASE 1 · SPECIAL FUNCTIONS</small><h1>{lesson.title}</h1><p>The error function is a scaled, signed Gaussian integral from 0 to x.</p><span>#2023 · 15 min · Advanced · Special Functions</span></header><section className="ef-intro"><div><h2>Interactive Lab</h2><p>Accumulated Gaussian area and its corresponding error-function value.</p></div><Link to={lesson.toolRoute}>Open studio<ArrowRight size={14}/></Link></section>
    <div className={`ef-workspace ${expanded?"expanded":""}`}><section className="ef-lab"><div className="ef-heading"><h2>Gaussian Accumulation Lab</h2><div><button onClick={()=>move(1)}><RotateCcw size={13}/>Reset</button><button title={expanded?"Restore layout":"Expand graphs"} aria-label={expanded?"Restore layout":"Expand graphs"} onClick={()=>setExpanded(v=>!v)}>{expanded?<Minimize2 size={14}/>:<Maximize2 size={14}/>}</button><button title="Download calculated CSV" aria-label="Download calculated CSV" onClick={download}><Download size={14}/></button></div></div><article className="ef-linked"><h3>1A · Gaussian kernel and accumulated area</h3><MathExpression value="y=e^{-t^2},\quad\int_0^x e^{-t^2}\,dt"/><div><ErrorPlot kind="gaussian" x={x} onX={move}/><aside><label>x = <input type="number" aria-label="Gaussian upper limit x" min="-3" max="3" step=".001" value={x} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))move(e.target.valueAsNumber);}}/><input type="range" aria-label="Gaussian upper limit slider" min="-3" max="3" step=".001" value={x} onChange={e=>move(+e.target.value)}/></label><p>Signed integral</p><strong className="ef-orange">{state.area.toFixed(10)}</strong><small>{x<0?"The geometric region is positive; reversing limits from 0 to negative x gives a negative integral.":"This is the unscaled Gaussian area, not erf(x)."}</small></aside></div></article><article className="ef-linked"><h3>1B · Error function</h3><MathExpression value="\operatorname{erf}(x)=\frac{2}{\sqrt\pi}\int_0^x e^{-t^2}\,dt"/><div><ErrorPlot kind="erf" x={x} onX={move}/><aside><h3>erf({x.toFixed(3)})</h3><strong>{state.erf.toFixed(10)}</strong><h3>Odd Symmetry</h3><p>erf(−x) = {(-state.erf).toFixed(8)}</p><h3>Derivative</h3><p>erf′(x) = {state.derivative.toFixed(8)}</p><p>The curve approaches −1 and 1 without attaining them at finite x.</p></aside></div></article></section>
    <aside className="ef-properties"><section><h2>Key Properties</h2><h3>Definition</h3><MathExpression value="\operatorname{erf}(x)=\frac{2}{\sqrt\pi}\int_0^x e^{-t^2}\,dt" display/><h3>Odd symmetry</h3><MathExpression value="\operatorname{erf}(-x)=-\operatorname{erf}(x)"/><h3>Limits</h3><MathExpression value="\lim_{x\to\infty}\operatorname{erf}(x)=1" display/><MathExpression value="\lim_{x\to-\infty}\operatorname{erf}(x)=-1" display/><h3>Derivative</h3><MathExpression value="\operatorname{erf}'(x)=\frac{2}{\sqrt\pi}e^{-x^2}" display/></section><section><h2>Link to Normal CDF</h2><MathExpression value="\Phi(z)=\frac12\left[1+\operatorname{erf}\left(\frac{z}{\sqrt2}\right)\right]" display/><h3>Current z = x = {x}</h3><p>Φ({x}) = {state.normal.toFixed(10)}</p><h3>Checkpoint</h3><p>Φ(1) = {errorFunctionState(1).normal.toFixed(10)}</p></section></aside></div>
    <section className="ef-three"><article><h2>Diffusion Profile (Heat Equation)</h2><MathExpression value="u(z,t)=\frac{1}{\sqrt{4\pi\alpha t}}e^{-z^2/(4\alpha t)}"/><label>αt<select aria-label="Diffusivity times time" value={tau} onChange={e=>setTau(+e.target.value)}>{[.1,.25,.5,1,2].map(v=><option key={v} value={v}>{v}</option>)}</select></label><ErrorPlot kind="gaussian" tau={tau} x={x} mini/><p>Total mass on the full real line = 1.</p><small>Only z ∈ [−3,3] is displayed; wider profiles extend beyond this window.</small></article><article><h2>Complementary Error Function</h2><MathExpression value="\operatorname{erfc}(x)=1-\operatorname{erf}(x)"/><ErrorPlot kind="erfc" x={x} mini/><p>erfc({x.toFixed(3)})</p><strong>{state.erfc.toFixed(10)}</strong><small>erfc decreases from 2 toward 0 across the real line.</small></article><article><h2>Normal CDF Φ(z)</h2><MathExpression value="\Phi(z)=\tfrac12[1+\operatorname{erf}(z/\sqrt2)]"/><ErrorPlot kind="normal" x={x} mini/><p>Φ({x.toFixed(3)})</p><strong>{state.normal.toFixed(10)}</strong></article></section>
    <section className="ef-three ef-study"><article><h2>Study &amp; Practice</h2><div className="ef-tabs" role="group" aria-label="Study view">{["Learn","Explore","Practice"].map((name,i)=><button key={name} aria-pressed={tab===i} onClick={()=>setTab(i)}>{name}</button>)}</div>{tab===0?<><p>Integrate the positive Gaussian kernel with oriented limits, then multiply by 2/√π.</p><p>The resulting erf is odd and increasing, with derivative 2e⁻ˣ²/√π.</p><p>The raw kernel e⁻ᵗ² is not a normalized probability density on the real line.</p></>:tab===1?<><button onClick={()=>move(-x)}>Reflect x → −x</button><button onClick={()=>move(0)}>Inspect zero</button><button onClick={()=>move(3)}>Inspect x = 3</button><p>Compare the integral, erf, erfc and normal CDF at the same input.</p></>:<><label>1. Find erf(0)<input aria-label="Practice erf zero" type="number" step="any" value={zero} onChange={e=>{setZero(e.target.value);setChecked(false);}}/></label><fieldset><legend>2. The signed shaded integral represents:</legend>{[{id:"integral",label:"The unscaled integral of e⁻ᵗ² from 0 to x."},{id:"symmetric",label:"The symmetric area from −x to x."},{id:"erf",label:"The value of erf(x) directly."}].map(a=><label key={a.id}><input type="radio" name="erf-area-meaning" value={a.id} checked={interpretation===a.id} onChange={e=>{setInterpretation(e.target.value);setChecked(false);}}/>{a.label}</label>)}</fieldset><label>3. Use odd symmetry to find erf(1) from erf(−1) ≈ −0.842700793<input aria-label="Practice erf one" type="number" step="any" value={one} onChange={e=>{setOne(e.target.value);setChecked(false);}}/></label><button onClick={()=>setChecked(true)}>Check answers</button>{checked&&<p role="status">{valid.map((v,i)=>`${i+1}: ${v?"Correct":"Try again"}`).join(" · ")}</p>}</>}</article><article className="ef-reference"><h2>Quick Reference</h2><button aria-expanded={showReference} onClick={()=>setShowReference(v=>!v)}>{showReference?"Hide":"Show"} reference values</button>{showReference&&<ul><li>erf(0) = 0</li><li>erf(1) ≈ {erfValue(1).toFixed(10)}</li><li>erf(−1) ≈ {erfValue(-1).toFixed(10)}</li><li>erfc(1) ≈ {errorFunctionState(1).erfc.toFixed(10)}</li><li>Φ(1) ≈ {errorFunctionState(1).normal.toFixed(10)}</li></ul>}<h2>Formulas</h2><MathExpression value="\operatorname{erfc}(x)=1-\operatorname{erf}(x)" display/><MathExpression value="\Phi(z)=\tfrac12[1+\operatorname{erf}(z/\sqrt2)]" display/></article><article><h2>Objectives</h2>{["Understand the scaled Gaussian integral.","Use odd symmetry and limits.","Connect erf to the normal CDF.","Recognize diffusion profiles and conservation of mass."].map(s=><p key={s}><CheckCircle2 size={14}/>{s}</p>)}<small>Objectives describe learning aims, not automatically awarded completion.</small></article></section><nav><Link to="/lessons/advanced-concepts/2022-beta-function"><ArrowLeft size={14}/>Beta Function</Link><Link to="/lessons/advanced-concepts/2024-zeta-function">Zeta Function<ArrowRight size={14}/></Link></nav>
      <LessonTopicStudyBoard lessonId={2023} view={tab} />
</main>;
}
