import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft,ArrowRight,BookOpen,CheckCircle2,FlaskConical,GitFork,Monitor,Palette,RotateCcw,ShieldCheck,Trash2,Undo2,XCircle } from "lucide-react";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { coloringStatus,fourColorMap,initialMapColors,mapEdges,palette,practiceColorMap,regionPath,suggestedColors,type RegionMap } from "./fourColorLessonModel";
import "./FourColorTheoremTargetLesson2010.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
const originalPositions:[[number,number],...Array<[number,number]>]=[[45,55],[150,55],[255,55],[35,145],[150,145],[260,145],[35,235],[150,235],[260,235],[90,310],[210,310]];
function MapDrawing({map,colors,onPaint,highlight=0,onHighlight,small=false}:{map:RegionMap;colors:number[];onPaint?:(id:number)=>void;highlight?:number;onHighlight?:(id:number)=>void;small?:boolean}) {
  return <svg viewBox={map===fourColorMap?"0 0 300 450":"0 0 215 215"} className={small?"fc-mini-map":"fc-map"} aria-label={map===fourColorMap?"Eleven-region planar map":"Five-region practice map"} role="group">{map.regions.map(region=><g key={region.id} role={onPaint?"button":undefined} tabIndex={onPaint?0:undefined} aria-label={`Region ${region.id}, ${palette[colors[region.id-1]]?.name??"uncolored"}`} onClick={()=>onPaint?.(region.id)} onKeyDown={e=>{if(onPaint&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onPaint(region.id);}}} onMouseEnter={()=>onHighlight?.(region.id)} onMouseLeave={()=>onHighlight?.(0)} onFocus={()=>onHighlight?.(region.id)} onBlur={()=>onHighlight?.(0)}><path d={regionPath(map,region)} fill={palette[colors[region.id-1]]?.hex??"#f2f5fa"} stroke={highlight===region.id?"#006aa9":"#49566c"} strokeWidth={highlight===region.id?3:1.5}/><circle cx={region.label[0]} cy={region.label[1]} r={small?15:12} fill="white" stroke="#aac7da"/><text x={region.label[0]} y={region.label[1]+4} textAnchor="middle">{region.id}</text></g>)}</svg>;
}
export default function FourColorTheoremTargetLesson2010({lesson}:{lesson:AdvancedConceptLesson}) {
  const [colors,setColors]=useState([...initialMapColors]),[count,setCount]=useState(4),[selected,setSelected]=useState(0),[history,setHistory]=useState<{colors:number[];count:number}[]>([]),[auto,setAuto]=useState(true),[checked,setChecked]=useState(false),[highlight,setHighlight]=useState(0),[tab,setTab]=useState("Color map"),[positions,setPositions]=useState(originalPositions),[proof,setProof]=useState(false);
  const [practice,setPractice]=useState([0,1,2,-1,0]),[practiceColor,setPracticeColor]=useState(1),[practiceChecked,setPracticeChecked]=useState(false);
  const drag=useRef<{id:number;x:number;y:number;moved:boolean}|null>(null),suppressClick=useRef(false);
  const edges=mapEdges(fourColorMap),status=coloringStatus(fourColorMap,colors,count),practiceStatus=coloringStatus(practiceColorMap,practice,3),show=auto||checked;
  function change(next:number[],newCount=count){setHistory(old=>[...old,{colors:[...colors],count}]);setColors(next);setCount(newCount);setChecked(false);}
  const paint=(id:number)=>{if(colors[id-1]!==selected)change(colors.map((c,i)=>i===id-1?selected:c));};
  function undo(){const previous=history.at(-1);if(previous){setColors(previous.colors);setCount(previous.count);setSelected(old=>Math.min(old,previous.count-1));setHistory(old=>old.slice(0,-1));setChecked(false);}}
  const goto=(name:string)=>{setTab(name);if(name==="Proof story")setProof(true);document.getElementById(`fc-${name}`)?.scrollIntoView({behavior:"smooth"});};
  const summary=status.valid?`Great! No adjacent regions share a color. ${status.used} colors used.`:`${status.conflicts.length} shared-border conflicts; ${status.incomplete.length} regions need a permitted color.`;
  return <main className="fc2010" data-testid="advanced-mockup-0904" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={13}/>Advanced lessons</Link><small>PHASE 1 · FAMOUS PROBLEMS</small><h1>{lesson.title}</h1><p>Model maps as graphs and test why four colors always suffice on a plane.</p><span>#2010 · 16 min · Advanced · Famous Problems</span></header><nav className="fc-tabs" aria-label="Lesson sections">{[{name:"Color map",icon:Palette},{name:"Adjacency graph",icon:GitFork},{name:"Proof story",icon:BookOpen},{name:"Practice",icon:ShieldCheck}].map(({name,icon:Icon})=><button key={name} aria-current={tab===name?"location":undefined} onClick={()=>goto(name)}><Icon size={14}/>{name}</button>)}</nav>
    <section id="fc-Color map" className="fc-studio"><div className="fc-studio-head"><div><h2>Map Coloring Studio</h2><p>Color the regions so that no two adjacent regions share a color.</p></div><div className="fc-count"><small>Colors used</small><strong>{status.used}</strong><span>{palette.slice(0,count).map((color,i)=><i key={color.name} style={{background:color.hex,opacity:colors.includes(i)?1:.2}}/>)}</span></div><div className="fc-count"><small>Conflicts</small><strong>{show?status.conflicts.length:"—"}</strong></div><label className="fc-auto">Auto-check<input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);setChecked(false);}}/></label>{!auto&&<button onClick={()=>setChecked(true)}>Check</button>}</div>
    <div className="fc-workspace"><aside className="fc-tools"><h3>Palette ({count} colors)</h3><div className="fc-swatches">{palette.slice(0,count).map((color,i)=><button key={color.name} aria-label={`Paint ${color.name}`} title={color.name} aria-pressed={selected===i} style={{background:color.hex}} onClick={()=>setSelected(i)}/>)}</div><h3>Tools</h3><div className="fc-tool-buttons"><button title="Undo coloring" aria-label="Undo coloring" disabled={!history.length} onClick={undo}><Undo2 size={15}/></button><button title="Reset map" aria-label="Reset map" onClick={()=>change([...initialMapColors],4)}><RotateCcw size={15}/></button><button title="Clear map" aria-label="Clear map" onClick={()=>change(Array(11).fill(-1))}><Trash2 size={15}/></button></div><button className="fc-three" onClick={()=>{const next=count===4?3:4;change(colors.map(c=>c>=next?-1:c),next);setSelected(0);}}><FlaskConical size={14}/>{count===4?"Try with 3 colors":"Use 4 colors"}</button><button onClick={()=>{const suggested=suggestedColors(fourColorMap);change(suggested,4);setSelected(0);}}>Apply greedy coloring</button><div className="fc-selected"><b>{highlight?`Region ${highlight}`:"Shared borders"}</b><p>{highlight?`Neighbors: ${edges.filter(e=>e.includes(highlight)).map(e=>e.find(id=>id!==highlight)).sort((a,b)=>a!-b!).join(", ")}`:"Regions touching only at a point are not adjacent."}</p></div></aside>
    <div className="fc-map-column"><MapDrawing map={fourColorMap} colors={colors} onPaint={paint} highlight={highlight} onHighlight={setHighlight}/><p className={status.valid?"fc-success":"fc-feedback"} role="status">{show?summary:"Coloring changed. Check to see conflicts."}</p></div>
    <div id="fc-Adjacency graph" className="fc-graph-column"><h2>Planar Adjacency Graph</h2><p>Each region is a vertex.<br/>Edges connect regions sharing a border.</p><svg viewBox="0 0 300 350" className="fc-graph" role="group" aria-label="Linked adjacency graph">{edges.map(([a,b])=>{const conflict=show&&status.conflicts.some(([u,v])=>u===a&&v===b);return <line key={`${a}-${b}`} x1={positions[a-1][0]} y1={positions[a-1][1]} x2={positions[b-1][0]} y2={positions[b-1][1]} stroke={conflict?"#df354e":highlight===a||highlight===b?"#008ad0":"#64708a"} strokeWidth={conflict?3:1.3}/>;})}{positions.map(([x,y],i)=><g key={i} role="button" tabIndex={0} aria-label={`Graph vertex ${i+1}, ${palette[colors[i]]?.name??"uncolored"}`} onMouseEnter={()=>setHighlight(i+1)} onMouseLeave={()=>setHighlight(0)} onFocus={()=>setHighlight(i+1)} onBlur={()=>setHighlight(0)} onPointerDown={e=>{drag.current={id:i,x:e.clientX,y:e.clientY,moved:false};suppressClick.current=false;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const active=drag.current;if(!active||active.id!==i)return;if(Math.hypot(e.clientX-active.x,e.clientY-active.y)<4&&!active.moved)return;active.moved=true;suppressClick.current=true;const matrix=e.currentTarget.ownerSVGElement?.getScreenCTM();if(!matrix)return;const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());setPositions(old=>old.map((v,j)=>i===j?[Math.max(18,Math.min(282,point.x)),Math.max(20,Math.min(330,point.y))]:v) as typeof originalPositions);}} onPointerUp={e=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onPointerCancel={()=>{drag.current=null;suppressClick.current=true;}} onLostPointerCapture={()=>{drag.current=null;}} onClick={()=>{if(!suppressClick.current)paint(i+1);suppressClick.current=false;}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();paint(i+1);}else if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();setPositions(old=>old.map((v,j)=>i===j?[Math.max(18,Math.min(282,v[0]+(e.key==="ArrowLeft"?-5:e.key==="ArrowRight"?5:0))),Math.max(20,Math.min(330,v[1]+(e.key==="ArrowUp"?-5:e.key==="ArrowDown"?5:0)))]:v) as typeof originalPositions);}}}><circle cx={x} cy={y} r="17" fill={palette[colors[i]]?.hex??"#f2f5fa"} stroke={highlight===i+1?"#007aaf":"#6a6e7d"} strokeWidth={highlight===i+1?3:1}/><text x={x} y={y+4} textAnchor="middle">{i+1}</text><title>{`Vertex ${i+1}: same color as region ${i+1}`}</title></g>)}</svg><button aria-label="Reset graph positions" title="Reset graph positions" onClick={()=>setPositions(originalPositions)}><RotateCcw size={14}/></button><div className="fc-adjacent"><h3>What counts as adjacent?</h3><p><CheckCircle2 size={14}/>Sharing an edge counts.</p><p><XCircle size={14}/>Touching at a point does not.</p></div></div></div></section>
    <section className="fc-two"><article><h2>Map ↔ Graph Transformation</h2><p>The map and its adjacency graph represent the same shared-border relationships.</p><div className="fc-transformation"><MapDrawing map={fourColorMap} colors={colors} small/><ArrowRight size={23}/><svg viewBox="0 0 300 350" aria-label="Miniature adjacency graph" role="img">{edges.map(([a,b])=><line key={`${a}-${b}`} x1={originalPositions[a-1][0]} y1={originalPositions[a-1][1]} x2={originalPositions[b-1][0]} y2={originalPositions[b-1][1]} stroke="#62708b"/>)}{originalPositions.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="18" fill={palette[colors[i]]?.hex??"#edf2f8"} stroke="#586579"/><text x={x} y={y+4} textAnchor="middle">{i+1}</text></g>)}</svg></div><p>11 regions ↔ 11 vertices. {edges.length} shared borders ↔ {edges.length} edges.</p></article><article><h2>Quick facts</h2><p><Palette size={17}/>At most four colors suffice for every planar map under shared-edge adjacency.</p><p><Monitor size={17}/>Appel and Haken announced the computer-assisted proof in 1976.</p><p><BookOpen size={17}/>The proof reduces the problem to an unavoidable set of configurations.</p><p><ShieldCheck size={17}/>Reducibility rules these configurations out of a minimal counterexample.</p></article></section>
    <section className="fc-two"><article className="fc-misconception"><h2>Common misconception</h2><p>Touching at a point does not require different colors.</p><div className="fc-contact-examples"><figure><svg viewBox="0 0 160 100" role="img" aria-label="Two regions touching only at a point"><path d="M15 35L55 20L80 50L50 90Z" fill="#ffdf68" stroke="#596278"/><path d="M80 50L115 15L150 50L135 90Z" fill="#be92e4" stroke="#596278"/><circle cx="80" cy="50" r="3" fill="#069978"/></svg><figcaption>Not adjacent: one point</figcaption><CheckCircle2 size={22}/></figure><figure><svg viewBox="0 0 160 100" role="img" aria-label="Two regions sharing a border"><path d="M15 50L40 15H80V90H40Z" fill="#72d1e9" stroke="#596278"/><path d="M80 15H125L150 50L125 90H80Z" fill="#ffdf68" stroke="#596278"/></svg><figcaption>Adjacent: shared edge</figcaption><ShieldCheck size={22}/></figure></div></article><article id="fc-Practice"><h2>Practice Challenge</h2><p>Color this five-region map using only three colors.</p><div className="fc-practice-layout"><MapDrawing map={practiceColorMap} colors={practice} onPaint={id=>{setPractice(old=>old.map((c,i)=>i===id-1?practiceColor:c));setPracticeChecked(false);}}/><div><div className="fc-swatches">{palette.slice(0,3).map((color,i)=><button key={color.name} aria-label={`Practice paint ${color.name}`} title={color.name} style={{background:color.hex}} aria-pressed={practiceColor===i} onClick={()=>setPracticeColor(i)}/>)}</div><p>Adjacent regions must differ. Corner-only contact is allowed.</p><button onClick={()=>setPracticeChecked(true)}>Check my answer</button><button title="Clear practice" aria-label="Clear practice" onClick={()=>{setPractice(Array(5).fill(-1));setPracticeChecked(false);}}><RotateCcw size={14}/></button></div></div>{practiceChecked&&<p role="status" className={practiceStatus.valid?"fc-success":"fc-feedback"}>{practiceStatus.valid?"Correct! The map uses at most three colors with no shared-border conflicts.":`${practiceStatus.conflicts.length} conflicts; ${practiceStatus.incomplete.length} regions still need a color.`}</p>}</article></section>
    <section className="fc-two"><article><h2>Theorem statement</h2><p className="fc-theorem">Every planar map can be colored using at most four colors so that no two regions sharing an edge have the same color.</p><p>This map can also use three colors. The theorem gives an upper bound, not a requirement to use all four.</p></article><article id="fc-Proof story"><h2>About the proof</h2><p>The accepted proof is computer-assisted. Finite configuration checks belong to a broader mathematical argument, not merely a trial on a few maps.</p><button onClick={()=>setProof(v=>!v)}>{proof?"Close proof story":"Explore proof story"}<ArrowRight size={14}/></button>{proof&&<div className="fc-proof"><ol><li>Assume a smallest counterexample exists.</li><li>Show it must contain a configuration from an unavoidable set.</li><li>Verify that every configuration in that set is reducible, so it cannot occur in a smallest counterexample.</li><li>The contradiction eliminates the counterexample.</li></ol><a href="https://www.library.illinois.edu/mtx/four-color-theorem-resources/" target="_blank" rel="noreferrer">University of Illinois proof resources</a></div>}</article></section><nav className="fc-next"><Link to="/lessons/advanced-concepts/2009-fermats-last-theorem"><ArrowLeft size={14}/>Fermat's Last Theorem</Link><Link to="/lessons/advanced-concepts/2011-confidence-intervals">Confidence Intervals<ArrowRight size={14}/></Link></nav>
      <LessonTopicStudyBoard lessonId={2010} view={tab} />
</main>;
}
