import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { scaleLinear } from "d3";
import { ArrowLeft, ArrowRight, ArrowDownRight, ArrowUpRight, Check, Eye, EyeOff, Minus, Radiation, RotateCcw, Shuffle, Sprout } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { checkGrowthChallenge, growthModel, growthPreset, type GrowthContext } from "./growthDecayModel";
import "./GrowthDecayTargetLesson2018.css";

const compact=(value:number)=>Math.abs(value)>=100000?value.toExponential(1):Number(value.toFixed(2)).toLocaleString("en-US");
export default function GrowthDecayTargetLesson2018({lesson}:{lesson:AdvancedConceptLesson}) {
  const [k,setK]=useState(.35),[initial,setInitial]=useState(100),[window,setWindow]=useState(8),[markers,setMarkers]=useState(true),[context,setContext]=useState<GrowthContext>("bacteria");
  const [coefficient,setCoefficient]=useState(""),[rate,setRate]=useState(""),[halfLife,setHalfLife]=useState(""),[amount,setAmount]=useState(""),[checked,setChecked]=useState(false),[reveal,setReveal]=useState(false);
  const model=useMemo(()=>growthModel(k,initial,window),[k,initial,window]),unit=context==="bacteria"?"hours":"days",quantity=context==="bacteria"?"bacteria":"grams",symbol=context==="bacteria"?"P":"N";
  const sx=scaleLinear().domain([0,window]).range([62,608]),sy=scaleLinear().domain([0,Math.max(initial*1.3,model.samples.at(-1)!.growth*1.06)]).nice(6).range([590,54]);
  const curve=(kind:"growth"|"decay")=>model.samples.map((p,i)=>`${i?"L":"M"}${sx(p.t)},${sy(p[kind])}`).join(" "),valid=checkGrowthChallenge(coefficient,rate,halfLife,amount);
  function preset(newK:number,newInitial:number) { setK(newK);setInitial(newInitial); }
  function selectContext(next:GrowthContext) { setContext(next);const p=growthPreset(next);preset(p.k,p.initial);setWindow(p.window); }
  function reset(){selectContext("bacteria");setMarkers(true);}
  return <main className="gd2018" data-testid="advanced-mockup-0912" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={14}/>Advanced lessons</Link><small>PHASE 1 · DIFFERENTIAL EQUATIONS</small><h1>{lesson.title}</h1><p>Proportional change with initial value problems: <MathExpression value="y'=ky,\quad y(0)=y_0"/></p><span>#2018 · {lesson.estimatedMinutes} min · Advanced · Differential Equations</span></header>
    <section className="gd-lab"><div className="gd-lab-heading"><h2>Proportional Change Lab</h2><button onClick={reset}><RotateCcw size={14}/>Reset</button></div><div className="gd-subheading"><p>Solutions of y′ = ky for positive initial amounts.</p><label>Show markers<input type="checkbox" role="switch" checked={markers} onChange={e=>setMarkers(e.target.checked)}/></label></div>
    <div className="gd-workspace"><aside><div className="gd-parameters"><h2>Parameters</h2>{[{label:`Rate k (per ${unit=== "hours"?"hour":"day"})`,value:k,set:setK,min:-1,max:1,step:.01},{label:`Initial value y₀ (${quantity})`,value:initial,set:setInitial,min:10,max:1000,step:1},{label:`Time window (${unit})`,value:window,set:setWindow,min:1,max:16,step:.5}].map(p=><label className="gd-parameter" key={p.label}><span>{p.label}</span><div><input type="range" aria-label={`${p.label} slider`} min={p.min} max={p.max} step={p.step} value={p.value} onChange={e=>p.set(+e.target.value)}/><input type="number" aria-label={p.label} min={p.min} max={p.max} step={p.step} value={p.value} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=p.min&&n<=p.max)p.set(n);}}/></div><small><span>{p.min}</span><span>{p.value}</span><span>{p.max}</span></small></label>)}</div><div className="gd-state"><h2>State</h2>{[{name:"Growth",text:"Exponential increase",condition:"k > 0",icon:ArrowUpRight},{name:"Constant",text:"No change",condition:"k = 0",icon:Minus},{name:"Decay",text:"Exponential decrease",condition:"k < 0",icon:ArrowDownRight}].map(s=><div key={s.name} className={`${s.name.toLowerCase()} ${model.state===s.name?"selected":""}`}><b>{s.condition}</b><span><strong>{s.name}</strong><small>{s.text}</small></span><s.icon size={18}/></div>)}<p aria-live="polite">Current: <b>{model.state}</b></p></div></aside>
    <div className="gd-main"><div className="gd-graph"><div className="gd-graph-heading"><h3>Solutions of y′ = ky, y(0) = y₀</h3><MathExpression value="y(t)=y_0e^{kt}"/></div><div className="gd-legend"><span className="growth">Growth: k = {Math.abs(k).toFixed(2)}, y₀ = {initial}</span><span className="decay">Decay: k = {k===0?"0":(-Math.abs(k)).toFixed(2)}, y₀ = {initial}</span></div><svg viewBox="0 0 650 630" role="img" aria-label={`Growth and decay comparison, rate magnitude ${Math.abs(k)}, initial ${initial}, time zero to ${window}; linear axes`}>
      {sy.ticks(6).map(t=><g key={t}><path d={`M62 ${sy(t)}H608`} stroke="#edf1f5"/><text x="53" y={sy(t)+4} textAnchor="end">{compact(t)}</text></g>)}{sx.ticks(6).map(t=><g key={t}><path d={`M${sx(t)} 54V590`} stroke="#f0f4f7"/><text x={sx(t)} y="611" textAnchor="middle">{t}</text></g>)}<path d="M62 42V590H620" fill="none" stroke="#233148"/><text x="16" y="26">{symbol}(t)</text><text x="610" y="625">t</text><path d={curve("growth")} stroke="#009aaf" strokeWidth={k>=0?3:1.8} fill="none"/><path d={curve("decay")} stroke="#8a31dd" strokeWidth={k<0?3:1.8} strokeDasharray="7 5" fill="none"/>{markers&&<><circle cx="62" cy={sy(initial)} r="5" fill="#6d35b4"/>{model.markers.map(m=><g key={m.n}><path d={`M${sx(m.t)} ${sy(m.growth)}V${sy(m.decay)}`} stroke="#a5acb8" strokeDasharray="4 4"/><circle cx={sx(m.t)} cy={sy(m.growth)} r="6" fill="#009aaf"><title>{`${m.n===1?"Doubling":"Second doubling"}: t=${m.t.toFixed(3)}, y=${m.growth}`}</title></circle><circle cx={sx(m.t)} cy={sy(m.decay)} r="6" fill="#8a31dd"><title>{`${m.n===1?"Half-life":"Second half-life"}: t=${m.t.toFixed(3)}, y=${m.decay}`}</title></circle></g>)}</>}
    </svg><div className="gd-marker-values">{markers&&(model.interval===null?<span>k = 0: no finite doubling time or half-life.</span>:model.markers.length?model.markers.map(m=><span key={m.n}>t = {m.t.toFixed(2)}: <b className="growth">{compact(m.growth)}</b> / <b className="decay">{compact(m.decay)}</b></span>):<span>First doubling / half-life at {model.interval.toFixed(2)} {unit}, outside this window.</span>)}</div><small className="gd-axis-note">Linear axes · t in {unit} · amount in {quantity}. Both signs are compared; the selected sign is emphasized.</small></div>
    <div className="gd-cases"><article className="growth"><h3>Growth (k &gt; 0)</h3><MathExpression value="y(t)=y_0e^{kt}"/><p>Increases by a constant factor per unit time.</p><MathExpression value="T_D=\frac{\ln 2}{k}"/></article><article><h3>Constant (k = 0)</h3><MathExpression value="y(t)=y_0"/><p>Remains constant.</p><p>No doubling or decay.</p></article><article className="decay"><h3>Decay (k &lt; 0)</h3><MathExpression value="y(t)=y_0e^{kt}"/><p>Decreases by a constant factor per unit time.</p><MathExpression value="T_{1/2}=\frac{\ln 2}{|k|}"/></article></div><div className="gd-preview"><h2>Solution Preview</h2><MathExpression value={`${symbol}(t)=${initial}e^{${k}t},\\quad ${symbol}(0)=${initial}`}/><p>{model.state}: {model.interval===null?"the amount stays constant.":`${k>0?"doubling time":"half-life"} = ${model.interval.toFixed(2)} ${unit}.`}</p></div></div></div></section>
    <section className="gd-learning"><article><h2>Real-World Modes</h2><div className="gd-contexts" role="group" aria-label="Model context">{([{id:"bacteria",name:"Bacteria Population",icon:Sprout,description:"Population with a constant proportional rate; time in hours."},{id:"radioactive",name:"Radioactive Decay",icon:Radiation,description:"Remaining mass with a constant decay rate; time in days."}] as const).map(c=><button key={c.id} aria-pressed={context===c.id} onClick={()=>selectContext(c.id)}><c.icon size={25}/><span><b>{c.name}</b><small>{c.description}</small></span></button>)}</div><p>{context==="radioactive"&&k>=0?"A nonnegative rate is not radioactive decay. This is a mathematical comparison, not a physical radioactive-decay model.":context==="bacteria"&&k<0?"A negative net rate models a decreasing population.":"These idealized models assume a constant proportional rate."}</p><MathExpression value={`${symbol}'=k${symbol},\\quad ${symbol}(0)=${initial}`}/><p>k = proportional rate; y₀ = initial amount.</p></article>
    <article><h2>Worked Example (Current)</h2><MathExpression value={`y'=${k}y,\\quad y(0)=${initial}`}/><h3>Solution</h3><MathExpression value={`y(t)=${initial}e^{${k}t}`} display/><h3>{k>0?"Doubling time":k<0?"Half-life":"Constant amount"}</h3>{model.interval!==null?<MathExpression value={`T=\\frac{\\ln 2}{${Math.abs(k)}}\\approx ${model.interval.toFixed(2)}\\text{ ${unit}}`} display/>:<p>y(t) = {initial} for every t.</p>}<p>{model.interval===null?"No finite doubling time or half-life.":`The amount ${k>0?"doubles":"halves"} every ${model.interval.toFixed(2)} ${unit}.`}</p><div className="gd-table-wrap"><table><tbody><tr><th>t</th>{model.rows.map((r,i)=><td key={i}>{r.t.toFixed(2)}</td>)}</tr><tr><th>y(t)</th>{model.rows.map((r,i)=><td key={i}>{compact(r.y)}</td>)}</tr></tbody></table></div><small>Times displayed rounded; amounts use unrounded times.</small></article>
    <article className="gd-challenge"><h2>Challenge</h2><MathExpression value="y'=-0.4y,\quad y(0)=80"/><p>Find the solution and key decay values.</p><label>1. Write y(t) = A eᵇᵗ<div><input aria-label="Challenge coefficient A" placeholder="A" type="number" value={coefficient} onChange={e=>{setCoefficient(e.target.value);setChecked(false);}}/><input aria-label="Challenge exponent rate b" placeholder="b" type="number" step="any" value={rate} onChange={e=>{setRate(e.target.value);setChecked(false);}}/></div></label><label>2. Half-life (time units)<input aria-label="Challenge half-life" type="number" step="any" value={halfLife} onChange={e=>{setHalfLife(e.target.value);setChecked(false);}}/></label><label>3. Amount after 3 time units<input aria-label="Challenge amount after three" type="number" step="any" value={amount} onChange={e=>{setAmount(e.target.value);setChecked(false);}}/></label><div className="gd-actions"><button onClick={()=>setChecked(true)}><Check size={13}/>Check</button><button onClick={()=>setReveal(v=>!v)}>{reveal?<EyeOff size={13}/>:<Eye size={13}/>}{reveal?"Hide":"Reveal"} solution</button></div>{checked&&<p role="status">{valid.map((v,i)=>`${i+1}: ${v?"Correct":"Try again"}`).join(" · ")}</p>}{reveal&&<div className="gd-answer"><MathExpression value="y(t)=80e^{-0.4t}"/><p>Half-life = ln(2)/0.4 ≈ 1.73.</p><p>y(3) = 80e⁻¹·² ≈ 24.10.</p></div>}</article></section>
    <section className="gd-bottom"><article><h2>Key Takeaways</h2><ul><li>y′ = ky models proportional change.</li><li>The initial condition selects y(t) = y₀eᵏᵗ.</li><li>For y₀ &gt; 0: positive k gives growth, negative k gives decay, and k = 0 is constant.</li><li>Doubling time and half-life depend on k, not the initial amount.</li></ul></article><article><h2>Try These</h2><div className="gd-actions"><button onClick={()=>preset(.5,50)}>k = 0.5, y₀ = 50</button><button onClick={()=>preset(-.2,200)}>k = −0.2, y₀ = 200</button><button onClick={()=>setK(0)}>k = 0</button><button onClick={()=>{let nextK=Math.round((Math.random()*2-1)*100)/100;if(nextK===k)nextK=k===1?-1:Math.round((k+.01)*100)/100;preset(nextK,10+Math.floor(Math.random()*991));}}><Shuffle size={14}/>Randomize</button></div></article></section>
    <nav><Link to="/lessons/advanced-concepts/2017-euler-method"><ArrowLeft size={14}/>Euler Method</Link><Link to="/lessons/advanced-concepts/2019-logistic-differential-equation">Logistic Differential Equation<ArrowRight size={14}/></Link></nav>
  </main>;
}
