import { describe, expect, it } from "vitest";
import { odeMethodComparison } from "../../../studios/calculus/calculusEnhancementEngine";
import { checkGrowthChallenge, growthModel, growthPreset, growthValue } from "./growthDecayModel";
describe("Growth and decay IVPs",()=>{
  it("satisfies the initial condition and ODE for both signs",()=>{for(const k of [-1,-.35,0,.35,1]){expect(growthValue(k,100,0)).toBe(100);for(const t of [0,1,3]){const derivative=(growthValue(k,100,t+.00001)-growthValue(k,100,t-.00001))/.00002;expect(derivative).toBeCloseTo(k*growthValue(k,100,t),5);}expect(growthValue(k,100,2)).toBeCloseTo(odeMethodComparison((_t,y)=>k*y,0,100,2,200).rk4,5);}});
  it("calculates marker times and amounts at the actual exponential coordinates",()=>{const m=growthModel(.35,100,8);expect(m.interval).toBeCloseTo(1.9804205159,9);expect(m.markers).toHaveLength(2);for(const marker of m.markers){expect(marker.growth).toBeCloseTo(growthValue(.35,100,marker.t),12);expect(marker.decay).toBeCloseTo(growthValue(-.35,100,marker.t),12);}expect(m.rows.map(r=>Math.round(r.y))).toEqual([100,200,400,800]);});
  it("keeps half-life independent of initial amount and updates decay table",()=>{const m=growthModel(-.35,100,8);expect(m.interval).toBe(growthModel(-.35,900,8).interval);m.rows.forEach((r,i)=>expect(r.y).toBeCloseTo(100/2**i,12));expect(m.state).toBe("Decay");});
  it("handles constant amounts without infinite marker times",()=>{const m=growthModel(0,150,8);expect(m.interval).toBeNull();expect(m.markers).toEqual([]);expect(m.state).toBe("Constant");expect(m.samples.every(s=>s.growth===150&&s.decay===150)).toBe(true);expect(m.rows.every(r=>r.y===150&&Number.isFinite(r.t))).toBe(true);});
  it("omits off-window markers and keeps every permitted extreme finite",()=>{expect(growthModel(.01,100,16).markers).toHaveLength(0);for(const k of [-1,0,1]){const m=growthModel(k,1000,16);expect(m.samples).toHaveLength(321);expect(m.samples.at(-1)!.t).toBe(16);expect(m.samples.every(s=>Number.isFinite(s.growth)&&Number.isFinite(s.decay)&&s.growth>0&&s.decay>0)).toBe(true);}});
  it("checks the fixed challenge using rounded numeric answers and actual rate",()=>{expect(checkGrowthChallenge("80","-.4","1.73","24.10")).toEqual([true,true,true]);expect(checkGrowthChallenge("80",".4","1.73","24.10")).toEqual([false,true,true]);expect(checkGrowthChallenge("","","","")).toEqual([false,false,false]);expect(checkGrowthChallenge("NaN","Infinity","Infinity","NaN")).toEqual([false,false,false]);});
  it("sets physical context presets with correct signs",()=>{expect(growthPreset("bacteria")).toEqual({k:.35,initial:100,window:8});expect(growthPreset("radioactive").k).toBe(-.35);});
});
