import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6, Eye, Lightbulb, Pause, Play, RotateCcw, TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { DIE_EVENTS, independentEvents, simulateIndependent, URN_COMPARISON, type CoinEvent, type DieEvent, type SimulationStats } from "./independentEventsModel";
import "./IndependentEventsTargetLesson10212.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

const fmt = (n: number) => Number(n.toFixed(3));
const dice = [Dice1, Dice2, Dice3, Dice4, Dice5, Dice6];
export default function IndependentEventsTargetLesson10212({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [coinEvent, setCoinEvent] = useState<CoinEvent>("H"), [dieEvent, setDieEvent] = useState<DieEvent>("even");
  const [coin, setCoin] = useState<"H" | "T">("H"), [die, setDie] = useState(4), [tab, setTab] = useState("Test"), [auto, setAuto] = useState(false);
  const [history, setHistory] = useState<SimulationStats[]>([]), [comparison, setComparison] = useState<"independent" | "dependent">("independent");
  const [answers, setAnswers] = useState<Array<number | null>>([null, null, null]), [solutions, setSolutions] = useState(false);
  const model = independentEvents(coinEvent, dieEvent), DieIcon = dice[die - 1];
  const coinLabel = coinEvent === "either" ? "Heads or Tails" : coinEvent === "H" ? "Heads" : "Tails";
  const append = (batch: SimulationStats) => setHistory(previous => { const last = previous.at(-1) ?? { trials: 0, hits: 0 }; return [...previous, { trials: last.trials + batch.trials, hits: last.hits + batch.hits }].slice(-6); });
  const run = (n: number) => append(simulateIndependent(n, coinEvent, dieEvent));
  useEffect(() => {
    if (!auto) return;
    const timer = window.setInterval(() => {
      const batch = simulateIndependent(100, coinEvent, dieEvent);
      setHistory(previous => { const last = previous.at(-1) ?? { trials: 0, hits: 0 }; return [...previous, { trials: last.trials + batch.trials, hits: last.hits + batch.hits }].slice(-6); });
    }, 500);
    return () => window.clearInterval(timer);
  }, [auto, coinEvent, dieEvent]);
  const reset = () => { setCoinEvent("H"); setDieEvent("even"); setCoin("H"); setDie(4); setAuto(false); setHistory([]); setComparison("independent"); setAnswers([null, null, null]); setSolutions(false); };
  return <main className="ie10212" data-testid="school-mockup-0886"><header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · PROBABILITY</small><h1>{lesson.title}</h1><p>Knowing one event does not change the probability of the other.</p><div className="ie-tags">18 min · ADVANCED · CONCEPT · independence</div></header><nav className="ie-tabs" aria-label="Lesson sections">{["Test", "Outcome Grid", "Simulation", "Rule", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`ie-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}<button onClick={reset}><RotateCcw size={14} />Reset lab</button></nav>
    <section id="ie-Test" className="ie-top"><article><h2>DUAL EXPERIMENT</h2><p>Flip a fair coin and roll a fair six-sided die.<br />Each outcome is equally likely.</p><div className="ie-devices"><div><h3>COIN</h3><span className="ie-coin">{coin}</span><small>Fair coin</small></div><div><h3>DIE</h3><DieIcon size={76} strokeWidth={1.2} /><small>Fair six-sided die</small></div></div><div className="ie-actions"><button onClick={() => setCoin(Math.random() < .5 ? "H" : "T")}>Flip Coin</button><button onClick={() => setDie(1 + Math.floor(Math.random() * 6))}><Dice5 size={15} />Roll Die</button></div><p className="ie-last" aria-live="polite">Last result: <b>{coin === "H" ? "Heads" : "Tails"}</b><DieIcon size={24} /><b>{die}</b></p></article><article><h2>SELECT EVENTS</h2><p>Choose event A from the coin and event B from the die.</p><label className="ie-select">Event A (Coin)<select aria-label="Coin event A" value={coinEvent} onChange={e => { setCoinEvent(e.target.value as CoinEvent); setHistory([]); setAuto(false); }}><option value="H">A = Heads (H)</option><option value="T">A = Tails (T)</option><option value="either">A = Heads or Tails</option></select></label><p className="ie-equation">P(A) = {model.countA}/12 = {fmt(model.pA)}</p><label className="ie-select">Event B (Die)<select aria-label="Die event B" value={dieEvent} onChange={e => { setDieEvent(e.target.value as DieEvent); setHistory([]); setAuto(false); }}>{Object.entries(DIE_EVENTS).map(([value, event]) => <option key={value} value={value}>B = {event.label}</option>)}</select></label><p className="ie-equation">P(B) = {model.countB}/12 = {fmt(model.pB)}</p></article><article className="ie-summary" aria-live="polite"><h2>PROBABILITY SUMMARY</h2><p className="ie-equation">P(A ∩ B) = {model.countAB}/12 = {fmt(model.pAB)}</p><p className="ie-equation">P(A)P(B) = {fmt(model.pA)} × {fmt(model.pB)} = {fmt(model.pA * model.pB)}</p><p><CheckCircle2 size={18} />P(A ∩ B) = P(A)P(B)</p><strong>Events A and B are independent.</strong><p className="ie-tip"><Lightbulb size={23} />Independence means knowing one event does not change the probability of the other.</p></article></section>
    <section id="ie-Outcome Grid" className="ie-grid-section"><h2>OUTCOME GRID (12 EQUALLY LIKELY OUTCOMES)</h2><div className="ie-grid-scroll"><table><thead><tr><th>Coin (A) / Die (B)</th>{[1, 2, 3, 4, 5, 6].map(n => <th key={n} className={DIE_EVENTS[dieEvent].values.includes(n) ? "ie-event-b" : ""}>{n}{DIE_EVENTS[dieEvent].values.includes(n) ? " (B)" : ""}</th>)}</tr></thead><tbody>{["H", "T"].map(face => <tr key={face}><th>{face} {coinEvent === face || coinEvent === "either" ? "(A)" : "(not A)"}</th>{model.outcomes.filter(p => p.coin === face).map(p => <td key={p.die} className={`${p.inA && p.inB ? "ie-favorable" : ""} ${p.coin === coin && p.die === die ? "ie-current" : ""}`} aria-label={`${p.coin}, ${p.die}${p.inA && p.inB ? ", favorable" : ""}${p.coin === coin && p.die === die ? ", last result" : ""}`}>({p.coin}, {p.die})</td>)}</tr>)}</tbody></table></div><p>Favorable for A ∩ B ({model.countAB} outcomes): {model.outcomes.filter(p => p.inA && p.inB).map(p => `(${p.coin}, ${p.die})`).join(", ")}<span>Total outcomes = 12</span></p></section>
    <section className="ie-live"><article><h2>LIVE INDEPENDENCE CHECK</h2><p>Two equivalent tests must both be true.</p><div><h3><CheckCircle2 size={15} />Test 1: Product rule</h3><p className="ie-equation">P(A ∩ B) = P(A)P(B)<br />{fmt(model.pAB)} = {fmt(model.pA)} × {fmt(model.pB)} = {fmt(model.pA * model.pB)}</p></div><div><h3><CheckCircle2 size={15} />Test 2: Conditioning</h3><p className="ie-equation">P(B | A) = P(B)<br />{fmt(model.conditional)} = {fmt(model.pB)}</p></div></article><article><h2>REVEAL: KNOWING A = {coinLabel.toUpperCase()}</h2><p>Given {coinLabel.toLowerCase()}, the remaining die outcomes are still equally likely.</p><p className="ie-equation">P(B | A) = {model.countAB}/{model.countA} = {fmt(model.conditional)} = P(B)</p><h3>Probability of B ({DIE_EVENTS[dieEvent].label}) on the die</h3>{[{ label: "Before knowing A", value: model.pB }, { label: `After knowing A (${coinLabel})`, value: model.conditional }].map(item => <label className="ie-bar" key={item.label}>{item.label}<progress max="1" value={item.value} /><b>{fmt(item.value)}</b></label>)}<p className="ie-tip">The probability does not change. B is unaffected by A.</p></article></section>
    <section className="ie-sim-compare"><article id="ie-Simulation"><h2>SIMULATION (FREQUENCY OF A ∩ B)</h2><p>Run more trials to see frequencies approach {fmt(model.pAB)}.</p><div className="ie-run">{[1, 100, 1000].map(n => <button key={n} onClick={() => run(n)}>Run {n}</button>)}<button aria-pressed={auto} onClick={() => setAuto(v => !v)}>{auto ? <Pause size={14} /> : <Play size={14} />}{auto ? "Pause" : "Auto"}</button></div><table><thead><tr><th>Trials</th><th>Hits (A ∩ B)</th><th>Frequency</th><th>Expected</th></tr></thead><tbody>{history.length ? history.map(row => <tr key={row.trials}><td>{row.trials}</td><td>{row.hits}</td><td>{(row.hits / row.trials).toFixed(3)}<progress max="1" value={row.hits / row.trials} /></td><td>{fmt(model.pAB)}</td></tr>) : <tr><td colSpan={4}>No trials yet</td></tr>}</tbody></table><p className="ie-tip" aria-live="polite">{history.length ? `${history.at(-1)!.trials} trials; ${history.at(-1)!.hits} favorable outcomes.` : "Theoretical probability is distinct from observed frequency."}</p></article><article><h2>COMPARE: INDEPENDENT vs DEPENDENT</h2><p>Switch the experiment to see how probabilities change.</p><div className="ie-comparison-modes">{(["independent", "dependent"] as const).map(value => <button key={value} aria-pressed={comparison === value} onClick={() => setComparison(value)}>{value === "independent" ? "Independent (Coin & Die)" : "Dependent (2R, 1B balls)"}</button>)}</div>{comparison === "dependent" ? <><p>Urn: 2 red (R) and 1 blue (B). Draw twice without replacement.</p><table><thead><tr><th>Event</th><th>Before any draw</th><th>After first draw is red</th></tr></thead><tbody><tr><td>P(Second is Red)</td><td>2/3 = {fmt(URN_COMPARISON.redBefore)}</td><td>1/2 = {URN_COMPARISON.redAfterRed}</td></tr><tr><td>P(Second is Blue)</td><td>1/3 = {fmt(URN_COMPARISON.blueBefore)}</td><td>1/2 = {URN_COMPARISON.blueAfterRed}</td></tr></tbody></table><p className="ie-dependent">Probabilities change after the first draw. These events are dependent.</p></> : <><p>Fair coin and fair die: separate independent experiments.</p><table><thead><tr><th>Event</th><th>Before knowing A</th><th>After knowing A</th></tr></thead><tbody><tr><td>B: {DIE_EVENTS[dieEvent].label}</td><td>{fmt(model.pB)}</td><td>{fmt(model.conditional)}</td></tr></tbody></table><p className="ie-independent">Knowing {coinLabel.toLowerCase()} does not change the die probabilities.</p></>}</article></section>
    <section id="ie-Rule" className="ie-notes"><article><h2>INDEPENDENCE vs MUTUALLY EXCLUSIVE</h2><div className="ie-distinction"><div><h3>Independent Events</h3><p>Knowing one does not change the probability of the other.</p><p>P(A ∩ B) = P(A)P(B)</p><p>Example: coin and die.</p></div><div><h3>Mutually Exclusive Events</h3><p>Cannot happen at the same time.</p><p>P(A ∩ B) = 0</p><p>For two positive-probability events, this rules out independence.</p></div></div></article><article className="ie-mistake"><h2><TriangleAlert size={17} />COMMON MISCONCEPTION</h2><p>Do not confuse independence with mutual exclusivity.</p><p>Rolling a die: A = Even, B = Odd.</p><p>They cannot occur together. P(A ∩ B) = 0, but P(A)P(B) = 1/4. They are not independent!</p></article><article><h2>WORKED EXAMPLE</h2><p>A box has 5 red and 7 blue balls. Draw twice with replacement. Let A = first red, B = second blue.</p><p className="ie-equation">P(A) = 5/12, P(B) = 7/12<br />P(A ∩ B) = 35/144<br />P(A)P(B) = (5/12)(7/12) = 35/144</p><p>Since P(A ∩ B) = P(A)P(B), A and B are independent.</p></article></section>
    <section id="ie-Practice" className="ie-practice"><div><h2>TRY IT YOURSELF</h2><button aria-expanded={solutions} onClick={() => setSolutions(v => !v)}><Eye size={14} />{solutions ? "Hide" : "Show"} solutions</button></div><div className="ie-questions">{[{ question: "Which pair of events is independent?", options: ["A coin shows Heads and a die shows 5", "Rolling a die: Even and Odd", "Two cards drawn without replacement are both Aces"], correct: [0], explanation: "The coin result does not affect the die." }, { question: "If P(A) = 0.3, P(B) = 0.4 and A, B are independent, what is P(A ∩ B)?", options: ["0.07", "0.12", "0.28", "0.70"], correct: [1], explanation: "0.3 × 0.4 = 0.12." }, { question: "A fair coin and a fair die: A = Heads, B = Even. What is P(B | A)?", options: ["1/6", "1/2", "3/6", "2/3"], correct: [1, 2], explanation: "Both 1/2 and 3/6 are correct: three of the six die faces are even." }].map((item, i) => <fieldset key={item.question}><legend>{i + 1}. {item.question}</legend>{item.options.map((option, j) => <label key={option}><input type="radio" name={`ie-question-${i}`} checked={answers[i] === j} onChange={() => setAnswers(previous => previous.map((v, k) => k === i ? j : v))} />{option}</label>)}{solutions && <p role="status">{answers[i] !== null ? item.correct.includes(answers[i]!) ? "Correct. " : "Try again. " : ""}{item.explanation}</p>}</fieldset>)}</div></section>
    <nav className="ie-next"><Link to="/lessons/school/class-12/class-12-probability-multiplication-rule"><ArrowLeft size={14} />Multiplication Rule</Link><Link to="/lessons/school/class-12/class-12-probability-total-probability-theorem">Total Probability Theorem<ArrowRight size={14} /></Link></nav>
      <LessonTopicStudyBoard lessonId={10212} view={tab} />

  </main>;
}
