import { useRef,useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft,ArrowRight,RotateCcw,Scan,CheckCircle2,Eye,Lightbulb,TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { multipleOptimalModel,EDGE_SAMPLES } from "./multipleOptimalModel";
import "./MultipleOptimalTargetLesson10205.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
const fmt=(n:number)=>Number(n.toFixed(2));
export default function MultipleOptimalTargetLesson10205({lesson}:{lesson:SchoolSyllabusLesson}) {
  const [a,setA]=useState(1),[b,setB]=useState(1),[c,setC]=useState(4),[mode,setMode]=useState<"max"|"min">("max");
  const [grid,setGrid]=useState(true),[zoom,setZoom]=useState(1),[tab,setTab]=useState("Interact"),[answers,setAnswers]=useState(["","",""]),[solution,setSolution]=useState(false);
  const dragging=useRef(false),model=multipleOptimalModel(a,b,mode);
  const map=(x:number,y:number)=>[55+x*65*zoom,375-y*65*zoom];
  const objective=b!==0?[[-1,(c+a)/b],[6,(c-6*a)/b]]:a!==0?[[c/a,-1],[c/a,5]]:null;
  const status=model.kind==="region"?"Every feasible point is optimal":model.kind==="edge"?`Infinitely many optimal points on edge ${model.best.map(p=>p.label).join("")}`:`Unique optimum at ${model.best[0].label} (${model.best[0].x}, ${model.best[0].y})`;
  const slider=(name:string,value:number,set:(v:number)=>void,min:number,max:number)=><div className="mo-slider"><label>{name}<input type="number" aria-label={`${name} value`} min={min} max={max} step=".1" value={value} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))set(Math.max(min,Math.min(max,v)));}}/></label><div><span>{min}</span><input type="range" aria-label={name} min={min} max={max} step=".1" value={value} onChange={e=>set(Number(e.target.value))}/><span>{max}</span></div></div>;
  const dragLine=(event:React.PointerEvent<SVGSVGElement>)=>{if(!dragging.current)return;const matrix=event.currentTarget.getScreenCTM();if(!matrix)return;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());const x=(p.x-55)/(65*zoom),y=(375-p.y)/(65*zoom);setC(Math.max(-10,Math.min(10,Math.round((a*x+b*y)*10)/10)));};
  return <main className="mo10205" data-testid="school-mockup-0879"><header><Link to="/lessons/school/class-12"><ArrowLeft size={14}/>School lessons</Link><small>CLASS 12 · LINEAR PROGRAMMING</small><h1>{lesson.title}</h1><p>Explore when a linear objective reaches the same optimal value along a whole feasible edge.</p><div className="mo-tags">18 min · ADVANCED · CONCEPT · Graph & Optimization</div></header>
    <nav className="mo-tabs">{["Interact","Learn","Example","Rule","Practice"].map(name=><button key={name} aria-current={tab===name?"location":undefined} onClick={()=>{setTab(name);document.getElementById(`mo-${name}`)?.scrollIntoView({behavior:"smooth"});}}>{name}</button>)}</nav>
    <section id="mo-Interact" className="mo-workspace"><div className="mo-graph-panel"><h2>FEASIBLE REGION</h2><label><select aria-label="Optimization mode" value={mode} onChange={e=>setMode(e.target.value as "max"|"min")}><option value="max">Maximize</option><option value="min">Minimize</option></select> Z = {a}x + {b}y</label>
      <svg viewBox="0 0 430 430" className="mo-graph" role="img" aria-label="Triangle and movable objective line" onPointerMove={dragLine} onPointerUp={event=>{dragging.current=false;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}} onPointerCancel={()=>{dragging.current=false;}}>
        {grid&&Array.from({length:7},(_,i)=>i).map(n=><path key={n} d={`M${map(n,0)[0]} 20V405 M20 ${map(0,n)[1]}H420`} stroke="#e9edf4" strokeDasharray="2 2"/>)}
        <polygon points={[[0,0],[4,0],[0,4]].map(p=>map(p[0],p[1]).join(",")).join(" ")} fill="#88c3ef" opacity=".5" stroke="#2678bc"/>
        <path d="M55 12V402 M15 375H420" fill="none" stroke="#22323e"/>
        {Array.from({length:6},(_,i)=>i).map(n=><g key={n}><text x={map(n,0)[0]-3} y="392">{n}</text><text x="35" y={map(0,n)[1]+3}>{n}</text></g>)}
        {model.kind==="edge"&&<line x1={map(model.best[0].x,model.best[0].y)[0]} y1={map(model.best[0].x,model.best[0].y)[1]} x2={map(model.best[1].x,model.best[1].y)[0]} y2={map(model.best[1].x,model.best[1].y)[1]} stroke="#efa51b" strokeWidth="5"/>}
        {objective&&<g onPointerDown={event=>{dragging.current=true;event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId);event.preventDefault();}} style={{cursor:"grab"}}><line x1={map(objective[0][0],objective[0][1])[0]} y1={map(objective[0][0],objective[0][1])[1]} x2={map(objective[1][0],objective[1][1])[0]} y2={map(objective[1][0],objective[1][1])[1]} stroke="transparent" strokeWidth="18"/><line x1={map(objective[0][0],objective[0][1])[0]} y1={map(objective[0][0],objective[0][1])[1]} x2={map(objective[1][0],objective[1][1])[0]} y2={map(objective[1][0],objective[1][1])[1]} stroke="#1684ef" strokeDasharray="6 4" strokeWidth="2"/></g>}
        {EDGE_SAMPLES.map(p=><g key={p.label}><circle cx={map(p.x,p.y)[0]} cy={map(p.x,p.y)[1]} r="5" fill="#4766e8"/><text x={map(p.x,p.y)[0]+7} y={map(p.x,p.y)[1]-8}>{p.label} ({p.x}, {p.y})</text></g>)}
        <text x="95" y="290">Feasible region</text><text x="110" y="310">x + y ≤ 4</text><text x="105" y="330">x ≥ 0, y ≥ 0</text>
      </svg><div className="mo-tools"><button onClick={()=>{setZoom(1);setC(4);}}><RotateCcw size={14}/>Reset view</button><button onClick={()=>setZoom(1.15)}><Scan size={14}/>Zoom fit</button><label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>Show grid</label></div>
    </div><aside><section><h2>OBJECTIVE FUNCTION Z = ax + by</h2>{slider("a (coefficient of x)",a,setA,-5,5)}{slider("b (coefficient of y)",b,setB,-5,5)}{slider("Objective position c",c,setC,-10,10)}</section><section><h2>SLOPE COMPARISON</h2><p>Objective line slope: {a===0&&b===0?"Undefined (constant objective)":model.slope===null?"Vertical":fmt(model.slope)}</p><p>Edge AB slope: −1</p></section><section className="mo-status" aria-live="polite"><h2>STATUS</h2><CheckCircle2 size={26}/><strong>{status}</strong><p>{mode==="max"?"Maximum":"Minimum"} Z = {fmt(model.value)}</p></section><section><h3>Try changing ‘a’</h3><button onClick={()=>{setA(2);setB(1);setMode("max");}}>a = 2, b = 1</button></section></aside></section>
    <section className="mo-samples"><h2>SAMPLE POINTS ON EDGE AB (x + y = 4)</h2><div>{model.samples.map(p=><article key={p.label}><h3>{p.label} ({p.x}, {p.y})</h3><p>Z = {a}({p.x}) + {b}({p.y})</p><strong>Z = {fmt(p.value)}</strong></article>)}</div></section>
    <section id="mo-Example" className="mo-comparison"><h2>ONE POINT VS WHOLE EDGE</h2><div><article><h3>Case 1: a = b = 1 (maximization)</h3><p>Every point on AB gives Z = 4.</p><button onClick={()=>{setA(1);setB(1);setMode("max");setC(4);}}>Explore whole edge</button></article><article><h3>Case 2: a = 2, b = 1</h3><p>Maximum Z = 8 at A(4, 0).</p><button onClick={()=>{setA(2);setB(1);setMode("max");setC(8);}}>Explore unique optimum</button></article></div></section>
    <section id="mo-Learn" className="mo-notes"><article id="mo-Rule"><h2><Lightbulb size={18}/>KEY RULE</h2><p>When an objective attains its optimum at both ends of an edge, every point on that edge is optimal. Parallel slopes alone do not tell you which side is optimal.</p></article><article><h2><TriangleAlert size={18}/>COMMON MISCONCEPTION</h2><p>Not only corner points can be optimal. For a zero objective, the entire feasible region is optimal.</p></article></section>
    <section id="mo-Practice" className="mo-practice"><h2>CHECK YOUR UNDERSTANDING</h2><p>Maximize each objective over x ≥ 0, y ≥ 0, x + y ≤ 4.</p>{["x + y","2x + y","−x + 2y"].map((expression,i)=><fieldset key={i}><legend>Z = {expression}</legend>{["Whole edge AB","Single point"].map(option=><label key={option}><input type="radio" name={`multiple-practice-${i}`} checked={answers[i]===option} onChange={()=>setAnswers(previous=>previous.map((v,j)=>i===j?option:v))}/>{option}</label>)}{answers[i]&&<strong>{answers[i]===(i===0?"Whole edge AB":"Single point")?"✓":"Try again"}</strong>}</fieldset>)}<button onClick={()=>setSolution(v=>!v)} aria-expanded={solution}><Eye size={14}/>Show Solution</button>{solution&&<p role="status">1: Edge AB, Z = 4. 2: A(4,0), Z = 8. 3: B(0,4), Z = 8.</p>}</section>
    <nav className="mo-next"><Link to="/lessons/school/class-12/class-12-linear-programming-unbounded-feasible-region"><ArrowLeft size={14}/>Previous: Unbounded Feasible Region</Link><Link to="/lessons/school/class-12/class-12-linear-programming-infeasible-problems">Next: Infeasible Problems<ArrowRight size={14}/></Link></nav>
      <LessonTopicStudyBoard lessonId={10205} view={tab} />

  </main>;
}
