import { useEffect, useId, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { scaleLinear } from "d3";
import { ArrowLeft,ArrowRight,CheckCircle2,FlaskConical,Lightbulb,Pause,Play,RotateCcw } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { checkOscillatorPractice,oscillatorSamples,oscillatorState,oscillatorSummary } from "./oscillatorLessonModel";
import "./OscillatorTargetLesson2020.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
const colors={x:"#009fc3",v:"#f18b09",a:"#8f3de0"};
export default function OscillatorTargetLesson2020({lesson}:{lesson:AdvancedConceptLesson}) {
  const [omega,setOmega]=useState(2),[x0,setX0]=useState(1),[v0,setV0]=useState(0),[rawTime,setTime]=useState(Math.PI/6),[playing,setPlaying]=useState(false),[damping,setDamping]=useState(false),[zeta,setZeta]=useState(.1),[responses,setResponses]=useState(["","",""]),[checked,setChecked]=useState(false);
  const parameters=useMemo(()=>({omega,x0,v0}),[omega,x0,v0]),summary=oscillatorSummary(parameters),duration=2*summary.period,t=Math.min(rawTime,duration),state=oscillatorState(parameters,t),damped=oscillatorState(parameters,t,zeta),samples=useMemo(()=>oscillatorSamples(parameters),[parameters]),dampedSamples=useMemo(()=>oscillatorSamples(parameters,zeta),[parameters,zeta]),clip=useId();
  useEffect(()=>{if(!playing)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=(now-last)/1000;last=now;setTime(old=>(Math.min(old,duration)+dt)%duration);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,duration]);
  const sx=scaleLinear().domain([0,duration]).range([40,610]),amp=Math.max(summary.amplitude,.25),phaseX=scaleLinear().domain([-amp*1.15,amp*1.15]).range([35,315]),phaseY=scaleLinear().domain([-amp*omega*1.15,amp*omega*1.15]).range([220,20]),positionScale=scaleLinear().domain([-amp*1.2,amp*1.2]).range([175,465]),massX=positionScale(state.x),valid=checkOscillatorPractice(...responses as [string,string,string]);
  const spring=(end:number)=>`M32 90H55 ${Array.from({length:22},(_,i)=>`L${55+(end-55)*i/21} ${i===21?90:i%2?102:78}`).join(" ")}`;
  function scrub(value:number){setPlaying(false);setTime(Math.max(0,Math.min(duration,value)));}
  function reset(){setOmega(2);setX0(1);setV0(0);setTime(Math.PI/6);setPlaying(false);setDamping(false);setZeta(.1);}
  return <main className="os2020" data-testid="advanced-mockup-0914" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={14}/>Advanced lessons</Link><small>PHASE 1 · DIFFERENTIAL EQUATIONS</small><h1>{lesson.title}</h1><p>Spring–Mass Motion Lab for <MathExpression value="x''+\omega^2x=0"/></p><span>#2020 · 18 min · Advanced · Differential Equations · Oscillation</span></header><section className="os-intro"><div><h2><FlaskConical size={14}/>Interactive Studio</h2><p>Explore simple harmonic motion, energy and phase space.</p></div><Link to={lesson.toolRoute}>Open studio<ArrowRight size={14}/></Link></section>
    <section className="os-lab"><h2>Spring–Mass Motion Lab</h2><div className="os-motion"><aside><article><h3>Equation of Motion</h3><MathExpression value="x''+\omega^2x=0"/></article><article><h3>Current Parameters</h3><p>ω = {omega.toFixed(2)} rad/s</p><p>x(0) = {x0.toFixed(2)} m</p><p>v(0) = {v0.toFixed(2)} m/s</p><small>Mass m = 1 kg; spring k = ω².</small></article><article><h3>Show Damping (optional)</h3><label><input type="checkbox" role="switch" checked={damping} onChange={e=>setDamping(e.target.checked)}/>Compare with damping</label><label>Damping ratio ζ<input type="range" aria-label="Damping ratio" min="0" max="2" step=".05" value={zeta} disabled={!damping} onChange={e=>setZeta(+e.target.value)}/><output>{zeta.toFixed(2)}</output></label>{damping&&<small>{zeta<1?"Underdamped":zeta===1?"Critically damped":"Overdamped"}: x″ + 2ζωx′ + ω²x = 0.</small>}</article></aside>
    <div className="os-spring"><h3>t = {t.toFixed(3)} s</h3><svg viewBox="0 0 520 185" role="img" aria-label={`Mass displacement ${state.x.toFixed(3)} meters`}><defs><pattern id={clip} width="5" height="5" patternUnits="userSpaceOnUse"><path d="M0 5L5 0" stroke="#9ca7b4"/></pattern></defs><rect x="17" y="32" width="15" height="95" fill={`url(#${clip})`}/><path d="M32 125H490" stroke="#aab1bc" strokeWidth="6"/><path d={spring(massX-30)} fill="none" stroke="#4c536a" strokeWidth="2"/><rect x={massX-30} y="59" width="60" height="60" rx="2" fill="#9754ce"/><text x={massX} y="96" textAnchor="middle" className="os-mass-label">m</text><circle cx={massX-21} cy="122" r="6" fill="#596473"/><circle cx={massX+21} cy="122" r="6" fill="#596473"/>{damping&&<rect x={positionScale(damped.x)-30} y="59" width="60" height="60" rx="2" fill="none" stroke="#df407c" strokeWidth="2" strokeDasharray="5 4"/>}<path d="M175 155H465" stroke="#69788c"/>{[-amp,0,amp].map(v=><g key={v}><path d={`M${positionScale(v)} 152v6`} stroke="#69788c"/><text x={positionScale(v)} y="177" textAnchor="middle">{v.toFixed(2)}</text></g>)}<circle cx={massX} cy="155" r="4" fill="#8f3de0"/><text x="480" y="160">x (m)</text></svg><div className="os-insights"><article><h3>Period</h3><MathExpression value={`T=\\frac{2\\pi}{\\omega}=${summary.period.toFixed(3)}\\text{ s}`}/></article><article><h3>Key Insight</h3><p>Undamped acceleration opposes displacement.</p><MathExpression value="a=-\omega^2x"/></article><article><h3>Restoring</h3><p>The spring force points toward equilibrium x = 0.</p></article></div></div><article className="os-instant"><h3>Instantaneous Values</h3>{(["x","v","a"] as const).map(key=><p key={key} style={{color:colors[key]}}>{key}(t) = {state[key].toFixed(3)} {key==="x"?"m":key==="v"?"m/s":"m/s²"}</p>)}{damping&&<small>Dashed pink mass: damped x = {damped.x.toFixed(3)} m.</small>}</article></div>
    <div className="os-graphs">{(["x","v","a"] as const).map((key,index)=>{const scale=Math.max(...samples.map(p=>Math.abs(p[key])),...dampedSamples.map(p=>damping?Math.abs(p[key]):0),.1)*1.15,sy=scaleLinear().domain([-scale,scale]).range([117,13]);return <div className="os-graph-row" key={key}><article><h3 style={{color:colors[key]}}>{["Position x(t)","Velocity v(t)","Acceleration a(t)"][index]}</h3><p>Undamped amplitude = {(summary.amplitude*omega**index).toFixed(2)} {index===0?"m":index===1?"m/s":"m/s²"}</p></article><svg viewBox="0 0 650 150" role="group" aria-label={`${key} versus time; select time`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const m=e.currentTarget.getScreenCTM();if(m)scrub(sx.invert(new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse()).x));}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const m=e.currentTarget.getScreenCTM();if(m)scrub(sx.invert(new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse()).x));}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}><path d={`M40 8V122M40 ${sy(0)}H620`} stroke="#7f8b9b" fill="none"/>{[0,summary.period/2,summary.period,summary.period*1.5,duration].map(tick=><g key={tick}><path d={`M${sx(tick)} 10V120`} stroke="#eaf0f5"/><text x={sx(tick)} y="140" textAnchor="middle">{tick.toFixed(2)}</text></g>)}{[-scale/1.15,0,scale/1.15].map(v=><text key={v} x="32" y={sy(v)+3} textAnchor="end">{v.toFixed(1)}</text>)}<path d={samples.map((p,i)=>`${i?"L":"M"}${sx(p.t)},${sy(p[key])}`).join(" ")} stroke={colors[key]} strokeWidth="2" fill="none"/>{damping&&<path d={dampedSamples.map((p,i)=>`${i?"L":"M"}${sx(p.t)},${sy(p[key])}`).join(" ")} stroke="#db407f" strokeWidth="1.5" strokeDasharray="5 4" fill="none"/>}<path d={`M${sx(t)} 8V122`} stroke="#233044"/><circle cx={sx(t)} cy={sy(state[key])} r="4" fill="#152234"/><text x="625" y="140">t (s)</text></svg>
      <LessonTopicStudyBoard lessonId={2020} alwaysVisible />
</div>;})}<div className="os-time"><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={14}/>:<Play size={14}/>}{playing?"Pause":"Play"}</button><label>Time cursor<input aria-label="Time cursor" type="range" min="0" max={duration} step=".001" value={t} onChange={e=>scrub(+e.target.value)}/></label><output>t = {t.toFixed(3)} s</output>{damping&&<small>Dashed pink: damped comparison</small>}</div></div>
    <div className="os-energy-row"><article><h2>Phase Plane (x, v)</h2><MathExpression value={`x^2+(v/\\omega)^2=${(summary.amplitude**2).toFixed(3)}`}/><svg viewBox="0 0 350 250" role="img" aria-label="Phase trajectory with current position and velocity"><path d={`M20 ${phaseY(0)}H330M${phaseX(0)} 10V230`} stroke="#6c7c90"/><path d={samples.map((p,i)=>`${i?"L":"M"}${phaseX(p.x)},${phaseY(p.v)}`).join(" ")} fill="none" stroke="#009fc3" strokeWidth="2"/>{damping&&<path d={dampedSamples.map((p,i)=>`${i?"L":"M"}${phaseX(p.x)},${phaseY(p.v)}`).join(" ")} fill="none" stroke="#db407f" strokeDasharray="4 3"/>}<circle cx={phaseX(state.x)} cy={phaseY(state.v)} r="4" fill="#14263a"/>{[-amp,amp].map(v=><text key={v} x={phaseX(v)} y={phaseY(0)+16} textAnchor="middle">{v.toFixed(2)}</text>)}<text x="322" y={phaseY(0)-5}>x</text><text x={phaseX(0)+5} y="16">v</text></svg></article><article><h2>Energy Exchange</h2><MathExpression value="KE=\frac12 mv^2,\quad PE=\frac12 kx^2"/><p>Total E = {summary.energy.toFixed(3)} J (constant, undamped).</p>{[{label:"KE",value:state.ke,color:colors.v},{label:"PE",value:state.pe,color:colors.x}].map(e=><div className="os-energy" key={e.label}><b style={{color:e.color}}>{e.label}</b><div role="meter" aria-label={e.label} aria-valuemin={0} aria-valuemax={summary.energy||1} aria-valuenow={e.value}><span style={{width:`${summary.energy?100*e.value/summary.energy:0}%`,background:e.color}}/></div><span>{summary.energy?(100*e.value/summary.energy).toFixed(0):0}%</span></div>)}{damping&&<p>Damped E = {damped.energy.toFixed(3)} J; dissipated = {Math.max(0,summary.energy-damped.energy).toFixed(3)} J.</p>}<div className="os-energy-note"><p>At x = 0: KE is maximum; PE is zero.</p><p>At |x| = A: KE is zero; PE is maximum.</p>{summary.energy===0&&<p>At rest with A = 0, both energies remain zero.</p>}</div></article></div>
    <div className="os-practice-row"><article><h2><Lightbulb size={14}/>Common Misconception</h2><p><b>Speed</b> is greatest at equilibrium, not at maximum displacement.</p><p>At |x| = A, velocity is zero. For undamped motion, a = −ω²x.</p><p>With damping, acceleration also includes −2ζωv; it need not oppose displacement at every instant.</p></article><article><h2>Practice Check</h2><p>For ω = 2, x₀ = 1, v₀ = 0 at t = π/6 s, find the state to three decimals.</p><div className="os-answers">{["x (m)","v (m/s)","a (m/s²)"].map((label,i)=><label key={label}>{label}<input aria-label={`Practice ${label}`} type="number" step="any" value={responses[i]} onChange={e=>{setResponses(old=>old.map((v,j)=>i===j?e.target.value:v));setChecked(false);}}/>{checked&&<small>{valid[i]?"Correct":"Try again"}</small>}</label>)}</div><button onClick={()=>setChecked(true)}>Check</button><button onClick={()=>{reset();}}>Inspect this state</button>{checked&&<p role="status">{valid.every(Boolean)?"Correct: x = 0.500, v = −1.732, a = −2.000.":"Use x = cos(2t), v = −2 sin(2t), and a = −4 cos(2t)."}</p>}</article></div></section>
    <section><h2>Lab Controls</h2><div className="os-controls">{[{name:"ω (rad/s)",value:omega,set:setOmega,min:.5,max:5,step:.05},{name:"x₀ (m)",value:x0,set:setX0,min:-2,max:2,step:.05},{name:"v₀ (m/s)",value:v0,set:setV0,min:-4,max:4,step:.05}].map(p=><label key={p.name}>{p.name}<div><input type="range" aria-label={`${p.name} slider`} min={p.min} max={p.max} step={p.step} value={p.value} onChange={e=>p.set(+e.target.value)}/><input type="number" aria-label={p.name} min={p.min} max={p.max} step={p.step} value={p.value} onChange={e=>{const v=e.target.valueAsNumber;if(Number.isFinite(v)&&v>=p.min&&v<=p.max)p.set(v);}}/></div><small>{p.min} to {p.max}</small></label>)}<button onClick={reset}><RotateCcw size={14}/>Reset to Default</button></div></section>
    <section className="os-bottom"><article><h2>Learn</h2><MathExpression value="x(t)=x_0\cos(\omega t)+\frac{v_0}{\omega}\sin(\omega t)" display/><p>Position and initial velocity select one solution.</p><p>Acceleration is the second derivative of position.</p><p>Undamped mechanical energy is conserved.</p></article><article><h2>Objectives</h2>{["Model undamped spring–mass motion.","Relate position, velocity and acceleration.","Connect the phase plane and energy to motion."].map(text=><p key={text}><CheckCircle2 size={13}/>{text}</p>)}</article><article><h2>Practice</h2><button onClick={()=>{setOmega(3);setX0(1);setV0(0);scrub(0);}}>Inspect ω = 3, x₀ = 1, v₀ = 0</button><p>Compare the period with the default oscillator.</p><button onClick={()=>{setDamping(true);setZeta(.2);}}>Compare damping ζ = 0.20</button><p>Observe the loss of energy and inward phase trajectory.</p></article><article><h2>Search Tags</h2><p>Second-order differential equation · Spring mass · Simple harmonic motion · Energy · Phase plane · Undamped</p></article></section><nav><Link to="/lessons/advanced-concepts/2019-logistic-differential-equation"><ArrowLeft size={14}/>Logistic Differential Equation</Link><Link to="/lessons/advanced-concepts/2021-gamma-function">Gamma Function<ArrowRight size={14}/></Link></nav></main>;
}
