import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight, Pause, Play, RotateCcw, SkipBack, TriangleAlert } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { periodicConvergents, periodicSquareRoot } from "./periodicSquareRootsModel";
import "./PeriodicSquareRootsTargetLesson2005.css";

const gallery = [2, 3, 5, 13, 23], options = Array.from({ length: 99 }, (_, i) => i + 2).filter(n => !Number.isInteger(Math.sqrt(n)));
export default function PeriodicSquareRootsTargetLesson2005({ lesson }: { lesson: AdvancedConceptLesson }) {
  const [n, setN] = useState(23), [step, setStep] = useState(0), [auto, setAuto] = useState(false), [tab, setTab] = useState("Cycle"), [squareN, setSquareN] = useState(25);
  const [answers, setAnswers] = useState<Record<number, number>>({}), [checked, setChecked] = useState([false, false, false, false]);
  const model = periodicSquareRoot(n), convergents = periodicConvergents(n), last = model.states.length - 1, active = model.states[step], states = model.states.slice(1, -1), square = periodicSquareRoot(squareN);
  useEffect(() => { if (!auto) return; const timer = window.setTimeout(() => { if (step < last) setStep(step + 1); else setAuto(false); }, 950); return () => window.clearTimeout(timer); }, [auto, step, last]);
  const select = (index: number) => { setStep(index); setAuto(false); };
  const choose = (value: number) => { setN(value); setStep(0); setAuto(false); };
  const reset = () => { choose(23); setSquareN(25); setAnswers({}); setChecked([false, false, false, false]); };
  const position = (index: number) => { const angle = -Math.PI / 2 + index / states.length * 2 * Math.PI; return { x: 190 + 133 * Math.cos(angle), y: 215 + 155 * Math.sin(angle) }; };
  const colors = ["#00a8ae", "#2285e9", "#e9a529", "#9c51e4"];
  const periodicTex = (value: number) => { const m = periodicSquareRoot(value); return `\\sqrt{${value}}=[${m.a0};\\overline{${m.period.join(",")}}]`; };
  return <main className="ps2005" data-testid="advanced-mockup-0899" data-lesson-viewport="advanced"><header><div><small>PHASE 1 · CONTINUED FRACTIONS</small><h1>{lesson.title}</h1><p>Discover why √N for non-square integers produces periodic continued fractions by tracking repeated quadratic-surd states.</p><div className="ps-tags">#2005 · 18 min · Advanced · Continued Fractions</div></div><aside><Link to="/lessons/advanced-concepts"><ArrowLeft size={13} />Advanced lessons</Link><div><b>For N = {n}</b><p>√{n} ≈ {Math.sqrt(n).toFixed(7)}</p><MathExpression value={periodicTex(n)} /><p>Period length = <strong>{model.period.length}</strong></p></div></aside></header><nav className="ps-tabs" aria-label="Lesson sections">{["Cycle", "State Table", "Convergents", "Patterns", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`ps-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}</nav>
    <section className="ps-main"><div id="ps-Cycle" className="ps-explorer"><div className="ps-section-head"><h2>State Cycle Explorer</h2><label>Choose N (non-square)<select aria-label="Choose non-square N" value={n} onChange={e => choose(+e.target.value)}>{options.map(value => <option key={value}>{value}</option>)}</select></label></div><p>Track quadratic-surd states using the standard recurrence.</p><div className="ps-formula"><b>Recurrence (a₀ = ⌊√N⌋):</b><MathExpression value="m_{k+1}=d_ka_k-m_k,\quad d_{k+1}=\frac{N-m_{k+1}^2}{d_k},\quad a_{k+1}=\left\lfloor\frac{a_0+m_{k+1}}{d_{k+1}}\right\rfloor" /></div><div className="ps-playback"><button disabled={step === 0} onClick={() => select(0)}><SkipBack size={12} />First</button><button disabled={step === 0} onClick={() => select(step - 1)}><ChevronLeft size={12} />Prev</button><button className="ps-primary" disabled={step === last} onClick={() => select(step + 1)}>Step<ChevronRight size={12} /></button><button disabled={step === last && !auto} aria-pressed={auto} onClick={() => setAuto(v => !v)}>{auto ? <Pause size={12} /> : <Play size={12} />}{auto ? "Pause" : "Auto Play"}</button><button onClick={reset}><RotateCcw size={12} />Reset</button><label>Step {step} of {last}<input aria-label="State playback position" type="range" min="0" max={last} value={step} onChange={e => select(+e.target.value)} /></label></div>
      <div className="ps-cycle-table"><article><h2>State cycle (aₖ sequence)</h2><svg viewBox="0 0 380 430" className="ps-cycle" role="group" aria-label={`Periodic state cycle for square root of ${n}`}><defs><marker id="ps-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#71839d" /></marker></defs>{states.map((s, i) => { const start = position(i), end = position((i + 1) % states.length), radius = states.length > 8 ? 25 : 50; if (states.length === 1) return <path key="loop" d="M175 34C100 -5 278 -5 205 34" fill="none" stroke="#71839d" markerEnd="url(#ps-arrow)" />; const dx = end.x - start.x, dy = end.y - start.y, distance = Math.hypot(dx, dy); return <path key={s.k} d={`M${start.x + dx / distance * radius} ${start.y + dy / distance * radius}Q${(start.x + end.x) / 2 + dy / distance * 35} ${(start.y + end.y) / 2 - dx / distance * 35} ${end.x - dx / distance * (radius + 3)} ${end.y - dy / distance * (radius + 3)}`} fill="none" stroke="#71839d" markerEnd="url(#ps-arrow)" />; })}{states.map((s, i) => { const point = position(i), selected = step === s.k || step === last && i === 0, compact = states.length > 8; return <g key={s.k} role="button" tabIndex={0} aria-label={`Select state ${s.k}: m ${s.m}, d ${s.d}, quotient ${s.a}`} aria-pressed={selected} onClick={() => select(s.k)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); select(s.k); } }}><ellipse cx={point.x} cy={point.y} rx={compact ? 20 : 35} ry={compact ? 22 : 48} fill={selected ? "#e9f9ff" : "white"} stroke={colors[i % 4]} strokeWidth={selected ? 3 : 1.5} /><text x={point.x} y={point.y - (compact ? 0 : 16)} textAnchor="middle" className="ps-node-value">{s.a}</text>{!compact && <><text x={point.x} y={point.y + 7} textAnchor="middle">k = {s.k}</text><text x={point.x} y={point.y + 27} textAnchor="middle">({s.m}, {s.d}, {s.a})</text></>}<title>({s.m}, {s.d}, {s.a})</title></g>; })}</svg><div className="ps-cycle-note" aria-live="polite">{step === 0 ? `Initial state: (0, 1, ${model.a0}). The repeating block starts at k = 1.` : `Selected k = ${step}: (${active.m}, ${active.d}, ${active.a}).`}{step === last && " This repeats k = 1: the cycle is complete."}</div><p>Numbers in the circles are aₖ values.</p><p>The state at k = 1 returns at k = {last}, after {model.period.length} transitions.</p></article>
      <article id="ps-State Table"><h2>State table</h2><div className="ps-table-scroll"><table className="ps-state-table"><thead><tr><th>k</th><th>(mₖ, dₖ, aₖ)</th><th>Calculations</th></tr></thead><tbody>{model.states.map((s, i) => { const previous = model.states[i - 1]; return <tr key={i} className={step === i ? "ps-selected" : i === last ? "ps-repeat" : ""}><td><button aria-label={`Select table state ${i}`} onClick={() => select(i)}>k<sub>{i}</sub></button></td><td>({s.m}, {s.d}, {s.a})</td><td>{i === 0 ? <MathExpression value={`a_0=\\lfloor\\sqrt{${n}}\\rfloor=${model.a0}`} /> : <><MathExpression value={`m_${i}=${previous.d}\\cdot${previous.a}-${previous.m}=${s.m}`} /><MathExpression value={`d_${i}=\\frac{${n}-${s.m}^2}{${previous.d}}=${s.d}`} /><MathExpression value={`a_${i}=\\left\\lfloor\\frac{${model.a0}+${s.m}}{${s.d}}\\right\\rfloor=${s.a}`} /></>}</td></tr>; })}</tbody></table></div><p className="ps-repeat-caption">k = {last} matches k = 1 exactly. Period length = {model.period.length}.</p></article></div>
      <div className="ps-tape"><h2>Quotient tape (continued fraction expansion)</h2><MathExpression value={`\\sqrt{${n}}=[${model.a0};${[...model.period, ...model.period].join(",")},\\ldots]=[${model.a0};\\overline{${model.period.join(",")}}]`} /><p>Period length = {model.period.length}.</p></div></div>
    <aside className="ps-sidebar"><article className="ps-square"><h2>Square test (compare)</h2><label>Perfect square N<select aria-label="Perfect square comparison" value={squareN} onChange={e => setSquareN(+e.target.value)}>{[4, 9, 16, 25, 36, 49, 64, 81, 100].map(value => <option key={value}>{value}</option>)}</select></label><table><thead><tr><th>k</th><th>(mₖ, dₖ, aₖ)</th></tr></thead><tbody><tr><td>0</td><td>(0, 1, {square.a0})</td></tr></tbody></table><p>√{squareN} = {square.a0} is already an integer.</p><div className="ps-green">Terminates at [{square.a0}].<br />No cycle (perfect square).<br />No reciprocal step is needed.</div></article><article className="ps-theorem"><h2>Key theorem (insight)</h2><p>Let N be a positive non-square integer and a₀ = ⌊√N⌋.</p><p>The recurrence produces integer states with 0 ≤ m ≤ a₀ and 1 ≤ d ≤ N.</p><p>Only finitely many states occur. Once a state repeats, the deterministic recurrence repeats its future quotients.</p><p>For √N the periodic block starts immediately after a₀.</p></article><article className="ps-warning"><h2><TriangleAlert size={13} />Common misconception</h2><b>Repeating decimals ≠ periodic continued fractions</b><p>√{n} ≈ {Math.sqrt(n).toFixed(9)}… has a nonrepeating decimal expansion.</p><p>Its continued fraction is periodic:</p><MathExpression value={periodicTex(n)} /></article></aside></section>
    <section className="ps-lower"><article id="ps-Convergents"><h2>Convergents of √{n}</h2><p>Rational approximations from prefixes of the continued fraction.</p><div className="ps-table-scroll"><table><thead><tr><th>k</th><th>Prefix</th><th>Convergent pₖ/qₖ</th><th>Decimal</th><th>Absolute error</th><th>Error trend</th></tr></thead><tbody>{convergents.map((c, i) => <tr key={c.k}><td>{c.k}</td><td>[{model.a0}{i ? `; ${convergents.slice(1, i + 1).map(v => v.a).join(", ")}` : ""}]</td><td>{c.p.toString()}/{c.q.toString()}</td><td>{c.decimal.toFixed(8)}</td><td>{c.error.toExponential(5)}</td><td><progress aria-label={`Error at convergent ${i}`} max={convergents[0].error} value={c.error} /></td></tr>)}</tbody></table></div><p className="ps-green">√{n} ≈ {Math.sqrt(n).toPrecision(15)}… (the exact value is irrational)</p></article><article id="ps-Patterns"><h2>Pattern gallery (periods)</h2>{gallery.map(value => <button key={value} aria-label={`Explore square root of ${value}`} aria-pressed={n === value} onClick={() => choose(value)}><MathExpression value={periodicTex(value)} /><span>ℓ = {periodicSquareRoot(value).period.length}</span></button>)}<div className="ps-cycle-note">Period length counts transitions before the first periodic state returns.</div></article></section>
    <section id="ps-Practice" className="ps-practice"><h2>Quick practice (√23)</h2><div>{[{ question: "What is the period length of √23?", options: ["2", "3", "4", "5"], answer: 2 }, { question: "Which quotient starts the period for √23?", options: ["1", "3", "4", "8"], answer: 0 }, { question: "Which is the convergent at index k = 4 for √23?", options: ["19/4", "24/5", "211/44", "43/9"], answer: 2 }, { question: "Which square root terminates at [5]?", options: ["√20", "√24", "√25", "√27"], answer: 2 }].map((q, i) => <article key={q.question}><p>{i + 1}. {q.question}</p>{q.options.map((value, j) => <label key={value}><input type="radio" name={`ps-question-${i}`} checked={answers[i] === j} onChange={() => { setAnswers(old => ({ ...old, [i]: j })); setChecked(old => old.map((v, k) => k === i ? false : v)); }} />{value}</label>)}<button onClick={() => setChecked(old => old.map((v, k) => k === i ? true : v))}>Check Answer</button>{checked[i] && <p role="status">{answers[i] === undefined ? "Choose an answer first." : answers[i] === q.answer ? "Correct." : `Try again. The answer is ${q.options[q.answer]}.`}</p>}</article>)}</div></section><nav className="ps-next"><Link to="/lessons/advanced-concepts/2004-best-rational-approximations"><ArrowLeft size={14} />Best Rational Approximations</Link><Link to="/lessons/advanced-concepts/2006-collatz-conjecture">Collatz Conjecture<ArrowRight size={14} /></Link></nav>
  </main>;
}
