import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Armchair, Box, Check, CheckCircle2, Download, Factory, Minus, Plus, RotateCcw, TriangleAlert, Trophy } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { productionMix, productionPlanning, productionQuantity } from "./productionPlanningModel";
import "./ProductionPlanningTargetLesson10208.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

const model = productionPlanning();
const money = (n: number) => n.toFixed(2);
const xy = (x: number, y: number) => [38 + 35 * x, 328 - 35 * y];
export default function ProductionPlanningTargetLesson10208({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [x, setX] = useState(3.6), [y, setY] = useState(3.6), [whole, setWhole] = useState(false);
  const [tab, setTab] = useState("Plan"), [answer, setAnswer] = useState<number | null>(null), [checked, setChecked] = useState(false);
  const dragging = useRef(false), graph = useRef<SVGSVGElement>(null);
  const mix = productionMix(x, y, whole);
  const change = (a: number, b: number, integer = whole) => { setX(productionQuantity(a, integer)); setY(productionQuantity(b, integer)); };
  const chooseOptimum = (integer: boolean) => { const point = integer ? model.integer : model.continuous; setWhole(integer); change(point.x, point.y, integer); };
  const exportGraph = () => {
    if (!graph.current) return;
    const copy = graph.current.cloneNode(true) as SVGSVGElement;
    copy.setAttribute("xmlns", "http://www.w3.org/2000/svg"); copy.setAttribute("width", "700"); copy.setAttribute("height", "740");
    copy.querySelectorAll("text").forEach(text => { text.setAttribute("font-family", "Arial, sans-serif"); text.setAttribute("font-size", "10"); });
    const url = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)], { type: "image/svg+xml" }));
    const link = document.createElement("a"); link.href = url; link.download = "production-planning.svg"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  const stop = (event: React.PointerEvent<SVGSVGElement>) => { dragging.current = false; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); };
  const examples = [[6, 0], [0, 6], [3.6, 3.6], [3, 4]];
  return <main className="pp10208" data-testid="school-mockup-0882">
    <header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · LINEAR PROGRAMMING</small><h1>{lesson.title}</h1><p>Choose quantities of two products under resource limits to maximize profit.</p><div className="pp-tags">Class 12 · 18 min · ADVANCED · CONCEPT · graph · factory</div></header>
    <nav className="pp-tabs" aria-label="Lesson sections">{["Plan", "Build Model", "Graph", "Compare", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`pp-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}</nav>
    <section className="pp-problem"><div><h2>THE PROBLEM</h2><p>A factory makes tables (x) and chairs (y). Maximize profit subject to limits on wood units and labour hours.</p></div><div><h2>TABLE (x)</h2><p>Wood: 2 units<br />Labour: 3 hours<br />Profit: ₹40</p></div><div><h2>CHAIR (y)</h2><p>Wood: 3 units<br />Labour: 2 hours<br />Profit: ₹50</p></div><div><h2>AVAILABLE RESOURCES</h2><p>Wood units: <b>18</b><br />Labour hours: <b>18</b></p></div></section>
    <section id="pp-Plan" className="pp-workspace"><div className="pp-board"><div className="pp-heading"><h2><Factory size={17} />FACTORY PLANNING BOARD</h2><label className="pp-toggle">Whole products only<input aria-label="Whole products only" type="checkbox" role="switch" checked={whole} onChange={e => { setWhole(e.target.checked); change(x, y, e.target.checked); }} /></label></div><p>Adjust production to see resources, profit, and graph update instantly.</p>
      <div className="pp-products">{[{ name: "Tables", variable: "x", value: x, icon: Box }, { name: "Chairs", variable: "y", value: y, icon: Armchair }].map(({ name, variable, value, icon: Icon }) => {
        const set = (n: number) => variable === "x" ? change(n, y) : change(x, n);
        return <article key={variable} className={`pp-product-${variable}`}><h3><Icon size={23} />{name.toUpperCase()} ({variable})</h3><input type="number" aria-label={`${name} quantity`} min="0" max="6" step={whole ? 1 : .1} value={value} onChange={e => { if (Number.isFinite(e.target.valueAsNumber)) set(e.target.valueAsNumber); }} /><p>{name.toLowerCase()}</p><div className="pp-stepper"><button title={`Decrease ${name}`} aria-label={`Decrease ${name}`} disabled={value === 0} onClick={() => set(value - (whole ? 1 : .1))}><Minus size={14} /></button><input type="range" aria-label={`${name} production`} min="0" max="6" step={whole ? 1 : .1} value={value} onChange={e => set(Number(e.target.value))} /><button title={`Increase ${name}`} aria-label={`Increase ${name}`} disabled={value === 6} onClick={() => set(value + (whole ? 1 : .1))}><Plus size={14} /></button></div><div className="pp-scale"><span>0</span><span>6</span></div><small>Step: {whole ? 1 : .1}</small></article>;
      })}</div>
      <div className="pp-stats" aria-live="polite"><article><h3>EXPECTED PROFIT</h3><strong>₹{money(mix.profit)}</strong><small>= 40({x}) + 50({y})</small></article><article><h3>CURRENT POINT</h3><strong>({x}, {y})</strong><small>{Math.abs(mix.woodLeft) < 1e-8 && Math.abs(mix.labourLeft) < 1e-8 ? "On both constraints" : "Selected production mix"}</small></article><article className={mix.feasible ? "pp-feasible" : "pp-infeasible"}><h3>{mix.feasible ? "FEASIBLE" : "NOT FEASIBLE"}</h3>{mix.feasible ? <CheckCircle2 size={20} /> : <TriangleAlert size={20} />}<small>{mix.feasible ? "Point is inside the feasible region" : "A resource limit is exceeded"}</small></article></div>
      {[{ name: "WOOD UNITS", amount: mix.wood, remaining: mix.woodLeft, equation: "2x + 3y ≤ 18" }, { name: "LABOUR HOURS", amount: mix.labour, remaining: mix.labourLeft, equation: "3x + 2y ≤ 18" }].map((resource, i) => <div className={`pp-resource pp-resource-${i}`} key={resource.name}><label htmlFor={`pp-resource-${i}`}><b>{resource.name}</b><span>Used {money(resource.amount)} / 18</span></label><progress id={`pp-resource-${i}`} max="18" value={Math.min(18, resource.amount)} /><div><span className={resource.remaining < -1e-8 ? "pp-infeasible" : ""}>{resource.remaining >= -1e-8 ? "Remaining" : "Exceeded by"}: {money(Math.abs(resource.remaining))}</span><span>Constraint: {resource.equation}</span></div></div>)}
    </div><div id="pp-Graph" className="pp-graph-panel"><div className="pp-heading"><h2>FEASIBLE REGION GRAPH</h2><div><button title="Reset to continuous optimum" aria-label="Reset to continuous optimum" onClick={() => chooseOptimum(false)}><RotateCcw size={14} /></button><button title="Download graph" aria-label="Download graph" onClick={exportGraph}><Download size={14} /></button></div></div>
      <svg ref={graph} viewBox="0 0 350 370" className="pp-graph" aria-label="Production quantities and resource constraint graph" onPointerMove={event => {
        if (!dragging.current) return; const matrix = event.currentTarget.getScreenCTM(); if (!matrix) return;
        const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse()); change((point.x - 38) / 35, (328 - point.y) / 35);
      }} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={() => { dragging.current = false; }}>
        <defs><clipPath id="pp-clip"><rect x="38" y="48" width="280" height="280" /></clipPath></defs>
        <g clipPath="url(#pp-clip)"><polygon points={model.corners.map(p => xy(p.x, p.y).join(",")).join(" ")} fill="#dff2fc" stroke="#95c6df" />{Array.from({ length: 9 }, (_, i) => <path key={i} d={`M${xy(i, 0)[0]} 48V328 M38 ${xy(0, i)[1]}H318`} stroke="#e3e9f0" strokeDasharray="2 2" />)}<path d={`M${xy(0, 6).join(" ")}L${xy(9, 0).join(" ")}`} stroke="#008dd2" strokeWidth="1.5" /><path d={`M${xy(0, 9).join(" ")}L${xy(6, 0).join(" ")}`} stroke="#7131de" strokeWidth="1.5" />{whole && model.integers.map(p => <circle key={`${p.x}-${p.y}`} cx={xy(p.x, p.y)[0]} cy={xy(p.x, p.y)[1]} r="2" fill="#4d939a" />)}</g>
        <path d="M38 339V43 M35 49L38 43L41 49 M28 328H324 M318 325L324 328L318 331" fill="none" stroke="#253248" />{Array.from({ length: 9 }, (_, i) => <g key={i}><text x={xy(i, 0)[0]} y="343" textAnchor="middle">{i}</text><text x="29" y={xy(0, i)[1] + 3} textAnchor="end">{i}</text></g>)}<text x="20" y="31">y (chairs)</text><text x="298" y="359">x (tables)</text><text x="52" y="76" fill="#7131de">3x + 2y = 18</text><text x="52" y="167" fill="#008dd2">2x + 3y = 18</text>
        {model.corners.filter(p => p.x === 0 || p.y === 0).map(p => <g key={`${p.x}-${p.y}`}><circle cx={xy(p.x, p.y)[0]} cy={xy(p.x, p.y)[1]} r="3" fill="#354b64" /><text x={xy(p.x, p.y)[0] + 6} y={xy(p.x, p.y)[1] - 7}>({p.x}, {p.y})</text></g>)}
        <g role="button" tabIndex={0} aria-label={`Move production point, ${x} tables and ${y} chairs`} className="pp-point" onPointerDown={event => { event.preventDefault(); dragging.current = true; event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId); }} onKeyDown={event => { if (!["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(event.key)) return; event.preventDefault(); const step = whole ? 1 : .1; change(x + (event.key === "ArrowRight" ? step : event.key === "ArrowLeft" ? -step : 0), y + (event.key === "ArrowUp" ? step : event.key === "ArrowDown" ? -step : 0)); }}><circle cx={xy(x, y)[0]} cy={xy(x, y)[1]} r="16" fill="transparent" /><circle cx={xy(x, y)[0]} cy={xy(x, y)[1]} r="5" fill={mix.feasible ? "#172b41" : "#d12d43"} /><rect x={xy(x, y)[0] + 10} y={xy(x, y)[1] - 31} width="68" height="23" rx="4" fill="white" stroke="#a2afbd" /><text x={xy(x, y)[0] + 16} y={xy(x, y)[1] - 16}>({x}, {y})</text></g>
      </svg><div className="pp-legend"><p><i />Feasible region</p><p><i />2x + 3y ≤ 18 (wood)</p><p><i />3x + 2y ≤ 18 (labour)</p></div><p className="pp-corners">Corner points: {model.corners.map(p => `(${p.x}, ${p.y})`).join(", ")}</p>
    </div></section>
    <section id="pp-Compare" className="pp-compare"><div><h2>RESOURCE USAGE AT CORNER POINTS</h2><table><thead><tr><th>Corner<br />(x, y)</th><th>Wood<br />2x + 3y</th><th>Labour<br />3x + 2y</th><th>Feasible?</th><th>Profit<br />40x + 50y</th></tr></thead><tbody>{model.corners.map(p => <tr key={`${p.x}-${p.y}`} className={p.profit === model.continuous.profit ? "pp-best" : ""}><td>({p.x}, {p.y})</td><td>{p.wood}</td><td>{p.labour}</td><td><CheckCircle2 size={14} aria-label="Yes" /></td><td>{p.profit}</td></tr>)}</tbody></table><p>Continuous optimum at ({model.continuous.x}, {model.continuous.y}) with maximum profit ₹{model.continuous.profit}.</p></div><div><h2>OPTIMAL PRODUCTION &amp; PROFIT</h2><div className="pp-optima">{[false, true].map(integer => { const p = integer ? model.integer : model.continuous; return <article key={String(integer)}><h3><Trophy size={17} />{integer ? "WHOLE PRODUCTS ONLY" : "CONTINUOUS SOLUTION"}</h3><small>{integer ? "Whole numbers only" : "Real numbers allowed"}</small><p>x = <b>{p.x}</b> tables<br />y = <b>{p.y}</b> chairs<br />Profit = <strong>₹{money(p.profit)}</strong></p><hr /><p>Wood used: {p.wood} / 18<br />Labour used: {p.labour} / 18</p><p>Wood left: {p.woodLeft}; Labour left: {p.labourLeft}</p><button onClick={() => chooseOptimum(integer)}>OPTIMAL ({integer ? "integer" : "continuous"})</button></article>; })}</div></div></section>
    <section id="pp-Build Model" className="pp-notes"><article><h2>TRANSLATE DATA TO MODEL</h2><ol><li><b>Define decision variables:</b><br />x = tables to make, y = chairs to make.</li><li><b>Write resource constraints:</b><br />Wood: 2x + 3y ≤ 18<br />Labour: 3x + 2y ≤ 18</li><li><b>Non-negativity:</b><br />x ≥ 0, y ≥ 0</li><li><b>Objective (maximize profit):</b><br />Maximize P = 40x + 50y</li></ol></article><article className="pp-misconception"><h2><TriangleAlert size={17} />COMMON MISCONCEPTION</h2><p>Don’t pick the point with the highest profit first. Always check resource limits before profit.</p><div><b>Wrong:</b> Choose (6, 6) for profit ₹540<p>Wood: 2(6) + 3(6) = 30 × Exceeds 18<br />Labour: 3(6) + 2(6) = 30 × Exceeds 18</p><button onClick={() => change(6, 6)}>Inspect (6, 6)</button></div><p className="pp-feasible">Right: Check feasible region → then profit <Check size={14} /></p></article><article><h2>WHY THE OPTIMUM IS AT (3.6, 3.6)</h2><p>The maximum of a linear objective over this bounded region occurs at a corner.</p><p>(3.6, 3.6) is the intersection of both resource constraints.</p><p>Its profit ₹324 exceeds the other corner profits ₹0, ₹240 and ₹300.</p><p>Thus it gives the maximum feasible continuous profit.</p></article></section>
    <section id="pp-Practice" className="pp-practice"><div><h2>QUICK PRACTICE</h2><p>Maximize P = 40x + 50y</p><p>subject to 2x + 3y ≤ 18, 3x + 2y ≤ 18, x ≥ 0, y ≥ 0. Allow fractional products.</p></div><fieldset><legend>Choose the continuous optimum</legend>{examples.map(([a, b], i) => <label key={i}><input type="radio" name="pp-answer" checked={answer === i} onChange={() => { setAnswer(i); setChecked(false); }} /><b>{String.fromCharCode(65 + i)}</b><span>({a}, {b}), Profit ₹{productionMix(a, b).profit}{i === 3 ? " (integer)" : ""}</span></label>)}</fieldset><button onClick={() => setChecked(true)}><Check size={16} />Check answer</button>{checked && <p role="status">{answer === null ? "Choose a production plan first." : productionMix(...examples[answer] as [number, number]).profit === model.continuous.profit ? "Correct. (3.6, 3.6) is feasible and gives the greatest continuous profit, ₹324." : "This plan is feasible, but does not give the greatest continuous profit. Compare all corner points."}</p>}</section>
    <nav className="pp-next"><Link to="/lessons/school/class-12/class-12-linear-programming-diet-problem"><ArrowLeft size={14} />Diet Problem</Link><Link to="/lessons/school/class-12/class-12-linear-programming-transportation-style-lpp-introduction">Transportation-Style LPP Introduction<ArrowRight size={14} /></Link></nav>
      <LessonTopicStudyBoard lessonId={10208} view={tab} />

  </main>;
}
