import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Dice5, Eye, Info, Pencil, RotateCcw, TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { COIN_OUTCOMES, RANDOM_VARIABLE_RULES, randomVariableGroups, tossMappedCoins, type CoinOutcome, type OutcomeScores } from "./randomVariablesModel";
import "./RandomVariablesTargetLesson10215.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

type RuleName = keyof typeof RANDOM_VARIABLE_RULES | "custom";
export default function RandomVariablesTargetLesson10215({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [rule, setRule] = useState<RuleName>("heads"), [scores, setScores] = useState<OutcomeScores>([2, 1, 1, 0]);
  const [trace, setTrace] = useState<Array<{ outcome: CoinOutcome; value: number }>>([]), [selected, setSelected] = useState<CoinOutcome | null>(null);
  const [tab, setTab] = useState("MAP"), [help, setHelp] = useState(false), [answer, setAnswer] = useState<number | null>(null), [checked, setChecked] = useState(false), [explanation, setExplanation] = useState(false);
  const groups = randomVariableGroups(scores), last = trace.at(-1), title = rule === "custom" ? "X = custom scores" : RANDOM_VARIABLE_RULES[rule].label;
  const setRuleName = (name: RuleName) => { setRule(name); if (name !== "custom") setScores([...RANDOM_VARIABLE_RULES[name].scores]); setTrace([]); setSelected(null); };
  const toss = (count: number) => { const batch = tossMappedCoins(count, scores); setTrace(previous => [...previous, ...batch].slice(-20)); setSelected(batch.at(-1)!.outcome); };
  const reset = () => { setRuleName("heads"); setAnswer(null); setChecked(false); setExplanation(false); setHelp(false); };
  const coinPair = (outcome: CoinOutcome) => <span className="rv-coin-pair">{[...outcome].map((face, i) => <i key={i} className={face === "T" ? "rv-tail" : ""}>{face}</i>)}</span>;
  const selector = (label: string) => <select aria-label={label} value={rule} onChange={e => setRuleName(e.target.value as RuleName)}>{Object.entries(RANDOM_VARIABLE_RULES).map(([name, config]) => <option key={name} value={name}>{config.label}</option>)}<option value="custom">X = custom scores</option></select>;
  return <main className="rv10215" data-testid="school-mockup-0889"><header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · PROBABILITY</small><h1>{lesson.title}</h1><p>A random variable is a rule that assigns a real number to every outcome of a random experiment.</p><div className="rv-tags">18 min · ADVANCED · CONCEPT · mapping · function</div></header><nav className="rv-tabs" aria-label="Lesson sections">{["MAP", "EXPERIMENT", "DEFINITION", "EXAMPLES", "PRACTICE"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`rv-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}<button title="Reset mapping lab" aria-label="Reset mapping lab" onClick={reset}><RotateCcw size={14} /></button></nav>
    <section id="rv-MAP" className="rv-lab"><div className="rv-heading"><div><h2>Mapping Lab: Two Coins</h2><p>Experiment: Toss two fair coins. Define a random variable X.</p></div><button aria-expanded={help} onClick={() => setHelp(v => !v)}><Info size={14} />How it works</button></div>{help && <p className="rv-help">Choose a rule or assign a real-number score to each outcome. Each outcome has probability 1/4, but several outcomes can produce the same value.</p>}
    <div className="rv-map"><article className="rv-outcomes"><h3>All possible outcomes (Ω)</h3><p>Each outcome is equally likely (1/4).</p>{COIN_OUTCOMES.map(outcome => <button key={outcome} aria-pressed={selected === outcome} aria-label={`Inspect outcome ${outcome}`} onClick={() => setSelected(outcome)}>{coinPair(outcome)}<b>{outcome}</b><small>1/4</small></button>)}</article><div className="rv-machine"><h3>The rule (mapping function)</h3><p>Choose or define the rule X.</p>{selector("Mapping rule")}<button onClick={() => { setRuleName("custom"); document.getElementById("rv-score-HH")?.focus(); }}><Pencil size={14} />Customize rule</button><div className="rv-machine-image"><img src="/assets/lessons/random-variable-machine.png" alt="Mapping machine labeled X, Rule" /><ArrowRight className="rv-input-arrow" size={30} /><ArrowRight className="rv-output-arrow" size={30} /></div><p className="rv-equation">X: Ω → ℝ</p><p>Mapping every outcome to a real number.</p>{selected && <output>{selected} → {scores[COIN_OUTCOMES.indexOf(selected)]}</output>}</div><article className="rv-range"><h3>Mapped values (range of X)</h3><p>Outcomes collect by their X value.</p><div className="rv-groups">{groups.map(group => <div key={group.value} className={selected && group.outcomes.includes(selected) ? "rv-selected" : ""}><h4>X = {group.value}<small>{group.outcomes.length} {group.outcomes.length === 1 ? "outcome" : "outcomes"}</small></h4><div>{group.outcomes.map(outcome => <button key={outcome} aria-pressed={selected === outcome} onClick={() => setSelected(outcome)}>{outcome}</button>)}</div></div>)}</div></article></div></section>
    <section id="rv-EXPERIMENT" className="rv-experiment"><div><h2>Try it!</h2><p>Toss to see one outcome and its mapped value.</p><button onClick={() => toss(1)}><Dice5 size={15} />Toss</button><button onClick={() => toss(20)}><Dice5 size={15} />Run 20</button></div><div><h2>Last toss</h2><div className="rv-last" aria-live="polite"><span><small>Outcome</small><b>{last?.outcome ?? "—"}</b></span><ArrowRight size={21} /><span><small>Mapped value</small><b>{last?.value ?? "—"}</b></span></div></div><div><h2>Trace of X (last 20 tosses)</h2><div className="rv-trace">{Array.from({ length: 20 }, (_, i) => <span key={i} title={trace[i] ? `${trace[i].outcome} → ${trace[i].value}` : "No toss yet"}>{trace[i]?.value ?? "—"}</span>)}</div></div></section>
    <section className="rv-domain"><div><h3>Domain (all outcomes)</h3><p className="rv-equation">Ω = {"{HH, HT, TH, TT}"}</p></div><div><h3>Range of X (values that can occur)</h3><p className="rv-equation">X(Ω) = {"{"}{[...groups].reverse().map(g => g.value).join(", ")}{"}"}</p></div></section>
    <section className="rv-editor"><article><h2>Mapping table for {title}</h2><table><thead><tr><th>Outcome ω ∈ Ω</th>{COIN_OUTCOMES.map(outcome => <th key={outcome}>{outcome}</th>)}</tr></thead><tbody><tr><th>X(ω)</th>{scores.map((value, i) => <td key={i}>{value}</td>)}</tr></tbody></table></article><article><h2>Edit or define your own rule</h2><label>Predefined rules{selector("Editor predefined rule")}</label><p>Custom scores (assign any real number)</p><div className="rv-scores">{COIN_OUTCOMES.map((outcome, i) => <label key={outcome}>{outcome}<input id={`rv-score-${outcome}`} aria-label={`Custom score for ${outcome}`} type="number" step="any" value={scores[i]} onChange={e => { const value = e.target.valueAsNumber; if (!Number.isFinite(value)) return; setScores(previous => previous.map((v, j) => i === j ? value : v) as OutcomeScores); setRule("custom"); setTrace([]); setSelected(null); }} /></label>)}</div><p className="rv-valid"><CheckCircle2 size={15} />Valid rule: every outcome has exactly one real value.</p></article></section>
<section className="rv-how"><article><h2>How mapping works (three-step view)</h2><div><section><h3>1 Outcome</h3><p>The experiment produces one outcome from Ω.</p>{coinPair(selected ?? "HT")}</section><ArrowRight size={20} /><section><h3>2 Rule</h3><p>The rule X maps the outcome to a real number.</p><img src="/assets/lessons/random-variable-machine.png" alt="Rule X" /></section><ArrowRight size={20} /><section><h3>3 Number</h3><p>We record the mapped value X(ω) ∈ ℝ.</p><strong>{scores[COIN_OUTCOMES.indexOf(selected ?? "HT")]}</strong></section></div></article><article className="rv-mistake"><h2><TriangleAlert size={17} />Common misconception</h2><p>X is not the coin outcome.</p><p>X(ω) is the number produced by the rule.</p><p>Two different outcomes can map to the same value. The values are real numbers, not necessarily probabilities.</p></article></section>
    <section className="rv-definition"><article id="rv-DEFINITION"><h2>Key idea</h2><p>A random variable is a function that assigns a real number to each outcome.</p><p className="rv-help">Random variable: A function X: Ω → ℝ maps every outcome ω ∈ Ω to exactly one real number X(ω).</p><p>The same value can be assigned to multiple outcomes.</p></article><article id="rv-EXAMPLES"><h2>Worked example</h2><p>One die: Let X = face².</p><table><thead><tr><th>Face</th>{[1, 2, 3, 4, 5, 6].map(n => <th key={n}>{n}</th>)}</tr></thead><tbody><tr><th>X = face²</th>{[1, 2, 3, 4, 5, 6].map(n => <td key={n}>{n * n}</td>)}</tr></tbody></table><p>Domain Ω = {"{1, 2, 3, 4, 5, 6}"}<br />Range X(Ω) = {"{1, 4, 9, 16, 25, 36}"}</p></article></section>
    <section id="rv-PRACTICE" className="rv-practice"><div><h2>Try it yourself</h2><p>Two coins again. Let Y = number of tails.<br />What is Y(HH) + Y(HT) + Y(TH) + Y(TT)?</p><fieldset><legend>Select the sum</legend>{[0, 1, 2, 4].map(value => <label key={value}><input type="radio" name="rv-answer" checked={answer === value} onChange={() => { setAnswer(value); setChecked(false); }} />{value}</label>)}</fieldset></div><div><button onClick={() => setChecked(true)}><CheckCircle2 size={14} />Check answer</button><button aria-expanded={explanation} onClick={() => setExplanation(v => !v)}><Eye size={14} />{explanation ? "Hide" : "Show"} explanation</button></div>{checked && <p role="status">{answer === null ? "Select an answer first." : answer === 4 ? "Correct: 0 + 1 + 1 + 2 = 4." : "Count tails separately in HH, HT, TH and TT, then add those four values."}</p>}{explanation && <p>Y(HH) = 0, Y(HT) = 1, Y(TH) = 1, Y(TT) = 2. Their sum is 4; this is not the expected value, which is 1.</p>}</section>
    <nav className="rv-next"><Link to="/lessons/school/class-12/class-12-probability-bayes-theorem"><ArrowLeft size={14} />Bayes’ Theorem</Link><Link to="/lessons/school/class-12/class-12-probability-probability-distribution-of-a-random-variable">Probability Distribution of a Random Variable<ArrowRight size={14} /></Link></nav>
      <LessonTopicStudyBoard lessonId={10215} view={tab} />

  </main>;
}
