import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Factory, RotateCcw, SlidersHorizontal, TriangleAlert } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { probabilityControl, TOTAL_PRACTICE, totalProbability } from "./totalProbabilityModel";
import "./TotalProbabilityTargetLesson10213.css";

const fmt = (n: number) => Number(n.toFixed(4));
const pct = (n: number) => `${fmt(n * 100)}%`;
export default function TotalProbabilityTargetLesson10213({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [weight, setWeight] = useState(.6), [rate1, setRate1] = useState(.02), [rate2, setRate2] = useState(.05);
  const [tab, setTab] = useState("Explore"), [answers, setAnswers] = useState([false, false, false]);
  const model = totalProbability(weight, rate1, rate2);
  const barMaximum = model.total <= .04 ? .04 : model.total <= .1 ? .1 : model.total <= .25 ? .25 : 1;
  const resetSliders = () => { setWeight(.6); setRate1(.02); setRate2(.05); };
  const control = (label: string, value: number, set: (value: number) => void) => <label className="tp-control"><span>{label}</span><input type="number" aria-label={`${label} value`} min="0" max="1" step=".01" value={fmt(value)} onChange={e => { if (Number.isFinite(e.target.valueAsNumber)) set(probabilityControl(e.target.valueAsNumber)); }} /><b>{pct(value)}</b><input type="range" aria-label={label} min="0" max="1" step=".01" value={value} onChange={e => set(probabilityControl(Number(e.target.value)))} /></label>;
  return <main className="tp10213" data-testid="school-mockup-0887"><header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · PROBABILITY</small><h1>{lesson.title}</h1><p>Sum weighted conditional branches across a complete partition.</p><div className="tp-tags">25–30 min · RIGOROUS · INTERACTIVE · STEP-BY-STEP</div></header><nav className="tp-tabs" aria-label="Lesson sections">{["Explore", "Tree", "Proof", "Example", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`tp-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}<button onClick={() => { resetSliders(); setAnswers([false, false, false]); }}><RotateCcw size={14} />Reset all</button></nav>
    <section id="tp-Explore" className="tp-controls"><article><h2>SOURCE MIX <small>(complete partition)</small></h2>{control("P(M1)", weight, setWeight)}{control("P(M2)", 1 - weight, value => setWeight(probabilityControl(1 - value)))}<p className="tp-valid"><CheckCircle2 size={15} />Partition valid: P(M₁) + P(M₂) = 1.00</p></article><article><h2>DEFECT RATES <small>(conditional probabilities)</small></h2>{control("P(D | M1)", rate1, setRate1)}{control("P(D | M2)", rate2, setRate2)}<div className="tp-complements"><b>Complements:</b><p>P(D̄ | M₁) = {fmt(1 - rate1)}<br />P(D̄ | M₂) = {fmt(1 - rate2)}</p></div></article><article className="tp-result" aria-live="polite"><h2>LIVE RESULT</h2><b>P(D)</b><output>{fmt(model.total)}</output><strong>= {pct(model.total)}</strong><p><CheckCircle2 size={15} />Sum of weighted contributions</p></article></section>
    <section className="tp-visuals"><article><h2>PRODUCTION STREAM <small>(partitioned by source)</small></h2><p>Expected counts out of 100 items</p><div className="tp-stream"><Factory className="tp-factory" size={35} />{model.sources.map((source, i) => <div className={`tp-stream-row tp-source-${i}`} key={i}><div className="tp-source"><h3>M{i + 1}: {fmt(source.expected)} items ({pct(source.share)})</h3><div className="tp-dots" aria-label={`${Math.round(source.expected)} representative items from M${i + 1}`}>{Array.from({ length: Math.round(source.expected) }, (_, n) => <i key={n} />)}</div></div><ArrowRight size={17} /><div className="tp-outputs"><div><b>D</b><strong>{fmt(source.defective * 100)} items</strong><small>({pct(source.rate)})</small></div><div><b>D̄</b><strong>{fmt(source.good * 100)} items</strong><small>({pct(source.complement)})</small></div></div></div>)}</div><div className="tp-stream-totals"><b>Total: 100 items (100%)</b><b>Total defects: {fmt(model.expectedDefects)} items ({pct(model.total)})</b></div></article>
    <article id="tp-Tree"><h2>PROBABILITY TREE</h2><svg className="tp-tree" viewBox="0 0 450 360" role="img" aria-label="Machine source branches, defect outcomes and joint path probabilities"><text x="345" y="25">Path probability</text><circle cx="20" cy="180" r="5" fill="#8467df" />{model.sources.map((source, i) => { const y = i === 0 ? 105 : 270; return <g key={i}><path d={`M20 180L128 ${y}`} stroke="#405168" strokeWidth="2" /><text x="60" y={i ? 246 : 122}>{fmt(source.share)}</text><rect x="128" y={y - 17} width="45" height="34" rx="5" stroke={i ? "#9363eb" : "#4689ff"} fill={i ? "#faf6ff" : "#f4f9ff"} /><text x="150" y={y + 5} textAnchor="middle" fill={i ? "#753bda" : "#146cf4"}>M{i + 1}</text>{[true, false].map((defect, j) => { const leafY = y + (j ? 40 : -40), rate = defect ? source.rate : source.complement, joint = defect ? source.defective : source.good; return <g key={String(defect)}><path d={`M173 ${y}L245 ${leafY}`} stroke="#546478" strokeWidth="1.5" /><text x="190" y={(y + leafY) / 2 - 9}>{fmt(rate)}</text><rect x="245" y={leafY - 16} width="40" height="32" rx="5" fill={defect ? i ? "#faf6ff" : "#f4faff" : "white"} stroke={i ? "#b598ef" : "#82b2fd"} /><text x="265" y={leafY + 5} textAnchor="middle">{defect ? "D" : "D̄"}</text><text x="320" y={leafY - 3} fill={defect ? i ? "#7740d8" : "#086de0" : "#42516a"}>{fmt(source.share)} × {fmt(rate)}</text><text x="345" y={leafY + 15}>= {fmt(joint)}</text></g>; })}</g>; })}</svg><p className="tp-tree-check">Each node’s outgoing probabilities sum to 1.</p><p className="tp-valid"><CheckCircle2 size={14} />M1: {fmt(rate1)} + {fmt(1 - rate1)} = 1 <CheckCircle2 size={14} />M2: {fmt(rate2)} + {fmt(1 - rate2)} = 1</p></article></section>
<section className="tp-contributions"><article><h2>WEIGHTED CONTRIBUTIONS TO D</h2><table><thead><tr><th>Path</th><th>Formula</th><th>Value</th><th>Share of P(D)</th></tr></thead><tbody>{model.sources.map((source, i) => <tr key={i}><td>M{i + 1} → D</td><td>P(M{i + 1})P(D | M{i + 1})</td><td>{fmt(source.defective)}</td><td>{model.contributions[i] === null ? "Undefined" : pct(model.contributions[i]!)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Total P(D)</th><td>{fmt(model.total)}</td><td>{model.total ? "100%" : "Not applicable"}</td></tr></tfoot></table><h3>STACKED CONTRIBUTION BAR (total = {pct(model.total)})</h3><div className="tp-bar" role="img" aria-label={`Defect probability ${pct(model.total)}; first source ${pct(model.sources[0].defective)}, second source ${pct(model.sources[1].defective)}`} style={{ width: `${model.total / barMaximum * 100}%` }}>{model.sources.map((source, i) => <span key={i} style={{ flex: source.defective }} />)}</div><div className="tp-axis">{[0, .25, .5, .75, 1].map(step => <span key={step}>{pct(step * barMaximum)}</span>)}</div><p className="tp-bar-label">P(D) = {pct(model.total)}</p><p className="tp-legend">M1 contribution: {fmt(model.sources[0].defective)} · M2 contribution: {fmt(model.sources[1].defective)}</p></article><article className="tp-theorem"><h2>TOTAL PROBABILITY THEOREM</h2><p>If {"{A₁, A₂, …, Aₙ}"} is a complete partition of S, then for any event B:</p><p className="tp-equation">P(B) = ∑ᵢ P(Aᵢ) P(B | Aᵢ)</p><h3>Partition conditions</h3><div><p>M₁ ∪ M₂ = S<small>(collectively exhaustive)</small><CheckCircle2 size={15} /></p><p>M₁ ∩ M₂ = ∅<small>(mutually exclusive)</small><CheckCircle2 size={15} /></p></div><p>Here, B = D (defective items) and the partition is {"{M₁, M₂}"}.</p><small>For positive-probability partition events. A zero-weight source contributes zero; its supplied defect rate is a model parameter, not a conditional ratio on an observed event.</small></article></section>
    <section className="tp-notes"><article id="tp-Proof"><h2>WHY THE THEOREM WORKS (4-STEP DERIVATION)</h2><ol><li>Since {"{Aᵢ}"} is a partition, B = ⋃ᵢ (B ∩ Aᵢ), a disjoint union.</li><li>The events B ∩ Aᵢ are mutually exclusive.</li><li>Therefore P(B) = ∑ᵢ P(B ∩ Aᵢ).</li><li>By conditional probability, P(B ∩ Aᵢ) = P(Aᵢ)P(B | Aᵢ).</li></ol><p className="tp-equation">Thus P(B) = ∑ᵢ P(Aᵢ)P(B | Aᵢ).</p></article><article id="tp-Example"><h2>WORKED EXAMPLE <small>(Factory scenario)</small></h2><p>A factory’s items come from two machines:</p><p>P(M₁) = 0.60, P(D | M₁) = 0.02<br />P(M₂) = 0.40, P(D | M₂) = 0.05</p><p>Find P(D).</p><p className="tp-equation">P(D) = 0.60 × 0.02 + 0.40 × 0.05<br />= 0.012 + 0.020<br />= 0.032 = 3.2%</p><p className="tp-valid">On average, 3.2 out of every 100 items are defective.</p></article><article className="tp-mistake"><h2><TriangleAlert size={15} />COMMON MISTAKE</h2><p>Do not add raw conditional rates:</p><p className="tp-wrong">P(D | M₁) + P(D | M₂)<br />= 2% + 5% = 7% ×</p><p>These rates apply to different groups. Total probability requires weighting by how often each source occurs.</p><b>Correct approach:</b><p className="tp-equation">P(D) = ∑ P(source) × P(D | source)</p></article></section>
    <section id="tp-Practice" className="tp-practice"><div><h2>QUICK PRACTICE</h2><div className="tp-questions">{TOTAL_PRACTICE.map((item, i) => <article key={item.title}><h3>{i + 1}. {item.title}</h3><p>{item.text}</p><p>Find P({item.event}).</p><button aria-expanded={answers[i]} onClick={() => setAnswers(previous => previous.map((v, j) => j === i ? !v : v))}>{answers[i] ? "Hide" : "Show"} answer</button>{answers[i] && <p role="status">{item.weight} × {item.rate1} + {fmt(1 - item.weight)} × {item.rate2} = {fmt(totalProbability(item.weight, item.rate1, item.rate2).total)} = {pct(totalProbability(item.weight, item.rate1, item.rate2).total)}</p>}</article>)}</div></div><aside><h2>TRY IT YOURSELF</h2><p>Adjust the source mix and defect rates to see P(D) change in real time.</p><SlidersHorizontal size={32} /><button onClick={resetSliders}>Reset sliders</button></aside></section>
    <nav className="tp-next"><Link to="/lessons/school/class-12/class-12-probability-independent-events"><ArrowLeft size={14} />Independent Events</Link><Link to="/lessons/school/class-12/class-12-probability-bayes-theorem">Bayes’ Theorem<ArrowRight size={14} /></Link></nav>
  </main>;
}
