import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, CheckCircle2, ChevronDown, Factory, Info, Minus, Plus, RotateCcw, TriangleAlert, Warehouse } from "lucide-react";
import type { SchoolSyllabusLesson } from "../syllabus/lessonSyllabusTypes";
import { INITIAL_SHIPMENTS, SHIPMENT_COSTS, SHIPMENT_ROUTES, shipmentQuantity, transportationFamily, transportationModel, type Shipments } from "./transportationModel";
import "./TransportationTargetLesson10209.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";

const money = (n: number) => Number(n.toFixed(2));
const variables = ["x₁₁", "x₁₂", "x₂₁", "x₂₂"];
const routes = [
  { path: "M100 100H282", cx: 188, cy: 100, costY: 78 },
  { path: "M100 126C165 126 219 235 282 235", cx: 176, cy: 166, costY: 150 },
  { path: "M100 235C174 235 212 126 282 126", cx: 207, cy: 187, costY: 209 },
  { path: "M100 263H282", cx: 188, cy: 263, costY: 286 },
];
const practiceValues: Shipments = [20, 10, 5, 15];

export default function TransportationTargetLesson10209({ lesson }: { lesson: SchoolSyllabusLesson }) {
  const [values, setValues] = useState<Shipments>([...INITIAL_SHIPMENTS]), [mode, setMode] = useState<"drag" | "steppers">("drag");
  const [t, setT] = useState(25), [tab, setTab] = useState("Route"), [info, setInfo] = useState(false);
  const [answer, setAnswer] = useState<"yes" | "no" | null>(null), [checked, setChecked] = useState(false), [explanation, setExplanation] = useState(false);
  const drag = useRef<{ index: number; start: number; value: number } | null>(null);
  const model = transportationModel(values), practice = transportationModel(practiceValues);
  const familyCurrent = values.every((value, i) => value === transportationFamily(t)[i]);
  const setShipment = (index: number, value: number) => setValues(previous => previous.map((v, i) => i === index ? shipmentQuantity(value) : v) as Shipments);
  const stop = (event: React.PointerEvent<SVGSVGElement>) => { drag.current = null; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); };
  const reset = () => { setValues([...INITIAL_SHIPMENTS]); setT(25); setMode("drag"); setAnswer(null); setChecked(false); setExplanation(false); setInfo(false); };
  return <main className="tr10209" data-testid="school-mockup-0883">
    <header><Link to="/lessons/school/class-12"><ArrowLeft size={14} />School lessons</Link><small>CLASS 12 · LINEAR PROGRAMMING</small><h1>{lesson.title}</h1><p>Learn transportation problems using sources, destinations, shipment variables, row and column constraints, and total transport cost.</p><div className="tr-tags">18 min · ADVANCED · CONCEPT · application · 2 × 2 case</div></header>
    <nav className="tr-tabs" aria-label="Lesson sections">{["Route", "Build Table", "Equations", "Cost", "Practice"].map(name => <button key={name} aria-current={tab === name ? "location" : undefined} onClick={() => { setTab(name); document.getElementById(`tr-${name}`)?.scrollIntoView({ behavior: "smooth" }); }}>{name}</button>)}<button title="Reset shipments" aria-label="Reset shipments" onClick={reset}><RotateCcw size={14} /></button></nav>
    <section className="tr-summary" aria-live="polite"><div><CheckCircle2 size={23} /><span><h2>Balance Check</h2>Supply 50 = Demand 50<strong>Balanced problem</strong></span></div><div><Factory size={23} /><span><h2>Total Supply</h2>50 units<small>F1: 30 · F2: 20</small></span></div><div><Warehouse size={23} /><span><h2>Total Demand</h2>50 units<small>W1: 25 · W2: 25</small></span></div><div>{model.feasible ? <CheckCircle2 size={23} /> : <TriangleAlert size={23} />}<span><h2>Status</h2>{model.feasible ? "Feasible" : "Not feasible"}<small>{model.feasible ? "All constraints satisfied" : "Check row and column totals"}</small></span></div></section>
    <section id="tr-Route" className="tr-workspace"><div className="tr-map-panel"><h2>TRANSPORTATION MAP</h2><div className="tr-cost-info">Per-unit cost (₹)<button title="About shipment costs" aria-label="About shipment costs" onClick={() => setInfo(v => !v)} aria-expanded={info}><Info size={13} /></button></div>{info && <p className="tr-info">Each shipment contributes units × route cost. A balanced problem can still have an infeasible allocation.</p>}
      <svg className="tr-map" viewBox="0 0 382 330" aria-label="Four shipping routes between two factories and two warehouses" onPointerMove={event => {
        if (!drag.current) return; const matrix = event.currentTarget.getScreenCTM(); if (!matrix) return;
        const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse());
        setShipment(drag.current.index, drag.current.value + (point.x - drag.current.start) / 4);
      }} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={() => { drag.current = null; }}>
        <text x="55" y="25" textAnchor="middle" fill="#0768d5">Sources</text><text x="55" y="42" textAnchor="middle">(Rows)</text><text x="330" y="25" textAnchor="middle" fill="#7942dc">Destinations</text><text x="330" y="42" textAnchor="middle">(Columns)</text>
        {routes.map((route, i) => <g key={i}><path d={route.path} fill="none" stroke={values[i] ? "#0876df" : "#a4adbf"} strokeWidth={values[i] ? 2.5 : 1.5} strokeDasharray={values[i] ? undefined : "5 4"} /><text x={route.cx} y={route.costY} textAnchor="middle">₹{SHIPMENT_COSTS[i]}</text></g>)}
        {[{ x: 4, y: 78, title: "Factory F1", amount: "Supply: 30", icon: Factory }, { x: 4, y: 217, title: "Factory F2", amount: "Supply: 20", icon: Factory }, { x: 282, y: 78, title: "Warehouse W1", amount: "Demand: 25", icon: Warehouse }, { x: 282, y: 217, title: "Warehouse W2", amount: "Demand: 25", icon: Warehouse }].map((node, i) => <g key={node.title}><rect x={node.x} y={node.y} width="96" height="75" rx="5" fill={i < 2 ? "#f1f7ff" : "#faf4ff"} stroke={i < 2 ? "#9fc1ff" : "#c9a5ff"} /><foreignObject x={node.x + 7} y={node.y + 26} width="20" height="23"><node.icon size={20} color={i < 2 ? "#0876df" : "#7942dc"} /></foreignObject><text x={node.x + 31} y={node.y + 30} fontSize="9">{node.title}</text><text x={node.x + 31} y={node.y + 48} fontSize="8">{node.amount}</text></g>)}
        {routes.map((route, i) => <g key={i} tabIndex={mode === "drag" ? 0 : undefined} role={mode === "drag" ? "slider" : undefined} aria-label={`${SHIPMENT_ROUTES[i]} shipment`} aria-valuemin={mode === "drag" ? 0 : undefined} aria-valuemax={mode === "drag" ? 50 : undefined} aria-valuenow={mode === "drag" ? values[i] : undefined} className={mode === "drag" ? "tr-drag" : ""} onPointerDown={event => {
          if (mode !== "drag") return; const svg = event.currentTarget.ownerSVGElement, matrix = svg?.getScreenCTM(); if (!svg || !matrix) return;
          event.preventDefault(); const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix.inverse()); drag.current = { index: i, start: point.x, value: values[i] }; svg.setPointerCapture(event.pointerId);
        }} onKeyDown={event => { if (mode !== "drag") return; const n = event.key === "Home" ? 0 : event.key === "End" ? 50 : ["ArrowRight", "ArrowUp"].includes(event.key) ? values[i] + 1 : ["ArrowLeft", "ArrowDown"].includes(event.key) ? values[i] - 1 : null; if (n !== null) { event.preventDefault(); setShipment(i, n); } }}><rect x={route.cx - 18} y={route.cy - 15} width="36" height="30" fill="transparent" /><rect x={route.cx - 14} y={route.cy - 10} width="28" height="20" rx="7" fill={values[i] ? "#176be7" : "#959fb3"} /><text x={route.cx} y={route.cy + 4} textAnchor="middle" fill="white">{values[i]}</text></g>)}
        <path d="M100 315h18" stroke="#0876df" strokeWidth="2" /><text x="124" y="319" fontSize="9">Active shipment</text><path d="M235 315h18" stroke="#a4adbf" strokeDasharray="4 3" /><text x="259" y="319" fontSize="9">Zero shipment</text>
      </svg><div className="tr-map-notes"><h3>How to interact</h3><p>Drag shipment chips horizontally to change units, or use steppers in the table.</p><p>Row totals = Supply · Column totals = Demand</p></div><section className="tr-layout"><h2>UNDERSTAND THE LAYOUT</h2><p><b>Sources</b> (rows) are factories with limited supply.<br /><b>Destinations</b> (columns) are warehouses with demand.</p><p>Ship units along routes. Each route has a per-unit cost.</p><p>Row totals must equal supply. Column totals must equal demand.</p></section>
    </div><div id="tr-Build Table" className="tr-table-panel"><div className="tr-table-heading"><h2>SHIPMENT TABLE <small>(Decision Variables xᵢⱼ)</small></h2><div className="tr-mode" role="group" aria-label="Shipment editing mode">{(["drag", "steppers"] as const).map(value => <button key={value} aria-pressed={mode === value} onClick={() => { drag.current = null; setMode(value); }}>{value === "drag" ? "Drag" : "Steppers"}</button>)}</div></div>
      <table className="tr-shipment-table"><thead><tr><th>To →<br />From ↓</th><th>W1<small>Demand: 25</small></th><th>W2<small>Demand: 25</small></th><th>Row Supply</th></tr></thead><tbody>{[0, 1].map(row => <tr key={row}><th>F{row + 1}<small>Supply: {[30, 20][row]}</small></th>{[0, 1].map(column => { const i = row * 2 + column; return <td key={i}><label htmlFor={`tr-value-${i}`}>{variables[i]}</label><div className="tr-stepper"><button title={`Decrease ${SHIPMENT_ROUTES[i]}`} aria-label={`Decrease ${SHIPMENT_ROUTES[i]}`} disabled={values[i] === 0} onClick={() => setShipment(i, values[i] - 1)}><Minus size={12} /></button><input id={`tr-value-${i}`} aria-label={`${SHIPMENT_ROUTES[i]} units`} type="number" min="0" max="50" step="1" value={values[i]} onChange={e => { if (Number.isFinite(e.target.valueAsNumber)) setShipment(i, e.target.valueAsNumber); }} /><button title={`Increase ${SHIPMENT_ROUTES[i]}`} aria-label={`Increase ${SHIPMENT_ROUTES[i]}`} disabled={values[i] === 50} onClick={() => setShipment(i, values[i] + 1)}><Plus size={12} /></button></div><small>₹{SHIPMENT_COSTS[i]} per unit</small></td>; })}<td className={model.rowValid[row] ? "tr-valid" : "tr-invalid"}><strong>{model.rows[row]}</strong><progress aria-label={`Factory ${row + 1} allocated supply`} max={[30, 20][row]} value={Math.min(model.rows[row], [30, 20][row])} /><small>{model.rows[row]} / {[30, 20][row]} {model.rowValid[row] ? "✓" : "≠"}</small></td></tr>)}</tbody><tfoot><tr><th>Column<br />Demand</th>{[0, 1].map(i => <td key={i} className={model.columnValid[i] ? "tr-valid" : "tr-invalid"}><strong>{model.columns[i]}</strong><progress aria-label={`Warehouse ${i + 1} fulfilled demand`} max="25" value={Math.min(25, model.columns[i])} /><small>{model.columns[i]} / 25 {model.columnValid[i] ? "✓" : "≠"}</small></td>)}<td>Total<br /><b>{model.total}</b></td></tr></tfoot></table>
      <p className="tr-variable">xᵢⱼ = units shipped from source i to destination j</p><div className={`tr-allocation ${model.feasible ? "tr-valid" : "tr-invalid"}`} aria-live="polite">{model.feasible ? <CheckCircle2 size={24} /> : <TriangleAlert size={24} />}<span><b>{model.feasible ? "All row supplies and column demands are satisfied." : "This allocation does not satisfy all constraints."}</b><small>{model.feasible ? "This is a feasible (valid) allocation." : "Check each highlighted row and column total."}</small></span></div>
    </div></section>
    <section className="tr-model-cost"><article id="tr-Equations"><h2>MATHEMATICAL MODEL</h2><p>Let x₁₁, x₁₂, x₂₁, x₂₂ be the shipment variables.</p><h3>Constraints</h3><dl><dt>Row (supply) constraints</dt><dd>x₁₁ + x₁₂ = 30 (F1 supply)<br />x₂₁ + x₂₂ = 20 (F2 supply)</dd><dt>Column (demand) constraints</dt><dd>x₁₁ + x₂₁ = 25 (W1 demand)<br />x₁₂ + x₂₂ = 25 (W2 demand)</dd><dt>Non-negativity</dt><dd>xᵢⱼ ≥ 0 for all i, j</dd></dl><div className="tr-objective"><b>Objective (Minimize Total Cost)</b><p>Minimize C = 4x₁₁ + 6x₁₂ + 5x₂₁ + 3x₂₂</p></div></article><article id="tr-Cost"><h2>COST SUMMARY</h2><div className="tr-cost-breakdown"><div><p>Current Total Cost</p><output aria-live="polite">₹{money(model.cost)}</output></div><div><h3>Cost Breakdown</h3>{SHIPMENT_ROUTES.map((route, i) => <p key={route}>{route}: {values[i]} × ₹{SHIPMENT_COSTS[i]} = ₹{money(model.costs[i])}</p>)}<b>Total = ₹{money(model.cost)}</b></div></div><div className="tr-interpretation"><h3>Interpretation</h3><p>Total transport cost is the sum of units shipped × cost per unit over all routes.</p></div></article></section>
    <section className="tr-family"><div><h2>FEASIBLE ALLOCATIONS <small>(One-Parameter Family)</small></h2><p>Let t = x₁₁. From constraints: x₁₂ = 30 − t, x₂₁ = 25 − t, x₂₂ = t − 5.</p><label>t = x₁₁ <output>{t}</output><input aria-label="Feasible allocation t" type="range" min="5" max="25" step="1" value={t} onChange={e => { const next = Number(e.target.value); setT(next); setValues(transportationFamily(next)); }} /></label><div className="tr-family-scale"><span>5</span><span>25</span></div><div className="tr-family-scale"><b>t = 5 → C = ₹270</b><b>t = 25 → C = ₹190 (Minimum)</b></div>{!familyCurrent && <button onClick={() => setValues(transportationFamily(t))}>Apply family allocation at t = {t}</button>}</div><div><h3>Cost as a function of t</h3><p>C(t) = 4t + 6(30 − t) + 5(25 − t) + 3(t − 5)</p><strong>C(t) = 290 − 4t</strong><p>Since the coefficient of t is −4, cost decreases as t increases. Minimum at t = 25 → minimum cost = ₹190.</p></div></section>
    <section id="tr-Practice" className="tr-practice"><article className="tr-mistake"><h2><TriangleAlert size={15} />COMMON MISTAKE</h2><b>Do not forget column constraints.</b><p>Satisfying only row supplies may leave some warehouses under-served or over-served.</p><div className="tr-mini-tables">{[{ name: "Incorrect (row only)", data: [20, 10, 0, 20] as Shipments }, { name: "Correct (row + column)", data: practiceValues }].map(example => { const result = transportationModel(example.data); return <div key={example.name}><h3>{example.name}</h3><table><thead><tr><th /><th>W1</th><th>W2</th></tr></thead><tbody>{[0, 1].map(i => <tr key={i}><th>F{i + 1}</th><td>{example.data[i * 2]}</td><td>{example.data[i * 2 + 1]}</td></tr>)}</tbody><tfoot><tr><th>Total</th>{result.columns.map((v, i) => <td key={i} className={result.columnValid[i] ? "tr-valid" : "tr-invalid"}>{v} {result.columnValid[i] ? "✓" : "≠ 25"}</td>)}</tr></tfoot></table></div>; })}</div></article><article><h2>TRY IT YOURSELF</h2><p>A new allocation is given below. Check feasibility and find total cost.</p><div className="tr-practice-grid"><table><thead><tr><th /><th>W1</th><th>W2</th><th>Row Supply</th></tr></thead><tbody><tr><th>F1</th><td>20</td><td>10</td><td>30</td></tr><tr><th>F2</th><td>5</td><td>15</td><td>20</td></tr></tbody><tfoot><tr><th>Column Demand</th><td>25</td><td>25</td><td>50</td></tr></tfoot></table><div><fieldset><legend>Is it feasible?</legend>{(["yes", "no"] as const).map(value => <label key={value}><input type="radio" name="tr-practice" checked={answer === value} onChange={() => { setAnswer(value); setChecked(false); }} />{value === "yes" ? "Yes" : "No"}</label>)}</fieldset><button onClick={() => setChecked(true)}>Check Answer</button></div></div>{checked && <p role="status">{answer === null ? "Select Yes or No first." : (answer === "yes") === practice.feasible ? `Correct. Both supplies and demands are satisfied. Total cost = ₹${practice.cost}.` : "Check both row sums (30, 20) and column sums (25, 25). This allocation is feasible."}</p>}<button className="tr-explanation" aria-expanded={explanation} onClick={() => setExplanation(v => !v)}>{explanation ? "Hide" : "Show"} explanation<ChevronDown size={14} /></button>{explanation && <p>20 + 10 = 30, 5 + 15 = 20; 20 + 5 = 25, 10 + 15 = 25. Cost = 20 × 4 + 10 × 6 + 5 × 5 + 15 × 3 = ₹210.</p>}</article></section>
    <nav className="tr-next"><Link to="/lessons/school/class-12/class-12-linear-programming-production-planning-problem"><ArrowLeft size={14} />Previous: Production Planning Problem</Link></nav>
      <LessonTopicStudyBoard lessonId={10209} view={tab} />

  </main>;
}
