import { useState } from "react";
import { Link } from "react-router-dom";
import { scaleLinear } from "d3";
import { ArrowLeft,ArrowRight,CheckCircle2,ClipboardList,UserRound,XCircle } from "lucide-react";
import MathExpression from "../../../components/ui/MathExpression";
import { normalPdf } from "../../../visual-proofs/utils/statisticsMath";
import type { AdvancedConceptLesson } from "../catalog/advanced/advancedConceptLessons";
import { errorPower,errorProbability,errorQuestions,planErrorPower,type PowerTest } from "./errorPowerLessonModel";
import "./TypeErrorsTargetLesson2015.css";
import { LessonTopicStudyBoard } from "../components/LessonTopicStudyBoard";
export default function TypeErrorsTargetLesson2015({lesson}:{lesson:AdvancedConceptLesson}) {
  const [alpha,setAlpha]=useState(.05),[mu1,setMu1]=useState(56),[n,setN]=useState(36),[test,setTest]=useState<PowerTest>("one"),[help,setHelp]=useState(false),[selectedCell,setSelectedCell]=useState(0),[answers,setAnswers]=useState([-1,-1,-1]),[checked,setChecked]=useState(false),[capstone,setCapstone]=useState(false),[targetPower,setTargetPower]=useState(.8),[rationale,setRationale]=useState("");
  const model=errorPower(alpha,mu1,n,test),domain:[number,number]=[50-4.5*model.se,mu1+4.5*model.se],sx=scaleLinear().domain(domain).nice().range([40,585]),sy=scaleLinear().domain([0,normalPdf(50,50,model.se)*1.2]).range([295,65]);
  const values=Array.from({length:501},(_,i)=>domain[0]+(domain[1]-domain[0])*i/500),line=(mean:number,points=values)=>points.map((x,i)=>`${i?"L":"M"}${sx(x)},${sy(normalPdf(x,mean,model.se))}`).join(" ");
  const area=(mean:number,low:number,high:number)=>{const a=Math.max(domain[0],low),b=Math.min(domain[1],high);if(a>=b)return "";return `${line(mean,Array.from({length:151},(_,i)=>a+(b-a)*i/150))}L${sx(b)},295L${sx(a)},295Z`;};
  const alphaRows=[.2,.1,.05,.01,.001].map(a=>errorPower(a,mu1,n,test)),nRows=[12,24,36,50,100].map(size=>errorPower(alpha,mu1,size,test)),cutoffs=test==="two"?[model.lower,model.upper]:[model.upper];
  const cells=[{title:"Type I Error (α)",label:"False positive",text:"Rejecting a true null hypothesis creates a false alarm.",value:alpha},{title:model.alternativeTrue?"Correct Decision (Power)":"Rejection at the null",label:"True positive when an effect exists",text:model.alternativeTrue?"Rejecting a false null detects the specified effect.":"Here μ₁ = μ₀; there is no real effect to detect.",value:model.power},{title:"Correct Decision",label:"True negative",text:"Failing to reject a true null is the correct decision, but does not prove the null.",value:1-alpha},{title:model.alternativeTrue?"Type II Error (β)":"Non-rejection at the null",label:"False negative when an effect exists",text:model.alternativeTrue?"Failing to reject a false null misses the specified effect.":"When μ₁ = μ₀, this is correct non-rejection, not Type II error.",value:model.beta}];
  const planned=planErrorPower(alpha,mu1,test,targetPower);
  return <main className="te2015" data-testid="advanced-mockup-0909" data-lesson-viewport="advanced"><header><Link to="/lessons/advanced-concepts"><ArrowLeft size={13}/>Advanced lessons</Link><small>PHASE 1 · STATISTICAL INFERENCE</small><h1>{lesson.title}</h1><p>See the decision trade-off. At fixed n and true effect, lowering α reduces false positives but raises false negatives.</p><span>#2015 · 17 min · Advanced · Statistical Inference</span></header>
    <section className="te-lab"><div className="te-lab-head"><div><h2>Decision Trade-off Lab</h2><p>Compare Type I error, Type II error and power for independent normal observations with known σ = 6.</p></div><button aria-expanded={help} onClick={()=>setHelp(v=>!v)}>How to read this</button></div>{help&&<aside className="te-help">The blue curve is the distribution of the sample mean under μ₀ = 50; teal uses the specified true mean. Red is rejection under the null (α), yellow is non-rejection at the alternative (β), and teal is power. Areas are conditional probabilities, not posterior probabilities of a hypothesis. <a href="https://online.stat.psu.edu/statprogram/reviews/statistical-concepts/power-analysis" target="_blank" rel="noreferrer">Power analysis reference</a></aside>}
    <div className="te-lab-grid"><div><svg viewBox="0 0 620 385" className="te-chart" role="img" aria-label="Null and alternative sample-mean distributions with computed error and power areas"><text x="155" y="22" textAnchor="middle" className="te-null-label">Null: μ₀ = 50</text><text x="455" y="22" textAnchor="middle" className="te-alt-label">Comparison mean: μ₁ = {mu1.toFixed(2)}</text><text x="155" y="43" textAnchor="middle">Sample-mean SD = {model.se.toFixed(3)}</text><text x="455" y="43" textAnchor="middle">Sample-mean SD = {model.se.toFixed(3)}</text><path d={area(50,-Infinity,Infinity)} fill="#deebff"/><path d={area(mu1,model.lower,model.upper)} fill="#ffe49a"/><path d={area(mu1,model.upper,Infinity)} fill="#a4e2e0"/>{test==="two"&&<path d={area(mu1,-Infinity,model.lower)} fill="#a4e2e0"/>}<path d={area(50,model.upper,Infinity)} fill="#ff9c92" fillOpacity=".8"/>{test==="two"&&<path d={area(50,-Infinity,model.lower)} fill="#ff9c92" fillOpacity=".8"/>}<path d={line(50)} fill="none" stroke="#1678ee" strokeWidth="2"/><path d={line(mu1)} fill="none" stroke="#009ba7" strokeWidth="2"/><path d="M40 65V295H590" stroke="#98a8bd" fill="none"/>{sx.ticks(7).map(t=><text key={t} x={sx(t)} y="315" textAnchor="middle">{t.toFixed(1)}</text>)}{sy.ticks(4).map(t=><text key={t} x="34" y={sy(t)+4} textAnchor="end">{t.toFixed(2)}</text>)}{cutoffs.map((value,i)=><g key={i}><path d={`M${sx(value)} 65V295`} stroke="#757686" strokeDasharray="4 4"/><text x={sx(value)} y={337+i*15} textAnchor="middle">{value.toFixed(3)}</text></g>)}<text x="320" y="378" textAnchor="middle">Sample mean x̄ · dashed lines: critical cutoff(s)</text></svg><div className="te-legend"><span>H₀: μ = 50</span><span>True μ = {mu1.toFixed(2)}</span><span>Critical cutoff</span></div><div className="te-metrics" aria-live="polite">{[{title:"Type I Error (α)",value:errorProbability(alpha),detail:"P(reject H₀ | H₀ true)"},{title:model.alternativeTrue?"Type II Error (β)":"Non-rejection at μ₀",value:errorProbability(model.beta),detail:model.alternativeTrue?"P(fail to reject H₀ | specified H₁)":"No false alternative at μ₁ = μ₀"},{title:model.alternativeTrue?"Power (1 − β)":"Rejection at μ₀",value:errorProbability(model.power),detail:model.alternativeTrue?"P(reject H₀ | specified H₁)":"Equals α, not detection of an effect"},{title:"Standardized separation",value:model.d.toFixed(3),detail:"(μ₁ − μ₀) / SE"}].map(item=><article key={item.title}><h3>{item.title}</h3><strong>{item.value}</strong><p>{item.detail}</p></article>)}</div></div>
    <aside className="te-controls"><h3>Controls</h3>{[{label:"Significance level α",value:alpha,min:.001,max:.2,step:.001,set:setAlpha},{label:"True mean μ₁",value:mu1,min:50,max:60,step:.01,set:setMu1},{label:"Sample size n",value:n,min:10,max:200,step:1,set:setN}].map((control,i)=><label key={control.label}>{control.label}<div><input aria-label={`Drag ${control.label}`} type="range" min={control.min} max={control.max} step={control.step} value={control.value} onChange={e=>control.set(+e.target.value)}/><input aria-label={control.label} type="number" min={control.min} max={control.max} step={control.step} value={control.value} onChange={e=>{const value=+e.target.value;if(Number.isFinite(value)&&value>=control.min&&value<=control.max&&(i!==2||Number.isInteger(value)))control.set(value);}}/></div><small>{control.min} to {control.max}</small></label>)}<h3>Test</h3><div className="te-test-buttons" role="group" aria-label="Test sidedness"><button aria-pressed={test==="one"} onClick={()=>setTest("one")}>One-sided (&gt;)</button><button aria-pressed={test==="two"} onClick={()=>setTest("two")}>Two-sided (≠)</button></div><div className="te-settings"><h3>Current Settings</h3><MathExpression value="H_0:\mu=50"/><MathExpression value={`H_1:\\mu${test==="one"?">":"\\ne"}50`}/><p>σ = 6 (known); n = {n}</p><p>SE = 6 / √{n} = {model.se.toFixed(3)}</p><p>d = ({mu1.toFixed(2)} − 50) / {model.se.toFixed(3)} = {model.d.toFixed(3)}</p><p>z critical = {test==="two"?"±":""}{model.critical.toFixed(3)}</p><p>x̄ cutoff(s): {cutoffs.map(v=>v.toFixed(3)).join(", ")}</p></div></aside></div></section>
    <section className="te-two"><article><h2>Decision Framework</h2><p>{test==="one"?`Reject H₀ when x̄ > ${model.upper.toFixed(3)}.`:`Reject H₀ when x̄ < ${model.lower.toFixed(3)} or x̄ > ${model.upper.toFixed(3)}.`}</p><div className="te-matrix"><span/><b>H₀ true<br/>(μ = 50)</b><b>{model.alternativeTrue?"H₁ true":"Null comparison"}<br/>(μ = {mu1.toFixed(2)})</b><b>Reject H₀</b>{cells.slice(0,2).map((cell,i)=><button key={cell.title} aria-pressed={selectedCell===i} onClick={()=>setSelectedCell(i)}><strong>{cell.title}</strong><small>{cell.label}</small><span>{errorProbability(cell.value)}</span></button>)}<b>Fail to reject H₀</b>{cells.slice(2).map((cell,i)=><button key={cell.title} aria-pressed={selectedCell===i+2} onClick={()=>setSelectedCell(i+2)}><strong>{cell.title}</strong><small>{cell.label}</small><span>{errorProbability(cell.value)}</span></button>)}</div><p className="te-cell-detail" aria-live="polite">{cells[selectedCell].text}</p></article><article><h2><ClipboardList size={18}/>Scenario: Medical Screening</h2><p>A screening test flags a possible disease. This illustrates decision errors, not a diagnostic model or clinical recommendation.</p><p>H₀: disease absent. H₁: disease present.</p><div className="te-scenario"><div><UserRound size={35}/><b>Type I Error (False Positive)</b><p>A healthy person is flagged as potentially having disease.</p></div><div><UserRound size={35}/><b>Type II Error (False Negative)</b><p>A person with disease is missed by the screen.</p></div></div><p>Choosing α balances the consequences of errors. Predictive values also depend on prevalence; α and β alone do not give them.</p></article></section>
    <section className="te-tables"><article><h2>Explore: Lower α → Higher β</h2><p>n and true mean fixed at {n} and {mu1.toFixed(2)}.</p><table><thead><tr><th>α</th><th>z critical</th><th>β / non-rejection</th><th>Power / rejection</th></tr></thead><tbody>{alphaRows.map(row=><tr key={row.alpha} className={Math.abs(alpha-row.alpha)<1e-10?"te-current":""}><td><button onClick={()=>setAlpha(row.alpha)}>{row.alpha}</button></td><td>{test==="two"?"±":""}{row.critical.toFixed(3)}</td><td>{errorProbability(row.beta)}</td><td>{errorProbability(row.power)}</td></tr>)}</tbody></table><p className="te-note">A stricter cutoff reduces false positives but increases misses at a fixed nonzero effect and n.</p></article><article><h2>Explore: Higher n → Higher Power</h2><p>α and true mean fixed at {alpha.toFixed(3)} and {mu1.toFixed(2)}.</p><table><thead><tr><th>n</th><th>SE = σ/√n</th><th>β / non-rejection</th><th>Power / rejection</th></tr></thead><tbody>{nRows.map(row=><tr key={row.n} className={n===row.n?"te-current":""}><td><button onClick={()=>setN(row.n)}>{row.n}</button></td><td>{row.se.toFixed(3)}</td><td>{errorProbability(row.beta)}</td><td>{errorProbability(row.power)}</td></tr>)}</tbody></table><p className="te-note">Larger n narrows the sampling distributions. At zero effect, rejection probability remains α.</p></article></section>
    <section className="te-practice"><h2>Practice</h2><div>{errorQuestions.map((q,i)=><fieldset key={q.question}><legend>{i+1}. {q.question}</legend>{q.options.map((option,j)=><label key={option} className={checked&&answers[i]===j?(q.correct===j?"te-correct":"te-wrong"):""}><input type="radio" name={`te-question-${i}`} checked={answers[i]===j} onChange={()=>{setAnswers(old=>old.map((value,k)=>k===i?j:value));setChecked(false);}}/>{option}</label>)}{checked&&<p>{answers[i]===q.correct?<CheckCircle2 size={14}/>:<XCircle size={14}/>} {q.options[q.correct]}</p>}</fieldset>)}</div><button onClick={()=>setChecked(true)}>Check answers</button>{checked&&<p role="status">{errorQuestions.filter((q,i)=>answers[i]===q.correct).length} / 3 correct.</p>}</section><nav className="te-next"><Link to="/lessons/advanced-concepts/2014-p-values"><ArrowLeft size={14}/>p-Values</Link><Link to="/lessons/advanced-concepts/2016-slope-fields">Slope Fields<ArrowRight size={14}/></Link></nav>
    <section className="te-capstone"><div><h2>Capstone Prompt</h2><p>Plan a study of improved teaching scores. Choose α, target power and sample size, then explain the consequences of both errors.</p></div><button aria-expanded={capstone} onClick={()=>setCapstone(v=>!v)}>{capstone?"Close capstone workspace":"Open capstone workspace"}</button>{capstone&&<div className="te-capstone-workspace"><label>Target power<input aria-label="Capstone target power" type="number" min=".5" max=".99" step=".01" value={targetPower} onChange={e=>{const v=+e.target.value;if(Number.isFinite(v)&&v>=.5&&v<=.99)setTargetPower(v);}}/></label><p>Using current α = {alpha.toFixed(3)}, σ = 6, true mean {mu1.toFixed(2)} and {test==="one"?"one-sided":"two-sided"} test: {planned?`smallest n in 10–200 meeting target is ${planned.n}.`:mu1===50?"No real effect: rejection probability equals α.":"Target not reached for n ≤ 200."}</p>{planned&&<button onClick={()=>setN(planned.n)}>Use n = {planned.n}</button>}<label>Study rationale<textarea aria-label="Capstone study rationale" value={rationale} onChange={e=>setRationale(e.target.value)} rows={4}/></label><small>{rationale.trim().length?"Draft retained while this lesson remains mounted. Reasoning is not automatically graded.":"No rationale entered."}</small></div>}</section>
      <LessonTopicStudyBoard lessonId={2015} alwaysVisible />
</main>;
}
