import {useId,useRef,useState} from 'react';
import {useStudioModel} from '../../phase1/StudioModelProvider';
import {canonicalPoints,circumcircle,format,projection,triangleFromPoints,type Triangle,type Vertex,type Points} from './triangleMath';
export const pairColors={A:'#0864e8',B:'#dc3545',C:'#7948da'};
const vertices:Vertex[]=['A','B','C'];
function arc(o:{x:number;y:number},p:{x:number;y:number},q:{x:number;y:number},r:number){const s=Math.atan2(p.y-o.y,p.x-o.x);let d=Math.atan2(q.y-o.y,q.x-o.x)-s;while(d>Math.PI)d-=2*Math.PI;while(d< -Math.PI)d+=2*Math.PI;return `M ${o.x+r*Math.cos(s)} ${o.y+r*Math.sin(s)} A ${r} ${r} 0 0 ${d>0?1:0} ${o.x+r*Math.cos(s+d)} ${o.y+r*Math.sin(s+d)}`;}
export default function ObliqueTriangle({triangle,alternative,onChange,showValues=true,showAngles=true,showHeight=false,showCircle=false,showAltitudes=false,selected='A',onSelect,unit='units',known=[],highlightSolved=false,construction,apexA=false}: {triangle:Triangle|null;alternative?:Triangle;onChange?:(t:Triangle)=>void;showValues?:boolean;showAngles?:boolean;showHeight?:boolean;showCircle?:boolean;showAltitudes?:boolean;selected?:Vertex;onSelect?:(v:Vertex)=>void;unit?:string;known?:string[];highlightSolved?:boolean;construction?:{A:number;a:number;b:number};apexA?:boolean}){
 const model=useStudioModel();
 const id=useId(),drag=useRef<{vertex:Vertex;points:Points;scale:number;minX:number;minY:number}|null>(null),[notice,setNotice]=useState(''),[custom,setCustom]=useState<{points:Points;triangle:Triangle}|null>(null);
 const same=custom&&triangle&&(['a','b','c','A','B','C'] as const).every(k=>Math.abs(custom.triangle[k]-triangle[k])<1e-7);
 const apex=(t:Triangle):Points=>{const x=(t.c*t.c+t.a*t.a-t.b*t.b)/(2*t.a);return {A:{x,y:-Math.sqrt(Math.max(0,t.c*t.c-x*x))},B:{x:0,y:0},C:{x:t.a,y:0}};};
 const raw=triangle?(same?custom!.points:apexA?apex(triangle):canonicalPoints(triangle)):construction?{A:{x:0,y:0},B:{x:construction.b*Math.cos(construction.A*Math.PI/180),y:0},C:{x:construction.b*Math.cos(construction.A*Math.PI/180),y:-construction.b*Math.sin(construction.A*Math.PI/180)}}:canonicalPoints({a:7,b:8,c:10,A:50,B:60,C:70,area:0});
 const phi=Math.atan2(raw.B.y-raw.A.y,raw.B.x-raw.A.x);
 const other=alternative?Object.fromEntries(Object.entries(canonicalPoints(alternative)).map(([v,p])=>[v,{x:raw.A.x+p.x*Math.cos(phi)-p.y*Math.sin(phi),y:raw.A.y+p.x*Math.sin(phi)+p.y*Math.cos(phi)}])) as Points:null,circle=showCircle&&triangle?circumcircle(raw):null;
 const extent=[...Object.values(raw),...(other?Object.values(other):[])];
 if(circle)extent.push({x:circle.center.x-circle.radius,y:circle.center.y-circle.radius},{x:circle.center.x+circle.radius,y:circle.center.y+circle.radius});
 if(construction){extent.push({x:raw.C.x-construction.a,y:raw.C.y-construction.a},{x:raw.C.x+construction.a,y:raw.C.y+construction.a});}
 const minX=Math.min(...extent.map(p=>p.x)),minY=Math.min(...extent.map(p=>p.y)),width=Math.max(...extent.map(p=>p.x))-minX,height=Math.max(...extent.map(p=>p.y))-minY;
 const scale=Math.min(400/Math.max(width,.001),270/Math.max(height,.001)),ox=50+(400-width*scale)/2,oy=48+(270-height*scale)/2;
 const frame=drag.current;
 const map=(p:{x:number;y:number})=>frame?{x:frame.minX+p.x*frame.scale,y:frame.minY+p.y*frame.scale}:{x:ox+(p.x-minX)*scale,y:oy+(p.y-minY)*scale};
 const pts=Object.fromEntries(vertices.map(v=>[v,map(raw[v])])) as Points;
 const change=(v:Vertex,x:number,y:number,source=raw)=>{const t=triangleFromPoints({...source,[v]:{x,y}});if(t){setCustom({points:{...source,[v]:{x,y}},triangle:t});onChange?.(t);setNotice('');}else setNotice('Keep the vertices apart and off a straight line.');};
 const dsc=triangle?vertices.map(v=>`${v} ${format(triangle[v])} degrees; ${v.toLowerCase()} ${format(triangle[v.toLowerCase() as 'a'|'b'|'c'])}`).join('; '):'No valid triangle for these inputs.';
 return <><svg className="obl-triangle" viewBox="0 0 500 390" aria-label="Interactive oblique triangle" role="group" onPointerMove={e=>{const d=drag.current;if(!d)return;const m=e.currentTarget.getScreenCTM();if(!m)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());change(d.vertex,(pt.x-d.minX)/d.scale,(pt.y-d.minY)/d.scale,d.points);}} onPointerUp={()=>{drag.current=null;setCustom(c=>c?{...c}:null);model?.ledger.endGesture();}} onPointerCancel={()=>{drag.current=null;setCustom(c=>c?{...c}:null);model?.ledger.endGesture();}}><title>{dsc}</title><defs><linearGradient id={id}><stop stopColor="#edf7ff"/><stop offset="1" stopColor="#dcecff"/></linearGradient></defs>
 {construction&&<><line x1={pts.A.x} y1={pts.A.y} x2={pts.A.x+(480-pts.A.x)*Math.cos(phi)} y2={pts.A.y+(480-pts.A.x)*Math.sin(phi)} stroke="#7b95b2" strokeDasharray="5 4"/><circle cx={pts.C.x} cy={pts.C.y} r={construction.a*(frame?.scale??scale)} fill="none" stroke="#9164ce" strokeDasharray="5 5"/><text x="22" y="22" fill="#6a4f9d" fontSize="13">Side a swings about C; B lies on the ray from A.</text></>}
 {circle&&<circle cx={map(circle.center).x} cy={map(circle.center).y} r={circle.radius*(frame?.scale??scale)} fill="none" stroke="#7db8e2" strokeDasharray="6 5"/>}

 {triangle&&<polygon points={vertices.map(v=>`${pts[v].x},${pts[v].y}`).join(' ')} fill={`url(#${id})`}/>}
 {other&&<><polygon points={vertices.map(v=>`${map(other[v]).x},${map(other[v]).y}`).join(' ')} fill="#eee5ff66" stroke="#8052c9" strokeDasharray="7 5" strokeWidth="2"/><text x={map(other.B).x+7} y={map(other.B).y+44} fill="#8052c9">B₂</text></>}
 {(showHeight||showAltitudes)&&triangle&&vertices.filter(v=>showAltitudes||v==='C').map(v=>{const [u,w]=vertices.filter(q=>q!==v),f=map(projection(raw[v],raw[u],raw[w]));return <g key={v}><line x1={pts[v].x} y1={pts[v].y} x2={f.x} y2={f.y} stroke="#50708f" strokeDasharray="5 4"/><path d={`M ${f.x-7} ${f.y} v -7 h 7`} stroke="#50708f" fill="none"/>{v==='C'&&<text className="obl-altitude-label" x={f.x+8} y={(pts[v].y+f.y)/2+24} fill="#3d5777">h{showValues?` = ${format(2*triangle.area/triangle.c)}`:''}</text>}</g>;})}
 {triangle&&vertices.map(v=>{const [u,w]=vertices.filter(q=>q!==v),side=v.toLowerCase() as 'a'|'b'|'c',mid={x:(pts[u].x+pts[w].x)/2,y:(pts[u].y+pts[w].y)/2},center={x:(pts.A.x+pts.B.x+pts.C.x)/3,y:(pts.A.y+pts.B.y+pts.C.y)/3},dx=mid.x-center.x,dy=mid.y-center.y,l=Math.hypot(dx,dy)||1;return <g key={v} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?`Highlight side ${side} and angle ${v}`:undefined} onKeyDown={e=>{if(onSelect&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect(v);}}} onClick={()=>onSelect?.(v)}><line x1={pts[u].x} y1={pts[u].y} x2={pts[w].x} y2={pts[w].y} stroke={selected===v||highlightSolved&&!known.includes(side)?pairColors[v]:'#13253e'} strokeWidth={selected===v?3.5:2.3}/><text className="obl-svg-label" x={mid.x+dx/l*23} y={mid.y+dy/l*23+5} fill={pairColors[v]} textAnchor="middle">{side}{showValues&&triangle?` = ${format(triangle[side])}`:''}</text>{triangle&&<path d={arc(pts[v],pts[u],pts[w],27)} stroke={pairColors[v]} fill="none" strokeWidth="1.6"/>}{showAngles&&triangle&&<text className="obl-svg-angle" x={pts[v].x+(center.x-pts[v].x)*.24} y={pts[v].y+(center.y-pts[v].y)*.24+5} textAnchor="middle" fill={pairColors[v]}>{format(triangle[v],1)}°</text>}</g>;})}
 {!triangle&&construction&&<><line x1={pts.A.x} y1={pts.A.y} x2={pts.C.x} y2={pts.C.y} stroke="#dc3545" strokeWidth="2.5"/><text x={(pts.A.x+pts.C.x)/2-20} y={(pts.A.y+pts.C.y)/2} fill="#dc3545">b = {format(construction.b)}</text><line x1={pts.C.x} y1={pts.C.y} x2={pts.C.x} y2={pts.A.y} stroke="#7893b2" strokeDasharray="4 4"/><text x={pts.C.x+8} y={(pts.C.y+pts.A.y)/2}>h = {format(construction.b*Math.sin(construction.A*Math.PI/180))}</text></>}
 {(triangle?vertices:construction?(['A','C'] as Vertex[]):[]).map(v=><g key={v} role={onChange?'button':undefined} tabIndex={onChange?0:undefined} aria-label={`Move vertex ${v} with arrow keys`} className={onChange?'obl-drag':''} onPointerDown={e=>{if(!onChange||!triangle)return;e.preventDefault();model?.ledger.beginGesture();e.currentTarget.setPointerCapture(e.pointerId);drag.current={vertex:v,points:raw,scale,minX:ox-minX*scale,minY:oy-minY*scale};onSelect?.(v);}} onKeyDown={e=>{if(!onChange||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const d=(e.shiftKey?10:2)/scale;change(v,raw[v].x+(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0),raw[v].y+(e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0));}}><circle cx={pts[v].x} cy={pts[v].y} r="17" fill="transparent"/><circle cx={pts[v].x} cy={pts[v].y} r="6" fill={pairColors[v]} stroke="white" strokeWidth="2"/><text x={pts[v].x+(v==='A'?-14:12)} y={pts[v].y+(v==='C'?-13:25)} fill="#13253e" fontSize="22" fontFamily="Georgia">{v}{construction&&v==='B'&&alternative?'₁':''}</text></g>)}
 {!triangle&&!construction&&<text x="250" y="190" textAnchor="middle" fill="#933d32">Enter valid data to draw a triangle.</text>}
 {showHeight&&showValues&&triangle&&<text x="250" y="369" textAnchor="middle" fill="#163863" fontSize="17">Area = {format(triangle.area)} {unit}²</text>}
 </svg><p className="obl-graph-hint" role="status">{notice||(!triangle?'No triangle exists for this data.':onChange?'Drag a vertex or focus it and use arrow keys. Select a side to highlight its opposite angle.':'Sides are paired with their opposite angles.')}</p></>;
}
