import {useState} from 'react';
import {useStudioState} from '../../phase1/StudioModelProvider';
import {Answer,Comparison,Formula,KeyIdea,LessonBottom,NumberField,Panel,Steps,TriangleExplorer,Verification,useLengthUnit,useTriangleInputs} from './ObliqueShared';
import {format,solveProblem,type Problem,type Quantity,type Triangle} from './triangleMath';
const initial={A:42,B:71,C:67,a:8.6,b:11.6,c:12.8};
const fields:Record<Problem,Quantity[]>={ASA:['A','B','c'],AAS:['A','B','a'],SAS:['b','c','A'],SSS:['a','b','c'],SSA:['A','a','b']};
const methods:Record<Problem,string>={ASA:'Find the third angle, then use the Sine Law.',AAS:'Find the third angle, then use the Sine Law.',SAS:'Use the Cosine Law for the opposite side, then find angles.',SSS:'Use the Cosine Law to find angles.',SSA:'Use the Sine Law and test both possible angles.'};
export default function SolveTrianglePage(){const unit=useLengthUnit();const model=useTriangleInputs('solve-triangle',initial),[kind,setKind]=useStudioState<Problem>('ObliqueStudio:solve:case','ASA'),[step,setStep]=useState(0),[solution,setSolution]=useState(0),[exampleIndex,setExampleIndex]=useState(0),[knownMask,setKnown]=useStudioState<Record<Quantity,boolean>>('ObliqueTriangleLab:ObliqueTriangleLab:known',{a:true,b:true,c:true,A:true,B:true,C:false}),v=model.values,solutions=solveProblem(kind,v),t=solutions[solution]??solutions[0]??null;
 const another=()=>{const next=exampleIndex+1;setExampleIndex(next);setStep(0);setSolution(0);const examples=kind==='SSS'?{...initial,a:3,b:4,c:5}:kind==='SSA'?{...initial,A:40,a:8,b:10}:kind==='SAS'?{...initial,A:60,b:9,c:7}:{...initial,A:30,B:45,a:10,c:19.3185165258};model.setValues(next%2?examples:initial);};
 const known=fields[kind],choose=(k:Problem)=>{setKind(k);setStep(0);setSolution(0);if(k==='SSA')model.setValues({...initial,A:35,a:7,b:10});else if(k==='SSS')model.setValues({...initial,a:5,b:6,c:7});else if(k==='SAS')model.setValues({...initial,A:58,b:9.1,c:7.5});else model.reset();};
 const messages=(s:Triangle)=>kind==='ASA'||kind==='AAS'?[`Find C = 180° − ${format(v.A)}° − ${format(v.B)}° = ${format(s.C)}°.`,kind==='ASA'?`Use a = c sin A / sin C = ${format(s.a,5)}.`:`Use b = a sin B / sin A = ${format(s.b,5)}.`,kind==='ASA'?`Use b = c sin B / sin C = ${format(s.b,5)}.`:`Use c = a sin C / sin A = ${format(s.c,5)}.`,`All six quantities found. Verify angle sum and triangle inequalities.`]:kind==='SAS'?[`Use a² = b² + c² − 2bc cos A = ${format(s.a*s.a,5)}.`,`Take the positive square root: a = ${format(s.a,5)}.`,`Use arccos to find B = ${format(s.B,5)}°; C = 180° − A − B = ${format(s.C,5)}°.`,`Verify all six values and triangle inequalities.`]:kind==='SSS'?[`Use cos A = (b²+c²−a²)/(2bc); A = ${format(s.A,5)}°.`,`Use cos B = (a²+c²−b²)/(2ac); B = ${format(s.B,5)}°.`,`Find C = 180° − A − B = ${format(s.C,5)}°.`,`Verify all six values and triangle inequalities.`]:[`Use sin B = b sin A / a; test both B and 180°−B.`,`For this solution: B = ${format(s.B,5)}°, C = ${format(s.C,5)}°.`,`Use c = a sin C / sin A = ${format(s.c,5)}.`,`Verify all ${solutions.length} valid solutions without silently selecting only one.`];
 return <><div className="obl-lesson-grid"><Panel title="Problem Types"><p>Three independent measurements, including at least one side, can determine a triangle. SSA may be ambiguous; AAA determines only shape.</p><div className="obl-case-list">{(['ASA','AAS','SAS','SSS','SSA'] as Problem[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>choose(k)}><b>{k}</b><span>{methods[k]}</span></button>)}</div><KeyIdea>Select the method from what is known. The included angle is essential in SAS; a non-included angle creates SSA.</KeyIdea></Panel>
 <TriangleExplorer triangle={t} alternative={solutions.length>1?solutions[solution===0?1:0]:undefined} onChange={model.load} reset={()=>{model.reset();setKind('ASA');setStep(0);}} known={known} activePair={step===0?'C':step===1?'A':step===2?'B':'C'}/>
 <Panel title="Step-by-Step Solver" className="obl-solver"><div className="obl-solver-grid"><div className="obl-input-panel"><h3>Choose case</h3><select aria-label="Problem type" value={kind} onChange={e=>choose(e.target.value as Problem)}>{Object.keys(fields).map(k=><option key={k}>{k}</option>)}</select><p>{methods[kind]}</p><h3>Enter known values</h3>{known.map(k=><NumberField key={k} label={k===k.toUpperCase()?`Angle ${k}`:`Side ${k}`} value={v[k]} onChange={n=>{model.set(k,n);setStep(0);}} unit={k===k.toUpperCase()?'°':undefined}/>)}<button className="obl-primary" onClick={()=>{setStep(3);document.getElementById('obl-full-solution')?.scrollIntoView({block:'nearest'});}}>Solve Triangle</button><button onClick={another}>Try Another Example</button></div><div className="obl-solution" id="obl-full-solution"><h3>Step-by-step solution</h3>{t?<><Steps>{messages(t).map((m,i)=><li key={m} className={i===step?'obl-current-step':''}><button className="obl-step-button" onClick={()=>setStep(i)} aria-pressed={step===i}>{m}</button></li>)}</Steps><div className="obl-mode-buttons"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>Previous Step</button><button disabled={step===3} onClick={()=>setStep(s=>s+1)}>Next Step</button></div>{solutions.length>1&&<div className="obl-mode-buttons">{solutions.map((_,i)=><button key={i} aria-pressed={solution===i} onClick={()=>{setSolution(i);setStep(0);}}>Solution {i+1}</button>)}</div>}{solutions.map((s,i)=><Answer key={i}><b>Complete triangle {solutions.length>1?i+1:''}</b><p>A = {format(s.A)}°, B = {format(s.B)}°, C = {format(s.C)}°</p><p>a = {format(s.a)}, b = {format(s.b)}, c = {format(s.c)} {unit}</p><Verification triangle={s}/></Answer>)}</>:<Answer error>{kind==='SSS'?`${format(v.a)} + ${format(v.b)} must exceed ${format(v.c)}, and all three triangle inequalities must hold.`:'No valid solution. Check positive sides, valid angle sums, and SSA feasibility.'}</Answer>}</div></div></Panel></div>
 <LessonBottom expected={t?.C??null} prompt="Find the third angle C of the displayed solution, in degrees." values={{v,kind,solution}} onExample={()=>{setKind('AAS');model.setValues({...initial,A:52,B:71,a:120});}}><Panel title="Known Values and Verification Workspace"><p>Preserved known-value markers for planning a measurement problem. Select any three independent quantities, then choose the corresponding case above. Markers do not change the solver’s input requirements.</p><div className="obl-known-grid">{(['a','b','c','A','B','C'] as Quantity[]).map(k=><label key={k}><input type="checkbox" checked={knownMask[k]} onChange={e=>setKnown(m=>({...m,[k]:e.target.checked}))}/>{k} known</label>)}</div><p>{Object.values(knownMask).filter(Boolean).length} / 6 values marked.</p><Formula tex="A+B+C=180^\circ,\quad a+b>c,\ a+c>b,\ b+c>a"/><p>AAA supplies no absolute size; fewer than three independent measurements cannot uniquely solve an oblique triangle. No solution is fabricated for insufficient or inconsistent data.</p></Panel>{t&&<Comparison t={t}/>}</LessonBottom></>;}
