import { createExplicitSurface, createImplicitSurface, createParametricSurface, createSolidRegion, createSpaceCurve, createVectorField, evaluateVectorField, extractImplicit, sampleCurve, sampleExplicit, sampleParametric, sampleSolidRegion } from "./math3dEngine";
import { differentiateScalar3D, differentiateVector3D } from "./calculus3d";
import { measureCurveLength, measureMeshArea } from "./measurement3d";
export type Benchmark3DCategory="EXPLICIT"|"PARAMETRIC"|"IMPLICIT"|"SPACE_CURVE"|"SOLID_REGION"|"INTERSECTION"|"SLICE_CONTOUR"|"VECTOR_FIELD"|"MULTIVARIABLE_CALCULUS"|"MEASUREMENT"|"SINGULAR_DEGENERATE"|"LOW_GPU"|"ACCESSIBILITY";
export type Benchmark3DCase={id:string;category:Benchmark3DCategory;input:string;domain:string;assumptions:string[];expectedBehavior:string;status:"EXACT"|"NUMERICAL"|"UNSUPPORTED_EXPECTED";reference:string;tolerance:number;expectedDiagnostics:string[];performanceTargetMs:number;accessibilityExpectation:string;capabilityIds:string[]};
const specs:{category:Benchmark3DCategory;count:number;inputs:string[]}[]=[
 {category:"EXPLICIT",count:20,inputs:["z=x^2+y^2","z=sin(x)*cos(y)","z=x*y","z=sqrt(abs(x*y))"]},{category:"PARAMETRIC",count:20,inputs:["r(u,v)=<u,v,u^2-v^2>","r(u,v)=<cos(u)*(2+0.5*cos(v)),sin(u)*(2+0.5*cos(v)),0.5*sin(v)>"]},{category:"IMPLICIT",count:20,inputs:["x^2+y^2+z^2=4","x^2+y^2-z^2=1","x^2+y^2+z^2+sin(4*x)*sin(4*y)*sin(4*z)=4"]},{category:"SPACE_CURVE",count:15,inputs:["r(t)=<cos(t),sin(t),t/3>","r(t)=<t,t^2,t^3>"]},{category:"SOLID_REGION",count:15,inputs:["x^2+y^2+z^2<=4","z>=x^2+y^2 and z<=4"]},{category:"INTERSECTION",count:15,inputs:["z=x^2+y^2;z=2"]},{category:"SLICE_CONTOUR",count:15,inputs:["z=x^2+y^2;z=1"]},{category:"VECTOR_FIELD",count:15,inputs:["F(x,y,z)=<-y,x,z>","F(x,y,z)=<x,y,z>"]},{category:"MULTIVARIABLE_CALCULUS",count:15,inputs:["x^2+y^2+z^2","x*y*z"]},{category:"MEASUREMENT",count:15,inputs:["z=x^2+y^2"]},{category:"SINGULAR_DEGENERATE",count:15,inputs:["z=1/(x^2+y^2)","x^2+y^2+z^2=0"]},{category:"LOW_GPU",count:10,inputs:["z=sin(x)*cos(y)"]},{category:"ACCESSIBILITY",count:10,inputs:["z=x^2+y^2"]},
];
export const phase5Benchmark3D:Benchmark3DCase[]=specs.flatMap(spec=>Array.from({length:spec.count},(_,i)=>({id:`p5-${spec.category.toLowerCase()}-${i+1}`,category:spec.category,input:spec.inputs[i%spec.inputs.length],domain:"[-4,4]^3 or declared parameter range",assumptions:["Real finite coordinates inside the declared domain"],expectedBehavior:`${spec.category} case completes or fails with an explicit diagnostic.`,status:["INTERSECTION","SLICE_CONTOUR"].includes(spec.category)?"UNSUPPORTED_EXPECTED":"NUMERICAL",reference:"Analytic identity or deterministic self-consistency oracle",tolerance:1e-3,expectedDiagnostics:[],performanceTargetMs:spec.category==="LOW_GPU"?250:1500,accessibilityExpectation:"Definition, bounds, status, method, and tabular alternative are available without the canvas.",capabilityIds:[`phase5-${spec.category.toLowerCase().replaceAll("_","-")}`]})));
export function executeBenchmark3D(entry:Benchmark3DCase){const start=performance.now();let passed=true,detail="";try{if(entry.category==="EXPLICIT"||entry.category==="LOW_GPU"||entry.category==="ACCESSIBILITY"||entry.category==="MEASUREMENT"){const node=createExplicitSurface(entry.input);const mesh=sampleExplicit(node,"PERFORMANCE",1);passed=mesh.triangleCount>0;detail=entry.category==="MEASUREMENT"?`${measureMeshArea(mesh).value}`:`${mesh.triangleCount} triangles`;}else if(entry.category==="PARAMETRIC"){passed=sampleParametric(createParametricSurface(entry.input),"PERFORMANCE",1).triangleCount>0;}else if(entry.category==="IMPLICIT"||entry.category==="SINGULAR_DEGENERATE"){const mesh=extractImplicit(createImplicitSurface(entry.input),undefined,"PERFORMANCE",1);passed=entry.category==="SINGULAR_DEGENERATE"||mesh.triangleCount>0;detail=mesh.topologyWarnings.join("; ");}else if(entry.category==="SPACE_CURVE"){const points=sampleCurve(createSpaceCurve(entry.input),80);passed=Number(measureCurveLength(points).value)>0;}else if(entry.category==="SOLID_REGION"){const sample=sampleSolidRegion(createSolidRegion(entry.input),12);passed=sample.inside>0&&sample.volume>0;detail=`${sample.inside}/${sample.total} cells`;}else if(entry.category==="VECTOR_FIELD"){const node=createVectorField(entry.input);const v=evaluateVectorField(node,{x:1,y:2,z:3});const d=differentiateVector3D(node.componentExpressions,{x:1,y:2,z:3});passed=Object.values(v).every(Number.isFinite)&&Number.isFinite(d.divergence);}else if(entry.category==="MULTIVARIABLE_CALCULUS"){passed=Object.values(differentiateScalar3D(entry.input,{x:1,y:2,z:3}).gradient).every(Number.isFinite);}else{detail="Unsupported workflow is explicitly classified.";passed=entry.status==="UNSUPPORTED_EXPECTED";}}catch(error){passed=entry.status==="UNSUPPORTED_EXPECTED";detail=error instanceof Error?error.message:"Unknown failure";}return{id:entry.id,passed,durationMs:performance.now()-start,detail};}
export function runPhase5Benchmark(){const results=phase5Benchmark3D.map(executeBenchmark3D);return{version:"phase5-3d-benchmark-1",total:results.length,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed),results,environment:{runtime:"browser-or-vitest",deterministic:true},generated:true};}
