import { useMemo, useState } from "react";
import SectionCard from "../components/ui/SectionCard";
import TopicHeader from "../components/ui/TopicHeader";
import { capabilityRegistry, curriculumMappings, curriculumPathways } from "../truth-layer/registry";
import type { BoardId, CoverageDimensions, CurriculumMappingStatus } from "../truth-layer/types";
import { validateCurriculumMapping } from "../truth-layer/validation";

type Dimension = keyof CoverageDimensions;
export default function CoverageDashboardPage() {
  const [board, setBoard] = useState<BoardId | "ALL">("ALL"); const [status, setStatus] = useState<CurriculumMappingStatus | "ALL">("ALL"); const [dimension, setDimension] = useState<Dimension | "ALL">("ALL"); const [year, setYear] = useState("ALL"); const [course, setCourse] = useState("ALL"); const [paper, setPaper] = useState("ALL"); const [reviewer, setReviewer] = useState("ALL");
  const filtered = useMemo(() => curriculumMappings.filter((mapping) => (board === "ALL" || mapping.board === board) && (status === "ALL" || mapping.status === status) && (dimension === "ALL" || mapping.coverage[dimension] !== "NOT_STARTED") && (year === "ALL" || mapping.curriculumYear === year) && (course === "ALL" || mapping.gradeOrCourse === course) && (paper === "ALL" || mapping.paper === paper) && (reviewer === "ALL" || (reviewer === "REVIEWED" ? mapping.review.reviewers.length > 0 : mapping.review.reviewers.length === 0))), [board, status, dimension, year, course, paper, reviewer]);
  const missingEvidence = filtered.reduce((sum, mapping) => sum + validateCurriculumMapping({ ...mapping, status: mapping.status === "UNMAPPED" ? "COMPLETE" : mapping.status }).length, 0);
  const boards = [...new Set(curriculumMappings.map((mapping) => mapping.board))];
  return <div className="space-y-4"><TopicHeader title="Coverage Truth Dashboard" subtitle="Internal evidence reporting calculated from curriculum and capability registries. Availability, mapping, and certification remain separate." difficulty="Advanced" estimatedMinutes={8} />
    <SectionCard title="Registry filters" description="Every count below is recalculated from the selected records." compact visualizationTools={false}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Filter label="Board" value={board} onChange={(value) => setBoard(value as BoardId | "ALL")} options={["ALL", ...boards]} /><Filter label="Curriculum year" value={year} onChange={setYear} options={["ALL", ...new Set(curriculumMappings.map((mapping) => mapping.curriculumYear))]} /><Filter label="Course or class" value={course} onChange={setCourse} options={["ALL", ...new Set(curriculumMappings.map((mapping) => mapping.gradeOrCourse))]} /><Filter label="Intermediate paper" value={paper} onChange={setPaper} options={["ALL", "IA", "IB", "IIA", "IIB"]} /><Filter label="Mapping status" value={status} onChange={(value) => setStatus(value as CurriculumMappingStatus | "ALL")} options={["ALL", "UNMAPPED", "UNVERIFIED", "SUPPORTING", "PARTIAL", "COMPLETE", "CERTIFIED"]} /><Filter label="Coverage dimension" value={dimension} onChange={(value) => setDimension(value as Dimension | "ALL")} options={["ALL", "catalogued", "explained", "visualized", "computational", "practised", "assessed", "textbookMapped", "boardCertified"]} /><Filter label="Reviewer state" value={reviewer} onChange={setReviewer} options={["ALL", "REVIEWED", "UNREVIEWED"]} /></div></SectionCard>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Affected mappings" value={filtered.length} /><Metric label="Missing evidence fields" value={missingEvidence} warning={missingEvidence > 0} /><Metric label="Generated scaffolds" value={filtered.filter((mapping) => mapping.contentOrigin === "GENERATED_SCAFFOLD").length} /><Metric label="Expired reviews" value={filtered.filter((mapping) => mapping.review.expiresAt && new Date(mapping.review.expiresAt) <= new Date()).length} /><Metric label="Certified mappings" value={filtered.filter((mapping) => mapping.status === "CERTIFIED").length} /></div>
    <SectionCard title="Dimension evidence" description="A concept can be explained or visualized without being assessed, officially mapped, or certified." compact visualizationTools={false}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Dimension</th>{["NOT_STARTED", "DRAFT", "REVIEW_REQUIRED", "VERIFIED", "NOT_APPLICABLE"].map((state) => <th className="p-2" key={state}>{state.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{(["catalogued", "explained", "visualized", "computational", "practised", "assessed", "textbookMapped", "boardCertified"] as Dimension[]).map((key) => <tr className="border-t border-slate-200 dark:border-white/10" key={key}><th className="p-2">{key}</th>{["NOT_STARTED", "DRAFT", "REVIEW_REQUIRED", "VERIFIED", "NOT_APPLICABLE"].map((state) => <td className="p-2 font-mono" key={state}>{filtered.filter((mapping) => mapping.coverage[key] === state).length}</td>)}</tr>)}</tbody></table></div></SectionCard>
    <SectionCard title="Exact affected records" description="Drill-down shows the source record behind every summary count." compact visualizationTools={false}><div className="grid gap-2">{filtered.map((mapping) => { const issues = validateCurriculumMapping({ ...mapping, status: mapping.status === "UNMAPPED" ? "COMPLETE" : mapping.status }); return <details className="rounded-xl border border-slate-200 p-3 dark:border-white/10" key={mapping.id}><summary className="cursor-pointer font-bold">{mapping.board} · {mapping.gradeOrCourse}{mapping.paper ? ` · ${mapping.paper}` : ""} — {mapping.status}</summary><p className="mt-2 text-sm">{mapping.unit} / {mapping.chapter}</p><p className="mt-1 text-xs text-slate-500">{mapping.id} · {mapping.curriculumYear}</p>{issues.length ? <ul className="mt-2 grid gap-1 text-xs text-amber-800 dark:text-amber-200">{issues.map((issue) => <li key={`${mapping.id}-${issue.code}-${issue.field}`}>{issue.code}: {issue.message}</li>)}</ul> : <p className="mt-2 text-xs text-emerald-700">No validation gaps for current status.</p>}</details>; })}</div></SectionCard>
    <SectionCard title="Supported pathways" description="AP and Telangana are separate pathways; no equivalence is inferred. All four Intermediate papers are distinct." compact visualizationTools={false}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{curriculumPathways.map((pathway) => <article className="rounded-xl border border-slate-200 p-3 dark:border-white/10" key={pathway.id}><strong className="text-sm">{pathway.course}{"paper" in pathway ? ` · ${pathway.paper}` : ""}</strong><p className="mt-1 text-xs text-slate-500">{pathway.board} · {pathway.id}</p></article>)}</div></SectionCard>
    <SectionCard title="Capability status" description="Support disclosures are generated from the same registry used by the Universal Math Document." compact visualizationTools={false}><div className="grid gap-2 lg:grid-cols-2">{capabilityRegistry.map((capability) => <article className="rounded-xl border border-slate-200 p-3 dark:border-white/10" key={capability.id}><div className="flex justify-between gap-3"><strong>{capability.name}</strong><span className="mini-chip">{capability.status}</span></div><p className="mt-2 text-xs">Routes: {capability.consumingRoutes.join(", ") || "No consuming route"}</p><p className="mt-1 text-xs text-slate-500">{capability.knownLimitations.join(" ")}</p></article>)}</div></SectionCard>
  </div>;
}
function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="text-sm font-bold">{label}<select className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-2 text-slate-950 dark:border-white/15 dark:bg-slate-950 dark:text-white" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Metric({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <div className={`rounded-xl border p-4 ${warning ? "border-amber-300 bg-amber-50 dark:bg-amber-300/10" : "border-cyan-200 bg-cyan-50 dark:bg-cyan-300/10"}`}><p className="text-2xl font-black">{value}</p><p className="text-xs font-semibold">{label}</p></div>; }
