import { describe, expect, it } from 'vitest';
import { analyzeOrder, analyzeRelation, booleanOrder, checkedPower, divisibility, expressionResult, mappingAnalysis, maskMatches, parseBuilder, parseRelation, parseRoster } from './math';
import { functionProperties, pairKey } from '../setTheoryEngine';
import { correctAnswer, createQuestion, practiceTopics } from './practiceEngine';
describe('Set Theory strict notation and operations',()=>{
 it('handles duplicates, empty rosters, ranges and invalid forms',()=>{expect(parseRoster('A={1,2,2}')).toEqual(['1','2']);expect(parseRoster('∅')).toEqual([]);expect(parseRoster('{-2,...,2}')).toEqual(['-2','-1','0','1','2']);expect(()=>parseRoster('{1,2')).toThrow();expect(()=>parseRoster('{1,...,100}')).toThrow();});
 it('filters builder predicates relative to U without evaluating code',()=>{const u=parseRoster('{-5,...,5}');expect(parseBuilder('x ∈ U | x is even',u)).toEqual(['-4','-2','0','2','4']);expect(parseBuilder('1 ≤ x ≤ 3',u)).toEqual(['1','2','3']);expect(parseBuilder('x mod 3 = 1',u)).toEqual(['-5','-2','1','4']);expect(parseBuilder('x is prime',u)).toEqual(['2','3','5']);expect(()=>parseBuilder('x mod 0 = 1',u)).toThrow();expect(()=>parseBuilder('alert(1)',u)).toThrow();expect(()=>parseBuilder('x is prime',['1e30'])).toThrow();});
 it('parses exact pairs and prevents out-of-carrier or ambiguous input',()=>{expect(parseRelation('{(1,2),(2,1),(1,2)}',['1','2'],['1','2'])).toEqual([['1','2'],['2','1']]);expect(()=>parseRelation('(1,2,3)',['1'],['2'])).toThrow();expect(()=>parseRelation('(1,9)',['1'],['2'])).toThrow();expect(pairKey(['a->b','c'])).not.toBe(pairKey(['a','b->c']));});
 it('uses exact Boolean atoms for complements and three-set expressions',()=>{expect(expressionResult('Aᶜ',['1','2','3'],['1'],[],[])).toEqual(['2','3']);expect(expressionResult('A ∩ B ∩ C',['1','2'],['1','2'],['2'],['2'])).toEqual(['2']);expect(Array.from({length:8},(_,i)=>maskMatches('A ∩ B',i))).toEqual([false,false,false,true,false,false,false,true]);expect(Array.from({length:8},(_,i)=>maskMatches('Aᶜ',i))).toEqual([true,false,true,false,true,false,true,false]);});
 it('never silently truncates power-set enumeration',()=>{expect(checkedPower([])).toEqual([[]]);expect(checkedPower(['a','b','c'])).toHaveLength(8);expect(()=>checkedPower(Array.from({length:9},(_,i)=>String(i)))).toThrow();});
});
describe('relations, orders and functions',()=>{
 it('produces witnesses, separates symmetry types and handles different carriers',()=>{const a=['1','2','3'],p:[string,string][]=[['1','2'],['2','3']];const props=analyzeRelation(a,a,p);expect(props.find(p=>p.name==='Transitive')).toMatchObject({value:false});expect(props.find(p=>p.name==='Transitive')?.why).toContain('(1,3)');expect(props.find(p=>p.name==='Irreflexive')?.value).toBe(true);expect(analyzeRelation(['1'],['a'],[['1','a']]).every(p=>p.value===null)).toBe(true);expect(analyzeRelation([],[],[]).find(p=>p.name==='Reflexive')?.value).toBe(true);});
 it('reduces covers and calculates all-pair lattice properties',()=>{const {domain,pairs}=divisibility(12),p=analyzeOrder(domain,pairs,['4','6']);expect(p.valid).toBe(true);expect(p.covers).toHaveLength(7);expect(p.covers).not.toContainEqual(['1','12']);expect(p.meet).toBe('2');expect(p.join).toBe('12');expect(p.least).toBe('1');expect(p.greatest).toBe('12');expect(p.lattice).toBe(true);const bool=booleanOrder(['a','b','c']);expect(bool.domain).toHaveLength(8);expect(analyzeOrder(bool.domain,bool.pairs,[]).lattice).toBe(true);});
 it('rejects non-posets and identifies missing meet/join',()=>{expect(analyzeOrder(['a','b'],[['a','b'],['b','a']],['a','b']).valid).toBe(false);const p=analyzeOrder(['a','b'],[['a','a'],['b','b']],['a','b']);expect(p.valid).toBe(true);expect(p.lattice).toBe(false);expect(p.meet).toBeUndefined();expect(p.join).toBeUndefined();expect(p.antichain).toBe(true);});
 it('treats relation pairs as a set and checks totality, collisions and inverse availability',()=>{expect(functionProperties(['1'],['a'],[['1','a'],['1','a']]).bijective).toBe(true);expect(mappingAnalysis(['1'],['a','b'],[['1','a'],['1','b']])).toMatchObject({isFunction:false,oneToMany:true,inverse:null});expect(mappingAnalysis([],['a'],[])).toMatchObject({isFunction:true,injective:true,surjective:false,into:true});expect(mappingAnalysis([],[],[]).bijective).toBe(true);});
});
describe('local practice generation',()=>{
 it('generates hundreds of varied solvable prompts and valid unique choices',()=>{const prompts=new Set<string>(),kinds=new Set<string>();for(const difficulty of ['Beginner','Medium','Advanced'])for(const topic of practiceTopics.slice(1))for(let seed=0;seed<48;seed++){const q=createQuestion(seed,topic,difficulty);expect(correctAnswer(q,q.answer),q.id).toBe(true);if(['mcq','diagram','true-false'].includes(q.kind)){expect(q.options.filter(x=>correctAnswer(q,x)),q.id).toHaveLength(1);expect(new Set(q.options).size).toBe(q.options.length);}prompts.add(q.prompt);kinds.add(q.kind);}expect(prompts.size).toBeGreaterThan(300);expect(kinds.size).toBe(7);});
 it('grades set semantics without accepting malformed notation',()=>{const q=createQuestion(0,'Set Operations','Medium');expect(correctAnswer(q,'{5,4,3,2,1,1}')).toBe(true);expect(correctAnswer(q,'{1,2,3,4}')).toBe(false);expect(correctAnswer(q,'{1,2,3,4,5')).toBe(false);});
});
