import { cartesianProduct, equivalenceClasses, relationProperties, type OrderedPair } from '../setTheoryEngine';
import { analyzeOrder, divisibility, expressionResult, mappingAnalysis, parseRoster, setText, type Expression } from './math';
export const practiceTopics=['All Topics','Set Basics','Membership','Subsets & Equality','Set Operations','Venn Diagrams','Cartesian Products','Power Sets','Relations','Function Mapping','Hasse Diagrams','Equivalence Classes','Set Identities','Word Problems'];
export type Question={id:string;topic:string;kind:'mcq'|'set'|'number'|'notation'|'true-false'|'drag'|'diagram';prompt:string;answer:string;answerType:'set'|'number'|'notation'|'boolean';options:string[];hint:string;steps:string[];a:string[];b:string[];u:string[];expression?:Expression;relation?:OrderedPair[];mapping?:OrderedPair[];order?:ReturnType<typeof divisibility>;aliases?:string[]};
const canonical=(s:string)=>s.replace(/\s/g,'').replace(/->/g,'→').replace(/\\cup/g,'∪').replace(/\\cap/g,'∩').replace(/\\subseteq/g,'⊆').replace(/\\in/g,'∈');
export function correctAnswer(q:Question,value:string){try{if(q.answerType==='set'){const actual=parseRoster(value).sort(),expected=parseRoster(q.answer).sort();return JSON.stringify(actual)===JSON.stringify(expected);}if(q.answerType==='number')return value.trim()!==''&&Number.isFinite(Number(value))&&Number(value)===Number(q.answer);return [q.answer,...q.aliases||[]].some(x=>canonical(x).toLowerCase()===canonical(value).toLowerCase());}catch{return false;}}
export function createQuestion(seed:number,requested:string,difficulty:string):Question{
 const topics=practiceTopics.slice(1),topic=requested==='All Topics'?topics[seed%topics.length]:requested;
 const offset=Math.floor(seed/6)%9,size=difficulty==='Advanced'?8:difficulty==='Beginner'?5:6,u=Array.from({length:size},(_,i)=>String(i+1+offset));
 const a=seed===0?['1','2','3','4']:u.filter((_,i)=>(i+seed)%3!==2),b=seed===0?['3','4','5']:u.filter((_,i)=>(i+seed)%3!==0);
 const exprs:Expression[]=['A ∪ B','A ∩ B','A − B','B − A','Aᶜ','Bᶜ','A △ B'],expression=exprs[seed%exprs.length];
 let answerType:Question['answerType']='set',answer=setText(expressionResult(expression,u,a,b)),prompt=`Given A=${setText(a)} and B=${setText(b)} in U=${setText(u)}, find ${expression}.`,hint='Check each U element against the membership rule; keep each element once.',steps=[`Use the definition of ${expression}.`,'Test membership element by element.',`The result is ${answer}.`],relation:OrderedPair[]|undefined,mapping:OrderedPair[]|undefined,order:ReturnType<typeof divisibility>|undefined;
 if(topic==='Set Basics'){answerType='number';answer=String(a.length);prompt=`How many distinct elements are in A=${setText([...a,a[0]])}?`;hint='Repeated entries do not create extra set elements.';steps=['Remove duplicate entries.',`The distinct roster is ${setText(a)}.`,`Cardinality is ${answer}.`];}
 if(topic==='Membership'){answerType='boolean';const x=u[(seed+1)%u.length];answer=String(a.includes(x));prompt=`True or false: ${x} ∈ A when A=${setText(a)}.`;hint='Look for the exact element in the roster.';steps=[`Compare ${x} with each listed member.`,a.includes(x)?'The element is listed.':'The element is absent.',`The statement is ${answer}.`];}
 if(topic==='Subsets & Equality'){answerType='boolean';const left=seed%2?a:a.slice(0,2);answer=String(left.every(x=>b.includes(x)));prompt=`Is ${setText(left)} ⊆ ${setText(b)}?`;hint='Every member of the first set must occur in the second.';steps=['Inspect every element on the left.',left.some(x=>!b.includes(x))?`Counterexample: ${left.find(x=>!b.includes(x))} is absent on the right.`:'Every left element occurs on the right.',`The claim is ${answer}.`];}
 if(topic==='Cartesian Products'){answerType='number';answer=String(a.length*b.length);prompt=`For A=${setText(a)}, B=${setText(b)}, find |A × B|.`;hint='For each first entry, count all possible second entries.';steps=[`There are ${a.length} first-entry choices.`,`Each has ${b.length} second-entry choices.`,`Multiply to get ${answer}.`];}
 if(topic==='Power Sets'){answerType='number';answer=String(2**a.length);prompt=`How many subsets does A=${setText(a)} have?`;hint='Each member has two choices: include or exclude.';steps=[`A has ${a.length} distinct members.`,`Independent binary choices give 2^${a.length}.`,`This equals ${answer}, including ∅ and A.`];}
 if(topic==='Relations'){answerType='boolean';relation=cartesianProduct(u,u).filter(([x,y])=>seed%2?Number(x)<Number(y):x===y);const props=relationProperties(u,relation),property=['reflexive','symmetric','antisymmetric','transitive'][seed%4] as keyof typeof props;answer=String(props[property]);prompt=`On U=${setText(u)}, R=${relation.map(([x,y])=>`(${x},${y})`).join(', ')||'∅'}. Is R ${property}?`;hint=`Apply the definition of ${property}, including every required pair.`;steps=[`The carrier is ${setText(u)}.`,`Inspect all pairs, including relevant diagonal or composed pairs.`,`The computed ${property} property is ${answer}.`];}
 if(topic==='Function Mapping'){answerType='boolean';const codomain=['a','b','c'],domain=u.slice(0,3);mapping=domain.map((x,i)=>[x,codomain[seed%2?i:0]]);const p=mappingAnalysis(domain,codomain,mapping),property=seed%3===0?'injective':seed%3===1?'surjective':'bijective';answer=String(p[property]);prompt=`For f:${setText(domain)}→${setText(codomain)} with ${mapping.map(([x,y])=>`${x}↦${y}`).join(', ')}, is f ${property}?`;hint='Compare repeated outputs with unused codomain elements.';steps=['Each input has exactly one valid output.',`The range is ${setText(p.range)}.`,`The ${property} claim is ${answer}.`];}
 if(topic==='Hasse Diagrams'){answerType='number';order=divisibility(seed%2?30:12);const chosen=seed%2?['6','10']:['4','6'],op=seed%3?'meet':'join',p=analyzeOrder(order.domain,order.pairs,chosen);answer=p[op]||'';prompt=`For divisors of ${seed%2?30:12} ordered by divisibility, find the ${op} of ${chosen.join(' and ')}.`;hint=op==='meet'?'Find the greatest element below both selected values.':'Find the least element above both selected values.';steps=[`List the ${op==='meet'?'lower':'upper'} bounds: ${setText(op==='meet'?p.lower:p.upper)}.`,`Choose the ${op==='meet'?'greatest lower':'least upper'} bound within this poset.`,`The ${op} is ${answer}.`];}
 if(topic==='Equivalence Classes'){const modulus=seed%3+2,element=u[seed%u.length];relation=cartesianProduct(u,u).filter(([x,y])=>Number(x)%modulus===Number(y)%modulus);answerType='set';answer=setText(equivalenceClasses(u,relation).find(c=>c.includes(element))||[]);prompt=`On U=${setText(u)}, x~y when x≡y (mod ${modulus}). Find [${element}].`;hint='Keep elements with the same remainder as the selected element.';steps=[`The target remainder is ${Number(element)%modulus}.`,'Congruence is reflexive, symmetric and transitive.',`The class is ${answer}.`];}
 if(topic==='Set Identities'){answerType='set';answer=setText(u.filter(x=>!a.includes(x)&&!b.includes(x)));prompt=`For U=${setText(u)}, A=${setText(a)}, B=${setText(b)}, compute (A ∪ B)ᶜ.`;hint='De Morgan rewrites this as Aᶜ ∩ Bᶜ.';steps=['Remove elements in A or B from U.','Keep only elements absent from both.',`The complement is ${answer}.`];}
 if(topic==='Word Problems'){answerType='number';answer=String(new Set([...a,...b]).size);prompt=`Club A has students ${setText(a)} and club B has ${setText(b)}. How many different students attend at least one club?`;hint='Common students must be counted once, not twice.';const common=a.filter(x=>b.includes(x)).length;steps=[`Club counts are ${a.length} and ${b.length}.`,`Subtract ${common} students counted twice.`,`The union has ${answer} members.`];}
 let kind:Question['kind']=['mcq','set','number','notation','drag','diagram'][seed%6] as Question['kind'];
 if(answerType==='boolean')kind='true-false';else if(kind==='set'&&answerType!=='set')kind='number';else if(kind==='number'&&answerType==='set')kind='set';else if(kind==='drag'&&answerType!=='set')kind='mcq';
 if(kind==='notation'&&!['Set Operations','Venn Diagrams','Set Identities'].includes(topic))kind='mcq';
 if(kind==='notation'){answerType='notation';const intersection=seed%2===0;answer=intersection?'∩':'∪';prompt=`Which symbol means ${intersection?'intersection (in both sets)':'union (in at least one set)'}? Enter the symbol or its name.`;hint='Think of the membership condition rather than the shape of the symbol.';steps=[intersection?'Intersection requires both memberships.':'Union requires either membership.',`The notation is ${answer}.`,'Do not confuse this with subset ⊆ or membership ∈.'];}
 let options:string[]=[];
 if(answerType==='boolean')options=['true','false'];else if(answerType==='number')options=[answer,String(Number(answer)+1),String(Math.max(0,Number(answer)-1)),String(Number(answer)+2)];else if(answerType==='set'){const correct=parseRoster(answer);options=[answer,setText(correct.slice(1)),setText([...new Set([...correct,String(Number(u.at(-1))+1)])]),setText(correct.length?[...correct.slice(0,-1),String(Number(u.at(-1))+2)]:[u[0],u[1]])];}
 options=[...new Set(options)];while(options.length<4&&answerType!=='boolean'&&answerType!=='notation')options.push(answerType==='number'?String(Number(answer)+options.length+5):setText([String(Number(u.at(-1))+options.length+5)]));
 if(options.length>1){const shift=seed%options.length;options=[...options.slice(shift),...options.slice(0,shift)];}
 return {id:`${seed}:${topic}:${difficulty}`,topic,kind,prompt,answer,answerType,options,hint,steps,a,b,u,expression,relation,mapping,order,aliases:kind==='notation'?[answer==='∩'?'intersection':'union']:undefined};
}
export function optionExplanation(q:Question,option:string){if(correctAnswer(q,option))return 'This satisfies the required definition.';if(q.answerType==='set'){const actual=parseRoster(option),expected=parseRoster(q.answer),missing=expected.filter(x=>!actual.includes(x)),extra=actual.filter(x=>!expected.includes(x));return [missing.length?`Missing ${setText(missing)}.`:'',extra.length?`Includes extra ${setText(extra)}.`:''].filter(Boolean).join(' ');}return `This does not satisfy the rule; the worked calculation gives ${q.answer}.`;}
