import { useEffect, useState } from 'react';
import { BookOpen, Check, Flame, Lightbulb, Settings2, Target, Trophy } from 'lucide-react';
import { hasseLevels, coverRelations, equivalenceClasses } from '../setTheoryEngine';
import { Card, Button } from './components';
import { GraphCanvas, circularNodes } from './GraphCanvas';
import { TheoryPanel } from './TheoryPanel';
import { createQuestion, correctAnswer, optionExplanation, practiceTopics, type Question } from './practiceEngine';
import { setText } from './math';
function QuestionDiagram({q}:{q:Question}){if(q.order){const levels=hasseLevels(q.order.domain,q.order.pairs),max=Math.max(...levels.map(x=>x.level));return <GraphCanvas modelKey="set-theory:practice-order" directed={false} nodes={levels.map(n=>{const same=levels.filter(x=>x.level===n.level);return {id:n.id,label:n.id,x:360+(same.findIndex(x=>x.id===n.id)-(same.length-1)/2)*160,y:430-n.level*350/Math.max(1,max)};})} pairs={coverRelations(q.order.domain,q.order.pairs)}/>;}
 if(q.mapping)return <GraphCanvas modelKey="set-theory:practice-mapping" nodes={[...q.u.slice(0,3).map((x,i)=>({id:`a:${x}`,label:x,x:170,y:140+i*100,side:'a' as const})),...['a','b','c'].map((x,i)=>({id:`b:${x}`,label:x,x:550,y:140+i*100,side:'b' as const}))]} pairs={q.mapping.map(([x,y])=>[`a:${x}`,`b:${y}`])}/>;
 if(q.relation&&q.topic==='Relations')return <GraphCanvas modelKey="set-theory:practice-relation" nodes={circularNodes(q.u)} pairs={q.relation}/>;
 if(q.topic==='Equivalence Classes'&&q.relation)return <div className="st-class-grid">{equivalenceClasses(q.u,q.relation).map(c=><div key={c.join(',')}><b>Equivalence class</b><p>{setText(c)}</p></div>)}</div>;
 if(q.topic==='Cartesian Products')return <div><p>A × B: one row per second entry</p><div className="st-pair-list">{q.b.map(y=><div key={y}>{q.a.map(x=><span key={x}>({x}, {y}) </span>)}</div>)}</div></div>;
 if(q.topic==='Power Sets')return <div className="st-formula"><p>A = {setText(q.a)}</p><p>For each element: include or exclude.</p><p>∅ ⊆ A and A ⊆ A</p></div>;
 const onlyA=q.a.filter(x=>!q.b.includes(x)),both=q.a.filter(x=>q.b.includes(x)),onlyB=q.b.filter(x=>!q.a.includes(x));
 return <svg viewBox="0 0 330 310" role="img" aria-label="Question Venn diagram" className="st-practice-diagram"><circle cx="120" cy="142" r="88" fill="#a9dcff" fillOpacity=".45" stroke="#1686ff" strokeWidth="2"/><circle cx="215" cy="142" r="88" fill="#f7bcf0" fillOpacity=".45" stroke="#ed4fd1" strokeWidth="2"/><text x="75" y="95" fontSize="23" fontWeight="800">A</text><text x="258" y="95" fontSize="23" fontWeight="800">B</text>{[onlyA,both,onlyB].map((items,j)=>items.map((x,i)=><text key={`${j}:${x}`} x={[83,167,256][j]} y={118+i*25} fontWeight="700" fontSize="18" textAnchor="middle">{x}</text>))}<text x="165" y="255" fontSize="13" textAnchor="middle">Outside: {setText(q.u.filter(x=>!q.a.includes(x)&&!q.b.includes(x)))}</text><text x="165" y="284" fontSize="16" textAnchor="middle">{q.expression||'Membership in A and B'}</text></svg>;
}
type Session={topic:string;difficulty:string;count:number;index:number;base:number;score:number;completed:number;streak:number;lastAnswered:number;lastCorrect:boolean;lastAnswer:string};
const initial:Session={topic:'Set Operations',difficulty:'Medium',count:10,index:0,base:0,score:0,completed:0,streak:0,lastAnswered:-1,lastCorrect:false,lastAnswer:''};
function loadSession(){try{const p=JSON.parse(localStorage.getItem('set-theory:premium:practice')||'null');return p&&practiceTopics.includes(p.topic)&&['Beginner','Medium','Advanced'].includes(p.difficulty)&&Number.isInteger(p.index)&&p.index>=0&&p.index<p.count&&[10,20,30].includes(p.count)&&[p.base,p.score,p.completed,p.streak].every((x:unknown)=>Number.isInteger(x)&&Number(x)>=0)?{...initial,...p} as Session:initial;}catch{return initial;}}
export default function Practice(){const [session,setSession]=useState<Session>(loadSession),[answer,setAnswer]=useState(()=>{const s=loadSession();return s.lastAnswered===s.index?s.lastAnswer:'';}),[chosen,setChosen]=useState<string[]>([]),[hint,setHint]=useState(false),[feedback,setFeedback]=useState<boolean|null>(()=>{const s=loadSession();return s.lastAnswered===s.index?s.lastCorrect:null;}),[error,setError]=useState('');
 const q=createQuestion(session.base+session.index,session.topic,session.difficulty),answered=session.completed,finished=answered>=session.count;
 useEffect(()=>{try{localStorage.setItem('set-theory:premium:practice',JSON.stringify(session));}catch{/* The quiz remains usable without persistence. */}},[session]);
 const clear=()=>{setAnswer('');setChosen([]);setHint(false);setFeedback(null);setError('');};
 const update=(patch:Partial<Session>)=>{setSession(s=>({...s,...patch,index:0,completed:0,score:0,streak:0,lastAnswered:-1,lastCorrect:false,lastAnswer:'',base:s.base+s.index+7}));clear();};
 const submit=()=>{if(feedback!==null||finished)return;const value=q.kind==='drag'?setText(chosen):answer;if(!value.trim()){setError('Choose or enter an answer first.');return;}const correct=correctAnswer(q,value);setFeedback(correct);setError('');setSession(s=>({...s,completed:s.completed+1,score:s.score+(correct?1:0),streak:correct?s.streak+1:0,lastAnswered:s.index,lastCorrect:correct,lastAnswer:value}));};
 const next=()=>{if(finished){update({});return;}setSession(s=>({...s,index:s.index+1}));clear();};
 const isChoice=['mcq','diagram','true-false'].includes(q.kind);
 return <><div className="st-practice-layout"><div className="st-stack"><Card title={`Question ${Math.min(session.index+1,session.count)} of ${session.count}`} icon={Target}><div className="st-progress-bar"><span style={{width:`${answered/session.count*100}%`}}/></div><span className="st-difficulty">{session.difficulty} · {q.topic} · {q.kind}</span><div className="st-question-grid"><div><h2 className="st-question">{q.prompt}</h2>
 {isChoice?<div className="st-answers">{q.options.map((option,i)=><button key={option} disabled={feedback!==null||finished} className={answer===option?'selected':''} aria-pressed={answer===option} onClick={()=>setAnswer(option)}><span>{String.fromCharCode(65+i)}</span><b>{option==='true'?'True':option==='false'?'False':option}</b></button>)}</div>:q.kind==='drag'?<><p>Select or drag all result elements into the answer region.</p><div className="st-drag-bank">{q.u.map(x=><button key={x} disabled={feedback!==null||finished} draggable={feedback===null} aria-pressed={chosen.includes(x)} onDragStart={e=>e.dataTransfer.setData('text/plain',x)} onClick={()=>setChosen(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])}>{x}</button>)}</div><div className="st-drop-answer" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(feedback!==null)return;const x=e.dataTransfer.getData('text/plain');if(q.u.includes(x))setChosen(v=>[...new Set([...v,x])]);}} role="group" aria-label="Practice answer region">{setText(chosen)}</div></>:<label className="st-answer-input">{q.answerType==='set'?'Enter a roster (or ∅)':q.answerType==='notation'?'Enter notation':'Enter a number'}<input aria-label="Practice answer" disabled={feedback!==null||finished} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit();}} placeholder={q.answerType==='set'?'{1, 2}':q.answerType==='notation'?'Symbol or name':'Number'}/></label>}
 </div><div className="st-question-visual"><QuestionDiagram q={q}/></div></div><div className="st-question-actions"><Button onClick={()=>setHint(v=>!v)}><Lightbulb size={17}/>Show Hint</Button><Button primary disabled={feedback!==null||finished} onClick={submit}><Check size={17}/>Check Answer</Button>{feedback!==null||finished?<Button primary onClick={next}>{finished?'Start New Session':'Next Question →'}</Button>:null}</div>{hint?<p className="st-hint">{q.hint}</p>:null}{error?<p role="alert" className="st-error">{error}</p>:null}</Card>
 <Card title="Recent Practice Topics" icon={BookOpen}><div className="st-recent-topics">{['Set Operations','Venn Diagrams','Subsets & Equality','Set Identities','Word Problems'].map(t=><button key={t} className={session.topic===t?'active':''} onClick={()=>update({topic:t})}>{t}</button>)}</div></Card></div>
 <aside className="st-stack"><Card title="Your Progress" icon={Trophy}><div className="st-progress-metrics"><div><strong>{session.score}/{answered}</strong><b>Score</b><small>{answered?Math.round(session.score/answered*100):0}% correct</small></div><div><Flame/><strong>{session.streak}</strong><b>Answer streak</b></div><div><strong>{session.difficulty}</strong><b>Difficulty</b></div><div><Target/><b>{session.topic}</b><small>Current topic</small></div></div><h3 className="st-settings-title"><Settings2 size={17}/>Practice Settings</h3><div className="st-practice-settings"><label>Topic<select aria-label="Practice topic" value={session.topic} onChange={e=>update({topic:e.target.value})}>{practiceTopics.map(t=><option key={t}>{t}</option>)}</select></label><label>Difficulty<select aria-label="Practice difficulty" value={session.difficulty} onChange={e=>update({difficulty:e.target.value})}>{['Beginner','Medium','Advanced'].map(t=><option key={t}>{t}</option>)}</select></label><label>Questions<select aria-label="Practice question count" value={session.count} onChange={e=>update({count:Number(e.target.value)})}>{[10,20,30].map(n=><option key={n}>{n}</option>)}</select></label></div><p className="st-muted">{answered} completed. Changing settings starts a fresh session.</p></Card>
 <Card title={feedback===null?'Think, then check':feedback?'Correct!':'Review the solution'} icon={feedback===null?Lightbulb:Check} className={feedback?'st-feedback-correct':'st-feedback'}>{feedback===null?<p>Use a conceptual hint if needed. The solution appears after submission.</p>:<div role="status"><ol>{q.steps.map(x=><li key={x}>{x}</li>)}</ol><div className="st-formula">Answer: {q.answer}</div>{isChoice?<><h3>Why the other options are incorrect</h3>{q.options.filter(x=>!correctAnswer(q,x)).map(x=><p key={x}><b>{x}</b> — {optionExplanation(q,x)}</p>)}</>:null}</div>}</Card><div className="st-encouragement"><Trophy/><div><b>{finished?'Session complete':'Build real understanding'}</b><p>{finished?`You answered ${session.score} of ${session.count} correctly.`:'Explain the rule as well as finding the answer.'}</p></div></div></aside></div><TheoryPanel page="practice" onTry={title=>update({topic:title.includes('Function')?'Function Mapping':title.includes('order')?'Hasse Diagrams':'Set Operations'})}/></>;
}
