import { useState } from 'react';
import { BookOpen, Boxes, Copy, Settings2, Sigma, ZoomIn, ZoomOut } from 'lucide-react';
import { useSetTheoryStore } from '../setTheoryStore';
import { cartesianProduct, equivalenceClasses, hasseLevels, coverRelations, type OrderedPair } from '../setTheoryEngine';
import { Card, Button, SetInput, Toggle } from './components';
import { GraphCanvas } from './GraphCanvas';
import { Matrix } from './Relations';
import { analyzeRelation, booleanOrder, checkedPower, keyPair, parseRelation, setText } from './math';
import { TheoryPanel } from './TheoryPanel';
const modes=['Cartesian Product','Power Set','Relation Table','Equivalence Classes'];
export default function Representations(){const s=useSetTheoryStore(),[mode,setMode]=useState(modes[0]),[points,setPoints]=useState(true),[grid,setGrid]=useState(true),[ordered,setOrdered]=useState(true),[zoom,setZoom]=useState(1),[selected,setSelected]=useState<OrderedPair|null>(null),[powerView,setPowerView]=useState('Grouped'),[draft,setDraft]=useState<string|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const a=(mode==='Relation Table'||mode==='Equivalence Classes')?s.relationDomain:s.setA,b=mode==='Relation Table'?s.relationCodomain:s.setB;
 const product=cartesianProduct(a,b);let subsets:string[][]=[],powerError='';try{subsets=checkedPower(a);}catch(e){powerError=(e as Error).message;}
 const relationProps=analyzeRelation(a,a,s.relationPairs),equivalence=relationProps.find(p=>p.name==='Equivalence relation')?.value===true,classes=equivalence?equivalenceClasses(a,s.relationPairs):[];
 const toggle=(x:string,y:string)=>{const p=s.relationPairs,exists=p.some(([u,v])=>u===x&&v===y);s.setRelationPairs(exists?p.filter(([u,v])=>u!==x||v!==y):[...p,[x,y]]);setSelected([x,y]);};
 const reset=()=>{if(mode==='Relation Table'||mode==='Equivalence Classes'){const values=['1','2','3','4'];s.setRelationDomain(values);s.setRelationCodomain(values);s.setRelationPairs(values.map(x=>[x,x]));}else{s.setSetA(['1','2','3','4','5']);s.setSetB(['1','2','3','4']);}setDraft(null);setError('');setZoom(1);setSelected(null);};
 const position=(values:string[],v:string,lo:number,hi:number)=>{const numeric=values.every(x=>x!==''&&Number.isFinite(Number(x))),nums=values.map(Number),min=Math.min(...nums),max=Math.max(...nums);return numeric&&max>min?lo+(Number(v)-min)/(max-min)*(hi-lo):lo+values.indexOf(v)/Math.max(1,values.length-1)*(hi-lo);};
 const result=mode===modes[0]?`|A × B| = ${a.length} × ${b.length} = ${product.length}`:mode===modes[1]?`|P(A)| = 2^${a.length} = ${2**a.length}`:mode===modes[2]?`R contains ${s.relationPairs.filter(([x,y])=>a.includes(x)&&b.includes(y)).length} valid pairs`:`${equivalence?classes.length+' equivalence classes':'The current relation is not an equivalence relation'}`;
 const smallLattice=a.length<=4?booleanOrder(a):null,levels=smallLattice?hasseLevels(smallLattice.domain,smallLattice.pairs):[];
 return <><section className="st-representation-shell"><div className="st-tabs st-mode-tabs">{modes.map(m=><button key={m} className={mode===m?'active':''} onClick={()=>{setMode(m);setZoom(1);setSelected(null);setCopied(false);}}>{m}</button>)}</div><div className="st-representation-layout"><aside className="st-view-menu"><h3>Explore other views</h3>{modes.map((m,i)=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}><span>{['×','{ }','▦','≡'][i]}</span><div><b>{m}</b><p>{['Ordered pairs on a coordinate grid.','All subsets of a set.','Set relations in table form.','Partition a set into classes.'][i]}</p></div><span>›</span></button>)}</aside>
 <Card title={mode} description="Different representations. The same mathematical objects." icon={Boxes}><div className="st-toolbar"><Button onClick={()=>setZoom(z=>Math.min(2,z+.15))}><ZoomIn size={15}/>Zoom In</Button><Button onClick={()=>setZoom(z=>Math.max(.6,z-.15))}><ZoomOut size={15}/>Zoom Out</Button><Button onClick={()=>setZoom(1)}>Reset View</Button></div>
 {mode===modes[0]?<><div className="st-product-scroll"><svg className={grid?'st-product-svg st-grid':'st-product-svg'} viewBox={`${360-360/zoom} ${240-240/zoom} ${720/zoom} ${480/zoom}`} role="img" aria-label="Cartesian product coordinate grid"><path d="M60 50V410H385" stroke="#1e398d" strokeWidth="1.5" fill="none"/><text x="47" y="40" fontWeight="800">B</text><text x="385" y="435" fontWeight="800">A</text>{a.map(x=><text key={x} x={position(a,x,85,360)} y="435" textAnchor="middle" fontSize="13">{x}</text>)}{b.map(y=><text key={y} x="45" y={position(b,y,380,85)+5} textAnchor="middle" fontSize="13">{y}</text>)}{points?product.map(([x,y])=><g key={keyPair([x,y])} role="button" tabIndex={0} aria-label={`Select product pair (${x}, ${y})`} onClick={()=>setSelected([x,y])} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected([x,y]);}}}><circle cx={position(a,x,85,360)} cy={position(b,y,380,85)} r={selected?.[0]===x&&selected?.[1]===y?10:6} fill={['#13c5a3','#249dff','#9759ff','#ed54bc'][b.indexOf(y)%4]} stroke="white" strokeWidth="2"/><title>({x}, {y})</title></g>):null}<rect x="410" y="45" width="285" height="100" rx="15" fill="#edf3ff"/><text x="552" y="78" textAnchor="middle" fontWeight="800" fontSize="23">A × B</text><text x="552" y="112" textAnchor="middle" fontSize="16">{'{(a,b) | a ∈ A, b ∈ B}'}</text><text x="552" y="340" textAnchor="middle" className="st-svg-formula">{selected?`Selected: (${selected[0]}, ${selected[1]})`:result}</text><text x="430" y="375" fontSize="12">Numeric axes use value spacing.</text><text x="430" y="395" fontSize="12">Other labels use categorical positions.</text></svg></div>{ordered?<div className="st-pair-list">{product.map(q=><button key={keyPair(q)} className={selected&&keyPair(selected)===keyPair(q)?'selected':''} onClick={()=>setSelected(q)}>{`(${q[0]}, ${q[1]})`}</button>)}</div>:null}{!product.length?<p className="st-info">If either factor is empty, the product is empty.</p>:null}</>:null}
 {mode===modes[1]?<><div className="st-tabs">{['List','Grouped','Lattice'].map(v=><button key={v} disabled={v==='Lattice'&&a.length>4} className={powerView===v?'active':''} onClick={()=>setPowerView(v)}>{v}</button>)}</div>{powerError?<p role="alert" className="st-error">{powerError}</p>:powerView==='Lattice'&&smallLattice?<GraphCanvas modelKey="set-theory:power-lattice" directed={false} zoom={zoom} nodes={levels.map(n=>{const same=levels.filter(x=>x.level===n.level),i=same.findIndex(x=>x.id===n.id);return {id:n.id,label:n.id,x:360+(i-(same.length-1)/2)*Math.min(100,540/Math.max(1,same.length)),y:430-n.level*350/Math.max(1,a.length)};})} pairs={coverRelations(smallLattice.domain,smallLattice.pairs)}/>:<div className="st-subsets">{powerView==='Grouped'?Array.from({length:a.length+1},(_,k)=><section key={k}><h3>Size {k} · {subsets.filter(x=>x.length===k).length} subsets</h3><div>{subsets.filter(x=>x.length===k).map(v=><span key={JSON.stringify(v)}>{setText(v)}</span>)}</div></section>):subsets.map(v=><span key={JSON.stringify(v)}>{setText(v)}</span>)}</div>}<p className="st-info">Lattice view supports up to four elements; list and grouped views enumerate up to eight.</p></>:null}
 {mode===modes[2]?<Matrix a={a} b={b} pairs={s.relationPairs} selected={selected} onToggle={toggle}/>:null}
 {mode===modes[3]?<>{equivalence?<div className="st-partitions">{classes.map((c,i)=><div key={JSON.stringify(c)} style={{borderColor:['#1686ff','#b16cf4','#06cba2','#ed54bc'][i%4]}}><h3>Class {i+1}</h3><span className="st-formula">{setText(c)}</span></div>)}</div>:<div className="st-empty"><h3>Not an equivalence relation</h3>{relationProps.filter(p=>['Reflexive','Symmetric','Transitive','Valid relation'].includes(p.name)&&!p.value).map(p=><p key={p.name}><b>{p.name}:</b> {p.why}</p>)}</div>}<Button primary onClick={()=>{const values=['1','2','3','4','5','6'];s.setRelationDomain(values);s.setRelationCodomain(values);s.setRelationPairs(cartesianProduct(values,values).filter(([x,y])=>Number(x)%2===Number(y)%2));}}>Load parity partition</Button><label>Equivalence relation pairs<textarea aria-label="Equivalence relation pairs" value={draft??s.relationPairs.map(([x,y])=>`(${x},${y})`).join('; ')} onChange={e=>setDraft(e.target.value)}/></label><Button onClick={()=>{try{s.setRelationPairs(parseRelation(draft??'',a,a));setDraft(null);setError('');}catch(e){setError((e as Error).message);}}}>Apply Relation</Button>{error?<p role="alert" className="st-error">{error}</p>:null}</>:null}</Card>
 <aside className="st-stack"><Card title="Set Input & Options" icon={Settings2}><Button onClick={reset}>Reset Sets</Button><SetInput name="Representation set A" values={a} onChange={mode==='Relation Table'||mode==='Equivalence Classes'?s.setRelationDomain:s.setSetA}/>{mode!==modes[1]&&mode!==modes[3]?<SetInput name="Representation set B" values={b} onChange={mode==='Relation Table'?s.setRelationCodomain:s.setSetB}/>:null}<p>|A|={a.length} {mode!==modes[1]?`· |B|=${b.length}`:''}</p>{mode===modes[0]?<><h3>View Options</h3><Toggle label="Show points" checked={points} onChange={setPoints}/><Toggle label="Show grid" checked={grid} onChange={setGrid}/><Toggle label="Show ordered pairs" checked={ordered} onChange={setOrdered}/></>:null}</Card><Card title="Result & Notation" icon={Sigma}><div className="st-formula">{mode===modes[0]?'A × B = {(a,b) | a∈A, b∈B}':mode===modes[1]?'P(A) = {S | S⊆A}':mode===modes[2]?'Mᵣ[i,j]=1 ⇔ (aᵢ,bⱼ)∈R':'[a] = {b∈A | aRb}'}</div><output className="st-result" aria-live="polite">{result}</output><Button onClick={()=>{void navigator.clipboard.writeText(result).then(()=>setCopied(true)).catch(()=>setCopied(false));}}><Copy size={15}/>{copied?'Copied':'Copy result'}</Button><p className="st-info">{mode===modes[3]?'Equivalence classes are displayed only after checking the full relation.':'All representations are derived from the current finite sets.'}</p></Card></aside></div></section><Card title="Examples & Key Ideas" icon={BookOpen}><div className="st-concept-strip"><div><b>Definition</b><p>A product chooses two entries. A power set chooses a subset. A relation selects product entries.</p></div><div><b>Example</b><p>A={'{1,2,3}'}, B={'{1,2}'} gives |A×B|=6 and |P(A)|=8.</p></div><div><b>Why It Matters</b><p>Represent relations, combinations of choices and partitions without losing the underlying objects.</p></div></div></Card><TheoryPanel page="representations" onTry={title=>setMode(title.includes('Power')||title.includes('Subset')?modes[1]:title.includes('Partition')?modes[3]:title.includes('Table')?modes[2]:modes[0])}/></>;
}
