import { Boxes, Link2, Play, Settings2, Sigma } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { useStudioState } from '../../../studios/phase1/StudioModelProvider';
import { useSetTheoryStore } from '../setTheoryStore';
import { Card, Button, Toggle } from './components';
import { VennCanvas } from './VennCanvas';
import { expressionResult, expressions, setText, type Expression } from './math';
import { membership } from './vennLearningEngine';
import { VennLearning } from './VennLearning';
import { TheoryPanel } from './TheoryPanel';
export default function Venn(){const s=useSetTheoryStore(),[params]=useSearchParams(),[expression,setExpression]=useStudioState<Expression>('set-theory:premium:expression',()=>({union:'A ∪ B',intersection:'A ∩ B',difference:'A − B',complement:'Aᶜ','symmetric-difference':'A △ B'}[params.get('op')||''] as Expression)||'A ∪ B');
 const result=expressionResult(expression,s.universe,s.setA,s.setB,s.setC);
 return <><div className="st-venn-layout"><VennCanvas expression={expression} names={s.names} controller={api=><><aside className="st-stack"><Card title="Current Expression" icon={Sigma}><div className="st-expression-result"><select aria-label="Venn expression" value={expression} onChange={e=>setExpression(e.target.value as Expression)}>{expressions.map(x=><option key={x}>{x}</option>)}</select><output aria-live="polite"><b className="st-formula">{api.concealed?"Predict first":setText(api.paint?s.universe.filter(x=>api.shaded.includes(membership(s,x))):api.override?s.universe.filter(x=>api.override!.includes(membership(s,x))):result)}</b><small>{api.concealed?"Answer hidden":api.paint?"Your shaded regions":api.override?"Learning activity highlight":`${result.length} elements`}</small></output></div></Card>
 <Card title="Quick Relationships" description="Update the sets and their layout together." icon={Link2}><div className="st-relationships">{['disjoint','overlap','subset','equal','triple overlap'].map((p,i)=><button key={p} onClick={()=>api.preset(p)}><span>{['○ ○','◉','⊂','=','◌'][i]}</span><b>{p}</b></button>)}</div></Card>
 <Card title="Elements & Settings" icon={Settings2}><div className="st-two-columns"><Button primary onClick={api.pulse}><Play size={17}/>Pulse Result</Button><Button onClick={api.reset}>Reset Layout</Button><Toggle label="Dragging" checked={api.dragging} onChange={api.setDragging}/><Toggle label="Boundary lock" checked={api.boundary} onChange={api.setBoundary}/></div><label className="st-range">Set A radius <input aria-label="Set A radius" type="range" min="60" max="185" value={api.radius} onChange={e=>api.setRadius(Number(e.target.value))}/><span>{Math.round(api.radius)}</span></label></Card>
 <div className="st-two-columns"><Card title="Set Legend" icon={Boxes}>{[['A','#189aff',s.names[1]],['B','#ef49d6',s.names[2]],['C','#00cba3',s.names[3]],['A ∩ B','#8e5dff','Overlap region'],['A ∩ C','#00b7c8','Overlap region'],['B ∩ C','#f3a136','Overlap region'],['A ∩ B ∩ C','#ffcb25','Triple region'],['U − (A ∪ B ∪ C)','#cce3fc','Outside all sets']].map(([label,color,name])=><p className="st-legend-item" key={label}><i style={{background:color}}/><span>{label} — {name}</span></p>)}</Card><Card title="Set Names" icon={Settings2}>{s.names.map((n,i)=><label key={i} className="st-name-row">{'UABC'[i]} name<input aria-label={`Venn ${'UABC'[i]} name`} value={n} onChange={e=>s.setNames(s.names.map((x,j)=>j===i?e.target.value:x) as typeof s.names)}/></label>)}</Card></div></aside><VennLearning api={api} expression={expression}/></>}/></div><TheoryPanel page="venn-diagram-engine" onTry={title=>{const map:Record<string,Expression>={Union:'A ∪ B',Intersection:'A ∩ B',Difference:'A − B',Complement:'Aᶜ','Symmetric difference':'A △ B','Three-set regions':'A ∩ B ∩ C'};setExpression(map[title]||'A ∪ B');}}/></>;
}
