import { useCallback, useEffect, useId, useMemo, useRef, useState, type PointerEvent } from 'react';
import { Maximize2, RotateCcw, Scan, ZoomIn, ZoomOut } from 'lucide-react';
import { useStudioState } from '../../../studios/phase1/StudioModelProvider';
import { useSetTheoryStore } from '../setTheoryStore';
import { expressionResult, maskMatches, setText, type Expression } from './math';
import { Button } from './components';
import { connectedCircleLayout, defaultCircles, inside, layoutElements, maskAt, type Circle, type Point } from './vennLayout';
import { changeExplanation, membership, regionMeaning, regionName, type Model } from './vennLearningEngine';
type Snapshot={model:Model&{names:[string,string,string,string]};circles:Circle[];points:Record<string,Point>;note:string;beginner:boolean};
const colors=['#189aff','#ef49d6','#00cba3'];
export function VennCanvas({expression,names,compact=false,controller}:{expression:Expression;names:string[];compact?:boolean;controller?:(api:VennApi)=>React.ReactNode}){
 const store=useSetTheoryStore(),uid=useId().replace(/:/g,''),svgRef=useRef<SVGSVGElement>(null),fullRef=useRef<HTMLDivElement>(null);
 const [circles,setCircles]=useStudioState<Circle[]>('set-theory:premium:circles',defaultCircles),[zoom,setZoom]=useState(1),[dragging,setDragging]=useState(true),[boundary,setBoundary]=useState(true),[pulse,setPulse]=useState(0);
 const [positions,setPositions]=useState<Record<string,Point>|null>(null),drag=useRef<{kind:'circle'|'element';id:string;dx:number;dy:number;circle?:Circle;points?:Record<string,Point>}|null>(null);
 const [movementMode,setMovementMode]=useState<'arrange'|'explore'>('arrange'),[notice,setNotice]=useState('Arrange preserves memberships. Explore changes memberships.'),[inspected,setInspected]=useState<string|null>(null),[region,setRegion]=useState(0),[shaded,setShaded]=useState<number[]>([]),[concealed,setConcealed]=useState(false),[patterns,setPatterns]=useState(false),[beginner,setBeginner]=useState(false),[ghost,setGhost]=useState(false),[override,setOverride]=useState<number[]|null>(null),[paint,setPaint]=useState(false);
 const history=useRef<Snapshot[]>([]),cursor=useRef(-1),restoring=useRef(false),[historyVersion,setHistoryVersion]=useState(0),[replaying,setReplaying]=useState(false);
 const [gestureVersion,setGestureVersion]=useState(0);
 const thirdSet=useRef<{circle:Circle;members:string[]}|null>(null);
 const beginnerMode=(enabled:boolean)=>{if(enabled&&!beginner){thirdSet.current={circle:circles[2],members:store.setC};setCircles(circles.map(c=>c.id==='C'?{...c,x:1200,y:1200}:c));store.setSetC([]);}else if(!enabled&&beginner){setCircles(circles.map(c=>c.id==='C'?thirdSet.current?.circle??defaultCircles[2]:c));store.setSetC((thirdSet.current?.members??[]).filter(x=>store.universe.includes(x)));}setBeginner(enabled);setPositions(null);};
 const points=useMemo(()=>{
  // Direct marker edits may cross a border. Reflow only stale roster positions, not each keyboard step.
  if(positions&&store.universe.every(item=>positions[item]&&maskAt(positions[item],circles)===((store.setA.includes(item)?1:0)|(store.setB.includes(item)?2:0)|(store.setC.includes(item)?4:0))))return positions;
  return layoutElements(store.universe,store.setA,store.setB,store.setC,circles,positions??undefined);
 },[store.universe,store.setA,store.setB,store.setC,circles,positions]);
 useEffect(()=>{const model={universe:store.universe,setA:store.setA,setB:store.setB,setC:store.setC,names:store.names};if(restoring.current){restoring.current=false;return;}if(drag.current)return;const prior=history.current[cursor.current];if(prior&&JSON.stringify([prior.model,prior.circles,prior.points,prior.beginner])===JSON.stringify([model,circles,points,beginner]))return;const snapshot={model,circles,points,beginner,note:prior?changeExplanation(prior.model,model,expression):'Starting diagram.'};history.current=[...history.current.slice(0,cursor.current+1),snapshot].slice(-60);cursor.current=history.current.length-1;setNotice(snapshot.note);setHistoryVersion(v=>v+1);},[store.universe,store.setA,store.setB,store.setC,store.names,circles,points,gestureVersion,expression,beginner]);
 const restore=useCallback((index:number)=>{const snapshot=history.current[index];if(!snapshot)return;restoring.current=true;cursor.current=index;setPositions(snapshot.points);setCircles(snapshot.circles);setBeginner(snapshot.beginner);useSetTheoryStore.setState(snapshot.model);setNotice(snapshot.note);setHistoryVersion(v=>v+1);},[setCircles]);
 useEffect(()=>{if(!replaying)return;const timer=window.setInterval(()=>{if(cursor.current>=history.current.length-1)setReplaying(false);else restore(cursor.current+1);},1200);return()=>clearInterval(timer);},[replaying,restore]);
 const toPoint=(event:PointerEvent<SVGElement>)=>{const svg=svgRef.current,m=svg?.getScreenCTM();if(!svg||!m)return null;return new DOMPoint(event.clientX,event.clientY).matrixTransform(m.inverse());};
 const commitMembership=(nextCircles:Circle[],nextPoints:Record<string,Point>)=>{useSetTheoryStore.setState({setA:store.universe.filter(x=>inside(nextPoints[x],nextCircles[0])),setB:store.universe.filter(x=>inside(nextPoints[x],nextCircles[1])),setC:store.universe.filter(x=>inside(nextPoints[x],nextCircles[2]))});};
 const updateCircle=(id:string,change:Partial<Circle>,sourceCircle?:Circle,sourcePoints=points)=>{
  setReplaying(false);
  const before=sourceCircle??circles.find(c=>c.id===id)!;
  const next=circles.map(c=>{if(c.id!==id)return c;const updated={...c,...change};return boundary?{...updated,x:Math.max(updated.r+20,Math.min(700-updated.r,updated.x)),y:Math.max(updated.r+20,Math.min(480-updated.r,updated.y))}:updated;});
  const after=next.find(c=>c.id===id)!,connected=connectedCircleLayout(store.universe,sourcePoints,before,after,next);
  if(movementMode==='arrange'){
   const arranged=layoutElements(store.universe,store.setA,store.setB,store.setC,next,connected.points);
   if(store.universe.some(x=>maskAt(arranged[x],next)!==membership(store,x))){setNotice('This arrangement cannot represent the current sets. Keep the required overlaps, or switch to Explore membership.');return;}
   setPositions(arranged);setCircles(next);return;
  }
  setPositions(connected.points);setCircles(next);useSetTheoryStore.setState({setA:connected.sets[0],setB:connected.sets[1],setC:connected.sets[2]});
 };
 const moveCircle=(id:string,x:number,y:number)=>updateCircle(id,{x,y},drag.current?.kind==='circle'?drag.current.circle:undefined,drag.current?.kind==='circle'?drag.current.points:points);
 const moveElement=(item:string,p:Point)=>{setReplaying(false);const next={...points,[item]:{x:boundary?Math.max(32,Math.min(688,p.x)):p.x,y:boundary?Math.max(35,Math.min(475,p.y)):p.y}};setPositions(next);commitMembership(circles,next);};
 const down=(kind:'circle'|'element',id:string,event:PointerEvent<SVGGElement>)=>{if(!dragging||compact||paint)return;const p=toPoint(event);if(!p)return;event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);const start=kind==='circle'?circles.find(c=>c.id===id)!:points[id];drag.current={kind,id,dx:p.x-start.x,dy:p.y-start.y,circle:kind==='circle'?{...circles.find(c=>c.id===id)!}:undefined,points:kind==='circle'?{...points}:undefined};};
 const move=(event:PointerEvent<SVGGElement>)=>{if(!drag.current)return;const p=toPoint(event);if(!p)return;const d=drag.current;if(d.kind==='circle')moveCircle(d.id,p.x-d.dx,p.y-d.dy);else moveElement(d.id,{x:p.x-d.dx,y:p.y-d.dy});};
 const finishDrag=()=>{drag.current=null;setGestureVersion(v=>v+1);};
 const reset=()=>{setBeginner(false);setCircles(defaultCircles);setPositions(null);setZoom(1);};
 const preset=(name:string)=>{setBeginner(false);let next:Circle[]=defaultCircles.map(c=>({...c}));
  if(name==='disjoint')next=[{id:'A',x:140,y:160,r:100},{id:'B',x:380,y:160,r:100},{id:'C',x:590,y:340,r:100}];
  if(name==='subset')next=[{id:'A',x:280,y:230,r:85},{id:'B',x:280,y:230,r:185},{id:'C',x:580,y:320,r:105}];
  if(name==='equal')next=[{id:'A',x:280,y:230,r:150},{id:'B',x:280,y:230,r:150},{id:'C',x:560,y:300,r:105}];
  if(name==='triple overlap')next=[{id:'A',x:285,y:220,r:160},{id:'B',x:405,y:220,r:160},{id:'C',x:345,y:300,r:160}];
  setCircles(next);setPositions(null);
  const u=store.universe;
  if(name==='disjoint'){store.setSetA(u.filter((_,i)=>i%3===0));store.setSetB(u.filter((_,i)=>i%3===1));store.setSetC(u.filter((_,i)=>i%3===2));}
  else if(name==='equal'){store.setSetA(u.slice(0,Math.ceil(u.length/2)));store.setSetB(u.slice(0,Math.ceil(u.length/2)));store.setSetC(u.slice(Math.ceil(u.length/2)));}
  else if(name==='subset'){store.setSetA(u.slice(0,Math.floor(u.length/3)));store.setSetB(u.slice(0,Math.ceil(u.length*2/3)));store.setSetC(u.slice(Math.ceil(u.length*2/3)));}
  else {store.setSetA(u.filter((_,i)=>i%3!==2));store.setSetB(u.filter((_,i)=>i%3!==0));store.setSetC(u.filter((_,i)=>i%2===0));if(name==='triple overlap'&&u[0]){store.setSetA([...new Set([...u.filter((_,i)=>i%3!==2),u[0]])]);store.setSetB([...new Set([...u.filter((_,i)=>i%3!==0),u[0]])]);store.setSetC([...new Set([...u.filter((_,i)=>i%2===0),u[0]])]);}}
 };
 const api:VennApi={dragging,setDragging,boundary,setBoundary,reset,preset,pulse:()=>setPulse(x=>x+1),radius:circles[0].r,setRadius:r=>updateCircle('A',{r}),movementMode,setMovementMode,notice,inspected,setInspected,region,setRegion,shaded,setShaded,concealed,setConcealed,patterns,setPatterns,beginner,setBeginner:beginnerMode,ghost,setGhost,override,setOverride,paint,setPaint,circles,place:(item,mask)=>{const model={universe:store.universe,setA:store.setA,setB:store.setB,setC:store.setC};const next={...model};(['setA','setB','setC'] as const).forEach((key,i)=>{next[key]=mask&(1<<i)?[...new Set([...model[key],item])]:model[key].filter(x=>x!==item);});const arranged=layoutElements(next.universe,next.setA,next.setB,next.setC,circles,points);if(maskAt(arranged[item],circles)!==mask){setNotice('That region has no space in this layout. Reset the layout or adjust its circles.');return;}setPositions(arranged);useSetTheoryStore.setState(next);setInspected(item);},undo:()=>{setReplaying(false);restore(cursor.current-1);},redo:()=>{setReplaying(false);restore(cursor.current+1);},canUndo:historyVersion>=0&&cursor.current>0,canRedo:cursor.current<history.current.length-1,replay:()=>{restore(0);setReplaying(true);},replaying,stopReplay:()=>setReplaying(false),history:history.current.map(s=>s.note)};
 return <><div ref={fullRef} className={`st-venn-frame ${compact?'compact':''}`}>
 {!compact&&<div className="vl-canvas-result"><b>{paint?'Your shading':override?'Learning highlight':expression}</b><output aria-live="polite">{concealed?'Predict before revealing':setText(paint?store.universe.filter(x=>shaded.includes(membership(store,x))):override?store.universe.filter(x=>override.includes(membership(store,x))):expressionResult(expression,store.universe,store.setA,store.setB,store.setC))}</output></div>}
 {!compact?<div className="st-canvas-tools"><h2>Interactive Venn Diagram</h2><Button onClick={()=>setZoom(z=>Math.min(2,z+.15))}><ZoomIn size={15}/>Zoom In</Button><Button onClick={()=>setZoom(z=>Math.max(.6,z-.15))}><ZoomOut size={15}/>Zoom Out</Button><Button onClick={()=>{setZoom(1);setCircles(defaultCircles);setPositions(null);}}><Scan size={15}/>Fit</Button><Button onClick={reset}><RotateCcw size={15}/>Reset</Button><Button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void fullRef.current?.requestFullscreen().catch(()=>{});}}><Maximize2 size={15}/>Fullscreen</Button></div>:null}
 <svg ref={svgRef} viewBox={`${360-360/zoom} ${250-250/zoom} ${720/zoom} ${500/zoom}`} className="st-venn-svg st-grid" role="img" aria-label="Live three-set Venn diagram" onClick={e=>{const m=svgRef.current?.getScreenCTM();if(!m)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse()),mask=maskAt(p,circles);setRegion(mask);if(paint)setShaded(s=>s.includes(mask)?s.filter(x=>x!==mask):[...s,mask]);}}>

 <rect x="20" y="20" width="680" height="460" rx="15" fill="#f5fbff" fillOpacity=".35" stroke="#c6deff"/>
 <text x="40" y="47" fontWeight="800" fontSize="15">U · {names[0]}</text>
 {ghost&&history.current[Math.max(0,cursor.current-1)]?.circles.map(c=><circle key={`ghost-${c.id}`} cx={c.x} cy={c.y} r={c.r} fill="none" stroke="#475569" strokeDasharray="5 5" opacity=".5"/>)}
 {circles.map((c,i)=><circle key={c.id} data-set-circle={c.id} cx={c.x} cy={c.y} r={c.r} fill={patterns?`url(#${uid}-pattern-${i})`:colors[i]} fillOpacity=".24" stroke={colors[i]} strokeWidth="2" opacity={beginner&&i===2?.12:1}/>)}
 {/* Nested clips implement each Boolean atom exactly, including excluded circles. */}
 <defs>{colors.map((color,i)=><pattern id={`${uid}-pattern-${i}`} key={i} width="10" height="10" patternUnits="userSpaceOnUse" patternTransform={`rotate(${i*45})`}><rect width="10" height="10" fill={color} opacity=".4"/><path d="M0 0V10" stroke={color} strokeWidth={i+2}/></pattern>)}{circles.map(c=><clipPath id={`${uid}-clip-${c.id}`} key={c.id}><circle cx={c.x} cy={c.y} r={c.r}/></clipPath>)}{Array.from({length:8},(_,mask)=><mask key={mask} id={`${uid}-exclude-${mask}`}><rect x="20" y="20" width="680" height="460" fill="white"/>{circles.filter((_,i)=>!(mask&(1<<i))).map(c=><circle key={c.id} cx={c.x} cy={c.y} r={c.r} fill="black"/>)}</mask>)}</defs>
 {Array.from({length:8},(_,mask)=>{if(!(paint?shaded.includes(mask):concealed?false:override?override.includes(mask):maskMatches(expression,mask)))return null;let node:React.ReactNode=<rect key={`pulse-${pulse}`} className={pulse?'st-pulse':''} x="20" y="20" width="680" height="460" fill="#865bff" fillOpacity=".25" mask={`url(#${uid}-exclude-${mask})`}/>;circles.forEach((c,i)=>{if(mask&(1<<i))node=<g clipPath={`url(#${uid}-clip-${c.id})`}>{node}</g>;});return <g key={mask} data-highlight-region={mask}>{node}</g>;})}
 {circles.filter(c=>!beginner||c.id!=='C').map((c,i)=><g key={c.id} tabIndex={compact?-1:0} role="button" aria-label={`Move Set ${c.id}`} onPointerDown={e=>down('circle',c.id,e)} onPointerMove={move} onPointerUp={finishDrag} onPointerCancel={finishDrag} onKeyDown={e=>{if(!dragging||paint)return;const d={ArrowLeft:[-8,0],ArrowRight:[8,0],ArrowUp:[0,-8],ArrowDown:[0,8]}[e.key];if(d){e.preventDefault();moveCircle(c.id,c.x+d[0],c.y+d[1]);}}} className="st-draggable"><circle cx={c.x} cy={c.y} r={c.r} fill="transparent" stroke="transparent" strokeWidth="12"/><text x={c.x+(i===0?-50:i===1?50:0)} y={c.y+(i===2?75:-50)} textAnchor="middle" fontSize="28" fontWeight="900">{c.id}</text><text x={c.x+(i===0?-50:i===1?50:0)} y={c.y+(i===2?95:-28)} textAnchor="middle" fontSize="12" fontWeight="700">{names[i+1]}</text></g>)}
 {store.universe.map(item=><g key={item} data-element={item} data-membership={maskAt(points[item],circles)} tabIndex={compact?-1:0} role="button" aria-label={`Move element ${item}`} aria-description={regionMeaning(membership(store,item))} onFocus={()=>setInspected(item)} onClick={e=>{e.stopPropagation();setInspected(item);setRegion(membership(store,item));if(paint){const m=membership(store,item);setShaded(old=>old.includes(m)?old.filter(x=>x!==m):[...old,m]);}}} onPointerDown={e=>down('element',item,e)} onPointerMove={move} onPointerUp={finishDrag} onPointerCancel={finishDrag} onKeyDown={e=>{const d={ArrowLeft:[-8,0],ArrowRight:[8,0],ArrowUp:[0,-8],ArrowDown:[0,8]}[e.key];if(d&&dragging&&!paint){e.preventDefault();moveElement(item,{x:points[item].x+d[0],y:points[item].y+d[1]});}}} className="st-draggable"><circle cx={points[item].x} cy={points[item].y} r="15" fill="#ffc529" stroke="white" strokeWidth="3"/><text x={points[item].x} y={points[item].y+5} textAnchor="middle" fontSize="13" fontWeight="800" fill="#775600">{item.length>3?item.slice(0,3):item}</text><title>{item}: {regionName(membership(store,item))}</title></g>)}
 </svg><p className="st-canvas-note">Outside all sets: {setText(store.universe.filter(x=>!store.setA.includes(x)&&!store.setB.includes(x)&&!store.setC.includes(x)))}{!compact?' · Choose Arrange to preserve sets or Explore to change them. Select a number to inspect it; arrow keys move it.':''}</p></div>{controller?.(api)}</>;
}
export type VennApi={movementMode:'arrange'|'explore';setMovementMode:(v:'arrange'|'explore')=>void;notice:string;inspected:string|null;setInspected:(v:string|null)=>void;region:number;setRegion:(v:number)=>void;shaded:number[];setShaded:(v:number[])=>void;concealed:boolean;setConcealed:(v:boolean)=>void;patterns:boolean;setPatterns:(v:boolean)=>void;beginner:boolean;setBeginner:(v:boolean)=>void;ghost:boolean;setGhost:(v:boolean)=>void;override:number[]|null;setOverride:(v:number[]|null)=>void;paint:boolean;setPaint:(v:boolean)=>void;circles:Circle[];place:(item:string,mask:number)=>void;undo:()=>void;redo:()=>void;canUndo:boolean;canRedo:boolean;replay:()=>void;replaying:boolean;stopReplay:()=>void;history:string[];dragging:boolean;setDragging:(v:boolean)=>void;boundary:boolean;setBoundary:(v:boolean)=>void;reset:()=>void;preset:(s:string)=>void;pulse:()=>void;radius:number;setRadius:(v:number)=>void};
