import {test,expect} from 'vitest';
import {computeMath} from './kernel';
import {certifyKernel} from './independentVerification';
import {outcome} from './types';
test('rational certificates reject a deliberately incorrect solver answer',()=>{const request={operation:'evaluate' as const,expression:'1/3+1/6'},bad=certifyKernel(request,outcome('verified_exact','2/3'));expect(bad.execution?.status).toBe('internal_error');expect(bad.execution?.evidence.counterexample?.input).toEqual(request);});
test('seeded rational equivalent representations are independently certified',async()=>{let seed=20261009;for(let i=0;i<80;i++){seed=(1664525*seed+1013904223)>>>0;const a=seed%101,b=seed%29+1;const result=await computeMath({operation:'evaluate',expression:a+'/'+b+'+'+a+'/'+b});expect(result.execution?.status).toBe('verified');expect(result.execution?.evidence.level).toBe('exact_symbolic');}});
test('symbolic coefficient certificates and definite-integral bounds use different checks',async()=>{for(const request of [{operation:'expand' as const,expression:'(x+2)^3'},{operation:'differentiate' as const,expression:'3*x^4-2*x'},{operation:'integrate' as const,expression:'2*x+3',args:[-2,5]}])expect((await computeMath(request)).execution?.status).toBe('verified');});
test('malformed, zero denominators, domain violations and nonfinite input remain invalid',async()=>{for(const request of [{operation:'evaluate' as const,expression:'1/0'},{operation:'evaluate' as const,expression:'sqrt(-1)'},{operation:'evaluate' as const,expression:'2+'},{operation:'geometry3d' as const,args:[Infinity]}])expect((await computeMath(request)).execution?.status).toBe('invalid_input');});
test('unsupported certificates do not turn legacy solver confidence into independent proof',async()=>{const result=await computeMath({operation:'solve',expression:'x^2-4=0'});expect(result.execution?.status).toBe('valid_unverified');const sampled=await computeMath({operation:'decimal',expression:'1/3',precision:4});expect(sampled.execution?.evidence.method).toContain('rounding-error');expect(sampled.execution?.evidence.level).toBe('numerical_consistency');const guarded=certifyKernel({operation:'equivalent',expression:'x',other:'0',assumptions:['x = 0']},outcome('verified_exact','false',false));expect(guarded.execution?.status).toBe('valid_unverified');});
