import { chromium } from '@playwright/test';
import fs from 'node:fs';
const routes=['/algebra','/algebraic-structures','/geometry','/calculus','/number-systems','/linear-algebra','/complex-numbers','/mathematical-modelling','/discrete-world','/set-theory','/graph-theory','/probability-statistics','/differential-equations','/math-lab/continued-fractions','/math-lab/famous-problems','/math-lab/stats-inference','/math-lab/special-functions','/math-lab/differential-equations'];
const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));const rows=[];
for(const route of routes){await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:5175'+route);await page.locator('[data-hero]').waitFor({timeout:30000});await page.waitForTimeout(1800);const a=await page.locator('[data-hero] canvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(350);const b=await page.locator('[data-hero] canvas').evaluate(c=>c.toDataURL());if(a===b)errors.push(route+' scene not animating');const id=await page.locator('[data-hero]').getAttribute('data-hero');await page.screenshot({path:`artifacts/studio-heroes/${id}.png`});
 for(const [width,height] of [[1920,1080],[1600,900],[1440,900],[1366,768],[390,844]]){await page.setViewportSize({width,height});await page.waitForTimeout(150);rows.push({route,width,height,...await page.locator('[data-hero]').evaluate(e=>{const r=e.getBoundingClientRect();const canvas=e.querySelector('canvas');return{heroHeight:r.height,heroWidth:r.width,top:r.top,copyBottom:e.querySelector('.cinematic-copy').getBoundingClientRect().bottom,bottom:r.bottom,overflow:document.documentElement.scrollWidth>innerWidth,canvasWidth:canvas.width,canvasHeight:canvas.height,links:[...e.querySelectorAll('a')].map(a=>a.getAttribute('href')),next:!!e.nextElementSibling};})});}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:`artifacts/studio-heroes/mobile-${id}.png`});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(150);const reduced=await page.locator('[data-hero] canvas').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);const frozen=await page.locator('[data-hero] canvas').evaluate(c=>c.toDataURL());if(reduced!==frozen)errors.push(route+' reduced motion not frozen');await page.emulateMedia({reducedMotion:'no-preference'});
}
for(const r of rows){if(r.width>600&&r.bottom>r.height-25)errors.push(r.route+' desktop hero/next section below viewport '+r.width);if(r.copyBottom>r.bottom+1)errors.push(r.route+' copy clipped '+r.width);}
await page.goto('http://127.0.0.1:5175/trigonometry');if(await page.locator('[data-hero]').count())errors.push('Trigonometry hero changed');
fs.writeFileSync('artifacts/studio-heroes/browser-audit.json',JSON.stringify({rows,errors},null,2));console.log(JSON.stringify({pages:routes.length,checks:rows.length,errors,overflow:rows.filter(r=>r.overflow),desktopHeights:[...new Set(rows.filter(r=>r.width>600).map(r=>r.heroHeight))]},null,2));await browser.close();
