import type { MasteryUnit } from './masteryContent';

export type StudioGapContent = { topics: string[]; remainingTools: string; lessons: MasteryUnit[] };
type Seed = [string, string, string, string, string[], string, number, string, string];
/** Authored examples address teaching gaps for their stated cases, not general solver gaps. */
function lesson(base: string, seed: Seed): MasteryUnit {
  const [title, idea, conditions, problem, solution, prompt, answer, misconception, explanation] = seed;
  return {
    id: `gap-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    title, idea, conditions, problem, solution, calculation: { prompt, answer },
    method: ['Identify the assumptions and admissible inputs stated below.', 'Follow the derivation in the worked solution, preserving its restrictions.', 'Check the result against the original definition and explain a boundary case.'],
    misconception, explanation,
    investigation: `Solve the transfer exercise before checking its answer. Then change one assumption in the worked problem and explain which step must change. Use the Studio for supported computations; derive unsupported cases on paper.`,
    href: base,
  };
}
function content(base: string, topics: string[], remainingTools: string, seeds: Seed[]): StudioGapContent {
  return { topics, remainingTools, lessons: seeds.map(seed => lesson(base, seed)) };
}

export const studioGapContent: Record<string, StudioGapContent> = {
  algebra: content('/algebra', ['Parameterized inequalities and sign reversal', 'Rational domains, holes, poles and endpoint practice'], 'A general parameterized inequality practice generator remains a tool gap.', [
    ['Parameter cases in inequalities', 'An inequality containing a parameter can change direction or become identically true or false at a special parameter value.', 'Take a and x real. Treat a=0 before dividing by a.', 'Solve ax≤6 for every real a.', ['If a>0, division gives x≤6/a.', 'If a<0, division reverses the relation: x≥6/a.', 'If a=0, 0≤6 holds for every real x.'], 'For a=−3, the solution is x≥k. Find k.', -2, 'A parameter can always be divided out.', 'Division by zero is undefined; dividing by a negative number reverses order.'],
    ['Canceled factors and rational endpoints', 'Cancellation simplifies values on an existing domain; it does not restore excluded inputs. Track the domain separately from a simplified formula.', 'Use real x and preserve every original denominator zero.', 'Solve (x²−1)/(x−1)≤3.', ['The original denominator excludes x=1.', 'For x≠1 the expression is x+1, giving x≤2.', 'The solution is (−∞,1)∪(1,2]; 1 is a hole, while 2 is included.'], 'For (x²−4)/(x−2)≤5, what is the included upper endpoint?', 3, 'Canceling a factor makes its zero an admissible input.', 'The simplified expression agrees only where the original expression was defined.'],
  ]),
  'algebraic-structures': content('/algebraic-structures', ['Permutation orders, products and parity', 'Finite extension arithmetic and irreducibility'], 'Dedicated permutation and extension-field interactive models remain incomplete.', [
    ['Disjoint cycles and permutation order', 'Disjoint cycles commute and return to the identity together after the least common multiple of their lengths. Parity counts transpositions.', 'Compose right to left; include fixed points when describing the underlying set.', 'Find the order and parity of (123)(45) in S₅.', ['The cycles have lengths 3 and 2 and are disjoint.', 'The order is lcm(3,2)=6.', 'A 3-cycle uses two transpositions and a 2-cycle uses one; the permutation is odd.'], 'Order of the disjoint permutation (1234)(567)?', 12, 'The order of disjoint cycles is always their product.', 'It is their least common multiple; equal or overlapping prime factors reduce that value.'],
    ['Arithmetic in a four-element field', 'A polynomial quotient over a field is a field when the defining polynomial is irreducible. Reduction gives a concrete arithmetic rule.', 'Work over F₂, so 1+1=0; use α²+α+1=0.', 'Find the inverse of α in F₂[α]/(α²+α+1).', ['The polynomial is 1 at both 0 and 1, so the quadratic has no root and is irreducible.', 'Reduction gives α²=α+1.', 'Then α(α+1)=α²+α=1, so α⁻¹=α+1.'], 'How many elements are in this degree-2 extension of F₂?', 4, 'Every polynomial quotient over a field is a field.', 'For a reducible polynomial, its proper factors can multiply to zero in the quotient.'],
  ]),
  geometry: content('/geometry', ['Formal proof steps and theorem hypotheses', 'Conic construction constraints and degeneracies'], 'Constraint-preserving conic construction tools still need expansion.', [
    ['A complete midpoint theorem proof', 'A coordinate proof translates geometric hypotheses into algebra, then converts the result back into the claimed geometric relationship.', 'ABC is a nondegenerate triangle; D and E are the midpoints of AB and AC.', 'Prove DE is parallel to BC and half its length.', ['Translate A to the origin and write B=b, C=c.', 'The midpoint definitions give D=b/2 and E=c/2.', 'E−D=(c−b)/2 is a positive scalar multiple of C−B, proving parallelism and the half-length result.'], 'If BC has length 14, what is DE?', 7, 'An accurate diagram is sufficient proof of parallelism.', 'The vector identity follows from the midpoint hypotheses and holds for every nondegenerate triangle.'],
    ['Ellipse construction feasibility', 'An ellipse with two distinct foci is the locus whose sum of focal distances is a fixed number greater than the distance between the foci.', 'Use focal separation 2c and distance sum 2a. A nondegenerate ellipse requires a>c>0.', 'Place foci at (−3,0),(3,0) and require a distance sum of 10.', ['Here c=3 and a=5, so the condition a>c holds.', 'Compute b²=a²−c²=25−9=16.', 'The ellipse is x²/25+y²/16=1. A sum of 6 collapses to the focal segment; a smaller sum is impossible.'], 'With focal separation 8 and sum 10, find b².', 9, 'Any string length produces an ellipse around two foci.', 'The triangle inequality requires the sum to exceed the focal separation for a nondegenerate ellipse.'],
  ]),
  trigonometry: content('/trigonometry', ['Fourier convergence at jumps and Gibbs behavior', 'Polar curves, negative radii and area practice'], 'Broader generated Fourier and polar-curve exercises remain a tool gap.', [
    ['Fourier jump values and overshoot', 'For a piecewise smooth periodic signal, Fourier sums converge at a jump to the average of its one-sided limits. Overshoot near a jump need not vanish in height.', 'Assume a periodic piecewise smooth function with finite one-sided limits.', 'A signal jumps from −2 to 4 at t=0. Determine the Fourier limit there.', ['The left limit is −2 and the right limit is 4.', 'Their average is (−2+4)/2=1, regardless of the assigned value at t=0.', 'More terms narrow the oscillatory region; they do not guarantee uniform convergence across the jump.'], 'Fourier limit at a jump from 1 to 7?', 4, 'Adding harmonics removes every overshoot in height.', 'Gibbs overshoot persists near jumps while its spatial extent shrinks.'],
    ['Area of a polar rose petal', 'Polar area accumulates one half of the squared radius over an angular interval. Negative radii describe points in the opposite direction.', 'Use radians and an interval tracing exactly one petal; avoid counting retraced regions twice.', 'Find one petal area for r=2cos(2θ).', ['A petal around the positive x-axis runs from −π/4 to π/4 where r≥0.', 'Area is (1/2)∫4cos²(2θ)dθ=∫(1+cos(4θ))dθ.', 'The sine boundary terms vanish, leaving π/2.'], 'For r=4cos(2θ), one petal area is kπ. Find k.', 2, 'A negative polar radius is an invalid point.', 'It places the point |r| units along angle θ+π; tracing and multiplicity still matter.'],
  ]),
  calculus: content('/calculus', ['Symbolic convergence tests and endpoint reasoning', 'Vector-calculus theorem hypotheses and proof practice'], 'General symbolic convergence classification and automatic proof assessment remain incomplete.', [
    ['A parameterized logarithmic series', 'The integral test connects a positive decreasing series to an improper integral. A substitution can reveal a parameter threshold invisible to the ratio test.', 'Study Σ from n=2 of 1/[n(log n)^p] for real p; the terms are eventually decreasing.', 'Find precisely which p make the series converge.', ['Compare with ∫₂^∞ dx/[x(log x)^p].', 'Set u=log x, obtaining ∫log2^∞ u^(−p)du.', 'The power integral converges exactly for p>1; at p=1 it diverges logarithmically.'], 'Does p=2 converge? Enter 1 for yes, 0 for no.', 1, 'A ratio-test limit of 1 proves divergence.', 'The ratio test is inconclusive at 1; another comparison or integral test is needed.'],
    ['Divergence theorem with a flux check', 'The divergence theorem equates outward flux through a closed surface with the volume integral of divergence, under the required smoothness conditions.', 'F is continuously differentiable near the solid and the boundary is piecewise smooth with outward orientation.', 'Compute outward flux of F=(x,y,z) through the unit cube [0,1]³.', ['The divergence is 1+1+1=3.', 'The cube has volume 1, so its volume integral is 3.', 'The three faces at coordinate 1 each contribute 1 and the faces at 0 contribute 0, confirming total flux 3.'], 'Outward flux of (x,y,z) through [0,2]³?', 24, 'The divergence theorem applies to an open surface without extra boundary faces.', 'Close the surface and account for all face contributions before using the theorem.'],
  ]),
  'number-systems': content('/number-systems', ['Exact versus floating representations', 'Rounding modes, propagated error and cancellation'], 'Arbitrary-precision interactive representation and rounding controls remain incomplete.', [
    ['Which fractions terminate in a base', 'A reduced fraction terminates in base b exactly when every prime factor of its denominator divides b. This explains why finite decimal values may be infinite in binary.', 'Reduce the fraction first; the base is an integer b≥2.', 'Compare representations of 1/10 in decimal and binary.', ['The denominator is 10=2×5.', 'Both factors divide base 10, so decimal representation terminates at 0.1.', 'Base 2 has no factor 5, so binary representation repeats; finite binary floating arithmetic approximates it.'], 'How many decimal places are needed for the shortest exact decimal of 1/8?', 3, 'Every short decimal is exactly stored in binary floating point.', 'Denominators with factors other than 2 cannot terminate in binary.'],
    ['Rounding bounds and cancellation', 'Rounding to a fixed decimal place has a known absolute error bound. Subtracting nearby rounded values can create a large relative error.', 'Use rounding to nearest; a specified tie rule is needed at exact halfway values.', 'Round x=1.2344 and y=1.2336 to three decimal places, then subtract.', ['Both numbers round to 1.234, so the rounded difference is 0.', 'The exact difference is 0.0008.', 'Each input error is at most 0.0005; the difference error can be at most 0.001, much larger relative to the small true difference.'], 'Maximum absolute rounding error at two decimal places?', 0.005, 'Small relative errors in inputs guarantee a small relative error in their difference.', 'Cancellation can make the true difference tiny, amplifying the relative error.'],
  ]),
  'linear-algebra': content('/linear-algebra', ['Geometric interpretation of SVD and singular directions', 'Conditioning and perturbation feedback'], 'Advanced workbenches still need graphical overlays for singular vectors and perturbations.', [
    ['SVD as stretching an orthogonal basis', 'The singular values describe how a linear transformation stretches orthogonal input directions. They are square roots of eigenvalues of AᵀA.', 'Use real matrices; zero singular values indicate directions collapsed to zero.', 'Describe the image of the unit circle under A=diag(3,1).', ['AᵀA=diag(9,1), so singular values are 3 and 1.', 'The input axes map to orthogonal output axes with those lengths.', 'The image is an ellipse with semi-axes 3 and 1, area 3π, and condition number 3.'], 'Largest singular value of diag(5,2)?', 5, 'Singular values are always signed eigenvalues of A.', 'Singular values are nonnegative and exist for rectangular matrices as well.'],
    ['Sensitivity in a nearly singular system', 'A small singular value makes one output direction weak, so recovering an input from that output can amplify measurement errors.', 'Use the Euclidean norm and invertible A; a condition number gives a worst-case relative sensitivity bound.', 'For A=diag(1,0.001), solve Ax=(1,0.001), then change the second right-hand component to 0.002.', ['Initially x=(1,1).', 'After the change x=(1,2), despite a right-hand change of only 0.001.', 'The singular-value ratio is 1000; the second coordinate is especially sensitive.'], 'Condition number of diag(1,0.01)?', 100, 'A small residual always implies a small solution error.', 'An ill-conditioned matrix can map a large solution error to a small residual.'],
  ]),
  'complex-numbers': content('/complex-numbers', ['Contour integrals, residues and orientation', 'Branch cuts and analytic continuation along paths'], 'General contour models and interactive analytic continuation remain incomplete.', [
    ['A contour integral from a residue', 'A positively oriented contour integral around an isolated pole is 2πi times the residue, when the residue theorem hypotheses hold.', 'The contour is closed, avoids poles, and bounds a region where the function is meromorphic with finitely many poles.', 'Integrate (z+1)/z around the counterclockwise unit circle.', ['Write (z+1)/z=1+1/z.', 'The constant term integrates to zero and the residue at 0 is 1.', 'The integral is 2πi. Reversing orientation gives −2πi.'], 'The counterclockwise integral of 3/z is kπi. Find k.', 6, 'A contour passing through a pole has an ordinary residue-theorem integral.', 'The ordinary contour integral is undefined there; deforming or prescribing a principal value changes the problem.'],
    ['Continuing a logarithm around zero', 'Local branches of the logarithm can be continued along a path avoiding zero, but one full turn changes the continued value by 2πi.', 'Distinguish continuous continuation along a path from the principal branch, whose cut lies on the nonpositive real axis.', 'Start log(1)=0 and continue along z(t)=e^(it), 0≤t≤2π.', ['A continuous argument along this path is t.', 'The continued logarithm is it.', 'At the endpoint z=1 the continued value is 2πi; the principal value there is still 0.'], 'After two counterclockwise turns, the continued value is kπi. Find k.', 4, 'Returning to the same point forces the continued logarithm to its starting value.', 'Winding around the branch point changes the sheet; a globally single-valued logarithm cannot exist on the punctured plane.'],
  ]),
  'mathematical-modelling': content('/mathematical-modelling', ['Observed-data calibration and residuals', 'Holdout validation, leakage and extrapolation'], 'External-data fitting and reusable out-of-sample validation workflows remain incomplete.', [
    ['Calibrating a model from observations', 'Calibration estimates parameters from observed data; residuals measure discrepancies in the response units. A fitted parameter depends on the assumed model family.', 'For y=ax with independent equal-variance errors, use unweighted least squares and keep units consistent.', 'Fit y=ax to observations (1,2) and (2,5).', ['Minimize (2−a)²+(5−2a)².', 'The normal equation gives a=(1×2+2×5)/(1²+2²)=12/5=2.4.', 'Residuals are −0.4 and 0.2; their squared sum is 0.2. A residual pattern can suggest a missing intercept.'], 'Fit y=ax to (1,3),(2,6). Find a.', 3, 'The fitted coefficient proves the physical law is correct.', 'A fit estimates a coefficient within an assumed family; alternatives and residual structure still need evaluation.'],
    ['Holdout error and information leakage', 'Evaluate prediction on observations withheld from fitting and model selection. Split strategy must reflect how predictions will be used.', 'For time series, train on earlier observations and test later ones. Fit preprocessing only on training data.', 'A holdout has observed responses 3,5 and predictions 2,7. Compute mean squared error.', ['Residuals are 1 and −2.', 'Their squares are 1 and 4.', 'The holdout MSE is (1+4)/2=2.5; using this set repeatedly for tuning makes it a validation set, requiring a fresh final test.'], 'Holdout MSE for residuals 2 and 0?', 2, 'Choosing a model on test data leaves test performance unbiased.', 'Model selection uses that information, so the same data no longer provide an independent final evaluation.'],
  ]),
  'discrete-world': content('/discrete-world', ['Algorithm traces and invariants', 'Proof exercises with explicit reasoning checks'], 'More animated traces and automatically assessed proof exercises remain incomplete.', [
    ['Extended Euclid with an invariant', 'The Euclidean algorithm preserves the gcd while reducing remainders. Back substitution expresses that gcd as an integer combination of the original inputs.', 'Use positive integer inputs and exact integer division.', 'Find gcd(84,30) and a Bézout identity.', ['84=2×30+24 and 30=24+6.', '24=4×6, so the gcd is 6.', 'Back substitute: 6=30−24=30−(84−2×30)=3×30−84.'], 'Find gcd(99,36).', 9, 'The final quotient is the gcd.', 'The last nonzero remainder is the gcd; the final quotient has a different role.'],
    ['A divisibility induction proof', 'Induction proves a claim for every integer in a specified range when both the base case and implication to the next case are justified.', 'Consider integers n≥0; demonstrate divisibility using an integer multiple.', 'Prove 3 divides 4ⁿ−1 for every n≥0.', ['For n=0, 4⁰−1=0 is divisible by 3.', 'Assume 4ᵏ−1=3m for some integer m.', 'Then 4ᵏ⁺¹−1=4(4ᵏ−1)+3=3(4m+1), completing the step.'], 'Compute (4³−1)/3.', 21, 'A proof of the induction step alone proves the claim.', 'Without a base case there is no established starting point for the implication chain.'],
  ]),
  'set-theory': content('/set-theory', ['Cantor cardinality proof beyond examples', 'Axioms, separation and Russell paradox'], 'Infinite-cardinality and axiomatic coverage still needs a broader advanced course.', [
    ['Cantor theorem for any power set', 'No function from a set A onto its power set can be surjective. The diagonal set gives a proof independent of whether A is finite or infinite.', 'Let f:A→P(A) be any function; use separation to form a subset of A.', 'Prove f cannot enumerate every subset of A.', ['Define D={a∈A : a∉f(a)}.', 'If f were onto, D=f(d) for some d∈A.', 'Then d∈D iff d∉D, a contradiction; hence no such surjection exists.'], 'For a finite A with 3 elements, how many elements does P(A) have?', 8, 'An infinite set and its power set must have equal cardinality.', 'Cantor diagonalization prohibits a surjection onto the power set for every set.'],
    ['Separation and the Russell obstruction', 'Axiomatic set theory permits selecting elements from an existing set by a predicate; it does not permit unrestricted formation of a set from any predicate.', 'This is a distinction between separation in ZF and unrestricted comprehension; no universal set is assumed.', 'Why does R={x : x∉x} cause a contradiction if treated as a set of all such objects?', ['If R∈R, its defining condition forces R∉R.', 'If R∉R, its defining condition forces R∈R.', 'Separation instead starts from a given A and forms {x∈A : x∉x}; it does not assert the unrestricted R exists.'], 'Number of subsets of the empty set?', 1, 'The paradox shows every use of set-builder notation is contradictory.', 'Restricted separation within an existing set avoids the unrestricted existence claim.'],
  ]),
  'graph-theory': content('/graph-theory', ['Matching augmenting paths and Hall obstructions', 'Residual networks, rerouting and min-cut certificates'], 'Dedicated matching and flow animations within this Studio remain incomplete.', [
    ['Augmenting a bipartite matching', 'An alternating path beginning and ending at unmatched vertices increases matching size by one when its matched and unmatched edges are exchanged.', 'Use a bipartite graph with left {a,b}, right {1,2}; edges a−1,a−2,b−1.', 'Start with the matching {a−1}. Find a matching covering both left vertices.', ['The alternating path b−1−a−2 begins and ends unmatched.', 'Remove a−1 and add b−1 and a−2.', 'The matching now has size 2. Greedily refusing to change a−1 would miss this improvement.'], 'How much does one augmenting path increase matching size?', 1, 'A chosen matching edge can never be replaced.', 'Augmenting paths rearrange earlier choices while increasing the total matching.'],
    ['Residual capacity and a cut certificate', 'Residual edges record how flow can be increased or canceled. A feasible flow equal to a cut capacity is certified maximum.', 'Directed capacities are nonnegative; conserve flow at every vertex except source and sink.', 'Edges s→a=3,s→b=2,a→t=2,b→t=3,a→b=1. Find maximum flow.', ['Send 2 along s−a−t and 2 along s−b−t.', 'Send 1 along s−a−b−t, reaching total 5.', 'The cut leaving s has capacity 3+2=5; no larger flow is possible. Reverse residual edges allow canceling previous choices.'], 'If the two edges out of s have capacities 4 and 2, what upper bound does this cut give?', 6, 'An original reverse edge must exist to cancel a flow.', 'Residual networks include reverse capacity from already assigned flow, even without an original reverse edge.'],
  ]),
  'probability-statistics': content('/probability-statistics', ['Assumption diagnostics and model selection', 'Power, effect sizes and sample-size planning'], 'Automated diagnostics and power controls remain tool gaps; the enhancement manifest and ratings need a separate implementation audit.', [
    ['Diagnosing assumptions before inference', 'A statistical method has assumptions about sampling, dependence, variances and distribution shape. Plots and study design provide different kinds of evidence.', 'A paired t procedure uses independent pairs and approximately normal differences for a small sample; it does not require equal before/after variances.', 'Before: 4,8,12; after: 5,10,15. Identify the analyzed observations.', ['Compute within-pair differences 1,2,3.', 'The mean difference is 2 and sample variance is [(−1)²+0²+1²]/2=1.', 'Assess independence from the design and distribution of differences; three observations provide weak evidence about normality.'], 'Sample variance of differences 2,4,6?', 4, 'A normal-looking histogram establishes independent sampling.', 'Independence concerns data collection and dependence structure; a histogram cannot establish it.'],
    ['Planning power for a mean shift', 'Power is the probability of rejecting the null under a specified alternative. A larger meaningful shift or larger sample can improve power.', 'For this planning approximation use independent normal observations, known σ, a two-sided α=0.05 test, and target power 0.80.', 'Use n≈[(1.96+0.84)σ/δ]² with σ=10 and meaningful δ=5.', ['The standardized multiplier is (2.8×10)/5=5.6.', 'Squaring gives n≈31.36, so plan at least 32 observations.', 'This z-based formula is approximate; an unknown-variance t design or different alternative requires a different calculation.'], 'Using the same formula with σ=10 and δ=2, find the planned n.', 196, 'A nonsignificant result proves the effect is zero.', 'Low power can miss a meaningful effect; report estimates, intervals and the planned detectable difference.'],
  ]),
  'differential-equations': content('/differential-equations', ['General initial data as PDE mode expansions', 'Boundary-value discretization and residual checking'], 'General PDE and boundary-value numerical solvers remain incomplete.', [
    ['Heat evolution from multiple modes', 'Linearity permits summing separated solutions. General initial profiles require coefficients in an appropriate eigenfunction expansion, rather than a single chosen mode.', 'Use u_t=u_xx on [0,π], zero endpoint values, and the stated finite sine expansion.', 'Evolve initial profile u(x,0)=2sin x−sin(3x).', ['The first mode acquires factor e^(−t).', 'The third mode acquires factor e^(−9t).', 'Thus u=2e^(−t)sin x−e^(−9t)sin(3x). Both boundary values vanish and substitution verifies the PDE.'], 'Decay-rate coefficient of sin(4x) for this PDE?', 16, 'Every initial profile decays with the same exponential rate.', 'Each spatial eigenmode has its own rate; high-frequency modes decay faster for the heat equation.'],
    ['A finite-difference boundary problem', 'Finite differences turn a boundary-value problem into simultaneous equations for interior values; boundary conditions contribute to the right-hand side.', 'Use −u″=2 on [0,1], u(0)=u(1)=0, and uniform spacing h=1/2.', 'Approximate u at the only interior node x=1/2.', ['Replace −u″ by (2u₁−u₀−u₂)/h².', 'With u₀=u₂=0 and h²=1/4, solve 8u₁=2.', 'Therefore u₁=1/4, matching the exact quadratic u=x(1−x) at this node; exactness here does not hold for arbitrary forcing.'], 'For −u″=4 with the same grid and endpoints, find u₁.', 0.5, 'Agreement at one grid node proves every finite-difference solve is exact.', 'This stencil is exact for the quadratic case; general problems require refinement and error analysis.'],
  ]),
  'continued-fractions': content('/math-lab/continued-fractions', ['Quadratic periodic expansions and exact recurrences', 'Pell solutions and minimality reasoning'], 'General quadratic-irrational and Pell solvers remain incomplete.', [
    ['Periodicity from a quadratic identity', 'An algebraic identity can expose the repeating complete quotient of a quadratic irrational without relying on rounded decimal digits.', 'Take the positive square root and use exact algebra; floating truncation alone cannot prove periodicity.', 'Derive the continued fraction of √3.', ['The integer part is 1; 1/(√3−1)=(√3+1)/2 has integer part 1.', 'Its remaining fraction is (√3−1)/2; reciprocation gives √3+1 with integer part 2.', 'Subtracting 2 returns √3−1, so the complete-quotient process repeats: √3=[1;1,2,1,2,…].'], 'Second convergent [1;1] as a numeric value?', 2, 'A decimal expansion that appears repetitive proves continued-fraction periodicity.', 'Exact recurrence or a theorem supplies proof; approximate digits can be misleading.'],
    ['Building further Pell solutions', 'Multiplying units x+y√d with norm x²−dy²=1 generates new integer solutions of the same Pell equation.', 'Use positive nonsquare integer d and exact integer arithmetic; generation alone needs additional theory to establish completeness.', 'Square the solution 3+2√2.', ['(3+2√2)²=9+12√2+8=17+12√2.', 'Its norm is 17²−2×12²=289−288=1.', 'Thus (17,12) solves x²−2y²=1; multiplying again generates further solutions.'], 'Compute x for the squared unit 2+√3.', 7, 'Every generated Pell solution is necessarily the smallest positive solution.', 'Powers grow; minimality of a fundamental solution requires checking smaller possibilities or using continued-fraction theory.'],
  ]),
  'famous-problems': content('/math-lab/famous-problems', ['Precise conjectures and limits of experiments', 'Complete accessible theorem proofs'], 'The atlas still needs a broader referenced proof library and curated experiment explanations.', [
    ['What a conjecture experiment can establish', 'A finite search establishes results only over the tested domain. A universal statement needs a proof; one valid counterexample refutes it.', 'Define the exact range and arithmetic used. Treat conjectures as questions rather than asserting current status without a checked reference.', 'Test the Collatz rule from 6 until reaching 1.', ['The sequence is 6,3,10,5,16,8,4,2,1.', 'This establishes termination for starting value 6 using eight transitions.', 'It establishes nothing by itself about all other positive starting values or the universal conjecture.'], 'Number of transitions from 3 to 1 in this sequence?', 7, 'Testing a large finite range proves all positive integers terminate.', 'There are infinitely many untested inputs; a proof must supply a universal argument.'],
    ['Euclid proof of infinitely many primes', 'A contradiction proof can turn an alleged complete finite list into an integer with a prime divisor outside that list.', 'Every integer greater than 1 has a prime divisor; the constructed integer need not itself be prime.', 'Suppose p₁,…,pₖ list all primes. Derive a contradiction.', ['Form N=p₁p₂…pₖ+1, which is greater than 1.', 'Division by any listed prime leaves remainder 1, so none divides N.', 'A prime divisor of N exists and is absent from the list, contradicting completeness.'], 'For the proposed list 2,3,5, what is product plus one?', 31, 'The product of listed primes plus one is always prime.', 'It may be composite; the proof needs only a prime factor not present in the list.'],
  ]),
  'stats-inference': content('/math-lab/stats-inference', ['Welch comparisons and uncertainty', 'Equivalence tests versus failure to reject'], 'A broader interactive procedure selector and diagnostic workflow remain incomplete.', [
    ['Welch standard error for two means', 'Independent mean estimates have additive variances. Welch inference accommodates unequal estimated variances and uses an adjusted degrees-of-freedom approximation.', 'Samples are independent; small-sample use requires reasonable distributional assumptions. Do not use this formula for paired data.', 'Take n₁=n₂=25, s₁=3, s₂=4. Find the standard error of the mean difference.', ['The estimated variance is s₁²/n₁+s₂²/n₂=9/25+16/25=1.', 'The standard error is √1=1.', 'A confidence interval also needs a t critical value with Welch degrees of freedom; the standard error alone is not an interval.'], 'With n₁=n₂=25 and s₁=s₂=5, what is the variance of the estimated difference?', 2, 'Equal sample sizes imply equal population variances.', 'The two questions are independent; Welch uses separate variance estimates.'],
    ['Equivalence within a meaningful margin', 'Equivalence asks whether an effect is contained inside prespecified practical margins. It differs from testing an exactly zero difference.', 'For two one-sided tests at α=0.05, compare a valid 90% interval to the equivalence margins; choose margins before viewing results.', 'Margins are (−2,2) and the valid 90% interval is (−0.5,1.5).', ['The entire interval lies strictly inside the chosen margins.', 'Both one-sided null hypotheses are rejected, supporting equivalence at the specified level.', 'An interval (−3,1) would not support equivalence even though it includes zero.'], 'Does interval (−1,1) fit inside margins (−2,2)? Enter 1 for yes, 0 for no.', 1, 'Failure to reject a zero difference proves equivalence.', 'An imprecise interval can include both zero and large meaningful effects.'],
  ]),
  'special-functions': content('/math-lab/special-functions', ['Recurrence formulas and orthogonality', 'Numerical truncation bounds and domain checks'], 'Interactive recurrence, orthogonality and numerical-error tools remain incomplete.', [
    ['Legendre recurrence and orthogonality', 'Legendre polynomials satisfy a three-term recurrence and are orthogonal under unit weight on [−1,1]. Orthogonality isolates expansion coefficients.', 'Use P₀=1, P₁=x and (n+1)Pₙ₊₁=(2n+1)xPₙ−nPₙ₋₁.', 'Derive P₂ and verify its integral against P₀.', ['For n=1, 2P₂=3x²−1, so P₂=(3x²−1)/2.', 'Integrate from −1 to 1: [x³−x]/2 at the endpoints gives 0.', 'This verifies orthogonality with P₀ in this case; general orthogonality follows from the differential-equation structure.'], 'Value of P₂(0)?', -0.5, 'Orthogonal polynomials have zero products at every point.', 'The weighted integral of their product is zero; pointwise products generally are not.'],
    ['An explicit error bound for erf', 'A truncated alternating series can bound a special-function approximation when term magnitudes decrease. A displayed decimal should be accompanied by a justified bound.', 'For 0≤x≤1, use erf(x)=(2/√π)Σ(−1)ⁿx^(2n+1)/[n!(2n+1)].', 'Approximate erf(1/2) using the first two terms.', ['The inner sum is x−x³/3=1/2−1/24=11/24.', 'The approximation is (2/√π)(11/24).', 'The next inner term is x⁵/10=1/320; the absolute error is at most (2/√π)/320 by the alternating-series bound.'], 'At x=1, what is the first omitted inner term after x−x³/3?', 0.1, 'More displayed digits guarantee greater numerical accuracy.', 'Accuracy depends on truncation and rounding error, not formatting precision.'],
  ]),
  'advanced-differential-equations': content('/math-lab/differential-equations', ['Stiffness and numerical stability beyond pictures', 'Boundary forcing and steady-state decomposition'], 'This companion still lacks general numerical and boundary solvers; the main Studio contains the broader method collection.', [
    ['Stability versus accuracy for a stiff mode', 'A numerical method can amplify a decaying exact solution unless its step lies within the stability region. Stability alone does not guarantee acceptable accuracy.', 'For y′=−λy with λ>0 and explicit Euler, require |1−λh|<1 for strict asymptotic decay.', 'Determine the stable step range for y′=−100y.', ['Euler multiplies each iterate by 1−100h.', 'The condition −1<1−100h<1 gives 0<h<0.02.', 'At h=0.02 the factor is −1, so magnitude fails to decay; h=0.03 causes alternating growth.'], 'Largest strict-stability threshold 2/λ when λ=50?', 0.04, 'A stable numerical trajectory is automatically accurate.', 'A step near the stability boundary can oscillate and badly approximate the exact exponential decay.'],
    ['Nonzero heat boundaries and a steady part', 'Subtracting a steady solution turns nonhomogeneous fixed boundary data into homogeneous boundary conditions for a transient problem.', 'Use u_t=u_xx on [0,1], u(0,t)=1,u(1,t)=3 and compatible initial profile 1+2x+sin(πx).', 'Find the steady and transient parts.', ['Solve s″=0 with the endpoints, giving s(x)=1+2x.', 'Set v=u−s, which satisfies zero endpoint values and initial sin(πx).', 'Thus u=1+2x+e^(−π²t)sin(πx), approaching the steady linear temperature.'], 'Steady temperature at x=1/2?', 2, 'Sine modes alone satisfy any nonzero boundary values.', 'The sine modes vanish at the endpoints; a steady or lifting part must supply nonzero boundary data.'],
  ]),
};
