import { useState } from 'react';
import { GuidedCourse } from './GuidedCourse';
import StudioGapChecklist from './StudioGapChecklist';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { chaptersFor, curriculumStudios } from './curriculumCatalog';
import { ChallengeBox, fmt } from '../mockup/studioLabKit';
import { useStudioState } from '../phase1/StudioModelProvider';
import { supplementalDefaults, supplementalModel } from './supplementalModels';
import './studioLearning.css';
export default function StudioCurriculum(){
  const {studioId}=useParams(),[params,setParams]=useSearchParams(),[query,setQuery]=useState('');
  const studio=curriculumStudios.find(s=>s.id===studioId);
  if(!studio)return <main className="studio-curriculum"><h1>Studio learning paths</h1><p>Start with the prerequisites, study the chapters and apply each idea in its linked lab.</p><div className="studio-curriculum-grid">{curriculumStudios.map(s=><Link key={s.id} to={`/studios/${s.id}/curriculum`}><h2>{s.name}</h2><p>{s.scope}</p><span>{chaptersFor(s.id).length} chapters</span></Link>)}</div></main>;
  const chapters=chaptersFor(studio.id),active=chapters.find(c=>c.id===params.get('topic'))||chapters[0],filtered=chapters.filter(c=>`${c.title} ${c.copy.principle}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="studio-curriculum"><header><div><Link to="/studios/curriculum">All learning paths</Link><h1>{studio.name} · Learning path</h1><p>{studio.scope}</p><p><b>Prerequisites:</b> {studio.prerequisites}</p></div><Link to={studio.base}>Open studio</Link></header><p className="studio-scope-note">Core school and undergraduate concepts, with introductions to advanced topics. A worked example is evidence for its stated case; a general claim needs proof and its assumptions.</p><StudioGapChecklist studioId={studio.id}/><GuidedCourse key={studio.id} studioId={studio.id}/><details className="guided-reference" open={!!params.get('topic')}><summary>Full reference library · {chapters.length} chapters</summary><div className="studio-curriculum-layout"><aside><label>Search chapters<input aria-label="Search chapters" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav aria-label="Curriculum chapters">{filtered.map((c,i)=><button key={c.id} type="button" aria-current={active?.id===c.id?'page':undefined} onClick={()=>{const next=new URLSearchParams(params);next.set('topic',c.id);setParams(next);}}><span>{i+1}.</span> {c.title}</button>)}</nav>{!filtered.length?<p>No chapters match.</p>:null}</aside>{active?<article key={active.id}><h2>{active.title}</h2><section><h3>Definition and idea</h3><p>{active.copy.principle}</p></section><section><h3>Method and relationships</h3><p>{active.copy.method}</p></section><section><h3>Worked examples</h3>{active.copy.examples.filter(Boolean).map((example,i)=><details key={i} open={i===0}><summary>{example.title}</summary><p>{example.setup}</p><p>{example.result}</p></details>)}</section><section className="studio-assumptions"><h3>Assumptions and common mistakes</h3><p>{active.copy.caution}</p></section>{active.exercise?<ChallengeBox kind="concept" prompt={active.exercise.prompt} expected={active.exercise.expected} tolerance={.001} hint="Review the worked example and method. Enter a number or a simple fraction." placeholder="Numeric answer"/>:null}<Link className="studio-lab-link" to={active.href}>Explore this concept in its lab →</Link><p>Before opening the lab: predict what a parameter change should do. After changing it: explain the result, identify a boundary case, and state which assumptions still hold.</p><SupplementalWorkbench studioId={studio.id}/></article>:null}</div></details></main>;
}
export function SupplementalWorkbench({studioId}:{studioId:string}){
  const config=supplementalDefaults[studioId];
  const [a,setA]=useStudioState(`curriculum:${studioId}:a`,config.a),[b,setB]=useStudioState(`curriculum:${studioId}:b`,config.b);
  let result:ReturnType<typeof supplementalModel>|undefined,error='';try{result=supplementalModel(studioId,a,b);}catch(e){error=(e as Error).message;}
  const values=result?.series||[],lo=Math.min(0,...values),hi=Math.max(0,...values),height=hi-lo||1,points=values.map((v,i)=>`${30+i/Math.max(1,values.length-1)*460},${210-(v-lo)/height*180}`).join(' ');
  return <section className="studio-supplemental" data-supplemental-model={studioId}><h3>Supplemental concept workbench</h3><div className="studio-parameter-grid"><label>{config.aLabel}<input type="number" step="any" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label>{config.bLabel}<input type="number" step="any" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div>{error?<p role="alert">{error}</p>:result?<><code>{result.formula}</code><dl>{Object.entries(result.outputs).map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{typeof value==='number'?fmt(value,6):value}</dd></div>)}</dl><svg viewBox="0 0 520 245" role="img" aria-label="Supplemental model sequence" className="statistics-chart"><path d="M30 25V210H490" fill="none" stroke="currentColor"/><polyline points={points} fill="none" stroke="#0891b2" strokeWidth="2.5"/>{values.length<60?values.map((v,i)=><circle key={i} cx={30+i/Math.max(1,values.length-1)*460} cy={210-(v-lo)/height*180} r="3" fill="#7c3aed"><title>{`Index ${i}: ${v}`}</title></circle>):null}<text x="30" y="237" fill="currentColor" fontSize="12">Sequence index 0 → {values.length-1}; values {fmt(lo)} to {fmt(hi)}</text></svg><p>{result.note}</p>{Object.values(result.outputs).some(v=>typeof v==='number'&&Number.isFinite(v))?<ChallengeBox kind="live" prompt={`Compute ${Object.keys(result.outputs).find(k=>typeof result!.outputs[k]==='number')} for the current supplemental model. Round to 3 decimal places.`} expected={Object.values(result.outputs).find(v=>typeof v==='number') as number} tolerance={.001} hint="Use the relationship and current parameters shown above." placeholder="Numeric answer"/>:null}</>:null}</section>;
}
