import { logGamma, normalCdf } from '../statistics/statisticsCore';
export type SupplementalResult={formula:string;outputs:Record<string,number|string>;series:number[];note:string};
export const supplementalDefaults:Record<string,{a:number;b:number;aLabel:string;bLabel:string}>= {
algebra:{a:-2,b:6,aLabel:'Coefficient a (nonzero)',bLabel:'Constant b'},'algebraic-structures':{a:2,b:6,aLabel:'Generator a',bLabel:'Modulus n (2–100)'},geometry:{a:5,b:3,aLabel:'Ellipse semimajor a > 0',bLabel:'Semiminor b, 0 < b ≤ a'},trigonometry:{a:.5,b:1,aLabel:'Sine target c (−1 to 1)',bLabel:'Number of full periods (1–10)'},calculus:{a:2,b:20,aLabel:'Power p (0–20)',bLabel:'Even Simpson intervals (2–200)'},'number-systems':{a:11,b:2,aLabel:'Integer (0–1,000,000)',bLabel:'Base (2–36)'},'linear-algebra':{a:4,b:1,aLabel:'Diagonal entry a',bLabel:'Diagonal entry b'},'complex-numbers':{a:-1,b:1,aLabel:'Real part',bLabel:'Imaginary part'},'mathematical-modelling':{a:10,b:1,aLabel:'Linear reward a',bLabel:'Quadratic cost b > 0'},'discrete-world':{a:3,b:2,aLabel:'Initial value a₀',bLabel:'Recurrence multiplier r'},'set-theory':{a:5,b:3,aLabel:'Finite set size n (0–20)',bLabel:'Second set size m (0–20)'},'graph-theory':{a:6,b:9,aLabel:'Vertices V (3–50)',bLabel:'Edges E'},'probability-statistics':{a:.01,b:.05,aLabel:'Disease prevalence (0–1)',bLabel:'False positive rate (0–1)'},'differential-equations':{a:10,b:.1,aLabel:'Decay rate k > 0',bLabel:'Euler step h > 0'},'continued-fractions':{a:43,b:19,aLabel:'Positive integer numerator',bLabel:'Positive integer denominator'},'famous-problems':{a:6,b:100,aLabel:'Positive integer start',bLabel:'Maximum steps (1–500)'},'stats-inference':{a:72,b:120,aLabel:'Successes k ≥ 0',bLabel:'Sample size n ≥ k'},'special-functions':{a:2,b:.5,aLabel:'Legendre degree n (0–15)',bLabel:'Argument x (−1 to 1)'}
};
supplementalDefaults['advanced-differential-equations']=supplementalDefaults['differential-equations'];
const valid=(condition:boolean,message:string)=>{if(!condition)throw new Error(message);};
export function supplementalModel(id:string,a:number,b:number):SupplementalResult{
valid(Number.isFinite(a)&&Number.isFinite(b),'Enter finite numbers.');let formula='',outputs:Record<string,number|string>={},series:number[]=[],note='';
switch(id==='advanced-differential-equations'?'differential-equations':id){
case 'algebra':valid(a!==0,'The coefficient must be nonzero.');formula='ax+b ≥ 0; boundary x=−b/a';outputs={boundary:-b/a,solution:`x ${a>0?'≥':'≤'} ${-b/a}`};series=Array.from({length:21},(_,i)=>a*(i-10)+b);note='The inequality reverses when dividing by a negative coefficient. Boundary equality is included.';break;
case 'algebraic-structures':{valid(Number.isInteger(a)&&Number.isInteger(b)&&b>=2&&b<=100,'Use integer a and modulus 2–100.');let x=0;do{series.push(x);x=((x+a)%b+b)%b;}while(x!==0&&series.length<=b);formula='⟨a⟩ in (Zₙ,+); order(a)=n/gcd(a,n)';outputs={order:series.length,subgroup:`{${series.join(', ')}}`};note='Addition modulo n is associative with identity 0 and inverse −a; this generator gives a cyclic subgroup.';break;}
case 'geometry':valid(a>0&&b>0&&b<=a,'Require 0 < b ≤ a.');formula='c=√(a²−b²); e=c/a; area=πab';outputs={focusDistance:Math.sqrt(a*a-b*b),eccentricity:Math.sqrt(a*a-b*b)/a,area:Math.PI*a*b};series=Array.from({length:41},(_,i)=>b*Math.sqrt(Math.max(0,1-((i/20-1))**2)));note='Equal axes give a circle with eccentricity 0. The displayed samples trace the upper ellipse.';break;
case 'trigonometry':valid(Math.abs(a)<=1&&Number.isInteger(b)&&b>=1&&b<=10,'Use target in [−1,1] and 1–10 integer periods.');formula='sin x=c: x=asin c+2kπ or π−asin c+2kπ';for(let k=-1;k<=b;k++)for(const angle of [Math.asin(a)+2*k*Math.PI,Math.PI-Math.asin(a)+2*k*Math.PI])if(angle>=-1e-10&&angle<2*b*Math.PI-1e-10&&!series.some(v=>Math.abs(v-angle)<1e-9))series.push(angle);series.sort((x,y)=>x-y);outputs={solutionsRadians:series.map(v=>v.toFixed(6)).join(', '),count:series.length};note='Solutions are in [0, 2π·periods). Coincident branch solutions at ±1 are counted once.';break;
case 'calculus':{valid(a>=0&&a<=20&&Number.isInteger(b)&&b>=2&&b<=200&&b%2===0,'Use power 0–20 and an even interval count 2–200.');formula='∫₀¹xᵖdx=1/(p+1); Simpson weighted sum';series=Array.from({length:b+1},(_,i)=>(i/b)**a);const approximate=series.reduce((sum,x,i)=>sum+x*(i===0||i===b?1:i%2?4:2),0)/(3*b);outputs={exact:1/(a+1),simpson:approximate,absoluteError:Math.abs(approximate-1/(a+1))};note='Convergence rate depends on smoothness. The power is nonnegative to avoid an endpoint singularity.';break;}
case 'number-systems':valid(Number.isInteger(a)&&a>=0&&a<=1e6&&Number.isInteger(b)&&b>=2&&b<=36,'Use an integer 0–1,000,000 and integer base 2–36.');formula='n=Σdᵢbⁱ';outputs={representation:a.toString(b).toUpperCase(),roundTrip:parseInt(a.toString(b),b)};{let n=a;do{series.push(n%b);n=Math.floor(n/b);}while(n>0);}note='Remainders are displayed least significant first; reverse them to obtain the numeral.';break;
case 'linear-algebra':formula='A=diag(a,b); singular values=|a|,|b|';outputs={determinant:a*b,rank:Number(a!==0)+Number(b!==0),condition:a===0||b===0?'Infinite (singular)':Math.max(Math.abs(a),Math.abs(b))/Math.min(Math.abs(a),Math.abs(b)),trace:a+b};series=[Math.abs(a),Math.abs(b)];note='This calculator handles diagonal 2×2 matrices. Full matrix tools are available in the linked studio; the singular condition is explicitly reported.';break;
case 'complex-numbers':valid(a!==0||b!==0,'log(0) is undefined.');formula='log z=ln|z|+i(arg z+2πk)';outputs={logReal:Math.log(Math.hypot(a,b)),principalArg:Math.atan2(b,a),modulus:Math.hypot(a,b)};series=Array.from({length:5},(_,i)=>Math.atan2(b,a)+2*Math.PI*(i-2));note='The principal argument uses atan2; five displayed imaginary parts correspond to branches k=−2,…,2.';break;
case 'mathematical-modelling':valid(b>0,'Quadratic cost b must be positive.');formula='Profit(x)=ax−bx², x≥0; x*=max(0,a/(2b))';{const optimum=Math.max(0,a/(2*b));outputs={optimalQuantity:optimum,maxProfit:a*optimum-b*optimum*optimum};series=Array.from({length:21},(_,i)=>{const x=i*Math.max(1,optimum*2)/20;return a*x-b*x*x;});}note='This result assumes continuous nonnegative production and a quadratic cost model; discrete units need a neighboring-integer check.';break;
case 'discrete-world':valid(Math.abs(a)<=100&&Math.abs(b)<=10,'Use |initial|≤100 and |multiplier|≤10.');formula='aₙ=r aₙ₋₁, hence aₙ=a₀rⁿ';series=Array.from({length:11},(_,i)=>a*b**i);outputs={term10:series[10],initial:a};note='Magnitude and sign of r determine decay, growth and alternating behavior; the initial value selects the sequence.';break;
case 'set-theory':valid(Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&a<=20&&b>=0&&b<=20,'Set sizes must be integers 0–20.');formula='|P(A)|=2ⁿ; |A×B|=nm; functions A→B=mⁿ';outputs={powerSetSize:2**a,cartesianProductSize:a*b,functionCount:b**a};series=Array.from({length:a+1},(_,i)=>2**i);note='Finite labeled sets are assumed. There is one empty-domain function, including the function ∅→∅, so the count at n=m=0 is 1.';break;
case 'graph-theory':valid(Number.isInteger(a)&&a>=3&&a<=50&&Number.isInteger(b)&&b>=a-1&&b<=3*a-6,'Use V=3–50 and V−1 ≤ E ≤ 3V−6 for a possible connected simple planar graph.');formula='For a connected planar embedding: V−E+F=2';outputs={faces:b-a+2,degreeSum:2*b,treeEdges:a-1,planarEdgeBound:3*a-6};series=[a,b,b-a+2];note='These are necessary counts under the stated planar assumptions, not a planarity certificate. A graph satisfying the edge bound can still be nonplanar.';break;
case 'probability-statistics':valid(a>=0&&a<=1&&b>=0&&b<=1&&a*.95+(1-a)*b>0,'Use probabilities in [0,1] with a positive probability of a positive test.');formula='P(D|+)=(.95·prior)/(.95·prior+FPR·(1−prior))';outputs={posterior:.95*a/(.95*a+b*(1-a)),positiveProbability:.95*a+b*(1-a),sensitivity:.95};series=[a,outputs.posterior as number];note='Sensitivity is fixed at 0.95 in this model. Edit all three quantities in the probability experiments lab.';break;
case 'differential-equations':valid(a>0&&a<=100&&b>0&&b<=2,'Use decay rate (0,100] and step (0,2].');formula='Euler yₙ₊₁=(1−kh)yₙ; exact y(t)=e⁻ᵏᵗ, y₀=1';outputs={amplification:1-a*b,stable:Math.abs(1-a*b)<1?'Yes':'No',maxStableStep:2/a,exactAt10Steps:Math.exp(-10*a*b),eulerAt10Steps:(1-a*b)**10};series=Array.from({length:11},(_,i)=>(1-a*b)**i);note='Stability requires strict |1−kh|<1; the boundary is not asymptotically stable. Numerical growth can occur despite exact decay.';break;
case 'continued-fractions':{valid(Number.isInteger(a)&&Number.isInteger(b)&&a>0&&b>0&&a<=1e6&&b<=1e6,'Use positive integers up to 1,000,000.');let n=a,d=b;while(d){const q=Math.floor(n/d);series.push(q);[n,d]=[d,n%d];}formula='Euclidean quotients give [a₀;a₁,…]';outputs={partialQuotients:`[${series[0]};${series.slice(1).join(',')}]`,gcd:n,reduced:`${a/n}/${b/n}`};note='Integer Euclidean divisions avoid the floating-point termination errors of expanding a decimal approximation.';break;}
case 'famous-problems':{valid(Number.isInteger(a)&&a>=1&&a<=1e6&&Number.isInteger(b)&&b>=1&&b<=500,'Use a positive integer start ≤1,000,000 and 1–500 steps.');let n=BigInt(a);series=[a];let steps=0;while(n!==1n&&steps<b){n=n%2n===0n?n/2n:3n*n+1n;steps++;if(n<=BigInt(Number.MAX_SAFE_INTEGER))series.push(Number(n));else break;}formula='Collatz: even n→n/2; odd n→3n+1';outputs={steps,last:n.toString(),reachedOne:n===1n?'Yes for this start':'Not within this run'};note='This finite experiment proves nothing about all positive integers. The graph stops if exact integer values exceed safe chart coordinates.';break;}
case 'stats-inference':valid(Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=1&&a<=b&&b<=1e6,'Use integer counts 0≤k≤n and 1≤n≤1,000,000.');formula='p̂=k/n; z=(p̂−.5)/√(.25/n)';outputs={proportion:a/b,z:(a/b-.5)/Math.sqrt(.25/b),twoSidedP:2*(1-normalCdf(Math.abs((a/b-.5)/Math.sqrt(.25/b))))};series=[a,b-a];note='The normal score approximation needs adequate expected successes and failures; use an exact binomial procedure for sparse samples.';break;
case 'special-functions':{valid(Number.isInteger(a)&&a>=0&&a<=15&&Math.abs(b)<=1,'Use degree 0–15 and x in [−1,1].');series=[1];if(a>=1)series.push(b);for(let n=1;n<a;n++)series.push(((2*n+1)*b*series[n]-n*series[n-1])/(n+1));formula='(n+1)Pₙ₊₁=(2n+1)xPₙ−nPₙ₋₁';outputs={legendre:series[a],gammaNPlus1:Math.exp(logGamma(a+1))};note='Legendre polynomials are orthogonal on [−1,1] with weight 1. The plotted sequence shows degrees 0 through n at fixed x.';break;}
default:throw new Error('No supplemental model for this studio.');
}return {formula,outputs,series,note};}
