import type { StrengthenedLesson } from "../strengthenedLessonSchema";

export type StatisticsBatchChallenge = {
  prompt: string;
  expected: string;
  hint: string;
  kind: "numeric" | "keywords" | "interaction";
  factoryId: string;
};

type FormulaSeed = {
  label: string;
  expression: string;
  variables: Array<{ symbol: string; meaning: string }>;
  restrictions?: string[];
  exactness?: "exact" | "approximation" | "definition" | "theorem" | "identity";
};

type Seed = {
  id: number;
  title: string;
  slug: string;
  topic: "Spreadsheet" | "Statistics and Regression";
  lessonType: StrengthenedLesson["lessonType"];
  definition: string;
  action: string;
  reason: string;
  representation: "spreadsheet_grid" | "table" | "distribution_plot" | "function_graph" | "coordinate_graph";
  misconception: [string, string, string];
  examples: [string, string][];
  challenge: StatisticsBatchChallenge;
  formula?: FormulaSeed;
};

const data: Record<number, Seed> = {
  462: item(462, "Spreadsheet Charts", "spreadsheet-charts", "Spreadsheet", "tool", "Spreadsheet charts turn selected cells into visual displays such as bar charts, line charts, or scatter plots.", "Select the correct cell range, choose a chart type, and check that labels match the data.", "Charts help people see patterns faster than reading many rows.", "spreadsheet_grid", ["WRONG_CHART_TYPE", "Using a chart type that does not match the data.", "Use bar charts for categories, line charts for time, and scatter plots for paired numbers."], [["Monthly spending", "A bar chart compares money spent in each month."], ["Plant height", "A line chart shows growth over time."], ["Study time and marks", "A scatter plot shows paired data."]], "Which chart is best for paired number data?", "scatter plot"),
  463: item(463, "Regression from Data", "regression-from-data", "Spreadsheet", "tool", "Regression from data fits an equation to points so a trend can be described.", "Plot the paired data, choose a model, and inspect the fitted equation and residuals.", "Regression gives a useful summary when data has a visible pattern.", "function_graph", ["FORCING_LINE", "Forcing a straight line onto clearly curved data.", "Choose a model that matches the shape of the points."], [["Rain and crop yield", "A model estimates yield from rainfall."], ["Temperature and ice cream sales", "A trend line shows the relationship."], ["Practice time and score", "A model can predict likely score."]], "What should you inspect after fitting a regression model?", "residuals", { label: "Linear model", expression: "y = mx + b", variables: [{ symbol: "m", meaning: "slope of the fitted line" }, { symbol: "b", meaning: "y-intercept of the fitted line" }], exactness: "approximation" }),
  464: item(464, "Dynamic Cell Links", "dynamic-cell-links", "Spreadsheet", "tool", "Dynamic cell links connect spreadsheet cells to live outputs such as charts or workspace objects.", "Link the output to the correct cells, edit one source cell, and confirm the output updates.", "A link keeps the same data source, so changes flow through automatically.", "spreadsheet_grid", ["BROKEN_RANGE", "Linking the output to the wrong range.", "Check the source range before trusting the live output."], [["Budget sheet", "Changing rent updates the total chart."], ["Science table", "Changing time updates plotted points."], ["Class marks", "Changing a mark updates the mean."]], "A dynamic link should update when the source what changes?", "cell"),
  465: item(465, "Import CSV", "import-csv", "Spreadsheet", "tool", "Import CSV loads comma-separated text data into rows and columns.", "Choose the file, check the separator, confirm headings, and inspect data types.", "CSV works because commas mark where one cell ends and the next begins.", "spreadsheet_grid", ["BAD_SEPARATOR", "Importing with the wrong separator so columns shift.", "Check the delimiter before analysing the imported table."], [["Bank file", "Transactions import into dated rows."], ["Weather data", "Temperatures load into columns."], ["Survey export", "Responses become spreadsheet rows."]], "What separator does a normal CSV file use?", "comma"),
  466: item(466, "Export Data", "export-data", "Spreadsheet", "tool", "Export data saves a table or result so another tool can read it.", "Select the correct range, choose the file format, and include headings when needed.", "Exporting preserves the values needed for sharing, checking, or later analysis.", "spreadsheet_grid", ["MISSING_HEADINGS", "Exporting numbers without labels.", "Include headings so another reader knows what each column means."], [["Project marks", "A teacher exports marks for a report."], ["Experiment results", "A group shares measurements as CSV."], ["Budget totals", "A family saves a monthly table."]], "What should usually be included when exporting a table?", "headings"),
  467: item(467, "Data Types", "data-types", "Statistics and Regression", "concept", "Data types describe what kind of values a data set contains, such as categories, counts, or measurements.", "Identify whether each variable is categorical, discrete numerical, or continuous numerical.", "The data type decides which graph, summary, or model is appropriate.", "table", ["MIXING_TYPES", "Treating category names like measured numbers.", "Use category graphs for labels and numerical summaries for numbers."], [["Favourite colour", "This is categorical data."], ["Number of siblings", "This is discrete numerical data."], ["Height", "This is continuous numerical data."]], "Is favourite colour categorical or numerical?", "categorical"),
  468: item(468, "Frequency Tables", "frequency-tables", "Statistics and Regression", "concept", "A frequency table counts how many times each value or category occurs.", "Make clear categories, tally every data value once, and write the final counts.", "Counting frequencies summarises raw data without changing the total number of observations.", "table", ["DOUBLE_COUNT", "Counting one observation in two categories.", "Use categories that do not overlap unless the table is designed for multiple choices."], [["Lunch choices", "Count how many students chose each food."], ["Dice rolls", "Count each face from 1 to 6."], ["Test marks", "Count each score or mark band."]], "A frequency table records how many times values what?", "occur"),
  469: item(469, "Grouped Frequency Tables", "grouped-frequency-tables", "Statistics and Regression", "concept", "A grouped frequency table counts data inside intervals, or class groups.", "Choose non-overlapping intervals, place each value in one interval, and count the values.", "Grouping makes large or continuous data easier to read.", "table", ["OVERLAPPING_CLASSES", "Using class intervals that overlap at endpoints.", "Use clear intervals so each value belongs to one class only."], [["Heights", "Group students by height intervals."], ["Travel time", "Group minutes into bands."], ["Marks", "Count marks from 0-9, 10-19, and so on."]], "Grouped tables use non-overlapping what?", "intervals"),
  470: item(470, "Mean", "mean", "Statistics and Regression", "concept", "The mean is the sum of all values divided by the number of values.", "Add the values, count how many values there are, then divide.", "The mean shares the total equally among all data positions.", "distribution_plot", ["FORGET_COUNT", "Adding values but not dividing by the number of values.", "Always divide the total by the count of values."], [["Pocket money", "Average weekly money can be found with the mean."], ["Marks", "A class average uses the mean."], ["Daily temperature", "The mean gives a typical temperature."]], "What is the mean of 2, 4, and 6?", "4", { label: "Mean", expression: "mean = sum of values / n", variables: [{ symbol: "n", meaning: "number of values" }], restrictions: ["n must be greater than 0"], exactness: "definition" }),
  471: item(471, "Median", "median", "Statistics and Regression", "concept", "The median is the middle value after the data is ordered.", "Order the values, find the middle position, or average the two middle values.", "The median splits ordered data into two equal halves.", "distribution_plot", ["NO_SORT", "Finding the middle before sorting the data.", "Sort the data first, then find the middle."], [["House prices", "Median price is less affected by one very high price."], ["Running times", "The middle time describes a typical runner."], ["Exam marks", "The median shows the central ordered mark."]], "What must you do before finding the median?", "sort"),
  472: item(472, "Mode", "mode", "Statistics and Regression", "concept", "The mode is the value or category that appears most often.", "Count the frequency of each value, then choose the highest frequency.", "The mode shows the most common result in the data.", "table", ["ONE_MODE_ALWAYS", "Thinking every data set has exactly one mode.", "A data set can have no mode, one mode, or more than one mode."], [["Shoe sizes", "The modal size helps a shop stock shoes."], ["Favourite sport", "The mode is the most chosen sport."], ["Bus arrival minute", "The most common delay is the mode."]], "What is the mode of 2, 3, 3, 5?", "3"),
  473: item(473, "Weighted Mean", "weighted-mean", "Statistics and Regression", "concept", "A weighted mean is an average where some values count more than others.", "Multiply each value by its weight, add the products, then divide by the total weight.", "Weights show how much each value should influence the average.", "table", ["IGNORE_WEIGHTS", "Averaging values without using their weights.", "Multiply by weights before dividing by total weight."], [["Course grade", "Tests may count more than homework."], ["Shopping price", "Buying more of one item gives it more weight."], ["Sports score", "Some rounds may carry double points."]], "In a weighted mean, divide by the total what?", "weight", { label: "Weighted mean", expression: "weighted mean = sum(wx) / sum(w)", variables: [{ symbol: "w", meaning: "weight of a value" }, { symbol: "x", meaning: "data value" }], restrictions: ["Total weight must not be 0"], exactness: "definition" }),
  474: item(474, "Range", "range", "Statistics and Regression", "concept", "The range is the largest value minus the smallest value.", "Find the maximum, find the minimum, then subtract minimum from maximum.", "Range measures the total spread from one end of the data to the other.", "distribution_plot", ["SUBTRACT_ORDER", "Subtracting largest from smallest and getting a negative range.", "Range is maximum minus minimum, so it is not negative."], [["Daily temperature", "Range shows the day's temperature change."], ["Exam marks", "Range shows the gap between highest and lowest marks."], ["Delivery times", "Range shows the full time spread."]], "What is the range of 3, 8, and 10?", "7", { label: "Range", expression: "range = maximum - minimum", variables: [{ symbol: "maximum", meaning: "largest data value" }, { symbol: "minimum", meaning: "smallest data value" }], exactness: "definition" }),
  475: item(475, "Quartiles and IQR", "quartiles-and-iqr", "Statistics and Regression", "concept", "Quartiles split ordered data into four parts, and IQR is the upper quartile minus the lower quartile.", "Order the data, find Q1 and Q3, then subtract Q1 from Q3.", "IQR measures the spread of the middle half of the data.", "distribution_plot", ["NO_ORDER_IQR", "Finding quartiles before ordering the data.", "Order the data before finding quartiles."], [["Test marks", "IQR shows spread for the middle students."], ["House prices", "IQR ignores extreme ends better than range."], ["Travel times", "IQR describes usual variation."]], "IQR equals Q3 minus what?", "Q1", { label: "Interquartile range", expression: "IQR = Q3 - Q1", variables: [{ symbol: "Q1", meaning: "lower quartile" }, { symbol: "Q3", meaning: "upper quartile" }], exactness: "definition" }),
  476: item(476, "Variance and Standard Deviation", "variance-and-standard-deviation", "Statistics and Regression", "concept", "Variance and standard deviation measure how far values usually are from the mean.", "Find the mean, measure deviations, square them for variance, then take the square root for standard deviation.", "Squaring keeps distances positive, and the square root returns to the original units.", "distribution_plot", ["ONLY_RANGE", "Using only range to describe all spread.", "Standard deviation uses every value, not only the two ends."], [["Factory parts", "Small standard deviation means sizes are consistent."], ["Marks", "It shows how spread out scores are."], ["Weather", "It shows how much temperatures vary."]], "Standard deviation is the square root of what?", "variance", { label: "Standard deviation", expression: "standard deviation = square root of variance", variables: [{ symbol: "variance", meaning: "mean squared deviation" }], restrictions: ["Use the correct population or sample formula for the question."], exactness: "definition" }),
  477: item(477, "Percentiles", "percentiles", "Statistics and Regression", "concept", "A percentile tells the value below which a given percent of data lies.", "Order the data, choose the percentile position, and read or interpolate the value if required.", "Percentiles compare one value with the rest of an ordered data set.", "distribution_plot", ["PERCENT_IS_SCORE", "Thinking the 80th percentile means a score of 80.", "It means about 80 percent of data is at or below that value."], [["Height chart", "A child at the 60th percentile is taller than about 60 percent of peers."], ["Exam rank", "Percentile compares a score with other scores."], ["Internet speed", "A percentile describes service consistency."]], "Does the 80th percentile always mean score 80?", "no"),
  478: item(478, "Z-Scores", "z-scores", "Statistics and Regression", "concept", "A z-score tells how many standard deviations a value is from the mean.", "Subtract the mean from the value, then divide by the standard deviation.", "Z-scores let values from different scales be compared fairly.", "distribution_plot", ["SIGN_IGNORED", "Ignoring whether the z-score is positive or negative.", "Positive means above the mean, and negative means below the mean."], [["Exam scores", "Compare results from two different tests."], ["Heights", "See how far a height is from average."], ["Machine parts", "Check whether a part is unusually large."]], "A positive z-score is above or below the mean?", "above", { label: "Z-score", expression: "z = (x - mean) / standard deviation", variables: [{ symbol: "x", meaning: "data value" }, { symbol: "mean", meaning: "average of the data" }, { symbol: "standard deviation", meaning: "spread measure" }], restrictions: ["Standard deviation must be greater than 0"], exactness: "definition" }),
  479: item(479, "Outliers", "outliers", "Statistics and Regression", "concept", "An outlier is a data value that is unusually far from the rest of the data.", "Inspect the data, use a clear rule such as the 1.5 IQR rule when required, and check for recording errors.", "Outliers matter because they can strongly change the mean and some models.", "distribution_plot", ["DELETE_FAST", "Deleting an outlier without checking why it happened.", "Investigate the value before deciding whether to keep or remove it."], [["Typo in marks", "A score of 900 out of 100 is likely an error."], ["Very tall player", "A real extreme height can still be valid data."], ["Late bus", "One very late trip may affect the mean."]], "Should you check an outlier before deleting it?", "yes"),
  481: item(481, "Dot Plot", "dot-plot", "Statistics and Regression", "visual_exploration", "A dot plot places one dot for each data value on a number line.", "Draw a scale, place each dot above its value, and stack repeated values.", "Dot plots show shape, clusters, gaps, and repeated values clearly.", "distribution_plot", ["BAD_SCALE", "Using uneven spacing on the number line.", "Use equal spacing so positions represent values correctly."], [["Class shoe sizes", "Repeated sizes stack as dots."], ["Quiz scores", "Clusters show common scores."], ["Daily steps", "Gaps show missing ranges."]], "In a dot plot, repeated values are shown by stacking what?", "dots"),
  482: item(482, "Stem-and-Leaf Plot", "stem-and-leaf-plot", "Statistics and Regression", "visual_exploration", "A stem-and-leaf plot splits numbers into stems and final digits called leaves.", "Choose place values, write stems in order, and place leaves in sorted order.", "It keeps the original data values while showing the distribution shape.", "table", ["UNSORTED_LEAVES", "Leaving leaves unordered inside each stem.", "Sort leaves so the data can be read correctly."], [["Test marks", "67 has stem 6 and leaf 7."], ["Ages", "A plot groups ages by tens."], ["Distances", "Leaves keep each exact value."]], "In 67, if tens are stems, what is the leaf?", "7"),
  483: item(483, "Histogram", "histogram", "Statistics and Regression", "visual_exploration", "A histogram uses touching bars to show frequencies for numerical intervals.", "Choose equal-width intervals when suitable, count values in each interval, and draw touching bars.", "Touching bars show that the number line is continuous across intervals.", "distribution_plot", ["GAPS_BETWEEN_BARS", "Drawing gaps between histogram bars as if categories are separate.", "Histogram bars touch because intervals are adjacent on a number line."], [["Heights", "Bars show how many students are in each height interval."], ["Travel times", "A histogram shows common time ranges."], ["Rainfall", "Intervals show amounts of rain."]], "Do histogram bars usually touch?", "yes"),
  484: item(484, "Frequency Polygon", "frequency-polygon", "Statistics and Regression", "visual_exploration", "A frequency polygon joins points plotted at class midpoints and their frequencies.", "Find each class midpoint, plot midpoint against frequency, and join neighbouring points.", "Joining points shows the overall shape of grouped numerical data.", "coordinate_graph", ["USING_CLASS_ENDS", "Plotting class endpoints instead of class midpoints.", "Use the midpoint of each class interval."], [["Grouped marks", "Midpoint points show the mark distribution."], ["Rainfall intervals", "A polygon shows the pattern across ranges."], ["Heights", "Joined points show the shape of the data."]], "A frequency polygon plots frequencies at class what?", "midpoints"),
  485: item(485, "Cumulative Frequency Curve", "cumulative-frequency-curve", "Statistics and Regression", "visual_exploration", "A cumulative frequency curve shows running totals up to each class boundary.", "Add frequencies cumulatively, plot each running total, and join the points smoothly.", "Running totals show how many observations are less than or equal to a value.", "coordinate_graph", ["PLOT_RAW_FREQ", "Plotting ordinary frequencies instead of cumulative totals.", "Add the frequencies as you move across the classes."], [["Exam marks", "The curve estimates how many students scored up to 60."], ["Ages", "It shows how many people are below an age."], ["Delivery times", "It estimates percentiles from grouped data."]], "Cumulative frequency uses running what?", "totals"),
  486: item(486, "Bar and Pie Charts", "bar-and-pie-charts", "Statistics and Regression", "visual_exploration", "Bar charts compare category frequencies, and pie charts show category parts of a whole.", "Count each category, draw bars or convert each share into a sector angle.", "Both charts show categorical data, but pie charts require a meaningful whole.", "table", ["PIE_FOR_NOT_WHOLE", "Using a pie chart when categories do not form one whole.", "Use a pie chart only when the parts make one complete total."], [["Favourite fruit", "Bars compare each fruit count."], ["Monthly budget", "A pie chart shows parts of total spending."], ["Transport choices", "Bars show the most common choice."]], "A pie chart should show parts of one what?", "whole"),
  487: item(487, "Scatter Plot", "scatter-plot", "Statistics and Regression", "visual_exploration", "A scatter plot shows paired numerical data as points on coordinate axes.", "Plot each pair as one point and look for direction, form, and strength.", "Scatter plots reveal relationships between two numerical variables.", "coordinate_graph", ["CONNECT_POINTS", "Joining scatter points as if they are a time line.", "Usually leave scatter points separate unless order has meaning."], [["Height and arm span", "Points may show a positive association."], ["Study time and score", "The plot shows a possible trend."], ["Temperature and sales", "Points show how sales change with temperature."]], "A scatter plot uses paired what?", "numbers"),
  488: item(488, "Time-Series Plot", "time-series-plot", "Statistics and Regression", "visual_exploration", "A time-series plot shows how a quantity changes over time.", "Put time on the horizontal axis, plot values in order, and join neighbouring time points.", "Time order matters because each value happened before or after another.", "coordinate_graph", ["TIME_NOT_ORDERED", "Plotting dates out of order.", "Keep time in correct order before reading the trend."], [["Daily temperature", "A line shows warming or cooling over days."], ["Savings", "The graph shows money growing over months."], ["Website visits", "A plot shows busy days."]], "Which axis usually shows time?", "horizontal"),
  489: item(489, "Correlation Coefficient", "correlation-coefficient", "Statistics and Regression", "concept", "The correlation coefficient r measures the direction and strength of a linear relationship.", "Make a scatter plot, check that a linear pattern is sensible, then read r between -1 and 1.", "Values near 1 or -1 show strong linear association; values near 0 show weak linear association.", "coordinate_graph", ["CAUSE_FROM_CORRELATION", "Thinking correlation proves one variable causes the other.", "Correlation shows association, not proof of cause."], [["Ice cream sales and temperature", "They may have positive correlation."], ["Practice time and race time", "They may have negative correlation."], ["Shoe size and reading score", "They may have weak correlation."]], "Does correlation alone prove cause?", "no", { label: "Correlation range", expression: "-1 <= r <= 1", variables: [{ symbol: "r", meaning: "correlation coefficient" }], restrictions: ["r describes linear association."], exactness: "definition" }),
  490: item(490, "Linear Regression", "linear-regression", "Statistics and Regression", "modelling", "Linear regression fits a straight line that best models paired numerical data.", "Plot the data, fit y = mx + b, then check residuals and context.", "Least-squares linear regression chooses a line by making squared vertical errors as small as possible.", "function_graph", ["EXTRAPOLATE_FAR", "Using a fitted line far outside the data range.", "Predictions far beyond the data can be unreliable."], [["Taxi fare", "A line can model cost by distance."], ["Plant growth", "A short steady period may fit a line."], ["Study hours", "A line can estimate score from hours."]], "What graph should you check before using linear regression?", "scatter plot", { label: "Linear regression model", expression: "y = mx + b", variables: [{ symbol: "m", meaning: "slope" }, { symbol: "b", meaning: "intercept" }], exactness: "approximation" }),
  491: item(491, "Polynomial Regression", "polynomial-regression", "Statistics and Regression", "modelling", "Polynomial regression fits a polynomial curve to paired numerical data.", "Plot the data, choose a sensible degree, fit the curve, and inspect residuals.", "Powers of x let the model bend to match curved patterns.", "function_graph", ["HIGH_DEGREE_OVERFIT", "Choosing a very high degree just to hit every point.", "Use the simplest curve that explains the pattern well."], [["Projectile height", "A quadratic model can fit upward then downward motion."], ["Growth with turning point", "A polynomial can model bends."], ["Engineering data", "A low-degree polynomial can approximate a curve."]], "What risk comes from using too high a polynomial degree?", "overfit", { label: "Polynomial model", expression: "y = a_n x^n + ... + a_1 x + a_0", variables: [{ symbol: "x", meaning: "input variable" }, { symbol: "a_i", meaning: "polynomial coefficients" }, { symbol: "n", meaning: "degree of the polynomial" }], restrictions: ["Use a degree justified by the data and context."], exactness: "approximation" }),
  492: item(492, "Exponential Regression", "exponential-regression", "Statistics and Regression", "modelling", "Exponential regression fits a model where values change by a repeated multiplying factor.", "Plot the data, check for multiplicative change, fit the model, and inspect residuals.", "Equal input steps cause equal multiplication in an exponential pattern.", "function_graph", ["LINEAR_FOR_GROWTH", "Using a line for data that changes by repeated percent growth.", "Use an exponential model when ratios are roughly steady."], [["Population growth", "A steady percent growth can be exponential."], ["Compound interest", "Money grows by repeated multiplication."], ["Cooling difference", "Some cooling data decays exponentially."]], "Exponential change uses repeated addition or multiplication?", "multiplication", { label: "Exponential model", expression: "y = ab^x", variables: [{ symbol: "a", meaning: "starting scale" }, { symbol: "b", meaning: "multiplying factor" }, { symbol: "x", meaning: "input value" }], restrictions: ["a is not 0 and b must be greater than 0."], exactness: "approximation" }),
};

export function statisticsSeed(id: number) {
  return data[id];
}

export type StatisticsBatchSeed = Seed;

export function statisticsBatchLesson(seed: Seed): StrengthenedLesson {
  const code = seed.misconception[0];
  return {
    id: seed.id,
    title: seed.title,
    route: `/lessons/data-and-probability/${seed.id}-${seed.slug}`,
    category: "Data and Probability",
    topic: seed.topic,
    lessonType: seed.lessonType,
    learningObjectives: [`Define ${seed.title} accurately.`, seed.action, `Avoid this common mistake: ${seed.misconception[1]}`],
    prerequisites: ["Reading tables", "Basic arithmetic", "Interpreting simple graphs"],
    keyVocabulary: [{ term: seed.title, meaning: seed.definition }, { term: "Data", meaning: "Values collected from observations, measurements, or categories." }],
    introduction: `${seed.title} helps us organise or study data. It is important because daily choices often use data, such as marks, money, weather, and sports results.`,
    basicIdea: `${seed.definition} The basic idea is to represent the data in a form that matches the question. ${seed.reason} A common mistake is ${seed.misconception[1]}`,
    howItWorks: `${seed.action} Then check the result against the original data and the question context.`,
    whyItWorks: "Statistics works by preserving the data structure, then using counts, order, distance, or a model to describe the pattern.",
    definitions: [{ id: `${seed.slug}-definition`, statement: seed.definition }],
    facts: [{ id: `${seed.slug}-fact`, statement: seed.reason }],
    formulas: seed.formula ? [{ id: `${seed.slug}-formula`, ...seed.formula }] : [],
    conditionsAndRestrictions: ["Use the right data type for the method.", "Keep units and labels visible.", "Do not predict outside the data range unless the context supports it."],
    representations: [{ id: `${seed.slug}-representation`, type: seed.representation, learningPurpose: `Show the data structure for ${seed.title}.` }],
    workedExamples: [{ id: `${seed.slug}-worked-1`, prompt: seed.challenge.prompt, steps: ["Identify the data type and question.", seed.action, "Check that the answer matches the context."], answer: seed.challenge.expected }],
    realLifeExamples: seed.examples.map(([context, connection], index) => ({ id: `${seed.slug}-real-${index + 1}`, context, connection })),
    misconceptions: [{ code, mistake: seed.misconception[1], correction: seed.misconception[2] }],
    interaction: {
      id: `${seed.slug}-interaction`,
      learningPurpose: `Explore ${seed.title} with editable data, linked graphs, and summary values.`,
      parameters: [{ id: "sample", label: "Sample data", validValues: ["2, 3, 4, 4, 5, 6, 7, 8", "1, 2, 2, 4, 7, 12"] }],
      initialState: `Start with a small data set for ${seed.title}.`,
      dynamicFeedback: "Changing values updates the plot, summary, fitted model, or table.",
      successCriteria: ["Use the correct data rule", "Read the linked output", "Explain the common mistake"],
      accessibilityAlternative: "Provide the data, summary values, and graph interpretation as text.",
    },
    guidedExploration: [{ id: "predict", prompt: "Predict how the output changes when one data value changes." }, { id: "test", prompt: "Edit the data and compare the new result." }, { id: "explain", prompt: "Explain the result using the lesson definition." }],
    practice: [practice(`${seed.slug}-recognition`, `What is ${seed.title}?`, seed.definition, code, "recognition"), practice(`${seed.slug}-direct`, seed.challenge.prompt, seed.challenge.expected, code, "direct"), practice(`${seed.slug}-multi`, `How do you use ${seed.title}?`, seed.action, code, "multi_step"), practice(`${seed.slug}-error`, `What is wrong with this mistake: ${seed.misconception[1]}`, seed.misconception[2], code, "error_diagnosis"), practice(`${seed.slug}-transfer`, `Give one daily use of ${seed.title}.`, seed.examples[0][0], code, "transfer")],
    challenge: { id: `${seed.slug}-challenge`, prompt: seed.challenge.prompt, successCriteria: ["Uses the correct statistical idea", "Checks labels or data order", "Avoids the common mistake"], hints: [seed.challenge.hint, seed.misconception[2]] },
    exitCheck: [{ id: `${seed.slug}-exit`, prompt: `State one rule for ${seed.title}.`, answer: seed.misconception[2], criterion: "Answer names the correct data or model check." }],
    accessibilityNotes: ["Announce plotted values and summary numbers.", "Do not rely only on colour to compare graph elements."],
    expertReviewRequired: false,
  };
}

export function statisticsBatchChallenge(seed: Seed) {
  return seed.challenge;
}

function item(id: number, title: string, slug: string, topic: Seed["topic"], lessonType: Seed["lessonType"], definition: string, action: string, reason: string, representation: Seed["representation"], misconception: Seed["misconception"], examples: Seed["examples"], prompt: string, expected: string, formula?: FormulaSeed): Seed {
  return { id, title, slug, topic, lessonType, definition, action, reason, representation, misconception, examples, formula, challenge: { prompt, expected, hint: `Use the ${title} rule and check the data.`, kind: Number.isFinite(Number(expected)) ? "numeric" : "keywords", factoryId: `statistics.${slug}` } };
}

function practice(id: string, prompt: string, answer: string, misconceptionTag: string, difficulty: StrengthenedLesson["practice"][number]["difficulty"]): StrengthenedLesson["practice"][number] {
  return { id, prompt, answer, hints: ["Read the data carefully.", "Choose the matching representation.", "Check the context."], workedSolution: ["Identify the data question.", "Apply the correct statistical rule.", "Check the answer against the original data."], misconceptionTag, difficulty, parameterConstraints: ["Use labelled data and valid numerical values."] };
}
