import { afterEach,describe,expect,it,vi } from 'vitest';
import { cameraErrorMessage,requestCameraStream,requestEnvironmentCameraStream } from './arCameraSession';
const fakeStream=()=>{const stop=vi.fn();return {stream:{getTracks:()=>[{stop}]} as unknown as MediaStream,stop};};
afterEach(()=>vi.useRealTimers());
describe('AR camera startup',()=>{
 it('accepts a granted stream and clears its timeout',async()=>{vi.useFakeTimers();const {stream,stop}=fakeStream();expect(await requestEnvironmentCameraStream({getUserMedia:vi.fn().mockResolvedValue(stream)},new AbortController().signal)).toBe(stream);expect(vi.getTimerCount()).toBe(0);await vi.advanceTimersByTimeAsync(30000);expect(stop).not.toHaveBeenCalled();});
 it('prefers a rear camera without requiring one',async()=>{const {stream}=fakeStream();const getUserMedia=vi.fn().mockResolvedValue(stream);await requestEnvironmentCameraStream({getUserMedia},new AbortController().signal);expect(getUserMedia).toHaveBeenCalledExactlyOnceWith({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});});
 it.each(['NotAllowedError','NotFoundError','NotReadableError','SecurityError'])('does not retry %s',async name=>{const getUserMedia=vi.fn().mockRejectedValue(new DOMException('failed',name));await expect(requestEnvironmentCameraStream({getUserMedia},new AbortController().signal)).rejects.toHaveProperty('name',name);expect(getUserMedia).toHaveBeenCalledTimes(1);});
 it('falls back only for a constraint failure',async()=>{const {stream}=fakeStream();const getUserMedia=vi.fn().mockRejectedValueOnce(new DOMException('failed','OverconstrainedError')).mockResolvedValueOnce(stream);expect(await requestEnvironmentCameraStream({getUserMedia},new AbortController().signal)).toBe(stream);expect(getUserMedia).toHaveBeenLastCalledWith({video:true,audio:false});});
 it('times out once and stops a late granted stream',async()=>{vi.useFakeTimers();let grant!:(stream:MediaStream)=>void;const getUserMedia=vi.fn(()=>new Promise<MediaStream>(resolve=>{grant=resolve;}));const request=requestEnvironmentCameraStream({getUserMedia},new AbortController().signal);const rejection=expect(request).rejects.toHaveProperty('name','TimeoutError');await vi.advanceTimersByTimeAsync(15000);await rejection;const {stream,stop}=fakeStream();grant(stream);await Promise.resolve();expect(stop).toHaveBeenCalledOnce();expect(getUserMedia).toHaveBeenCalledOnce();});
 it('cancel rejects immediately and stops a late stream',async()=>{let grant!:(stream:MediaStream)=>void;const controller=new AbortController();const request=requestEnvironmentCameraStream({getUserMedia:()=>new Promise(resolve=>{grant=resolve;})},controller.signal);const rejection=expect(request).rejects.toHaveProperty('name','AbortError');controller.abort();await rejection;const {stream,stop}=fakeStream();grant(stream);await Promise.resolve();expect(stop).toHaveBeenCalledOnce();});
 it('does not request access after cancellation',async()=>{const controller=new AbortController();controller.abort();const getUserMedia=vi.fn();await expect(requestEnvironmentCameraStream({getUserMedia},controller.signal)).rejects.toHaveProperty('name','AbortError');expect(getUserMedia).not.toHaveBeenCalled();});
 it('handles synchronous platform failures',async()=>{await expect(requestCameraStream({getUserMedia:()=>{throw new DOMException('blocked','SecurityError');}},{video:true},new AbortController().signal)).rejects.toHaveProperty('name','SecurityError');});
 it('shows actionable pending permission guidance',()=>expect(cameraErrorMessage(new DOMException('pending','TimeoutError'))).toContain('Chrome or Edge'));
});
