import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

/* global document, innerHeight, innerWidth */
const root=process.cwd(),out=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0228-interactive-intermediate-coordinate-geometry-section-formula-redesigned.png",url=process.env.LESSON_URL??"http://127.0.0.1:2254/lessons/geometry/171-section-formula";
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1447,height:1087}}),page=await context.newPage(),consoleMessages=[];page.on("console",m=>{if(["error","warning"].includes(m.type()))consoleMessages.push(`${m.type()}: ${m.text()}`)});await page.goto(url,{waitUntil:"domcontentloaded",timeout:180000});const lesson=page.getByTestId("geometry-mockup-0228");await lesson.waitFor({timeout:600000});const state=()=>lesson.evaluate(el=>Object.fromEntries(["mode","m","n","point","ratio","tab","grid","axes","labels","snap","compare","status"].map(n=>[n,el.getAttribute(`data-${n}`)])));const checks={initial:await state()};
await lesson.getByRole("button",{name:/Tools/}).click();checks.tools=await lesson.getByRole("region",{name:"Graph tools"}).isVisible();await lesson.getByRole("button",{name:/Tools/}).click();await lesson.getByLabel("Ratio m").fill("5");await lesson.getByLabel("Ratio n").fill("4");checks.inputs=await state();await lesson.getByLabel("Ratio slider").fill("6");checks.slider=await state();await lesson.getByRole("button",{name:"Reset lesson"}).click();const p=lesson.getByTestId("section-point"),box=await p.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+70,box.y+box.height/2-23,{steps:7});await page.mouse.up();checks.pointer=await state();await p.press("ArrowLeft");checks.keyboard=await state();
for(const label of ["Grid","Axes","Labels"])await lesson.getByLabel(label).uncheck();await lesson.getByLabel("Snap").check();checks.visibility=await state();for(const label of ["Grid","Axes","Labels"])await lesson.getByLabel(label).check();await lesson.getByLabel("Snap").uncheck();for(const label of ["Observe","Notice","Understand","Try","Manipulate"])await lesson.getByRole("button",{name:new RegExp(label)}).click();
await lesson.getByRole("button",{name:"External division"}).click();await lesson.getByLabel("Ratio m").fill("3");await lesson.getByLabel("Ratio n").fill("1");checks.external=await state();await lesson.getByRole("button",{name:"Internal division"}).click();await lesson.getByLabel("Compare ratios").check();await lesson.getByRole("button",{name:"1 : 2"}).click();checks.compare=await state();
await lesson.getByLabel("Practice section x").fill("0");await lesson.getByLabel("Practice section y").fill("0");await lesson.getByRole("button",{name:/Check Answer/}).click();checks.wrong=await state();await lesson.getByLabel("Practice section x").fill("1.2");await lesson.getByLabel("Practice section y").fill("1.4");await lesson.getByRole("button",{name:/Check Answer/}).click();checks.correct=await state();await lesson.getByRole("button",{name:/Lesson Resources/}).click();checks.resources=await lesson.getByRole("region",{name:"Lesson resources"}).isVisible();await lesson.getByRole("button",{name:/Lesson Resources/}).click();await lesson.getByRole("button",{name:"Reset lesson"}).click();checks.reset=await state();await page.evaluate(()=>{document.documentElement.scrollTop=0;document.body.scrollTop=0});
const previousHref=await lesson.locator(".sf171-nav a").first().getAttribute("href"),nextHref=await lesson.locator(".sf171-nav a").last().getAttribute("href");const metrics=await page.evaluate(()=>{const region=s=>{const r=document.querySelector(s)?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height}:null};return{viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},horizontalOverflow:document.documentElement.scrollWidth>innerWidth,verticalOverflow:document.documentElement.scrollHeight>innerHeight,regions:{page:region(".sf171-page"),header:region(".sf171-header"),body:region(".sf171-body"),stages:region(".sf171-stages"),lab:region(".sf171-lab"),graph:region(".sf171-grid"),how:region(".sf171-how"),side:region(".sf171-side"),navigation:region(".sf171-nav"),footer:region(".sf171-footer")}}});const geometryPassed=metrics.viewport.width===1447&&metrics.viewport.height===1087&&metrics.document.width===1447&&Math.round(metrics.regions.page.left)===250&&Math.abs(metrics.regions.header.top-110)<=1&&Math.abs(metrics.regions.body.top-244)<=1;
const passed=checks.initial.mode==="internal"&&checks.initial.m==="3"&&checks.initial.n==="4"&&checks.initial.point==="-0.14:2.29"&&checks.initial.ratio==="0.750"&&checks.tools===true&&checks.inputs.point==="1:2.67"&&checks.slider.m==="6"&&checks.pointer.point!==checks.initial.point&&checks.keyboard.point!==checks.pointer.point&&checks.visibility.grid==="false"&&checks.visibility.axes==="false"&&checks.visibility.labels==="false"&&checks.visibility.snap==="true"&&checks.external.mode==="external"&&checks.external.point==="9.50:5.50"&&checks.compare.compare==="true"&&checks.compare.m==="1"&&checks.compare.n==="2"&&checks.wrong.status==="Recheck the weighted coordinates"&&checks.correct.status==="Correct section point"&&checks.resources===true&&checks.reset.point==="-0.14:2.29"&&previousHref==="/lessons/geometry/170-midpoint"&&nextHref==="/lessons/geometry/172-gradient-slope"&&geometryPassed&&!metrics.horizontalOverflow&&consoleMessages.length===0;await page.screenshot({path:path.join(out,"0228-desktop.png"),fullPage:true});await copyFile(reference,path.join(out,"0228-reference.png"));const report={mockup:"0228",lessonId:171,route:"/lessons/geometry/171-section-formula",checks,navigation:{previousHref,nextHref},metrics,consoleMessages,passed,mathNote:"Target mockup arithmetic is inconsistent: 3*5 + 4*(-4) = -1, not 1; implementation correctly gives P=(-1/7,16/7) for the displayed initial inputs."};await writeFile(path.join(out,"0228-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await browser.close();process.exit(passed?0:1);
