import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd(), evidence = path.join(root, "test-evidence", "lesson-ui-upgrade");
const reference = "D:\\Math App Screenshots for UI Update\\Updated UI\\0339-interactive-intermediate-advanced-cas-workspace-solve-redesigned.png";
const url = process.env.LESSON_URL ?? "http://127.0.0.1:2255/lessons/symbolic-mathematics/433-solve";
const browser = await chromium.launch({ headless: true }), page = await browser.newPage({ viewport: { width: 1012, height: 1555 } }), consoleMessages = [];
page.on("console", (message) => { if (["error", "warning"].includes(message.type())) consoleMessages.push(`${message.type()}: ${message.text()}`); });
await page.goto(url, { waitUntil: "domcontentloaded", timeout: 180000 });
const lesson = page.getByTestId("symbolic-cas-mockup-0339"); await lesson.waitFor({ timeout: 600000 });
const state = () => lesson.evaluate((node) => Object.fromEntries(["equation", "valid", "coefficients", "pair", "roots", "factors", "stage", "actions", "practice-feedback"].map((key) => [key, node.getAttribute(`data-${key}`)])));
const checks = { initial: await state() };
const equation = lesson.getByLabel("Equation to solve");
await equation.fill("x^2+2x-8=0"); checks.edited = await state();
await equation.fill("x^2-5x+6=0");
const dropzone = lesson.locator('[data-lesson-control="solve-operation-dropzone"]');
await lesson.locator('[data-lesson-control="solve-operation-add-linear"]').dragTo(dropzone); checks.addedLinear = await state();
await lesson.locator('[data-lesson-control="solve-operation-subtract-constant"]').click(); checks.subtractedConstant = await state();
await lesson.locator('[data-lesson-control="solve-operation-factor"]').click(); checks.factored = await state();
await lesson.locator('[data-lesson-control="solve-fullscreen"]').click(); checks.fullscreenOpen = await lesson.evaluate((node) => node.classList.contains("fullscreen"));
await lesson.locator('[data-lesson-control="solve-fullscreen"]').click(); checks.fullscreenClosed = await lesson.evaluate((node) => !node.classList.contains("fullscreen"));
await lesson.locator('[data-lesson-control="solve-practice-try"]').click();
await lesson.getByLabel("First practice root").fill("-4"); await lesson.getByLabel("Second practice root").fill("3"); await lesson.locator('[data-lesson-control="solve-practice-check"]').click(); checks.rejected = await state();
await lesson.getByLabel("Second practice root").fill("2"); await lesson.locator('[data-lesson-control="solve-practice-check"]').click(); checks.accepted = await state();
await lesson.locator('[data-lesson-control="solve-practice-show"]').click(); checks.solutionShown = await lesson.locator('[data-lesson-control="solve-practice-show"]').textContent();
await page.getByTitle("Reset lesson progress").click(); checks.reset = await state();
const navigation = { previousHref: await lesson.getByRole("link", { name: /Previous/ }).getAttribute("href"), nextHref: await lesson.getByRole("link", { name: /Next/ }).getAttribute("href") };
const metrics = await page.evaluate(() => { const rect = (selector) => { const element = globalThis.document.querySelector(selector); if (!element) return null; const box = element.getBoundingClientRect(); return { top: Math.round(box.top), left: Math.round(box.left), width: Math.round(box.width), height: Math.round(box.height), bottom: Math.round(box.bottom) }; }; return { document: { width: globalThis.document.documentElement.scrollWidth, height: globalThis.document.documentElement.scrollHeight }, overflow: globalThis.document.documentElement.scrollWidth > globalThis.innerWidth, sidebar: rect('[data-testid="desktop-sidebar"]'), header: rect(".lesson-shell-header"), tabs: rect('nav[role="tablist"]'), lab: rect(".sol433-lab"), flow: rect(".sol433-flow"), body: rect(".sol433-body"), practice: rect(".sol433-bottom"), adjacent: rect(".sol433-nav") }; });
const passed = checks.initial.roots === "2,3" && checks.initial.pair === "-2,-3" && checks.initial.factors === "(x - 2)(x - 3)" && checks.edited.coefficients === "1,2,-8" && checks.edited.roots === "-4,2" && checks.addedLinear.stage === "1" && checks.subtractedConstant.stage === "2" && checks.factored.stage === "3" && checks.fullscreenOpen && checks.fullscreenClosed && checks.rejected["practice-feedback"] === "incorrect" && checks.accepted["practice-feedback"] === "correct" && checks.solutionShown?.includes("-4, 2") && checks.reset.equation === "x^2-5x+6=0" && checks.reset.actions === "0" && navigation.previousHref === "/lessons/symbolic-mathematics/432-substitute" && navigation.nextHref === "/lessons/symbolic-mathematics/434-numerical-solve" && metrics.document.width === 1012 && metrics.document.height === 1555 && metrics.sidebar?.width === 205 && metrics.header?.top === 110 && metrics.tabs?.top === 369 && metrics.lab?.top === 426 && metrics.flow?.top === 505 && metrics.body?.bottom === 1258 && metrics.adjacent?.bottom === 1546 && !metrics.overflow && consoleMessages.length === 0;
const report = { mockup: "0339", lessonId: 433, checks, navigation, metrics, consoleMessages, passed };
await page.screenshot({ path: path.join(evidence, "0339-desktop.png"), fullPage: true }); await copyFile(reference, path.join(evidence, "0339-reference.png")); await writeFile(path.join(evidence, "0339-dedicated-target-validation.json"), `${JSON.stringify(report, null, 2)}\n`); await browser.close(); console.log(JSON.stringify(report, null, 2)); if (!passed) process.exitCode = 1;
