import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const out = path.join(root, "test-evidence", "lesson-ui-upgrade");
const reference = "D:\\Math App Screenshots for UI Update\\Updated UI\\0021-interactive-foundational-advanced-algebra-and-dynamic-variables-numeric-sliders-redesigned.png";
const url = process.env.LESSON_URL ?? "http://localhost:2245/lessons/core-workspaces/21-numeric-sliders";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1217, height: 1292 } });
const consoleMessages = [];
page.on("console", (message) => { if (["error", "warning"].includes(message.type())) consoleMessages.push(`${message.type()}: ${message.text()}`); });
await page.goto(url, { waitUntil: "domcontentloaded", timeout: 180000 });
const node = page.getByTestId("algebra-mockup-0021");
await node.waitFor({ timeout: 180000 });
const state = () => node.evaluate((element) => Object.fromEntries(["data-x", "data-y", "data-min", "data-max", "data-step", "data-actions"].map((name) => [name.replace("data-", ""), element.getAttribute(name)])));
const checks = { initial: await state() };
await page.getByLabel("Numeric slider x drag control").fill("-1.5");
checks.slider = await state();
await page.locator(".numeric-pattern button").filter({ hasText: "x = 4" }).click();
checks.preset = await state();
await page.getByLabel("Minimum slider value").fill("-3");
await page.getByLabel("Maximum slider value").fill("8");
checks.bounds = await state();
await page.locator("#numeric-step").selectOption("0.5");
await page.getByLabel("Decrease x").click();
checks.precisionStep = await state();
await page.getByRole("button", { name: "Reset" }).click();
checks.reset = await state();
const metrics = await page.evaluate(() => {
  const region = (selector) => { const rect = document.querySelector(selector)?.getBoundingClientRect(); return rect ? { top: rect.top, bottom: rect.bottom, height: rect.height, left: rect.left, right: rect.right, width: rect.width } : null; };
  return { viewport: { width: innerWidth, height: innerHeight }, document: { width: document.documentElement.scrollWidth, height: document.documentElement.scrollHeight }, horizontalOverflow: document.documentElement.scrollWidth > innerWidth, surface: region(".numeric-slider-page"), regions: { card: region(".numeric-surface"), header: region(".numeric-header"), main: region(".numeric-main"), slider: region(".numeric-slider-stage"), linked: region(".numeric-linked"), pattern: region(".numeric-pattern"), control: region(".numeric-control"), graph: region(".numeric-graph"), neighbors: region(".numeric-neighbors"), footer: region(".numeric-footer") } };
});
const passed = checks.initial.x === "2" && checks.initial.y === "7" && checks.slider.x === "-1.5" && checks.slider.y === "0" && checks.preset.x === "4" && checks.preset.y === "11" && checks.bounds.min === "-3" && checks.bounds.max === "8" && checks.precisionStep.step === "0.5" && checks.precisionStep.x === "3.5" && checks.precisionStep.y === "10" && checks.reset.x === "2" && checks.reset.y === "7" && checks.reset.min === "-5" && checks.reset.max === "5" && checks.reset.step === "0.1" && !metrics.horizontalOverflow && consoleMessages.length === 0;
await page.screenshot({ path: path.join(out, "0021-desktop.png") });
await copyFile(reference, path.join(out, "0021-reference.png"));
const report = { mockup: "0021", lessonId: 21, route: "/lessons/core-workspaces/21-numeric-sliders", objectModel: "continuous-bounded-precision-slider-linked-substitution-pattern-coordinate-graph-model", checks, metrics, consoleMessages, passed };
await writeFile(path.join(out, "0021-dedicated-target-validation.json"), `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify(report, null, 2));
await browser.close();
process.exit(passed ? 0 : 1);
