import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";
const root=process.cwd(),out=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0012-interactive-foundational-advanced-scientific-calculator-hyperbolic-functions-redesigned.png",url=process.env.LESSON_URL??"http://localhost:2245/lessons/core-workspaces/12-hyperbolic-functions";
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1068,height:1472}}),consoleMessages=[];page.on("console",m=>{if(["error","warning"].includes(m.type()))consoleMessages.push(`${m.type()}: ${m.text()}`)});
await page.goto(url,{waitUntil:"domcontentloaded"});const node=page.getByTestId("calculator-mockup-0012");await node.waitFor();const state=()=>node.evaluate(e=>Object.fromEntries(["data-x","data-positive","data-negative","data-output","data-actions","data-view","data-practice","data-revealed"].map(n=>[n.replace("data-",""),e.getAttribute(n)])));const checks={initial:await state()};
await page.getByLabel("Hyperbolic x drag control").fill("1.5");checks.drag=await state();await page.getByLabel("Hyperbolic x drag control").fill("-1");checks.negative=await state();await page.getByRole("button",{name:/Reset/}).click();checks.reset=await state();await page.getByRole("button",{name:"Examples",exact:true}).click();checks.view=await state();await page.getByRole("button",{name:/Hide answer/}).click();checks.hidden=await state();await page.getByRole("button",{name:/New practice/}).click();checks.problem=await state();await page.getByRole("button",{name:/Reveal answer/}).click();checks.revealed=await state();
await page.reload({waitUntil:"domcontentloaded"});await node.waitFor();const metrics=await page.evaluate(()=>{const region=s=>{const r=document.querySelector(s)?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom,height:r.height,left:r.left,right:r.right,width:r.width}:null};return{viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},horizontalOverflow:document.documentElement.scrollWidth>innerWidth,surface:region(".target-hyper-page"),regions:{header:region(".hyper-header"),tabs:region(".hyper-tabs"),lab:region(".hyper-lab"),columns:region(".hyper-columns"),graph:region(".hyper-graph"),practice:region(".hyper-practice"),neighbors:region(".hyper-neighbors"),footer:region(".hyper-footer")}}});
const passed=checks.initial.output==="1.175"&&checks.drag.positive==="4.482"&&checks.drag.negative==="0.223"&&checks.drag.output==="2.129"&&checks.negative.output==="-1.175"&&checks.reset.x==="1"&&checks.view.view==="2"&&checks.hidden.revealed==="false"&&checks.problem.practice==="1"&&checks.revealed.revealed==="true"&&!metrics.horizontalOverflow&&consoleMessages.length===0;await page.screenshot({path:path.join(out,"0012-desktop.png")});await copyFile(reference,path.join(out,"0012-reference.png"));const report={mockup:"0012",lessonId:12,route:"/lessons/core-workspaces/12-hyperbolic-functions",objectModel:"draggable-x-dual-exponential-hyperbolic-sine-difference-trace-practice-model",checks,metrics,consoleMessages,passed};await writeFile(path.join(out,"0012-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await browser.close();process.exit(passed?0:1);
