/* global document, innerWidth, scrollTo */
import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root=process.cwd(),evidence=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0355-interactive-intermediate-advanced-cas-workspace-cas-to-graph-link-redesigned.png",url=process.env.LESSON_URL??"http://127.0.0.1:2255/lessons/symbolic-mathematics/449-cas-to-graph-link";
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1023,height:1538}}),consoleMessages=[];
page.on("console",message=>{if(["error","warning"].includes(message.type()))consoleMessages.push(`${message.type()}: ${message.text()}`)});
await page.goto(url,{waitUntil:"domcontentloaded",timeout:180000});const lesson=page.getByTestId("symbolic-cas-mockup-0355");await lesson.waitFor({timeout:600000});
const state=()=>lesson.evaluate(node=>Object.fromEntries(["series","expressions","practice-a","practice-b","feedback","actions"].map(key=>[key,node.getAttribute(`data-${key}`)])));const checks={initial:await state()};
await lesson.getByLabel("Expression 1").fill("-x + 1");checks.edited=await state();
await lesson.locator('[data-lesson-control="style-1"]').click();await lesson.locator('[data-lesson-control="color-1"]').click();checks.styled=await state();
await lesson.locator('[data-lesson-control="remove-3"]').click();checks.removed=await state();await lesson.locator('[data-lesson-control="add-expression"]').click();checks.added=await state();
await lesson.locator('[data-lesson-control="a (slope)-plus"]').click();await lesson.locator('[data-lesson-control="practice-check"]').click();checks.rejected=await state();await lesson.locator('[data-lesson-control="a (slope)-minus"]').click();await lesson.locator('[data-lesson-control="practice-check"]').click();checks.accepted=await state();
await page.getByTitle("Reset lesson progress").dispatchEvent("click");await page.waitForFunction(()=>document.querySelector('[data-testid="symbolic-cas-mockup-0355"]')?.getAttribute("data-actions")==="0");checks.reset=await state();
const navigation={previousHref:await lesson.getByRole("link",{name:/Previous/}).getAttribute("href"),nextHref:await lesson.getByRole("link",{name:/Next/}).getAttribute("href")};
await page.evaluate(()=>{document.querySelectorAll("*").forEach(element=>{try{element.scrollLeft=0;element.scrollTop=0}catch{/* SVG */}});scrollTo(0,0)});await page.waitForTimeout(100);
const metrics=await page.evaluate(()=>{const rect=selector=>{const element=document.querySelector(selector);if(!element)return null;const box=element.getBoundingClientRect();return Object.fromEntries(["top","left","width","height","bottom"].map(key=>[key,Math.round(box[key])]))};return{document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},overflow:document.documentElement.scrollWidth>innerWidth,sidebar:rect('[data-testid="desktop-sidebar"]'),shellHeader:rect(".lesson-shell-header"),hero:rect(".cg449-hero"),flow:rect(".cg449-flow"),workspace:rect(".cg449-workspace"),graph:rect(".cg449-graph svg"),learning:rect(".cg449-learning"),practice:rect(".cg449-practice"),adjacent:rect(".cg449-nav"),footer:rect('footer[aria-label="Site footer"]')}});
const paths=await lesson.locator(".cg449-graph path").count(),passed=checks.initial.series==="3"&&checks.initial.expressions==="2x + 4|3x - 2|x^2 - 4"&&checks.edited.expressions.startsWith("-x + 1")&&checks.removed.series==="2"&&checks.added.series==="3"&&checks.rejected.feedback==="incorrect"&&checks.accepted.feedback==="correct"&&checks.reset.expressions==="2x + 4|3x - 2|x^2 - 4"&&checks.reset.actions==="0"&&paths===3&&navigation.previousHref==="/lessons/symbolic-mathematics/448-step-by-step-algebra"&&metrics.document.width===1023&&!metrics.overflow&&metrics.sidebar?.width===215&&metrics.shellHeader?.height===0&&consoleMessages.length===0;
const report={mockup:"0355",lessonId:449,checks,paths,navigation,metrics,consoleMessages,passed};await page.screenshot({path:path.join(evidence,"0355-desktop.png"),fullPage:true});await copyFile(reference,path.join(evidence,"0355-reference.png"));await writeFile(path.join(evidence,"0355-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);await browser.close();console.log(JSON.stringify(report,null,2));if(!passed)process.exitCode=1;
