import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

/* global document, innerWidth, innerHeight */
const root=process.cwd(),out=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0189-interactive-intermediate-advanced-functions-vertical-line-test-redesigned.png",url=process.env.LESSON_URL??"http://127.0.0.1:2254/lessons/graphs-and-functions/132-vertical-line-test";
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:984,height:1598}}),page=await context.newPage(),consoleMessages=[];
page.on("console",message=>{if(["error","warning"].includes(message.type()))consoleMessages.push(`${message.type()}: ${message.text()}`);});
await page.goto(url,{waitUntil:"domcontentloaded",timeout:180000});const node=page.getByTestId("graph-mockup-0189");await node.waitFor({timeout:600000});
const names=["relation","radius","test-x","hits","hit-values","passes","actions"],state=()=>node.evaluate((element,attrs)=>Object.fromEntries(attrs.map(name=>[name,element.getAttribute(`data-${name}`)])),names),checks={initial:await state()};
const dragRange=async(locator,startFraction,delta)=>{const box=await locator.boundingBox();if(!box)throw new Error("Range has no box");const x=box.x+box.width*startFraction,y=box.y+box.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+box.width*delta,y,{steps:8});await page.mouse.up();};
await dragRange(node.getByRole("slider",{name:"Vertical test line position"}),.5,.2);checks.rangeDrag=await state();
const graphLine=node.getByRole("slider",{name:"Drag vertical test line"}),graph=node.locator(".vlt132-graph"),lineBox=await graphLine.boundingBox(),graphBox=await graph.boundingBox();if(!lineBox||!graphBox)throw new Error("Scanner geometry unavailable");const lineX=lineBox.x+lineBox.width/2,lineY=lineBox.y+lineBox.height/2;await page.mouse.move(lineX,lineY);await page.mouse.down();await page.mouse.move(lineX+graphBox.width*(48/430),lineY,{steps:8});await page.mouse.up();checks.graphDrag=await state();
await graphLine.focus();await graphLine.press("ArrowRight");checks.keyboard=await state();
await node.getByRole("button",{name:"Reset",exact:true}).click();checks.tangentBaseline=await state();await dragRange(node.getByRole("slider",{name:"Vertical test line position"}),.5,.333);checks.tangent=await state();
await node.getByRole("button",{name:/Passes: y = x²/}).click();checks.parabola=await state();
await node.getByRole("button",{name:/Fails: x = y²/}).click();checks.sideways=await state();
await node.getByRole("button",{name:"Next x-value"}).click();checks.tryIt=await state();
await node.getByRole("button",{name:"Examples",exact:true}).click();checks.example=await state();
await node.getByRole("button",{name:"Reset",exact:true}).click();checks.reset=await state();
const metrics=await page.evaluate(()=>{const region=selector=>{const rect=document.querySelector(selector)?.getBoundingClientRect();return rect?{top:rect.top,bottom:rect.bottom,height:rect.height,left:rect.left,right:rect.right,width:rect.width}:null;};return{viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},horizontalOverflow:document.documentElement.scrollWidth>innerWidth,verticalOverflow:document.documentElement.scrollHeight>innerHeight,regions:{surface:region(".vlt132-page"),intro:region(".vlt132-intro"),tabs:region(".vlt132-tabs"),lab:region(".vlt132-lab"),layout:region(".vlt132-layout"),main:region(".vlt132-main"),plot:region(".vlt132-plot"),rail:region(".vlt132-rail"),steps:region(".vlt132-steps"),compare:region(".vlt132-compare"),lower:region(".vlt132-result"),navigation:region(".vlt132-adjacent"),footer:region(".vlt132-footer")}};});
const passed=checks.initial.relation==="circle"&&checks.initial.radius==="3"&&checks.initial["test-x"]==="0"&&checks.initial.hits==="2"&&checks.initial["hit-values"]==="3,-3"&&checks.initial.passes==="false"&&checks.rangeDrag["test-x"]!=="0"&&checks.graphDrag["test-x"]!==checks.rangeDrag["test-x"]&&Number(checks.keyboard["test-x"])===Number(checks.graphDrag["test-x"])+.5&&checks.tangent["test-x"]==="3"&&checks.tangent.hits==="1"&&checks.parabola.relation==="parabola"&&checks.parabola.hits==="1"&&checks.parabola.passes==="true"&&checks.sideways.relation==="sideways"&&checks.sideways["test-x"]==="4"&&checks.sideways.hits==="2"&&checks.sideways["hit-values"]==="2,-2"&&checks.tryIt["test-x"]==="2"&&checks.example.relation==="parabola"&&checks.example["test-x"]==="2"&&checks.example.hits==="1"&&checks.reset.relation==="circle"&&checks.reset.radius==="3"&&checks.reset["test-x"]==="0"&&!metrics.horizontalOverflow&&!metrics.verticalOverflow&&consoleMessages.length===0;
await page.screenshot({path:path.join(out,"0189-desktop.png")});await copyFile(reference,path.join(out,"0189-reference.png"));const report={mockup:"0189",lessonId:132,route:"/lessons/graphs-and-functions/132-vertical-line-test",checks,metrics,consoleMessages,passed};await writeFile(path.join(out,"0189-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await browser.close();process.exit(report.passed?0:1);
