import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd(), out = path.join(root, "test-evidence", "lesson-ui-upgrade");
const reference = "D:\\Math App Screenshots for UI Update\\Updated UI\\0261-interactive-foundational-advanced-dynamic-geometry-constructions-segment-redesigned.png";
const url = process.env.LESSON_URL ?? "http://127.0.0.1:2255/lessons/geometry/204-segment";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1024, height: 1536 } });
const messages = [];
page.on("console", (m) => { if (["error","warning"].includes(m.type())) messages.push(`${m.type()}: ${m.text()}`); });
await page.goto(url, { waitUntil: "domcontentloaded", timeout: 180000 });
const lesson = page.getByTestId("dynamic-geometry-mockup-0261");
await lesson.waitFor({ timeout: 600000 });
const state = () => lesson.evaluate((node) => Object.fromEntries(["model","a","b","length","midpoint","snap","stage","compare","tool","history","solution","shared"].map((key) => [key,node.getAttribute(`data-${key}`)])));
const checks = { initial: await state() };
const endpoint = lesson.getByTestId("segment-point-a").locator("circle"), box = await endpoint.boundingBox();
await page.mouse.move(box.x+box.width/2,box.y+box.height/2); await page.mouse.down(); await page.mouse.move(box.x+box.width/2+72,box.y+box.height/2-36,{steps:4}); await page.mouse.up();
checks.dragged = await state();
await lesson.getByRole("button",{name:"Undo",exact:true}).click(); checks.undo = await state();
await lesson.getByRole("button",{name:"Redo",exact:true}).click(); checks.redo = await state();
await lesson.getByRole("button",{name:"Reset",exact:true}).click();
await lesson.getByRole("button",{name:"Snap",exact:true}).click();
const bpoint=lesson.getByTestId("segment-point-b").locator("circle"), bbox=await bpoint.boundingBox(); await page.mouse.move(bbox.x+bbox.width/2,bbox.y+bbox.height/2);await page.mouse.down();await page.mouse.move(bbox.x+bbox.width/2-25,bbox.y+bbox.height/2+19,{steps:3});await page.mouse.up();checks.unsnapped=await state();
for(const mode of ["line","ray","none"]) await lesson.getByRole("button",{name:mode,exact:true}).click(); checks.compare=await state();
for(const name of ["Place nearest endpoint","Show segment","Compare ray","Toggle snap","Select endpoints"]) await lesson.getByRole("button",{name,exact:true}).click(); checks.tools=await state();
for(const name of ["Manipulate","Notice","Understand","Try","Observe"]) await lesson.getByRole("button",{name,exact:true}).click(); checks.stages=await state();
await lesson.getByLabel("Lesson language").selectOption({label:"Hindi (Hindi)"});
await lesson.getByRole("button",{name:"Share",exact:true}).click(); checks.shared=await state();
await lesson.getByRole("button",{name:"Workspace",exact:true}).click(); checks.workspaceOn=await lesson.getByRole("button",{name:"Workspace",exact:true}).getAttribute("aria-pressed"); await lesson.getByRole("button",{name:"Workspace",exact:true}).evaluate((button)=>button.click());
for(const [label,value] of [["A x coordinate","-2"],["A y coordinate","-1"],["B x coordinate","3"],["B y coordinate","4"]]) await lesson.getByLabel(label,{exact:true}).fill(value);
checks.taskPoints=await state(); await lesson.getByRole("button",{name:"Check Answer",exact:true}).click(); checks.answer=await lesson.getByRole("status").textContent(); await lesson.getByRole("button",{name:"Show Solution",exact:true}).click(); checks.solution=await state();
const previousHref=await lesson.locator(".sg204-nav a").first().getAttribute("href"),nextHref=await lesson.locator(".sg204-nav a").last().getAttribute("href");
await page.reload({waitUntil:"domcontentloaded"});await lesson.waitFor();
const metrics=await page.evaluate(()=>{const region=(s)=>{const b=globalThis.document.querySelector(s)?.getBoundingClientRect();return b?{top:b.top,left:b.left,width:b.width,height:b.height,bottom:b.bottom}:null;};return{document:{width:globalThis.document.documentElement.scrollWidth,height:globalThis.document.documentElement.scrollHeight},overflow:globalThis.document.documentElement.scrollWidth>globalThis.innerWidth,regions:{header:region(".sg204-header"),stages:region(".sg204-stages"),main:region(".sg204-main"),practice:region(".sg204-practice"),nav:region(".sg204-nav"),footer:region(".sg204-footer")}};});
const geometry=metrics.document.width===1024&&metrics.document.height<=1536&&Math.round(metrics.regions.header.left)===240&&Math.round(metrics.regions.header.width)===768&&Math.round(metrics.regions.header.top)===114&&Math.round(metrics.regions.footer.bottom)<=1536;
const passed=checks.initial.model==="finite-two-endpoint-distance-midpoint-comparison"&&checks.initial.a==="-3:1"&&checks.initial.b==="4:2"&&Math.abs(Number(checks.initial.length)-Math.sqrt(50))<1e-10&&checks.initial.midpoint==="0.5:1.5"&&checks.dragged.a!==checks.initial.a&&checks.undo.a===checks.initial.a&&checks.redo.a===checks.dragged.a&&checks.unsnapped.snap==="false"&&checks.unsnapped.b!==checks.initial.b&&checks.compare.compare==="none"&&checks.tools.tool==="select"&&checks.stages.stage==="Observe"&&checks.shared.shared==="true"&&checks.workspaceOn==="true"&&checks.taskPoints.a==="-2:-1"&&checks.taskPoints.b==="3:4"&&checks.answer?.startsWith("Correct")&&checks.solution.solution==="true"&&previousHref==="/lessons/geometry/203-line-through-two-points"&&nextHref==="/lessons/geometry/205-segment-with-given-length"&&geometry&&!metrics.overflow&&messages.length===0;
await page.screenshot({path:path.join(out,"0261-desktop.png"),fullPage:true});await copyFile(reference,path.join(out,"0261-reference.png"));const report={mockup:"0261",lessonId:204,checks,navigation:{previousHref,nextHref},metrics,consoleMessages:messages,passed};await writeFile(path.join(out,"0261-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await browser.close();process.exit(passed?0:1);
