/* global document, innerWidth, scrollTo */
import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root=process.cwd(),evidence=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0353-interactive-intermediate-advanced-cas-workspace-exact-numeric-toggle-redesigned.png",url=process.env.LESSON_URL??"http://127.0.0.1:2255/lessons/symbolic-mathematics/447-exact-numeric-toggle";
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:995,height:1580}}),consoleMessages=[];
page.on("console",message=>{if(["error","warning"].includes(message.type()))consoleMessages.push(`${message.type()}: ${message.text()}`)});
await page.goto(url,{waitUntil:"domcontentloaded",timeout:180000});const lesson=page.getByTestId("symbolic-cas-mockup-0353");await lesson.waitFor({timeout:600000});
const state=()=>lesson.evaluate(node=>Object.fromEntries(["expression","exact","numeric","error","mode","precision","feedback","actions"].map(key=>[key,node.getAttribute(`data-${key}`)])));
const checks={initial:await state()};
await lesson.locator('[data-lesson-control="mode-numeric"]').click();await lesson.locator('[data-lesson-control="precision-minus"]').click();await lesson.locator('[data-lesson-control="precision-minus"]').click();checks.numericSix=await state();
await lesson.locator('[data-lesson-control="exact-example-1"]').click();checks.sqrt=await state();
await lesson.locator('[data-lesson-control="exact-example-2"]').click();checks.third=await state();
await lesson.getByLabel("Practice exact result").fill("4pi-sqrt(3)+2/7");await lesson.getByLabel("Practice numeric result").fill("0");await lesson.getByLabel("Practice rounding error").fill("0");await lesson.locator('[data-lesson-control="exact-practice-check"]').click();checks.rejected=await state();
const challengeValue=4*Math.PI-Math.sqrt(3)+2/7,challengeRounded=challengeValue.toFixed(8).replace(/0+$/,"").replace(/\.$/,""),challengeError=Math.abs(Number(challengeRounded)-challengeValue).toExponential(2);
await lesson.getByLabel("Practice numeric result").fill(challengeRounded);await lesson.getByLabel("Practice rounding error").fill(challengeError);await lesson.locator('[data-lesson-control="exact-practice-check"]').click();checks.accepted=await state();
await page.getByTitle("Reset lesson progress").dispatchEvent("click");await page.waitForFunction(()=>document.querySelector('[data-testid="symbolic-cas-mockup-0353"]')?.getAttribute("data-actions")==="0");checks.reset=await state();
const navigation={previousHref:await lesson.getByRole("link",{name:/Previous/}).getAttribute("href"),nextHref:await lesson.getByRole("link",{name:/Next/}).getAttribute("href")};
await page.evaluate(()=>{document.querySelectorAll("*").forEach(element=>{try{element.scrollLeft=0;element.scrollTop=0}catch{/* Some SVG properties are read-only. */}});scrollTo(0,0)});await page.waitForTimeout(100);
const metrics=await page.evaluate(()=>{const rect=selector=>{const element=document.querySelector(selector);if(!element)return null;const box=element.getBoundingClientRect();return Object.fromEntries(["top","left","width","height","bottom"].map(key=>[key,Math.round(box[key])]))};return{document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},overflow:document.documentElement.scrollWidth>innerWidth,sidebar:rect('[data-testid="desktop-sidebar"]'),shellHeader:rect(".lesson-shell-header"),hero:rect(".en447-hero"),flow:rect(".en447-flow"),workspace:rect(".en447-workspace"),results:rect(".en447-results"),rule:rect(".en447-rule"),misconception:rect(".en447-misconception"),worked:rect(".en447-worked"),practice:rect(".en447-practice"),adjacent:rect(".en447-nav"),footer:rect('footer[aria-label="Site footer"]')}});
const passed=checks.initial.exact==="353/4 + √2"&&Math.abs(Number(checks.initial.numeric)-(353/4+Math.sqrt(2)))<1e-8&&checks.initial.precision==="8"&&checks.numericSix.mode==="numeric"&&checks.numericSix.precision==="6"&&checks.numericSix.numeric==="89.664214"&&checks.sqrt.exact==="√2"&&checks.third.exact==="1/3"&&checks.rejected.feedback==="incorrect"&&checks.accepted.feedback==="correct"&&checks.reset.exact==="353/4 + √2"&&checks.reset.mode==="exact"&&checks.reset.precision==="8"&&checks.reset.actions==="0"&&navigation.previousHref==="/lessons/symbolic-mathematics/446-assumptions"&&navigation.nextHref==="/lessons/symbolic-mathematics/448-step-by-step-algebra"&&metrics.document.width===995&&metrics.document.height===1580&&!metrics.overflow&&metrics.sidebar?.width===208&&metrics.shellHeader?.height===0&&metrics.footer?.height===0&&consoleMessages.length===0;
const report={mockup:"0353",lessonId:447,checks,challenge:{value:challengeValue,rounded:challengeRounded,error:challengeError},navigation,metrics,consoleMessages,passed};await page.screenshot({path:path.join(evidence,"0353-desktop.png"),fullPage:true});await copyFile(reference,path.join(evidence,"0353-reference.png"));await writeFile(path.join(evidence,"0353-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);await browser.close();console.log(JSON.stringify(report,null,2));if(!passed)process.exitCode=1;
