import { chromium } from "playwright";
import { copyFile, writeFile } from "node:fs/promises";
import path from "node:path";

/* global document, innerHeight, innerWidth */
const root=process.cwd(),out=path.join(root,"test-evidence","lesson-ui-upgrade"),reference="D:\\Math App Screenshots for UI Update\\Updated UI\\0223-interactive-intermediate-function-transformations-graph-matching-redesigned.png",url=process.env.LESSON_URL??"http://127.0.0.1:2254/lessons/graphs-and-functions/166-graph-matching";
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1206,height:1304}}),page=await context.newPage(),consoleMessages=[];page.on("console",m=>{if(["error","warning"].includes(m.type()))consoleMessages.push(`${m.type()}: ${m.text()}`)});await page.goto(url,{waitUntil:"domcontentloaded",timeout:180000});const node=page.getByTestId("graph-mockup-0223");await node.waitFor({timeout:600000});const state=()=>node.evaluate(el=>Object.fromEntries(["score","progress","stage","selected","matches","checked"].map(n=>[n,el.getAttribute(`data-${n}`)])));const checks={initial:await state()};
const equations=["y = (x - 2)² + 1","y = x²","y = (x + 2)² - 2","y = -x²","y = 2x²","y = -(x - 2)²"],targets=["rightUp","parent","leftDown","reflect","stretch","rightReflect"];
const cardFor=equation=>node.locator(".gm166-cards>button").filter({hasText:equation});
await cardFor(equations[0]).dragTo(node.locator(`[data-target="${targets[0]}"]`));checks.nativeDrag=await state();await cardFor(equations[1]).click();await node.locator(`[data-target="${targets[2]}"]`).click();await node.getByRole("button",{name:"Check Answers"}).click();checks.wrong=await state();checks.wrongText=await node.locator(".gm166-result").textContent();await node.getByRole("button",{name:"Reset",exact:true}).click();
for(let i=0;i<equations.length;i++){const card=cardFor(equations[i]);await card.focus();await card.press("Enter");await node.locator(`[data-target="${targets[i]}"]`).press("Enter")}checks.allAssigned=await state();await node.getByRole("button",{name:"Check Answers"}).click();checks.correct=await state();checks.correctText=await node.locator(".gm166-result").textContent();
await node.getByRole("checkbox",{name:"Show hints"}).uncheck();checks.hintsHidden=await node.locator(".gm166-cards small").count()===0;await node.getByRole("checkbox",{name:"Show hints"}).check();for(const label of ["2 Manipulate","3 Pattern","4 Rule","5 Practice","1 Observe"])await node.getByRole("button",{name:new RegExp(label)}).click();checks.stages=await state();await node.getByRole("button",{name:/Replay/}).click();checks.replay=await node.getByRole("button",{name:"Replay 1"}).isVisible();
const previousHref=await node.getByRole("link",{name:/Previous Lesson Parent-Function Library/}).getAttribute("href"),nextHref=await node.getByRole("link",{name:/Next Lesson Shifts & Reflections/}).getAttribute("href");await node.getByRole("button",{name:"Reset",exact:true}).click();checks.reset=await state();await page.evaluate(()=>{document.documentElement.scrollTop=0;document.body.scrollTop=0;document.querySelectorAll("*").forEach(el=>{if(el.scrollTop)el.scrollTop=0})});await page.waitForTimeout(80);
const metrics=await page.evaluate(()=>{const region=s=>{const r=document.querySelector(s)?.getBoundingClientRect();return r?{top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,height:r.height}:null};return{viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},horizontalOverflow:document.documentElement.scrollWidth>innerWidth,regions:{page:region(".gm166-page"),header:region(".gm166-header"),stages:region(".gm166-stages"),lab:region(".gm166-lab"),work:region(".gm166-work"),cards:region(".gm166-cards"),plot:region(".gm166-plot"),hints:region(".gm166-hints"),worked:region(".gm166-worked"),rule:region(".gm166-rule"),actions:region(".gm166-actions"),navigation:region(".gm166-nav")}}});
const geometryPassed=metrics.document.width===1206&&metrics.document.height===1304&&metrics.regions.page?.top===101&&metrics.regions.header?.left===258&&metrics.regions.header?.right===1188&&metrics.regions.lab?.top===355&&metrics.regions.navigation?.bottom===1287;
const passed=checks.initial.score==="0"&&checks.nativeDrag.score==="1"&&checks.wrong.score==="1"&&checks.wrongText?.includes("Score: 1/6")&&checks.allAssigned.score==="6"&&checks.correct.score==="6"&&checks.correct.progress==="100"&&checks.correctText?.includes("All six")&&checks.hintsHidden&&checks.stages.stage==="1"&&checks.replay&&checks.reset.score==="0"&&previousHref==="/lessons/graphs-and-functions/165-parent-function-library"&&nextHref==="/lessons/graphs-and-functions/167-cartesian-plane"&&geometryPassed&&!metrics.horizontalOverflow&&consoleMessages.length===0;
await page.screenshot({path:path.join(out,"0223-desktop.png")});await copyFile(reference,path.join(out,"0223-reference.png"));const report={mockup:"0223",lessonId:166,route:"/lessons/graphs-and-functions/166-graph-matching",checks,navigation:{previousHref,nextHref},metrics,consoleMessages,passed};await writeFile(path.join(out,"0223-dedicated-target-validation.json"),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report,null,2));await browser.close();process.exit(passed?0:1);
