import * as tf from '@tensorflow/tfjs';
import fs from 'node:fs';
import {semanticFeatures,inferSemanticHeads,HEADS} from '../src/math-robo/intelligence/hierarchicalModel';
import {splitSemanticRows} from '../src/math-robo/intelligence/semanticDataset';
import type {SemanticRow} from '../src/math-robo/intelligence/types';
const dir='reports/ruhi-2d-nlp',data=JSON.parse(fs.readFileSync('datasets/ruhi-2d-nlp/v1.normalized.json','utf8'));
type Row={id:string;phrase:string;split:string;labels:Record<string,string>};
const spec=JSON.parse(fs.readFileSync('public/models/math-robo-intelligence-v4/model.json','utf8')),bytes=fs.readFileSync('public/models/math-robo-intelligence-v4/weights.bin'),labels=spec.userDefinedMetadata.labels as Record<string,string[]>;
const mapping:Record<string,[string,string]>={create_polygon:['CREATE','TRIANGLE'],create_rectangle:['CREATE','RECTANGLE'],create_square:['CREATE','SQUARE'],create_circle:['CREATE','CIRCLE'],create_ellipse:['CREATE','ELLIPSE'],plot_equation:['CREATE','FUNCTION'],translate:['MOVE','OBJECT'],rotate:['ROTATE','OBJECT'],scale:['SCALE','UNIFORM'],set_style:['CHANGE','COLOR'],set_angle:['CHANGE','ANGLE'],set_slope:['CHANGE','SLOPE'],move_vertex:['MOVE','OBJECT'],reflect_copy:['REFLECT','Y_AXIS'],construct_incircle:['CONSTRUCT','INCIRCLE'],construct_centroid:['FIND','CENTROID'],construct_midpoint:['MARK','MIDPOINT'],create_segment:['CREATE','LINE'],construct_perpendicular:['CONSTRUCT','PERPENDICULAR'],extend_to_intersection:['EXTEND','OBJECT'],intersect:['FIND','INTERSECTION'],undo_action:['UNDO','LAST']};
const skipped:{id:string;reason:string}[]=[],rows:Row[]=[];
for(const r of data.records){if(r.split!=='test')continue;const a=r.expected.actions?.[0];let pair=a?.op==='create_regular_polygon'?['CREATE',a.shape.toUpperCase()]:mapping[a?.op];if(a?.op==='reflect_copy')pair=['REFLECT',a.axis==='x'?'X_AXIS':'Y_AXIS'];if(!r.valid||r.ambiguous||!pair||!labels.action.includes(pair[0])||!labels.subAction.includes(pair[1])){skipped.push({id:r.id,reason:'No independently supplied compatible primary execute label in the existing classifier heads.'});continue;}const objectType=pair[0]==='CREATE'?pair[1]==='FUNCTION'?'plot':pair[1].toLowerCase():'none';rows.push({id:r.id,phrase:r.userUtterance,split:r.split,labels:{action:pair[0],subAction:pair[1],mode:'graph2d',objectType:labels.objectType.includes(objectType)?objectType:'none'}});}
await tf.setBackend('cpu');await tf.ready();const model=await tf.loadLayersModel(tf.io.fromMemory({modelTopology:spec.modelTopology,weightSpecs:spec.weightsManifest[0].weights,weightData:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),userDefinedMetadata:spec.userDefinedMetadata}));
function measure(samples:Row[]){const predictions=samples.map(r=>({id:r.id,expected:r.labels,predicted:inferSemanticHeads(model,r.phrase,r.labels.mode as SemanticRow['mode'])}));return {total:samples.length,primaryAccuracy:predictions.filter(r=>r.predicted.action.label===r.expected.action&&r.predicted.subAction.label===r.expected.subAction).length/samples.length,headAccuracy:Object.fromEntries(HEADS.map(h=>[h,predictions.filter(r=>r.predicted[h].label===r.expected[h]).length/samples.length])),predictions};}

fs.writeFileSync(`${dir}/held-out-classifier.json`,JSON.stringify({scope:'Compatible primary classifier labels only; separate from end-to-end execution',heldOutUsedForFit:0,labels:measure(rows),skipped,checkpoint:'Original bundled weights retained after unsuccessful candidate training'},null,2));model.dispose();
