import fs from 'node:fs';
import crypto from 'node:crypto';
import * as tf from '@tensorflow/tfjs';
import {contextPages} from '../src/math-robo/intelligence/contextKnowledge';
import {buildContextDataset} from '../src/math-robo/intelligence/contextDataset';
import {trainContextModel,inferContext,CONTEXT_INTENTS,CONTEXT_MEANINGS,type ContextRow,type ContextIntent} from '../src/math-robo/intelligence/ruhiContextNet';

// Explicit trainer/dev entry point. Never writes public/, never promotes a model.
if(!process.argv.includes('--train-candidates'))throw new Error('Pass --train-candidates for the authorized isolated evaluation.');
const dir='reports/ruhi-v6-phase2',seed=20261009;
fs.mkdirSync(dir,{recursive:true});
const phrases:Record<ContextIntent,string[]>={
 explain:['Describe the idea presented here','Unpack the mathematics of this lesson','Help me interpret this subject','Discuss the central idea on this screen','Talk me through the topic on display','Describe the reasoning behind this lesson'],
 define:['Specify the meaning of this mathematical term','State exactly how this concept is defined','Supply a precise definition for the topic','Clarify the formal meaning of this idea','Identify the definition used by this lesson','Write down what this terminology denotes'],
 formula:['List the equation associated with this concept','Provide the algebraic rule for this topic','Express the current rule with symbols','Write the relation used in this lesson','State the relevant mathematical identity','Display the symbolic expression for this subject'],
 proof:['Derive a rigorous justification of this theorem','Establish why this mathematical claim holds','Supply a formal argument for this proposition','Demonstrate the validity of the theorem logically','Prove the claim discussed by the current lesson','Justify the statement with a complete argument'],
 example:['Illustrate this concept with one particular case','Work through a concrete instance of this topic','Supply a sample application of this idea','Demonstrate a worked case rather than a definition','Show a specific situation where this rule applies','Present one numerical illustration of this concept'],
 demonstrate:['Animate the concept currently on screen','Present this idea using a visual construction','Render a demonstration of the lesson','Demonstrate the topic with the visual tools','Display a visual model of the current rule','Illustrate the concept interactively on the canvas'],
 calculate:['Determine the numeric value of the current task','Compute the quantity in this problem','Obtain the numerical result for this task','Find the value requested by the current exercise','Evaluate the quantity under discussion','Work out the numeric outcome of this exercise'],
 compare:['Contrast these two mathematical approaches','Discuss the differences between the methods','Compare the two ideas in the current lesson','Identify how these methods differ mathematically','Distinguish the two concepts under discussion','Describe similarities and differences of the ideas'],
 why:['Explain the reason this property holds','Why does this mathematical rule work here','What makes the current result valid','Tell me why this conclusion follows','Why is this property preserved','Explain why the stated result is true'],
 simplify:['Restate this explanation in simpler terms','Use easier language for this mathematical idea','Make the concept easier to understand','Reduce the complexity of the explanation','Explain the topic as if I were a beginner','Use a less technical explanation of this subject'],
 simulation:['Read the state of the active simulation','Report what the simulation currently displays','Summarize the live simulation parameters','Inspect the current simulation values','Tell me the current simulated configuration','Describe the state of the interactive simulation'],
 selected:['Describe the object I have highlighted','Explain the currently selected construction','Identify the item selected on the canvas','Discuss the properties of my chosen object','Tell me about the highlighted mathematical object','Interpret the construction that I selected'],
 followup:['Continue explaining the idea we just discussed','Expand the previous explanation further','Develop the same topic a little further','Follow up on our current mathematical discussion','Add more detail to that explanation','Keep discussing the concept we were exploring'],
 practice:['Set an exercise about the current concept','Give me a task to practise this topic','Ask me a practice question on this subject','Prepare a short exercise for this lesson','Challenge me with a problem on this topic','Provide a question for practising the current idea'],
 hint:['Offer a clue without solving the exercise','Give me a small hint for the current problem','Suggest a first step without revealing the answer','Help me get started with a clue','Nudge me toward solving the current exercise','Supply a hint that leaves the solution to me'],
 previous:['Return to the subject from the preceding page','Recall the topic we studied before this one','Summarize the earlier mathematical concept','Revisit the topic that preceded the current lesson','Remind me about the concept on the previous page','Bring back the earlier topic in our discussion'],
 unrelated:['Compose a business email for my manager','Recommend a holiday hotel near the beach','Summarize celebrity gossip from this morning','Find me a good restaurant for dinner','Tell me which sports team won last night','Write a romantic poem for a birthday'],
};
const old=new Set(buildContextDataset().map(r=>r.question.toLowerCase().trim()));
type Row=ContextRow&{partition:'train'|'validation'|'calibration'|'holdout';provenance:string;family:string};
const pages=contextPages.filter(p=>p.definition&&p.vocabulary).slice(0,32),rows:Row[]=[];
for(const intent of CONTEXT_INTENTS)for(let family=0;family<6;family++)for(const polite of [false,true])for(const page of pages){
 const question=(polite?'Could you please ':'')+phrases[intent][family];if(old.has(question.toLowerCase().trim()))throw new Error('Exposed question overlap');
 const partition=family<3?'train':family===3?'validation':family===4?'calibration':'holdout',meaning=intent==='previous'?'previous':intent==='selected'?'selected':intent==='unrelated'?'unknown':'active';
 rows.push({question,intent,meaning,pageVocabulary:page.vocabulary,pageId:page.id,hasPrevious:['previous','followup'].includes(intent),previousVocabulary:['previous','followup'].includes(intent)?pages[(pages.indexOf(page)+1)%pages.length].vocabulary:undefined,selectedTypes:intent==='selected'?['triangle']:[],simulation:intent==='simulation'?{n:10,k:3}:undefined,group:`authored-family-${family}`,family:`authored-family-${family}`,partition,split:partition==='train'?'train':partition==='calibration'?'calibration':'test',provenance:'Controlled synthetic context-state corpus; authored intent utterances, existing reviewed page vocabulary; not human conversation data.'});
}
const key=(r:Row)=>JSON.stringify([r.question.toLowerCase(),r.pageVocabulary,r.previousVocabulary,r.hasPrevious,r.selectedTypes,r.simulation]);
const seen=new Set<string>();for(const row of rows){if(seen.has(key(row)))throw new Error('Duplicate context row');seen.add(key(row));}
const corpus=rows.map(r=>JSON.stringify(r)).join('\n')+'\n',sha=crypto.createHash('sha256').update(corpus).digest('hex');
fs.writeFileSync(`${dir}/candidate-corpus.jsonl`,corpus);
fs.writeFileSync(`${dir}/dataset-audit.json`,JSON.stringify({seed,rows:rows.length,sha256:sha,pages:pages.length,distinctAuthoredBaseUtterances:102,groups:6,partitions:Object.fromEntries(['train','validation','calibration','holdout'].map(p=>[p,rows.filter(r=>r.partition===p).length])),duplicates:0,exposedQuestionOverlap:0,groupLeakage:0,nearDuplicates:'Politeness variants stay in the same authored family and partition. Repeated utterances on different reviewed contexts are explicitly retained; they are not independent language examples.',meaningCoverage:['active','previous','selected','unknown'],excludedMeaningClasses:CONTEXT_MEANINGS.filter(m=>!rows.some(r=>r.meaning===m)),provenance:rows[0].provenance},null,2));
await tf.setBackend('cpu');await tf.ready();
const spec=JSON.parse(fs.readFileSync('public/models/ruhi-context-v1/model.json','utf8')),bytes=fs.readFileSync('public/models/ruhi-context-v1/weights.bin');
const baseline=await tf.loadLayersModel(tf.io.fromMemory({modelTopology:spec.modelTopology,weightSpecs:spec.weightsManifest[0].weights,weightData:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),userDefinedMetadata:spec.userDefinedMetadata}));
function evaluate(model:tf.LayersModel,data:Row[]){
 const predictions=data.map(r=>({expected:{intent:r.intent,meaning:r.meaning},prediction:inferContext(model,r)})),correct=predictions.filter(r=>r.expected.intent===r.prediction.intent&&r.expected.meaning===r.prediction.meaning),accepted=predictions.filter(r=>r.prediction.accepted),latencies=predictions.map(r=>r.prediction.inferenceMs).sort((a,b)=>a-b);
 const perClass=CONTEXT_INTENTS.map(label=>{const tp=predictions.filter(r=>r.expected.intent===label&&r.prediction.intent===label).length,actual=predictions.filter(r=>r.expected.intent===label).length,predicted=predictions.filter(r=>r.prediction.intent===label).length,precision=predicted?tp/predicted:0,recall=actual?tp/actual:0;return {label,support:actual,precision,recall,f1:precision+recall?2*precision*recall/(precision+recall):0};});
 let ece=0;const bins=[];for(let i=0;i<10;i++){const group=predictions.filter(r=>Math.min(9,Math.floor(Math.min(r.prediction.intentConfidence,r.prediction.meaningConfidence)*10))===i),accuracy=group.length?group.filter(r=>r.expected.intent===r.prediction.intent&&r.expected.meaning===r.prediction.meaning).length/group.length:0,confidence=group.length?group.reduce((s,r)=>s+Math.min(r.prediction.intentConfidence,r.prediction.meaningConfidence),0)/group.length:0;ece+=group.length/predictions.length*Math.abs(accuracy-confidence);bins.push({bin:i,count:group.length,accuracy,confidence});}
 return {total:data.length,jointCorrect:correct.length,jointAccuracy:correct.length/data.length,accepted:accepted.length,coverage:accepted.length/data.length,acceptedAccuracy:accepted.length?accepted.filter(r=>r.expected.intent===r.prediction.intent&&r.expected.meaning===r.prediction.meaning).length/accepted.length:null,perClass,ece,bins,parameters:model.countParams(),inferenceMs:{median:latencies[Math.floor(latencies.length/2)],p95:latencies[Math.floor(latencies.length*.95)]},tensorMemory:tf.memory()};
}
const validation=rows.filter(r=>r.partition==='validation'),holdout=rows.filter(r=>r.partition==='holdout'),baselineValidation=evaluate(baseline,validation),candidates=[];
for(const hidden of [32,64]){const start=performance.now(),model=await trainContextModel(rows.filter(r=>r.partition==='train'||r.partition==='calibration'),hidden,35);const metrics=evaluate(model,validation);candidates.push({hidden,model,metrics,trainingMs:performance.now()-start});console.log('candidate validation',hidden,metrics.jointAccuracy);}
candidates.sort((a,b)=>b.metrics.jointAccuracy-a.metrics.jointAccuracy||a.metrics.parameters-b.metrics.parameters);const chosen=candidates[0];
chosen.model.setUserDefinedMetadata({...chosen.model.getUserDefinedMetadata(),candidateId:`v6-phase2-context-${chosen.hidden}-seed-${seed}-${sha.slice(0,12)}`,datasetSha256:sha,training:{epochs:35,workflowSeed:seed,initializerSeeds:[73,79,80],shuffle:false},promotion:'candidate-only'});
// Selection is frozen using validation only, before touching holdout predictions.
const baselineHoldout=evaluate(baseline,holdout),candidateHoldout=evaluate(chosen.model,holdout);
let exportedBytes=0;await chosen.model.save(tf.io.withSaveHandler(async artifacts=>{const data=artifacts.weightData as ArrayBuffer;exportedBytes=data.byteLength;fs.writeFileSync(`${dir}/candidate-weights.bin`,Buffer.from(data));fs.writeFileSync(`${dir}/candidate-model.json`,JSON.stringify({modelTopology:artifacts.modelTopology,weightsManifest:[{paths:['candidate-weights.bin'],weights:artifacts.weightSpecs}],userDefinedMetadata:artifacts.userDefinedMetadata}));return {modelArtifactsInfo:{dateSaved:new Date(),modelTopologyType:'JSON',weightDataBytes:data.byteLength}};}));
const stress=['Pleese explane the current ideea','Move that circle','Draw a rectangle and then rotate it','Book a flight to Paris','Which angle do you mean?'].map(question=>({question,prediction:inferContext(chosen.model,{question,pageVocabulary:pages[0].vocabulary})}));
fs.writeFileSync(`${dir}/neural-evaluation.json`,JSON.stringify({seed,datasetSha256:sha,scope:'Controlled synthetic context classifier candidate, two existing prediction heads; no production promotion, no arbitrary-language accuracy claim.',backend:tf.getBackend(),epochs:35,baselineValidation,candidates:candidates.map(c=>({hidden:c.hidden,validation:c.metrics,trainingMs:c.trainingMs})),chosenHidden:chosen.hidden,selection:'Validation joint accuracy, tie break fewer parameters; holdout evaluated after selection.',baselineHoldout,candidateHoldout,exportedBytes,stress,promotion:'NOT PROMOTED; four meaning classes only, small family count, no human unseen evaluation.'},null,2));
baseline.dispose();for(const candidate of candidates){candidate.model.optimizer.dispose();candidate.model.dispose();}
fs.writeFileSync(`${dir}/neural-memory-final.json`,JSON.stringify(tf.memory(),null,2));
