import fs from 'node:fs';import crypto from 'node:crypto';import * as tf from '@tensorflow/tfjs';
import {inferContext,CONTEXT_INTENTS,CONTEXT_MEANINGS,type ContextIntent,type ContextMeaning} from '../src/math-robo/intelligence/ruhiContextNet';
import {inferSemanticHeads,HEAD_LABELS} from '../src/math-robo/intelligence/hierarchicalModel';
const root='reports/ruhi-v6-phase3';await tf.setBackend('cpu');await tf.ready();
const phrases:Record<ContextIntent,string>={explain:'Walk me through the mathematical idea on this page',define:'Give the formal definition of the topic shown here',formula:'Which equation expresses the rule on this screen',proof:'Provide a logical proof of the theorem on this page',example:'Give one worked numerical example of this topic',demonstrate:'Draw a visual demonstration of this concept',calculate:'Calculate the quantity requested in this lesson',compare:'Compare the two methods shown in this lesson',why:'Why is the result displayed here true',simplify:'Explain this concept using simpler words',simulation:'What are the current simulation values',selected:'Explain the highlighted geometric object',followup:'Add detail to the explanation we just discussed',practice:'Give me a practice problem for this concept',hint:'Offer a hint for the exercise I am solving',previous:'Explain the topic from the previous page',unrelated:'Recommend a hotel reservation for tomorrow'};
const vocab=['circle angle radians sine cosine','triangle median centroid geometry','derivative tangent slope calculus','equation polynomial algebra','sample probability random outcome','integer prime divisibility'];
const rows=CONTEXT_INTENTS.flatMap(intent=>vocab.flatMap((pageVocabulary,p)=>['',' please',' for this learner',' with care'].map(suffix=>({id:`${intent}:${p}:${suffix}`,question:phrases[intent]+suffix,pageVocabulary,previousVocabulary:'pigeonhole principle finite counting',hasPrevious:intent==='previous'||intent==='followup',selectedTypes:intent==='selected'?['circle']:[],intent,meaning:(intent==='unrelated'?'unknown':intent==='previous'?'previous':intent==='selected'?'selected':'active') as ContextMeaning}))));
fs.writeFileSync(root+'/neural-holdout.jsonl',rows.map(r=>JSON.stringify(r)).join('\n')+'\n');
async function load(file:string){const spec=JSON.parse(fs.readFileSync(file,'utf8')),bytes=fs.readFileSync(new URL(spec.weightsManifest[0].paths[0],new URL('file:///'+process.cwd().replaceAll('\\','/')+'/'+file)));return tf.loadLayersModel(tf.io.fromMemory({modelTopology:spec.modelTopology,weightSpecs:spec.weightsManifest[0].weights,weightData:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),userDefinedMetadata:spec.userDefinedMetadata}));}
function metrics(data:{actual:string;predicted:string;confidence:number;ms:number}[],labels:readonly string[]){const confusion=labels.map(a=>labels.map(p=>data.filter(r=>r.actual===a&&r.predicted===p).length));const perClass=labels.map((label,i)=>{const tp=confusion[i][i],support=confusion[i].reduce((a,b)=>a+b,0),predicted=confusion.reduce((s,r)=>s+r[i],0),precision=predicted?tp/predicted:0,recall=support?tp/support:0;return{label,support,precision,recall,f1:precision+recall?2*precision*recall/(precision+recall):0};});const bins=Array.from({length:10},(_,i)=>{const b=data.filter(r=>Math.min(9,Math.floor(r.confidence*10))===i);return{count:b.length,accuracy:b.length?b.filter(r=>r.actual===r.predicted).length/b.length:0,confidence:b.length?b.reduce((s,r)=>s+r.confidence,0)/b.length:0};});const times=data.map(r=>r.ms).sort((a,b)=>a-b);return{total:data.length,accuracy:data.filter(r=>r.actual===r.predicted).length/data.length,labels,confusion,perClass,macroF1:perClass.filter(r=>r.support).reduce((s,r)=>s+r.f1,0)/perClass.filter(r=>r.support).length,ece:bins.reduce((s,b)=>s+b.count/data.length*Math.abs(b.accuracy-b.confidence),0),bins,latencyMs:{median:times[Math.floor(times.length*.5)],p95:times[Math.floor(times.length*.95)]}};}
const report={backend:tf.getBackend(),scope:'New controlled synthetic phrases, 17 base intent families expanded across six vocabularies and polite suffixes. No fitting, threshold tuning or promotion. Not a human language benchmark.',context:[] as unknown[],primary:{} as unknown,before:tf.memory(),after:{} as unknown};
for(const file of ['public/models/ruhi-context-v1/model.json','reports/ruhi-v6-phase2/candidate-model.json']){const model=await load(file),predictions=rows.map(r=>({id:r.id,actual:r.intent,actualMeaning:r.meaning,...inferContext(model,r)}));report.context.push({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),parameters:model.countParams(),intent:metrics(predictions.map(p=>({actual:p.actual,predicted:p.intent,confidence:p.intentConfidence,ms:p.inferenceMs})),CONTEXT_INTENTS),meaning:metrics(predictions.map(p=>({actual:p.actualMeaning,predicted:p.meaning,confidence:p.meaningConfidence,ms:p.inferenceMs})),CONTEXT_MEANINGS),jointCorrect:predictions.filter(p=>p.intent===p.actual&&p.meaning===p.actualMeaning).length,accepted:predictions.filter(p=>p.accepted).length,acceptedCorrect:predictions.filter(p=>p.accepted&&p.intent===p.actual&&p.meaning===p.actualMeaning).length,predictions});model.dispose();}
const primary=await load('public/models/math-robo-intelligence-v4/model.json');const commands=[['CREATE','CIRCLE','Create a circle with radius'],['CREATE','RECTANGLE','Draw a rectangle width'],['MOVE','OBJECT','Move the selected circle right by'],['ROTATE','OBJECT','Rotate the selected square by'],['SCALE','UNIFORM','Scale the selected triangle by'],['FIND','AREA','Find the area of the selected circle'],['DELETE','OBJECT','Delete the selected circle']] as const;
const rawPredictions=commands.flatMap(([action,subAction,prefix])=>Array.from({length:20},(_,i)=>{const phrase=prefix+(action==='CREATE'?subAction==='CIRCLE'?` ${i+1}`:` ${i+1} height 6`:action==='MOVE'?` ${i+1}`:action==='ROTATE'?` ${i+1} degrees`:action==='SCALE'?` ${i+1}`:''),start=performance.now(),p=inferSemanticHeads(primary,phrase,'graph2d');return{phrase,actual:action,expectedSubAction:subAction,expectedObjectType:action==='CREATE'?subAction.toLowerCase():phrase.includes('square')?'square':phrase.includes('triangle')?'triangle':'circle',prediction:p,ms:performance.now()-start};}));
const predictions=[...new Map(rawPredictions.map(r=>[r.phrase,r])).values()];
report.primary={parameters:primary.countParams(),scope:'Action head on seven authored families; target context is named in text. Numeric substitutions are not independent wording families. Four heads on seven independently authored action/sub-action families; mode fixed graph2d. Broad language and mode coverage remains incomplete.',semanticExactMatch:predictions.filter(p=>p.prediction.action.label===p.actual&&p.prediction.subAction.label===p.expectedSubAction&&p.prediction.mode.label==='graph2d'&&p.prediction.objectType.label===p.expectedObjectType).length/predictions.length,mode:metrics(predictions.map(p=>({actual:'graph2d',predicted:p.prediction.mode.label,confidence:p.prediction.mode.score,ms:p.ms})),HEAD_LABELS.mode),objectType:metrics(predictions.map(p=>({actual:p.expectedObjectType,predicted:p.prediction.objectType.label,confidence:p.prediction.objectType.score,ms:p.ms})),HEAD_LABELS.objectType),subAction:metrics(predictions.map(p=>({actual:p.expectedSubAction,predicted:p.prediction.subAction.label,confidence:p.prediction.subAction.score,ms:p.ms})),HEAD_LABELS.subAction),action:metrics(predictions.map(p=>({actual:p.actual,predicted:p.prediction.action.label,confidence:p.prediction.action.score,ms:p.ms})),HEAD_LABELS.action),predictions};primary.dispose();report.after=tf.memory();fs.writeFileSync(root+'/neural-evaluation.json',JSON.stringify(report,null,2));console.log('CPU inference completed; no model training.');
