import { AlertTriangle, ArrowLeft, Check, Expand, Link2, Plus, RotateCcw, Share2, Target } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { LessonAdapterProps } from "../../types";
import "./CasToGraphTargetLesson449.css";
import "./CasToGraphTargetLesson449Practice.css";

type Series = { id: number; expression: string; color: string; dashed: boolean };
const initialSeries: Series[] = [
  { id: 1, expression: "2x + 4", color: "#1769ff", dashed: false },
  { id: 2, expression: "3x - 2", color: "#7c3cff", dashed: true },
  { id: 3, expression: "x^2 - 4", color: "#11b6b4", dashed: false },
];
const colors = ["#1769ff", "#7c3cff", "#11b6b4", "#e94168"];

export default function CasToGraphTargetLesson449({ resetToken, onInteraction }: LessonAdapterProps) {
  const [series, setSeries] = useState<Series[]>(initialSeries);
  const [practice, setPractice] = useState({ a: -2, b: 3 });
  const [feedback, setFeedback] = useState<"" | "correct" | "incorrect">("correct");
  const [pointer, setPointer] = useState({ x: 3, y: 2 });
  const [actions, setActions] = useState(0);
  const models = useMemo(() => series.map((item) => ({ ...item, model: parseExpression(item.expression) })), [series]);
  const reset = () => { setSeries(initialSeries); setPractice({ a: -2, b: 3 }); setFeedback("correct"); setPointer({ x: 3, y: 2 }); setActions(0); };
  useEffect(reset, [resetToken]);
  const act = (run: () => void) => { run(); setActions((value) => value + 1); onInteraction(); };
  const update = (id: number, change: Partial<Series>) => act(() => setSeries((items) => items.map((item) => item.id === id ? { ...item, ...change } : item)));
  return <section className="cg449-page" data-testid="symbolic-cas-mockup-0355" data-dedicated-lesson="449" data-object-model="parsed-symbolic-linear-quadratic-live-cartesian-series-style-practice" data-series={series.length} data-expressions={series.map((item) => item.expression).join("|")} data-practice-a={practice.a} data-practice-b={practice.b} data-feedback={feedback} data-actions={actions}>
    <header className="cg449-hero"><span><b>SYMBOLIC MATHEMATICS</b><b>CAS WORKSPACE</b></span><h1>CAS-to-Graph Link</h1><p>Connect symbolic and visual output.</p><div className="meta"><i>♙ Intermediate–Advanced</i><i>⚡ CAS Lab</i><i>▣ CAS Calculator</i><i>◷ 6–10 min</i></div><div className="actions"><button data-lesson-control="language">⚒ English (English)⌄</button><button data-lesson-control="reset" onClick={() => act(reset)}><RotateCcw />Reset</button><button data-lesson-control="share" onClick={() => act(() => navigator.clipboard?.writeText(series.map((item) => item.expression).join(", ")))}><Share2 />Share</button><a href="/workspace/data/cas">↗ Workspace</a></div></header>
    <section className="cg449-flow"><h3>How this<br/>works</h3>{[["◉","OBSERVE","Read the expression and see the graph."],["☝","MANIPULATE","Change parameters in the CAS panel."],["♧","NOTICE","Watch the graph update instantly."],["♢","UNDERSTAND","Connect the rule to the visual changes."]].map(([icon,title,copy],index)=><article key={title}><b>{icon}</b><div><strong>{title}</strong><p>{copy}</p></div>{index<3&&<span>⟶</span>}</article>)}</section>
    <section className="cg449-workspace"><header><div><h2>CAS Workspace</h2><p>Expressions and parameters</p></div><div><h2>Graph Output</h2><p>Axes: Cartesian</p></div><span>● Live linkage: ON</span><button data-lesson-control="fullscreen" onClick={() => act(() => document.documentElement.requestFullscreen?.())}><Expand /></button></header><div className="cg449-body"><div className="cg449-cas">
      {models.map((item,index)=><article key={item.id} style={{borderLeftColor:item.color}}><div><b>{String.fromCharCode(102+index)}(x)</b><input aria-label={`Expression ${index+1}`} data-lesson-control={`expression-${index+1}`} value={item.expression} onChange={(event)=>update(item.id,{expression:event.target.value})}/><button data-lesson-control={`remove-${index+1}`} onClick={()=>act(()=>setSeries((items)=>items.filter((entry)=>entry.id!==item.id)))}>×</button></div><footer><label>Color <button aria-label={`Color ${index+1}`} data-lesson-control={`color-${index+1}`} style={{background:item.color}} onClick={()=>update(item.id,{color:colors[(colors.indexOf(item.color)+1)%colors.length]})}/></label><label>Line style <button data-lesson-control={`style-${index+1}`} onClick={()=>update(item.id,{dashed:!item.dashed})}><i style={{borderTopStyle:item.dashed?"dashed":"solid",borderColor:item.color}}/>⌄</button></label></footer>{!item.model&&<small>Use ax + b or ax² + b</small>}</article>)}
      <button className="add" data-lesson-control="add-expression" disabled={series.length>=4} onClick={()=>act(()=>setSeries((items)=>[...items,{id:Math.max(0,...items.map((item)=>item.id))+1,expression:"-x + 1",color:colors[items.length%colors.length],dashed:false}]))}><Plus />Add expression</button>
    </div><div className="cg449-graph"><Graph models={models} setPointer={(point)=>setPointer(point)}/><div className="legend">{models.map((item,index)=><span key={item.id}><i style={{borderColor:item.color,borderTopStyle:item.dashed?"dashed":"solid"}}/>{String.fromCharCode(102+index)}(x) = {item.expression}</span>)}</div><output>x: {pointer.x.toFixed(2)} / y: {pointer.y.toFixed(2)}</output></div></div></section>
    <section className="cg449-learning"><article><Link2 /><div><h3>Rule / Connection</h3><p>This engine links a symbolic expression to its graph.</p><p>For y = ax + b:</p><ul><li><b>Slope = a</b> (rate of change)</li><li><b>y-intercept = b</b> (point (0, b))</li></ul><p>For y = x² + k: vertex = (0, k) and axis of symmetry is x = 0.</p></div></article><article><Check /><div><h3>Worked Example</h3><p><b>Example:</b> y = 2x + 4</p><ul><li>Slope a = 2 → line rises 2 units for every 1 unit right.</li><li>y-intercept b = 4 → crosses the y-axis at (0, 4).</li></ul><p>Check on graph: the blue line passes through (0, 4) and (2, 8).</p></div></article><article className="mis"><AlertTriangle /><div><h3>Common Misconception</h3><p><b>Changing only one number changes only one thing.</b></p><p>Not always! In y = ax + b, changing a rotates the line, which also changes where it crosses the axes.</p></div></article></section>
    <section className="cg449-practice"><header><h3>Quick Practice</h3><p>Adjust the parameters to match the target statement.</p></header><div className="target"><Target /><p><b>Target</b><br/>Line with slope = −2<br/>and y-intercept = 3<br/>(i.e., y = −2x + 3)</p></div><div className="practice-controls"><label>Expression<output>y = ax + b</output></label><Stepper label="a (slope)" value={practice.a} set={(a)=>{setPractice({...practice,a});setFeedback("");}}/><Stepper label="b (y-intercept)" value={practice.b} set={(b)=>{setPractice({...practice,b});setFeedback("");}}/><button data-lesson-control="practice-check" onClick={()=>act(()=>setFeedback(practice.a===-2&&practice.b===3?"correct":"incorrect"))}>Check</button></div><div className={`result ${feedback}`}><h3>{feedback==="correct"?"✓ Correct!":feedback==="incorrect"?"Try again":"Result"}</h3><p>{feedback==="correct"?"Your line matches the target. It crosses the y-axis at (0, 3) and falls 2 units for every 1 unit right.":"Set the slope and intercept, then check."}</p></div><MiniGraph a={practice.a} b={practice.b}/></section>
    <nav className="cg449-nav"><a href="/lessons/symbolic-mathematics/448-step-by-step-algebra"><ArrowLeft/><span><small>Previous</small>Step-by-Step Algebra</span></a><a href="/lessons/symbolic-mathematics/450-next-symbolic-step"><span><small>Next</small>Next symbolic step</span>→</a></nav>
  </section>;
}

function Stepper({label,value,set}:{label:string;value:number;set:(value:number)=>void}){return <label>{label}<span><button data-lesson-control={`${label}-minus`} onClick={()=>set(value-1)}>−</button><output>{value}</output><button data-lesson-control={`${label}-plus`} onClick={()=>set(value+1)}>+</button></span></label>}
type Model={kind:"linear"|"quadratic";a:number;b:number;value:(x:number)=>number};
function parseExpression(raw:string):Model|null{const text=raw.toLowerCase().replace(/\s/g,"").replace(/²/g,"^2").replace(/−/g,"-");const quad=text.match(/^([+-]?(?:\d*\.?\d+)?)x\^2([+-]\d*\.?\d+)?$/);if(quad){const a=coefficient(quad[1]),b=Number(quad[2]||0);return Number.isFinite(a)&&Number.isFinite(b)?{kind:"quadratic",a,b,value:(x)=>a*x*x+b}:null}const linear=text.match(/^([+-]?(?:\d*\.?\d+)?)x([+-]\d*\.?\d+)?$/);if(linear){const a=coefficient(linear[1]),b=Number(linear[2]||0);return Number.isFinite(a)&&Number.isFinite(b)?{kind:"linear",a,b,value:(x)=>a*x+b}:null}return null}function coefficient(value:string){return value===""||value==="+"?1:value==="-"?-1:Number(value)}
function Graph({models,setPointer}:{models:Array<Series&{model:Model|null}>;setPointer:(point:{x:number;y:number})=>void}){const size=420,to=(value:number)=>size/2+value*(size/20),path=(model:Model)=>Array.from({length:201},(_,i)=>{const x=-10+i/10,y=model.value(x);return `${i?"L":"M"}${to(x)} ${to(-y)}`}).join(" ");return <svg viewBox={`0 0 ${size} ${size}`} role="img" aria-label="Live Cartesian graph" onPointerMove={(event)=>{const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*20-10,y=10-(event.clientY-rect.top)/rect.height*20;setPointer({x,y})}}>{Array.from({length:21},(_,i)=><g key={i}><line className="grid" x1={to(i-10)} y1="0" x2={to(i-10)} y2={size}/><line className="grid" x1="0" y1={to(i-10)} x2={size} y2={to(i-10)}/></g>)}<line className="axis" x1="0" y1={size/2} x2={size} y2={size/2}/><line className="axis" x1={size/2} y1="0" x2={size/2} y2={size}/>{models.map((item)=>(item.model&&<g key={item.id}><path d={path(item.model)} fill="none" stroke={item.color} strokeWidth="2" strokeDasharray={item.dashed?"7 5":undefined}/><circle cx={to(0)} cy={to(-item.model.b)} r="4" fill={item.color}/></g>))}<text x="405" y="204">x</text><text x="215" y="12">y</text></svg>}
function MiniGraph({a,b}:{a:number;b:number}){const to=(value:number)=>55+value*10;return <svg className="mini" viewBox="0 0 110 110"><line x1="0" y1="55" x2="110" y2="55"/><line x1="55" y1="0" x2="55" y2="110"/><line x1={to(-5)} y1={to(-(a*-5+b))} x2={to(5)} y2={to(-(a*5+b))} stroke="#8a2be2" strokeWidth="2"/><circle cx="55" cy={to(-b)} r="3" fill="#8a2be2"/></svg>}
