import { useEffect, useMemo, useState } from "react";
import { applyOperator, buildTruthTable, type LogicOperator } from "../../../mathematical-logic/logicEngine";
import { chromaticNumber, graphColorConflicts, sampleGraph } from "../../../graph-theory/graphTheoryEngine";
import { createLessonInteractionEvent } from "../../engine/lessonInteraction";
import { classifyTruthResults, computeSetBuilder, computeSetOperation, parseFiniteNumberList, powerSet, satisfiesSetPredicate, setPredicateLabel, type SetOperationId, type SetPredicateId } from "../../engine/p0LessonModels";
import type { LessonAdapterProps, LessonControlKind } from "../../types";

type ActivityProps = Pick<LessonAdapterProps, "resetToken" | "onInteraction">;

export function SetBuilderActivity({ resetToken, onInteraction }: ActivityProps) {
  const [universeText, setUniverseText] = useState("-5,-4,-3,-2,-1,0,1,2,3,4,5");
  const [predicate, setPredicate] = useState<SetPredicateId>("even");
  const [notation, setNotation] = useState<"roster" | "builder">("builder");
  const [membership, setMembership] = useState(2);
  useEffect(() => { setUniverseText("-5,-4,-3,-2,-1,0,1,2,3,4,5"); setPredicate("even"); setNotation("builder"); setMembership(2); }, [resetToken]);
  const parsed = useMemo(() => parseFiniteNumberList(universeText), [universeText]);
  const computed = useMemo(() => computeSetBuilder(parsed.values, predicate), [parsed.values, predicate]);
  const membershipResult = parsed.values.includes(membership) && satisfiesSetPredicate(membership, predicate);
  const emit = (controlId: string, kind: LessonControlKind, before: unknown, after: unknown) => onInteraction(createLessonInteractionEvent({ controlId, kind, before, after, affectedOutputs: ["computed-set", "membership-result"] }));
  const state = { computedCount: computed.length, members: computed, predicate, membership, membershipResult };
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]">
    <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900">
      <div className="flex min-h-48 flex-wrap content-center justify-center gap-2" role="img" aria-label={`Universe ${parsed.values.join(", ")}. Set contains ${computed.join(", ") || "no values"}.`}>
        {parsed.values.map((value) => <span key={value} className={computed.includes(value) ? "grid h-12 w-12 place-items-center rounded-full border-2 border-cyan-700 bg-cyan-100 font-mono font-black text-cyan-900" : "grid h-12 w-12 place-items-center rounded-full border-2 border-dashed border-slate-300 font-mono text-slate-500"}>{value}</span>)}
      </div>
      <output className="mt-3 block rounded-xl bg-white p-3 text-center font-mono text-sm font-black dark:bg-white/10">{notation === "roster" ? `A = {${computed.join(", ")}}` : `A = {x ∈ U | ${setPredicateLabel(predicate)}}`}</output>
    </div>
    <div className="space-y-3">
      <Field label="Finite universe"><input data-lesson-control="set-rule" value={universeText} onChange={(event) => { const before = state; const next = event.target.value; setUniverseText(next); const values = parseFiniteNumberList(next).values; emit("set-rule", "input", before, { ...state, computedCount: computeSetBuilder(values, predicate).length }); }} className="lesson-input" aria-label="Finite universe" /></Field>
      <Field label="Predicate"><select data-lesson-control="set-rule" value={predicate} onChange={(event) => { const next = event.target.value as SetPredicateId; const before = state; setPredicate(next); emit("set-rule", "selection", before, { ...state, predicate: next, computedCount: computeSetBuilder(parsed.values, next).length }); }} className="lesson-input" aria-label="Set-builder predicate"><option value="even">x is even</option><option value="positive">x &gt; 0</option><option value="greater-than-two">x &gt; 2</option><option value="multiple-of-three">x is a multiple of 3</option></select></Field>
      <div className="grid grid-cols-2 gap-2" aria-label="Notation"><Choice active={notation === "builder"} onClick={() => { setNotation("builder"); emit("set-rule", "toggle", notation, { ...state, notation: "builder" }); }}>Set-builder</Choice><Choice active={notation === "roster"} onClick={() => { setNotation("roster"); emit("set-rule", "toggle", notation, { ...state, notation: "roster" }); }}>Roster</Choice></div>
      <Field label="Test membership"><input data-lesson-control="set-membership" type="number" value={membership} onChange={(event) => { const next = Number(event.target.value); setMembership(next); emit("set-membership", "input", membership, { ...state, membership: next, membershipResult: parsed.values.includes(next) && satisfiesSetPredicate(next, predicate) }); }} className="lesson-input" aria-label="Membership test value" /></Field>
      <p className={membershipResult ? "status-good" : "status-neutral"}>{membership} {membershipResult ? "∈" : "∉"} A</p>
      {parsed.error ? <p className="text-xs font-bold text-amber-700">{parsed.error}</p> : null}
    </div>
  </div>;
}

export function SetOperationsActivity({ resetToken, onInteraction }: ActivityProps) {
  const [aText, setAText] = useState("1,2,3,5"); const [bText, setBText] = useState("3,4,5,6"); const [operation, setOperation] = useState<SetOperationId>("union");
  useEffect(() => { setAText("1,2,3,5"); setBText("3,4,5,6"); setOperation("union"); }, [resetToken]);
  const a = useMemo(() => parseFiniteNumberList(aText, 10).values, [aText]); const b = useMemo(() => parseFiniteNumberList(bText, 10).values, [bText]);
  const result = useMemo(() => computeSetOperation(a, b, operation), [a, b, operation]);
  const emit = (before: unknown, after: unknown) => onInteraction(createLessonInteractionEvent({ controlId: "set-operation", kind: "selection", before, after, affectedOutputs: ["set-result", "set-cardinality"] }));
  const symbol: Record<SetOperationId, string> = { union: "A ∪ B", intersection: "A ∩ B", "a-minus-b": "A \\ B", "b-minus-a": "B \\ A", "symmetric-difference": "A △ B" };
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]">
    <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><svg viewBox="0 0 560 300" className="h-[260px] w-full" role="img" aria-label={`${symbol[operation]} equals ${result.join(", ") || "empty set"}`}><circle cx="225" cy="145" r="105" fill="#06b6d4" opacity={operation === "union" || operation === "a-minus-b" || operation === "symmetric-difference" ? .35 : .15} stroke="#0891b2" strokeWidth="4"/><circle cx="335" cy="145" r="105" fill="#f59e0b" opacity={operation === "union" || operation === "b-minus-a" || operation === "symmetric-difference" ? .35 : .15} stroke="#b45309" strokeWidth="4"/><ellipse cx="280" cy="145" rx="50" ry="92" fill={operation === "intersection" || operation === "union" ? "#8b5cf6" : "#f8fafc"} opacity=".55"/><text x="165" y="55" fontWeight="900">A</text><text x="385" y="55" fontWeight="900">B</text><text x="280" y="285" textAnchor="middle" fontWeight="900">{symbol[operation]} = {`{${result.join(", ")}}`}</text></svg></div>
    <div className="space-y-3"><Field label="Set A"><input value={aText} onChange={(event) => { const next = event.target.value; setAText(next); emit({ a, b, operation }, { resultCount: computeSetOperation(parseFiniteNumberList(next).values, b, operation).length }); }} className="lesson-input" aria-label="Set A values" /></Field><Field label="Set B"><input value={bText} onChange={(event) => { const next = event.target.value; setBText(next); emit({ a, b, operation }, { resultCount: computeSetOperation(a, parseFiniteNumberList(next).values, operation).length }); }} className="lesson-input" aria-label="Set B values" /></Field><Field label="Operation"><select data-lesson-control="set-operation" value={operation} onChange={(event) => { const next = event.target.value as SetOperationId; setOperation(next); emit(operation, { operation: next, resultCount: computeSetOperation(a, b, next).length }); }} className="lesson-input" aria-label="Set operation"><option value="union">Union A ∪ B</option><option value="intersection">Intersection A ∩ B</option><option value="a-minus-b">Difference A \\ B</option><option value="b-minus-a">Difference B \\ A</option><option value="symmetric-difference">Symmetric difference</option></select></Field><p className="status-good">|{symbol[operation]}| = {result.length}</p></div>
  </div>;
}

export function PowerSetActivity({ resetToken, onInteraction }: ActivityProps) {
  const values = [1, 2, 3, 4]; const [source, setSource] = useState([1, 2, 3]); const [candidate, setCandidate] = useState([1]);
  useEffect(() => { setSource([1, 2, 3]); setCandidate([1]); }, [resetToken]);
  const subsets = useMemo(() => powerSet(source), [source]); const isSubset = candidate.every((value) => source.includes(value)); const proper = isSubset && candidate.length < source.length;
  const emit = (controlId: string, before: unknown, nextSource: number[], nextCandidate: number[]) => { const nextIsSubset = nextCandidate.every((value) => nextSource.includes(value)); onInteraction(createLessonInteractionEvent({ controlId, kind: "toggle", before, after: { sourceSize: nextSource.length, powerCount: 2 ** nextSource.length, isSubset: nextIsSubset, proper: nextIsSubset && nextCandidate.length < nextSource.length }, affectedOutputs: ["power-set", "power-cardinality", "subset-status"] })); };
  const toggle = (list: number[], value: number) => list.includes(value) ? list.filter((item) => item !== value) : [...list, value].sort();
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-xs font-black uppercase text-slate-500">P({`{${source.join(",")}}`})</p><div className="mt-3 grid max-h-72 grid-cols-2 gap-2 overflow-y-auto sm:grid-cols-3">{subsets.map((subset) => <span key={subset.join("-")} className="rounded-lg bg-white p-2 text-center font-mono text-xs shadow-sm dark:bg-white/10">{`{${subset.join(", ")}}`}</span>)}</div></div><div className="space-y-3"><ToggleSet label="Source set" values={values} selected={source} controlId="power-source" onToggle={(value) => { const next = toggle(source, value); setSource(next); emit("power-source", source, next, candidate); }} /><ToggleSet label="Candidate subset" values={values} selected={candidate} controlId="power-candidate" onToggle={(value) => { const next = toggle(candidate, value); setCandidate(next); emit("power-candidate", candidate, source, next); }} /><p className="status-good">2^{source.length} = {subsets.length} subsets</p><p className={isSubset ? "status-good" : "status-neutral"}>{`{${candidate.join(",")}}`} is {proper ? "a proper subset" : isSubset ? "a subset" : "not a subset"} of {`{${source.join(",")}}`}.</p></div></div>;
}

export function TruthTableActivity({ resetToken, onInteraction }: ActivityProps) {
  const [expression, setExpression] = useState("p -> q"); const [highlight, setHighlight] = useState(0);
  useEffect(() => { setExpression("p -> q"); setHighlight(0); }, [resetToken]);
  const result = useMemo(() => { try { return { table: buildTruthTable(expression), error: "" }; } catch (error) { return { table: null, error: error instanceof Error ? error.message : "Invalid proposition." }; } }, [expression]);
  const classification = result.table ? classifyTruthResults(result.table.rows.map((row) => row.result)) : "contingency";
  const emit = (controlId: string, kind: LessonControlKind, before: unknown, after: unknown) => onInteraction(createLessonInteractionEvent({ controlId, kind, before, after, affectedOutputs: ["truth-table", "truth-classification"] }));
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-white/10">{result.table ? <table className="w-full text-center text-sm"><thead><tr>{[...result.table.variables, "result"].map((value) => <th key={value} className="bg-slate-100 p-2 font-black dark:bg-white/10">{value}</th>)}</tr></thead><tbody>{result.table.rows.map((row, index) => <tr key={index} tabIndex={0} onClick={() => { setHighlight(index); emit("truth-row", "selection", highlight, { classification, row: index }); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { setHighlight(index); emit("truth-row", "keyboard", highlight, { classification, row: index }); } }} className={index === highlight ? "border-t border-cyan-400 bg-cyan-50 dark:bg-cyan-400/10" : "border-t border-slate-200 dark:border-white/10"}>{result.table.variables.map((variable) => <td key={variable} className="p-2">{row.values[variable] ? "T" : "F"}</td>)}<td className="p-2 font-black">{row.result ? "T" : "F"}</td></tr>)}</tbody></table> : <p className="p-4 text-sm font-bold text-amber-700">{result.error}</p>}</div><div className="space-y-3"><Field label="Proposition"><input data-lesson-control="truth-expression" value={expression} onChange={(event) => { const next = event.target.value; setExpression(next); setHighlight(0); let nextClass = "invalid"; try { nextClass = classifyTruthResults(buildTruthTable(next).rows.map((row) => row.result)); } catch { /* visible parser error */ } emit("truth-expression", "input", expression, { classification: nextClass }); }} className="lesson-input" aria-label="Logical proposition" /></Field><div className="grid grid-cols-2 gap-2"><Choice onClick={() => { setExpression("p & q"); emit("truth-expression", "selection", expression, { classification: "contingency" }); }}>p AND q</Choice><Choice onClick={() => { setExpression("p | !p"); emit("truth-expression", "selection", expression, { classification: "tautology" }); }}>Tautology</Choice></div><p className="status-good">{classification}</p><p className="text-xs text-slate-500">Grammar: !, &amp;, |, xor, →, ↔ and parentheses.</p></div></div>;
}

type ConnectiveId = "not" | Exclude<LogicOperator, "not">;
export function LogicalConnectivesActivity({ resetToken, onInteraction }: ActivityProps) {
  const [p, setP] = useState(true); const [q, setQ] = useState(false); const [operator, setOperator] = useState<ConnectiveId>("and");
  useEffect(() => { setP(true); setQ(false); setOperator("and"); }, [resetToken]);
  const value = operator === "not" ? !p : applyOperator(operator, p, q); const symbol: Record<ConnectiveId, string> = { not: "¬p", and: "p ∧ q", or: "p ∨ q", xor: "p ⊕ q", nand: "p ↑ q", nor: "p ↓ q", implies: "p → q", iff: "p ↔ q" };
  const emit = (controlId: string, before: unknown, after: unknown) => onInteraction(createLessonInteractionEvent({ controlId, kind: "toggle", before, after, affectedOutputs: ["connective-result", "connective-row"] }));
  const nextResult = (nextP: boolean, nextQ: boolean, nextOperator: ConnectiveId) => nextOperator === "not" ? !nextP : applyOperator(nextOperator, nextP, nextQ);
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="grid min-h-64 place-items-center rounded-xl bg-slate-950 p-5 text-white"><div className="text-center"><p className="font-mono text-3xl font-black">{symbol[operator]}</p><p className={value ? "mt-5 text-5xl font-black text-emerald-300" : "mt-5 text-5xl font-black text-amber-300"}>{value ? "TRUE" : "FALSE"}</p><p className="mt-3 text-sm">With p={String(p)}{operator === "not" ? "" : ` and q=${String(q)}`}, the statement is {String(value)}.</p></div></div><div className="space-y-3"><div className="grid grid-cols-2 gap-2"><Choice active={p} onClick={() => { const next = !p; setP(next); emit("connective-values", p, { result: String(nextResult(next, q, operator)), p: next, q, operator }); }}>p = {String(p)}</Choice><Choice active={q} disabled={operator === "not"} onClick={() => { const next = !q; setQ(next); emit("connective-values", q, { result: String(nextResult(p, next, operator)), p, q: next, operator }); }}>q = {String(q)}</Choice></div><Field label="Connective"><select data-lesson-control="connective-kind" value={operator} onChange={(event) => { const next = event.target.value as ConnectiveId; setOperator(next); emit("connective-kind", operator, { result: String(nextResult(p, q, next)), p, q, operator: next }); }} className="lesson-input" aria-label="Logical connective"><option value="not">NOT</option><option value="and">AND</option><option value="or">OR</option><option value="xor">XOR</option><option value="implies">Implication</option><option value="iff">Biconditional</option></select></Field><p className="status-good">Highlighted row: p={p ? "T" : "F"}, q={q ? "T" : "F"} → {value ? "T" : "F"}</p></div></div>;
}

export function QuantifiersActivity({ resetToken, onInteraction }: ActivityProps) {
  const [domainText, setDomainText] = useState("-2,-1,0,1,2,3"); const [predicate, setPredicate] = useState<SetPredicateId>("positive"); const [quantifier, setQuantifier] = useState<"forall" | "exists">("exists");
  useEffect(() => { setDomainText("-2,-1,0,1,2,3"); setPredicate("positive"); setQuantifier("exists"); }, [resetToken]);
  const domain = useMemo(() => parseFiniteNumberList(domainText, 12).values, [domainText]); const mapped = domain.map((value) => ({ value, holds: satisfiesSetPredicate(value, predicate) }));
  const result = quantifier === "forall" ? mapped.every((item) => item.holds) : mapped.some((item) => item.holds); const evidenceItem = quantifier === "forall" ? mapped.find((item) => !item.holds) : mapped.find((item) => item.holds);
  const emit = (controlId: string, kind: LessonControlKind, before: unknown, after: unknown) => onInteraction(createLessonInteractionEvent({ controlId, kind, before, after, affectedOutputs: ["quantifier-evaluation", "quantifier-evidence"] }));
  const state = { quantifier, predicate, result, evidence: String(evidenceItem?.value ?? "none") };
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><p className="text-center font-mono text-lg font-black">{quantifier === "forall" ? "∀" : "∃"} x ∈ D: {setPredicateLabel(predicate)}</p><div className="mt-5 flex flex-wrap justify-center gap-2">{mapped.map((item) => <span key={item.value} className={item === evidenceItem ? "rounded-xl border-2 border-amber-500 bg-amber-100 px-3 py-2 font-mono font-black text-amber-900" : item.holds ? "rounded-xl bg-emerald-100 px-3 py-2 font-mono text-emerald-900" : "rounded-xl bg-slate-200 px-3 py-2 font-mono text-slate-600"}>{item.value}: {item.holds ? "T" : "F"}</span>)}</div><p className={result ? "status-good mt-4" : "status-neutral mt-4"}>{result ? "TRUE" : "FALSE"} · {quantifier === "forall" ? "counterexample" : "witness"}: {evidenceItem?.value ?? "none"}</p></div><div className="space-y-3"><Field label="Finite domain"><input data-lesson-control="quantifier-domain" value={domainText} onChange={(event) => { const next = event.target.value; setDomainText(next); const nextDomain = parseFiniteNumberList(next).values; const values = nextDomain.map((value) => ({ value, holds: satisfiesSetPredicate(value, predicate) })); const evidence = quantifier === "forall" ? values.find((item) => !item.holds) : values.find((item) => item.holds); emit("quantifier-domain", "input", state, { evidence: String(evidence?.value ?? "none") }); }} className="lesson-input" aria-label="Quantifier finite domain" /></Field><Field label="Quantifier"><select data-lesson-control="quantifier-kind" value={quantifier} onChange={(event) => { const next = event.target.value as "forall" | "exists"; setQuantifier(next); const evidence = next === "forall" ? mapped.find((item) => !item.holds) : mapped.find((item) => item.holds); emit("quantifier-kind", "selection", state, { evidence: String(evidence?.value ?? "none"), quantifier: next }); }} className="lesson-input" aria-label="Quantifier"><option value="forall">∀ for all</option><option value="exists">∃ there exists</option></select></Field><Field label="Predicate"><select value={predicate} onChange={(event) => { const next = event.target.value as SetPredicateId; setPredicate(next); const nextMapped = domain.map((value) => ({ value, holds: satisfiesSetPredicate(value, next) })); const evidence = quantifier === "forall" ? nextMapped.find((item) => !item.holds) : nextMapped.find((item) => item.holds); emit("quantifier-kind", "selection", state, { evidence: String(evidence?.value ?? "none"), predicate: next }); }} className="lesson-input" aria-label="Quantifier predicate"><option value="positive">x &gt; 0</option><option value="even">x is even</option><option value="greater-than-two">x &gt; 2</option><option value="multiple-of-three">x is a multiple of 3</option></select></Field></div></div>;
}

export function GraphColouringActivity({ resetToken, onInteraction }: ActivityProps) {
  const palette = ["#06b6d4", "#f59e0b", "#8b5cf6", "#10b981"]; const [selected, setSelected] = useState(0); const [assignment, setAssignment] = useState<Record<string, number>>({});
  useEffect(() => { setSelected(0); setAssignment({}); }, [resetToken]);
  const conflicts = graphColorConflicts(sampleGraph, assignment); const target = chromaticNumber(sampleGraph).colors; const used = new Set(Object.values(assignment)).size; const complete = Object.keys(assignment).length === sampleGraph.nodes.length; const valid = complete && conflicts.length === 0;
  const colorVertex = (nodeId: string) => { const before = assignment; const next = { ...assignment, [nodeId]: selected }; setAssignment(next); const nextConflicts = graphColorConflicts(sampleGraph, next); onInteraction(createLessonInteractionEvent({ controlId: "graph-colour-vertex", kind: "selection", before, after: { assignment: next, conflictCount: nextConflicts.length, valid: Object.keys(next).length === sampleGraph.nodes.length && nextConflicts.length === 0, colorCount: new Set(Object.values(next)).size }, affectedOutputs: ["colour-conflicts", "colour-count", "valid-colouring"] })); };
  return <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="rounded-xl bg-slate-950 p-3"><svg viewBox="0 0 460 300" className="h-[280px] w-full" role="img" aria-label={`${Object.keys(assignment).length} of ${sampleGraph.nodes.length} vertices colored, ${conflicts.length} conflicts.`}>{sampleGraph.edges.map((edge) => { const a = sampleGraph.nodes.find((node) => node.id === edge.source)!; const b = sampleGraph.nodes.find((node) => node.id === edge.target)!; return <line key={edge.id} x1={a.x + 20} y1={a.y + 10} x2={b.x + 20} y2={b.y + 10} stroke={conflicts.includes(edge.id) ? "#ef4444" : "#64748b"} strokeWidth={conflicts.includes(edge.id) ? 7 : 3} strokeDasharray={conflicts.includes(edge.id) ? "8 5" : undefined}/>; })}{sampleGraph.nodes.map((node) => <g key={node.id} role="button" tabIndex={0} aria-label={`Color vertex ${node.label}`} onClick={() => colorVertex(node.id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") colorVertex(node.id); }} className="cursor-pointer outline-none focus-visible:[filter:drop-shadow(0_0_6px_#fbbf24)]"><circle cx={node.x + 20} cy={node.y + 10} r="23" fill={assignment[node.id] === undefined ? "#334155" : palette[assignment[node.id]]} stroke="white" strokeWidth="3"/><text x={node.x + 20} y={node.y + 15} textAnchor="middle" fill="white" fontWeight="900">{node.label}</text></g>)}</svg></div><div className="space-y-3"><p className="text-xs font-black uppercase text-slate-500">Palette</p><div className="grid grid-cols-4 gap-2">{palette.map((color, index) => <button key={color} type="button" aria-label={`Select color ${index + 1}`} onClick={() => setSelected(index)} className={selected === index ? "h-11 rounded-xl ring-4 ring-amber-400" : "h-11 rounded-xl"} style={{ background: color }}/>)}</div><button type="button" className="action-secondary w-full justify-center" onClick={() => { setAssignment(chromaticNumber(sampleGraph).assignment); onInteraction(createLessonInteractionEvent({ controlId: "graph-colour-vertex", kind: "playback", before: assignment, after: { conflictCount: 0, valid: true, colorCount: target }, affectedOutputs: ["colour-conflicts", "colour-count", "valid-colouring"] })); }}>Greedy hint</button><p className={valid ? "status-good" : conflicts.length ? "status-bad" : "status-neutral"}>{valid ? `Valid with ${used} colors` : `${conflicts.length} conflict${conflicts.length === 1 ? "" : "s"}`} · target {target}</p></div></div>;
}

function ToggleSet({ label, values, selected, controlId, onToggle }: { label: string; values: number[]; selected: number[]; controlId: string; onToggle: (value: number) => void }) { return <fieldset><legend className="text-xs font-black text-slate-500">{label}</legend><div className="mt-2 grid grid-cols-4 gap-2">{values.map((value) => <button data-lesson-control={controlId} key={value} type="button" aria-pressed={selected.includes(value)} onClick={() => onToggle(value)} className={selected.includes(value) ? "min-h-11 rounded-xl bg-cyan-500 font-black text-white" : "min-h-11 rounded-xl bg-slate-100 font-black dark:bg-white/10"}>{value}</button>)}</div></fieldset>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="text-xs font-black text-slate-500">{label}</span><span className="mt-1 block">{children}</span></label>; }
function Choice({ active = false, disabled = false, onClick, children }: { active?: boolean; disabled?: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" disabled={disabled} onClick={onClick} className={active ? "min-h-11 rounded-xl bg-cyan-500 px-3 text-sm font-black text-white" : "min-h-11 rounded-xl bg-slate-100 px-3 text-sm font-black disabled:opacity-40 dark:bg-white/10"}>{children}</button>; }
