import { expect, test } from "@playwright/test";

test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });

test("3D geometry shape library, inspector, undo, and viewport remain usable", async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto("/workspace/3d");
  const root = page.locator(".object-studio-shell");
  await expect(root).toBeVisible({ timeout: 30_000 });
  const canvas = root.locator("canvas").first();
  await expect(canvas).toBeVisible();
  const initialCount = await root.locator(".os-object-list > div").count();
  await page.getByRole("button", { name: "Shape library menu" }).click();
  await expect(root).toHaveAttribute("data-mws-overlay", "shapes");
  await page.getByRole("button", { name: "Collapse Shape Library" }).click();
  await expect(root).toHaveAttribute("data-mws-overlay", "");
  await page.getByRole("button", { name: "Shape library menu" }).click();
  await page.getByRole("button", { name: "Add Cube" }).click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(initialCount + 1);
  await expect(root).toHaveAttribute("data-mws-overlay", "inspector");
  await page.getByRole("button", { name: "Delete Cube" }).last().click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(initialCount);
  await page.getByRole("button", { name: "Close inspector" }).click();
  await expect(root).toHaveAttribute("data-mws-overlay", "");
  const toolbar = page.getByRole("navigation", { name: "3D geometry tools" });
  await toolbar.getByRole("button", { name: "More" }).click();
  await page.getByRole("button", { name: "Undo", exact: true }).last().click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(initialCount + 1);
  await toolbar.getByRole("button", { name: "More" }).click();
  await page.getByRole("button", { name: "Redo", exact: true }).last().click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(initialCount);
  await toolbar.getByRole("button", { name: "More" }).click();
  await page.getByRole("button", { name: "Clear all objects" }).click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(0);
  await toolbar.getByRole("button", { name: "More" }).click();
  await page.getByRole("button", { name: "Undo", exact: true }).last().click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(initialCount);
  await toolbar.getByRole("button", { name: "More" }).click();
  await page.getByRole("button", { name: "Redo", exact: true }).last().click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(0);
  await page.getByRole("button", { name: "Shape library menu" }).click();
  await page.getByRole("button", { name: "Add Cube" }).click();
  await expect(root.locator(".os-object-list > div")).toHaveCount(1);
  await page.getByRole("button", { name: "Close inspector" }).click();
  const box = await canvas.boundingBox();
  expect(box!.width).toBeGreaterThan(300);
  expect(box!.height).toBeGreaterThan(500);
  await page.mouse.move(box!.x + box!.width * 0.5, box!.y + box!.height * 0.4);
  await page.mouse.down();
  await page.mouse.move(box!.x + box!.width * 0.65, box!.y + box!.height * 0.55, { steps: 8 });
  await page.mouse.up();
  await expect(canvas).toBeVisible();
  await page.setViewportSize({ width: 844, height: 390 });
  await expect.poll(() => canvas.evaluate((element) => element.getBoundingClientRect().width)).toBeGreaterThan(700);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => canvas.evaluate((element) => element.getBoundingClientRect().height)).toBeGreaterThan(500);
});
