import {test,expect,type Page} from '@playwright/test';
const path='/set-theory/venn-diagram-engine';
async function state(page:Page){return page.evaluate(()=>{const svg=document.querySelector('svg[aria-label="Live three-set Venn diagram"]')!;const circles=[...svg.querySelectorAll<SVGCircleElement>('[data-set-circle]')].map(c=>({id:c.dataset.setCircle,x:c.cx.baseVal.value,y:c.cy.baseVal.value,r:c.r.baseVal.value}));const points=[...svg.querySelectorAll<SVGGElement>('[data-element]')].map(g=>{const c=g.querySelector('circle')!;return {id:g.dataset.element,x:c.cx.baseVal.value,y:c.cy.baseVal.value,mask:Number(g.dataset.membership)};});const stored=JSON.parse(localStorage.getItem('math-universe-set-theory-session')!).state;return {circles,points,sets:[stored.setA,stored.setB,stored.setC] as string[][]};});}
async function correct(page:Page){const s=await state(page);for(const p of s.points){const mask=s.circles.reduce((m,c,i)=>m|(Math.hypot(p.x-c.x,p.y-c.y)<c.r?1<<i:0),0);expect(mask).toBe(p.mask);expect(s.sets.reduce((m,set,i)=>m|(set.includes(p.id!)?1<<i:0),0)).toBe(mask);}return s;}
test('dragging a circle carries its owned and shared numbers and keeps set results truthful',async({page})=>{
 await page.goto(path);const svg=page.getByRole('img',{name:'Live three-set Venn diagram'});await expect(svg).toBeVisible();await page.getByLabel('Circle movement',{exact:true}).selectOption('explore');const before=await correct(page);
 const target=await svg.evaluate(svg=>{const p=new DOMPoint(485,150).matrixTransform((svg as SVGSVGElement).getScreenCTM()!);const q=new DOMPoint(545,130).matrixTransform((svg as SVGSVGElement).getScreenCTM()!);return {x:p.x,y:p.y,endX:q.x,endY:q.y};});await page.mouse.move(target.x,target.y);await page.mouse.down();await page.mouse.move(target.endX,target.endY,{steps:12});await page.mouse.up();const after=await correct(page);expect(after.circles[1].x).toBeCloseTo(before.circles[1].x+60,0);for(const item of before.sets[1]){const p=before.points.find(p=>p.id===item)!,q=after.points.find(p=>p.id===item)!;expect(Math.hypot(q.x-p.x,q.y-p.y)).toBeGreaterThan(5);expect(after.sets[1]).toContain(item);}await page.screenshot({path:'artifacts/set-theory-upgrade/connected-circle-drag.png'});
});
test('resizing and keyboard movement keep numbers connected and direct marker movement still edits membership',async({page})=>{
 await page.goto(path);await page.getByRole('img',{name:'Live three-set Venn diagram'}).waitFor();await page.getByLabel('Circle movement',{exact:true}).selectOption('explore');const before=await correct(page);await page.getByLabel('Set A radius', {exact:true}).fill('110');const resized=await correct(page);expect(resized.circles[0].r).toBe(110);for(const item of before.sets[0])expect(resized.sets[0]).toContain(item);const circle=page.getByRole('button',{name:'Move Set A',exact:true});await circle.focus();await page.keyboard.press('ArrowRight');expect((await correct(page)).circles[0].x).toBeCloseTo(resized.circles[0].x+8,0);
 const marker=page.getByRole('button',{name:'Move element 1',exact:true});await marker.focus();for(let i=0;i<35;i++)await page.keyboard.press('ArrowRight');const moved=await correct(page);expect(moved.sets[0]).not.toContain('1');
});

