import { useEffect, useState } from 'react';
import { useStudioModel, useStudioState } from '../../phase1/StudioModelProvider';
import { Card, Button, Field, Tabs } from './components';
import { NumberLine, makePoints } from './NumberLine';
import { decimalText, parseReal, fractionText, compareReal, short, terminatingDenominator, type Rational } from './math';
export function FractionModels({r,all=false,mode='Pie Chart'}:{r:Rational;all?:boolean;mode?:string}){const value=r.numerator/r.denominator,amount=Math.abs(value),whole=Math.floor(amount),portion=amount>=1?amount-whole:amount,slices=Math.min(r.denominator,24),angle=portion*2*Math.PI,endX=80+62*Math.sin(angle),endY=80-62*Math.cos(angle);const bar=<div className="np-model"><h3>Fraction Bar</h3><svg viewBox="0 0 240 110" aria-label="Fraction bar model"><rect x="10" y="25" width="220" height="45" fill="#f5f5ff" stroke="#7b5af2"/><rect x="10" y="25" width={220*portion} height="45" fill="#b7a2ff"/>{Array.from({length:slices-1},(_,i)=><line key={i} x1={10+(i+1)*220/slices} x2={10+(i+1)*220/slices} y1="25" y2="70" stroke="#8761f5"/>)}<text x="120" y="98" textAnchor="middle" fontSize="16" fill="#252567">{fractionText(r)}</text></svg><p>{r.denominator>24?'Subdivision marks are limited to 24; the fill proportion is exact.':`${Math.abs(r.numerator)} parts over ${r.denominator} parts per unit.`}</p></div>;
 const pie=<div className="np-model"><h3>Circle Model</h3><svg viewBox="0 0 160 160" aria-label="Fraction circle model"><circle cx="80" cy="80" r="62" fill="#f5f6ff" stroke="#765ce4"/>{portion===0?null:<path d={`M80 80L80 18A62 62 0 ${portion>.5?1:0} 1 ${endX} ${endY}Z`} fill="#b6a3ff" stroke="#7957e9"/>}{r.denominator<=12?Array.from({length:r.denominator},(_,i)=><line key={i} x1="80" y1="80" x2={80+62*Math.sin(i/r.denominator*2*Math.PI)} y2={80-62*Math.cos(i/r.denominator*2*Math.PI)} stroke="#8971de"/>):null}</svg><b className="np-formula">{fractionText(r)}</b><p>Shading shows the fractional part of one unit.</p></div>;
 return <><div className={all?'np-three np-model-grid':'np-model-single'}>{all||mode==='Fraction Bar'?bar:null}{all||mode==='Pie Chart'?pie:null}{all||mode==='Number Line'?<div className="np-model"><h3>Number Line</h3><NumberLine compact points={makePoints([fractionText(r)],[value])} min={Math.min(0,value)-.1} max={Math.max(1,value)+.1}/><p>Located at {short(value)}.</p></div>:null}</div>{whole>0||value<0?<p className="np-info">{value<0?'The value is negative; models show magnitude. ':''}{whole} complete unit{whole===1?'':'s'} plus {short(portion)} of another unit.</p>:null}</>;
}
export function ConversionEngine({raw,setRaw}:{raw:string;setRaw:(s:string)=>void}){const model=useStudioModel(),[mode,setMode]=useState('Fraction'),[p,setP]=useState('3'),[q,setQ]=useState('4'),[error,setError]=useState('');const parsed=parseReal(raw),r=parsed.rational!;const update=(s:string)=>{try{const x=parseReal(s);if(!x.rational)throw Error('Use a rational value for conversion.');setRaw(s);setError('');}catch(e){setError((e as Error).message);}};
 useEffect(()=>{if(raw.includes('/')){const [n,d]=raw.split('/');setP(n);setQ(d);setMode('Fraction');}},[raw]);
 const [draft,setDraft]=useState('0.75');const changeMode=(s:string)=>{setMode(s);setError('');setP(String(r.numerator));setQ(String(r.denominator));setDraft(s==='Percentage'?short(parsed.value*100):s==='Ratio'?`${r.numerator}:${r.denominator}`:short(parsed.value));};
 return <Card title="Conversion Engine" icon="▦" description="Enter a value in any form. All equivalent representations update together."><Tabs options={['Fraction','Decimal','Percentage','Ratio']} value={mode} onChange={changeMode}/><div className="np-conversion-input">{mode==='Fraction'?<div className="np-fraction-input"><Field label="Fraction numerator" type="number" value={p} onChange={v=>{setP(v);update(`${v}/${q}`);}}/><hr/><Field label="Fraction denominator" type="number" value={q} onChange={v=>{setQ(v);update(`${p}/${v}`);}}/></div>:<Field label={`${mode} value`} value={draft} onChange={s=>{setDraft(s);update(mode==='Percentage'?s.replace(/%$/,'')+'%':s);}}/>}<span className="np-arrow">→</span><div className="np-soft mint"><h3>Decimal</h3><b className="np-big-value">{model&&!model.exact?short(parsed.value):decimalText(r)}</b></div><div className="np-soft violet"><h3>Percentage</h3><b className="np-big-value">{short(parsed.value*100)}%</b></div><div className="np-soft"><h3>Ratio</h3><b>{r.numerator}:{r.denominator}</b></div></div>{error?<p className="np-error" role="alert">{error}</p>:null}<p className="np-formula np-info">{fractionText(r)} = {decimalText(r)} {terminatingDenominator(r.denominator)?'=':'≈'} {short(parsed.value*100)}%</p><div className="np-pills">{['1/2','1/3','3/4','5/8','8/12'].map(s=><Button key={s} onClick={()=>{update(s);const [n,d]=s.split('/');setP(n);setQ(d);setMode('Fraction');}}>{s}</Button>)}</div></Card>;
}
export function CompareForms(){const [a,setA]=useState('2/5'),[b,setB]=useState('3/4');let explanation='',error='';try{const x=parseReal(a),y=parseReal(b);explanation=`${a} ${compareReal(x,y)} ${b}: ${short(x.value)} ${compareReal(x,y)} ${short(y.value)}`;}catch(e){error=(e as Error).message;}return <Card title="Compare Forms" icon="⚖"><div className="np-two"><Field label="Compare left value" value={a} onChange={setA}/><Field label="Compare right value" value={b} onChange={setB}/></div><output className="np-formula np-info">{error||explanation}</output><p>Use exact fraction arithmetic where both operands are rational.</p></Card>;}
export default function Conversion({fractions=false}:{fractions?:boolean}){const [raw,setRaw]=useStudioState('number-premium:conversion-input','3/4'),r=parseReal(raw).rational!,setR=(v:Rational)=>setRaw(fractionText(v)),[view,setView]=useState('Pie Chart');return <><div className={fractions?'np-two':'np-rational-grid'}><ConversionEngine raw={raw} setRaw={setRaw}/><Card title={fractions?'Visual Models':'Visual Representation'} icon="◉" description="The same value represented as shaded parts and position."><FractionModels r={r} all={fractions} mode={view}/>{!fractions?<Tabs options={['Fraction Bar','Pie Chart','Number Line']} value={view} onChange={setView}/>:null}</Card>{!fractions?<Card title="Terminating vs. Repeating Decimals" icon="3"><div className="np-two"><div className="np-soft mint"><h3>Terminating</h3><b className="np-formula">1/2 = 0.5</b><p>This decimal ends.</p></div><div className="np-soft violet"><h3>Repeating</h3><b className="np-formula">1/3 = 0.(3)</b><p>The digit 3 repeats forever.</p></div></div><p className="np-info">A reduced denominator with only factors 2 and 5 terminates. Otherwise the decimal eventually repeats.</p><p>Current value: <b>{terminatingDenominator(r.denominator)?'terminating':'repeating'}</b>.</p></Card>:null}</div><div className="np-three"><CompareForms/>{fractions?<Card title="Real-World Examples" icon="◎"><div className="np-three"><div className="np-soft"><span className="np-example-art">🍕</span><h3>Pizza</h3><p>3 of 4 equal slices is 3/4 = 75%.</p><Button onClick={()=>setR(parseReal('3/4').rational!)}>Visualize</Button></div><div className="np-soft"><span className="np-example-art">🏷</span><h3>Discounts</h3><p>A 75% discount leaves 25% of the price to pay.</p><Button onClick={()=>setR(parseReal('25%').rational!)}>Visualize</Button></div><div className="np-soft"><span className="np-example-art">▤</span><h3>Test Scores</h3><p>15 out of 20 correct gives 75%.</p><Button onClick={()=>setR(parseReal('15/20').rational!)}>Visualize</Button></div></div></Card>:<Card title="Equivalent Fractions & Simplification" icon="≡"><p className="np-formula">{fractionText(r)} = {r.numerator*2}/{r.denominator*2} = {r.numerator*3}/{r.denominator*3}</p><p>Multiply numerator and denominator by the same nonzero integer.</p><p className="np-info">8/12 → 2/3: divide both components by gcd(8,12)=4.</p></Card>}<Card title="Key Ideas" icon="☀"><ul><li>Fractions, decimals, percentages and ratios can express the same rational number.</li><li>The denominator must be nonzero.</li><li>Decimals end or eventually repeat.</li><li>Equivalent fractions multiply both components equally.</li><li>Divide to obtain a decimal; multiply by 100 to obtain a percentage.</li></ul></Card></div></>;}
