import {describe,it,expect} from 'vitest';
import {parseReal,memberships,compareReal,interval,intervalContains,intervalText,union,intersection,closure,question,grades,formulas,decimalText,operate} from './math';
describe('Number Systems exact models',()=>{
 it.each([['0',['W','Z','Q','R']],['1',['N','W','Z','Q','R']],['-2',['Z','Q','R']],['3/4',['Q','R']],['0.(3)',['Q','R']],['π',['I','R']],['√2',['I','R']],['√9',['N','W','Z','Q','R']],['-√2',['I','R']]])('classifies %s',(s,sets)=>expect(memberships(parseReal(s as string))).toEqual(sets));
 it('normalizes fractions, percentages, ratios and repeating decimals',()=>{for(const s of ['3/4','0.75','75%','3:4'])expect(parseReal(s).rational).toEqual({numerator:3,denominator:4});expect(parseReal('-1.2(3)').rational).toEqual({numerator:-37,denominator:30});expect(decimalText(parseReal('1/3').rational!)).toContain('3');});
 it('compares rational cross-products without float equality',()=>{expect(compareReal(parseReal('2/3'),parseReal('0.6666666667'))).toBe('<');expect(compareReal(parseReal('3/4'),parseReal('75%'))).toBe('=');expect(compareReal(parseReal('√2'),parseReal('1.4'))).toBe('>');});
 it('rejects undefined and nonreal inputs',()=>{for(const s of ['1/0','√-2','hello'])expect(()=>parseReal(s)).toThrow();expect(()=>operate(parseReal('1'),parseReal('0'),'÷')).toThrow('Division by zero');});
 it('handles open, closed, infinite and singleton intervals',()=>{const a=interval(-2,1,false,true);expect(intervalContains(a,-2)).toBe(false);expect(intervalContains(a,1)).toBe(true);expect(intervalText(interval(-Infinity,Infinity,true,true))).toBe('(−∞, ∞)');expect(intervalText(interval(1,1,true,true))).toBe('[1, 1]');expect(intervalText(interval(1,1,false,true))).toBe('∅');expect(()=>interval(3,2,true,true)).toThrow();});
 it('merges touching intervals only when their joining point is included',()=>{expect(union(interval(0,1,false,false),interval(1,2,false,false))).toHaveLength(2);expect(union(interval(0,1,false,true),interval(1,2,false,false)).map(intervalText)).toEqual(['(0, 2)']);expect(intersection(interval(0,1,true,true),interval(1,2,true,true)).map(intervalText)).toEqual(['[1, 1]']);expect(intersection(interval(0,1,true,false),interval(1,2,true,true))).toEqual([]);});
 it('states closure correctly',()=>{expect(Object.values(closure.I).every(x=>x.startsWith('Not closed'))).toBe(true);expect(closure.Q['÷']).toContain('nonzero');expect(closure.N['−']).toContain('Not closed');});
 it('generates varied, graded practice for every formula',()=>{for(const f of formulas){const prompts=new Set(Array.from({length:200},(_,i)=>question(f,i,'Hard').prompt));expect(prompts.size).toBeGreaterThan(95);for(let i=0;i<30;i++){const q=question(f,i,'Medium');expect(grades(q.answer,q.answer)).toBe(true);if(q.second)expect(grades(q.second,q.second)).toBe(true);}}expect(new Set(Array.from({length:10},(_,i)=>question('Compare Numbers',i,'Easy').answer))).toEqual(new Set(['<','=','>']));});
});
