import { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { Header, Hero, Card, Preview, TheoryPanel, Button } from './components';
import { labs, route } from './catalog';
import { Classification } from './Classification';
import { NaturalWhole, Integers } from './CountingIntegers';
import Conversion from './Conversion';
import Irrational from './Irrational';
import RealLine from './RealLine';
import { Ordering, Properties } from './OrderingProperties';
import FormulaLab from './FormulaLab';
import LiveExperiment from './LiveExperiment';
import { NUMBER_TAB_REDIRECTS, NUMBER_SYSTEMS_ROUTES, completedLabs, rememberLastRoute } from '../../../pages/numberSystemsStudioSession';
import './numberPremium.css';
function readCompleted():string[]{try{return [...new Set([...completedLabs(),...JSON.parse(localStorage.getItem('number-premium:completed')||'[]')])];}catch{return [];}}
function Home({done}:{done:string[]}){const featured=labs[0],group=labs.slice(1,8),completed=labs.slice(0,8).filter(l=>done.includes(l.id)).length,percent=Math.round(completed/8*100);return <><div id="np-lab"/><section id="np-labs" className="np-home-grid"><div><header className="np-section-heading"><h2>▧ Explore the Labs</h2><p>Hands-on labs to explore, visualize and master each part of the number system.</p></header><Link className="np-home-card featured" to={route(featured.id)}><span className="np-icon">▣</span><div><h2>{featured.title}</h2><p>{featured.description}</p><div className="np-pills">{featured.chips.map(x=><span className="np-chip" key={x}>{x}</span>)}</div></div><Preview id={featured.id}/><span className="np-card-cta">Open Lab →</span></Link><div className="np-home-small-grid">{group.slice(0,3).map(l=><LabCard key={l.id} lab={l}/>)}</div></div><Card title="Your Learning Path" icon="▥"><p>Make progress, one step at a time.</p><div className="np-progress-ring" style={{background:`conic-gradient(#1fc6b5 ${percent*3.6}deg,#edf2ff 0)`}}><span>{percent}%</span></div><h3>Continue where you left off</h3><p>{completed} of the first 8 labs completed.</p><Link className="np-button primary" to={route(labs.find(l=>!done.includes(l.id))?.id||'formula-visualizer')}>Continue Learning →</Link><p className="np-info">Small steps lead to big understanding. Progress counts only completed checks.</p></Card></section><div className="np-home-bottom-grid">{group.slice(3).map(l=><LabCard key={l.id} lab={l}/>)}</div><div className="np-feature-strip"><div><b>◉ Visual First</b><p>Number lines, set maps and live examples.</p></div><div><b>↖ Interactive</b><p>Drag, compare, classify and convert.</p></div><div><b>▥ Step by Step</b><p>Theory, examples and guided practice.</p></div></div><Card title="Explore Further" description="Additional labs and existing learning material remain available."><div className="np-home-bottom-grid">{labs.slice(8).map(l=><LabCard key={l.id} lab={l}/>)}</div><div className="np-pills"><Link className="np-button" to="/number-systems/concepts">Existing concept cards →</Link><Link className="np-button" to="/number-systems/practice">Existing practice & accuracy →</Link><Link className="np-button" to="/studios/number-systems/curriculum">Complete learning path →</Link></div></Card></>;}
function LabCard({lab}:{lab:typeof labs[number]}){return <Link to={route(lab.id)} className={`np-home-card lab-${lab.id}`}><span className="np-icon">{lab.icon}</span><div><h3>{lab.title}</h3><p>{lab.description}</p><div className="np-pills">{lab.chips.map(x=><span key={x} className="np-chip">{x}</span>)}</div></div><Preview id={lab.id}/><span className="np-card-cta">Open Lab →</span></Link>;}
export default function NumberPremium(){const location=useLocation(),navigate=useNavigate(),[params]=useSearchParams(),id=location.pathname.split('/')[2]||'home',[done,setDone]=useState(readCompleted);const home=id==='home',lab=labs.find(x=>x.id===id),complete=()=>{if(!done.includes(id)){const next=[...done,id];setDone(next);localStorage.setItem('number-premium:completed',JSON.stringify(next));}};
 useEffect(()=>{document.title=`${home?'Number Systems Studio':lab?.title||'Number Systems'} | Math Universe`;if(!home)rememberLastRoute(location.pathname);const tab=params.get('tab');if(home&&tab&&NUMBER_TAB_REDIRECTS[tab])navigate(NUMBER_SYSTEMS_ROUTES[NUMBER_TAB_REDIRECTS[tab]],{replace:true});if(home&&params.get('lab')==='resume')navigate(route(labs.find(x=>!done.includes(x.id))?.id||'formula-visualizer'),{replace:true});},[home,lab,location.pathname,params,navigate,done]);
 const contents:Record<string,React.ReactNode>={fundamentals:<Classification/>,hierarchy:<Classification hierarchy/>,'natural-whole':<NaturalWhole/>,integers:<Integers/>,rational:<Conversion/>,irrational:<Irrational/>,'real-line':<RealLine/>,'fractions-decimals-percentages':<Conversion fractions/>,'ordering-comparing':<Ordering/>,'absolute-distance-intervals':<RealLine absolute/>,'properties-operations':<Properties/>,'formula-visualizer':<FormulaLab onComplete={complete}/>};
 return <div className={`np-studio np-page-${id}`}><Header/><main className="np-main"><Hero id={id} home={home}/>{home?<><Home done={done}/><LiveExperiment key="home" id="home"/></>:<><div id="np-lab" className="np-lab-content"><LiveExperiment key={id} id={id} onComplete={complete}/>{contents[id]||<Card title="Choose a lab"><Link to="/number-systems">Studio Home</Link></Card>}</div><TheoryPanel id={id} onComplete={complete}/><nav className="np-lab-nav" aria-label="Number Systems Studio navigation">{labs.map(l=><Link key={l.id} aria-current={l.id===id?'page':undefined} to={route(l.id)}>{l.title}</Link>)}</nav>{['rational','irrational','real-line','hierarchy'].includes(id)?<details className="np-retained"><summary>Additional existing workbench, lessons and examples</summary><p>The original working lab remains available with its presets and explanations.</p><Link className="np-button" to={`${route(id)}?legacy=1`}>Open retained {lab?.title} workbench →</Link></details>:null}</>}<footer className="np-footer"><Link to="/number-systems">✦ Interactive Math Lab</Link><span>Numbers are everywhere. Let’s make sense of them together.</span><Link to="/studios/number-systems/curriculum">Explore · Practice · Build Confidence</Link></footer></main>{home?<nav className="np-sr-only" aria-label="Number Systems Studio navigation">{labs.map(l=><Link key={l.id} to={route(l.id)}>{l.title}</Link>)}</nav>:null}<Button onClick={()=>{document.querySelector('.studio-learning-content')?.scrollTo({top:0,behavior:'smooth'});document.getElementById('main-content')?.scrollTo({top:0,behavior:'smooth'});window.scrollTo({top:0,behavior:'smooth'});}}>Back to Top ↑</Button></div>;
}

