import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1672,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const base='http://127.0.0.1:5178/trigonometry/oblique',routes=[['','Overview'],['sine-law','Sine Law'],['cosine-law','Cosine Law'],['area','Area of a Triangle'],['ssa-ambiguous-case','SSA Ambiguous Case'],['solve-triangle','Solve Triangle']],report={routes:[],interactions:[],legacy:[],errors};
await page.goto(base,{waitUntil:'domcontentloaded',timeout:120000});const root=page.locator('.obl-studio');await root.waitFor({timeout:120000});
for(const [slug,name] of routes){if(slug)await root.locator('.obl-subnav').getByRole('link',{name,exact:true}).click();await expect(root).toHaveAttribute('data-oblique-page',slug||'overview');await root.locator('.obl-header').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/oblique-studio/${slug||'overview'}-desktop.png`,fullPage:true});report.routes.push({slug:slug||'overview',title:await root.locator('h1').innerText(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),preservedTabs:await page.locator('.obl-preserved-learning [role=tab]').count()});
 if(slug){const explorer=root.locator('.obl-explorer'),svg=explorer.locator('svg.obl-triangle'),vals=explorer.locator('.obl-live-values');const before=await vals.innerText();const vertex=svg.getByRole('button',{name:'Move vertex C with arrow keys'});await vertex.focus();await page.keyboard.press('ArrowRight');await expect(vals).not.toHaveText(before);report.interactions.push({slug,keyboardUpdates:true});const node=vertex.locator('circle').last(),box=await node.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+17,box.y+box.height/2-10,{steps:5});await page.mouse.up();report.interactions.push({slug,dragUpdates:await vals.innerText()!==before});await explorer.getByLabel('Show values',{exact:true}).uncheck();await expect(svg.locator('.obl-svg-label').first()).not.toContainText('=');await explorer.getByLabel('Show values',{exact:true}).check();await explorer.getByRole('button',{name:'Reset',exact:true}).click();
 }
 if(slug==='sine-law'){await root.getByLabel('Angle A',{exact:true}).fill('30');await root.getByLabel('Angle B',{exact:true}).fill('45');await root.getByLabel('Side a (opposite A)',{exact:true}).fill('10');await expect(root.locator('#obl-sine-result')).toContainText('14.1421');await root.getByRole('button',{name:'Solve for an Angle (SSA)',exact:true}).click();await root.getByLabel('Angle A',{exact:true}).fill('40');await root.getByLabel('Side a (opposite A)',{exact:true}).fill('8');await root.getByLabel('Side b (opposite B)',{exact:true}).fill('10');await expect(root.locator('#obl-sine-result .obl-answer')).toHaveCount(2);await explorerToggle('Show both solutions');await root.locator('.obl-explorer').getByLabel('Show circumcircle').check();report.interactions.push({slug,ASA:true,SSA:true});}
 if(slug==='cosine-law'){await root.getByLabel('Side b',{exact:true}).fill('9');await root.getByLabel('Side c',{exact:true}).fill('7');await root.getByLabel('Angle A',{exact:true}).fill('60');await expect(root.locator('#obl-cosine-result .obl-answer')).toContainText('8.1854');await root.getByRole('button',{name:'Solve for an Angle',exact:true}).click();await root.getByLabel('Side a',{exact:true}).fill('5');await root.getByLabel('Side b',{exact:true}).fill('6');await root.getByLabel('Side c',{exact:true}).fill('7');await expect(root.locator('#obl-cosine-result .obl-answer')).toContainText('44.4153');await root.getByLabel('Side a',{exact:true}).fill('20');await expect(root.locator('#obl-cosine-result [role=alert]')).toContainText('No triangle');report.interactions.push({slug,SAS:true,SSS:true,invalidRejected:true});}
 if(slug==='area'){await root.getByLabel('Side b',{exact:true}).fill('8');await root.getByLabel('Side c',{exact:true}).fill('10');await root.getByLabel('Angle A (between b and c)',{exact:true}).fill('30');await expect(root.locator('#obl-area-result .obl-answer')).toContainText('20');for(const pair of ['B','C','A']){await root.getByLabel('Area formula choice').selectOption(pair);await expect(root.locator('#obl-area-result .obl-answer')).toContainText('20');}await explorerToggle('Show height');report.interactions.push({slug,area20:true,cyclicFormulas:true});}
 if(slug==='ssa-ambiguous-case'){for(const [preset,n] of [['No triangle',0],['One right triangle',1],['Two triangles',2],['One ordinary triangle',1],['Obtuse: no triangle',0],['Obtuse: one triangle',1]]){await root.getByRole('button',{name:preset,exact:true}).click();await expect(root.locator('#obl-ssa-result .obl-answer')).toContainText(`${n} possible`);await expect(root.locator('#obl-ssa-result .obl-complete')).toHaveCount(n);}await root.getByRole('button',{name:'Compare Outcomes',exact:true}).click();await expect(root.locator('.obl-outcomes button')).toHaveCount(6);report.interactions.push({slug,allSixOutcomes:true});}
 if(slug==='solve-triangle'){for(const kind of ['ASA','AAS','SAS','SSS','SSA']){await root.getByLabel('Problem type').selectOption(kind);await expect(root.locator('#obl-full-solution .obl-answer')).toHaveCount(kind==='SSA'?2:1);}await root.getByRole('button',{name:'Next Step',exact:true}).click();await root.getByRole('button',{name:'Solution 2',exact:true}).click();await root.getByLabel('Problem type').selectOption('SSS');await root.getByLabel('Side a',{exact:true}).fill('1');await root.getByLabel('Side b',{exact:true}).fill('2');await root.getByLabel('Side c',{exact:true}).fill('10');await expect(root.locator('#obl-full-solution [role=alert]')).toContainText('triangle inequalities');report.interactions.push({slug,allCases:true,steps:true,invalidRejected:true});}
 await page.setViewportSize({width:390,height:844});await root.locator('.obl-header').scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/oblique-studio/${slug||'overview'}-mobile.png`,fullPage:true});report.routes.at(-1).mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.setViewportSize({width:1672,height:1050});
}
async function explorerToggle(name){const box=root.locator('.obl-explorer').getByLabel(name,{exact:true});await box.uncheck();await box.check();}
for(const [mode,slug] of [['Sine Law','sine-law'],['SineLaw','sine-law'],['CosineLaw','cosine-law'],['Area','area'],['SSA Ambiguous Case','ssa-ambiguous-case'],['SSAAmbiguousCase','ssa-ambiguous-case'],['SolveTriangle','solve-triangle']]){await page.goto(`${base}?mode=${encodeURIComponent(mode)}`,{waitUntil:'domcontentloaded',timeout:120000});await expect(root).toHaveAttribute('data-oblique-page',slug);report.legacy.push({mode,url:page.url()});}
fs.writeFileSync('artifacts/oblique-studio/browser-report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));
