export type Observation={x:number;y:number};export function modellingWorkflow(question:string,assumptions:string[],variables:string[],equations:string[]){return{question,assumptions,variables,equations,ready:Boolean(question&&assumptions.length&&variables.length&&equations.length),warnings:assumptions.length<2?["Declare additional assumptions"]:[]}}
export function checkUnits(terms:Array<{coefficient:number;unit:Record<string,number>}>){const signature=(u:Record<string,number>)=>Object.entries(u).filter(([,p])=>p).sort().map(([k,p])=>`${k}^${p}`).join(" ");const signatures=terms.map(t=>signature(t.unit));return{consistent:signatures.every(s=>s===signatures[0]),signatures}}
export function importObservations(csv:string){const rows=csv.trim().split(/\r?\n/).map(line=>line.split(",").map(Number)).filter(r=>r.length>=2&&r.every(Number.isFinite));return{observations:rows.map(([x,y])=>({x,y})),valid:rows.length>1}}
export function fitLinear(data:Observation[]){const mx=avg(data.map(p=>p.x)),my=avg(data.map(p=>p.y)),sxx=data.reduce((s,p)=>s+(p.x-mx)**2,0),sxy=data.reduce((s,p)=>s+(p.x-mx)*(p.y-my),0),slope=sxy/sxx,intercept=my-slope*mx;return{intercept,slope,predict:(x:number)=>intercept+slope*x}}
export function informationCriteria(data:Observation[],predict:(x:number)=>number,parameters:number){const rss=data.reduce((s,p)=>s+(p.y-predict(p.x))**2,0),n=data.length,aic=n*Math.log(rss/n||1e-15)+2*parameters,bic=n*Math.log(rss/n||1e-15)+parameters*Math.log(n);return{rss,aic,bic}}
export function residualDiagnostics(data:Observation[],predict:(x:number)=>number){const residuals=data.map(p=>p.y-predict(p.x)),mean=avg(residuals),rmse=Math.sqrt(avg(residuals.map(r=>r*r))),lag1=residuals.length<2?0:correlation(residuals.slice(0,-1),residuals.slice(1));return{residuals,mean,rmse,lag1}}
export function linearParameterIntervals(data:Observation[],confidenceZ=1.96){const fit=fitLinear(data),res=data.map(p=>p.y-fit.predict(p.x)),s2=res.reduce((s,r)=>s+r*r,0)/(data.length-2),mx=avg(data.map(p=>p.x)),sxx=data.reduce((s,p)=>s+(p.x-mx)**2,0),slopeSE=Math.sqrt(s2/sxx),interceptSE=Math.sqrt(s2*(1/data.length+mx*mx/sxx));return{slope:[fit.slope-confidenceZ*slopeSE,fit.slope+confidenceZ*slopeSE],intercept:[fit.intercept-confidenceZ*interceptSE,fit.intercept+confidenceZ*interceptSE]}}
export function sensitivity(model:(parameters:number[])=>number,parameters:number[],relativeStep=1e-4){const baseline=model(parameters);return parameters.map((value,i)=>{const h=Math.max(1e-6,Math.abs(value)*relativeStep),next=[...parameters];next[i]+=h;return{parameter:i,derivative:(model(next)-baseline)/h,elasticity:baseline===0?undefined:(model(next)-baseline)/h*value/baseline}})}
export function identifiability(jacobian:number[][]){const columns=jacobian[0].map((_,j)=>jacobian.map(row=>row[j])),pairs=[];for(let i=0;i<columns.length;i++)for(let j=i+1;j<columns.length;j++)pairs.push({parameters:[i,j],correlation:Math.abs(correlation(columns[i],columns[j]))});return{identifiable:pairs.every(p=>p.correlation<.999),confounded:pairs.filter(p=>p.correlation>=.999)}}
export function kFoldValidation(data:Observation[],k:number){const errors=[];for(let fold=0;fold<k;fold++){const train=data.filter((_,i)=>i%k!==fold),test=data.filter((_,i)=>i%k===fold),fit=fitLinear(train);errors.push(Math.sqrt(avg(test.map(p=>(p.y-fit.predict(p.x))**2))))}return{foldErrors:errors,rmse:avg(errors)}}
export function compareScenarios(model:(time:number,parameter:number)=>number,times:number[],parameters:number[]){return parameters.map(parameter=>({parameter,values:times.map(time=>({time,value:model(time,parameter)}))}))}
export function piecewiseIntervention(initial:number,rateBefore:number,rateAfter:number,interventionTime:number,time:number){const before=Math.min(time,interventionTime),after=Math.max(0,time-interventionTime);return{value:initial*Math.exp(rateBefore*before+rateAfter*after),before,after}}
export function seasonalDelay(base:number,trend:number,amplitude:number,period:number,lagged:number,time:number){return{value:base+trend*time+amplitude*Math.sin(2*Math.PI*time/period)+lagged}}
export function sirStep(state:{s:number;i:number;r:number},beta:number,gamma:number,dt:number){const infections=beta*state.s*state.i*dt,recoveries=gamma*state.i*dt;return{s:state.s-infections,i:state.i+infections-recoveries,r:state.r+recoveries}}
export function predatorPreyStep(state:{prey:number;predator:number},p:{growth:number;interaction:number;conversion:number;death:number},dt:number){return{prey:state.prey+dt*(p.growth*state.prey-p.interaction*state.prey*state.predator),predator:state.predator+dt*(p.conversion*state.prey*state.predator-p.death*state.predator)}}
export function compartmentStep(state:number[],flows:Array<{from:number;to:number;rate:number}>,dt:number){const next=[...state];for(const flow of flows){const amount=state[flow.from]*flow.rate*dt;next[flow.from]-=amount;next[flow.to]+=amount}return next}
export function agentSimulation(count:number,infectionProbability:number,steps:number,seed=1){const random=rng(seed),agents=Array.from({length:count},(_,i)=>i===0?1:0);const history=[1];for(let step=0;step<steps;step++){for(let i=0;i<count;i++)if(!agents[i]&&random()<infectionProbability*agents.reduce<number>((a,b)=>a+b,0)/count)agents[i]=1;history.push(agents.reduce<number>((a,b)=>a+b,0))}return{infected:history.at(-1),history}}
export function monteCarlo(model:(random:()=>number)=>number,runs:number,seed=1){const random=rng(seed),values=Array.from({length:runs},()=>model(random)).sort((a,b)=>a-b);return{mean:avg(values),low:quantile(values,.025),high:quantile(values,.975),runs}}
export function odeSolverComparison(f:(t:number,y:number)=>number,y0:number,t1:number,steps:number){const h=t1/steps;let euler=y0,rk4=y0,t=0;for(let i=0;i<steps;i++){euler+=h*f(t,euler);const k1=f(t,rk4),k2=f(t+h/2,rk4+h*k1/2),k3=f(t+h/2,rk4+h*k2/2),k4=f(t+h,rk4+h*k3);rk4+=h*(k1+2*k2+2*k3+k4)/6;t+=h}return{euler,rk4,difference:Math.abs(euler-rk4)}}
export function mm1Queue(arrivalRate:number,serviceRate:number){const stable=arrivalRate<serviceRate,rho=arrivalRate/serviceRate;return{stable,utilization:rho,expectedSystem:stable?1/(serviceRate-arrivalRate):Infinity,expectedQueue:stable?rho/(serviceRate-arrivalRate):Infinity}}
export function constrainedCalibration(data:Observation[],model:(x:number,p:number)=>number,min:number,max:number,steps=500){let best={parameter:min,rss:Infinity};for(let i=0;i<=steps;i++){const p=min+(max-min)*i/steps,rss=data.reduce((s,o)=>s+(o.y-model(o.x,p))**2,0);if(rss<best.rss)best={parameter:p,rss}}return best}
export function dimensionalAnalysis(matrix:number[][]){const rank=matrixRank(matrix),variables=matrix[0]?.length??0;return{rank,variables,dimensionlessGroups:variables-rank}}
export function parameterSweep(model:(a:number,b:number)=>number,aValues:number[],bValues:number[]){return aValues.map(a=>bValues.map(b=>({a,b,value:model(a,b)})))}
export function provenance(input:{model:string;parameters:Record<string,number>;assumptions:string[];dataHash:string}){const serialized=JSON.stringify(input);return{...input,versionId:hash(serialized),timestamp:"deterministic"}}
export function exportModelReport(input:{equations:string[];parameters:Record<string,number>;simulation:Observation[];diagnostics:unknown}){return{format:"math-universe-model/v1",...input,generatedSections:["equations","parameters","simulation","diagnostics"]}}
function avg(v:number[]){return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}function correlation(a:number[],b:number[]){const ma=avg(a),mb=avg(b),num=a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0),den=Math.sqrt(a.reduce((s,v)=>s+(v-ma)**2,0)*b.reduce((s,v)=>s+(v-mb)**2,0));return den?num/den:0}function quantile(v:number[],p:number){const i=(v.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return v[l]+(v[h]-v[l])*(i-l)}function rng(seed:number){let s=seed>>>0;return()=>((s=(1664525*s+1013904223)>>>0)/4294967296)}function hash(s:string){let h=2166136261;for(const ch of s)h=Math.imul(h^ch.charCodeAt(0),16777619);return(h>>>0).toString(16)}function matrixRank(input:number[][]){const m=input.map(r=>[...r]);let rank=0;for(let col=0;col<(m[0]?.length??0)&&rank<m.length;col++){let pivot=rank;while(pivot<m.length&&Math.abs(m[pivot][col])<1e-10)pivot++;if(pivot===m.length)continue;[m[rank],m[pivot]]=[m[pivot],m[rank]];const d=m[rank][col];m[rank]=m[rank].map(v=>v/d);for(let r=0;r<m.length;r++)if(r!==rank){const f=m[r][col];m[r]=m[r].map((v,j)=>v-f*m[rank][j])}rank++}return rank}
