import type { DeepFifteen } from "./catalogGatewayDeepFifteenTypes";

const e = (prompt: string, answer: string, ...acceptable: string[]) => ({
  prompt,
  answer,
  acceptable,
});

function d(
  id: number,
  canvas: DeepFifteen["canvas"],
  trap: DeepFifteen["trap"],
  identity: string,
  secondMisconception: DeepFifteen["secondMisconception"],
  counterexample: DeepFifteen["counterexample"],
  boardExam: DeepFifteen["boardExam"],
  spoken: string,
  keyboard: DeepFifteen["keyboard"],
  handoff: DeepFifteen["handoff"],
  generator: DeepFifteen["generator"],
  errorHatch: DeepFifteen["errorHatch"],
  copyExact: string,
  workedFromLive: DeepFifteen["workedFromLive"],
  probe: DeepFifteen["probe"],
  unlockGate: DeepFifteen["unlockGate"],
): [number, DeepFifteen] {
  return [
    id,
    {
      id,
      canvas,
      trap,
      identity,
      secondMisconception,
      counterexample,
      boardExam,
      spoken,
      keyboard,
      handoff,
      generator,
      errorHatch,
      copyExact,
      workedFromLive,
      probe,
      unlockGate,
    },
  ];
}

export const deepFifteenSchoolAdvanced: Record<number, DeepFifteen> = Object.fromEntries([
  d(
    10001,
    { title: "Four place-value slots", layers: ["thousands", "hundreds=700", "tens", "ones"], forbidden: "digit 7 read as ones in hundreds" },
    { wrong: "7 in hundreds labelled 7", right: "Place decides value. 7 hundreds is 700." },
    "4791 = 4000+700+90+1 · live {live}",
    { wrong: "Commas change the place values.", correction: "Indian or international grouping does not change 7 hundreds." },
    { setup: "How many tens in 40?", result: "4 tens. The 4 sits in the tens place." },
    e("Value of the tens digit in 4791?", "90"),
    "Seven in the hundreds place is seven hundred. Live {live}.",
    { keys: "digits and Tab", action: "Type a digit, then Tab to the next place." },
    { sentence: "Scaled quantities become ratio language.", href: "/lessons/school/class-7/class-7-numbers-and-arithmetic-ratio-tables", label: "Ratio Tables" },
    { seed: "circled-digit values", items: ["hundreds in {n}791", "tens in 40", "ones in 479{n}"] },
    { trigger: "7 in hundreds labelled 7", message: "Hatch: that digit is 700." },
    "7 hundreds = 700 · live {live}",
    ["Drop each live digit into a place.", "Expand as a sum of values.", "Read {live}."],
    e("Does the digit 4 always mean four ones?", "no"),
    { requirement: "Complete one four-place expansion.", checkLabel: "Expansion complete" },
  ),
  d(
    10017,
    { title: "Multiply-row double number line", layers: ["2:3", "×4", "8:12"], forbidden: "add 4 to both parts" },
    { wrong: "2:3 plus 4 becomes 6:7", right: "Equivalent ratios use a common multiplier. ×4 gives 8:12." },
    "2:3 = 8:12 · live {live}",
    { wrong: "Simplifying 8:12 by subtracting 6.", correction: "Divide both parts by 4 to return to 2:3." },
    { setup: "Missing cell 2:? when the pair is 3:9.", result: "Scale is ×3, so ?=6." },
    e("Scale 5:2 by 3.", "15:6"),
    "Times four, eight to twelve. Live {live}.",
    { keys: "×", action: "Apply the live scale factor." },
    { sentence: "Scaled lengths become compass radii.", href: "/lessons/school/class-8/class-8-practical-geometry-triangle-construction-by-sss", label: "Triangle Construction by SSS" },
    { seed: "equivalent rows plus an additive decoy", items: ["2:3 ×{n}", "4:6 vs 2:3", "2:3 +4 decoy"] },
    { trigger: "Add-the-same-number rewrite", message: "Hatch 6:7. That is not a scale." },
    "2:3 = 8:12 · live {live}",
    ["Name the live multiplier.", "Multiply both parts.", "Read {live}."],
    e("Do you add 4 to both parts to scale 2:3 by 4?", "no"),
    { requirement: "Do one multiply-scale and one simplify.", checkLabel: "Scale and simplify done" },
  ),
  d(
    10028,
    { title: "Two-arc SSS vertex", layers: ["base", "arc from A", "arc from B"], forbidden: "sides 1+2 do not beat 3" },
    { wrong: "Three segments in a line labelled SSS", right: "The third vertex is an arc intersection. 1,2,3 cannot close." },
    "two arcs meet or inequality fails · live {live}",
    { wrong: "A measured drawing counts as the construction.", correction: "SSS copies three lengths with a compass, then joins." },
    { setup: "3-4-5 vs 1-2-3.", result: "Only 3-4-5 has meeting arcs." },
    e("Can 2,2,3 form a triangle?", "yes"),
    "Two arcs meet, or the triangle inequality fails. Live {live}.",
    { keys: "side fields and Enter", action: "Set the three sides, then redraw arcs." },
    { sentence: "A constructed triangle is not a proof by measuring.", href: "/lessons/school/class-8/class-8-data-handling-mean-median-and-mode-practice-path", label: "Mean Median and Mode" },
    { seed: "3-4-5 / 5-5-6 / 1-2-3", items: ["3-4-5", "5-5-{n}", "1-2-3"] },
    { trigger: "Polyline labelled SSS", message: "Hatch the flat chain." },
    "SSS: 3 sides · 1,2,3 no · live {live}",
    ["Draw the live base.", "Swing both arcs.", "Join only if they meet: {live}."],
    e("Do the compass arcs locate the third vertex?", "yes"),
    { requirement: "Record one successful arc intersection.", checkLabel: "Arcs met" },
  ),
  d(
    10033,
    { title: "Three centres on one dot plot", layers: ["mean fulcrum", "median after sort", "mode tallest"], forbidden: "names used as synonyms" },
    { wrong: "Mean of 1,2,9 called 2 because it is the middle", right: "Sort first for the median. Mean is 4." },
    "mean / median / mode are different · live {live}",
    { wrong: "A list with all unique values still has a mode equal to the mean.", correction: "No repeated value means no unique mode." },
    { setup: "2,2,3,5.", result: "Mode 2. For n=4 the median is the average of 2 and 3, which is 2.5." },
    e("Median of 1,4,7?", "4"),
    "Median two after sorting. Mean is not the middle. Live {live}.",
    { keys: "M D O", action: "Highlight mean, median, or mode." },
    { sentence: "Naming a definition is a reason on the next proof page.", href: "/lessons/school/class-9/class-9-euclidean-geometry-proof-structure-and-logical-statements", label: "Proof Structure" },
    { seed: "symmetric / skewed / bimodal", items: ["1,2,9 skew", "3,3,3,{n} mode", "1,2,3,4 mean=median"] },
    { trigger: "Wrong centre definition used", message: "Hatch: that is a different centre." },
    "median=2 · mode=2 · mean≠median · live {live}",
    ["Sort the live list.", "Name all three centres.", "Read {live}."],
    e("Must mean equal median?", "no"),
    { requirement: "Name all three centres on one list.", checkLabel: "Three centres named" },
  ),
  d(
    10057,
    { title: "Reason-chip proof order", layers: ["Given", "Definition", "Theorem"], forbidden: "diagram measurement as a reason" },
    { wrong: "A tick-mark on the figure offered as a reason", right: "Each key step needs Given, Definition, Axiom, or Theorem." },
    "G1 then D1 then T1 · live {live}",
    { wrong: "One measured diagram proves the theorem for all cases.", correction: "A diagram is a sketch. The reasons must cover every case." },
    { setup: "Is a given fact an allowed reason?", result: "Yes. Given is a legal chip." },
    e("Which comes first: a definition used or the given it rests on?", "given"),
    "Reasons in order, or incomplete. Live {live}.",
    { keys: "1 2 3", action: "Add the next expected fact." },
    { sentence: "The three-step write-up becomes SAS style.", href: "/lessons/school/class-9/class-9-triangle-proofs-sas-congruence", label: "SAS Congruence" },
    { seed: "disordered proofs to repair", items: ["swap G1/D1", "missing theorem", "measure as reason {n}"] },
    { trigger: "Statement with no reason", message: "Hatch the bare statement." },
    "G1 Given · D1 Definition · T1 Theorem · live {live}",
    ["Drop only legal reason chips.", "Keep the live order.", "Check {live}."],
    e("Is a given fact an allowed reason?", "yes"),
    { requirement: "Check a valid three-reason order.", checkLabel: "Valid order checked" },
  ),
  d(
    10066,
    { title: "Included-angle pulse", layers: ["side", "included angle", "side"], forbidden: "far angle as the A of SAS" },
    { wrong: "SSA marked as SAS", right: "The angle must sit between the two given sides." },
    "SAS = two sides and the included angle · live {live}",
    { wrong: "SAS uses three sides.", correction: "Three sides is SSS. SAS is side-angle-side." },
    { setup: "Two sides and a non-included angle.", result: "Not SAS. The triangle may not be unique." },
    e("Does SAS use the angle opposite one of the sides?", "no"),
    "Angle between the sides, not the far angle. Live {live}.",
    { keys: "A", action: "Cycle marked angles; only the included one validates." },
    { sentence: "Congruent sides become equal distances.", href: "/lessons/school/class-10/class-10-coordinate-geometry-distance-formula", label: "Distance Formula" },
    { seed: "SAS / SSA / SSS mark-ups", items: ["SAS included", "SSA decoy", "SSS {n} sides"] },
    { trigger: "Non-included angle used", message: "Hatch the far angle. SSA danger." },
    "SAS = two sides and the included angle · live {live}",
    ["Mark the two live sides.", "Pulse the angle between them.", "Read {live}."],
    e("If two sides and a non-included angle match, is that SAS?", "no"),
    { requirement: "Mark one correct included angle.", checkLabel: "Included angle marked" },
  ),
  d(
    10083,
    { title: "3-4-5 distance path", layers: ["Δx=3", "Δy=4", "√25=5"], forbidden: "|Δx|+|Δy| as Euclidean" },
    { wrong: "Distance (0,0) to (3,4) as 7", right: "√(9+16)=5, not the taxicab 7." },
    "√(Δx²+Δy²) · live {live}",
    { wrong: "Forgetting the square root and leaving 25.", correction: "25 is the square. Distance is 5." },
    { setup: "(1,2) to (4,2).", result: "Δx=3, Δy=0, distance 3." },
    e("Distance from (0,0) to (5,12)?", "13"),
    "Root of nine plus sixteen equals five. Live {live}.",
    { keys: "drag and Shift", action: "Move an endpoint; Shift constrains to an axis." },
    { sentence: "Equal distances from a centre preview a diameter.", href: "/lessons/school/class-10/class-10-circle-proofs-angle-in-a-semicircle", label: "Angle in a Semicircle" },
    { seed: "including a vertical segment", items: ["(0,0) to (3,4)", "(1,2) to (4,2)", "(0,0) to (0,{n})"] },
    { trigger: "|Δx|+|Δy| selected as distance", message: "Hatch taxicab 7." },
    "√(3²+4²)=5 · live {live}",
    ["Compute live Δx and Δy.", "Square, add, root.", "Read {live}."],
    e("Is distance |Δx|+|Δy|?", "no"),
    { requirement: "Compute one 3-4-5 and one axis-aligned distance.", checkLabel: "Two distances computed" },
  ),
  d(
    10092,
    { title: "Thales right angle on a diameter", layers: ["diameter AB", "C on the circle", "90° square"], forbidden: "90° on a non-diameter chord" },
    { wrong: "Any wide inscribed angle stamped 90°", right: "The opposite side must be a diameter." },
    "∠ in a semicircle = 90° · live {live}",
    { wrong: "C at an endpoint of the diameter still gives a triangle.", correction: "That position is degenerate. C must be another point on the circle." },
    { setup: "Slide C on the circle while AB is a diameter.", result: "The right angle travels with C." },
    e("If AB is a diameter and C is on the circle, ∠ACB?", "90"),
    "Ninety degrees when the hypotenuse is a diameter. Live {live}.",
    { keys: "D and drag C", action: "Snap AB to a diameter, then move C." },
    { sentence: "A right angle teasers tan undefined at 90°.", href: "/lessons/school/class-11/class-11-trigonometry-domain-and-range-of-trigonometric-functions", label: "Trig Domain and Range" },
    { seed: "diameter / non-diameter / degenerate", items: ["AB diameter", "non-diameter chord", "C at endpoint {n}"] },
    { trigger: "90° stamp on a non-diameter chord", message: "Hatch: theorem badge off." },
    "∠ACB = 90° (AB diameter) · live {live}",
    ["Confirm AB is a diameter.", "Place C on the circle.", "Read the live right angle {live}."],
    e("Does a non-diameter chord guarantee 90°?", "no"),
    { requirement: "Toggle the diameter condition on and off.", checkLabel: "Diameter toggled" },
  ),
  d(
    10124,
    { title: "Six-function domain cards", layers: ["sin ℝ →[−1,1]", "cos ℝ →[−1,1]", "tan gaps at 90°+180°k"], forbidden: "tan domain = sin domain" },
    { wrong: "tan 90° given the value 1 or ∞ as if defined on ℝ", right: "tan is undefined where cos=0." },
    "sin range [−1,1] · tan undefined at 90° · live {live}",
    { wrong: "Every real is in the range of sin.", correction: "Range is [−1,1]. 2 is outside." },
    { setup: "Is 2 in the range of sin?", result: "No. Clip at 1." },
    e("Is tan 270° defined?", "no"),
    "Sine range minus one to one. Tan undefined at ninety. Live {live}.",
    { keys: "S C T", action: "Switch sine, cosine, or tangent cards." },
    { sentence: "Function language first, then a binomial expansion.", href: "/lessons/school/class-11/class-11-binomial-theorem-binomial-expansion", label: "Binomial Expansion" },
    { seed: "tan defined or not", items: ["tan 90°", "tan {n}°", "tan 0°"] },
    { trigger: "Tan domain includes 90°", message: "Hatch the forbidden vertical." },
    "sin: [−1,1] · tan 90° undefined · live {live}",
    ["Pick the live function.", "State domain and range.", "Read {live}."],
    e("Is every real number in the range of sin?", "no"),
    { requirement: "State sin range and one tan undefined angle.", checkLabel: "Range and gap stated" },
  ),
  d(
    10134,
    { title: "Pascal term builder", layers: ["C(4,k)", "a^{4−k}", "b^k"], forbidden: "(a+b)^n = a^n+b^n" },
    { wrong: "(a+b)² written a²+b²", right: "The middle 2*ab is required. C(2,1)=2." },
    "(a+b)^n = Σ C(n,k) a^{n−k} b^k · live {live}",
    { wrong: "Pascal row n=4 summed to 4.", correction: "1+4+6+4+1=16=2^4." },
    { setup: "C(4,2).", result: "6, the middle chip." },
    e("Expand (a+b)^3 first and last terms.", "a^3 and b^3", "a³ and b³"),
    "C four two is six. Live {live}.",
    { keys: "K", action: "Step the term index k." },
    { sentence: "A finite expansion, then one-sided limits.", href: "/lessons/school/class-12/class-12-formal-calculus-left-hand-and-right-hand-limits", label: "Left- and Right-Hand Limits" },
    { seed: "n=2,3,4", items: ["(a+b)^2", "(a+b)^3", "(a+b)^{n}"] },
    { trigger: "a^n+b^n offered as the expansion", message: "Hatch the missing middle terms." },
    "a^2+2ab+b^2 · C(4,2)=6 · live {live}",
    ["Write C(n,k) for the live n.", "Attach the powers of a and b.", "Read {live}."],
    e("Is (a+b)^2 equal to a^2+b^2?", "no"),
    { requirement: "Keep the middle term present.", checkLabel: "Middle term present" },
  ),
  d(
    10165,
    { title: "Two approaching arrows", layers: ["LHL", "a", "RHL"], forbidden: "one side reported as two-sided" },
    { wrong: "Right-hand 2 called the limit while left is 3", right: "Two-sided exists only when LHL=RHL and both are finite." },
    "LHL and RHL must agree · live {live}",
    { wrong: "A hole with both sides 2 has no two-sided limit because f(a) differs.", correction: "The two-sided limit ignores f(a). It is 2." },
    { setup: "LHL=2, RHL=2.", result: "Two-sided 2." },
    e("If LHL=5 and RHL=5, two-sided limit?", "5"),
    "Left two, right two, or DNE. Live {live}.",
    { keys: "two sliders", action: "Move left approach and right approach separately." },
    { sentence: "Continuity discipline becomes rewrite the whole integrand.", href: "/lessons/school/class-12/class-12-formal-calculus-integration-by-substitution", label: "Integration by Substitution" },
    { seed: "agree / jump / blow-up", items: ["sides {n}={n}", "2 vs 3 jump", "blow-up at a"] },
    { trigger: "Two-sided claim from one side", message: "Hatch the missing side." },
    "LHL=2, RHL=2 ⇒ 2 · live {live}",
    ["Read LHL.", "Read RHL.", "Say {live}."],
    e("Is a right-hand limit enough for the two-sided limit?", "no"),
    { requirement: "Mark one agree and one disagree case.", checkLabel: "Agree and disagree marked" },
  ),
  d(
    10180,
    { title: "Linked u and du", layers: ["u=x²", "du=2x dx", "cos u du"], forbidden: "keep dx after the switch" },
    { wrong: "u=x² with leftover dx", right: "du=2x dx. The 2x in the integrand is absorbed." },
    "u=x² , du=2x dx · live {live}",
    { wrong: "Skipping the differentiate-back check.", correction: "d/dx sin(x²)=2x cos(x²) confirms the antiderivative." },
    { setup: "∫ 2x cos(x²) dx.", result: "sin(x²)+C." },
    e("If u=3x+1, what is du?", "3 dx"),
    "u equals x squared, du equals two x dx. Live {live}.",
    { keys: "U / D", action: "Highlight u, then du." },
    { sentence: "A finished technique, then an LPP formulation.", href: "/lessons/school/class-12/class-12-linear-programming-formulating-linear-programming-problems", label: "Formulating LPP" },
    { seed: "u-subs", items: ["u=x^2", "u=3x+1", "u=sin x"] },
    { trigger: "u changed but dx kept", message: "Hatch leftover dx." },
    "du = 2x dx · ∫ 2x cos(x^2) dx = sin(x^2)+C · live {live}",
    ["Choose live u.", "Write du.", "Rewrite the integrand as {live}."],
    e("Can you keep dx after changing to u?", "no"),
    { requirement: "Differentiate-back check is green.", checkLabel: "Back-check green" },
  ),
  d(
    10200,
    { title: "Named variables then objective", layers: ["x,y chips", "max 3x+5y", "inequalities"], forbidden: "maximise with no objective" },
    { wrong: "A shaded region without x,y names", right: "Name the decision variables before the objective box unlocks." },
    "max 3x+5y s.t. live inequalities · {live}",
    { wrong: "Feasible region as any one constraint.", correction: "The region is the intersection of all constraints." },
    { setup: "2-product mix.", result: "Two decision variables." },
    e("If there is no objective, can you maximise?", "no"),
    "Two variables, linear objective, inequality constraints. Live {live}.",
    { keys: "Tab", action: "Move variable → objective → constraints." },
    { sentence: "A feasible region becomes a sample space.", href: "/lessons/school/class-12/class-12-probability-conditional-probability", label: "Conditional Probability" },
    { seed: "mix / diet / transport stems", items: ["2-product mix", "diet {n} foods", "transport routes"] },
    { trigger: "LPP missing x,y names", message: "Hatch the unnamed sliders." },
    "max 3x+5y s.t. the live inequalities · {live}",
    ["Name x and y.", "Write the live objective.", "Add at least one inequality: {live}."],
    e("Is the feasible region the set of points meeting all constraints?", "yes"),
    { requirement: "Fill variables, objective, and one constraint.", checkLabel: "Formulation complete" },
  ),
  d(
    10210,
    { title: "B-column as new total", layers: ["A∩B count", "B total", "P=n∩/nB"], forbidden: "P(A)/P(B) as the conditional" },
    { wrong: "P(A|B)=P(A)/P(B)", right: "Use the intersection. P(A|B)=P(A∩B)/P(B)." },
    "P(A|B)=0.1/0.4=0.25 · live {live}",
    { wrong: "Empty B still given a conditional.", correction: "If B is empty, P(A|B) is undefined." },
    { setup: "P(A∩B)=0.1, P(B)=0.4.", result: "0.25." },
    e("P(A∩B)=0.2, P(B)=0.8. P(A|B)?", "0.25", "1/4"),
    "One tenth over four tenths is one fourth. Live {live}.",
    { keys: "cell digits", action: "Edit the four table counts." },
    { sentence: "The B-column becomes evidence for Bayes.", href: "/lessons/school/class-12/class-12-probability-bayes-theorem", label: "Bayes' Theorem" },
    { seed: "tables including zero B", items: ["0.1 / 0.4", "2/8", "B total 0"] },
    { trigger: "P(A)/P(B) used as the conditional", message: "Hatch the missing intersection." },
    "P(A|B)=0.25 · live {live}",
    ["Read n(A∩B).", "Read n(B).", "Divide to {live}."],
    e("If B is empty, is P(A|B) defined?", "no"),
    { requirement: "Show one defined and one undefined B case.", checkLabel: "Defined and undefined B" },
  ),
  d(
    10214,
    { title: "Prior-likelihood-posterior bar", layers: ["prior", "likelihood", "posterior"], forbidden: "posterior = prior after data" },
    { wrong: "Leaving the posterior equal to the prior after data arrives", right: "Bayes must update. Ignored-data badge if it does not move." },
    "posterior ≠ prior after data · live {live}",
    { wrong: "P(A|B) always equal to P(B|A).", correction: "Those are inverse conditionals. Use a numeric swap card." },
    { setup: "Prior 0.2, data ignored.", result: "Posterior still 0.2 — that means the data was not used." },
    e("If prior=0.5 and data is used, must the posterior stay 0.5?", "no"),
    "Posterior is not the prior. Live {live}.",
    { keys: "slider and Enter", action: "Change the prior, then apply the live likelihood." },
    { sentence: "After inference, jump to experiment versus definition.", href: "/lessons/advanced-concepts/2001-partial-quotients", label: "Partial Quotients" },
    { seed: "prior/likelihood triples", items: ["prior 0.2", "prior 0.{n}", "swap P(A|B) vs P(B|A)"] },
    { trigger: "Posterior equals prior after non-trivial data", message: "Hatch ignored data." },
    "posterior = live update {live}",
    ["Set the live prior.", "Apply the likelihood.", "Read a new posterior {live}."],
    e("Is P(A|B) always equal to P(B|A)?", "no"),
    { requirement: "Make the posterior differ from the prior once.", checkLabel: "Posterior moved" },
  ),
  d(
    2001,
    { title: "Euclid floor boxes", layers: ["7/5", "a0=1", "remainder 2/5 → 5/2"], forbidden: "decimal digits as partial quotients" },
    { wrong: "1.4 digits 1,4 used as a_i", right: "Each quotient is a floor of a reciprocal remainder. a0=1." },
    "7/5 = [1; 2, 2] · live {live}",
    { wrong: "A convergent list treated as a finished proof of uniqueness.", correction: "This page produces quotients. Convergents are the next lesson." },
    { setup: "Reciprocal of remainder 2/5.", result: "5/2." },
    e("First partial quotient of 13/8?", "1"),
    "First quotient one, not the decimal digit four. Live {live}.",
    { keys: "N / D", action: "Edit numerator and denominator." },
    { sentence: "This is not a proof of all n — that ethic goes to Collatz.", href: "/lessons/advanced-concepts/2006-collatz-conjecture", label: "Collatz Conjecture" },
    { seed: "7/5, 22/7, 13/8", items: ["7/5", "22/7", "13/{n}"] },
    { trigger: "Quotient list copied from decimal digits", message: "Hatch the decimal decoy." },
    "7/5 = [1; 2, 2] · live {live}",
    ["Floor the live ratio.", "Reciprocate the remainder.", "Read {live}."],
    e("Are decimal digits the partial quotients?", "no"),
    { requirement: "Complete one remainder-reciprocal step.", checkLabel: "Remainder flipped" },
  ),
  d(
    2006,
    { title: "Hailstone even/odd colouring", layers: ["even n/2", "odd 3n+1", "path toward 1"], forbidden: "QED on one orbit" },
    { wrong: "A path to 1 stamped theorem", right: "That is evidence for this n, not a proof for every n." },
    "6→3→10→5→16→… · live {live}",
    { wrong: "3n−1 used as if it were Collatz.", correction: "The rule is a definition: even n/2, odd 3n+1." },
    { setup: "Next after 5.", result: "16, then 8,4,2,1." },
    e("Next Collatz term after 10?", "5"),
    "Six is even, next is three. Live {live}.",
    { keys: "N and Space", action: "Type a start, then apply one step." },
    { sentence: "Experiment versus proof unlocks an interval about a sample.", href: "/lessons/advanced-concepts/2011-confidence-intervals", label: "Confidence Intervals" },
    { seed: "6, 7, 27", items: ["start 6", "start 7", "start 27 long"] },
    { trigger: "QED on a single orbit", message: "Hatch the theorem stamp." },
    "6,3,10,5,16 · live {live}",
    ["Apply the live parity rule.", "Write the next term.", "Keep the prefix {live}."],
    e("Does a path to 1 prove the conjecture?", "no"),
    { requirement: "Take one even step and one odd step.", checkLabel: "Even and odd steps" },
  ),
  d(
    2011,
    { title: "x̄ ± ME on a line", layers: ["x̄", "left x̄−ME", "right x̄+ME"], forbidden: "95% chance μ is in this interval after data" },
    { wrong: "This interval contains μ with probability 0.95 after seeing the data", right: "95% is about the method across samples. This interval always contains x̄." },
    "10 ± 2 = (8, 12) · live {live}",
    { wrong: "A wider ME makes the claim stronger.", correction: "Wider is less precise. Strength and width trade." },
    { setup: "x̄=10, ME=2.", result: "Upper bound 12. The interval contains 10 by construction." },
    e("If x̄=7 and ME=3, lower bound?", "4"),
    "Ten plus or minus two, twelve and eight. Live {live}.",
    { keys: "[ ]", action: "Change ME by 1." },
    { sentence: "A numeric interval without a unique curve teasers a slope field.", href: "/lessons/advanced-concepts/2016-slope-fields", label: "Slope Fields" },
    { seed: "(x̄, ME) plus a prove-μ no", items: ["10±2", "10±{n}", "does this prove μ inside? no"] },
    { trigger: "95% chance μ is in this interval after data", message: "Hatch the inverted probability." },
    "10 ± 2 = (8, 12) · live {live}",
    ["Place live x̄.", "Mark ±ME.", "Read {live}, still containing x̄."],
    e("Does one interval prove μ is inside it?", "no"),
    { requirement: "Confirm the interval contains x̄ by construction.", checkLabel: "Contains x̄" },
  ),
  d(
    2016,
    { title: "Direction ticks plus one IVP", layers: ["field y'=x", "point (x0,y0)", "Euler polyline"], forbidden: "field claimed as the unique solution" },
    { wrong: "The slope field is already one curve", right: "The field is a direction map. An IVP picks one curve." },
    "at x=2, slope=2 · Euler y1=y0+hf · live {live}",
    { wrong: "Two initial points must share one solution.", correction: "Two points make two curves in the same field." },
    { setup: "y0=1, h=1, f=2.", result: "y1=3." },
    e("If dy/dx=y and y=2, what slope is drawn?", "2"),
    "Slope two at x=2. The field is not one curve. Live {live}.",
    { keys: "click and H", action: "Drop an IVP, then change the Euler step." },
    { sentence: "Named special functions come after fields.", href: "/lessons/advanced-concepts/2024-zeta-function", label: "Zeta Function" },
    { seed: "y'=x / y'=y / y'=1", items: ["y'=x", "y'=y", "y'=1 Euler {n}"] },
    { trigger: "Single curve claimed without an initial point", message: "Hatch: no point, no curve." },
    "y1 = 1 + 1·2 = 3 · live {live}",
    ["Read the live slope tick.", "Drop an IVP.", "Euler-step to {live}."],
    e("Euler step: y0=1, h=1, f=2, y1?", "3"),
    { requirement: "Draw one IVP curve.", checkLabel: "IVP curve drawn" },
  ),
  d(
    2024,
    { title: "Partial sums versus Euler product", layers: ["1/n^s bars", "prime factors", "ζ(s) for s>1"], forbidden: "1+2+3+… as ordinary ζ(−1)" },
    { wrong: "ζ(−1)=−1/12 treated as 1+2+3+… converging", right: "Negative arguments use analytic continuation. The s>1 series is a different object." },
    "partial sum of 1/n^s · live {live}",
    { wrong: "ζ(2) ≤ 1 because the first term is 1.", correction: "Further positive terms make ζ(2)>1, heading to π²/6." },
    { setup: "Does the series for ζ(2) converge?", result: "Yes, for s>1." },
    e("Is ζ(3) greater than 1?", "yes"),
    "Partial sum still below zeta of two. Live {live}.",
    { keys: "S", action: "Step s among 2, 3, 4, and custom." },
    { sentence: "Acknowledge what continuation is not before leaving the advanced list.", href: "/lessons/advanced-concepts", label: "Advanced lessons" },
    { seed: "s values plus illegal 1+2+3", items: ["s=2", "s=3", "1+2+3 decoy"] },
    { trigger: "Ordinary-sum claim for 1+2+3+…", message: "Hatch: that is not the s>1 series." },
    "ζ(2) > 1 · series converges · live {live}",
    ["Add the next 1/n^s term.", "Compare with the Euler product.", "Read {live}."],
    e("Does ζ(-1)=-1/12 mean 1+2+3+… converges ordinarily?", "no"),
    { requirement: "Acknowledge the continuation warning before leaving.", checkLabel: "Continuation warning read" },
  ),
]);
