import type { StrengthenedLesson } from "./strengthenedLessonSchema";

type FunctionChallenge = {
  prompt: string;
  expected: string;
  hint: string;
  kind: "numeric" | "keywords" | "interaction";
  factoryId: string;
};

type FunctionSeed = {
  id: number;
  title: string;
  slug: string;
  definition: string;
  intro: string;
  basicIdea: string;
  how: string;
  why: string;
  vocabulary: [string, string][];
  facts: string[];
  restrictions: string[];
  representation: StrengthenedLesson["representations"][number]["type"];
  worked: [string, string[], string];
  examples: [string, string][];
  misconception: [string, string, string];
  practiceAnswers: [string, string, string, string, string];
  challenge: FunctionChallenge;
  formula: StrengthenedLesson["formulas"][number];
};

const seeds: FunctionSeed[] = [
  fn(129, "Function Concept", "function-concept", "A function assigns each input exactly one output.", "A function is a rule from inputs to outputs. It helps describe change in graphs, tables, and formulas. We use functions for prices, travel, and machine rules.", "In a function, one input cannot have two different outputs. The rule f(x)=2x+1 gives one answer for each x. If x=3, the output is 7. A vending machine code, a taxi fare rule, and a temperature conversion all act like functions. This works because a clear rule must give a dependable output. A common mistake is allowing one input to point to two outputs.", "Choose an input. Apply the rule once. Check that the input gives only one output.", "Functions are reliable because each allowed input has a single assigned output.", [["Input", "The value put into a function."], ["Output", "The value returned by a function."]], ["Each input has exactly one output.", "Different inputs may share the same output."], ["Inputs must be in the domain."], "function_graph", ["For f(x)=2x+1, find f(3).", ["Replace x with 3.", "Compute 2 x 3 + 1.", "The output is 7."], "7"], [["Taxi fare", "Distance gives one fare."], ["Vending code", "One code gives one item."], ["Temperature conversion", "One Celsius value gives one Fahrenheit value."]], ["ONE_INPUT_TWO_OUTPUTS", "Calling a relation a function when one input has two outputs.", "A function gives exactly one output per input."], ["one output", "input", "7", "One input had two outputs.", "taxi fare"], "For f(x)=2x+1, what is f(3)?", "7", "Substitute x=3.", "numeric", "graph.function-concept", "Function rule", "f: input -> output"),
  fn(130, "Domain and Range", "domain-and-range", "The domain is the set of allowed inputs, and the range is the set of possible outputs.", "Domain and range tell where a function can start and end. They matter in graphs and real situations. They stop us from using impossible values.", "For y=sqrt(x), x cannot be negative in real-number graphing, so the domain is x >= 0. The outputs are also y >= 0. Real examples include time, distance, and item counts, which often cannot be negative. This works because the rule may break or stop making sense outside allowed inputs. A common mistake is reading range from the x-axis instead of the y-axis.", "Find allowed x-values for the domain. Then find possible y-values for the range.", "The formula and context decide which inputs and outputs are possible.", [["Domain", "Allowed input values."], ["Range", "Possible output values."]], ["Domain uses x-values.", "Range uses y-values."], ["Respect roots, denominators, and context limits."], "function_graph", ["Find domain and range of y=sqrt(x).", ["The square root needs x >= 0.", "Square-root outputs are not negative.", "So domain and range are both >= 0."], "domain x>=0, range y>=0"], [["Trip time", "Negative time is not allowed."], ["Height", "A ball height may have a limited range."], ["Tickets", "Ticket count must be whole and non-negative."]], ["RANGE_FROM_X_AXIS", "Reading range from horizontal values.", "Range is the set of y-values."], ["x>=0,y>=0", "domain x", "range y", "They used the wrong axis.", "time"], "For y=sqrt(x), is x=-1 in the real domain? Enter yes or no.", "no", "Real square roots need x >= 0.", "keywords", "graph.domain-and-range", "Domain and range", "domain = allowed x, range = possible y"),
  fn(131, "Function Notation", "function-notation", "Function notation writes a rule as f(x), meaning the output from input x.", "Function notation is a short way to name rules. It helps compare many functions. We use it in tables, graphs, and formulas.", "The notation f(4) means use input 4 in the function f. If f(x)=3x-2, then f(4)=10. The letter f is a name, not multiplication. This appears in graph labels, spreadsheet rules, and science formulas. It works because the notation tells which rule and which input to use. A common mistake is reading f(x) as f times x.", "Read the function name. Replace x by the given input. Simplify the output.", "Notation separates the rule name from the input value.", [["Function notation", "A way to write rule and input together."], ["Evaluate", "Find the output for an input."]], ["f(3) means input 3.", "f(x) is not f multiplied by x."], ["Use the named function if several rules are given."], "table", ["If f(x)=3x-2, find f(4).", ["Replace x with 4.", "Compute 3 x 4 - 2.", "The result is 10."], "10"], [["Graph labels", "f(x) names the plotted rule."], ["Spreadsheets", "A named formula takes an input."], ["Science", "T(t) can mean temperature at time t."]], ["F_TIMES_X", "Treating f(x) as f multiplied by x.", "f is the function name."], ["10", "input 4", "function name", "They treated f as a number.", "temperature"], "If f(x)=3x-2, what is f(4)?", "10", "Replace x by 4.", "numeric", "graph.function-notation", "Evaluation", "f(a) means use input a"),
  fn(132, "Vertical-Line Test", "vertical-line-test", "The vertical-line test checks whether a graph gives one y-value for each x-value.", "The vertical-line test tells whether a graph is a function. It is important when reading graphs. It prevents one input from having two outputs.", "If any vertical line crosses a graph more than once, the graph is not a function. A circle fails this test because some x-values have two y-values. A normal line passes because each x gives one y. We see this when checking paths, data plots, and relation graphs. It works because vertical lines hold x constant. A common mistake is using a horizontal line for the function test.", "Imagine vertical lines moving across the graph. If one line hits twice, it is not a function.", "A vertical line fixes one input x and counts how many outputs appear.", [["Vertical line", "A line straight up and down with one x-value."], ["Relation", "A set of paired values."]], ["One hit or zero hits passes.", "Two hits for one x fails."], ["Use vertical lines, not horizontal lines, for this test."], "coordinate_graph", ["Does a circle pass the vertical-line test?", ["Draw a vertical line through the circle.", "It crosses twice for some x-values.", "So the circle is not a function of x."], "No"], [["Map paths", "One x-position may have two heights."], ["Data plots", "Repeated x-values can break a function."], ["Graphs", "A sideways curve can fail."]], ["USED_HORIZONTAL_TEST", "Using a horizontal line to test if it is a function.", "Use vertical lines for functions of x."], ["no", "vertical line", "circle fails", "They used a horizontal line.", "graph"], "Does a circle pass the vertical-line test? Enter yes or no.", "no", "Some vertical lines hit a circle twice.", "keywords", "graph.vertical-line-test", "Function test", "one x -> one y"),
  fn(133, "Linear Functions", "linear-functions", "A linear function has a constant rate of change and graphs as a straight line.", "Linear functions show steady change. They are used for fares, wages, and distance at constant speed. Their graph is easy to predict.", "The function f(x)=2x+3 rises by 2 whenever x increases by 1. The number 2 is the slope, and 3 is the y-intercept. Taxi fares, hourly pay, and water filling at a steady rate can be linear. This works because the same input change always makes the same output change. A common mistake is thinking every straight line is proportional. A line is proportional only when it passes through the origin.", "Read the slope and intercept. Use slope for change. Use the intercept as the starting value.", "Constant rate creates equal steps on the graph.", [["Slope", "Change in y for one unit change in x."], ["Intercept", "Where the graph crosses an axis."]], ["Linear graphs are straight.", "Proportional lines pass through the origin."], ["Vertical lines are not functions of x."], "function_graph", ["For f(x)=2x+3, find f(4).", ["Multiply 2 by 4.", "Add 3.", "The output is 11."], "11"], [["Taxi fare", "Base fee plus per-km cost."], ["Hourly pay", "Pay grows by the same amount each hour."], ["Water tank", "Level can rise steadily."]], ["ALL_LINES_PROPORTIONAL", "Calling any line proportional.", "A proportional line must pass through (0,0)."], ["11", "slope 2", "intercept 3", "They ignored intercept.", "fare"], "For f(x)=2x+3, what is f(4)?", "11", "Use 2*4+3.", "numeric", "graph.linear-functions", "Linear form", "f(x)=mx+b"),
  fn(134, "Quadratic Functions", "quadratic-functions", "A quadratic function has highest power 2 and graphs as a parabola.", "Quadratic functions show curved change. They are used for area and thrown objects. Their graph can turn at a vertex.", "The function f(x)=x^2 opens upward and has vertex (0,0). A shifted function like (x-2)^2+1 has vertex (2,1). Quadratics appear in ball height, area of squares, and parabolic reflectors. This works because squaring makes outputs grow faster as x moves away from the vertex. A common mistake is reading the vertex from expanded form without completing the square.", "Find the squared term. Identify opening direction and vertex form if possible. Use symmetry to read matching points.", "The x squared term creates a U-shaped or upside-down U-shaped graph.", [["Parabola", "The graph of a quadratic function."], ["Vertex", "The turning point of a parabola."]], ["Positive leading coefficient opens upward.", "The axis of symmetry passes through the vertex."], ["A quadratic needs a non-zero x^2 coefficient."], "function_graph", ["Find the vertex of f(x)=(x-2)^2+1.", ["Vertex form is (x-h)^2+k.", "Here h=2 and k=1.", "The vertex is (2,1)."], "(2,1)"], [["Projectile motion", "Height can form a parabola."], ["Area", "Square area uses side squared."], ["Reflectors", "Parabolic shapes focus signals."]], ["VERTEX_FROM_EXPANDED_FORM", "Guessing the vertex from coefficients.", "Use vertex form or complete the square."], ["(2,1)", "vertex", "opens up", "They guessed the vertex.", "height"], "What is the vertex of f(x)=(x-2)^2+1?", "(2,1)", "Use vertex form.", "keywords", "graph.quadratic-functions", "Vertex form", "f(x)=a(x-h)^2+k"),
  fn(135, "Cubic Functions", "cubic-functions", "A cubic function has highest power 3 and often makes an S-shaped graph.", "Cubic functions model change that can bend twice. They appear in volume, motion, and curve design. They can have one, two, or three real roots.", "The parent cubic f(x)=x^3 goes down left and up right. It passes through the origin and is symmetric about the origin. Cubics appear in cube volume, smooth animation curves, and some motion models. This works because positive and negative inputs keep their sign when cubed. A common mistake is expecting every cubic to look like a parabola. Cubics do not have the same U-shape.", "Check the highest power. Read end behaviour. Find intercepts or turning points if needed.", "The odd power makes opposite signs on opposite sides of zero.", [["Cubic", "A function with highest power 3."], ["End behaviour", "What the graph does far left and far right."]], ["x^3 is odd and passes through (0,0).", "A cubic can have up to three real roots."], ["The leading coefficient cannot be zero."], "function_graph", ["What is f(-2) for f(x)=x^3?", ["Cube -2.", "(-2)^3 = -8.", "The output is -8."], "-8"], [["Volume", "Cube volume is side^3."], ["Animation", "Smooth curves can use cubic easing."], ["Motion", "Position models may include cubic terms."]], ["CUBIC_AS_PARABOLA", "Drawing every cubic as a U-shape.", "Cubic parent graphs are S-shaped."], ["-8", "S shape", "origin", "They drew a parabola.", "volume"], "For f(x)=x^3, what is f(-2)?", "-8", "Cube the input.", "numeric", "graph.cubic-functions", "Cubic parent", "f(x)=x^3"),
  fn(136, "Higher-Degree Polynomials", "higher-degree-polynomials", "A higher-degree polynomial has degree 4 or more.", "Higher-degree polynomials can make several bends. They are useful in curve fitting and design. They help model complex but smooth patterns.", "A polynomial of degree 4 can have up to 4 real roots and up to 3 turning points. Its end behaviour depends on degree and leading coefficient. These graphs appear in data fitting, computer graphics, and engineering curves. This works because each power term changes the shape in a predictable way. A common mistake is thinking degree equals the exact number of roots. It is only the maximum number of real roots.", "Find the degree and leading coefficient. Use them for end behaviour. Use roots and turning points to sketch.", "Degree limits how many roots and turns a polynomial can have.", [["Degree", "The highest power with non-zero coefficient."], ["Leading coefficient", "The coefficient of the highest-power term."]], ["Degree n gives at most n real roots.", "Degree n gives at most n-1 turning points."], ["Some roots may be complex or repeated."], "function_graph", ["What is the maximum number of real roots for degree 5?", ["A degree n polynomial has at most n real roots.", "Here n=5.", "The maximum is 5."], "5"], [["Data fitting", "Curves can pass near many points."], ["Design", "Smooth shapes can use polynomial pieces."], ["Engineering", "Complex response curves may be polynomial."]], ["DEGREE_EQUALS_ROOTS", "Saying degree 5 must have 5 real roots.", "Degree gives a maximum, not a promise."], ["5", "maximum", "degree", "They treated maximum as exact.", "curve fitting"], "A degree 4 polynomial has at most how many real roots?", "4", "Degree gives the maximum.", "numeric", "graph.higher-degree-polynomials", "Root limit", "degree n -> at most n real roots"),
  fn(137, "Reciprocal Functions", "reciprocal-functions", "A reciprocal function has a variable in the denominator, such as f(x)=1/x.", "Reciprocal functions show inverse relationships. They are used in speed-time links and sharing problems. Their graph has asymptotes.", "For f(x)=1/x, x cannot be 0. As x gets large, 1/x gets close to 0. The graph has two branches and does not touch the axes. We see this in time for a fixed distance, sharing a fixed amount, and lens formulas. This works because dividing by larger values makes smaller outputs. A common mistake is putting x=0 into the function.", "State the excluded input. Plot points on both sides of zero. Notice the vertical and horizontal asymptotes.", "Division by zero is undefined, so the graph breaks at x=0.", [["Reciprocal", "One divided by a quantity."], ["Asymptote", "A line the graph approaches but does not touch."]], ["x=0 is not in the domain of 1/x.", "The axes are asymptotes for y=1/x."], ["The denominator cannot be zero."], "function_graph", ["Find f(2) for f(x)=1/x.", ["Substitute x=2.", "Compute 1/2.", "The output is 0.5."], "0.5"], [["Speed and time", "Fixed distance gives time = distance/speed."], ["Sharing", "Each share shrinks as people increase."], ["Optics", "Lens formulas use reciprocals."]], ["USED_ZERO_INPUT", "Trying to calculate 1/0.", "Zero is excluded from the domain."], ["0.5", "x!=0", "asymptote", "They used zero.", "sharing"], "For f(x)=1/x, is x=0 allowed? Enter yes or no.", "no", "The denominator cannot be zero.", "keywords", "graph.reciprocal-functions", "Reciprocal rule", "f(x)=1/x, x!=0"),
  fn(138, "Rational Functions", "rational-functions", "A rational function is a ratio of two polynomial functions.", "Rational functions combine polynomial expressions in a fraction. They are useful for rates, proportions, and graph behaviour near excluded values. Restrictions matter.", "The function f(x)=(x+1)/(x-2) is rational. The denominator cannot be zero, so x cannot be 2. Rational graphs may have vertical asymptotes or holes. They appear in average cost, speed formulas, and inverse variation models. This works because division by a changing expression creates different behaviour near zeros of the denominator. A common mistake is cancelling factors and forgetting the original restriction.", "Factor numerator and denominator. State excluded values. Simplify if possible. Keep restrictions.", "Denominator zeros control breaks in the graph.", [["Rational function", "A quotient of polynomial functions."], ["Hole", "A missing point after a removable factor cancels."]], ["Denominator zeros are excluded.", "Cancelled denominator factors still create restrictions."], ["Original denominator must be non-zero."], "function_graph", ["Find the excluded value of (x+1)/(x-2).", ["Set x-2=0.", "Solve x=2.", "So x=2 is excluded."], "2"], [["Average cost", "Cost per item can be a rational function."], ["Speed", "Time can appear in a denominator."], ["Graph analysis", "Asymptotes show breaks."]], ["FORGOT_ORIGINAL_RESTRICTION", "Cancelling and allowing a forbidden x-value.", "Keep every original denominator restriction."], ["2", "denominator", "restriction", "They forgot x=2.", "average cost"], "What value is excluded from (x+1)/(x-2)?", "2", "Set denominator to zero.", "numeric", "graph.rational-functions", "Restriction", "denominator != 0"),
  fn(139, "Square-Root Functions", "square-root-functions", "A square-root function contains the variable inside a square root.", "Square-root functions model slow growth from a starting point. They are used in geometry and distance formulas. Their domain is limited in real numbers.", "The parent function f(x)=sqrt(x) starts at (0,0) and increases slowly. In real numbers, x must be at least 0. The graph appears in right-triangle distances, physics formulas, and designs with root scaling. This works because square roots undo squaring and return non-negative outputs. A common mistake is drawing the graph to the left of zero for sqrt(x).", "Find where the radicand is non-negative. Start the graph at that boundary. Plot outputs.", "Even roots require non-negative radicands in real-number graphing.", [["Radicand", "The expression inside a root."], ["Endpoint", "Where a limited graph begins."]], ["sqrt(x) has domain x>=0.", "sqrt(x) outputs are non-negative."], ["The radicand must be non-negative."], "function_graph", ["Find f(9) for f(x)=sqrt(x).", ["Substitute 9.", "sqrt(9)=3.", "The output is 3."], "3"], [["Distance", "Roots appear in distance formulas."], ["Design", "Root scaling grows slowly."], ["Physics", "Some formulas use square roots."]], ["NEGATIVE_ROOT_DOMAIN", "Using x=-1 in sqrt(x).", "For real outputs, x must be >=0."], ["3", "x>=0", "endpoint", "They used negative x.", "distance"], "For f(x)=sqrt(x), what is f(9)?", "3", "sqrt(9)=3.", "numeric", "graph.square-root-functions", "Square-root parent", "f(x)=sqrt(x), x>=0"),
  fn(140, "Cube-Root Functions", "cube-root-functions", "A cube-root function contains the variable inside a cube root.", "Cube-root functions undo cubing. They are useful for volume, scaling, and inverse cubic relationships. Unlike square roots, they allow negative inputs.", "The parent function f(x)=cuberoot(x) passes through the origin and is defined for all real x. For x=-8, the output is -2 because (-2)^3=-8. This appears when finding a cube side from volume, resizing models, and inverse volume formulas. It works because every real number has a real cube root. A common mistake is excluding negative inputs like in square-root functions.", "Use the number whose cube gives the input. Include negative inputs. Plot the smooth increasing curve.", "Cubing keeps sign, so cube roots can be negative.", [["Cube root", "A number that cubes to the input."], ["Inverse", "An operation that undoes another."]], ["cuberoot(-8)=-2.", "The real domain is all real numbers."], ["Do not apply square-root domain rules here."], "function_graph", ["Find cuberoot(-8).", ["Ask what number cubed is -8.", "(-2)^3=-8.", "So the cube root is -2."], "-2"], [["Volume", "Find cube side from volume."], ["Scaling", "3D scale uses cube roots."], ["Models", "Inverse cubic rules can use cube roots."]], ["EXCLUDED_NEGATIVE_CUBE_ROOT", "Saying cuberoot(-8) is not real.", "Negative inputs are allowed for cube roots."], ["-2", "all real x", "negative allowed", "They used square-root rules.", "volume"], "What is cuberoot(-8)?", "-2", "(-2)^3=-8.", "numeric", "graph.cube-root-functions", "Cube-root parent", "f(x)=cuberoot(x)"),
  fn(141, "Absolute-Value Functions", "absolute-value-functions", "An absolute-value function uses distance from zero or from a centre.", "Absolute-value functions make V-shaped graphs. They are useful for distance, error, and tolerance. They ignore direction but keep size.", "The parent function f(x)=|x| has vertex (0,0). It outputs 3 for both x=3 and x=-3. This appears in measurement error, distance from a target, and temperature difference. It works because absolute value measures distance, which is never negative. A common mistake is thinking |x| equals x for negative x. For x=-4, |x|=4.", "Find the centre inside the absolute value. Plot equal distances on both sides. Output is non-negative before vertical shifts.", "Distance from a centre creates matching left and right arms.", [["Absolute value", "Distance from zero."], ["Vertex", "The corner point of the V graph."]], ["|x| is never negative.", "|-a|=a for positive a."], ["Vertical shifts can move outputs below zero."], "function_graph", ["Find |-4|.", ["Distance from 0 to -4 is 4.", "Absolute value ignores direction.", "The output is 4."], "4"], [["Tolerance", "Error size ignores direction."], ["Distance", "Left or right distance can match."], ["Temperature", "Difference from target uses absolute value."]], ["ABS_NEGATIVE_STAYS_NEGATIVE", "Saying |-4|=-4.", "Absolute value is distance, so it is 4."], ["4", "distance", "vertex", "They kept the negative sign.", "tolerance"], "What is |-4|?", "4", "Distance is non-negative.", "numeric", "graph.absolute-value-functions", "Absolute value", "|x| = distance from 0"),
  fn(142, "Exponential Functions", "exponential-functions", "An exponential function has the variable in the exponent.", "Exponential functions model repeated multiplication. They are used for growth, decay, interest, and bacteria. Small input changes can make large output changes.", "The function f(x)=2^x doubles whenever x increases by 1. f(3)=8. Exponential growth appears in compound interest, population growth, and viral sharing. Exponential decay appears in half-life and cooling. This works because each step multiplies by the same factor. A common mistake is treating exponential growth as adding a fixed amount.", "Find the starting value and multiplier. Multiply by the same factor for each equal input step.", "A constant ratio between outputs creates exponential change.", [["Base", "The repeated multiplier."], ["Growth factor", "The number multiplied each step."]], ["2^x doubles each step.", "Exponential functions have constant ratios, not constant differences."], ["Standard real exponential bases are positive and not 1."], "function_graph", ["Find 2^3.", ["Start with base 2.", "Multiply 2 three times.", "The value is 8."], "8"], [["Interest", "Money compounds by a percent."], ["Bacteria", "Cells may double repeatedly."], ["Half-life", "Amount halves repeatedly."]], ["ADDED_NOT_MULTIPLIED", "Adding 2 each step for 2^x.", "Exponential change multiplies by a factor."], ["8", "constant ratio", "doubling", "They added instead of multiplied.", "interest"], "What is 2^3?", "8", "2 x 2 x 2.", "numeric", "graph.exponential-functions", "Exponential parent", "f(x)=a*b^x"),
  fn(143, "Logarithmic Functions", "logarithmic-functions", "A logarithmic function is the inverse of an exponential function.", "Logarithmic functions answer power questions. They are used for sound, pH, earthquakes, and growth scales. Their input must be positive.", "The function f(x)=log2(x) asks what power of 2 gives x. Since 2^3=8, log2(8)=3. Log graphs increase slowly and have x>0 as their domain. This appears in decibels, pH, earthquake magnitude, and data scales. It works because logarithms undo exponents. A common mistake is trying to take a logarithm of zero or a negative number in real-number graphing.", "Check the input is positive. Rewrite as an exponent question. Solve for the power.", "Only positive real inputs can be reached by positive exponential bases.", [["Logarithm", "The power needed to make a number."], ["Inverse function", "A function that undoes another function."]], ["log_b(b^x)=x.", "The input of a real logarithm must be positive."], ["Base must be positive and not 1; input must be positive."], "function_graph", ["Find log2(8).", ["Ask 2 to what power equals 8.", "2^3=8.", "So log2(8)=3."], "3"], [["Sound", "Decibels use logs."], ["pH", "Acidity uses a log scale."], ["Earthquakes", "Magnitude scales are logarithmic."]], ["LOG_ZERO_INPUT", "Using log(0) as a real number.", "Real logarithm inputs must be positive."], ["3", "positive input", "inverse", "They used zero input.", "sound"], "What is log2(8)?", "3", "2^3=8.", "numeric", "graph.logarithmic-functions", "Log definition", "log_b(x)=y means b^y=x"),
  fn(144, "Trigonometric Functions", "trigonometric-functions", "Trigonometric functions connect angles with ratios or unit-circle coordinates.", "Trigonometric functions model repeating angle patterns. They are used for waves, rotations, triangles, and navigation. Their graphs repeat.", "The sine function gives the y-coordinate on the unit circle. sin(30 degrees)=1/2. Sine and cosine repeat every 360 degrees. We see trig functions in sound waves, tides, wheel motion, and surveying. This works because rotating around a circle returns to the same positions. A common mistake is mixing degrees and radians without checking the mode.", "Choose angle units. Use the unit circle or triangle ratio. Track the period of the graph.", "Circular motion repeats, so trigonometric values repeat.", [["Sine", "The unit-circle y-coordinate."], ["Period", "The repeat length of a function."]], ["Sine and cosine repeat every 360 degrees or 2pi radians.", "Tangent is undefined when cosine is zero."], ["State whether angles use degrees or radians."], "unit_circle", ["Find sin(30 degrees).", ["On the unit circle, 30 degrees has y-coordinate 1/2.", "So sine is 1/2.", "Decimal form is 0.5."], "0.5"], [["Waves", "Sound and light repeat."], ["Wheels", "Height repeats as a wheel turns."], ["Surveying", "Angles help find heights."]], ["MIXED_ANGLE_UNITS", "Using degree values in radian mode.", "Check the angle unit before calculating."], ["0.5", "period", "degrees", "They mixed units.", "waves"], "What is sin(30 degrees)?", "0.5", "Use the unit circle.", "numeric", "graph.trigonometric-functions", "Sine parent", "sin(theta) = y-coordinate"),
  fn(145, "Hyperbolic Functions", "hyperbolic-functions", "Hyperbolic functions are functions like sinh and cosh linked to exponentials and hyperbolas.", "Hyperbolic functions describe smooth growth and hanging-chain shapes. They appear in engineering and advanced modelling. They are different from circular trigonometric functions.", "The function cosh(x) is shaped like a hanging cable curve called a catenary. It can be written using exponentials: cosh(x)=(e^x+e^-x)/2. These functions appear in bridges, cables, and some physics models. They work because they combine exponential growth and decay. A common mistake is treating cosh like cos. Hyperbolic functions are not periodic like sine and cosine.", "Recognise sinh, cosh, and tanh. Use their exponential definitions. Compare shape and symmetry.", "Exponential combinations create hyperbola-related identities and graph shapes.", [["Cosh", "An even hyperbolic function."], ["Catenary", "The curve of a hanging chain."]], ["cosh(x) is even.", "cosh(x) is not periodic."], ["Do not apply circular trig periods to hyperbolic functions."], "function_graph", ["Is cosh(x) periodic like cosine?", ["Cosine repeats.", "cosh(x) grows and does not repeat.", "So it is not periodic."], "No"], [["Bridges", "Hanging cables can follow catenaries."], ["Physics", "Some models use hyperbolic functions."], ["Engineering", "Smooth growth and decay combine."]], ["COSH_AS_COS", "Assuming cosh repeats like cos.", "cosh is hyperbolic and not periodic."], ["no", "not periodic", "catenary", "They treated cosh as cos.", "cable"], "Is cosh(x) periodic like cosine? Enter yes or no.", "no", "cosh does not repeat.", "keywords", "graph.hyperbolic-functions", "Cosh definition", "cosh(x)=(e^x+e^-x)/2"),
  fn(146, "Floor Function", "floor-function", "The floor function gives the greatest integer less than or equal to the input.", "The floor function rounds down to an integer. It is used in pricing, grouping, clocks, and computer programs. Its graph looks like steps.", "floor(3.8)=3, and floor(-1.2)=-2 because -2 is the greatest integer not above -1.2. Floor functions appear when counting full boxes, completed hours, and page groups. This works because the output must be an integer that does not exceed the input. A common mistake is rounding negative numbers toward zero.", "Find the nearest integer at or below the input. For negatives, move left on the number line if needed.", "The greatest allowed integer must be less than or equal to the input.", [["Floor", "Greatest integer less than or equal to x."], ["Step graph", "A graph made of flat pieces."]], ["floor(3.8)=3.", "floor(-1.2)=-2."], ["The output is always an integer."], "function_graph", ["Find floor(-1.2).", ["Integers below or equal to -1.2 include -2 and smaller.", "The greatest one is -2.", "So floor(-1.2)=-2."], "-2"], [["Boxes", "Only full boxes count."], ["Parking hours", "Completed hours may use floor."], ["Programming", "Array groups can use integer parts."]], ["NEGATIVE_FLOOR_TOWARD_ZERO", "Saying floor(-1.2)=-1.", "Floor goes down, so it is -2."], ["-2", "round down", "integer", "They rounded toward zero.", "boxes"], "What is floor(-1.2)?", "-2", "Choose the greatest integer not above it.", "numeric", "graph.floor-function", "Floor rule", "floor(x)<=x"),
  fn(147, "Ceiling Function", "ceiling-function", "The ceiling function gives the least integer greater than or equal to the input.", "The ceiling function rounds up to an integer. It is useful for boxes, seats, pages, and batches. It answers how many whole groups are needed.", "ceiling(3.2)=4 because 4 is the least integer not below 3.2. ceiling(-1.2)=-1 because -1 is greater than -1.2. We use ceiling when 23 students need buses of 10 seats, so 3 buses are needed. It works because partial groups still require one whole group. A common mistake is using ordinary rounding instead of always rounding up.", "Find the nearest integer at or above the input. Use one more group when any remainder exists.", "The least allowed integer must be greater than or equal to the input.", [["Ceiling", "Least integer greater than or equal to x."], ["Batch", "A whole group needed for packing or seating."]], ["ceiling(3.2)=4.", "ceiling(-1.2)=-1."], ["The output is always an integer."], "function_graph", ["Find ceiling(3.2).", ["Integers above or equal to 3.2 include 4 and larger.", "The least one is 4.", "So ceiling(3.2)=4."], "4"], [["Buses", "Extra students need another bus."], ["Pages", "More lines may need one more page."], ["Packaging", "Partial box count needs a full box."]], ["ORDINARY_ROUNDING_USED", "Rounding 3.2 to 3.", "Ceiling always rounds up to cover the amount."], ["4", "round up", "least integer", "They rounded normally.", "buses"], "What is ceiling(3.2)?", "4", "Choose the least integer not below it.", "numeric", "graph.ceiling-function", "Ceiling rule", "ceiling(x)>=x"),
  fn(148, "Sign Function", "sign-function", "The sign function returns -1, 0, or 1 depending on whether the input is negative, zero, or positive.", "The sign function tells direction, not size. It is useful for motion, profit/loss, and programming decisions. It keeps only the sign of a number.", "sign(-8)=-1, sign(0)=0, and sign(5)=1. The graph jumps from -1 to 0 to 1. This appears when showing direction of movement, gain or loss, and whether a measurement is above or below target. It works because the function classifies the input by its position relative to zero. A common mistake is returning the original number instead of just its sign.", "Compare the input with zero. Return -1, 0, or 1. Ignore the size except for zero.", "Only the side of zero matters, not the distance from zero.", [["Sign", "Whether a number is negative, zero, or positive."], ["Classify", "Put into a group by a rule."]], ["sign(x)=1 for x>0.", "sign(x)=-1 for x<0."], ["At x=0, sign(x)=0 in this lesson."], "function_graph", ["Find sign(-8).", ["-8 is less than zero.", "Negative inputs return -1.", "So sign(-8)=-1."], "-1"], [["Motion", "Direction can be left or right."], ["Money", "Profit positive and loss negative."], ["Programming", "Code can branch by sign."]], ["RETURNED_INPUT", "Saying sign(-8)=-8.", "The sign function returns only -1, 0, or 1."], ["-1", "negative", "three outputs", "They returned the input.", "profit"], "What is sign(-8)?", "-1", "Negative input returns -1.", "numeric", "graph.sign-function", "Sign rule", "sign(x) in {-1,0,1}"),
  fn(149, "Piecewise Functions", "piecewise-functions", "A piecewise function uses different rules on different parts of the domain.", "Piecewise functions model rules that change by region. They are useful for taxes, delivery fees, and tariffs. Each input uses only one matching rule.", "A delivery fee might be 50 rupees for distance up to 5 km and 80 rupees after that. In algebra, f(x)=x for x<0 and f(x)=x^2 for x>=0 uses two rules. This works because the domain is split into cases. A common mistake is applying every rule to one input. Use only the rule whose condition is true.", "Read the input. Choose the matching condition. Apply only that rule. Check boundary points carefully.", "Domain conditions decide which formula controls each input.", [["Piecewise", "Built from separate rules on separate intervals."], ["Case", "One rule with its condition."]], ["Each input should use one active case.", "Boundary symbols decide which rule includes the endpoint."], ["Conditions should not conflict for a function."], "function_graph", ["If f(x)=x for x<0 and x^2 for x>=0, find f(3).", ["3 satisfies x>=0.", "Use x^2.", "f(3)=9."], "9"], [["Delivery fee", "Price changes after a distance limit."], ["Taxes", "Rates can change by income band."], ["Electric bills", "Unit price can change by usage."]], ["USED_ALL_CASES", "Applying both rules to one input.", "Choose only the condition that matches the input."], ["9", "matching case", "boundary", "They used all rules.", "delivery"], "For f(x)=x^2 when x>=0, what is f(3)?", "9", "Use the x>=0 case.", "numeric", "graph.piecewise-functions", "Piecewise rule", "use the matching condition"),
  fn(150, "Composite Functions", "composite-functions", "A composite function uses the output of one function as the input of another.", "Composite functions connect rules in order. They are useful in discounts plus tax, unit conversions, and computer pipelines. Order matters.", "If f(x)=2x and g(x)=x+3, then f(g(4)) means first use g: 4+3=7. Then use f: 2*7=14. This appears when a price is discounted then taxed, when units are converted twice, or when data passes through two programs. It works because one output becomes the next input. A common mistake is reversing the order.", "Start inside the brackets. Find the first output. Put that output into the outside function.", "Composition chains functions so outputs become inputs.", [["Composite", "A function made by applying functions in order."], ["Inner function", "The function used first."]], ["f(g(x)) usually differs from g(f(x)).", "The range of the inner function must fit the domain of the outer function."], ["Check domain restrictions after composing."], "function_graph", ["If f(x)=2x and g(x)=x+3, find f(g(4)).", ["g(4)=7.", "Then f(7)=14.", "So f(g(4))=14."], "14"], [["Discount then tax", "Order changes final price."], ["Conversions", "Metres to centimetres then to millimetres."], ["Apps", "Data passes through filters in order."]], ["REVERSED_COMPOSITION", "Doing f first in f(g(x)).", "The inner function g is used first."], ["14", "inside first", "order matters", "They reversed order.", "discount"], "If f(x)=2x and g(x)=x+3, what is f(g(4))?", "14", "Do g first.", "numeric", "graph.composite-functions", "Composition", "(f o g)(x)=f(g(x))"),
  fn(151, "Inverse Functions", "inverse-functions", "An inverse function reverses the action of a function.", "Inverse functions undo rules. They are useful for conversions, decoding, and solving equations. They swap inputs and outputs.", "If f(x)=2x+3, the inverse is f^-1(x)=(x-3)/2. It undoes the multiply-by-2 and add-3 steps in reverse. Temperature conversion, currency conversion, and encryption/decryption use inverse ideas. This works because a one-to-one function pairs each output with exactly one input. A common mistake is thinking the inverse means 1/f(x).", "Replace f(x) by y. Swap x and y. Solve for y. Check by composing back to x.", "An inverse reverses input-output pairs.", [["Inverse function", "A function that undoes another function."], ["One-to-one", "No two inputs share the same output."]], ["Inverse graphs reflect across y=x.", "Only one-to-one functions have inverse functions without restricting domain."], ["The original must be one-to-one on the chosen domain."], "coordinate_graph", ["Find the inverse of f(x)=2x+3.", ["Write y=2x+3.", "Swap x and y: x=2y+3.", "Solve y=(x-3)/2."], "(x-3)/2"], [["Temperature conversion", "Celsius and Fahrenheit formulas undo each other."], ["Currency", "Exchange rates can reverse."], ["Codes", "Decoding reverses encoding."]], ["INVERSE_AS_RECIPROCAL", "Writing inverse as 1/f(x).", "An inverse function reverses the rule, not just the value."], ["(x-3)/2", "undo", "swap x and y", "They used reciprocal.", "conversion"], "What is the inverse of f(x)=2x+3?", "(x-3)/2", "Undo +3, then undo times 2.", "keywords", "graph.inverse-functions", "Inverse rule", "f^-1(f(x))=x"),
  fn(152, "Even and Odd Functions", "even-and-odd-functions", "Even and odd functions have special symmetry rules: f(-x)=f(x) or f(-x)=-f(x).", "Even and odd functions show symmetry. They help read graphs faster. They are useful in physics, waves, and polynomial patterns.", "An even function has mirror symmetry across the y-axis, like f(x)=x^2. An odd function has origin symmetry, like f(x)=x^3. For x^2, f(-3)=9 and f(3)=9. For x^3, f(-3)=-27 and f(3)=27. This works because powers keep or change sign in predictable ways. A common mistake is judging from the name instead of checking f(-x).", "Compute f(-x). Compare it with f(x) and -f(x). Use the matching symmetry.", "Replacing x by -x reveals graph symmetry.", [["Even function", "A function with f(-x)=f(x)."], ["Odd function", "A function with f(-x)=-f(x)."]], ["x^2 is even.", "x^3 is odd."], ["A function can be neither even nor odd."], "function_graph", ["Is f(x)=x^2 even or odd?", ["Compute f(-x)=(-x)^2.", "This equals x^2.", "So the function is even."], "even"], [["Physics", "Symmetric motion can be even or odd."], ["Waves", "Some signals have symmetry."], ["Graph sketching", "Symmetry reduces plotting work."]], ["NAME_NOT_TESTED", "Guessing from the graph title only.", "Check f(-x) against f(x) and -f(x)."], ["even", "f(-x)=f(x)", "symmetry", "They guessed without checking.", "waves"], "Is f(x)=x^2 even or odd?", "even", "Check f(-x).", "keywords", "graph.even-and-odd-functions", "Symmetry test", "even: f(-x)=f(x), odd: f(-x)=-f(x)"),
  fn(153, "Increasing and Decreasing", "increasing-and-decreasing", "A function is increasing when outputs rise as inputs move right, and decreasing when outputs fall.", "Increasing and decreasing describe graph direction. They help read speed, profit, and temperature changes. They tell where a quantity grows or shrinks.", "On a graph, move from left to right. If y-values go up, the function is increasing. If y-values go down, it is decreasing. A hill path, a bank balance, and cooling tea can all show increasing or decreasing intervals. This works because the graph compares output changes as input increases. A common mistake is reading the graph from right to left.", "Scan from left to right. Mark intervals where y rises or falls. Use x-intervals in the answer.", "Function behaviour is described as input x increases.", [["Increasing", "Outputs rise as x increases."], ["Decreasing", "Outputs fall as x increases."]], ["Read graphs from left to right.", "Intervals are written using x-values."], ["Flat intervals are constant, not increasing or decreasing."], "function_graph", ["Is f(x)=x increasing?", ["As x moves right, y rises.", "Each larger x gives a larger output.", "So it is increasing."], "increasing"], [["Temperature", "A room warming up is increasing."], ["Savings", "Money can increase over time."], ["Cooling tea", "Temperature decreases over time."]], ["READ_RIGHT_TO_LEFT", "Reading direction from right to left.", "Always describe behaviour as x increases."], ["increasing", "left to right", "x-interval", "They read backwards.", "temperature"], "When y rises as x moves right, is the function increasing or decreasing?", "increasing", "Read from left to right.", "keywords", "graph.increasing-and-decreasing", "Monotonic direction", "x increases => compare y"),
  fn(154, "Periodic Functions", "periodic-functions", "A periodic function repeats its output pattern after a fixed input length.", "Periodic functions model repeating events. They are useful for waves, clocks, seasons, and wheels. One repeat length is called the period.", "The sine graph repeats every 360 degrees, or 2pi radians. That means the same shape appears again and again. Daily temperature, tides, sound waves, and rotating wheels can be periodic. This works because the motion returns to the same state after a fixed cycle. A common mistake is calling any wavy graph periodic without checking exact repetition.", "Find a complete cycle. Measure the horizontal length to the next matching cycle. Check that the pattern repeats.", "A repeat happens when the same outputs occur after a fixed input shift.", [["Period", "The input length of one full repeat."], ["Cycle", "One complete repeated pattern."]], ["Sine and cosine are periodic.", "A repeating pattern must match exactly."], ["State the input unit for the period."], "function_graph", ["What is the period of sin(x) in radians?", ["The sine pattern repeats after 2pi.", "So sin(x+2pi)=sin(x).", "The period is 2pi."], "2pi"], [["Clock hands", "Positions repeat every 12 hours."], ["Tides", "Water levels repeat."], ["Sound", "Waves repeat in time."]], ["WAVY_MEANS_PERIODIC", "Calling a non-repeating wave periodic.", "The pattern must repeat exactly."], ["2pi", "repeat", "cycle", "They did not check exact repeat.", "clock"], "What is the period of sin(x) in radians?", "2pi", "Sine repeats after 2pi.", "keywords", "graph.periodic-functions", "Period rule", "f(x+T)=f(x)"),
  fn(155, "Recursive Functions", "recursive-functions", "A recursive function defines each new value using earlier value or values.", "Recursive functions build outputs step by step. They are useful for savings, population, and sequences. Each step depends on what came before.", "If a1=2 and a_n=a_(n-1)+3, the terms are 2, 5, 8, and 11. Each new term adds 3 to the previous term. Recursion appears in monthly savings, plant growth, and computer loops. This works because a starting value and a rule are enough to build the list. A common mistake is using the rule without the starting value.", "Start with the initial value. Apply the recurrence rule once per step. Keep terms in order.", "Each output depends on earlier output, so the sequence grows one step at a time.", [["Initial value", "The first value in a recursive rule."], ["Recurrence", "A rule that uses earlier terms."]], ["A recursive rule needs a starting value.", "Order matters when generating terms."], ["Do not skip terms unless a direct formula is known."], "table", ["Find the third term when a1=2 and add 3 each time.", ["First term is 2.", "Second term is 5.", "Third term is 8."], "8"], [["Savings", "Add the same amount each month."], ["Population", "Next year depends on this year."], ["Computer loops", "A step can use the previous result."]], ["NO_INITIAL_VALUE", "Trying to start without a first term.", "A recursive rule needs an initial value."], ["8", "initial value", "previous term", "They skipped the start.", "savings"], "If a1=2 and each term adds 3, what is a3?", "8", "2, 5, 8.", "numeric", "graph.recursive-functions", "Recursive rule", "a_n depends on a_(n-1)"),
  fn(156, "Vertical Translation", "vertical-translation", "A vertical translation moves a graph up or down by adding a constant outside the function.", "Vertical translation shifts output values. It is useful when a starting level changes. We see it in height, cost, and temperature graphs.", "The graph y=f(x)+3 is the graph of f(x) moved up 3 units. Every y-value becomes 3 larger, while x-values stay the same. This appears when adding a base fee, raising a platform, or adjusting temperature readings. It works because the constant is added after the function output is found. A common mistake is moving the graph sideways instead of up or down.", "Compute the original output. Add the outside constant. Move every point vertically by that amount.", "Adding outside the function changes y-values, not x-values.", [["Vertical shift", "A movement up or down."], ["Output", "The y-value of a function."]], ["f(x)+k moves up if k>0.", "f(x)+k moves down if k<0."], ["The domain usually stays the same after a vertical shift."], "transformation_animation", ["Move y=x^2 up 3.", ["Add 3 outside the function.", "Every y-value increases by 3.", "The vertex moves from (0,0) to (0,3)."], "up 3"], [["Base fare", "Adding a fixed fee shifts cost up."], ["Platform height", "A raised start shifts height up."], ["Thermometer correction", "Adding an offset shifts readings."]], ["VERTICAL_AS_HORIZONTAL", "Moving f(x)+3 sideways.", "Outside addition changes y-values."], ["up 3", "outside", "y-values", "They shifted sideways.", "base fare"], "What does f(x)+3 do to a graph?", "up 3", "Outside addition changes y.", "keywords", "graph.vertical-translation", "Vertical shift", "g(x)=f(x)+k"),
  fn(157, "Horizontal Translation", "horizontal-translation", "A horizontal translation moves a graph left or right by changing the input inside the function.", "Horizontal translation shifts input values. It is useful for delays, starting points, and phase changes. It can feel backwards at first.", "The graph y=f(x-2) moves the graph of f(x) right by 2 units. It moves right because the same output happens when x is 2 larger. Delayed signals, moved starting positions, and shifted schedules use this idea. It works because changing the input changes where each old output appears. A common mistake is moving f(x-2) left instead of right.", "Look inside the function. x-h moves right h. x+h moves left h. Check one key point.", "Input changes move the x-values needed to make the same output.", [["Horizontal shift", "A movement left or right."], ["Input", "The x-value put into the function."]], ["f(x-h) moves right h.", "f(x+h) moves left h."], ["Track signs carefully inside the function."], "transformation_animation", ["Move y=x^2 using f(x-2).", ["The input is x-2.", "The old vertex occurs when x-2=0.", "So x=2 and the graph moves right 2."], "right 2"], [["Delayed signal", "A wave can start later."], ["Moved origin", "A design can shift right."], ["Schedule", "Events can happen later."]], ["HORIZONTAL_SIGN_ERROR", "Moving f(x-2) left.", "Inside subtraction moves right."], ["right 2", "inside", "x-values", "They reversed the sign.", "delay"], "What does f(x-2) do?", "right 2", "Set x-2=0 for the old key point.", "keywords", "graph.horizontal-translation", "Horizontal shift", "g(x)=f(x-h)"),
  fn(158, "Vertical Stretch and Compression", "vertical-stretch-and-compression", "A vertical stretch or compression multiplies every output by a constant.", "Vertical scaling changes graph height. It is useful for louder waves, larger costs, or magnified measurements. The x-values stay fixed.", "The graph y=2f(x) is twice as tall as y=f(x). Every y-value is multiplied by 2. If 0<a<1, y=af(x) is vertically compressed. This appears in sound amplitude, scaled prices, and graph comparisons. It works because multiplication happens after the output is calculated. A common mistake is changing x-values during a vertical stretch.", "Find each output. Multiply it by the outside factor. Keep each x-value the same.", "Multiplying outside the function changes y-values only.", [["Vertical stretch", "Outputs move farther from the x-axis."], ["Compression", "Outputs move closer to the x-axis."]], ["|a|>1 stretches vertically.", "0<|a|<1 compresses vertically."], ["A negative factor also reflects in the x-axis."], "transformation_animation", ["What does y=2f(x) do?", ["Multiply every output by 2.", "Points move twice as far from the x-axis.", "x-values stay the same."], "vertical stretch by 2"], [["Sound", "Amplitude can double."], ["Prices", "Costs can be scaled up."], ["Graphs", "Data can be magnified vertically."]], ["CHANGED_X_FOR_VERTICAL", "Changing x-values during vertical scaling.", "Vertical scaling changes y-values."], ["vertical stretch", "y-values", "factor 2", "They changed x-values.", "sound"], "What does y=2f(x) do?", "vertical stretch", "Outside multiplication changes y.", "keywords", "graph.vertical-stretch-and-compression", "Vertical scale", "g(x)=a f(x)"),
  fn(159, "Horizontal Stretch and Compression", "horizontal-stretch-and-compression", "A horizontal stretch or compression changes input values inside the function.", "Horizontal scaling changes graph width. It is useful for time scaling, wave speed, and resized patterns. The effect can feel reversed.", "The graph y=f(2x) is horizontally compressed by factor 1/2. The same output happens with half the old x-value. The graph y=f(x/2) stretches horizontally by factor 2. This appears in faster videos, compressed waves, and map resizing. It works because the input reaches old values sooner or later. A common mistake is using the inside factor directly instead of its reciprocal.", "Look at the multiplier on x inside. Use the reciprocal scale for horizontal width. Check a key point.", "Changing input changes how quickly the graph reaches old outputs.", [["Horizontal scale", "A change in graph width."], ["Reciprocal", "One divided by a number."]], ["f(cx) scales horizontally by 1/c.", "c>1 compresses horizontally."], ["Use positive c for basic stretch and compression here."], "transformation_animation", ["What does f(2x) do?", ["The inside factor is 2.", "Use reciprocal width 1/2.", "The graph compresses horizontally."], "horizontal compression"], [["Video speed", "Faster playback compresses time."], ["Waves", "Higher frequency compresses wavelength."], ["Maps", "One direction can be scaled."]], ["USED_DIRECT_FACTOR", "Saying f(2x) stretches by 2.", "Horizontal scale uses the reciprocal."], ["compression", "reciprocal", "inside factor", "They used direct factor.", "video"], "What does f(2x) do horizontally?", "compression", "Use reciprocal scale 1/2.", "keywords", "graph.horizontal-stretch-and-compression", "Horizontal scale", "g(x)=f(cx)"),
  fn(160, "Reflection in x-Axis", "reflection-in-x-axis", "Reflection in the x-axis changes each output y to -y.", "Reflecting in the x-axis flips a graph upside down. It is useful for opposite height, profit and loss, or mirrored motion. The x-values stay the same.", "The graph y=-f(x) is the reflection of y=f(x) in the x-axis. Every point (x,y) becomes (x,-y). A peak becomes a valley. This appears in mirror images, changing gains to losses, and reversed vertical motion. It works because only the sign of y changes. A common mistake is changing x instead of y.", "Keep x the same. Multiply every y-value by -1. Check one point and its image.", "The x-axis is the mirror line, so vertical distance changes side.", [["Reflection", "A mirror flip."], ["Image point", "The new point after a transformation."]], ["(x,y) maps to (x,-y).", "The x-axis stays fixed."], ["Points on the x-axis do not move."], "transformation_animation", ["Reflect (2,3) in the x-axis.", ["Keep x=2.", "Change y=3 to -3.", "The image is (2,-3)."], "(2,-3)"], [["Mirrors", "A shape can flip vertically."], ["Profit/loss", "Positive values can become negative."], ["Motion", "Upward displacement can reverse."]], ["CHANGED_X_FOR_X_AXIS", "Changing x during x-axis reflection.", "Reflection in x-axis changes y."], ["(2,-3)", "change y", "x same", "They changed x.", "mirror"], "Reflect (2,3) in the x-axis.", "(2,-3)", "Keep x, change y sign.", "keywords", "graph.reflection-in-x-axis", "x-axis reflection", "(x,y)->(x,-y)"),
  fn(161, "Reflection in y-Axis", "reflection-in-y-axis", "Reflection in the y-axis changes each input x to -x.", "Reflecting in the y-axis flips a graph left and right. It is useful for mirror images and opposite directions. The y-values stay the same.", "The graph y=f(-x) is the reflection of y=f(x) in the y-axis. Every point (x,y) becomes (-x,y). This appears in mirrored designs, map directions, and symmetric motion. It works because only the sign of x changes. A common mistake is changing y instead of x.", "Keep y the same. Change each x-value to its opposite. Check one point and its image.", "The y-axis is the mirror line, so horizontal distance changes side.", [["Y-axis reflection", "A left-right mirror flip."], ["Opposite x", "The same distance from zero on the other side."]], ["(x,y) maps to (-x,y).", "The y-axis stays fixed."], ["Points on the y-axis do not move."], "transformation_animation", ["Reflect (2,3) in the y-axis.", ["Change x=2 to -2.", "Keep y=3.", "The image is (-2,3)."], "(-2,3)"], [["Mirror design", "A left shape can mirror right."], ["Maps", "East-west directions can reverse."], ["Graphs", "f(-x) flips left and right."]], ["CHANGED_Y_FOR_Y_AXIS", "Changing y during y-axis reflection.", "Reflection in y-axis changes x."], ["(-2,3)", "change x", "y same", "They changed y.", "design"], "Reflect (2,3) in the y-axis.", "(-2,3)", "Change x sign.", "keywords", "graph.reflection-in-y-axis", "y-axis reflection", "(x,y)->(-x,y)"),
  fn(162, "Combined Transformations", "combined-transformations", "Combined transformations apply more than one graph transformation to the same function.", "Combined transformations let us build many graph shapes. They are useful in modelling, animation, and matching data. Order and placement matter.", "The graph y=2f(x-3)+1 moves the graph right 3, stretches it vertically by 2, then moves it up 1. Each part has a job. This appears in shifted waves, resized designs, and adjusted cost models. It works because input changes affect x-values and outside changes affect y-values. A common mistake is mixing inside and outside effects.", "Separate inside changes from outside changes. Apply horizontal effects to x. Apply vertical effects to y. Check a key point.", "Function notation records each transformation in its place.", [["Combined transformation", "Two or more transformations used together."], ["Key point", "A point used to track movement."]], ["Inside changes affect x-values.", "Outside changes affect y-values."], ["Order can matter when transformations are mixed."], "transformation_animation", ["Describe y=2f(x-3)+1.", ["x-3 moves right 3.", "2 outside stretches vertically.", "+1 outside moves up 1."], "right 3, stretch 2, up 1"], [["Animation", "Objects can move and scale."], ["Wave modelling", "Waves can shift and stretch."], ["Data fitting", "Parent curves can be adjusted."]], ["INSIDE_OUTSIDE_MIXED", "Treating x-3 as a vertical shift.", "Inside changes affect x-values."], ["right 3", "outside y", "inside x", "They mixed effects.", "animation"], "In y=2f(x-3)+1, what does x-3 do?", "right 3", "Inside subtraction shifts right.", "keywords", "graph.combined-transformations", "Combined transform", "g(x)=a f(x-h)+k"),
  fn(163, "Transformation Order", "transformation-order", "Transformation order is the sequence in which graph changes are applied.", "Transformation order helps avoid wrong graphs. It matters in animations, functions, and modelling. Some steps do not commute, which means order can change the result.", "For y=2f(x)+3, first the output of f is doubled, then 3 is added. For points, scaling then translating can differ from translating then scaling. This appears in computer graphics, map transformations, and graph sketching. It works because each step uses the result of the previous step. A common mistake is applying steps in a random order.", "Track one key point. Apply transformations in the written order for that point. Compare the final image.", "Later transformations act on already transformed values.", [["Order", "The sequence of steps."], ["Commute", "Give the same result when order is swapped."]], ["Scaling and translating may not commute.", "Tracking a key point reveals order errors."], ["Follow the chosen convention consistently."], "transformation_animation", ["Apply double then add 3 to y=2.", ["Double 2 to get 4.", "Add 3 to get 7.", "The final output is 7."], "7"], [["Graphics", "Scale then move can differ from move then scale."], ["Maps", "Transforms must follow order."], ["Animation", "Objects move according to ordered steps."]], ["RANDOM_ORDER", "Applying transformations without tracking order.", "Use a key point step by step."], ["7", "track point", "order", "They changed order.", "graphics"], "Double y=2, then add 3. What is the result?", "7", "Do the steps in order.", "numeric", "graph.transformation-order", "Ordered transform", "new value uses previous value"),
  fn(164, "Parameter Explorer", "parameter-explorer", "A parameter is a value that changes a whole family of graphs.", "Parameters let one formula make many related graphs. They are useful in simulations and modelling. Sliders make parameter effects visible.", "In y=ax+b, a and b are parameters. Changing a changes slope. Changing b moves the line up or down. Parameters appear in physics models, finance formulas, and graphing tools. This works because a parameter stays fixed for one graph but can change between graphs. A common mistake is treating a parameter like the input variable x.", "Choose one parameter. Keep others fixed. Change it and watch which graph feature changes.", "Parameters control the rule, while inputs move along one graph.", [["Parameter", "A value that controls a family of graphs."], ["Input variable", "The value that moves along one graph."]], ["Changing a parameter changes the graph.", "Changing x finds another point on the same graph."], ["Change one parameter at a time for clear evidence."], "function_graph", ["In y=ax+b, which parameter shifts the line vertically?", ["a controls slope.", "b is added to every output.", "So b shifts the line vertically."], "b"], [["Simulations", "A slider changes model assumptions."], ["Finance", "Interest rate is a parameter."], ["Physics", "Gravity can be a parameter."]], ["PARAMETER_AS_INPUT", "Treating a like the input x.", "A parameter controls the rule; x is the input."], ["b", "parameter", "slider", "They confused a with x.", "simulation"], "In y=ax+b, which parameter shifts the line vertically?", "b", "b is added outside.", "keywords", "graph.parameter-explorer", "Parameter model", "y=a x+b"),
  fn(165, "Parent-Function Library", "parent-function-library", "A parent function is the simplest function in a family of related graphs.", "Parent functions are graph starting points. They help identify shape before transformations. We use them to recognise lines, parabolas, roots, and exponentials.", "The parent of quadratic functions is y=x^2. The parent of absolute-value functions is y=|x|. Each parent shows the basic shape before shifting, stretching, or reflecting. This helps graph matching, modelling, and equation reading. It works because transformations preserve a family pattern. A common mistake is choosing a transformed graph as the parent.", "Identify the family. Name the simplest rule. Compare transformations to the parent shape.", "A parent function shows the core shape without added transformations.", [["Parent function", "The simplest rule in a graph family."], ["Family", "Graphs with the same basic kind of rule."]], ["y=x^2 is the quadratic parent.", "y=|x| is the absolute-value parent."], ["Parent functions are chosen before shifts and stretches."], "function_graph", ["What is the quadratic parent function?", ["Quadratic functions have an x squared term.", "The simplest one is y=x^2.", "So the parent is y=x^2."], "y=x^2"], [["Graph matching", "Parents help name shapes."], ["Modelling", "Start from a known family."], ["Transformations", "Compare changed graphs to parents."]], ["TRANSFORMED_AS_PARENT", "Calling (x-2)^2 the parent.", "The parent has no shift or stretch."], ["y=x^2", "simplest", "family", "They chose a shifted graph.", "matching"], "What is the parent function for quadratics?", "y=x^2", "Use the simplest quadratic.", "keywords", "graph.parent-function-library", "Parent function", "simplest family rule"),
  fn(166, "Graph Matching", "graph-matching", "Graph matching connects a formula, table, or description to the correct graph.", "Graph matching checks whether representations agree. It is useful in modelling and exams. It helps catch formula and graph mistakes.", "To match y=2x+1, look for a straight line with y-intercept 1 and slope 2. To match y=x^2, look for a parabola. Tables can confirm points. This appears in data analysis, science graphs, and choosing cost models. It works because every function type has features that appear in its graph. A common mistake is matching by one point only.", "Name the family. Check intercepts, slope, vertex, asymptotes, or period. Verify with at least two points.", "A correct match must satisfy the formula and the visual features.", [["Match", "Connect two representations of the same function."], ["Feature", "A graph property such as slope or vertex."]], ["One point is not enough for a reliable match.", "Use both shape and sample points."], ["Check scale and axes before deciding."], "function_graph", ["Which graph matches y=2x+1?", ["Choose a straight line.", "Check y-intercept 1.", "Check slope 2 using another point."], "line with slope 2 and intercept 1"], [["Science", "Choose a graph for measured data."], ["Costs", "Match a formula to a price graph."], ["Exams", "Check if equation and graph agree."]], ["ONE_POINT_MATCH", "Matching because one point fits.", "Use shape and more than one point."], ["slope 2", "two points", "shape", "They used one point.", "science"], "For y=2x+1, what is the y-intercept?", "1", "Set x=0.", "numeric", "graph.graph-matching", "Match check", "formula, table, and graph agree"),
];

export const functionStrengthenedLessons: Record<number, StrengthenedLesson> = Object.fromEntries(seeds.map((seed) => [seed.id, buildFunctionLesson(seed)]));

export const functionStrengthenedChallenges: Record<number, FunctionChallenge> = Object.fromEntries(seeds.map((seed) => [seed.id, seed.challenge]));

function fn(
  id: number,
  title: string,
  slug: string,
  definition: string,
  intro: string,
  basicIdea: string,
  how: string,
  why: string,
  vocabulary: [string, string][],
  facts: string[],
  restrictions: string[],
  representation: StrengthenedLesson["representations"][number]["type"],
  worked: [string, string[], string],
  examples: [string, string][],
  misconception: [string, string, string],
  practiceAnswers: [string, string, string, string, string],
  prompt: string,
  expected: string,
  hint: string,
  kind: FunctionChallenge["kind"],
  factoryId: string,
  formulaLabel: string,
  formulaExpression: string,
): FunctionSeed {
  return {
    id,
    title,
    slug,
    definition,
    intro,
    basicIdea,
    how,
    why,
    vocabulary,
    facts,
    restrictions,
    representation,
    worked,
    examples,
    misconception,
    practiceAnswers,
    challenge: { prompt, expected, hint, kind, factoryId },
    formula: {
      id: `${slug}-formula`,
      label: formulaLabel,
      expression: formulaExpression,
      variables: [{ symbol: "x", meaning: "the function input" }, { symbol: "f(x)", meaning: "the function output" }],
      restrictions,
      exactness: "definition",
    },
  };
}

function buildFunctionLesson(seed: FunctionSeed): StrengthenedLesson {
  const code = seed.misconception[0];
  return {
    id: seed.id,
    title: seed.title,
    route: `/lessons/graphs-and-functions/${seed.id}-${seed.slug}`,
    category: "Graphs and Functions",
    topic: "Functions",
    lessonType: "visual_exploration",
    learningObjectives: [
      `Define ${seed.title} using inputs and outputs.`,
      `Read ${seed.title} from a graph, table, or formula.`,
      `Correct a common mistake about ${seed.title}.`,
    ],
    prerequisites: ["Coordinate plane", "Basic substitution", "Reading tables"],
    keyVocabulary: seed.vocabulary.map(([term, meaning]) => ({ term, meaning })),
    introduction: seed.intro,
    basicIdea: seed.basicIdea,
    howItWorks: seed.how,
    whyItWorks: seed.why,
    definitions: [{ id: `${seed.slug}-definition`, statement: seed.definition }],
    facts: seed.facts.map((statement, index) => ({ id: `${seed.slug}-fact-${index + 1}`, statement })),
    formulas: [seed.formula],
    conditionsAndRestrictions: seed.restrictions,
    representations: [{ id: `${seed.slug}-graph`, type: seed.representation, learningPurpose: `Show the input-output behaviour of ${seed.title}.` }],
    workedExamples: [{ id: `${seed.slug}-worked-1`, prompt: seed.worked[0], steps: seed.worked[1], answer: seed.worked[2] }],
    realLifeExamples: seed.examples.map(([context, connection], index) => ({ id: `${seed.slug}-real-${index + 1}`, context, connection })),
    misconceptions: [{ code, mistake: seed.misconception[1], correction: seed.misconception[2] }],
    interaction: {
      id: `${seed.slug}-graph-interaction`,
      learningPurpose: `Connect the ${seed.title} graph, table, and formula.`,
      parameters: [{ id: "a", label: "Shape or scale", validRange: [-5, 5] }, { id: "b", label: "Shift", validRange: [-5, 5] }],
      initialState: `Start with the parent graph for ${seed.title}.`,
      dynamicFeedback: `The graph and table should show the defining feature of ${seed.title}.`,
      successCriteria: [`Name the key graph feature of ${seed.title}.`, "Use the table to check one input-output pair."],
      accessibilityAlternative: "Read the formula, key feature, and sample table values as text.",
    },
    guidedExploration: [
      { id: "predict", prompt: "Predict how the graph changes before moving a slider." },
      { id: "observe", prompt: "Move one control and compare the table with the graph." },
      { id: "conclude", prompt: `Explain the defining feature of ${seed.title}.` },
    ],
    practice: [
      practice(`${seed.slug}-recognition`, `Identify the key feature of ${seed.title}.`, seed.practiceAnswers[0], code, "recognition"),
      practice(`${seed.slug}-direct`, `Answer a direct ${seed.title} question.`, seed.practiceAnswers[1], code, "direct"),
      practice(`${seed.slug}-multi`, `Use a graph or table for ${seed.title}.`, seed.practiceAnswers[2], code, "multi_step"),
      practice(`${seed.slug}-error`, `Find the mistake in a ${seed.title} claim.`, seed.practiceAnswers[3], code, "error_diagnosis"),
      practice(`${seed.slug}-transfer`, `Use ${seed.title} in a real situation.`, seed.practiceAnswers[4], code, "transfer"),
    ],
    challenge: { id: `${seed.slug}-challenge`, prompt: seed.challenge.prompt, successCriteria: ["Uses the function definition", "Checks the graph or table", "Avoids the named misconception"], hints: [seed.challenge.hint, "Use one input-output pair to check."] },
    exitCheck: [{ id: `${seed.slug}-exit`, prompt: `State one graph or domain rule for ${seed.title}.`, answer: seed.facts[0], criterion: "Answer names a true function-specific rule." }],
    accessibilityNotes: ["Announce graph feature and table values.", "Do not rely only on colour for parent and live graphs."],
    expertReviewRequired: false,
  };
}

function practice(
  id: string,
  prompt: string,
  answer: string,
  misconceptionTag: string,
  difficulty: StrengthenedLesson["practice"][number]["difficulty"],
): StrengthenedLesson["practice"][number] {
  return {
    id,
    prompt,
    answer,
    hints: ["Read the input.", "Apply the function rule.", "Check the graph feature."],
    workedSolution: ["Identify the function type.", "Use the rule or graph.", "Check the output or domain condition."],
    misconceptionTag,
    difficulty,
    parameterConstraints: ["Use simple inputs that keep the graph readable."],
  };
}
