import type { StrengthenedLesson } from "./strengthenedLessonSchema";

type Challenge = { prompt: string; expected: string; hint: string; kind: "numeric" | "keywords" | "interaction"; factoryId: string };
type Seed = {
  id: number; title: string; slug: string; definition: string; rule: string; mistake: [string, string, string];
  formula: string; worked: [string, string[], string]; examples: [string, string][]; challenge: Challenge;
};

const seeds: Seed[] = [
  s(183, "Vector Introduction", "vector-introduction", "A vector has size and direction.", "Draw an arrow from tail to head; moving the arrow without turning it keeps the same vector.", ["VECTOR_AS_POINT", "Treating a vector as only a point.", "A vector describes movement, not just location."], "v=(x,y)", ["Name the vector from (0,0) to (3,2).", ["Read horizontal change 3.", "Read vertical change 2.", "Write the vector as (3,2)."], "(3,2)"], [["Walking", "3 m east and 2 m north is a vector."], ["Games", "Velocity has direction and speed."], ["Maps", "Wind arrows show vector direction."]], "What vector goes from (0,0) to (3,2)?", "(3,2)", "Read change in x and y.", "keywords"),
  s(184, "Component Form", "component-form", "Component form writes a vector by horizontal and vertical parts.", "The first component is x-change; the second component is y-change.", ["COMPONENTS_SWAPPED", "Writing vertical change first.", "Component form is (x,y)."], "v=(vx,vy)", ["Write 4 right and 1 down.", ["Right means x=4.", "Down means y=-1.", "Vector is (4,-1)."], "(4,-1)"], [["Screen movement", "Pixels move by x and y."], ["Robotics", "A command can split motion into parts."], ["Navigation", "East and north parts form components."]], "What is 4 right and 1 down in component form?", "(4,-1)", "Down is negative y.", "keywords"),
  s(185, "Position Vectors", "position-vectors", "A position vector goes from the origin to a point.", "A point (a,b) has position vector (a,b) from the origin.", ["POSITION_NOT_FROM_ORIGIN", "Starting a position vector away from the origin.", "Position vectors start at (0,0)."], "OP=(x,y)", ["Find the position vector of P(5,-2).", ["Start at origin.", "Move to (5,-2).", "The vector is (5,-2)."], "(5,-2)"], [["Maps", "A location can be measured from an origin."], ["Robots", "Position from base can be a vector."], ["Graphics", "Objects have position vectors."]], "What is the position vector of P(5,-2)?", "(5,-2)", "Use the coordinates from the origin.", "keywords"),
  s(186, "Vector Addition", "vector-addition", "Vector addition combines movements head-to-tail or component by component.", "Add x-components and y-components separately.", ["ADDED_LENGTHS_ONLY", "Adding only magnitudes.", "Add components with direction."], "u+v=(ux+vx,uy+vy)", ["Add (3,2)+(-1,4).", ["Add x: 3+(-1)=2.", "Add y: 2+4=6.", "Sum is (2,6)."], "(2,6)"], [["Walking", "Two walks combine into one displacement."], ["Forces", "Forces add by components."], ["Games", "Movement keys combine directions."]], "Add (3,2)+(-1,4).", "(2,6)", "Add matching components.", "keywords"),
  s(187, "Vector Subtraction", "vector-subtraction", "Vector subtraction finds the movement from one vector tip to another.", "Subtract matching components: u-v=(ux-vx,uy-vy).", ["SUBTRACTED_BACKWARDS", "Reversing u-v and v-u.", "Order matters in subtraction."], "u-v=(ux-vx,uy-vy)", ["Find (5,1)-(2,4).", ["Subtract x: 5-2=3.", "Subtract y: 1-4=-3.", "Result is (3,-3)."], "(3,-3)"], [["Displacement", "Final minus start gives movement."], ["Maps", "Compare two locations."], ["Physics", "Relative position uses subtraction."]], "Find (5,1)-(2,4).", "(3,-3)", "Subtract component by component.", "keywords"),
  s(188, "Scalar Multiplication", "scalar-multiplication", "Scalar multiplication stretches or reverses a vector.", "Multiply every component by the scalar.", ["MULTIPLIED_ONE_COMPONENT", "Multiplying only one component.", "Scale every component."], "kv=(kvx,kvy)", ["Find 3(2,-1).", ["Multiply x by 3.", "Multiply y by 3.", "Result is (6,-3)."], "(6,-3)"], [["Speed", "Doubling velocity doubles each component."], ["Maps", "Scale an arrow on a diagram."], ["Forces", "Multiply a force vector by a constant."]], "Find 3(2,-1).", "(6,-3)", "Multiply both components.", "keywords"),
  s(189, "Magnitude and Unit Vectors", "magnitude-and-unit-vectors", "Magnitude is vector length; a unit vector has length 1.", "Use Pythagoras for length, then divide by the length for a unit vector.", ["UNIT_NOT_LENGTH_ONE", "Calling any small vector a unit vector.", "A unit vector must have magnitude 1."], "|v|=sqrt(x^2+y^2)", ["Find the magnitude of (3,4).", ["Square 3 and 4.", "Add 9+16=25.", "Square root gives 5."], "5"], [["Speed", "Velocity magnitude is speed."], ["Directions", "Unit vectors show direction only."], ["Forces", "Force size is magnitude."]], "What is the magnitude of (3,4)?", "5", "Use the 3-4-5 triangle.", "numeric"),
  s(190, "Dot Product", "dot-product", "The dot product measures how much two vectors point in the same direction.", "Multiply matching components and add.", ["DOT_AS_VECTOR", "Returning a vector for a dot product.", "The dot product is a scalar number."], "u dot v=uxvx+uyvy", ["Find (3,2) dot (1,4).", ["Multiply 3*1.", "Multiply 2*4.", "Add 3+8=11."], "11"], [["Work", "Force along motion uses dot product."], ["Lighting", "Brightness uses direction alignment."], ["Projection", "Dot product measures shadow length."]], "Find (3,2) dot (1,4).", "11", "Multiply matching components and add.", "numeric"),
  s(191, "Cross Product", "cross-product", "In 3D, the cross product gives a vector perpendicular to two vectors.", "Its magnitude equals parallelogram area made by the vectors.", ["CROSS_AS_DOT", "Giving a scalar alignment answer.", "Cross product gives a perpendicular vector in 3D."], "u x v is perpendicular to u and v", ["What is i cross j?", ["i points along x.", "j points along y.", "By the right-hand rule, i cross j = k."], "k"], [["Torque", "Turning effect uses cross product."], ["Area", "Parallelogram area uses cross product magnitude."], ["3D graphics", "Surface normals use cross products."]], "What is i cross j?", "k", "Use the right-hand rule.", "keywords"),
  s(192, "Vector Projection", "vector-projection", "Projection is the shadow of one vector along another vector.", "Use the dot product to find the component in the target direction.", ["PROJECTION_AS_ORIGINAL", "Keeping the whole vector instead of its shadow.", "Projection keeps only the part along the target vector."], "proj_v u=((u dot v)/(v dot v))v", ["Project (3,4) onto the x-axis.", ["The x-axis keeps horizontal part.", "Horizontal component is 3.", "Projection is (3,0)."], "(3,0)"], [["Shadows", "A shadow is a projection."], ["Work", "Only force along motion does work."], ["Navigation", "Find motion along a road direction."]], "Project (3,4) onto the x-axis.", "(3,0)", "Keep only horizontal part.", "keywords"),
  s(193, "Linear Combinations", "linear-combinations", "A linear combination adds scaled vectors.", "Multiply vectors by scalars, then add the results.", ["SCALES_AFTER_ADDING", "Adding first when the expression says scale first.", "Follow multiplication before addition."], "au+bv", ["Find 2(1,0)+3(0,1).", ["2(1,0)=(2,0).", "3(0,1)=(0,3).", "Add to get (2,3)."], "(2,3)"], [["Robotics", "Combine basis movements."], ["Graphics", "Blend directions by weights."], ["Physics", "Forces can be scaled and added."]], "Find 2(1,0)+3(0,1).", "(2,3)", "Scale first, then add.", "keywords"),
  s(194, "Vector Equation of a Line", "vector-equation-of-a-line", "A vector line equation uses a point and a direction vector.", "r=a+tv means start at point a and move in direction v.", ["T_AS_POINT", "Treating t as a point.", "t is a scalar parameter."], "r=a+tv", ["For r=(1,2)+t(3,0), find t=2.", ["Multiply direction by 2: (6,0).", "Add start point (1,2).", "Point is (7,2)."], "(7,2)"], [["Roads", "A straight path has start and direction."], ["Motion", "Position changes with time parameter."], ["Graphics", "Rays use point plus direction."]], "For r=(1,2)+t(3,0), what point is t=2?", "(7,2)", "Substitute t=2.", "keywords"),
  s(195, "Vector Equation of a Plane", "vector-equation-of-a-plane", "A vector plane equation uses a point and two non-parallel direction vectors.", "r=a+su+tv moves in two independent directions from a point.", ["PARALLEL_DIRECTIONS_PLANE", "Using parallel direction vectors for a plane.", "A plane needs two non-parallel directions."], "r=a+su+tv", ["Name what s and t do in r=a+su+tv.", ["u gives one direction.", "v gives another direction.", "s and t scale these directions."], "scale directions"], [["Sheets", "A flat surface has two directions."], ["3D graphics", "Planes model walls and floors."], ["Navigation", "A plane can describe a flat path."]], "In r=a+su+tv, what do s and t do?", "scale directions", "They are scalar parameters.", "keywords"),
  s(196, "Relative Motion", "relative-motion", "Relative motion compares one object's velocity or position with another's.", "Subtract velocities to describe motion as seen from another object.", ["USED_ABSOLUTE_ONLY", "Using one velocity without comparing.", "Relative motion uses a difference."], "v_relative=v_a-v_b", ["A walks east 5 m/s and B east 2 m/s. Relative speed of A from B?", ["Use 5-2.", "Both move same direction.", "Relative speed is 3."], "3"], [["Trains", "One train's speed from another changes."], ["Boats", "Water current changes relative motion."], ["Games", "Camera motion changes apparent speed."]], "A is 5 m/s east, B is 2 m/s east. Relative speed?", "3", "Subtract same-direction speeds.", "numeric"),
  s(197, "Force Vectors", "force-vectors", "Force vectors show push or pull with magnitude and direction.", "Add force vectors by components to find the resultant force.", ["FORCE_SIZE_ONLY", "Ignoring direction of a force.", "Force is a vector, so direction matters."], "F_result=sum F_i", ["For forces (3,0) and (0,4), find resultant magnitude.", ["Add to get (3,4).", "Magnitude is sqrt(9+16).", "Result is 5."], "5"], [["Pushing", "Two people can push in different directions."], ["Bridges", "Loads act as force vectors."], ["Sports", "A kicked ball feels force direction."]], "For forces (3,0) and (0,4), what is resultant magnitude?", "5", "Add, then find magnitude.", "numeric"),
];

export const vectorStrengthenedLessons: Record<number, StrengthenedLesson> = Object.fromEntries(seeds.map((seed) => [seed.id, build(seed)]));
export const vectorStrengthenedChallenges: Record<number, Challenge> = Object.fromEntries(seeds.map((seed) => [seed.id, seed.challenge]));

function s(id: number, title: string, slug: string, definition: string, rule: string, mistake: [string, string, string], formula: string, worked: [string, string[], string], examples: [string, string][], prompt: string, expected: string, hint: string, kind: Challenge["kind"]): Seed {
  return { id, title, slug, definition, rule, mistake, formula, worked, examples, challenge: { prompt, expected, hint, kind, factoryId: `vector.${slug}` } };
}

function build(seed: Seed): StrengthenedLesson {
  return {
    id: seed.id,
    title: seed.title,
    route: `/lessons/geometry/${seed.id}-${seed.slug}`,
    category: "Geometry",
    topic: "Vectors",
    lessonType: "visual_exploration",
    learningObjectives: [`Define ${seed.title}.`, `Use a vector diagram for ${seed.title}.`, `Correct a common ${seed.title} mistake.`],
    prerequisites: ["Coordinate plane", "Signed numbers", "Basic algebra"],
    keyVocabulary: [{ term: seed.title, meaning: seed.definition }, { term: "Component", meaning: "One coordinate part of a vector." }],
    introduction: `${seed.title} is a vector idea about size, direction, or components. It helps describe movement, force, and position in daily life.`,
    basicIdea: `${seed.rule} We see this in maps, motion, computer graphics, and forces. The scientific reason is that vectors keep direction and size together. A common mistake is ${seed.mistake[1]}`,
    howItWorks: "Read the components. Apply the vector rule. Check the direction and magnitude.",
    whyItWorks: "Vector rules work because horizontal and vertical parts can be calculated separately, then combined.",
    definitions: [{ id: `${seed.slug}-definition`, statement: seed.definition }],
    facts: [{ id: `${seed.slug}-fact`, statement: seed.rule }],
    formulas: [{ id: `${seed.slug}-formula`, label: seed.title, expression: seed.formula, variables: [{ symbol: "v", meaning: "a vector" }], exactness: "definition" }],
    conditionsAndRestrictions: ["Keep component order fixed.", "Check whether the answer is a scalar or a vector."],
    representations: [{ id: `${seed.slug}-diagram`, type: "vector_diagram", learningPurpose: `Show ${seed.title} with arrows and components.` }],
    workedExamples: [{ id: `${seed.slug}-worked`, prompt: seed.worked[0], steps: seed.worked[1], answer: seed.worked[2] }],
    realLifeExamples: seed.examples.map(([context, connection], index) => ({ id: `${seed.slug}-real-${index + 1}`, context, connection })),
    misconceptions: [{ code: seed.mistake[0], mistake: seed.mistake[1], correction: seed.mistake[2] }],
    interaction: { id: `${seed.slug}-interaction`, learningPurpose: `Connect vector arrows to ${seed.title}.`, parameters: [{ id: "u", label: "Vector u" }, { id: "v", label: "Vector v" }], initialState: "Start with two visible vectors.", dynamicFeedback: `Show the computed result for ${seed.title}.`, successCriteria: ["Reads components correctly", "Explains direction and size"], accessibilityAlternative: "Read vector components and computed values as text." },
    guidedExploration: [{ id: "predict", prompt: "Predict the result before moving a vector." }, { id: "observe", prompt: "Move a component and read the new result." }],
    practice: ["recognition", "direct", "multi_step", "error_diagnosis", "transfer"].map((difficulty, index) => ({ id: `${seed.slug}-${difficulty}`, prompt: `Practice ${seed.title}.`, answer: [seed.worked[2], seed.challenge.expected, seed.formula, seed.mistake[2], seed.examples[0][0]][index], hints: ["Read components.", "Use the rule.", "Check units and direction."], workedSolution: seed.worked[1], misconceptionTag: seed.mistake[0], difficulty: difficulty as StrengthenedLesson["practice"][number]["difficulty"], parameterConstraints: ["Use small integer components."] })),
    challenge: { id: `${seed.slug}-challenge`, prompt: seed.challenge.prompt, successCriteria: ["Uses vector components", "Gives correct result"], hints: [seed.challenge.hint] },
    exitCheck: [{ id: `${seed.slug}-exit`, prompt: `State one rule for ${seed.title}.`, answer: seed.rule, criterion: "Names a vector-specific rule." }],
    accessibilityNotes: ["Announce vector components and result.", "Do not rely only on arrow colour."],
    expertReviewRequired: false,
  };
}
