import { normalCdf, normalQuantile, normalSurvival } from "./statistics";

export type DistributionId = "bernoulli" | "binomial" | "geometric" | "poisson" | "continuous-uniform" | "normal" | "exponential" | "lognormal";
export type DistributionRequest = { id: DistributionId; parameters: Record<string, number> };
export type DistributionEvaluation = { id: DistributionId; valid: boolean; support: string; pmf?: (x: number) => number; pdf?: (x: number) => number; cdf: (x: number) => number; survival: (x: number) => number; logProbability: (x: number) => number; quantile: (p: number) => number; mean: number; variance: number; warnings: string[]; numericalMethod: string; precision: number };

export const phase4DistributionRegistry: Array<{ id: DistributionId; parameters: string[]; support: string }> = [
  { id: "bernoulli", parameters: ["p"], support: "{0,1}" }, { id: "binomial", parameters: ["n", "p"], support: "{0,…,n}" }, { id: "geometric", parameters: ["p"], support: "{1,2,…}" }, { id: "poisson", parameters: ["lambda"], support: "{0,1,2,…}" },
  { id: "continuous-uniform", parameters: ["a", "b"], support: "[a,b]" }, { id: "normal", parameters: ["mu", "sigma"], support: "ℝ" }, { id: "exponential", parameters: ["lambda"], support: "[0,∞)" }, { id: "lognormal", parameters: ["mu", "sigma"], support: "(0,∞)" },
];

export function createDistribution(request: DistributionRequest): DistributionEvaluation {
  const p = request.parameters;
  if (request.id === "normal") { const mu = p.mu ?? 0; const sigma = p.sigma ?? 1; if (!(sigma > 0)) return invalid(request.id, "σ must be positive."); return { id: request.id, valid: true, support: "ℝ", pdf: (x) => Math.exp(-0.5 * ((x - mu) / sigma) ** 2) / (sigma * Math.sqrt(2 * Math.PI)), cdf: (x) => normalCdf((x - mu) / sigma), survival: (x) => normalSurvival((x - mu) / sigma), logProbability: (x) => -Math.log(sigma * Math.sqrt(2 * Math.PI)) - 0.5 * ((x - mu) / sigma) ** 2, quantile: (q) => mu + sigma * normalQuantile(q), mean: mu, variance: sigma ** 2, warnings: [], numericalMethod: "erfc tail + bracketed inverse CDF", precision: 12 }; }
  if (request.id === "exponential") { const lambda = p.lambda; if (!(lambda > 0)) return invalid(request.id, "λ must be positive."); return { id: request.id, valid: true, support: "[0,∞)", pdf: (x) => x < 0 ? 0 : lambda * Math.exp(-lambda * x), cdf: (x) => x < 0 ? 0 : -Math.expm1(-lambda * x), survival: (x) => x < 0 ? 1 : Math.exp(-lambda * x), logProbability: (x) => x < 0 ? -Infinity : Math.log(lambda) - lambda * x, quantile: (q) => -Math.log1p(-q) / lambda, mean: 1 / lambda, variance: 1 / lambda ** 2, warnings: [], numericalMethod: "expm1/log1p stable closed form", precision: 15 }; }
  if (request.id === "continuous-uniform") { const a = p.a; const b = p.b; if (!(b > a)) return invalid(request.id, "b must exceed a."); return { id: request.id, valid: true, support: `[${a},${b}]`, pdf: (x) => x >= a && x <= b ? 1 / (b - a) : 0, cdf: (x) => x <= a ? 0 : x >= b ? 1 : (x - a) / (b - a), survival: (x) => x <= a ? 1 : x >= b ? 0 : (b - x) / (b - a), logProbability: (x) => x >= a && x <= b ? -Math.log(b - a) : -Infinity, quantile: (q) => a + q * (b - a), mean: (a + b) / 2, variance: (b - a) ** 2 / 12, warnings: [], numericalMethod: "stable closed form", precision: 15 }; }
  if (request.id === "lognormal") { const mu = p.mu ?? 0; const sigma = p.sigma ?? 1; if (!(sigma > 0)) return invalid(request.id, "σ must be positive."); const normal = createDistribution({ id: "normal", parameters: { mu, sigma } }); return { id: request.id, valid: true, support: "(0,∞)", pdf: (x) => x <= 0 ? 0 : Math.exp(-((Math.log(x) - mu) ** 2) / (2 * sigma ** 2)) / (x * sigma * Math.sqrt(2 * Math.PI)), cdf: (x) => x <= 0 ? 0 : normal.cdf(Math.log(x)), survival: (x) => x <= 0 ? 1 : normal.survival(Math.log(x)), logProbability: (x) => x <= 0 ? -Infinity : -Math.log(x * sigma * Math.sqrt(2 * Math.PI)) - ((Math.log(x) - mu) ** 2) / (2 * sigma ** 2), quantile: (q) => Math.exp(normal.quantile(q)), mean: Math.exp(mu + sigma ** 2 / 2), variance: Math.expm1(sigma ** 2) * Math.exp(2 * mu + sigma ** 2), warnings: [], numericalMethod: "log-domain normal transform", precision: 12 }; }
  if (request.id === "bernoulli") { const probability = p.p; if (!(probability >= 0 && probability <= 1)) return invalid(request.id, "p must lie in [0,1]."); const pmf = (x: number) => x === 1 ? probability : x === 0 ? 1 - probability : 0; return discrete(request.id, "{0,1}", pmf, (x) => x < 0 ? 0 : x < 1 ? 1 - probability : 1, (q) => q <= 1 - probability ? 0 : 1, probability, probability * (1 - probability)); }
  if (request.id === "binomial") { const n = Math.floor(p.n); const probability = p.p; if (!(n >= 0 && probability >= 0 && probability <= 1)) return invalid(request.id, "n must be a non-negative integer and p must lie in [0,1]."); const pmf = (x: number) => Number.isInteger(x) && x >= 0 && x <= n ? combination(n, x) * probability ** x * (1 - probability) ** (n - x) : 0; const cdf = (x: number) => sumRange(0, Math.min(n, Math.floor(x)), pmf); return discrete(request.id, `{0,…,${n}}`, pmf, cdf, (q) => inverseDiscrete(q, 0, n, cdf), n * probability, n * probability * (1 - probability)); }
  if (request.id === "geometric") { const probability = p.p; if (!(probability > 0 && probability <= 1)) return invalid(request.id, "p must lie in (0,1]."); const pmf = (x: number) => Number.isInteger(x) && x >= 1 ? (1 - probability) ** (x - 1) * probability : 0; const cdf = (x: number) => x < 1 ? 0 : 1 - (1 - probability) ** Math.floor(x); return discrete(request.id, "{1,2,…}", pmf, cdf, (q) => Math.ceil(Math.log1p(-q) / Math.log1p(-probability)), 1 / probability, (1 - probability) / probability ** 2); }
  const lambda = p.lambda; if (!(lambda > 0)) return invalid(request.id, "λ must be positive."); const pmf = (x: number) => Number.isInteger(x) && x >= 0 ? Math.exp(-lambda + x * Math.log(lambda) - logFactorial(x)) : 0; const cdf = (x: number) => sumRange(0, Math.floor(x), pmf); return discrete(request.id, "{0,1,2,…}", pmf, cdf, (q) => inverseDiscrete(q, 0, Math.ceil(lambda + 12 * Math.sqrt(lambda) + 20), cdf), lambda, lambda);
}

function discrete(id: DistributionId, support: string, pmf: (x: number) => number, cdf: (x: number) => number, quantile: (p: number) => number, mean: number, variance: number): DistributionEvaluation { return { id, valid: true, support, pmf, cdf, survival: (x) => Math.max(0, 1 - cdf(x)), logProbability: (x) => Math.log(pmf(x)), quantile, mean, variance, warnings: [], numericalMethod: "log-domain PMF with cumulative summation", precision: 12 }; }
function invalid(id: DistributionId, warning: string): DistributionEvaluation { return { id, valid: false, support: "invalid", cdf: () => Number.NaN, survival: () => Number.NaN, logProbability: () => Number.NaN, quantile: () => Number.NaN, mean: Number.NaN, variance: Number.NaN, warnings: [warning], numericalMethod: "not run", precision: 0 }; }
function combination(n: number, k: number) { const r = Math.min(k, n - k); let result = 1; for (let i = 1; i <= r; i += 1) result = result * (n - r + i) / i; return result; }
function logFactorial(n: number) { let result = 0; for (let i = 2; i <= n; i += 1) result += Math.log(i); return result; }
function sumRange(start: number, end: number, fn: (x: number) => number) { let sum = 0; for (let x = start; x <= end; x += 1) sum += fn(x); return Math.min(1, Math.max(0, sum)); }
function inverseDiscrete(p: number, start: number, end: number, cdf: (x: number) => number) { for (let x = start; x <= end; x += 1) if (cdf(x) >= p) return x; return end; }
