import { summarize } from "./dataframe";
import type { Dataset, InferenceResult, LinearModelResult, ModelDiagnostic } from "./types";

export function fitSimpleLinearRegression(dataset: Dataset, outcomeId: string, predictorId: string, confidenceLevel = 0.95): LinearModelResult {
  const values = dataset.rows.map((row, index) => ({ row: index, rawX: row[predictorId], rawY: row[outcomeId] })).filter((item) => item.rawX !== null && item.rawX !== "" && item.rawY !== null && item.rawY !== "").map((item) => ({ row: item.row, x: Number(item.rawX), y: Number(item.rawY) })).filter((item) => Number.isFinite(item.x) && Number.isFinite(item.y));
  if (values.length < 3) return unsupportedModel(outcomeId, predictorId, "At least three complete numeric rows are required.");
  const n = values.length; const meanX = values.reduce((sum, item) => sum + item.x, 0) / n; const meanY = values.reduce((sum, item) => sum + item.y, 0) / n; const sxx = values.reduce((sum, item) => sum + (item.x - meanX) ** 2, 0); const sxy = values.reduce((sum, item) => sum + (item.x - meanX) * (item.y - meanY), 0);
  if (sxx === 0) return unsupportedModel(outcomeId, predictorId, "Predictor has zero variance.");
  const slope = sxy / sxx; const intercept = meanY - slope * meanX; const raw = values.map((item) => ({ ...item, fitted: intercept + slope * item.x, leverage: 1 / n + (item.x - meanX) ** 2 / sxx })).map((item) => ({ ...item, residual: item.y - item.fitted })); const sse = raw.reduce((sum, item) => sum + item.residual ** 2, 0); const syy = values.reduce((sum, item) => sum + (item.y - meanY) ** 2, 0); const sigma = Math.sqrt(sse / (n - 2)); const seSlope = sigma / Math.sqrt(sxx); const seIntercept = sigma * Math.sqrt(1 / n + meanX ** 2 / sxx); const slopeT = slope / seSlope; const interceptT = intercept / seIntercept; const critical = normalQuantile(0.5 + confidenceLevel / 2); const residuals = raw.map((item) => { const standardizedResidual = sigma ? item.residual / (sigma * Math.sqrt(Math.max(1e-12, 1 - item.leverage))) : 0; const cooksDistance = standardizedResidual ** 2 * item.leverage / (2 * Math.max(1e-12, 1 - item.leverage)); return { row: item.row, observed: item.y, fitted: item.fitted, residual: item.residual, standardizedResidual, leverage: item.leverage, cooksDistance }; });
  const diagnostics: ModelDiagnostic[] = [
    { id: "linearity", label: "Linearity", status: correlation(values.map((item) => item.x), residuals.map((item) => item.residual)) < 0.2 ? "PASS" : "WARN", detail: "Residual–predictor correlation is used as a compact diagnostic; inspect the residual plot." },
    { id: "variance", label: "Constant variance", status: varianceRatio(residuals.map((item) => item.residual)) < 4 ? "PASS" : "WARN", detail: "Compares residual spread across fitted-value halves." },
    { id: "normality", label: "Residual normality", status: Math.abs(summarize(residuals.map((item) => item.residual)).skewness ?? 0) < 1 ? "PASS" : "WARN", detail: "Residual skewness is a screening diagnostic, not a formal proof of normality." },
    { id: "influence", label: "Influential observations", status: residuals.some((item) => item.cooksDistance > 4 / n) ? "WARN" : "PASS", detail: "Cook’s distance is compared with the 4/n screening threshold." },
    { id: "independence", label: "Independence", status: "WARN", detail: "Independence depends on study design and cannot be established from these columns alone." },
  ];
  const coefficient = (term: string, estimate: number, standardError: number, statistic: number) => ({ term, estimate, standardError, statistic, pValue: 2 * normalSurvival(Math.abs(statistic)), confidenceInterval: [estimate - critical * standardError, estimate + critical * standardError] as [number, number] });
  return { status: "COMPLETE", outcome: outcomeId, predictors: [predictorId], equation: `${outcomeId} = ${intercept} + ${slope}·${predictorId}`, coefficients: [coefficient("intercept", intercept, seIntercept, interceptT), coefficient(predictorId, slope, seSlope, slopeT)], r2: syy ? 1 - sse / syy : 1, adjustedR2: 1 - (1 - (syy ? 1 - sse / syy : 1)) * (n - 1) / (n - 2), residualStandardError: sigma, residuals, diagnostics, confidenceLevel, trainingRows: values.map((item) => item.row), limitations: ["Association does not establish causation.", "Normal-reference p-values are approximations; inspect assumptions and study design."] };
}

export function twoSampleComparison(dataset: Dataset, outcomeId: string, groupId: string, groupA: string, groupB: string, confidenceLevel = 0.95): InferenceResult {
  const valuesFor = (group: string) => dataset.rows.filter((row) => String(row[groupId]) === group && row[outcomeId] !== null && row[outcomeId] !== "").map((row) => Number(row[outcomeId])).filter(Number.isFinite);
  const a = valuesFor(groupA); const b = valuesFor(groupB);
  if (a.length < 2 || b.length < 2) return { method: "Welch two-sample t-test", nullHypothesis: `μ(${groupA})-μ(${groupB})=0`, alternativeHypothesis: `μ(${groupA})-μ(${groupB})≠0`, statistic: Number.NaN, referenceDistribution: "Student t", pValue: Number.NaN, confidenceInterval: [Number.NaN, Number.NaN], effectSize: { name: "Hedges g", value: Number.NaN }, assumptions: [{ id: "sample-size", label: "Sample size", status: "FAIL", detail: "Each group requires at least two complete observations." }], decision: "Method not run.", interpretation: "Insufficient data.", limitations: ["No inferential conclusion is available."], alternatives: [] };
  const sa = summarize(a); const sb = summarize(b); const meanA = sa.mean ?? 0; const meanB = sb.mean ?? 0; const varA = sa.variance ?? 0; const varB = sb.variance ?? 0; const se = Math.sqrt(varA / a.length + varB / b.length); const statistic = (meanA - meanB) / se; const numerator = (varA / a.length + varB / b.length) ** 2; const denominator = (varA / a.length) ** 2 / (a.length - 1) + (varB / b.length) ** 2 / (b.length - 1); const df = numerator / denominator; const pValue = 2 * normalSurvival(Math.abs(statistic)); const critical = normalQuantile(0.5 + confidenceLevel / 2); const pooled = Math.sqrt(((a.length - 1) * varA + (b.length - 1) * varB) / (a.length + b.length - 2)); const d = pooled ? (meanA - meanB) / pooled : 0; const correction = 1 - 3 / (4 * (a.length + b.length) - 9); const effect = d * correction; const skewA = Math.abs(sa.skewness ?? 0); const skewB = Math.abs(sb.skewness ?? 0);
  const assumptions: ModelDiagnostic[] = [{ id: "independence", label: "Independent observations", status: "WARN", detail: "Must be justified by sampling or assignment; the dataset alone cannot verify it." }, { id: "shape", label: "Group distributions", status: skewA < 1 && skewB < 1 ? "PASS" : "WARN", detail: `Absolute skewness: ${skewA.toFixed(2)}, ${skewB.toFixed(2)}.` }, { id: "variance", label: "Equal variance", status: "NOT_APPLICABLE", detail: "Welch's method does not assume equal variances." }];
  return { method: "Welch two-sample t-test", nullHypothesis: `μ(${groupA})-μ(${groupB})=0`, alternativeHypothesis: `μ(${groupA})-μ(${groupB})≠0`, statistic, referenceDistribution: "Welch approximate Student t", degreesOfFreedom: df, pValue, confidenceInterval: [meanA - meanB - critical * se, meanA - meanB + critical * se], effectSize: { name: "Hedges g", value: effect }, assumptions, decision: pValue < 0.05 ? "Reject the null hypothesis at α=0.05." : "Fail to reject the null hypothesis at α=0.05.", interpretation: `Estimated mean difference is ${(meanA - meanB).toFixed(3)}; practical importance must be judged from the interval and effect size, not the p-value alone.`, limitations: ["This analysis does not prove the null hypothesis or establish causation.", "Normal-reference tail probability is an approximation for this compact offline implementation."], alternatives: skewA >= 1 || skewB >= 1 ? ["Permutation/randomization comparison", "Mann–Whitney comparison when its estimand is appropriate"] : ["Permutation/randomization comparison as a robustness check"] };
}

export function recommendMethod(input: { outcomeType: "NUMERIC" | "BINARY" | "CATEGORY"; groups: number; paired: boolean; independent: boolean; observational: boolean; sampleSize: number; severeSkew: boolean }) { const reasons: string[] = []; const warnings: string[] = []; let recommended: string[]; if (input.outcomeType === "NUMERIC" && input.groups === 2 && input.paired) { recommended = ["Paired t-test", "Paired permutation test"]; reasons.push("Two measurements are paired on the same unit."); } else if (input.outcomeType === "NUMERIC" && input.groups === 2) { recommended = [input.severeSkew || input.sampleSize < 20 ? "Permutation comparison" : "Welch two-sample t-test", "Bootstrap confidence interval"]; reasons.push("Numeric outcome with two independent groups."); } else if (input.outcomeType === "NUMERIC" && input.groups > 2) { recommended = ["One-way ANOVA", "Permutation ANOVA"]; reasons.push("Numeric outcome with more than two groups."); } else if (input.outcomeType === "BINARY") { recommended = ["Difference in proportions", "Fisher exact test for small counts"]; reasons.push("Binary outcome requires proportion-based methods."); } else { recommended = ["Chi-square independence test", "Exact/randomization alternative for sparse tables"]; reasons.push("Both variables are categorical."); } if (!input.independent) warnings.push("Independence is not established; use a design-aware or paired method."); if (input.observational) warnings.push("Observational association does not identify a causal effect without additional design assumptions."); return { recommended, alternatives: recommended.slice(1), reasons, requiredDiagnostics: ["Study design", "Missingness", "Distribution/expected counts", "Outliers or influential cases"], warnings, ruleVersion: "1.0.0" }; }

export function normalCdf(z: number) { return 0.5 * erfc(-z / Math.SQRT2); }
export function normalSurvival(z: number) { return 0.5 * erfc(z / Math.SQRT2); }
export function normalQuantile(p: number) { if (!(p > 0 && p < 1)) return p === 0 ? -Infinity : p === 1 ? Infinity : Number.NaN; let low = -10; let high = 10; for (let i = 0; i < 100; i += 1) { const mid = (low + high) / 2; if (normalCdf(mid) < p) low = mid; else high = mid; } return (low + high) / 2; }
function correlation(a: number[], b: number[]) { const n = Math.min(a.length, b.length); const ma = a.reduce((x, y) => x + y, 0) / n; const mb = b.reduce((x, y) => x + y, 0) / n; const top = a.slice(0, n).reduce((sum, value, index) => sum + (value - ma) * (b[index] - mb), 0); const aa = a.slice(0, n).reduce((sum, value) => sum + (value - ma) ** 2, 0); const bb = b.slice(0, n).reduce((sum, value) => sum + (value - mb) ** 2, 0); return aa && bb ? Math.abs(top / Math.sqrt(aa * bb)) : 0; }
function varianceRatio(values: number[]) { const half = Math.floor(values.length / 2); const first = summarize(values.slice(0, half)).variance ?? 0; const second = summarize(values.slice(half)).variance ?? 0; return Math.max(first, second) / Math.max(1e-12, Math.min(first, second)); }
function unsupportedModel(outcome: string, predictor: string, reason: string): LinearModelResult { return { status: "UNSUPPORTED", outcome, predictors: [predictor], equation: "Unavailable", coefficients: [], r2: Number.NaN, adjustedR2: Number.NaN, residualStandardError: Number.NaN, residuals: [], diagnostics: [{ id: "model", label: "Model eligibility", status: "FAIL", detail: reason }], confidenceLevel: 0.95, trainingRows: [], limitations: [reason] }; }
function erfc(x: number) { const z = Math.abs(x); const t = 1 / (1 + z / 2); const result = t * Math.exp(-z * z - 1.26551223 + t * (1.00002368 + t * (0.37409196 + t * (0.09678418 + t * (-0.18628806 + t * (0.27886807 + t * (-1.13520398 + t * (1.48851587 + t * (-0.82215223 + t * 0.17087277))))))))); return x >= 0 ? result : 2 - result; }
